const fs = require('fs');

const fixes = {
    'sr': {
        'Warum balancieren Seiltänzer oft mit einer extrem langen und schweren Stange?': 'Zašto plesači na žici često balansiraju sa ekstremno dugačkom i teškom šipkom?',
        'Die Stange verlagert den Schwerpunkt nach unten und außen, was sie viel stabiler macht.': 'Šipka pomera težište naniže i ka spolja, što ih čini mnogo stabilnijim.',
        'Damit man nicht so nah an der dreckigen Schraube stehen muss.': 'Da ne biste morali stajati tako blizu prljavog zavrtnja.',
        'Ein langer Griff vergrößert den Abstand zum Drehpunkt, wodurch das Drehmoment steigt (man braucht weniger Kraft).': 'Dugačka drška povećava rastojanje od obrtne tačke, čime se povećava obrtni moment (potrebno je manje sile).',
        'Eine Schüssel. Die Murmel liegt ganz unten.': 'Činija. Kliker leži na samom dnu.',
        'Ein Besen, den du hochkant auf deinem Finger balancierst, befindet sich in welchem Gleichgewicht?': 'Metla koju balansirate uspravno na prstu nalazi se u kojoj ravnoteži?',
        'Labil. Ein kleiner Wackler, und er fällt um!': 'Labilna. Mali potres i ona pada!',
        'Stabil. Er springt von alleine auf den Finger zurück.': 'Stabilna. Sama se vraća na prst.',
        'Fährt das Auto schnell in eine scharfe Linkskurve, wirst du in deinen Sitz nach rechts gedrückt. Dein Körper will nämlich geradeaus weiter, aber das Auto biegt unter dir ab!': 'Kada auto brzo uđe u oštru levu krivinu, bivate gurnuti u sedištu udesno. Vaše telo želi da nastavi pravo, ali auto skreće ispod vas!',
        'Was passiert mit der Fliehkraft, wenn sich das Karussell doppelt so schnell dreht?': 'Šta se dešava sa centrifugalnom silom ako se vrteška okreće duplo brže?',
        'Sie wird schwächer, weil der Fahrtwind dagegen drückt.': 'Postaje slabija jer vetar pritiska nasuprot.',
        'Sie wird VIEL stärker! Wer sich schneller dreht, wird stärker nach außen gedrückt.': 'Postaje MNOGO jača! Ko se brže okreće, biva jače gurnut ka spolja.',
        'Warum breitet eine Tänzerin nach einer schnellen Pirouette die Arme aus?': 'Zašto plesačica širi ruke nakon brze piruete?',
        'Um durch die Masseverlagerung nach außen die Drehung abzubremsen.': 'Da bi usporila rotaciju pomeranjem mase ka spolja.',
        'Um mehr Luft einzuatmen, weil ihr schwindelig ist.': 'Da bi udahnula više vazduha jer joj se vrti u glavi.',
        '1. Was ist der "Schwerpunkt" eines Gegenstands?': '1. Šta je "težište" nekog predmeta?',
        'Der gedachte Punkt, an dem die gesamte Masse/Schwerkraft ausbalanciert ist.': 'Zamišljena tačka u kojoj je čitava masa/gravitacija izbalansirana.',
        '2. Wo liegt der Schwerpunkt bei einem hohlen Reifen?': '2. Gde se nalazi težište kod šuplje gume?',
        'Exakt in der Mitte im Loch.': 'Tačno u sredini u rupi.',
        '3. Ein Turm aus Bauklötzen fällt um, sobald...': '3. Toranj od kockica pada čim...',
        '...er höher als 1 Meter ist.': '...postane viši od 1 metra.',
        '...sein Schwerpunkt nicht mehr über der Grundfläche (dem untersten Klotz) liegt.': '...njegovo težište više nije iznad osnovne površine (najniže kocke).',
        '4. Wie berechnet man das "Drehmoment"?': '4. Kako se izračunava "obrtni moment"?',
        '5. Wenn du ein festsitzendes Glasrad an einem Ventil drehen willst, fasst du wo an?': '5. Ako želite da okrenete zaglavljeni stakleni točak na ventilu, gde ćete ga uhvatiti?',
        'Ganz nah an der Schraube in der Mitte.': 'Veoma blizu zavrtnja u sredini.',
        '6. Eine Murmel in einer tiefen Schale ist ein Beispiel für...': '6. Kliker u dubokoj činiji je primer za...',
        '7. Ein Stift, der hochkant auf seiner spitzen Mine steht (und beim kleinsten Hauch umfällt), ist im...': '7. Olovka koja stoji uspravno na svom špicu (i pada na najmanji povetarac) je u...',
        '8. Ein Fußball liegt auf dem platten Rasen. Er rollt ein Stück und bleibt einfach wieder liegen. Welches Gleichgewicht?': '8. Fudbalska lopta leži na ravnoj travi. Otkotrlja se malo i jednostavno ponovo ostane da leži. Koja ravnoteža?',
        '9. Wie nennt man die Kraft, die dich im Kettenkarussell nach außen zieht?': '9. Kako se zove sila koja vas u vrtešci vuče ka spolja?',
        'Wegen der Trägheit: Dein Körper will geradeaus, wird aber auf eine Kreisbahn gezwungen.': 'Zbog inercije: Vaše telo želi pravo, ali je primorano na kružnu putanju.',
        'Weil der Wind von der Mitte des Karussells weht.': 'Zato što vetar duva iz centra vrteške.',
        '11. Eine Waschmaschine schleudert die Wäsche rasend schnell. Warum wird die Wäsche trocken?': '11. Mašina za pranje veša centrifugira veš veoma brzo. Zašto veš postaje suv?',
        'Die Fliehkraft drückt das Wasser aus der Wäsche durch die Löcher in der Trommel nach außen.': 'Centrifugalna sila potiskuje vodu iz veša kroz rupe u bubnju ka spolja.',
        '12. Was ist der "Pirouetteneffekt"?': '12. Šta je "efekat piruete"?',
        'Dass man sich schneller dreht, wenn man die Masse (Arme) zur Drehachse heranzieht.': 'Da se brže okrećete kada privučete masu (ruke) osi rotacije.',
        'Dass man durch Drehen einen lustigen Hut verliert.': 'Da se usled rotacije izgubi smešan šešir.',
        '13. Du sitzt auf einem drehbaren Bürostuhl, rotierst und streckst plötzlich die Beine aus. Was passiert?': '13. Sedite na okretnoj kancelarijskoj stolici, rotirate i iznenada ispružite noge. Šta se dešava?',
        '14. Wie können Helikopter verhindern, dass sich der ganze Hubschrauber wie ein Kreisel mit dem Rotor mitdreht?': '14. Kako helikopteri sprečavaju da se čitav helikopter okreće kao čigra zajedno sa rotorom?',
        'Sie hängen schwere Gewichte an die Seiten.': 'Kače teške tegove sa strana.',
        'Sie haben einen kleinen Heckrotor hinten, der ein Gegendrehmoment erzeugt.': 'Imaju mali repni rotor pozadi koji stvara suprotni obrtni moment.',
        '15. Eine Person sitzt auf einer Wippe genau auf dem Drehpunkt. Erzeugt sie ein Drehmoment?': '15. Osoba sedi na klackalici tačno na obrtnoj tački. Da li ona stvara obrtni moment?',
        'Nein, weil der Abstand zum Drehpunkt Null ist (Kraft x 0 = 0).': 'Ne, jer je rastojanje od obrtne tačke nula (sila x 0 = 0).',
        'Ja, ein sehr großes, weil sie in der Mitte ist.': 'Da, veoma veliki, jer je u sredini.',
        'Puh! Extrem anstrengend. Der Hebelarm ist winzig, das Drehmoment reicht kaum aus!': 'Uh! Ekstremno naporno. Krak poluge je sićušan, obrtni moment jedva da je dovoljan!',
        'Es geht schon besser, aber du brauchst immer noch ziemlich viel Muskelkraft.': 'Ide već bolje, ali vam je i dalje potrebno dosta snage mišića.',
        'Perfekt! Du drückst ganz außen. Der lange Hebelarm erzeugt ein riesiges Drehmoment!': 'Savršeno! Pritiskate sasvim spolja. Dug krak poluge stvara ogroman obrtni moment!',
        'Stabil: Du stupst sie an, sie rollt in die Mitte zurück und bleibt sicher liegen.': 'Stabilna: Gurnete je, ona se otkotrlja nazad u sredinu i sigurno ostane da leži.',
        'Labil: Ein kleiner Windhauch, und sie stürzt ab – und kommt nie wieder hoch!': 'Labilna: Mali povetarac i ona pada – i nikada se više ne vraća!',
        'Indifferent: Du stupst sie an, sie rollt ein Stückchen und bleibt genau dort liegen.': 'Indiferentna: Gurnete je, ona se malo otkotrlja i ostane da leži baš tamo.',
        'Arme angezogen: Die Masse ist nah der Drehachse. Das Drehen wird EXTREM SCHNELL!': 'Privučene ruke: Masa je blizu ose rotacije. Okretanje postaje EKSTREMNO BRZO!',
        'Arme draußen: Die Masse ist weit außen verteilt. Das Drehen wird stark gebremst.': 'Raširene ruke: Masa je raspoređena daleko spolja. Okretanje biva jako usporeno.'
    },
    'ar': {
        'Warum balancieren Seiltänzer oft mit einer extrem langen und schweren Stange?': 'لماذا يتوازن بهلوانيو الحبال غالباً بعصا طويلة وثقيلة للغاية؟',
        'Die Stange verlagert den Schwerpunkt nach unten und außen, was sie viel stabiler macht.': 'تزيح العصا مركز الثقل إلى الأسفل والخارج، مما يجعلها أكثر استقراراً.',
        'Damit man nicht so nah an der dreckigen Schraube stehen muss.': 'حتى لا تضطر للوقوف قريباً جداً من البرغي المتسخ.',
        'Ein langer Griff vergrößert den Abstand zum Drehpunkt, wodurch das Drehmoment steigt (man braucht weniger Kraft).': 'المقبض الطويل يزيد المسافة عن نقطة الارتكاز، مما يزيد من عزم الدوران (تحتاج قوة أقل).',
        'Eine Schüssel. Die Murmel liegt ganz unten.': 'وعاء. الرخامة تقع في الأسفل تماماً.',
        'Ein Besen, den du hochkant auf deinem Finger balancierst, befindet sich in welchem Gleichgewicht?': 'مكنسة توازنها رأسياً على إصبعك، في أي توازن تكون؟',
        'Labil. Ein kleiner Wackler, und er fällt um!': 'غير مستقر. اهتزاز صغير، ويسقط!',
        'Stabil. Er springt von alleine auf den Finger zurück.': 'مستقر. يعود إلى الإصبع من تلقاء نفسه.',
        'Fährt das Auto schnell in eine scharfe Linkskurve, wirst du in deinen Sitz nach rechts gedrückt. Dein Körper will nämlich geradeaus weiter, aber das Auto biegt unter dir ab!': 'إذا انعطفت السيارة بسرعة يساراً، فستُدفع في مقعدك نحو اليمين. جسمك يريد الاستمرار للأمام، لكن السيارة تنعطف من تحتك!',
        'Was passiert mit der Fliehkraft, wenn sich das Karussell doppelt so schnell dreht?': 'ماذا يحدث لقوة الطرد المركزي إذا دارت الأرجوحة بسرعة مضاعفة؟',
        'Sie wird schwächer, weil der Fahrtwind dagegen drückt.': 'تصبح أضعف لأن الرياح تضغط ضدها.',
        'Sie wird VIEL stärker! Wer sich schneller dreht, wird stärker nach außen gedrückt.': 'تصبح أقوى بكثير! من يدور أسرع يُدفع للخارج بقوة أكبر.',
        'Warum breitet eine Tänzerin nach einer schnellen Pirouette die Arme aus?': 'لماذا تفتح الراقصة ذراعيها بعد دوران سريع؟',
        'Um durch die Masseverlagerung nach außen die Drehung abzubremsen.': 'لإبطاء الدوران عن طريق إزاحة الكتلة للخارج.',
        'Um mehr Luft einzuatmen, weil ihr schwindelig ist.': 'لتنفس المزيد من الهواء لأنها تشعر بالدوار.',
        '1. Was ist der "Schwerpunkt" eines Gegenstands?': '1. ما هو "مركز الثقل" لشيء ما؟',
        'Der Punkt, der am dunkelsten aussieht.': 'النقطة التي تبدو الأكثر سواداً.',
        'Der gedachte Punkt, an dem die gesamte Masse/Schwerkraft ausbalanciert ist.': 'النقطة التخيلية التي تتوازن عندها الكتلة/الجاذبية بالكامل.',
        '2. Wo liegt der Schwerpunkt bei einem hohlen Reifen?': '2. أين يقع مركز الثقل في إطار مجوف؟',
        'Exakt in der Mitte im Loch.': 'في منتصف الفتحة تماماً.',
        '3. Ein Turm aus Bauklötzen fällt um, sobald...': '3. يسقط برج من المكعبات بمجرد...',
        '...er höher als 1 Meter ist.': '...أن يتجاوز ارتفاعه متراً واحداً.',
        '...sein Schwerpunkt nicht mehr über der Grundfläche (dem untersten Klotz) liegt.': '...أن يخرج مركز ثقله عن القاعدة (المكعب السفلي).',
        '4. Wie berechnet man das "Drehmoment"?': '4. كيف يتم حساب "عزم الدوران"؟',
        '5. Wenn du ein festsitzendes Glasrad an einem Ventil drehen willst, fasst du wo an?': '5. إذا أردت تدوير عجلة زجاجية عالقة في صمام، فأين تمسكها؟',
        'Ganz nah an der Schraube in der Mitte.': 'قريب جداً من البرغي في المنتصف.',
        '6. Eine Murmel in einer tiefen Schale ist ein Beispiel für...': '6. الرخامة في وعاء عميق هي مثال على...',
        '7. Ein Stift, der hochkant auf seiner spitzen Mine steht (und beim kleinsten Hauch umfällt), ist im...': '7. قلم يقف رأسياً على سنه (ويسقط عند أقل نسمة)، يكون في...',
        '8. Ein Fußball liegt auf dem platten Rasen. Er rollt ein Stück und bleibt einfach wieder liegen. Welches Gleichgewicht?': '8. كرة قدم على العشب المستوي. تتدحرج قليلاً ثم تتوقف. أي توازن هذا؟',
        '9. Wie nennt man die Kraft, die dich im Kettenkarussell nach außen zieht?': '9. ما اسم القوة التي تسحبك للخارج في الأرجوحة الدوارة؟',
        'Wegen der Trägheit: Dein Körper will geradeaus, wird aber auf eine Kreisbahn gezwungen.': 'بسبب القصور الذاتي: جسمك يريد الذهاب للأمام، لكنه يُجبر على مسار دائري.',
        'Weil der Wind von der Mitte des Karussells weht.': 'لأن الرياح تهب من منتصف الأرجوحة.',
        '11. Eine Waschmaschine schleudert die Wäsche rasend schnell. Warum wird die Wäsche trocken?': '11. الغسالة تدور بسرعة كبيرة. لماذا تجف الملابس؟',
        'Die Fliehkraft drückt das Wasser aus der Wäsche durch die Löcher in der Trommel nach außen.': 'قوة الطرد المركزي تدفع الماء من الملابس للخارج عبر فتحات الحلة.',
        '12. Was ist der "Pirouetteneffekt"?': '12. ما هو "تأثير الدوران المحوري"؟',
        'Dass man sich schneller dreht, wenn man die Masse (Arme) zur Drehachse heranzieht.': 'أنك تدور أسرع إذا قربت الكتلة (الذراعين) من محور الدوران.',
        'Dass man durch Drehen einen lustigen Hut verliert.': 'أن تفقد قبعة مضحكة بسبب الدوران.',
        '13. Du sitzt auf einem drehbaren Bürostuhl, rotierst und streckst plötzlich die Beine aus. Was passiert?': '13. تجلس على كرسي مكتب دوار، وتدور ثم تمد ساقيك فجأة. ماذا يحدث؟',
        '14. Wie können Helikopter verhindern, dass sich der ganze Hubschrauber wie ein Kreisel mit dem Rotor mitdreht?': '14. كيف تمنع المروحيات الطائرة من الدوران بالكامل مع المروحة؟',
        'Sie hängen schwere Gewichte an die Seiten.': 'يعلقون أثقالاً كبيرة على الجوانب.',
        'Sie haben einen kleinen Heckrotor hinten, der ein Gegendrehmoment erzeugt.': 'لديهم مروحة خلفية صغيرة تولد عزماً مضاداً.',
        '15. Eine Person sitzt auf einer Wippe genau auf dem Drehpunkt. Erzeugt sie ein Drehmoment?': '15. شخص يجلس على الأرجوحة في نقطة الارتكاز تماماً. هل يولد عزماً؟',
        'Nein, weil der Abstand zum Drehpunkt Null ist (Kraft x 0 = 0).': 'لا، لأن المسافة عن نقطة الارتكاز صفر (القوة × 0 = 0).',
        'Ja, ein sehr großes, weil sie in der Mitte ist.': 'نعم، كبير جداً لأنها في المنتصف.',
        'Puh! Extrem anstrengend. Der Hebelarm ist winzig, das Drehmoment reicht kaum aus!': 'أوف! متعب للغاية. ذراع الرافعة صغير جداً، وعزم الدوران بالكاد يكفي!',
        'Es geht schon besser, aber du brauchst immer noch ziemlich viel Muskelkraft.': 'الأمر أفضل الآن، لكنك لا تزال بحاجة للكثير من قوة العضلات.',
        'Perfekt! Du drückst ganz außen. Der lange Hebelarm erzeugt ein riesiges Drehmoment!': 'ممتاز! تضغط في الخارج تماماً. ذراع الرافعة الطويل يولد عزماً هائلاً!',
        'Stabil: Du stupst sie an, sie rollt in die Mitte zurück und bleibt sicher liegen.': 'مستقر: تنقرها، فتعود للمنتصف وتستقر بأمان.',
        'Labil: Ein kleiner Windhauch, und sie stürzt ab – und kommt nie wieder hoch!': 'غير مستقر: نسمة هواء صغيرة، وتسقط – ولا تعود أبداً!',
        'Indifferent: Du stupst sie an, sie rollt ein Stückchen und bleibt genau dort liegen.': 'محايد: تنقرها، فتتدحرج قليلاً وتتوقف في مكانها تماماً.',
        'Arme angezogen: Die Masse ist nah der Drehachse. Das Drehen wird EXTREM SCHNELL!': 'الذراعان مقربتان: الكتلة قريبة من محور الدوران. الدوران يصبح سريعاً للغاية!',
        'Arme draußen: Die Masse ist weit außen verteilt. Das Drehen wird stark gebremst.': 'الذراعان للخارج: الكتلة موزعة بعيداً. الدوران يتباطأ بشدة.'
    }
};

for (const lang of ['sr', 'ar']) {
    const f = `drehundstatik_${lang}.html`;
    if (!fs.existsSync(f)) continue;
    let content = fs.readFileSync(f, 'utf8');
    for (const [o, n] of Object.entries(fixes[lang])) {
        content = content.split(o).join(n);
    }
    fs.writeFileSync(f, content, 'utf8');
    console.log(`Deep fixed ${f}`);
}
