'use strict';
window.topicInit=function(){
 const zone=document.querySelector('[data-circulation-lab]');if(!zone||zone.dataset.initialized==='true')return;zone.dataset.initialized='true';
 // The route follows one cell. It does not animate the timing of the two heart halves.
 const stages=[
  ['Rechte Herzkammer','Das Blut wird aus der rechten Kammer Richtung Lunge gefördert.',['Körperarterien','Lungenarterien','Linke Herzkammer'],1,['Körperarterien erhalten Blut aus der linken Kammer. Hier beginnt der Weg zur Lunge.','Richtig: Arterien führen vom Herzen weg, auch wenn dieses Blut sauerstoffarm ist.','Die Herzscheidewand trennt beide Kammern. Der normale Weg führt zunächst durch die Lunge.']],
  ['Lungenarterien','Die Gefäße verzweigen sich auf dem Weg zum Gasaustausch.',['Lungenkapillaren','Lungenvenen','Körperkapillaren'],0,['Richtig: In den feinen Lungengefäßen kann das Blut Sauerstoff aufnehmen und Kohlenstoffdioxid abgeben.','Vor den Lungenvenen liegen im Schema die Austauschgefäße der Lunge.','Die Körperkapillaren werden später über das linke Herz erreicht.']],
  ['Lungenkapillaren','Das Blut hat hier Sauerstoff aufgenommen. Welche Gefäße führen zurück zum Herzen?',['Lungenarterien','Körpervenen','Lungenvenen'],2,['Die Arterien sind der Hinweg zur Lunge. Für den Rückweg suche Gefäße zum Herzen hin.','Körpervenen kommen aus den Körpergeweben, nicht aus der Lunge.','Richtig: Lungenvenen führen sauerstoffreiches Blut zum Herzen hin.']],
  ['Lungenvenen','Das Blut erreicht das linke Herz. Welcher Herzraum nimmt es zuerst auf?',['Rechter Vorhof','Linker Vorhof','Linke Herzkammer'],1,['Der rechte Vorhof nimmt Blut aus den Körpervenen auf.','Richtig: Die Lungenvenen münden in den linken Vorhof.','Vor der linken Kammer liegt im Blutweg der linke Vorhof.']],
  ['Linker Vorhof','Das Blut gelangt durch eine Herzklappe in die Kammer derselben Seite.',['Linke Herzkammer','Rechte Herzkammer','Lungenarterien'],0,['Richtig: Der linke Vorhof leitet Blut zur linken Kammer weiter.','Die Herzscheidewand trennt rechte und linke Seite.','Lungenarterien gehen von der rechten Kammer ab. Hier folgt zunächst die linke Kammer.']],
  ['Linke Herzkammer','Jetzt wird das Blut in den Körperkreislauf gefördert.',['Körpervenen','Lungenvenen','Körperarterien'],2,['Körpervenen bringen Blut aus dem Körper zum rechten Herzen zurück.','Lungenvenen bringen Blut von der Lunge zum linken Vorhof.','Richtig: Über die Aorta und weitere Körperarterien fließt Blut vom linken Herzen weg.']],
  ['Körperarterien','Die Gefäße verzweigen sich bis zu den Austauschflächen im Gewebe.',['Lungenkapillaren','Körperkapillaren','Rechter Vorhof'],1,['Die Lungenkapillaren werden erst nach dem Rückweg über das rechte Herz erreicht.','Richtig: Hier gelangen unter anderem Sauerstoff und Nährstoffe zum Gewebe.','Vor dem rechten Vorhof folgen noch Körperkapillaren und Körpervenen.']],
  ['Körperkapillaren','Nach dem Austausch im Gewebe fließt das Blut zum Herzen zurück.',['Körpervenen','Körperarterien','Lungenarterien'],0,['Richtig: Körpervenen führen zum rechten Herzen. Sauerstoffarm bedeutet nicht sauerstofffrei.','Körperarterien sind der Hinweg vom linken Herzen zum Gewebe.','Lungenarterien folgen erst nach dem Durchgang durch das rechte Herz.']],
  ['Körpervenen','Das Blut kommt zurück zum rechten Herzen. Welcher Raum nimmt es zuerst auf?',['Linker Vorhof','Rechte Herzkammer','Rechter Vorhof'],2,['Der linke Vorhof erhält Blut aus den Lungenvenen.','Vor der rechten Kammer liegt der rechte Vorhof.','Richtig: Die großen Körpervenen münden in den rechten Vorhof.']],
  ['Rechter Vorhof','Eine Klappe verbindet diesen Vorhof mit seiner Kammer.',['Linke Herzkammer','Rechte Herzkammer','Lungenkapillaren'],1,['Rechte und linke Seite sind normalerweise durch die Herzscheidewand getrennt.','Richtig: Zurück in der rechten Kammer ist die Runde durch beide Kreisläufe geschlossen.','Vor der Lunge folgen noch rechte Kammer und Lungenarterien.']]
 ];
 const current=zone.querySelector('[data-circulation-current]'),context=zone.querySelector('[data-circulation-context]'),options=zone.querySelector('[data-circulation-options]'),buttons=[...zone.querySelectorAll('[data-circulation-choice]')],feedback=zone.querySelector('[data-circulation-feedback]'),next=zone.querySelector('[data-circulation-next]');let index=0,answered=false;
 const render=focus=>{zone.dataset.step=String(index);answered=false;feedback.textContent='';delete feedback.dataset.correct;next.disabled=true;buttons.forEach(b=>b.removeAttribute('aria-pressed'));options.hidden=index===stages.length;
  if(index===stages.length){current.textContent='Runde abgeschlossen: zurück in der rechten Herzkammer';context.textContent='Du hast beide Kreisläufe verbunden. Erkläre jetzt ohne die Auswahlknöpfe, wo Sauerstoff ins Blut aufgenommen und ans Gewebe abgegeben wird.';next.hidden=true;}
  else{const s=stages[index];current.textContent=`Übergang ${index+1} von 10: ${s[0]}`;context.textContent=s[1];buttons.forEach((b,n)=>b.textContent=s[2][n]);next.hidden=false;}
  if(focus)current.focus();
 };
 buttons.forEach((b,choice)=>b.addEventListener('click',()=>{if(answered||index>=stages.length)return;const s=stages[index],correct=choice===s[3];feedback.dataset.correct=String(correct);feedback.textContent=s[4][choice];buttons.forEach((button,n)=>button.setAttribute('aria-pressed',String(n===choice)));if(correct){answered=true;next.disabled=false;}}));
 next.addEventListener('click',()=>{if(!answered||index>=stages.length)return;index++;render(true);});zone.querySelector('[data-circulation-reset]').addEventListener('click',()=>{index=0;render(false);buttons[0].focus();});render(false);
};
