function checkPyth1(){const input=document.getElementById('pyth1'),out=document.getElementById('fb_pyth1'),raw=input.value.trim(),value=/^\d+(?:[.,]\d+)?$/.test(raw)?Number(raw.replace(',','.')):NaN;out.textContent=!Number.isFinite(value)?'Gib die Länge als Zahl ein.':value===5?'Richtig! c² = 3² + 4² = 25 m². Daher c = √25 m = 5 m.':'Noch nicht richtig. Quadriere 3 und 4, addiere die Quadrate und ziehe dann die positive Quadratwurzel.';}


function topicInit(){const input=document.getElementById('pyth1');if(input){input.oninput=()=>document.getElementById('fb_pyth1').textContent='';input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();checkPyth1();}};}bindPythSpace();}
function pythSpaceModel(a,b,h){const floorSquared=a*a+b*b,spaceSquared=floorSquared+h*h;return{a,b,h,floorSquared,spaceSquared,floor:Math.sqrt(floorSquared),space:Math.sqrt(spaceSquared)};}
function bindPythSpace(){
 const lab=document.querySelector('[data-pyth-space]');if(!lab||lab.dataset.bound==='true')return;lab.dataset.bound='true';const controls=['a','b','h'].map(id=>lab.querySelector('#space-'+id)),input=lab.querySelector('#space-answer'),out=lab.querySelector('#space-status'),result=lab.querySelector('[data-space-result]'),model=()=>pythSpaceModel(...controls.map(c=>Number(c.value))),format=x=>x.toLocaleString('de-AT',{minimumFractionDigits:2,maximumFractionDigits:2});
 const clear=()=>{out.textContent='';result.replaceChildren();input.removeAttribute('aria-invalid');};
 const describe=()=>{clear();input.value='';const m=model();lab.querySelector('[data-space-description]').textContent='Modellquader: a = '+m.a+' cm, b = '+m.b+' cm, h = '+m.h+' cm. Im ersten Dreieck suchst du die Bodendiagonale e; im zweiten die Raumdiagonale d.';};
 const show=()=>{const m=model(),list=document.createElement('ol');for(const text of ['Bodendreieck: e² = '+m.a+'² + '+m.b+'² = '+m.floorSquared+' cm². Also e = √'+m.floorSquared+' cm ≈ '+format(m.floor)+' cm.','Schnittdreieck: d² = e² + h² = '+m.floorSquared+' + '+m.h+'² = '+m.spaceSquared+' cm². Also d = √'+m.spaceSquared+' cm ≈ '+format(m.space)+' cm.','Die zweite Rechnung verwendet e² direkt. Der gerundete Anzeigewert für e wird nicht eingesetzt.']){const li=document.createElement('li');li.textContent=text;list.append(li);}result.replaceChildren(list);};
 const check=()=>{clear();const raw=input.value.trim(),v=/^\d+(?:[.,]\d+)?$/.test(raw)?Number(raw.replace(',','.')):NaN;if(!Number.isFinite(v)||v<0||v>100){input.setAttribute('aria-invalid','true');out.textContent='Gib eine Länge von 0 bis 100 als Zahl in cm ein, zum Beispiel 13,00.';input.focus();return;}const m=model(),expected=Math.round(m.space*100)/100;out.textContent=(Math.abs(v-expected)<.005?'Richtig. ':'Noch nicht richtig. ')+'Die Raumdiagonale ist ungefähr '+format(expected)+' cm. Berechne zuerst e² und addiere danach h².';show();out.focus();};
 controls.forEach(c=>c.onchange=describe);input.oninput=clear;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check();}};lab.querySelector('[data-space-check]').onclick=check;lab.querySelector('[data-space-show]').onclick=()=>{clear();show();out.textContent='Beide rechtwinkligen Dreiecke sind berechnet. Vergleiche ihre Hypotenusen.';out.focus();};lab.querySelector('[data-space-reset]').onclick=()=>{controls.forEach((c,i)=>c.value=String([3,4,12][i]));describe();controls[0].focus();};describe();
}
