function check_m311() {
 const input=document.getElementById('ans_m311_2'),out=document.getElementById('res_m311_2');if(!input||!out)return;
 const raw=input.value.trim().replace(',', '.');
 if(!/^\d+(?:\.\d+)?$/.test(raw)||!Number.isFinite(Number(raw))){out.textContent='Gib einen nicht negativen Zahlenwert ein. Komma oder Punkt sind als Dezimaltrennzeichen möglich.';return;}
 out.textContent=Number(raw)===3?'Richtig: (2 + 4) : 2 = 3 Bücher pro Tag. Insgesamt sind es 6 Bücher an zwei Tagen.':Number(raw)===6?'6 Bücher ist die Summe. Für den Mittelwert musst du noch durch die Anzahl der zwei Tage teilen.':'Noch nicht: Addiere die beiden Ausleihzahlen 2 und 4 und teile ihre Summe durch die Anzahl der zwei Tage.';
}
function topicInit() {
 initStatisticsYear3();
 const input=document.getElementById('ans_m311_2'),out=document.getElementById('res_m311_2');if(!input||!out||input.dataset.bound==='true')return;
 input.dataset.bound='true';input.setAttribute('aria-describedby','res_m311_2');out.setAttribute('role','status');out.setAttribute('aria-live','polite');out.setAttribute('aria-atomic','true');
 input.addEventListener('input',()=>{out.textContent='';});input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();check_m311();}});input.closest('.interactive-zone').querySelector('button').onclick=check_m311;
}

function initStatisticsYear3(){
 const format=n=>n.toLocaleString('de-AT',{maximumFractionDigits:1}),element=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const svg=label=>{const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 360 280');s.setAttribute('role','img');s.setAttribute('aria-label',label);return s;};
 const add=(s,tag,attrs,text)=>{const n=document.createElementNS(s.namespaceURI,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;s.append(n);return n;};
 document.querySelectorAll('[data-stat3-axis]').forEach(zone=>{
  if(zone.dataset.ready)return;zone.dataset.ready='true';const select=zone.querySelector('select'),chart=zone.querySelector('[data-stat3-axis-chart]'),result=zone.querySelector('[data-stat3-axis-result]');
  chart.tabIndex=0;chart.setAttribute('role','region');chart.setAttribute('aria-label','Säulendiagramm; auf schmalen Bildschirmen seitlich verschiebbar');
  const render=()=>{const start=Number(select.value),y=v=>220-(v-start)*160/(60-start),s=svg('Erfundene Ausleihen: Tag A 40, Tag B 50. Achsenbeginn '+start+' Bücher.');add(s,'rect',{width:360,height:280,fill:'white'});add(s,'text',{x:20,y:25,fill:'#111827','font-size':17},'Ausgeliehene Bücher');for(const value of [start,(start+60)/2,60]){add(s,'line',{x1:50,y1:y(value),x2:335,y2:y(value),stroke:'#cbd5e1'});add(s,'text',{x:42,y:y(value)+5,'text-anchor':'end',fill:'#111827','font-size':16},value);}add(s,'path',{d:'M50 50V220H335',stroke:'#111827',fill:'none'});[40,50].forEach((value,i)=>{add(s,'rect',{x:90+i*130,y:y(value),width:65,height:220-y(value),fill:i?'#a85517':'#2563eb','data-stat3-bar':i});add(s,'text',{x:122.5+i*130,y:y(value)-8,'text-anchor':'middle',fill:'#111827','font-size':17},value);add(s,'text',{x:122.5+i*130,y:250,'text-anchor':'middle',fill:'#111827','font-size':17},'Tag '+(i?'B':'A'));});chart.replaceChildren(s);result.textContent='A: 40 Bücher; B: 50 Bücher. Unterschied: 10 Bücher, bezogen auf A 25 % mehr. Sichtbare Säulenlängen: '+(40-start)+' und '+(50-start)+' Einheiten; Verhältnis '+((50-start)/(40-start)).toLocaleString('de-AT',{maximumFractionDigits:2})+'. '+(start?'Die Skala ab 30 übertreibt den Unterschied beim Vergleich der Säulenlängen.':'Die Nullbasis zeigt das Verhältnis der Werte korrekt.');};select.addEventListener('change',render);render();
 });
 const models={six:{size:6,p:1/6,hit:n=>n===6,name:n=>'Augenzahl '+n,assumption:'Fairer Würfel, sechs gleich wahrscheinliche Augenzahlen. Treffer: 6. Unabhängige Wiederholungen; P(Treffer) = 1/6.'},even:{size:6,p:0.5,hit:n=>n%2===0,name:n=>'Augenzahl '+n,assumption:'Fairer Würfel, sechs gleich wahrscheinliche Augenzahlen. Treffer: 2, 4 oder 6. Unabhängige Wiederholungen; P(Treffer) = 3/6 = 1/2.'},coin:{size:2,p:0.5,hit:n=>n===1,name:n=>n===1?'Kopf':'Zahl',assumption:'Faire Münze mit den Ergebnissen Kopf und Zahl. Treffer: Kopf. Unabhängige Wiederholungen; P(Treffer) = 1/2.'},bag:{size:4,p:0.75,hit:n=>n<=3,name:n=>n<=3?'rote Kugel R'+n:'blaue Kugel B1',assumption:'Vier gleichartige Kugeln R1, R2, R3 und B1; jede Kugel gleich wahrscheinlich. Nach jedem Ziehen wird zurückgelegt und neu gemischt. Treffer: Rot. P(Treffer) = 3/4.'}};
 document.querySelectorAll('[data-stat3-chance]').forEach(zone=>{
  if(zone.dataset.ready)return;zone.dataset.ready='true';const select=zone.querySelector('select'),status=zone.querySelector('[data-stat3-chance-status]'),plot=zone.querySelector('[data-stat3-chance-plot]'),table=zone.querySelector('[data-stat3-chance-table]');let total=0,hits=0,history=[],batches=[];
  plot.tabIndex=0;plot.setAttribute('role','region');plot.setAttribute('aria-label','Verlauf der relativen Häufigkeit; auf schmalen Bildschirmen seitlich verschiebbar');
  const draw=()=>{const model=models[select.value],maximum=Math.max(10,total),x=n=>50+n/maximum*285,y=p=>220-p*160,s=svg('Relative Trefferhäufigkeit im Verlauf: '+total+' Versuche. Modellwahrscheinlichkeit '+format(model.p*100)+' Prozent. Die Daten der letzten Gruppen stehen in der Tabelle.');add(s,'rect',{width:360,height:280,fill:'white'});add(s,'text',{x:12,y:23,'font-size':16,fill:'#111827'},'Trefferanteil in %');for(const percent of [0,50,100]){add(s,'line',{x1:50,y1:y(percent/100),x2:335,y2:y(percent/100),stroke:'#cbd5e1'});add(s,'text',{x:43,y:y(percent/100)+5,'text-anchor':'end','font-size':15,fill:'#111827'},percent);}add(s,'path',{d:'M50 50V220H335',fill:'none',stroke:'#111827'});for(const n of [0,maximum/2,maximum])add(s,'text',{x:x(n),y:244,'text-anchor':'middle','font-size':15,fill:'#111827'},format(n));add(s,'text',{x:200,y:267,'text-anchor':'middle','font-size':16,fill:'#111827'},'Anzahl der Versuche');add(s,'line',{x1:50,y1:y(model.p),x2:335,y2:y(model.p),stroke:'#9a3412','stroke-width':2,'stroke-dasharray':'7 4','data-stat3-theory':''});if(history.length){add(s,'polyline',{points:history.map((v,i)=>x(i+1)+','+y(v)).join(' '),stroke:'#1d4ed8','stroke-width':2,fill:'none','data-stat3-observed':''});add(s,'circle',{cx:x(total),cy:y(hits/total),r:4,fill:'#1d4ed8','data-stat3-last':''});}plot.replaceChildren(s);
   table.replaceChildren();if(!batches.length)return;const t=element('table'),caption=element('caption','Zwischenstände nach den letzten '+Math.min(10,batches.length)+' ausgeführten Gruppen'),head=element('thead'),hr=element('tr'),labels=['Versuche insgesamt','Treffer insgesamt','Relativer Anteil'];for(const label of labels){const th=element('th',label);th.scope='col';hr.append(th);}head.append(hr);const body=element('tbody');for(const row of batches.slice(-10)){const tr=element('tr');[row.total,row.hits,format(100*row.hits/row.total)+' %'].forEach((value,i)=>{const td=element('td',value);td.dataset.label=labels[i];tr.append(td);});body.append(tr);}t.append(caption,head,body);table.append(t);
  };
  const reset=()=>{total=0;hits=0;history=[];batches=[];plot.scrollLeft=0;zone.dataset.total='0';zone.dataset.hits='0';zone.querySelector('[data-stat3-assumptions]').textContent=models[select.value].assumption;status.textContent='Noch keine Versuche. Eine beobachtete relative Häufigkeit ist noch nicht berechenbar.';draw();};
  for(const button of zone.querySelectorAll('[data-stat3-run]'))button.addEventListener('click',()=>{if(total>=1000){status.textContent='Diese Reihe enthält 1 000 Versuche. Vergleiche dein Ergebnis oder beginne mit „Neue Reihe“.';status.focus();return;}const model=models[select.value],count=Math.min(Number(button.dataset.stat3Run),1000-total);let last=0;for(let i=0;i<count;i++){last=Math.floor(Math.random()*model.size)+1;total++;if(model.hit(last))hits++;history.push(hits/total);}batches.push({total,hits});zone.dataset.total=String(total);zone.dataset.hits=String(hits);status.textContent=count+' neue Versuche. Insgesamt '+total+' Versuche und '+hits+' Treffer: relative Häufigkeit '+format(100*hits/total)+' %. Modellwahrscheinlichkeit '+format(100*model.p)+' %. Letztes simuliertes Ergebnis: '+model.name(last)+'. '+(total===1000?'Die Reihe ist voll; du kannst eine neue beginnen.':'Jede neue Reihe kann anders ausfallen.');draw();});
  select.addEventListener('change',reset);zone.querySelector('[data-stat3-reset]').addEventListener('click',()=>{reset();select.focus();});reset();
 });
}
