const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
const summaries={
dgb_word_werkstatt:['Ein Dokument braucht einen passenden Dateinamen und einen Speicherort, an dem du es wiederfindest.','Formatvorlagen, Absätze, Listen und Tabellen strukturieren Inhalte; Bilder brauchen eine verständliche Platzierung.','Prüfe das fertige Dokument und den PDF-Export auf Inhalt, Lesbarkeit und vollständige Seiten.'],
dgb5_orientierung:['EVA bedeutet Eingabe, Verarbeitung und Ausgabe. Diese Schritte lassen sich an vielen digitalen Geräten unterscheiden.','Digitale Darstellung verwendet unterscheidbare Werte oder Zeichen, etwa Bits; analoge Darstellung bildet Größen kontinuierlich ab.','Beobachte, wann und wozu du Medien nutzt, und beschreibe deren Nutzen und Wirkung.'],
dgb5_information:['Eine genaue Frage hilft, passende Suchbegriffe zu wählen.','Prüfe Urheber, Zweck, Aktualität und Belege einer Quelle und vergleiche mehrere Quellen.','Ordner und aussagekräftige Dateinamen helfen, gespeicherte Informationen wiederzufinden.'],
dgb5_kommunikation:['Personenbezogene Daten beziehen sich auf erkennbare oder bestimmbare Menschen.','Überlege vor dem Teilen, wer die Information benötigt und wer sie sehen kann.','Respektvolle Nachrichten beachten die betroffenen Menschen; bei Problemen gehört Hilfeholen dazu.'],
dgb5_produktion:['Ein Algorithmus beschreibt eine genaue Schrittfolge für eine Aufgabe.','Plane Ziel, Inhalt und Reihenfolge eines digitalen Produkts, bevor du es gestaltest.','Teste dein Ergebnis und verbessere unklare Schritte oder Darstellungen.'],
dgb5_handeln:['Hardware sind körperliche Bauteile, Software umfasst Programme und Apps.','Das Betriebssystem verwaltet grundlegende Funktionen und ermöglicht die Nutzung von Programmen und Dateien.','Beschreibe ein Problem anhand deiner Beobachtung, bevor du eine sichere Lösung oder Hilfe suchst.'],
dgb6_orientierung:['Wähle digitale Werkzeuge nach der Aufgabe und den Bedürfnissen der Nutzenden aus.','Gestaltung kann Nutzung erleichtern, Aufmerksamkeit lenken oder Menschen ausschließen.','Frage bei einem Angebot nach den Interessen der Beteiligten und nach Zugänglichkeit.'],
dgb6_information:['Sortieren und Filtern helfen, Daten zu ordnen und gezielt zu betrachten.','Tabellen und Diagramme brauchen passende Beschriftungen und Einheiten.','Prüfe Nutzungsbedingungen fremder Inhalte und dokumentiere Quelle und Lizenz.'],
dgb6_kommunikation:['Daten können in Paketen über Netzwerke übertragen und am Ziel wieder zusammengesetzt werden.','Nachrichten und Plattformen verfolgen unterschiedliche Zwecke, etwa Information, Unterhaltung oder Werbung.','Prüfe Absender, Link und verlangte Handlung; Zeitdruck allein ist kein Grund, Zugangsdaten preiszugeben.'],
dgb6_produktion:['Programme verarbeiten Daten; Medienprodukte verbinden beispielsweise Text, Bild und Ton.','Debuggen bedeutet, Fehler systematisch zu finden und zu beheben.','Beim Weiterverwenden fremder Inhalte müssen Rechte und erlaubte Nutzungen berücksichtigt werden.'],
dgb6_handeln:['Ein digitaler Arbeitsplatz verbindet Geräte, Programme, Dateien und Netzwerk.','Geordneter Datenaustausch benötigt passende Speicherorte und Zugriffsrechte.','Sorgsamer Umgang, Reparaturmöglichkeiten und lange Nutzung beeinflussen den Ressourcenverbrauch von Geräten.'],
dgb7_orientierung:['Vernetzte Systeme und KI-Anwendungen können Daten für Vorschläge und Ergebnisse nutzen.','Personalisierung verändert, welche Inhalte oder Angebote jemand sieht.','Beurteile Nutzen, Risiken und Teilhabe auch aus Sicht anderer Menschen.'],
dgb7_information:['Eine Recherche braucht eine genaue Frage, Suchstrategie und nachvollziehbare Quellen.','Vergleiche Aussagen und dokumentiere Belege, Zeitpunkt und offene Fragen.','Prüfe bei Diagrammen Achsen, Maßstab, Zeitraum und fehlende Daten, bevor du eine Schlussfolgerung ziehst.'],
dgb7_kommunikation:['Cloud-Dienste speichern oder verarbeiten Daten auf entfernten Rechnern; Freigaben bestimmen den Zugriff.','Einzigartige Passwörter und ein zusätzlicher Faktor schützen Zugänge auf unterschiedlichen Wegen.','Digitale Spuren können weiterverwendet werden; prüfe deshalb Inhalte und Berechtigungen vor dem Teilen.'],
dgb7_produktion:['Zerlege ein Problem in kleinere Teilaufgaben und suche nach wiederkehrenden Mustern.','Abstraktion lässt für die Aufgabe unwichtige Einzelheiten weg.','Teste Inhalt, Funktion und Zugänglichkeit deines Medienprodukts und verbessere es anhand der Ergebnisse.'],
dgb7_handeln:['Digitale Systeme stecken auch in Alltagsgegenständen und können Daten erfassen oder austauschen.','Aktualisierungen können Fehler und Sicherheitslücken beheben; verdächtige Dateien oder Nachrichten benötigen Vorsicht.','Nutzen, Datenverarbeitung und Umweltfolgen gehören gemeinsam zur Bewertung smarter Geräte.'],
dgb8_orientierung:['KI-Ausgaben können überzeugend wirken und dennoch sachlich falsch sein.','Personalisierte Auswahl und stereotype Darstellungen können die Wahrnehmung beeinflussen.','Begründe deine Bewertung einer Technik mit Belegen und berücksichtige Einsatzbedingungen und Folgen.'],
dgb8_information:['Ein Backup ist eine Sicherungskopie; zur Planung gehört auch das Wiederherstellen.','Datenspuren können zusammengeführt und ausgewertet werden.','Bereite Informationen für die jeweilige Zielgruppe verständlich auf und teile nur benötigte Daten.'],
dgb8_kommunikation:['Protokolle regeln, wie Geräte Daten austauschen.','Medieninhalte sind ausgewählt und gestaltet; prüfe mögliche Bearbeitung, Kontext und Quelle.','Vor dem Weitergeben sind Wirkung, Nutzungsrechte und Rechte betroffener Personen zu beachten.'],
dgb8_produktion:['Bedingungen steuern Entscheidungen, Schleifen wiederholen Anweisungen.','Pseudocode beschreibt einen Ablauf unabhängig von einer bestimmten Programmiersprache.','Ein gemeinsames Projekt braucht Aufgabenverteilung, Tests und nachvollziehbare Dokumentation.'],
dgb8_handeln:['Hardware, Betriebssystem, Anwendungen und Online-Dienste erfüllen unterschiedliche Aufgaben.','Verschlüsselung schützt Inhalte, indem sie diese ohne passenden Schlüssel unlesbar macht.','Prüfe Einstellungen, Vertragsbedingungen und Gesamtkosten digitaler Angebote, bevor du dich entscheidest.']};
for(const [id,summary]of Object.entries(summaries)){
 const t=d[id];if(!t)throw Error('Missing chapter '+id);
 const $=cheerio.load(t.sections[0].content),goals=$('.lesson-goals li').map((_,el)=>$(el).text().trim()).get();
 if(!goals.length)throw Error('No authored learning goals '+id);
 t.learningGoals=goals.map(s=>s.charAt(0).toUpperCase()+s.slice(1)+(s.endsWith('.')?'':'.'));t.summary=summary;
 const match=id.match(/^dgb([5-8])_(.+)$/);
 t.prerequisites=id==='dgb_word_werkstatt'?['dgb5_handeln','dgb5_information']:match&&Number(match[1])>5?['dgb'+(Number(match[1])-1)+'_'+match[2]]:id==='dgb5_orientierung'?[]:['dgb5_orientierung'];
}
// An analogue system can also process information; the distinction is its representation.
{const t=d.dgb5_orientierung,$=cheerio.load(t.sections[0].content);$('.word-ui-card').filter((_,el)=>$(el).find('strong').first().text()==='Analog oder digital?').html('<strong>Analog oder digital?</strong><br>Analog bildet eine Größe kontinuierlich ab, etwa eine Zeigerstellung. Digital verwendet unterscheidbare Werte oder Zeichen, etwa Zahlen und Bits. Beide können Informationen darstellen und verarbeiten.');t.sections[0].content=$('body').html();}
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');console.log('Added 21 DGB guides from existing chapter goals, with specific summaries and prerequisite links.');
