const fs=require('fs'),path=require('path');
const file=path.join(__dirname,'../lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8'));
// Goals describe the actual chapter scope, not a claim of full curriculum coverage.
const guides={
math1_1_vs_wissen:[['Zählen und Zahlen aus der Volksschule kennen.'],['Natürliche Zahlen addieren und subtrahieren.','Multiplikation als wiederholte Addition erklären.','Mengen gleichmäßig aufteilen und die passende Rechnung angeben.'],['Addition fasst Mengen zusammen; Subtraktion bestimmt einen Rest oder Unterschied.','5 · 4 bedeutet fünfmal vier und ergibt 20.','20 : 4 = 5: Bei vier gleich großen Gruppen enthält jede fünf Stück.']],
math1_2_nat_zahlen:[['math1_1_vs_wissen'],['Ziffern als Zeichen und Zahlen als dargestellte Werte unterscheiden.','Dreistellige Zahlen in Hunderter, Zehner und Einer zerlegen.','Den Wert einer Ziffer aus ihrer Stelle bestimmen.'],['Mit den zehn Ziffern 0 bis 9 schreiben wir Zahlen im Dezimalsystem.','347 = 3 · 100 + 4 · 10 + 7.','In 182 steht die 8 an der Zehnerstelle und hat den Wert 80.']],
math1_3_add_sub:[['math1_2_nat_zahlen'],['Natürliche Zahlen stellenrichtig untereinander schreiben.','Schriftlich addieren und einen Übertrag erklären.','Schriftlich subtrahieren und das Ergebnis durch Addition kontrollieren.'],['Beim schriftlichen Rechnen stehen gleiche Stellenwerte untereinander.','14 Einer werden zu 1 Zehner und 4 Einern gebündelt; der Zehner wird übertragen.','87 − 45 = 42. Die Gegenprobe lautet 42 + 45 = 87.']],
math1_4_mult_div:[['math1_1_vs_wissen'],['Faktoren und Produkt sowie Dividend, Divisor und Quotient benennen.','Multiplikation und Division als Umkehroperationen verwenden.','Punkt-vor-Strich-Regel und Verteilungsgesetz anwenden.'],['Faktor · Faktor = Produkt; Dividend : Divisor = Quotient. Durch 0 darf man nicht dividieren.','Bei natürlichen Zahlen lässt sich Multiplikation als wiederholte Addition darstellen.','Klammern haben Vorrang, danach folgen Multiplikation und Division vor Addition und Subtraktion. Das Verteilungsgesetz lautet a · (b + c) = a · b + a · c.']],
math1_5_geo_grundbegriffe:[['Mit Lineal und Stift umgehen.'],['Punkt, Gerade, Strahl und Strecke unterscheiden.','Parallele und normale Geraden erkennen.','Die Länge einer Strecke messen.'],['Eine Gerade ist beidseitig unbegrenzt, ein Strahl hat einen Anfangspunkt, eine Strecke zwei Endpunkte.','Eine Strecke besitzt eine messbare Länge.','Verschiedene parallele Geraden in einer Ebene schneiden sich nicht. Normale Geraden schneiden sich im rechten Winkel.']],
math1_6_winkel:[['math1_5_geo_grundbegriffe'],['Scheitelpunkt und Schenkel eines Winkels erkennen.','Winkel in Grad messen und eine Winkelgröße im Modell verändern.','Winkel anhand ihrer Größe benennen.'],['Zwei Strahlen mit gemeinsamem Anfangspunkt bilden die Schenkel eines Winkels; ihr Anfangspunkt ist der Scheitelpunkt.','Spitze Winkel liegen zwischen 0° und 90°, stumpfe zwischen 90° und 180°; die Grenzen gehören jeweils nicht dazu.','Rechter Winkel: 90°, gestreckter Winkel: 180°, voller Winkel: 360°.']],
math1_7_gleichungen:[['math1_3_add_sub'],['Das Gleichheitszeichen als Gleichheit zweier Werte erklären.','Einfache Gleichungen mit Addition oder Subtraktion lösen.','Eine Lösung durch Einsetzen überprüfen.'],['Bei einer Gleichung haben linke und rechte Seite denselben Wert.','Dieselbe Zahl auf beiden Seiten zu addieren oder zu subtrahieren erhält die Gleichheit.','x − 4 = 10 ergibt x = 14. Einsetzen bestätigt: 14 − 4 = 10.']],
math1_8_brueche:[['math1_4_mult_div'],['Brüche darstellen, lesen und bei gleichem Zähler oder Nenner vergleichen.','Brüche und gemischte Zahlen ineinander umwandeln.','Gleichnamige Brüche addieren und subtrahieren.','Bruchteile von Größen berechnen und Brüche als Division verstehen.'],['Der Nenner beschreibt die gleich großen Teile eines Ganzen, der Zähler ihre Anzahl.','Bei gleichem Nenner entscheidet der Zähler über die Größe; bei gleichem positiven Zähler bedeutet ein größerer positiver Nenner einen kleineren Bruch.','Gleichnamige Brüche: Zähler addieren oder subtrahieren, Nenner beibehalten.','3/4 von 20 € sind 20 € : 4 · 3 = 15 €. Der Bruchstrich bedeutet auch Division: 3/4 = 3 : 4.']],
math1_9_dezimalzahlen:[['math1_2_nat_zahlen','math1_8_brueche'],['Dezimalzahlen anhand ihrer Stellenwerte lesen, vergleichen und runden.','Zehntel- und Hundertstelbrüche als Dezimalzahlen schreiben.','Mit Dezimalzahlen rechnen und durch natürliche Zahlen ungleich 0 dividieren.','Sachaufgaben mit passenden Rechenschritten, Einheiten und Antwortsatz lösen.'],['Rechts vom Komma folgen Zehntel, Hundertstel und Tausendstel. Endnullen verändern den Wert nicht: 2,5 = 2,50.','Beim Runden entscheidet die erste wegfallende Ziffer: ab 5 aufrunden, sonst abrunden.','Bei Addition und Subtraktion stehen gleiche Stellenwerte untereinander; bei Multiplikation bestimmt die gesamte Zahl der Nachkommastellen die Kommasetzung.','Überschlag und Gegenprobe helfen bei der Kontrolle. 6,4 : 2 = 3,2, denn 3,2 · 2 = 6,4.']],
math1_10_groessen:[['math1_4_mult_div'],['Länge, Masse und Zeit passenden Einheiten zuordnen.','Meter und Zentimeter sowie Kilogramm und Gramm umrechnen.','Stunden und Minuten ineinander umrechnen.'],['1 m = 100 cm; 1 kg = 1000 g.','1 h = 60 min; 90 min = 1 h 30 min.','Ein vollständiges Messergebnis enthält eine Zahl und eine passende Einheit.']],
math1_11_figuren_koerper:[['math1_5_geo_grundbegriffe'],['Ebene Figuren von räumlichen Körpern unterscheiden.','Dreieck, Rechteck und Quadrat an ihren Eigenschaften erkennen.','Würfel, Quader, Zylinder und Kugel Alltagsmodellen zuordnen.'],['Ein Dreieck hat drei Ecken. Ein Rechteck hat vier rechte Winkel; beim Quadrat sind zusätzlich alle vier Seiten gleich lang.','Ein Würfel hat sechs quadratische Flächen, zwölf Kanten und acht Ecken.','Eine Papierfläche kann als ebene Figur modelliert werden. Ein echtes Blatt besitzt eine Dicke und ist ein räumlicher Gegenstand.']]
};
for(const[id,[p,g,s]]of Object.entries(guides))Object.assign(data[id],{prerequisites:p,learningGoals:g,summary:s});
function replace(id,from,to){for(const s of data[id].sections)s.content=s.content.replaceAll(from,to);}
replace('math1_1_vs_wissen','Wenn du Plus rechnest, wird es mehr (Addieren). Wenn du Minus rechnest, wird es weniger (Subtrahieren).','Wenn du eine positive natürliche Zahl addierst, wird das Ergebnis größer. Wenn du sie subtrahierst, wird es kleiner. Bei + 0 und − 0 bleibt die Zahl gleich.');
const n=data.math1_2_nat_zahlen;
n.sections[0].quizzes[0].id='m12_ziffer_zahl';
replace('math1_2_nat_zahlen','{{QUIZ_undefined}}','{{QUIZ_m12_ziffer_zahl}}');
replace('math1_2_nat_zahlen','Wie viele <span style="color:red">Zehner</span> hat die Zahl','Welche Ziffer steht an der <span style="color:red">Zehnerstelle</span> der Zahl');
replace('math1_2_nat_zahlen','Dreihundert-sieben-und-vierzig','dreihundertsiebenundvierzig');
if(!n.sections[1].content.includes('aria-label="Ziffer an der Zehnerstelle'))replace('math1_2_nat_zahlen','id="inputZehner"','id="inputZehner" aria-label="Ziffer an der Zehnerstelle von 182"');
n.diplom.questions=[
 {id:'m12_check_place',question:'Welchen Wert hat die Ziffer 8 in 182?',answers:[{text:'80',correct:true,pts:10,feedback:'Die 8 steht an der Zehnerstelle: 8 · 10 = 80.'},{text:'8',correct:false,pts:0,feedback:'8 wäre der Wert an der Einerstelle. Hier sind es acht Zehner, also 80.'},{text:'800',correct:false,pts:0,feedback:'800 wären acht Hunderter. In 182 steht die 8 an der Zehnerstelle.'}]},
 {id:'m12_check_build',question:'Welche Zahl besteht aus 4 Hundertern, 0 Zehnern und 6 Einern?',answers:[{text:'406',correct:true,pts:10,feedback:'400 + 0 + 6 = 406. Die 0 hält die Zehnerstelle frei.'},{text:'46',correct:false,pts:0,feedback:'46 hat vier Zehner, nicht vier Hunderter. Die Null an der Zehnerstelle darf nicht fehlen.'},{text:'460',correct:false,pts:0,feedback:'460 enthält sechs Zehner und keinen Einer. Gesucht sind sechs Einer.'}]}
];
if(!data.math1_3_add_sub.sections[2].content.includes('Gegenprobe:'))data.math1_3_add_sub.sections[2].content+='<p><strong>Gegenprobe:</strong> 42 + 45 = 87. Addiere Ergebnis und abgezogene Zahl: Du erhältst wieder die Ausgangszahl.</p>';
if(!data.math1_7_gleichungen.sections[1].content.includes('Probe durch Einsetzen'))data.math1_7_gleichungen.sections[1].content+='<p><strong>Probe durch Einsetzen:</strong> Setze 14 für x in x − 4 = 10 ein: 14 − 4 = 10. Beide Seiten sind gleich; die Lösung stimmt.</p>';
replace('math1_6_winkel','Kleiner als 90°.','Größer als 0° und kleiner als 90°.');
replace('math1_6_winkel','Größer als 90°.','Größer als 90° und kleiner als 180°.');
const w=data.math1_6_winkel;
w.sections[1].quizzes.find(q=>q.id==='m16_q2b').answers[0].text='Größer als 90° und kleiner als 180°';
w.diplom.questions[0].answers[0].text='…größer als 0° und kleiner als 90°';
w.diplom.questions[0].answers[1].feedback='Spitze Winkel sind größer als 0° und kleiner als 90°. Über 90° gibt es mehrere Winkelarten.';
w.sections[0].quizzes[0].question='Welches Beispiel veranschaulicht eine Drehung um 90°?';
w.sections[0].quizzes[0].answers[0].text='Eine Vierteldrehung auf dem Skateboard';
w.sections[0].quizzes[0].answers[0].feedback='Eine volle Drehung hat 360°. Ein Viertel davon sind 90°.';
w.sections[0].quizzes[0].answers[1].feedback='Geradeausfahren ändert die Fahrtrichtung nicht. Eine Vierteldrehung ändert sie um 90°.';
replace('math1_10_groessen','Gewicht messen wir','Masse messen wir');
replace('math1_11_figuren_koerper','Ein Handy ist ein Rechteck.','Ein Rechteck hat vier rechte Winkel. Die Vorderseite eines Handys kann näherungsweise als Rechteck modelliert werden. Ein Quadrat ist ein besonderes Rechteck mit vier gleich langen Seiten. Ein Dreieck hat drei Ecken.');
replace('math1_11_figuren_koerper','Er hat 6 Seiten.','Er hat 6 quadratische Flächen, 12 Kanten und 8 Ecken. Ein Quader hat sechs rechteckige Flächen. Eine Getränkedose lässt sich näherungsweise als Zylinder modellieren, ein Ball als Kugel.');
replace('math1_11_figuren_koerper',"<option value=''><option>","<option value=''>Bitte auswählen</option>");
const f=data.math1_11_figuren_koerper;
f.sections[1].quizzes[0].question='Wie viele Flächen hat ein Würfel?';
f.sections[1].quizzes[0].answers[0].feedback='Ein Würfel hat sechs quadratische Flächen: oben, unten, vorne, hinten, links und rechts.';
f.sections[1].quizzes[0].answers[1].feedback='Vier ist die Seitenanzahl einer einzelnen quadratischen Fläche. Der ganze Würfel besitzt sechs Flächen.';
f.diplom.questions[0].question='Die Oberfläche eines rechteckigen Papierblatts wird ohne Dicke betrachtet. Welches Modell passt?';
f.diplom.questions[0].answers[0].feedback='Die rechteckige Fläche wird als ebene Figur modelliert. Das echte Papierblatt hat jedoch eine Dicke.';
f.diplom.questions[0].answers[1].feedback='Das echte Blatt ist räumlich. Gefragt ist hier aber ausdrücklich das Modell seiner Fläche ohne Dicke.';
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');
console.log('Added 11 mathematics guides and corrected observed chapter defects.');
