const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..');
// Written from the existing chapter sections; this does not certify all underlying content.
const guides={
sieinheiten:{p:['Dezimalzahlen lesen und einfache Divisionen ausführen.'],g:['Messgrößen mit Zahlenwert und Einheit angeben.','Längen, Massen und Zeiten in passende Einheiten umrechnen.','Geschwindigkeit berechnen und Messwerte aus Diagrammen lesen.'],s:['Eine Messangabe verbindet Zahlenwert und Einheit; Größe und Einheit sind verschieden.','1 km = 1000 m, 1 m = 100 cm, 1 kg = 1000 g und 1 min = 60 s.','Für eine zurückgelegte Strecke gilt die mittlere Geschwindigkeit v = s/t; Achsen und Einheiten gehören zur Diagrammauswertung.']},
optik1:{p:['Lichtquelle und beleuchteten Gegenstand im Alltag unterscheiden.'],g:['Lichtquellen und Schattenbildung mit einem Strahlenmodell erklären.','Kern- und Halbschatten sowie die Anordnung bei Finsternissen unterscheiden.','Reflexion und Beugung als unterschiedliche Erscheinungen beschreiben.'],s:['In einem gleichmäßigen Medium beschreibt das Strahlenmodell geradlinige Lichtwege.','Bei Kernschatten ist die betrachtete Lichtquelle ganz, bei Halbschatten nur teilweise verdeckt.','Einfalls- und Reflexionswinkel werden zum Lot gemessen und sind gleich groß; Beugung zeigt die Welleneigenschaften des Lichts.']},
farben:{p:['optik1'],g:['Sichtbare Spektralfarben nach ihrer Wellenlänge einordnen.','Farbzerlegung und die Farbe beleuchteter Gegenstände erklären.','Additive Lichtmischung von subtraktiver Mischung unterscheiden.'],s:['Im sichtbaren Spektrum liegen rote Wellenlängen am langen, violette am kurzen Ende.','Ein Prisma trennt weißes Licht durch unterschiedlich starke Brechung seiner Spektralanteile.','Bei Lichtmischung kommen Lichtanteile hinzu; Farbstoffe absorbieren Anteile. Wahrgenommene Objektfarben hängen auch von der Beleuchtung ab.']},
linsen_spiegel:{p:['optik1'],g:['Reflexion, Brechung und Totalreflexion unterscheiden.','Sammel- und Zerstreuungslinsen anhand ihrer Wirkung auf Lichtstrahlen vergleichen.','Auge, Mikroskop und Teleskop als optische Systeme beschreiben.'],s:['Reflexionswinkel werden zum Lot gemessen. Bei einem Medienwechsel kann sich die Richtung eines Lichtstrahls durch Brechung ändern.','Totalreflexion ist beim Übergang zum optisch dünneren Medium oberhalb des Grenzwinkels möglich.','Eine Sammellinse bündelt achsennahe parallele Strahlen näherungsweise im Brennpunkt. Objektabstand und optischer Aufbau bestimmen die Bildentstehung.']},
akustik:{p:['sieinheiten'],g:['Schallentstehung und die notwendige Rolle eines Mediums erklären.','Frequenz und Amplitude in einer Schwingungsdarstellung unterscheiden.','Echo-Laufzeiten und Resonanz mit einfachen Modellen untersuchen.'],s:['Schall breitet sich durch Schwingungen in einem Medium aus; im Vakuum fehlt dieses Medium.','Frequenz beschreibt Schwingungen pro Sekunde und beeinflusst die Tonhöhe. Die Amplitude beschreibt die Stärke der Schwingung.','Ein Echo legt Hin- und Rückweg zurück. Resonanz ist besonders starkes Mitschwingen bei geeigneter Anregungsfrequenz.']},
kraft_und_bewegung:{p:['sieinheiten'],g:['Kräfte an Bewegungsänderungen und Verformungen erkennen.','Trägheit, Reibung und Wechselwirkungskräfte unterscheiden.','Beschleunigung mit F = m · a berechnen und einen Hebel qualitativ erklären.'],s:['Ohne resultierende Kraft bleibt ein Körper in Ruhe oder bewegt sich geradlinig mit unveränderter Geschwindigkeit.','F = m · a verbindet resultierende Kraft, Masse und Beschleunigung. Wechselwirkungskräfte wirken auf verschiedene Körper.','Reibung beeinflusst Bewegung; beim idealen Hebel kann ein längerer Kraftweg eine kleinere Kraft ermöglichen.']},
drehundstatik:{p:['kraft_und_bewegung'],g:['Kippen mithilfe von Schwerpunkt und Standfläche beurteilen.','Drehmomente bei senkrechter Kraftwirkung berechnen.','Gleichgewichtsarten und Kreisbewegung unterscheiden.'],s:['Für das Kippen ist entscheidend, ob die Wirkungslinie der Gewichtskraft innerhalb der Standfläche liegt.','Drehmoment ist Kraft mal senkrechter Abstand ihrer Wirkungslinie zur Drehachse.','Eine Kreisbewegung benötigt eine nach innen gerichtete resultierende Kraft. Bei einer Pirouette kann veränderte Massenverteilung die Drehgeschwindigkeit ändern.']},
arbeit:{p:['kraft_und_bewegung'],g:['Mechanische Arbeit von körperlicher Anstrengung unterscheiden.','Hubarbeit und einfache Kraft-Weg-Beziehungen berechnen.','Energieänderungen durch Heben, Reibung, Verformen und Beschleunigen erklären.'],s:['Bei konstanter Kraft in Wegrichtung gilt W = F · s; ohne Weg wird am festgehaltenen Gegenstand keine mechanische Arbeit verrichtet.','Für das Heben nahe der Erdoberfläche gilt W = m · g · h; Arbeit wird in Joule angegeben.','Ideale einfache Maschinen sparen Kraft auf Kosten eines längeren Weges. Reale Reibung erfordert zusätzliche Arbeit.']},
energie:{p:['arbeit'],g:['Energieformen an Alltagssituationen erkennen.','Energieumwandlungen als Kette darstellen.','Erneuerbare Energieträger und einen einfachen Stromkreis beschreiben.'],s:['Energie kann zwischen Körpern übertragen und in andere Formen umgewandelt werden.','In einem abgeschlossenen System bleibt die Gesamtenergie erhalten; bei Nutzungsprozessen wird oft Energie an die Umgebung abgegeben.','Ein geschlossener Stromkreis kann elektrische Energie übertragen. Nutzbare Energie und Gesamtenergie sind nicht dasselbe.']},
elektrizitaet:{p:['sieinheiten','energie'],g:['Ladung, Stromstärke, Spannung und Widerstand unterscheiden.','Einen geschlossenen Stromkreis und die Rolle einer Batterie erklären.','Das Ohmsche Gesetz in passenden Modellaufgaben anwenden.'],s:['Elektrischer Strom ist gerichteter Ladungstransport; in Metallleitern sind die beweglichen Ladungsträger Elektronen.','Spannung beschreibt Energie pro Ladung, Stromstärke Ladung pro Zeit. Eine Batterie ermöglicht durch chemische Vorgänge eine Spannung.','Für einen ohmschen Widerstand bei unveränderten Bedingungen gilt U = R · I. Ein Kondensator kann elektrische Energie speichern.']},
elektromagnetismus:{p:['elektrizitaet'],g:['Die Magnetwirkung eines stromdurchflossenen Leiters und einer Spule beschreiben.','Motor und Generator hinsichtlich der Energieumwandlung unterscheiden.','Relais und Transformator als Anwendungen erklären.'],s:['Elektrische Ströme erzeugen Magnetfelder; eine Spule bündelt die Wirkung mehrerer Windungen.','Ein Motor wandelt elektrische in mechanische Energie um. Ein Generator nutzt Induktion zur Umwandlung mechanischer in elektrische Energie.','Ein Transformator benötigt einen sich ändernden magnetischen Fluss; im idealen Modell entspricht das Spannungsverhältnis dem Windungszahlverhältnis.']},
waermelehre:{p:['energie'],g:['Temperatur und Wärmeübertragung unterscheiden.','Wärmeleitung, Strömung und Strahlung an Beispielen zuordnen.','Zustandsänderungen und Wärmeausdehnung mit einem Teilchenmodell erklären.'],s:['Temperatur kennzeichnet einen thermischen Zustand; Wärme bezeichnet Energieübertragung aufgrund eines Temperaturunterschieds.','Wärmeleitung, Wärmeströmung und Wärmestrahlung sind unterschiedliche Übertragungswege.','Bei Zustandsänderungen verändert sich die Anordnung und Bewegung von Teilchen. Viele Stoffe dehnen sich beim Erwärmen aus; es gibt Ausnahmen.']},
wetter:{p:['waermelehre'],g:['Wettergrößen den passenden Messgeräten zuordnen.','Wind, Gewitter und Niederschlagsformen qualitativ erklären.','Die Rolle von Luft- und Meeresströmungen beschreiben.'],s:['Temperatur, Luftdruck, Feuchte, Wind und Niederschlag beschreiben Wetter.','Luftdruckunterschiede treiben Luftbewegungen an; Erwärmung und Erdrotation beeinflussen Strömungen.','Die Temperaturverhältnisse in Wolken und Luftschichten beeinflussen die Form des Niederschlags. Ozeane transportieren ebenfalls Wärme.']},
klima:{p:['wetter'],g:['Kurzfristiges Wetter von langfristigen Klimamustern unterscheiden.','Den natürlichen Treibhauseffekt und Klimaeinflussfaktoren erklären.','Klimadiagramme und Klimaarchive als Informationsquellen einordnen.'],s:['Klima beschreibt statistische Eigenschaften des Wetters über lange Zeiträume, häufig anhand von 30 Jahren.','Treibhausgase absorbieren und emittieren einen Teil der Wärmestrahlung.','Klimadiagramme benötigen Achsen, Einheiten, Ort und Bezugszeitraum. Eis, Baumringe und andere Archive liefern indirekte Hinweise auf vergangenes Klima.']},
klimawandel:{p:['klima'],g:['Beobachtungen und Ursachen der aktuellen Erwärmung unterscheiden und verbinden.','Klimaschutz und Anpassung an Wiener Beispielen vergleichen.','Risiken und Handlungsmöglichkeiten auf mehreren Ebenen begründet besprechen.'],s:['Langfristige Messreihen mehrerer Größen belegen Veränderungen des Klimasystems.','Zusätzliche menschlich verursachte Treibhausgase verstärken die Erwärmung; Klimaschutz setzt an Ursachen, Anpassung an Folgen an.','Handlungsmöglichkeiten betreffen Einzelne, Schulen, Gemeinden, Politik und Wirtschaft. Kipprisiken sind keine einfache sofortige Domino-Kette.']},
astronomie:{p:['erde_mond_sonne','energie'],g:['Himmelskörper und Größenordnungen im Sonnensystem unterscheiden.','Beobachtungen mit Bahnen, Gravitation und Licht in Beziehung setzen.','Grundideen zu Sternen, Galaxien und kosmischer Entwicklung erklären und offene Fragen benennen.'],s:['Planeten umlaufen Sterne; Monde umlaufen Planeten oder andere kleinere Körper. Teleskope sammeln elektromagnetische Strahlung.','Meteoroid bezeichnet einen kleinen Körper im All, Meteor die Leuchterscheinung in der Atmosphäre, Meteorit einen Rest am Boden.','Dunkle Materie und dunkle Energie bezeichnen unterschiedliche offene Fragen: zusätzliche gravitative Wirkung beziehungsweise die beschleunigte kosmische Expansion.']},
rechenbeispiele:{p:['sieinheiten'],g:['Einheiten vor einer Rechnung vereinheitlichen.','Gesuchte Größen mit v = s/t, s = v · t und t = s/v berechnen.','Rechenergebnisse an Einheiten und Diagrammen prüfen.'],s:['Vor dem Addieren und Einsetzen müssen Einheiten zusammenpassen.','1 h = 3600 s; mittlere Geschwindigkeit ist zurückgelegter Weg geteilt durch benötigte Zeit.','Ein vollständiges Ergebnis enthält Zahlenwert und Einheit. Eine Abschätzung hilft, Rechenfehler zu erkennen.']}
};
const file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8'));
for(const[id,guide]of Object.entries(guides)){if(!data[id])throw Error('Missing chapter '+id);data[id].learningGoals=guide.g;data[id].prerequisites=guide.p;data[id].summary=guide.s;}
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');console.log('Added chapter-specific guides to 17 existing physics chapters.');
