const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
const guides={
bio_1_kompass:[[],['Biologie untersucht Lebewesen und ihre Beziehungen zur Umwelt.','Eine Untersuchung trennt Frage, Beobachtung, Auswertung und Erklärung.','Modelle und Quellen helfen beim Erklären, haben aber Grenzen und müssen kritisch geprüft werden.']],
bio_1_evolution:[['bio_1_kompass'],['Lebewesen zeigen gemeinsame Merkmale wie Zellaufbau, Stoffwechsel und Reaktion auf ihre Umwelt.','Evolution beschreibt Veränderungen vererbbarer Merkmale in Populationen über Generationen.','Fossilien, Vergleiche von Merkmalen und weitere Belege stützen die Erklärung gemeinsamer Abstammung.']],
bio_1_lebensraeume:[['bio_1_kompass'],['Lebensbedingungen werden durch belebte und unbelebte Faktoren geprägt.','Nahrungsnetze verbinden mehrere Nahrungsketten und zeigen Beziehungen zwischen Lebewesen.','Zersetzer tragen zum Stoffkreislauf bei; menschliche Eingriffe können mehrere Beziehungen zugleich verändern.']],
bio_1_bluetenpflanzen:[['bio_1_kompass'],['Wurzel, Sprossachse, Blatt und Blüte erfüllen unterschiedliche Aufgaben.','Bestäubung ist die Übertragung von Pollen; Befruchtung bezeichnet die Vereinigung von Geschlechtszellen.','Keimung und Wachstum hängen von passenden Bedingungen ab; Samen können auf verschiedene Weise verbreitet werden.']],
bio_1_wirbeltiere:[['bio_1_evolution'],['Wirbeltiere besitzen eine Wirbelsäule und ein inneres Skelett.','Merkmale von Körperbau, Fortpflanzung und Lebensweise helfen beim Vergleichen und Einordnen.','Eine ähnliche Lebensweise allein beweist keine enge Verwandtschaft: Wale sind beispielsweise Säugetiere.']],
bio_1_selektion:[['bio_1_evolution'],['Individuen einer Population unterscheiden sich; ein Teil dieser Variation ist vererbbar.','Umweltbedingungen beeinflussen Überleben und Fortpflanzungserfolg, sodass sich Merkmalsanteile über Generationen verändern können.','Selektion folgt keinem bewussten Ziel. Bei künstlicher Selektion wählen Menschen Merkmale für die Zucht aus.']],
bio_2_oekosysteme:[['bio_1_lebensraeume'],['Ein Ökosystem umfasst Lebensraum, Lebensgemeinschaft und ihre Wechselwirkungen.','Licht, Wasser, Boden und weitere Faktoren beeinflussen die Verteilung von Arten und die Stockwerke eines Waldes.','Lebensräume lassen sich anhand derselben Kriterien vergleichen; menschliche Eingriffe können Vielfalt und Wechselwirkungen verändern.']],
bio_2_pflanzenorgane_fotosynthese:[['bio_1_bluetenpflanzen'],['Pflanzenorgane arbeiten bei Stoffaufnahme, Transport, Fotosynthese und Fortpflanzung zusammen.','Bei der Fotosynthese werden mithilfe von Licht aus Kohlenstoffdioxid und Wasser energiereiche organische Stoffe aufgebaut; Sauerstoff wird freigesetzt.','Auch Pflanzen betreiben Zellatmung. Fotosynthese und Zellatmung sind unterschiedliche Vorgänge.']],
bio_2_zellen:[['bio_1_evolution'],['Zellen sind grundlegende Baueinheiten der Lebewesen; spezialisierte Zellen können Gewebe und Organe bilden.','Pflanzen- und Tierzellen teilen wichtige Strukturen; Pflanzenzellen besitzen beispielsweise eine Zellwand, viele auch Chloroplasten.','Eine mikroskopische Beobachtung ist von einer schematischen Modellzeichnung zu unterscheiden.']],
bio_2_pflanzenvermehrung:[['bio_1_bluetenpflanzen','bio_2_zellen'],['Bestäubung und Befruchtung sind verschiedene Schritte der geschlechtlichen Vermehrung.','Bei geschlechtlicher Vermehrung wird Erbinformation neu kombiniert; ungeschlechtliche Vermehrung erfolgt ohne Verschmelzung von Geschlechtszellen.','Samen, Früchte, Ausläufer und andere Vermehrungsformen erfüllen unterschiedliche Funktionen im Lebenszyklus.']],
bio_3_geologie_lebensraeume:[['bio_2_oekosysteme'],['Gesteine entstehen und verändern sich durch Erstarren, Verwitterung, Ablagerung und Umwandlung unter Druck und Temperatur.','Plattenbewegungen können Gebirge, Erdbeben und Vulkanismus verursachen.','Gestein und Boden beeinflussen Wasserverfügbarkeit und Lebensbedingungen; geologische Modelle beschreiben lange Zeiträume.']],
bio_3_boden_mikroorganismen:[['bio_2_oekosysteme'],['Boden enthält mineralische Bestandteile, organische Substanz, Wasser, Luft und Lebewesen.','Zersetzer bauen organisches Material ab und tragen zur Verfügbarkeit von Nährstoffen bei.','Boden speichert Wasser und gibt Pflanzen Halt; Verdichtung, Versiegelung und Erosion verändern seine Funktionen.']],
bio_3_fossilien_erdgeschichte:[['bio_1_evolution','bio_3_geologie_lebensraeume'],['Fossilien sind erhaltene Reste, Abdrücke oder Spuren früherer Lebewesen.','Fossilbildung benötigt geeignete Erhaltungsbedingungen; der Fossilbericht ist deshalb lückenhaft.','Fossilien und Gesteinsschichten liefern Belege für Veränderungen von Lebewesen und Lebensräumen über lange Zeit.']],
bio_3_kladogramme:[['bio_1_selektion','bio_1_wirbeltiere'],['Kladogramme stellen Hypothesen über gemeinsame Abstammung als Verzweigungen dar.','Gemeinsame abgeleitete Merkmale helfen, Gruppen zu bilden; äußere Ähnlichkeit allein reicht nicht.','Die Anordnung der Endpunkte bedeutet keine Rangfolge von höher oder niedriger entwickelten Lebewesen.']],
bio_4_landwirtschaft_biodiversitaet:[['bio_3_boden_mikroorganismen'],['Landwirtschaft erzeugt Produkte und verändert zugleich Ökosysteme.','Düngung, Bewässerung und Pflanzenschutz haben beabsichtigte Wirkungen und mögliche Folgen für Boden, Wasser und Artenvielfalt.','Eine Bewertung berücksichtigt Ertrag, Ressourcen, Biodiversität und unterschiedliche Interessen.']],
bio_4_siedlungsraeume:[['bio_2_oekosysteme'],['Auch Städte und Dörfer sind Lebensräume mit belebten und unbelebten Faktoren.','Versiegelung verändert Wasserhaushalt und Temperatur; begrünte Flächen können Lebensraum und Kühlung bieten.','Stadtökologie betrachtet Nutzungskonflikte und Möglichkeiten, Lebensräume zu erhalten oder zu verbessern.']],
bio_4_kohlenstoff_klima:[['bio_2_pflanzenorgane_fotosynthese'],['Fotosynthese, Zellatmung, Zersetzung und Verbrennung bewegen Kohlenstoff zwischen verschiedenen Speichern.','Zusätzliche Treibhausgase verändern den Strahlungshaushalt und das Klima.','Klimaschutz setzt an Ursachen an, Anpassung an Folgen; Veränderungen des Klimas beeinflussen Lebensräume.']],
bio_4_menschheitsentwicklung:[['bio_3_kladogramme','bio_3_fossilien_erdgeschichte'],['Menschen gehören zu den Primaten und teilen mit anderen Menschenaffen gemeinsame Vorfahren.','Fossilien und Merkmalsvergleiche liefern Hinweise auf eine verzweigte Entwicklungsgeschichte.','Evolution ist keine zielgerichtete Leiter; heutige Menschen stammen nicht von heute lebenden anderen Affenarten ab.']]};
for(const[id,[prerequisites,summary]]of Object.entries(guides)){
const t=d[id],$=cheerio.load(t.sections[0].content),boxes=$('.bio-overview-box').filter((_,el)=>$(el).text().includes('Das soll ich lernen'));
const goals=boxes.first().find('li').map((_,el)=>$(el).text().trim()).get();
if(!goals.length)throw Error('Missing authored goals '+id);
Object.assign(t,{prerequisites,summary,learningGoals:goals});
}
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');console.log('Added 18 biology guides for foundations, plants, evolution and ecosystems.');
