const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),id='geo_1_ernaehrung_landwirtschaft';
const blocks=[
 ['Vom Feld zur Jause',`<p>Bevor ein Brot in deiner Jausenbox liegt, haben viele Menschen gearbeitet. Ein landwirtschaftlicher Betrieb baut Getreide an und erntet es. Eine Mühle mahlt daraus Mehl. Eine Bäckerei verarbeitet Mehl und weitere Zutaten zu Brot. Transport und Handel verbinden diese Stationen. Nicht jeder Betrieb übernimmt alle Schritte selbst.</p><ol aria-label="Beispiel einer Lebensmittelkette"><li>Acker: Getreide anbauen und ernten</li><li>Mühle: Getreide zu Mehl verarbeiten</li><li>Bäckerei: Brot herstellen</li><li>Geschäft oder Direktverkauf: Brot verkaufen</li><li>Haushalt: Brot lagern und essen</li></ol><p>Die Landwirtschaft liefert pflanzliche und tierische Erzeugnisse. Zur Versorgung gehören außerdem Verarbeitung, Lagerung, Transport und Verkauf. Menschen benötigen nicht nur ausreichend Lebensmittel in einer Region, sondern auch Zugang dazu: etwa Geld zum Einkaufen und erreichbare Verkaufsstellen.</p>`],
 ['Was einen Anbauort prägt',`<p>Pflanzen benötigen passende Bedingungen. Temperatur, Wasser, Licht und Boden beeinflussen, was an einem Ort angebaut werden kann. Das Wetter einer einzelnen Saison kann eine Ernte verändern. Klima beschreibt typische Wetterverhältnisse über lange Zeiträume.</p><p>Auch menschliche Entscheidungen zählen: Arbeitskräfte, Wissen, Maschinen, Bewässerung, Energie, Preise und die Nähe zu Kund:innen. Ein Gewächshaus verändert Anbaubedingungen; sein Bau und Betrieb benötigen Material und gegebenenfalls Heizenergie. Bewässerung braucht verfügbares Wasser. Technik beseitigt daher nicht alle Grenzen.</p><p>In Wien gibt es neben Wohn- und Verkehrsflächen auch Landwirtschaft, etwa Gemüse- und Getreideanbau. Nähe zur Stadt kann kurze Wege zum Absatzmarkt ermöglichen. Flächen werden zugleich für Wohnen, Verkehr und Erholung gebraucht. Solche Interessen müssen bei der Planung gegeneinander abgewogen werden.</p>`],
 ['Betriebe fair vergleichen',`<p>Die folgende Tabelle zeigt <strong>erfundene Modellbetriebe</strong>, keine Wiener Messdaten. Beide bauen im gleichen Jahr dieselbe Feldfrucht an. Die Erntemenge allein verrät nicht, wie groß ein Betrieb ist oder wie viel er pro Fläche erntet.</p><table><caption>Modell: gleiche Feldfrucht und gleiches Erntejahr</caption><thead><tr><th scope="col">Betrieb</th><th scope="col">Anbaufläche</th><th scope="col">Erntemenge</th><th scope="col">Ernte pro Hektar</th></tr></thead><tbody><tr><th scope="row">A</th><td>2 ha</td><td>8 t</td><td>4 t/ha</td></tr><tr><th scope="row">B</th><td>4 ha</td><td>12 t</td><td>3 t/ha</td></tr></tbody></table><p>Ein Hektar (ha) sind 10 000 m², eine Tonne (t) sind 1 000 kg. Für die Ernte pro Hektar teilst du die Erntemenge durch die Anbaufläche. B erntet insgesamt mehr; A erntet mehr pro Hektar. Daraus folgt noch nicht, welcher Betrieb umweltschonender oder wirtschaftlich erfolgreicher arbeitet. Dafür fehlen etwa Angaben zu Wasser, Energie, Bodenpflege, Kosten und Verkaufspreisen.</p>`],
 ['Eine Entscheidung mit mehreren Kriterien',`<p><strong>Regional</strong> beschreibt die Herkunft aus einer näheren Umgebung; frage nach, welche Region gemeint ist. <strong>Saisonal</strong> bedeutet hier, dass ein Lebensmittel am Anbauort zu seiner üblichen Erntezeit verfügbar ist. Regional und saisonal sind deshalb nicht dasselbe. Auch Lagerung, Anbauweise, Verkehrsmittel und Lebensmittelverluste beeinflussen die Umweltwirkung. Eine kurze Strecke allein beweist keine insgesamt geringe Belastung.</p><p>Fiktiver Einkauf im September: Angebot A nennt Äpfel aus einem Betrieb in der Umgebung, Ernte im September, 2 kg für 4 €. Angebot B nennt Äpfel aus einem weiter entfernten Land, 1 kg für 2 €. Die Preise pro Kilogramm sind gleich. Transportmittel, Lagerdauer und Anbauweise sind unbekannt. Wenn die Gruppe nur 1 kg benötigt, muss sie bei A klären, ob sie teilen oder den Rest verwenden kann. Es gibt mit diesen Angaben keinen bewiesenen Sieger für alle Kriterien.</p><p>Plane benötigte Mengen und die Verwendung von Resten. Vergleiche Herkunft, Erntezeit, Preis pro Menge und vorhandene Belege. Eine gute Begründung nennt auch, was noch unbekannt ist, und bewertet Menschen nicht nach ihren finanziellen Möglichkeiten.</p>`]
];
const raw=[
 ['Welche Station verarbeitet Getreide unmittelbar zu Mehl?',['Die Mühle.','Die Bäckerei beim Backen.','Das Geschäft beim Verkauf.'],['Die Mühle mahlt die Körner zu Mehl.','Die Bäckerei verwendet das bereits gemahlene Mehl.','Der Verkauf verändert Getreide nicht zu Mehl.']],
 ['In einer Region gibt es genug Lebensmittel. Warum können trotzdem Menschen schlecht versorgt sein?',['Ihnen können Geld oder erreichbare Verkaufsstellen fehlen.','Die gesamte Erntemenge bestimmt allein den Zugang jeder Person.','Ein großes Angebot macht alle Lebensmittel automatisch kostenlos.'],['Verfügbarkeit und persönlicher Zugang sind verschiedene Voraussetzungen.','Die Menge sagt nichts darüber, wer Lebensmittel erreichen und bezahlen kann.','Angebot allein hebt Preise und Zugangsbarrieren nicht auf.']],
 ['Welche Angabe beschreibt eine natürliche Anbaubedingung?',['Die verfügbare Wassermenge am Standort.','Der Verkaufspreis im Geschäft.','Die Zahl der angestellten Arbeitskräfte.'],['Wasser beeinflusst das Pflanzenwachstum.','Preise sind eine wirtschaftliche Rahmenbedingung.','Arbeitskräfte gehören zu den menschlichen Rahmenbedingungen.']],
 ['Was folgt aus einem Gewächshaus am Stadtrand?',['Anbaubedingungen lassen sich verändern, der Betrieb benötigt aber Ressourcen.','Temperatur und Wasser spielen für Pflanzen darin keine Rolle mehr.','Seine Nähe zur Stadt beweist automatisch die geringste Umweltbelastung.'],['Material, Wasser und gegebenenfalls Heizenergie bleiben nötig.','Diese Bedingungen müssen auch im Gewächshaus passen.','Für eine Gesamtbewertung fehlen unter anderem Energie- und Anbaudaten.']],
 ['Betrieb B erntet 12 t auf 4 ha. Wie viel ist das pro Hektar?',['3 t/ha.','48 t/ha.','8 t/ha.'],['12 geteilt durch 4 ergibt 3.','Multiplizieren ergibt hier nicht die Ernte je Flächeneinheit.','Die Differenz aus Menge und Fläche hat nicht die gesuchte Bedeutung.']],
 ['Welche Aussage ist durch die Betriebstabelle belegt?',['B erntet insgesamt mehr, A mehr pro Hektar.','B erntet auch pro Hektar mehr als A.','A erzielt sicher den größeren Gewinn.'],['12 t sind mehr als 8 t; 4 t/ha sind mehr als 3 t/ha.','B erreicht 3 t/ha, A dagegen 4 t/ha.','Gewinn hängt auch von Preisen und Kosten ab, die nicht angegeben sind.']],
 ['Wie unterscheiden sich die Modellangebote im Kilopreis?',['Beide kosten 2 € pro kg.','A kostet 4 € pro kg.','B kostet 1 € pro kg.'],['Bei A: 4 € geteilt durch 2 kg. Bei B: 2 € für 1 kg.','4 € ist der Preis für zwei Kilogramm.','Bei B kostet ein Kilogramm ausdrücklich 2 €.']],
 ['Welche zusätzliche Frage hilft bei der Umweltbewertung der Äpfel?',['Wie wurden sie angebaut, gelagert und transportiert?','Welches Angebot hat die schönere Verpackungsfarbe?','Welcher Gesamtpreis ist höher, unabhängig von der Menge?'],['Diese Prozesse können die Umweltwirkung beeinflussen.','Eine Farbe liefert keinen Beleg zu Anbau oder Transport.','Verschiedene Mengen und Preise beweisen keine Umweltwirkung.']]
];
const questions=raw.map(([question,answers,feedback],i)=>({id:id+'_q'+i,question,answers:answers.map((text,j)=>({text,correct:j===0,pts:0,feedback:feedback[j]}))}));
const topic={title:'🌾 Landwirtschaft und unsere Lebensmittel',subtitle:'Vom Anbau zur Jause: Versorgung, Standorte und begründete Entscheidungen.',contentLanguage:'de',script:false,
 learningGoals:['Die Stationen einer Lebensmittelkette und ihre Aufgaben erklären.','Natürliche und menschliche Bedingungen der Landwirtschaft unterscheiden.','Erntemenge und Ernte pro Fläche anhand einer Tabelle vergleichen.','Eine Einkaufsentscheidung mit mehreren Kriterien und offenen Fragen begründen.'],
 prerequisites:['Einfache Geldbeträge vergleichen und durch ganze Zahlen teilen.','geo_2_wirtschaften'],
 summary:['Lebensmittelversorgung verbindet Anbau, Verarbeitung, Transport, Handel und Haushalte; Zugang hängt auch von Geld und Erreichbarkeit ab.','Landwirtschaft wird von natürlichen Bedingungen und menschlichen Entscheidungen geprägt, auch innerhalb Wiens.','Ernte pro Hektar = Erntemenge geteilt durch Anbaufläche; daraus allein folgt weder Gewinn noch Umweltverträglichkeit.','Herkunft, Erntezeit, Anbau, Lagerung, Transport und benötigte Menge gehören in einen begründeten Vergleich.'],
 sources:[{title:'RIS: Lehrplan der Mittelschule',url:'https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20007850'},{title:'Stadt Wien: Landwirtschaft in der Stadtplanung',url:'https://www.wien.gv.at/stadtplanung/landwirtschaft'},{title:'Stadt Wien: Stadt trifft Landwirtschaft',url:'https://www.wien.gv.at/spezial/klimatour/ernahrung/stadt-trifft-landwirtschaft/'}],
 sections:blocks.map(([title,content],i)=>({id:'section'+i,title:(i+1)+'. '+title,content:content+questions.slice(i*2,i*2+2).map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:questions.slice(i*2,i*2+2)})),
 workshop:{title:'5. Eine Jause begründet planen',instruction:'Unterscheide Beobachtung, Berechnung und eine noch offene Frage.',categories:['Angabe im Modell','Aus den Angaben berechnet','Noch zu untersuchen'],items:[{text:'Betrieb A nutzt 2 ha Anbaufläche.',answer:'Angabe im Modell',feedback:'Diese Fläche steht unmittelbar in der Tabelle.'},{text:'Angebot A kostet 2 € pro kg.',answer:'Aus den Angaben berechnet',feedback:'4 € geteilt durch 2 kg ergibt 2 € pro kg.'},{text:'Welches Transportmittel wurde für die Äpfel verwendet?',answer:'Noch zu untersuchen',feedback:'Dazu enthalten die Angebote keine Angabe.'}],writing:'Deine Gruppe benötigt 1 kg Äpfel. Vergleiche die zwei Angebote aus Abschnitt 4. Berechne die Kosten pro kg, entscheide dich vorläufig und begründe mit zwei Kriterien. Nenne zwei fehlende Informationen. Zeichne zusätzlich eine mögliche Kette vom Apfelbaum bis zur Jausenbox; kennzeichne unbekannte Orte als unbekannt.',rubric:['Beide Kilopreise sind richtig berechnet.','Meine Wahl berücksichtigt benötigte Menge und ein weiteres Kriterium.','Ich unterscheide bekannte Angaben und zwei offene Fragen.','Meine Kette enthält Anbau, Weitergabe oder Handel und Nutzung.'],model:'Beide Angebote kosten 2 €/kg. Ich wähle vorläufig B, weil wir genau 1 kg brauchen und das Angebot diese Menge enthält. A wäre eine Alternative, wenn wir die Packung teilen könnten; seine Herkunft aus der Umgebung ist bekannt. Für eine Umweltbewertung fehlen bei beiden Transportmittel und Lagerdauer. Mögliche Kette: Obstbaubetrieb (genauer Ort unbekannt) → Sortieren und Verpacken → Geschäft → Gruppe → Jausenbox. Eine andere begründete Wahl ist möglich.'}};
const data=JSON.parse(fs.readFileSync(path.join(root,'lang/de.json'),'utf8'));data[id]=topic;fs.writeFileSync(path.join(root,'lang/de.json'),JSON.stringify(data,null,2)+'\n');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'js/curriculum.js'),'utf8'),ctx);const list=ctx.window.SCIVERSE_CURRICULUM.geographie.topics;const entry={id,title:topic.title,grade:'5. Schulstufe (1. Kl.)',category:'Ernährung und Landwirtschaft'};const index=list.findIndex(t=>t.id===id);if(index>=0)list[index]=entry;else list.splice(list.findIndex(t=>t.id==='geo_2_wirtschaften')+1,0,entry);fs.writeFileSync(path.join(root,'js/curriculum.js'),'// Gemeinsame Kapitelordnung für Navigation und Lernbereich.\nwindow.SCIVERSE_CURRICULUM = '+JSON.stringify(ctx.window.SCIVERSE_CURRICULUM,null,2)+';\n');
console.log('Added food and agriculture geography: four sections, eight questions, evidence workshop and study-plan entry.');

require('./complete_food_climate.js');
