const fs=require('fs'),path=require('path'),vm=require('vm'),root=path.join(__dirname,'..'),id='geo_1_naturgefahren';
const lab=`<div class="interactive-zone" data-geo-experiment="flood"><h3>Standorte im Hochwassermodell</h3><p>Vier fiktive Häuser liegen auf verschiedenen Höhen. Alle Zahlen sind frei gewählte Modelleinheiten, keine Meterangaben oder echten Pegel. Regel: Erreicht oder überschreitet der Wasserstand die angegebene Bodenhöhe, gilt das Haus als überflutet. Strömung, Schutzbauten und Dauer werden nicht berechnet. Stelle zuerst eine Vermutung auf: Was verändert eine Verlegung der beiden niedrigen Häuser? Was verändert eine Warnung?</p><label>Wasserstand <select data-water-level><option value="1">1 – niedriger Modellstand</option><option value="3" selected>3 – mittlerer Modellstand</option><option value="5">5 – höherer Modellstand</option></select></label><p><label><input type="checkbox" data-relocate> Standorte A und B auf Höhe 6 verlegen</label></p><p><label><input type="checkbox" data-warning> Rechtzeitige, verständliche Warnung vorhanden</label></p><table><caption>Fiktive Standorte und Überflutung nach der Modellregel</caption><thead><tr><th scope="col">Haus</th><th scope="col">Bodenhöhe</th><th scope="col">Ergebnis</th></tr></thead><tbody data-flood-rows></tbody></table><button type="button" data-reset>Modell zurücksetzen</button><p data-status role="status" aria-live="polite" aria-atomic="true"></p><p>Das Verlegen vorhandener Gebäude ist in Wirklichkeit aufwendig und nicht überall möglich. Auch höher gelegene Standorte sind nicht gegen jede denkbare Naturgefahr geschützt. Nutze dieses Modell nicht zur Beurteilung deines Wohnorts.</p></div>`;
const blocks=[
 ['Naturereignis, Gefahr und Risiko',`<p>Starker Regen, ein Erdbeben oder ein Felssturz sind Naturereignisse. Eine Naturgefahr beschreibt die Möglichkeit, dass ein natürlicher Vorgang Menschen, Gebäude, Infrastruktur oder Umwelt schädigt. Beim Risiko fragen wir, wie wahrscheinlich ein schädigendes Ereignis ist und welche Folgen es haben könnte.</p><p>Für die möglichen Folgen ist wichtig, <strong>wer oder was im betroffenen Gebiet liegt</strong> und <strong>wie verletzlich</strong> diese Menschen und Dinge sind. Ein überschwemmter unbebauter Uferstreifen hat andere Folgen als ein überschwemmtes Wohngebiet. Das bedeutet nicht, dass unbebaute Räume wertlos sind. Eine Katastrophe ist eine schwere Störung, deren Bewältigung die Möglichkeiten der betroffenen Gemeinschaft stark beansprucht oder übersteigt.</p>`],
 ['Wie verschiedene Gefahren entstehen',`<p>Bei starkem oder lang anhaltendem Regen kann mehr Wasser abfließen, als ein Gewässer aufnehmen kann: Es tritt über die Ufer. Starkregen kann aber auch abseits von Flüssen Straßen und Gebäude überfluten. Boden, Gefälle, bereits vorhandene Nässe und versiegelte Flächen beeinflussen den Abfluss.</p><p>Bei einer Hangrutschung bewegt sich Boden oder Gestein unter der Schwerkraft hangabwärts. Wasser kann Hänge destabilisieren; nicht jeder nasse Hang rutscht. Ein Erdbeben entsteht durch plötzlich frei werdende Energie in der Erde, häufig durch ruckartige Bewegung an Bruchflächen. Es wird nicht durch Starkregen erklärt.</p><p>Länger anhaltender Wassermangel kann Trockenheit und Dürrefolgen verursachen, etwa Probleme für Landwirtschaft und Wasserversorgung. Beim Vergleichen frage deshalb immer nach dem konkreten Vorgang. Der Klimawandel verändert manche wetter- und klimabedingten Gefahren; daraus folgt weder, dass jedes Einzelereignis allein durch ihn verursacht ist, noch dass alle Naturgefahren dieselbe Ursache haben.</p>`],
 ['Gleiches Ereignis, unterschiedliche Folgen',`<p>Zwei Wohngebiete können vom selben Hochwasser unterschiedlich betroffen sein. Liegen Häuser direkt im Überflutungsbereich? Wie stabil sind Gebäude? Erreichen Warnungen alle Menschen rechtzeitig und verständlich? Sind Unterstützung und sichere Ausweichmöglichkeiten zugänglich? Menschen haben nicht immer die Mittel, ihren Wohnort frei zu wählen oder Schäden selbst zu bewältigen.</p>${lab}<p>Vergleiche im Modell zunächst nur den Standort und lasse den Wasserstand gleich. Vergleiche danach die Warnung. Die Warnung verändert die Zahl der überfluteten Häuser nicht, kann aber für Menschen entscheidend sein. Die Zahl betroffener Häuser allein misst daher nicht das gesamte Risiko.</p>`],
 ['Vorsorge und solidarische Hilfe',`<p>Vorsorge verbindet verschiedene Maßnahmen: gefährdete Flächen bei der Raumplanung berücksichtigen, Wasser Raum geben, passende Schutzbauten errichten und erhalten sowie verständlich warnen und Hilfe organisieren. Schutzbauten haben Grenzen; vollständige Sicherheit gegen alle denkbaren Ereignisse gibt es nicht.</p><p>Ein Wiener Beispiel ist die <strong>Neue Donau</strong>: Bei hohem Wasserstand entlastet sie den Donaustrom, indem sie zusätzlich Wasser ableitet. Sie ist Teil des Hochwasserschutzes. Daraus folgt nicht, dass jeder Ort Wiens vor jeder Art von Überflutung geschützt ist.</p><p>Solidarität heißt, unterschiedliche Bedürfnisse wahrzunehmen: etwa mehrsprachige Informationen oder Unterstützung für Menschen, die einen Ort nicht selbstständig verlassen können. Besprecht mit der Lehrkraft vorhandene schulische Abläufe. Im tatsächlichen Ereignis gelten aktuelle behördliche Hinweise und Anweisungen der Einsatzkräfte. Eine Lernsimulation ersetzt sie nicht.</p>`]
];
const raw=[
 ['Was gehört neben dem möglichen Naturereignis zur Risikobetrachtung?',['Die betroffenen Menschen und Gebäude sowie ihre Verletzlichkeit.','Nur der Name des Flusses.','Nur die Höhe des letzten gemessenen Pegels.'],['Lage, Verletzlichkeit und mögliche Folgen sind wesentlich.','Ein Flussname beschreibt weder Wahrscheinlichkeit noch Folgen.','Ein einzelner Pegelwert beschreibt nicht alle betroffenen Menschen und möglichen Schäden.']],
 ['Warum kann derselbe Wasserstand in zwei Gebieten verschiedene Folgen haben?',['Bebauung, Schutz und Unterstützungsmöglichkeiten können verschieden sein.','Derselbe Wasserstand verursacht überall dieselben Schäden.','Nur die Einwohnerzahl eines ganzen Landes entscheidet.'],['Die örtlichen Bedingungen und Möglichkeiten der Menschen beeinflussen Folgen.','Gebäude und Menschen sind nicht überall gleich betroffen oder verletzlich.','Entscheidend sind auch die konkreten Standorte und Bedingungen vor Ort.']],
 ['Welche Erklärung passt zu einer Hangrutschung?',['Boden oder Gestein bewegt sich durch Schwerkraft hangabwärts.','Ein Fluss verdunstet vollständig.','Jede Bodenbewegung entsteht ausschließlich durch ein Erdbeben.'],['Wasser kann die Stabilität beeinflussen; die Bewegung erfolgt hangabwärts.','Verdunstung beschreibt einen anderen Vorgang.','Hangrutschungen können auch ohne Erdbeben auftreten.']],
 ['Welche Aussage über Starkregen stimmt?',['Überflutungen sind auch abseits von Flüssen möglich.','Nur Häuser direkt an einem großen Fluss können betroffen sein.','Versiegelte Flächen nehmen das gesamte Regenwasser im Boden auf.'],['Wasser kann sich beispielsweise auf Straßen und in Senken sammeln.','Starkregen kann auch andernorts Abfluss und Überflutung auslösen.','Versiegelung begrenzt das direkte Versickern in den Boden.']],
 ['Wasserstand 3, ursprüngliche Bodenhöhen 1, 2, 3 und 4: Wie viele Häuser sind laut Modellregel überflutet?',['Drei.','Zwei.','Vier.'],['Auch Haus C auf Höhe 3 zählt, weil der Wasserstand die Bodenhöhe erreicht.','Die Regel zählt Erreichen oder Überschreiten; Haus C gehört dazu.','Haus D auf Höhe 4 liegt über dem Wasserstand 3.']],
 ['Was verändert die Warnung im Modell bei gleichem Wasserstand und gleichen Standorten?',['Die Vorbereitungsmöglichkeiten, aber nicht die Zahl überfluteter Häuser.','Sie senkt automatisch den Wasserstand.','Sie verlegt die Häuser auf höheres Gelände.'],['Eine Warnung wirkt über Information und Handeln, nicht durch Absenken des Wassers.','Warninformationen leiten selbst kein Wasser ab.','Warnen und Standortverlegung sind unterschiedliche Maßnahmen.']],
 ['Welche Aufgabe hat die Neue Donau beim Hochwasserschutz?',['Sie leitet bei Hochwasser zusätzlich Wasser ab und entlastet die Donau.','Sie verhindert jeden Starkregen in Wien.','Sie macht jede weitere Vorsorge überflüssig.'],['Sie dient als Entlastungsgerinne im Wiener Schutzsystem.','Ein Entlastungsgerinne verändert nicht die Entstehung des Regens.','Schutzsysteme haben Grenzen; andere Gefahren und Vorsorgemaßnahmen bleiben relevant.']],
 ['Welche Maßnahme berücksichtigt unterschiedliche Bedürfnisse?',['Warnungen verständlich vermitteln und benötigte Unterstützung organisieren.','Allen Menschen dieselben Selbsthilfemöglichkeiten unterstellen.','Schäden allein mit falschen persönlichen Entscheidungen erklären.'],['Sprache, Mobilität und verfügbare Unterstützung können unterschiedlich sein.','Menschen haben nicht dieselben Voraussetzungen.','Wohnmöglichkeiten, Infrastruktur und Ressourcen werden dadurch übersehen.']]
];
const questions=raw.map(([question,answers,feedback],i)=>({id:id+'_q'+i,question,answers:answers.map((text,j)=>({text,correct:j===0,pts:0,feedback:feedback[j]}))}));
const topic={title:'🌧️ Naturereignisse und Naturgefahren',subtitle:'Entstehung verstehen, unterschiedliche Folgen untersuchen und Vorsorge begründen.',contentLanguage:'de',script:false,
 learningGoals:['Naturereignis, Naturgefahr und Risiko unterscheiden.','Überflutung, Hangrutschung und Erdbeben unterschiedlichen Vorgängen zuordnen.','Im Modell den Einfluss von Standort und Warnung untersuchen.','Vorsorge und solidarische Unterstützung mit einem Wiener Beispiel erklären.'],prerequisites:['geo_1_karten_raeume','Zahlen vergleichen: kleiner, gleich oder größer.'],summary:['Risiko hängt von möglichen Ereignissen und Folgen ab; betroffene Standorte und Verletzlichkeit spielen dabei eine Rolle.','Überflutung, Hangrutschung und Erdbeben haben unterschiedliche Entstehungsprozesse.','Warnungen senken den Wasserstand nicht, können aber Vorbereitung und Schutz von Menschen ermöglichen.','Neue Donau, Raumplanung, Warnung und Unterstützung zeigen verschiedene Formen der Vorsorge; ein Restrisiko bleibt.'],
 sources:[{title:'RIS: Lehrplan der Mittelschule',url:'https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20007850'},{title:'Bundesministerium: Naturgefahren und ihre Entstehung',url:'https://www.naturgefahren.at/naturgefahrenarten.html'},{title:'GeoSphere Austria: Gravitative Massenbewegungen',url:'https://www.geosphere.at/de/themen/katastrophenschutz/gravitative-massenbewegungen'},{title:'Stadt Wien: Wie funktioniert der Donau-Hochwasserschutz?',url:'https://www.wien.gv.at/umwelt/donau-hochwasserschutz-funktion'}],
 sections:blocks.map(([title,content],i)=>({id:'section'+i,title:(i+1)+'. '+title,content:content+questions.slice(i*2,i*2+2).map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:questions.slice(i*2,i*2+2)})),
 workshop:{title:'5. Einen Vorsorgevorschlag begründen',instruction:'Ordne die Maßnahmen nach ihrer unmittelbaren Wirkung zu.',categories:['Standort berücksichtigen','Wasser ableiten','Menschen informieren und unterstützen'],items:[{text:'Neue Gebäude außerhalb eines untersuchten Überflutungsbereichs planen.',answer:'Standort berücksichtigen',feedback:'Die Planung verändert, welche Gebäude im gefährdeten Bereich liegen.'},{text:'Ein Entlastungsgerinne für zusätzliches Hochwasser vorsehen.',answer:'Wasser ableiten',feedback:'Das Gerinne bietet dem Wasser einen zusätzlichen Abflussweg.'},{text:'Eine verständliche Warnung mit organisierter Unterstützung verbinden.',answer:'Menschen informieren und unterstützen',feedback:'Information und Hilfe können Handeln ermöglichen; sie senken nicht selbst den Wasserstand.'}],writing:'Vergleiche im Modell Wasserstand 3 mit und ohne Verlegung von A und B. Notiere die Zahl der überfluteten Häuser. Erkläre, warum eine Warnung trotzdem wichtig sein kann. Entwirf für eine fiktive Gemeinde zwei verschiedene Vorsorgemaßnahmen und eine Unterstützung für Menschen mit besonderen Bedürfnissen. Nenne eine Grenze deines Vorschlags.',rubric:['Ich vergleiche bei gleichem Wasserstand (3 gegenüber 1 betroffenem Haus).','Ich unterscheide Standortverlegung und Warnung.','Meine Maßnahmen haben unterschiedliche Wirkungen.','Ich berücksichtige Unterstützung und eine Grenze.'],model:'Ohne Verlegung sind A, B und C betroffen, nach Verlegung nur C. Eine Warnung kann Vorbereitung ermöglichen, obwohl C überflutet bleibt. Die Gemeinde könnte gefährdete Flächen von neuer Bebauung freihalten und vorhandene Schutzanlagen fachgerecht erhalten. Verständliche Informationen und organisierte Hilfe sollen auch Menschen erreichen, die Unterstützung benötigen. Grenzen: Verlegung kostet Ressourcen; das Modell berücksichtigt weder Strömung noch das Versagen von Schutzanlagen. Der Vorschlag müsste für echte Orte fachlich geprüft werden.'}};
const data=JSON.parse(fs.readFileSync(path.join(root,'lang/de.json'),'utf8'));data[id]=topic;fs.writeFileSync(path.join(root,'lang/de.json'),JSON.stringify(data,null,2)+'\n');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'js/curriculum.js'),'utf8'),ctx);const list=ctx.window.SCIVERSE_CURRICULUM.geographie.topics,entry={id,title:topic.title,grade:'5. Schulstufe (1. Kl.)',category:'Naturgefahren und Vorsorge'},index=list.findIndex(t=>t.id===id);if(index>=0)list[index]=entry;else list.splice(list.findIndex(t=>t.id==='geo_1_ernaehrung_landwirtschaft')+1,0,entry);fs.writeFileSync(path.join(root,'js/curriculum.js'),'// Gemeinsame Kapitelordnung für Navigation und Lernbereich.\nwindow.SCIVERSE_CURRICULUM = '+JSON.stringify(ctx.window.SCIVERSE_CURRICULUM,null,2)+';\n');
console.log('Added natural hazards: four sections, eight questions, flood exposure model and workshop.');
