const fs=require('fs'),path=require('path'),vm=require('vm'),root=path.join(__dirname,'..');
const study=`<div class="interactive-zone" data-art-study><h3>Bildlabor: eine Änderung, eine Beobachtung</h3><p>Merke dir Variante A. Ändere ein Merkmal und vergleiche. Welche Form zieht deinen Blick an? Was liegt vor oder hinter einer anderen Form? Die selbst erstellte geometrische Studie ist kein historisches Kunstwerk. Der Farbregler verändert Bildschirmfarben, er simuliert keine Mischung von Malfarben.</p><svg viewBox="0 0 400 240" role="img" aria-label="Geometrische Studie"><rect data-ground x="0" y="0" width="400" height="240" fill="#dfd"/><rect x="210" y="55" width="110" height="130" fill="#2454a4"/><circle data-circle cx="145" cy="130" r="50" fill="#c85315"/><path d="M35 205 L180 40" stroke="#252525" stroke-width="9"/></svg><label>Kreisposition <output data-value="x">145</output><input aria-label="Kreisposition" data-setting="x" type="range" min="40" max="340" value="145"></label><label>Kreisradius <output data-value="size">50</output><input aria-label="Kreisradius" data-setting="size" type="range" min="15" max="80" value="50"></label><label>Hintergrundfarbton <output data-value="hue">120</output><input aria-label="Hintergrundfarbton" data-setting="hue" type="range" min="0" max="360" value="120"></label><label>Bildausschnitt (0 = ganz, 1 = enger) <output data-value="crop">0</output><input aria-label="Bildausschnitt" data-setting="crop" type="range" min="0" max="1" value="0"></label><button type="button" data-remember>Variante A merken</button><button type="button" data-compare>Mit A vergleichen</button><button type="button" data-reset>Ausgangsbild</button><p role="status" aria-live="polite" data-status>Deine Varianten bleiben nur während dieses Seitenbesuchs erhalten. Notiere deine Beobachtungen unten im Entwurf.</p></div>`;
const chapters=[
{id:'kunst_1_linie_farbe',title:'🎨 Linie, Farbe, Form',goals:['Linie, Fläche, Form und Farbkontrast unterscheiden.','Mit einer einzelnen Änderung eine Bildwirkung untersuchen.','Eine eigene Bildidee in zwei Varianten gestalten und begründen.'],prior:['Du kannst einfache Formen beschreiben.'],sections:[
['Spuren werden zu Bildern','Ein Strich kann dünn, breit, gebogen, unterbrochen oder gerade sein. Linien können Umrisse bilden, Bewegungen andeuten oder Flächen gliedern. Eine Form kann geometrisch sein, etwa ein Kreis, oder frei entstehen. Auch die freien Stellen zwischen Formen gehören zur Gestaltung: Man nennt sie Zwischenräume oder negative Formen. Zeichne mit demselben Stift fünf möglichst unterschiedliche Linien. Vergleiche Druck, Richtung und Abstand.'],
['Farben und Anordnung erproben','Helle und dunkle Flächen können sich deutlich voneinander abheben. Auch unterschiedliche Farbtöne bilden Kontraste. Die Wirkung hängt vom Umfeld ab: Eine kleine orange Fläche in einem großen blauen Feld kann auffallen. Farben haben keine für alle Menschen und Situationen feste Bedeutung. Untersuche im Bildlabor zuerst die Größe, dann die Position. Notiere jeweils eine Beobachtung und eine Deutung.'],
['Ein Zeichen mit eigener Handschrift','Gestalte deinen Vornamen oder ein erfundenes Wort so, dass seine Form eine Bewegung ausdrückt. Erprobe etwa hüpfende, schwere oder fließende Buchstaben. Zeichne zwei Varianten mit anderem Rhythmus oder Abstand. Lass eine zweite Person beschreiben, was sie erkennt, bevor du deine Absicht erklärst. Überarbeite eine Stelle aufgrund ihrer Rückmeldung.']],experiment:1,
summary:['Linien, Formen, Farben und Zwischenräume wirken zusammen.','Eine einzelne Änderung hilft, ihren Einfluss zu untersuchen.','Eine Gestaltungsabsicht lässt sich an konkreten Merkmalen erklären.'],categories:['Linie','Fläche','Zwischenraum'],items:[['Ein durchgehender dünner Strich.','Linie','Die Spur verläuft entlang einer Richtung.'],['Ein vollständig blau gefülltes Rechteck.','Fläche','Die Farbe bedeckt einen zweidimensionalen Bereich.'],['Die freie Stelle zwischen zwei Buchstaben.','Zwischenraum','Auch unbedruckte Bereiche beeinflussen das Gesamtbild.']],task:'Gestalte das Wort „Sprung“ auf Papier in zwei Varianten. Nutze unterschiedliche Linien und Abstände. Notiere hier deine Bildabsicht, die wichtigste Änderung und eine Rückmeldung. Du musst nichts hochladen.',rubric:['Ich habe zwei Varianten ausprobiert.','Meine Begründung nennt sichtbare Merkmale.','Ich habe eine Rückmeldung geprüft und eine Entscheidung dazu getroffen.'],model:'In A stehen alle Buchstaben auf einer Grundlinie. In B wechseln ihre Höhen und die Abstände werden größer. Dadurch kann B wie eine Folge von Sprüngen wirken. Eine Leserin erkannte das Wort nicht sofort; ich habe die Buchstabenformen vereinfacht. Andere Lösungen sind ebenso möglich.',questions:[
['Du willst die Wirkung der Kreisgröße untersuchen. Was ist ein guter Vergleich?','Nur den Radius verändern und die übrigen Einstellungen gleich lassen.','Größe, Farbe und Position gleichzeitig verändern.','Nur die Bildüberschrift verändern.','So lässt sich die veränderte Wirkung der Größe zuordnen.','Dann bleibt unklar, welche Änderung die Wirkung verursacht hat.','Eine Überschrift kann die Deutung ändern, prüft aber nicht die Größe.'],
['Welche Aussage beschreibt einen sichtbaren Farbkontrast?','Eine helle Fläche liegt neben einer dunklen.','Das Bild macht mich froh.','Die Person wollte bestimmt Mut ausdrücken.','Helligkeitsunterschiede sind am Bild beschreibbar.','Das ist eine persönliche Wirkung, keine Beschreibung des Kontrasts.','Eine Absicht muss begründet werden und ist nicht allein sichtbar.'],
['Was gehört zur Komposition eines Wortbildes?','Auch die Abstände zwischen den Buchstaben.','Nur die Bedeutung des Wortes.','Nur die verwendete Stiftmarke.','Leere Bereiche beeinflussen Rhythmus und Lesbarkeit.','Der Inhalt zählt, aber die Anordnung ist ebenfalls Gestaltung.','Ein Werkzeug beeinflusst Spuren; die Marke erklärt die Anordnung nicht.'],
['Zwei Personen deuten dieselbe Farbe unterschiedlich. Was folgt daraus?','Ich frage nach ihren Erfahrungen und nach dem Bildzusammenhang.','Eine Person muss die einzig richtige Farbbedeutung lernen.','Farben beeinflussen Bilder daher überhaupt nicht.','Wirkungen können vom Kontext und von Erfahrungen abhängen.','Farbbedeutungen sind nicht überall und für alle gleich.','Unterschiedliche Deutungen schließen eine Wirkung nicht aus.']]
},
{id:'kunst_1_wahrnehmen',title:'🖼️ Bilder wahrnehmen',goals:['Beschreibung, Deutung und Wertung auseinanderhalten.','Eine Bilddeutung mit sichtbaren Merkmalen begründen.','Mit einer Bildfolge eine eigene Geschichte erzählen.'],prior:['Linien, Formen und Farben benennen.'],sections:[
['Erst genau hinsehen','Beschreibe zunächst, was sichtbar ist: Formen, Farben, Positionen, Größen und Überschneidungen. „Der Kreis liegt links vom Rechteck“ beschreibt. „Der Kreis flieht“ deutet. „Mir gefällt das Bild“ wertet. Alle drei können Teil eines Gesprächs sein; sie sollten nicht verwechselt werden. Betrachte die geometrische Studie eine halbe Minute. Notiere drei Beschreibungen, ohne eine Geschichte hinzuzufügen.'],
['Deutungen begründen','Ein Bild kann mehrere Deutungen zulassen. Begründe deine Lesart mit sichtbaren Merkmalen und prüfe eine Alternative. Ein diagonaler Strich könnte Bewegung nahelegen; er beweist keine bestimmte Handlung. Bildtitel, Begleittext und Präsentationsort beeinflussen die Deutung. Vergleiche für die Studie die erfundenen Titel „Begegnung“ und „Hindernis“. Was bleibt sichtbar gleich, was deutest du anders?'],
['Mit Bildern erzählen','Eine Geschichte braucht keine Sprechblasen: Wiederkehrende Formen, veränderte Abstände und eine Reihenfolge können einen Ablauf zeigen. Zeichne auf drei gleich große Zettel Anfang, Veränderung und Ende einer Begegnung zweier Formen. Lass die Reihenfolge zunächst offen und bitte jemanden, sie zu ordnen. Besprich, welche sichtbaren Hinweise geholfen haben.']],experiment:0,
summary:['Beschreiben nennt Sichtbares; Deuten erschließt Bedeutung; Werten formuliert ein Urteil.','Eine Deutung braucht Bezüge zum Bild.','Reihenfolge und Veränderungen können eine Geschichte vermitteln.'],categories:['Beschreibung','Deutung','Wertung'],items:[['Der Kreis verdeckt einen Teil des Rechtecks.','Beschreibung','Die Überdeckung lässt sich am Bild überprüfen.'],['Die Formen scheinen miteinander zu streiten.','Deutung','Eine menschliche Handlung wird in Formen gelesen.'],['Die zweite Variante gefällt mir besser.','Wertung','Hier wird eine persönliche Einschätzung formuliert.']],task:'Erfinde eine Bildgeschichte aus drei Zeichnungen mit zwei Formen. Beschreibe ein Bild sachlich, deute anschließend die Handlung und nenne die Rückmeldung einer anderen Person. Bewahre die Zeichnungen in deiner Mappe auf.',rubric:['Meine Beschreibung nennt sichtbare Merkmale.','Meine Deutung verweist auf mindestens zwei Merkmale.','Ich unterscheide fremde Rückmeldung und eigene Absicht.'],model:'Im zweiten Bild liegen die Formen dichter beieinander und überdecken sich. Ich deute das als Begegnung. Eine andere Person sah einen Zusammenstoß. Deshalb habe ich im dritten Bild die Formen nebeneinander angeordnet; diese Änderung kann die freundliche Lesart unterstützen, aber nicht erzwingen.',questions:[
['Welche Aussage ist eine Beschreibung?','Der dunkle Strich verläuft diagonal.','Der Strich wirkt gefährlich.','Der Strich ist die beste Stelle.','Richtung und Farbe sind sichtbar.','Gefahr ist eine Deutung der Wirkung.','„Beste“ ist eine Bewertung.'],
['Wie prüfst du die Deutung „Die Formen bewegen sich“?','Ich suche sichtbare Hinweise und vergleiche eine andere Lesart.','Ich wiederhole die Behauptung lauter.','Ich suche nur nach einer Unterschrift.','Richtung, Wiederholung oder Abstand können die Lesart stützen.','Wiederholung ersetzt keine Begründung.','Eine Signatur belegt keine Bewegung.'],
['Was kann ein neuer Bildtitel verändern?','Die Deutung, auch wenn die sichtbaren Formen gleich bleiben.','Die tatsächlichen Positionen der Formen.','Automatisch die Entstehungszeit des Bildes.','Wörter lenken Erwartungen und Aufmerksamkeit.','Die Formen ändern sich durch den Titel nicht.','Ein Titel ändert keine historischen Tatsachen.'],
['Wozu lässt du deine Bildfolge von jemand anderem ordnen?','Um zu prüfen, ob die erzählerischen Hinweise verständlich sind.','Um jede abweichende Lesart zu verbieten.','Um auf eine eigene Bildidee verzichten zu können.','Rückmeldungen zeigen, wie die Folge gelesen wird.','Andere Lesarten können Hinweise für die Überarbeitung geben.','Du entscheidest weiterhin über deine Gestaltung.']]
},
{id:'kunst_2_raum',title:'🧊 Raum, Körper, Perspektive',goals:['Überdeckung, Größenunterschied und Perspektive als Raumhinweise erkennen.','Einen einfachen Raum entwerfen und seine Nutzung erklären.','Die Wirkung eines Raums aus mehreren Blickwinkeln untersuchen.'],prior:['Flächen und Körper unterscheiden.'],sections:[
['Tiefe auf einer Fläche','Eine Zeichnung ist flach, kann aber Raum nahelegen. Verdeckte Umrisse lassen eine Form hinter einer anderen erscheinen. Bei gleich großen Gegenständen wirken kleinere Darstellungen häufig weiter entfernt. Das ist ein Gestaltungsmittel, kein Beweis für die echte Größe. Zeichne drei gleichartige Becher so, dass sich ihre Umrisse teilweise überdecken. Entscheide bewusst über Vorder- und Hintergrund.'],
['Mit einem Fluchtpunkt konstruieren','Bei einer einfachen Zentralperspektive liegt ein Fluchtpunkt auf dem Horizont, der die Augenhöhe bezeichnet. Linien, die im dargestellten Raum parallel in die Tiefe laufen, treffen sich in dieser Konstruktion im Fluchtpunkt. Nicht alle Linien laufen dorthin: Die Vorderseite eines frontal gezeichneten Rechtecks behält horizontale und vertikale Kanten. Zeichne ein Rechteck, setze außerhalb davon einen Fluchtpunkt und verbinde seine Ecken damit. Begrenze die Tiefe durch eine kleinere Rückseite.'],
['Räume für Menschen','Ein Schulraum wird durch Eingänge, Licht, Möbel und Wege geprägt. Ein schöner Plan kann trotzdem schlecht nutzbar sein, etwa wenn ein Durchgang zugestellt ist. Entwirf auf Papier einen Leseplatz im Schulhaus. Prüfe Ruhe, Orientierung, Bewegungsfreiheit und unterschiedliche Körpergrößen. Baue ein kleines Modell aus sauberem Restkarton. Nutze für Schnitte nur die im Unterricht freigegebenen Werkzeuge.']],summary:['Überdeckung und Größenstaffelung können Tiefe zeigen.','In der einfachen Zentralperspektive treffen bestimmte Tiefenlinien im Fluchtpunkt zusammen.','Raumgestaltung verbindet Wirkung und Nutzung.'],categories:['Überdeckung','Perspektive','Nutzung'],items:[['Eine vordere Form unterbricht den Umriss der hinteren.','Überdeckung','Das verdeckte Stück wird als dahinterliegend gelesen.'],['Parallele Tiefenkanten laufen im Bild zum Fluchtpunkt.','Perspektive','Die Konstruktion stellt räumliche Tiefe dar.'],['Der Durchgang muss mit einer Tasche passierbar bleiben.','Nutzung','Hier wird eine praktische Anforderung geprüft.']],task:'Entwirf einen Leseplatz als Grundriss und als räumliche Skizze oder Kartonmodell. Beschrifte Eingang und Sitzfläche. Notiere hier zwei Entscheidungen, eine Nutzungsprüfung und eine Verbesserung.',rubric:['Meine Darstellungen zeigen dieselbe Grundidee.','Wege und Nutzung sind berücksichtigt.','Ich habe meinen Entwurf anhand einer konkreten Anforderung verbessert.'],model:'Der Grundriss zeigt eine Sitzfläche neben dem Fenster und einen freien Weg zur Tür. In der Raumsch Skizze überdeckt der vordere Tisch einen Teil des Regals. Nach dem Test mit einer Modellfigur habe ich den Durchgang verbreitert. Ein Modell ist nur ein Entwurf und keine bauliche Freigabe.',questions:[
['Ein Kreis verdeckt die rechte Kante eines Rechtecks. Welche Raumwirkung liegt nahe?','Der Kreis erscheint vor dem Rechteck.','Der Kreis muss in Wirklichkeit größer sein.','Das Rechteck liegt dadurch sicher vor dem Kreis.','Die unterbrochene Kante ist ein Hinweis auf Überdeckung.','Darstellungsgröße und tatsächliche Größe sind nicht dasselbe.','Die verdeckte Form erscheint üblicherweise dahinter.'],
['Welche Linien laufen in der beschriebenen Einpunktperspektive zum Fluchtpunkt?','Die parallel in die Tiefe gerichteten Kanten.','Jede Kante, auch die senkrechten Vorderkanten.','Nur die Bildränder.','Die Aussage gilt für die gewählte Tiefenrichtung.','Vertikale Vorderkanten bleiben in dieser Konstruktion vertikal.','Bildränder bestimmen nicht die Tiefenrichtung.'],
['Was stellt der Horizont in dieser Konstruktion dar?','Die Augenhöhe der betrachtenden Person.','Immer den unteren Papierrand.','Immer die Oberkante des höchsten Gebäudes.','Eine veränderte Augenhöhe verändert die Sicht auf den Raum.','Die Augenhöhe kann an unterschiedlichen Stellen im Bild liegen.','Gebäudehöhe und Augenhöhe sind verschieden.'],
['Was ist eine sinnvolle Prüfung des Leseplatzmodells?','Ob die Wege frei bleiben und die Sitzfläche erreichbar ist.','Ob es ausschließlich die Lieblingsfarbe der entwerfenden Person hat.','Ob es genau so aussieht wie das erste Modell.','Die Prüfung bezieht sich auf die Nutzung.','Farbe allein belegt keine gute Nutzbarkeit.','Überarbeitungen können die Idee verbessern.']]
},
{id:'kunst_2_design',title:'🪑 Design und Alltagsobjekte',goals:['Form, Funktion und Zielgruppe eines Entwurfs verbinden.','Ein verständliches Zeichen entwickeln und erproben.','Materialentscheidungen und Überarbeitungen begründen.'],prior:['Beobachtung und Bewertung unterscheiden.'],sections:[
['Gestalten für einen Zweck','Design umfasst die Gestaltung von Dingen, Zeichen und Abläufen. Ein Trinkbecher soll beispielsweise greifbar, standfest und passend zur Nutzung sein. Seine Form kann eine Funktion unterstützen oder erschweren. Beschreibe zwei Gegenstände im Klassenraum. Wer benutzt sie, wozu und unter welchen Bedingungen? Unterscheide eine überprüfbare Anforderung von deinem Geschmack.'],
['Ein Zeichen verständlich machen','Ein Piktogramm vereinfacht eine Handlung oder einen Gegenstand auf wenige erkennbare Merkmale. Weniger Details helfen nur, solange die Aussage verständlich bleibt. Entwirf ein Zeichen für „Bücher zurückstellen“. Teste es ohne Erklärung mit zwei Personen. Ein erfundenes Schulzeichen ersetzt keine vorgeschriebenen Sicherheitszeichen. Notiere die Antworten und verbessere eine missverständliche Stelle.'],
['Prototyp und Material','Ein Prototyp ist ein Versuch, mit dem eine Idee überprüft wird. Baue aus vorhandenem Papier eine Ablage für drei leichte Zettel. Prüfe Standfestigkeit, Zugriff und Materialverbrauch. Falten können Papier stabilisieren; mehr Material ist nicht automatisch die beste Lösung. Ein gescheiterter Versuch liefert Hinweise. Zerlege ihn und verwende brauchbare Teile für die nächste Version.']],summary:['Design verbindet Form, Zweck und die Bedürfnisse der Nutzenden.','Ein Zeichen muss an seiner tatsächlichen Verständlichkeit geprüft werden.','Ein Prototyp hilft, Anforderungen praktisch zu testen.'],categories:['Funktion','Form','Erprobung'],items:[['Die Ablage soll drei Zettel halten.','Funktion','Der Satz benennt den vorgesehenen Zweck.'],['Die Seitenflächen sind dreieckig gefaltet.','Form','Die sichtbare Gestalt wird beschrieben.'],['Zwei Personen probieren aus, ob sie einen Zettel entnehmen können.','Erprobung','Hier wird die Nutzung tatsächlich getestet.']],task:'Entwirf eine Papierablage und ein zugehöriges Zeichen. Halte Anforderung, Material, erste Version, Testergebnis und Änderung fest. Zeichnung und Modell bleiben in deiner Mappe; dein Prozessbericht kann hier gespeichert werden.',rubric:['Meine Anforderung ist überprüfbar.','Ich habe den Entwurf durch eine andere Person testen lassen.','Meine Änderung reagiert auf das Testergebnis.'],model:'Die Ablage soll drei A6-Zettel halten. Version A kippte beim Herausziehen. In B habe ich die Standfläche verbreitert. Das Zeichen zeigte zuerst nur ein Rechteck; eine angedeutete Papierkante machte es für die Testpersonen verständlicher.',questions:[
['Welche Anforderung lässt sich testen?','Die Ablage hält drei Zettel, ohne umzukippen.','Die Ablage ist für alle Menschen schön.','Die Ablage sieht irgendwie modern aus.','Anzahl und Standfestigkeit können praktisch geprüft werden.','Geschmack ist unterschiedlich; „für alle“ ist keine klare Prüfanweisung.','„Irgendwie modern“ braucht genauere Kriterien.'],
['Wie prüfst du ein neues Piktogramm?','Ich lasse andere die Bedeutung ohne Voraberklärung nennen.','Ich erkläre zuerst die Lösung und frage dann, ob sie verständlich war.','Ich zähle nur seine Linien.','So werden tatsächliche Lesarten sichtbar.','Die Erklärung beeinflusst den Test.','Wenige Linien allein garantieren keine Verständlichkeit.'],
['Was ist ein Prototyp?','Ein Versuch zur Prüfung einer Gestaltungsidee.','Immer das endgültige verkaufte Produkt.','Nur eine Beschreibung ohne mögliche Erprobung.','Ein Prototyp macht Entscheidungen überprüfbar.','Er kann noch verändert werden.','Eine Beschreibung kann ergänzen; wichtig ist die überprüfbare Umsetzung.'],
['Das Modell kippt. Was ist ein sinnvoller nächster Schritt?','Die Ursache untersuchen und die Standfläche gezielt verändern.','Nur die Farbe wechseln und denselben Test auslassen.','Das Testergebnis aus dem Bericht weglassen.','Die Änderung richtet sich auf die beobachtete Schwäche.','Eine Farbe verbessert die Standfläche nicht automatisch.','Auch Fehlversuche gehören zum Lernprozess.']]
},
{id:'kunst_3_foto_medien',title:'📷 Foto, Film und digitale Bilder',goals:['Ausschnitt und Perspektive als Entscheidungen erkennen.','Beobachtbare Bildinformation und ergänzende Behauptung trennen.','Eine kurze Bildfolge mit bewusster Wirkung gestalten.'],prior:['Bildbeschreibung und Deutung unterscheiden.'],sections:[
['Ein Bild zeigt einen Ausschnitt','Eine Aufnahme zeigt, was innerhalb eines gewählten Rahmens liegt. Was außerhalb liegt, bleibt unsichtbar. Ein enger Ausschnitt kann Nähe schaffen oder Zusammenhänge weglassen. Verändere im Bildlabor nur den Ausschnitt. Notiere zuerst, welche Teile verschwinden, und dann, wie sich dein Eindruck ändert. Ein Ausschnitt kann korrekt aufgenommen sein und trotzdem eine einseitige Geschichte nahelegen.'],
['Standpunkt und Montage','Augenhöhe, Blick von oben und Blick von unten verändern die Darstellung eines Gegenstands. Eine Nahaufnahme zeigt Details; eine weitere Einstellung zeigt mehr Umgebung. In einer Bildfolge beeinflusst auch die Reihenfolge die Erzählung. Zeichne drei Einstellungen eines fallenden Bleistifts: Tisch, Hand, Boden. Vertausche zwei Bilder. Welche Ursache vermutest du nun? Ohne weitere Informationen ist die vermutete Ursache noch kein Beweis.'],
['Verantwortlich mit Bildern arbeiten','Erstelle für die Aufgabe eigene Zeichnungen oder fotografiere Gegenstände statt Personen. Notiere Aufnahmeort, Datum und Bearbeitungen. Wenn du ein fremdes Bild nutzen möchtest, müssen Quelle und erlaubte Nutzung vor einer Veröffentlichung geprüft werden; eine Quellenangabe allein ist keine Erlaubnis. Für diese Übung genügt deine private Mappe. Vergleiche bei einer fraglichen Bildmeldung Originalquelle, Begleittext und weitere Belege.']],experiment:0,
summary:['Ausschnitt, Standpunkt und Reihenfolge beeinflussen die Wirkung.','Was außerhalb des Bildes liegt, ist durch das Bild nicht belegt.','Eigene Bilder, dokumentierte Bearbeitung und geprüfte Quellen erleichtern verantwortliches Arbeiten.'],categories:['Ausschnitt','Standpunkt','Montage'],items:[['Die Ränder einer Aufnahme werden weggeschnitten.','Ausschnitt','Der sichtbare Bereich wird enger.'],['Die Kamera blickt von unten auf das Objekt.','Standpunkt','Die Position zur aufgenommenen Sache verändert sich.'],['Drei Aufnahmen werden in anderer Reihenfolge gezeigt.','Montage','Die Verbindung der Bilder wird verändert.']],task:'Erstelle drei Zeichnungen oder eigene Sachfotos zu einer kleinen Handlung. Gestalte zwei Reihenfolgen oder zwei Ausschnitte. Notiere, was sichtbar gleich bleibt und welche Deutung sich ändert. Keine Aufnahme oder Veröffentlichung anderer Personen ist nötig.',rubric:['Ich benenne meine konkrete Bildentscheidung.','Ich unterscheide sichtbare Information und vermutete Ursache.','Eigene Aufnahmen und Änderungen sind dokumentiert.'],model:'A zeigt den Bleistift am Tischrand und dann am Boden. B beginnt mit dem Bleistift am Boden und endet am Tisch. Beide Folgen nutzen dieselben Ansichten, erzählen aber unterschiedliche Abläufe. Keine der Folgen belegt, wer den Gegenstand bewegt hat.',questions:[
['Was lässt sich aus einem engen Ausschnitt sicher ableiten?','Nur Informationen über den sichtbaren Bereich.','Dass außerhalb keine weiteren Personen oder Gegenstände vorhanden waren.','Dass das Bild unbearbeitet ist.','Fehlender Kontext muss anderweitig geprüft werden.','Nicht sichtbar bedeutet nicht nicht vorhanden.','Ein Ausschnitt belegt keine Bearbeitungsgeschichte.'],
['Wodurch kann dieselbe Bildserie eine andere Geschichte nahelegen?','Durch eine andere Reihenfolge.','Nur durch eine andere Dateigröße.','Nur durch das Umbenennen des Kameraordners.','Reihenfolge verändert zeitliche und ursächliche Erwartungen.','Dateigröße allein gestaltet keine Bildfolge.','Der Ordnername ist für die sichtbare Folge nicht entscheidend.'],
['Welche Aussage bleibt eine Vermutung?','Die Person außerhalb des Bildes hat den Bleistift fallen gelassen.','Der Bleistift liegt im sichtbaren Bild auf dem Boden.','Der Ausschnitt zeigt keinen Tisch.','Die handelnde Person ist nicht sichtbar; die Ursache braucht weitere Belege.','Bei entsprechender Aufnahme ist das direkt beschreibbar.','Auch das Fehlen eines sichtbaren Tisches lässt sich am Ausschnitt beschreiben.'],
['Wie machst du deine Bearbeitung nachvollziehbar?','Ich bewahre das Original auf und beschreibe Ausschnitt und Änderung.','Ich lösche die Ausgangsversion und nenne das Ergebnis unbearbeitet.','Ich notiere nur die verwendete Lieblingsfarbe.','Original und Änderungsbeschreibung ermöglichen einen Vergleich.','So würde der Vergleich erschwert und die Bearbeitung falsch dargestellt.','Die Farbe allein dokumentiert die Änderung nicht.']]
},
{id:'kunst_3_kunstgeschichte',title:'🏛️ Kunst und Gesellschaft',goals:['Werk, Entstehungszusammenhang und heutige Präsentation unterscheiden.','Auftrag, Publikum und Material in eine Betrachtung einbeziehen.','Einen eigenen Ausstellungsbeitrag begründet arrangieren.'],prior:['Bilddeutungen an sichtbaren Merkmalen begründen.'],sections:[
['Ein Werk hat einen Zusammenhang','Für die Betrachtung eines Werks helfen Fragen: Wer hat es wann, wo und für wen geschaffen? Welche Materialien und Aufgaben spielten eine Rolle? Nicht jede Antwort ist bekannt. Trenne belegte Informationen von Vermutungen. Stile sind hilfreiche Ordnungsvorschläge, aber kein Ersatz für genaues Hinsehen. Ein Werk kann zugleich mehrere Traditionen aufnehmen oder Erwartungen bewusst verändern.'],
['Auftrag und Freiheit','Vergleiche zwei erfundene Aufgaben: Ein Schulplakat soll den Weg zur Bibliothek zeigen. Ein freies Bild soll einen persönlichen Lieblingsort ausdrücken. Beim Plakat ist Verständlichkeit für andere ein wichtiges Kriterium. Beim freien Bild können Mehrdeutigkeit und persönliche Erfahrung wichtig sein. Auch Auftragsarbeit erlaubt Entscheidungen; freie Arbeit entsteht ebenfalls unter Bedingungen wie Zeit, Material und Ausstellungsraum.'],
['Begegnung und Präsentation','Suche mit deiner Lehrkraft ein Original im Schulhaus, im öffentlichen Raum oder in einem Wiener Museum. Bei einem digitalen Rundgang notierst du, dass du eine Reproduktion betrachtest. Größe, Oberfläche und räumliche Wirkung können anders erfahrbar sein. Dokumentiere Titel, Urheber:in, Datierung und Quelle, soweit angegeben. Ordne anschließend zwei eigene Arbeiten als kleine Ausstellung an. Begründe Reihenfolge, Abstand und Beschriftung.']],summary:['Kontextinformationen ergänzen die genaue Betrachtung.','Auftrag und Publikum beeinflussen Gestaltungsspielräume.','Ein Original und seine digitale Reproduktion ermöglichen unterschiedliche Erfahrungen.'],categories:['Beleg','Vermutung','Präsentation'],items:[['Die Werkbeschriftung nennt Karton als Material.','Beleg','Das ist eine zuordenbare Quelleninformation; eigene Beobachtung kann sie ergänzen.'],['Vielleicht sollte das Werk die Auftraggeberin beeindrucken.','Vermutung','Die Absicht wird ohne weiteren Nachweis angenommen.'],['Zwei Bilder hängen auf Augenhöhe mit gleichem Abstand.','Präsentation','Ihre Anordnung im Ausstellungsraum wird beschrieben.']],task:'Betrachte ein von deiner Lehrkraft ausgewähltes Werk oder eine Museumsabbildung. Notiere Quelle, drei Beobachtungen, eine begründete Deutung und eine offene Frage. Entwirf danach eine Beschriftung für eine eigene Arbeit und eine kleine Anordnung mit einer zweiten Arbeit.',rubric:['Ich unterscheide Quellenangabe und eigene Deutung.','Unbekannte Informationen sind als unbekannt markiert.','Meine Anordnung ist begründet und respektiert andere Arbeiten.'],model:'Auf der Beschriftung steht „Karton, undatiert“. Ich sehe gefaltete Kanten und verschieden große Öffnungen. Das erinnert mich an eine Stadt, belegt aber noch keine Absicht der gestaltenden Person. Meine offene Frage betrifft den Entstehungsanlass. Zwei eigene Raumstudien stelle ich nebeneinander, damit Unterschiede vergleichbar sind.',questions:[
['Eine Datierung fehlt. Wie gehst du damit um?','Ich kennzeichne sie als unbekannt und suche nach einer verlässlichen Quelle.','Ich erfinde ein plausibles Jahr.','Ich übernehme das Jahr meines Museumsbesuchs als Entstehungsjahr.','So bleiben belegte und unbekannte Informationen getrennt.','Plausibilität ersetzt keinen Nachweis.','Besuch und Entstehung sind verschiedene Ereignisse.'],
['Was ist beim Wegweiser-Plakat besonders wichtig?','Ob das vorgesehene Publikum den Weg erkennen kann.','Ob jede Information möglichst mehrdeutig bleibt.','Ob es nur der entwerfenden Person verständlich ist.','Der Auftrag verlangt Orientierung für andere.','Mehrdeutigkeit erschwert hier die Funktion.','Die Zielgruppe geht über die entwerfende Person hinaus.'],
['Was kann eine Bildschirmabbildung eines Werks nur eingeschränkt vermitteln?','Seine tatsächliche Größe und körperliche Oberflächenwirkung.','Dass es sichtbare Formen enthält.','Dass Bereiche unterschiedliche Helligkeiten zeigen.','Maßstab, Material und Licht können anders erfahrbar sein.','Formen können auch in einer Reproduktion betrachtet werden.','Helligkeitsunterschiede sind grundsätzlich sichtbar, auch wenn die Wiedergabe abweichen kann.'],
['Warum beschriftest du deine eigenen Arbeiten?','Damit Betrachtende Titel, Material und relevante Kontextinformationen erhalten.','Damit keine andere Deutung mehr erlaubt ist.','Damit die Anordnung keine Rolle mehr spielt.','Eine Beschriftung bietet Orientierung.','Sie muss nicht jede Deutung festlegen.','Raum und Anordnung beeinflussen die Wahrnehmung weiterhin.']]
},
{id:'kunst_4_portfolio',title:'📁 Portfolio und eigenes Projekt',goals:['Ein eigenes Vorhaben planen und begründet umsetzen.','Versuche, Entscheidungen und Überarbeitungen dokumentieren.','Ein Portfolio auswählen, präsentieren und reflektieren.'],prior:['Gestaltungsmittel gezielt einsetzen und Rückmeldungen auswerten.'],sections:[
['Von der Frage zur Idee','Wähle eine Frage, die du bildnerisch untersuchen möchtest: etwa „Wo fühle ich mich in meinem Stadtteil zugehörig?“ Du kannst real beobachtete und erfundene Orte verbinden. Bestimme Publikum, Medium, verfügbares Material und Zeitrahmen. Formuliere zwei oder drei Kriterien, die zu deiner Absicht passen. Ein Projekt darf sich entwickeln; notiere, warum du den Plan veränderst.'],
['Prozess statt nur Endprodukt','Ein Portfolio ist eine begründete Auswahl, die Lernen sichtbar macht. Sammle Recherche, Skizzen, Materialproben, Zwischenstände und Rückmeldungen. Wähle später auch einen Versuch, der nicht funktioniert hat, wenn er eine Entscheidung erklärt. Fotografiere eigene Modelle oder bewahre Teile auf. Ordne alles mit Datum und kurzem Kommentar: Was habe ich versucht, beobachtet und geändert?'],
['Zeigen und weiterdenken','Plane eine Präsentation im Klassenraum mit Titel, kurzen Erläuterungen und einer nachvollziehbaren Reihenfolge. Teste, ob die Beschriftung aus der vorgesehenen Entfernung lesbar ist. Bitte um Rückmeldung zu deinen Kriterien. Trenne das Urteil über eine Arbeit von einem Urteil über eine Person. Formuliere zum Schluss eine Stärke, eine offene Frage und einen konkreten nächsten Versuch.']],summary:['Ein Projekt verbindet eigene Frage, Gestaltung und passende Kriterien.','Ein Portfolio zeigt Entscheidungen und Veränderungen.','Reflexion benennt Belege, Grenzen und nächste Schritte.'],categories:['Planung','Prozessbeleg','Reflexion'],items:[['Ich entscheide mich für eine dreiteilige Collage und zwei Arbeitseinheiten.','Planung','Medium und Zeitrahmen werden festgelegt.'],['Meine Mappe enthält die erste Skizze und die überarbeitete Version.','Prozessbeleg','Die Materialien zeigen eine Entwicklung.'],['Der große Abstand trennt die Figuren stärker als beabsichtigt; ich teste einen kleineren.','Reflexion','Beobachtung und nächster Schritt werden verbunden.']],task:'Plane und realisiere ein Projekt zu einem Ort, einer Erinnerung oder einer Zukunftsvorstellung. Stelle mindestens eine Skizze, einen Versuch, das Ergebnis und eine begründete Überarbeitung zusammen. Speichere hier deinen Projektplan und die abschließende Reflexion; die bildnerischen Arbeiten bleiben in deiner Mappe.',rubric:['Meine Kriterien passen zur eigenen Fragestellung.','Meine Auswahl zeigt mindestens eine Veränderung.','Rückmeldungen werden konkret und wertschätzend verwendet.','Ich begründe einen nächsten Entwicklungsschritt.'],model:'Meine Collage untersucht Nähe und Abstand an einem erfundenen Lieblingsplatz. Im ersten Versuch waren alle Flächen gleich groß. Für die zweite Version vergrößerte ich den zentralen Ort. Das lenkte die Aufmerksamkeit wie beabsichtigt, ließ aber den Weg dorthin verschwinden. Als nächsten Versuch möchte ich diesen Weg durch eine Linie sichtbar machen.',questions:[
['Welche Auswahl zeigt einen Lernprozess besonders gut?','Skizze, begründeter Fehlversuch, Überarbeitung und Ergebnis.','Nur das Ergebnis ohne Erklärung.','Nur eine Liste verwendeter Werkzeuge.','So sind Entwicklung und Entscheidungen nachvollziehbar.','Das Ergebnis allein zeigt die Entwicklung kaum.','Werkzeuge dokumentieren noch keinen Lernweg.'],
['Welche Rückmeldung ist hilfreich?','Die dunkle Fläche zieht meinen Blick zuerst an; war das beabsichtigt?','Du bist einfach unbegabt.','Das ist falsch, weil ich eine andere Lieblingsfarbe habe.','Die Rückmeldung benennt ein Merkmal und fragt nach der Absicht.','Das bewertet die Person und hilft nicht beim Gestalten.','Eigener Geschmack ist kein allgemeines Fehlerkriterium.'],
['Wann ist eine Planänderung gut begründet?','Wenn eine Beobachtung zeigt, dass sie die Bildabsicht besser unterstützt.','Wenn ich damit einen Fehlversuch unsichtbar machen kann.','Nur wenn sich dabei das ganze Thema ändert.','Eine Änderung kann auf erprobte Wirkung reagieren.','Fehlversuche können wichtige Prozessbelege sein.','Auch eine kleine gezielte Änderung kann sinnvoll sein.'],
['Was ist ein konkreter nächster Schritt?','Ich teste dieselbe Anordnung mit kleinerem Abstand zwischen den Figuren.','Ich werde einfach besser.','Ich entscheide nichts, bis allen alles gefällt.','Die Veränderung ist ausführbar und vergleichbar.','Das Ziel bleibt ohne Handlung zu unbestimmt.','Unterschiedliche Sichtweisen sind möglich; du brauchst begründete Entscheidungen.']]
}
];
const data=JSON.parse(fs.readFileSync(path.join(root,'lang/de.json'),'utf8'));
for(const c of chapters){const quizzes=c.questions.map((q,i)=>({id:c.id+'_q'+i,question:q[0],answers:[1,2,3].map((j)=>({text:q[j],correct:j===1,pts:0,feedback:q[j+3]}))}));data[c.id]={title:c.title,subtitle:c.goals[0],contentLanguage:'de',script:false,learningGoals:c.goals,prerequisites:c.prior,summary:c.summary,sources:[{title:'Lehrplan der Mittelschule: Kunst und Gestaltung',url:'https://www.ris.bka.gv.at/NormDokument.wxe?Abfrage=Bundesnormen&Anlage=1&Artikel=&Gesetzesnummer=20007850&Paragraf=&Uebergangsrecht='}],sections:c.sections.map(([title,text],i)=>({id:'section'+i,title:(i+1)+'. '+title,content:'<p>'+text.replace('Raumsch Skizze','räumlichen Skizze')+'</p>'+(c.experiment===i?study:'')+quizzes.filter((_,j)=>Math.min(j,2)===i).map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:quizzes.filter((_,j)=>Math.min(j,2)===i)})),workshop:{title:'4. Gestalten und reflektieren',navLabel:'Gestaltungswerkstatt',instruction:'Prüfe die Begriffe. Bearbeite anschließend den Gestaltungsauftrag auf Papier oder mit geeignetem Material. Der Textentwurf dokumentiert deinen Prozess; er ersetzt nicht die bildnerische Arbeit.',categories:c.categories,items:c.items.map(([text,answer,feedback])=>({text,answer,feedback})),writing:c.task,rubric:c.rubric,model:c.model.replace('Raumsch Skizze','räumlichen Skizze')}};}
fs.writeFileSync(path.join(root,'lang/de.json'),JSON.stringify(data,null,2)+'\n');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'js/curriculum.js'),'utf8'),ctx);ctx.window.SCIVERSE_CURRICULUM.kunst.topics.forEach(t=>{if(data[t.id])delete t.available;});fs.writeFileSync(path.join(root,'js/curriculum.js'),'// Gemeinsame Kapitelordnung für Navigation und Lernbereich.\nwindow.SCIVERSE_CURRICULUM = '+JSON.stringify(ctx.window.SCIVERSE_CURRICULUM,null,2)+';\n');
console.log('Added 7 art chapters with 28 questions, 21 classifications, practical projects and 3 visual studies.');
