const fs=require('fs'),path=require('path'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
const guides={
math2_1_teilbarkeit:[['math1_4_mult_div'],['Teilbarkeit durch 2, 5 und 10 an der letzten Ziffer erkennen.','Den größten gemeinsamen Teiler zweier positiver natürlicher Zahlen bestimmen.','Das kleinste gemeinsame Vielfache mit Vielfachenlisten bestimmen.'],['Teilbar bedeutet: Die Division geht ohne Rest auf.','Der ggT ist der größte gemeinsame positive Teiler. Für 12 und 18 ist er 6.','Das kgV ist das kleinste gemeinsame positive Vielfache. Für 3 und 4 ist es 12.']],
math2_2_brueche:[['math1_8_brueche','math2_1_teilbarkeit'],['Brüche ohne Wertänderung erweitern und kürzen.','Ungleichnamige Brüche mit gemeinsamem Nenner addieren und subtrahieren.','Brüche multiplizieren und durch einen Bruch ungleich 0 dividieren.'],['Erweitern und Kürzen verändern Zähler und Nenner mit demselben Faktor und erhalten den Wert.','Zum Addieren und Subtrahieren zuerst einen gemeinsamen Nenner herstellen; danach nur die Zähler addieren oder subtrahieren.','Beim Multiplizieren gilt Zähler mal Zähler und Nenner mal Nenner. Beim Dividieren wird mit dem Kehrwert des zweiten Bruchs multipliziert. Der Divisor darf nicht 0 sein.']],
math2_3_dezimalzahlen:[['math1_9_dezimalzahlen'],['Dezimalzahlen stellenrichtig addieren und subtrahieren.','Positive Dezimalzahlen auf eine vorgegebene Stelle runden.','Dezimalzahlen mit 10 und 100 multiplizieren und durch 10 dividieren.'],['Bei Addition und Subtraktion stehen gleiche Stellenwerte untereinander.','Beim Runden entscheidet die erste Ziffer rechts von der Rundungsstelle; ab 5 wird aufgerundet.','Multiplikation mit 10 macht jeden Stellenwert zehnmal so groß; Division durch 10 macht ihn zehnmal so klein.']],
math2_4_relative_zahlen:[['math1_3_add_sub'],['Negative Zahlen in Temperatur- und Höhenangaben deuten.','Ganze Zahlen nach ihrer Größe ordnen.','Einfache Additionen und Subtraktionen mit ganzen Zahlen im Bewegungsmodell ausführen.'],['Negative Zahlen liegen auf dem Zahlenstrahl links von 0. Weiter links bedeutet kleiner: −100 < −1 < 0.','3 − 5 = −2: Vom Startwert 3 führen fünf Schritte nach links zu −2.','−15 + 20 = 5: Zwanzig Schritte nach rechts führen von −15 zu 5.']],
math2_5_var_gleichungen:[['math1_7_gleichungen'],['Eine Variable als Platzhalter für einen Zahlenwert verwenden.','Einfache Gleichungen durch gleiche Umformungen auf beiden Seiten lösen.','Die Lösung durch Einsetzen kontrollieren.'],['2x bedeutet 2 · x.','Die Addition oder Subtraktion derselben Zahl auf beiden Seiten erhält die Gleichheit; ebenso Multiplikation oder Division mit derselben Zahl ungleich 0.','2x = 10 ergibt x = 5. Die Probe lautet 2 · 5 = 10.']],
math2_6_prop_prozent:[['math1_9_dezimalzahlen','math1_8_brueche'],['Bei konstantem Stückpreis Menge und Gesamtpreis proportional zuordnen.','Prozentangaben als Anteile von 100 deuten.','Rabattbetrag und verminderten Preis berechnen.'],['Bei direkter Proportionalität bleibt der Quotient aus zugeordneten Größen gleich. Doppelter Menge entspricht der doppelte Preis, wenn der Stückpreis gleich bleibt.','100 % ist das Ganze, 50 % die Hälfte, 1 % ein Hundertstel.','20 % von 50 € sind 0,20 · 50 € = 10 €. Nach diesem Rabatt bleiben 40 €.']],
math2_7_geometrie:[['math1_11_figuren_koerper','math1_6_winkel'],['Dreiecke und wichtige Vierecke anhand ihrer Seiten und Winkel beschreiben.','Grundfläche, Deckfläche und Seitenflächen eines Prismas unterscheiden.','Das Volumen eines Prismas aus Grundflächeninhalt und senkrechter Höhe berechnen.'],['Ein Quadrat ist zugleich Rechteck und Raute. Besondere Vierecksarten können sich überschneiden.','Ein Prisma hat zwei kongruente, parallele Vielecke als Grund- und Deckfläche; die Seitenflächen sind Parallelogramme.','V = G · h: G ist der Grundflächeninhalt, h der senkrechte Abstand zwischen Grund- und Deckfläche.']],
math2_8_statistik:[['math1_4_mult_div'],['Häufigkeiten mit einer Strichliste erfassen.','Ein Säulendiagramm anhand seiner Achsen und Skala lesen.','Den arithmetischen Mittelwert berechnen.'],['Eine Strichliste zählt, wie oft eine Antwort oder Beobachtung vorkommt.','Zum Diagrammlesen gehören Titel, Achsenbeschriftungen und Skala.','Der arithmetische Mittelwert ist die Summe aller Werte geteilt durch ihre Anzahl.']]
};
for(const[id,[prerequisites,learningGoals,summary]]of Object.entries(guides))Object.assign(d[id],{prerequisites,learningGoals,summary});
const t=d.math2_2_brueche;
const q=(id,question,answers)=>({id,question,answers:answers.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const sections=[
{id:'m22_equivalent',title:'Erweitern und Kürzen',content:'<p>Ein halbes Ganzes ist genauso viel wie zwei Viertel: <strong>1/2 = 2/4</strong>. Beim Erweitern multiplizierst du Zähler und Nenner mit derselben positiven ganzen Zahl. Das teilt die Stücke feiner ein, ohne den Anteil zu verändern.</p><p>Beim Kürzen dividierst du Zähler und Nenner durch denselben gemeinsamen Teiler: 6/8 = (6 : 2)/(8 : 2) = 3/4. Mit dem ggT kürzt du vollständig. Zähler und Nenner dürfen dabei nicht unabhängig voneinander verändert werden. Ein Nenner darf nie 0 sein.</p>{{QUIZ_m22_expand}}{{QUIZ_m22_reduce}}',quizzes:[
q('m22_expand','Erweitere 2/3 auf den Nenner 12.',[['8/12',true,'3 · 4 = 12. Deshalb auch den Zähler mit 4 multiplizieren: 2 · 4 = 8.'],['2/12',false,'Nur den Nenner zu ändern verkleinert den Wert. Auch der Zähler muss mit 4 multipliziert werden.'],['11/12',false,'Erweitern bedeutet multiplizieren, nicht zu beiden Zahlen 9 addieren.']]),
q('m22_reduce','Kürze 12/18 vollständig.',[['2/3',true,'Der ggT von 12 und 18 ist 6: 12 : 6 = 2 und 18 : 6 = 3.'],['6/9',false,'Dieser Bruch hat denselben Wert, ist aber noch durch 3 kürzbar.'],['2/18',false,'Beim Kürzen müssen Zähler und Nenner durch dieselbe Zahl geteilt werden.']])]},
{id:'m22_common',title:'Unterschiedliche Nenner',content:'<p>Bei <strong>1/2 + 1/3</strong> sind die Stücke verschieden groß. Wähle einen gemeinsamen Nenner, zum Beispiel das kgV von 2 und 3: 6. Dann gilt 1/2 = 3/6 und 1/3 = 2/6. Jetzt kannst du addieren: 3/6 + 2/6 = <strong>5/6</strong>.</p><p>Beim Subtrahieren geht es ebenso: 3/4 − 1/6 = 9/12 − 2/12 = <strong>7/12</strong>. Ein gemeinsamer Nenner muss nicht der kleinste sein; ein größerer kann ebenfalls funktionieren. Kürze am Ende, wenn möglich.</p><div class="interactive-zone"><h3>Selbst rechnen: 1/2 + 1/4</h3><p>Schreibe zuerst beide Brüche mit dem Nenner 4. Addiere dann die Zähler.</p><label>Zähler des Ergebnisses <input type="number" id="bruch_common_n" step="1"></label><label>Nenner des Ergebnisses <input type="number" id="bruch_common_d" step="1" min="1"></label><button type="button">Prüfen</button></div>{{QUIZ_m22_sum}}{{QUIZ_m22_difference}}',quizzes:[
q('m22_sum','Was ergibt 1/2 + 1/3?',[['5/6',true,'1/2 = 3/6 und 1/3 = 2/6. Zusammen sind es fünf Sechstel.'],['2/5',false,'Nenner dürfen beim Addieren nicht addiert werden. Stelle zuerst gleich große Stücke her.'],['1/6',false,'1/6 ist das Produkt. Gesucht ist die Summe, die größer als jeder Summand sein muss.']]),
q('m22_difference','Was ergibt 3/4 − 1/6?',[['7/12',true,'9/12 − 2/12 = 7/12.'],['2/2',false,'Zähler und Nenner einzeln zu subtrahieren ist keine gültige Bruchregel.'],['2/12',false,'Nach dem Erweitern lauten die Zähler 9 und 2. Ihre Differenz ist 7.']])]}];
t.sections=t.sections.filter(s=>!sections.some(n=>n.id===s.id));t.sections.splice(0,0,sections[0]);t.sections.splice(2,0,sections[1]);
const div=t.sections.find(s=>s.id==='m22_s3');if(!div.content.includes('Divisor darf nicht'))div.content='<p>Der Divisor darf nicht 0 sein. Beim Kehrwert werden Zähler und Nenner vertauscht.</p>'+div.content;
function replace(id,a,b){for(const s of d[id].sections)s.content=s.content.replaceAll(a,b);}
replace('math2_1_teilbarkeit','Es ist die größte Zahl, durch die man zwei Zahlen teilen kann.','Für zwei positive natürliche Zahlen ist der ggT der größte gemeinsame positive Teiler: Beide Divisionen gehen ohne Rest auf.');
replace('math2_1_teilbarkeit','Wann spielt ihr zusammen? Am 12. Tag!','Wenn ihr heute gemeinsam startet: Nach wie vielen Tagen spielt ihr erstmals wieder zusammen? Nach 12 Tagen!');
replace('math2_3_dezimalzahlen','Bei 0, 1, 2, 3, 4 am Ende wird abgerundet (Zahl bleibt gleich).','Wähle zuerst die Rundungsstelle. Die Ziffer direkt rechts davon entscheidet: Bei 0, 1, 2, 3 oder 4 bleibt die Ziffer an der Rundungsstelle gleich.');
replace('math2_3_dezimalzahlen','Bei 5, 6, 7, 8, 9 wird aufgerundet (Zahl wird 1 größer).','Bei 5, 6, 7, 8 oder 9 erhöhst du die Ziffer an der Rundungsstelle um 1; falls nötig gibt es einen Übertrag. Die folgenden Nachkommastellen entfallen. Beispiel: 2,348 auf Zehntel gerundet ist 2,3, weil die Hundertstelziffer 4 entscheidet.');
replace('math2_6_prop_prozent','Ganz einfache Regel: Je mehr du kaufst, desto mehr musst du zahlen.','Bei gleichem Stückpreis und ohne zusätzliche Grundgebühr ist der Gesamtpreis direkt proportional zur Anzahl: Doppelte Menge kostet doppelt so viel. Mengenrabatte können diese Zuordnung verändern.');
replace('math2_7_geometrie','G ist die Grundfläche. h sagt, wie weit diese Fläche nach hinten weitergeht.','G ist der Flächeninhalt der Grundfläche. h ist der senkrechte Abstand zwischen Grund- und Deckfläche. Bei G = 12 cm² und h = 5 cm gilt V = 60 cm³.');
replace('math2_8_statistik','So musst du keine Zahlen lesen, sondern siehst es einfach!','Lies immer auch Achsenbeschriftung und Skala. Nur so kannst du die dargestellten Häufigkeiten richtig ablesen.');
if(!d.math2_5_var_gleichungen.sections[1].content.includes('Probe:'))d.math2_5_var_gleichungen.sections[1].content+='<p><strong>Probe:</strong> Für x = 5 wird 2x = 10 zu 2 · 5 = 10. Beide Seiten stimmen überein. Durch 0 darfst du keine Gleichung dividieren.</p>';
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');console.log('Added eight year-two guides and equivalent/unlike fraction lessons.');
