const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
const guides={
bio_1_haustiere:[['bio_1_wirbeltiere'],['Tierhaltung muss sich an den Bedürfnissen der jeweiligen Tierart orientieren.','Verhalten lässt sich beobachten, ohne ein Tier zu bedrängen oder menschliche Gefühle einfach zu unterstellen.','Platz, Sozialkontakte, Beschäftigung und Versorgung gehören gemeinsam zur Beurteilung einer Haltung.']],
bio_1_skelett_bewegung:[['bio_1_wirbeltiere'],['Das Skelett stützt den Körper und schützt Organe.','Gelenke verbinden Knochen beweglich; Muskeln ziehen über Sehnen an Knochen.','Bewegung entsteht durch das Zusammenspiel von Knochen, Gelenken, Muskeln und Steuerung durch das Nervensystem.']],
bio_1_ernaehrung_verdauung:[['bio_1_kompass'],['Nahrung liefert Energie und Stoffe für Aufbau und Körperfunktionen.','Bei der Verdauung wird Nahrung mechanisch und chemisch zerlegt; aufnehmbare Bestandteile gelangen durch die Darmwand in den Körper.','Bedarf, Zusammensetzung und Vielfalt sind aussagekräftiger als die pauschale Einteilung einzelner Lebensmittel in gut oder schlecht.']],
bio_1_pubertaet_fortpflanzung:[['bio_1_kompass'],['Die Pubertät umfasst körperliche, seelische und soziale Veränderungen; ihr Verlauf ist individuell.','Befruchtung bezeichnet die Vereinigung von Ei- und Samenzelle.','Sachliche Begriffe, Privatsphäre, persönliche Grenzen und verlässliche Hilfe gehören zur Auseinandersetzung mit Körper und Entwicklung.']],
bio_2_uebersicht:[['bio_1_kompass'],['Die Kapitel verbinden Lebensräume, Pflanzen, Zellen, Pilze, Mikroorganismen und Tiere.','Bau und Funktion werden auf verschiedenen Ebenen untersucht, von der Zelle bis zum Ökosystem.','Beobachtung, Vergleich und Modellbildung helfen, biologische Zusammenhänge zu erklären.']],
bio_2_pilze:[['bio_2_zellen'],['Pilze bilden eine eigene Gruppe von Lebewesen und betreiben keine Fotosynthese.','Viele Pilze bauen organische Stoffe ab; andere leben in Beziehungen mit weiteren Organismen.','Sporen dienen der Verbreitung und Fortpflanzung. Unbekannte Pilze eignen sich nicht für Kostproben.']],
bio_2_mikroorganismen:[['bio_2_zellen'],['Mikroorganismen kommen in vielen Lebensräumen vor und erfüllen unterschiedliche Aufgaben.','Viele sind nützlich oder harmlos; einige können Krankheiten verursachen.','Fermentation nutzt bestimmte Mikroorganismen, während Hygiene und Konservierung unerwünschte Vermehrung begrenzen sollen.']],
bio_2_wirbellose:[['bio_1_wirbeltiere','bio_2_oekosysteme'],['Wirbellose Tiere besitzen keine Wirbelsäule und umfassen viele verschiedene Gruppen.','Insekten haben im erwachsenen Grundbauplan sechs Beine und drei Körperabschnitte.','Wirbellose erfüllen Rollen als Bestäuber, Zersetzer, Pflanzenfresser, Räuber und Nahrung anderer Tiere.']],
bio_2_sinne_gehirn:[['bio_2_zellen'],['Sinneszellen nehmen Reize auf; Nerven leiten Signale zur Verarbeitung weiter.','Wahrnehmung entsteht durch das Zusammenspiel von Sinnesorganen und Gehirn.','Sinnestäuschungen zeigen, dass Wahrnehmung eine Verarbeitung und keine unveränderte Kopie der Umwelt ist.']],
bio_2_gehirn_bewegung:[['bio_2_sinne_gehirn','bio_1_skelett_bewegung'],['Nerven, Rückenmark und Gehirn vermitteln Informationen und steuern Reaktionen.','Willkürliche Bewegungen und Reflexe unterscheiden sich in Ablauf und Steuerung.','Übung und Erfahrung können Bewegungsabläufe verbessern; Beobachtungen ersetzen keine medizinische Diagnose.']],
bio_3_kompetenzplan:[['bio_2_uebersicht'],['Die Kapitel verbinden Wasserlebensräume, Organsysteme, Boden und Erdgeschichte.','Eine biologische Erklärung verknüpft Merkmale, Funktionen und Bedingungen.','Beobachtungen und Daten müssen von Deutung und Bewertung unterschieden werden.']],
bio_3_wasser_oekosysteme:[['bio_2_oekosysteme'],['Wasserlebensräume werden unter anderem durch Salzgehalt, Licht, Temperatur und Sauerstoff geprägt.','Nahrungsnetze und Stoffkreisläufe verbinden Organismen und Umwelt.','Nährstoffeinträge, Erwärmung und Abfälle können Gewässer verändern; Bewertungen benötigen Beobachtungen und Belege.']],
bio_3_wassertiere_entwicklung:[['bio_3_wasser_oekosysteme','bio_1_wirbeltiere'],['Körperform, Atmungsorgane und Verhalten stehen mit den Lebensbedingungen im Wasser in Beziehung.','Fortpflanzung und Entwicklung können von Wasser als Lebensraum abhängen.','Vergleiche verbinden ein beobachtetes Merkmal mit seiner Funktion, ohne allen Wassertieren denselben Bauplan zuzuschreiben.']],
bio_3_atmung_energie:[['bio_2_zellen'],['Beim Gasaustausch werden Atemgase mit der Umgebung ausgetauscht; Zellatmung ist ein anderer Vorgang.','Bei aerober Zellatmung wird mithilfe von Sauerstoff Energie aus energiereichen Stoffen für die Zelle verfügbar.','Tracheen, Kiemen und Lungen ermöglichen Gasaustausch auf unterschiedliche Weise.']],
bio_3_blut_kreislauf:[['bio_3_atmung_energie'],['Das Herz treibt den Blutkreislauf an; Blut transportiert unter anderem Atemgase und Nährstoffe.','Arterien führen vom Herzen weg, Venen zum Herzen hin; Kapillaren ermöglichen den Stoffaustausch mit Geweben.','Blutzellen und Blutplasma erfüllen unterschiedliche Aufgaben; Pulsdaten müssen im jeweiligen Beobachtungskontext betrachtet werden.']],
bio_3_ausscheidung_gesundheit:[['bio_3_blut_kreislauf'],['Ausscheidung entfernt Stoffwechselprodukte und überschüssige Stoffe.','Nieren, Lunge und Haut übernehmen unterschiedliche Aufgaben bei Ausscheidung und Regulation.','Organsysteme arbeiten zusammen; einzelne Alltagsbeobachtungen reichen nicht für eine Selbstdiagnose.']],
bio_4_kompetenzplan:[['bio_3_kompetenzplan'],['Die Kapitel verbinden Umweltfragen, Vererbung, Körpersteuerung, Gesundheit und Menschheitsentwicklung.','Eine begründete Bewertung berücksichtigt Belege, Unsicherheiten und unterschiedliche Perspektiven.','Sachliche Fachsprache und respektvoller Umgang sind auch bei persönlichen oder kontroversen Themen notwendig.']],
bio_4_genetik_gentechnik:[['bio_2_zellen','bio_1_selektion'],['DNA trägt Erbinformation; Gene sind Abschnitte der DNA, Chromosomen enthalten organisierte DNA.','Merkmale können durch Erbanlagen und Umwelt beeinflusst werden; einfache Vererbungsmodelle erklären nicht jedes Merkmal.','Gentechnische Anwendungen werden anhand ihres konkreten Zwecks, Nutzens, möglicher Risiken und Belege beurteilt.']],
bio_4_immunsystem_resistenzen:[['bio_2_mikroorganismen'],['Barrieren sowie angeborene und erworbene Abwehr wirken gegen Krankheitserreger zusammen.','Impfungen bereiten die Abwehr auf bestimmte Erreger vor und können vor Erkrankung oder schweren Verläufen schützen.','Antibiotika wirken gegen Bakterien, nicht gegen Viren. Resistent werden Bakterien; unpassende Anwendung kann ihre Ausbreitung begünstigen.']],
bio_4_nerven_hormone:[['bio_2_sinne_gehirn','bio_2_gehirn_bewegung'],['Das Nervensystem nimmt Informationen auf, verarbeitet sie und steuert Reaktionen.','Hormone sind Botenstoffe, die über das Blut zu passenden Zielzellen gelangen.','Nerven- und Hormonsystem wirken zusammen; Körperreaktionen lassen sich nicht allein aus einem einzelnen Signal erklären.']],
bio_4_sexualitaet_verantwortung:[['bio_1_pubertaet_fortpflanzung'],['Pubertät und Entwicklung verlaufen individuell; Körper und persönliche Identität verdienen Respekt.','Fortpflanzung, Schwangerschaftsverhütung und Schutz vor sexuell übertragbaren Infektionen sind unterschiedliche Themen.','Einverständnis muss freiwillig sein und kann widerrufen werden; niemand muss persönliche Erfahrungen im Unterricht offenlegen.']]};
const overviewGoals={
bio_2_uebersicht:['Themen der 2. Klasse benennen und miteinander verbinden.','Zellen, Organe und Lebensräume als unterschiedliche Betrachtungsebenen unterscheiden.','Biologische Fragen durch Beobachtung und Vergleich bearbeiten.'],
bio_3_kompetenzplan:['Themen der 3. Klasse ordnen und mit Vorwissen verbinden.','Eine Erklärung aus Beobachtung, Fachbegriffen und Begründung aufbauen.','Bilder und Daten zur Untersuchung einer Frage verwenden.'],
bio_4_kompetenzplan:['Die Themenfelder der 4. Klasse einordnen.','Biologische Fragen mit Belegen und Fachsprache bearbeiten.','Sachliche Erklärungen und persönliche Bewertungen unterscheiden.']};
for(const[id,[prerequisites,summary]]of Object.entries(guides)){
const t=d[id],$=cheerio.load(t.sections[0].content),goals=$('.bio-overview-box').filter((_,el)=>$(el).text().includes('Das soll ich lernen')).first().find('li').map((_,el)=>$(el).text().trim()).get();
const learningGoals=goals.length?goals:overviewGoals[id];if(!learningGoals?.length)throw Error('Missing goals '+id);Object.assign(t,{prerequisites,summary,learningGoals});
}
const sources={bio_1_ernaehrung_verdauung:[['Gesundheitsportal: Magen und Darm','https://www.gesundheit.gv.at/krankheiten/verdauung/info/magen-darm.html']],bio_1_pubertaet_fortpflanzung:[['Gesundheitsportal: Pubertät','https://www.gesundheit.gv.at/leben/kids-teens/pubertaet.html']],bio_4_immunsystem_resistenzen:[['Gesundheitsportal: Antibiotikaresistenz','https://www.gesundheit.gv.at/gesundheitsleistungen/medikamente/antibiotikaresistenz.html'],['Gesundheitsportal: Wie Impfungen schützen','https://www.gesundheit.gv.at/leben/gesundheitsvorsorge/impfungen/impfschutz.html']]};
for(const[id,rows]of Object.entries(sources)){const list=d[id].sources||[];for(const[label,url]of rows)if(!list.some(s=>s.url===url))list.push({label,url});d[id].sources=list;}
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');console.log('Added 21 remaining biology chapter guides.');
