const fs=require('fs'),path=require('path'),vm=require('vm'),cheerio=require('cheerio'),root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8')),ctx={window:{}};
const navFile=path.join(root,'js/curriculum.js');vm.runInNewContext(fs.readFileSync(navFile,'utf8'),ctx);const chapters=ctx.window.SCIVERSE_CURRICULUM.chemie.topics;
for(const t of chapters)t.grade='8. Schulstufe (4. Kl.)';
fs.writeFileSync(navFile,'// Gemeinsame Kapitelordnung für Navigation und Lernbereich.\nwindow.SCIVERSE_CURRICULUM = '+JSON.stringify(ctx.window.SCIVERSE_CURRICULUM,null,2)+';\n');
const roadmap=d.chemie_roadmap;roadmap.title='🧪 Chemie: Lernweg für die 4. Klasse';roadmap.subtitle='Zuerst Stoffe sicher untersuchen, dann Reaktionen und Anwendungen mit Modellen erklären.';
roadmap.sections[0].title='1. Ein Lernweg mit aufeinander aufbauenden Blöcken';
roadmap.sections[1].title='2. Grundlagen: Stoffe und Teilchen';roadmap.sections[2].title='3. Reaktionen und Anwendungen';
for(const s of roadmap.sections){s.content=s.content.replaceAll('3. und 4. Klasse','4. Klasse').replaceAll('3. Klasse:','Grundlagenblock:').replaceAll('4. Klasse:','Reaktionen und Anwendungen:').replaceAll('In beiden Jahren','In diesem Lernweg').replaceAll('Jahresziel:','Ziel dieses Blocks:').replaceAll('3. Klasse starten','Grundlagen starten').replaceAll('4. Klasse starten','Reaktionen vertiefen').replaceAll('Starte in der 3. Klasse','Starte im Grundlagenblock').replace(/<strong>[34]\.\d+ /g,'<strong>');}
roadmap.sections[0].content='<p>Der österreichische Mittelschullehrplan ordnet Chemie der 4. Klasse zu. Die folgenden Blöcke strukturieren diesen Lernweg; sie sind keine verpflichtende Verteilung auf zwei Schuljahre. Lehrkräfte können Reihenfolge und Vertiefungen an ihre Klasse und schulautonome Planung anpassen.</p>'+roadmap.sections[0].content;
roadmap.quizzes[0].question='Warum beginnt dieser Chemie-Lernweg mit Stoffen und Sicherheit?';roadmap.diplom.title='Chemie-Check: Lernweg';roadmap.diplom.questions[0].question='Welche Themen gehören zum Grundlagenblock?';roadmap.diplom.questions[0].answers[1].feedback='Redox und Kohlenstoffchemie bauen auf Grundlagen wie Stoffeigenschaften und Teilchenmodellen auf.';
// Distinguish the three representational levels from everyday application.
roadmap.sections[3].content=roadmap.sections[3].content.replace('<strong>Alltagsebene:</strong> Wo hilft mir das Wissen im echten Leben?','<strong>Symbolebene:</strong> Wie beschreibe ich den Vorgang mit Symbolen oder einfachen Reaktionsgleichungen?');
const summaries={
chemie_roadmap:['Der Lernweg gehört zur 4. Klasse und beginnt mit sicherem Untersuchen und Stoffeigenschaften.','Stoffebene, Teilchenebene und Symbolebene sind unterschiedliche Darstellungen chemischer Vorgänge.','Erklärungen verbinden Beobachtung und Modell; Anwendungen stellen den Bezug zum Alltag her.'],
chemie_sicherheit:['Lies Etikett und Arbeitsanweisung vor jedem Versuch und arbeite nach Anleitung der Lehrkraft.','Gefahrensymbole weisen auf Gefahren hin; auch kleine Mengen können gefährlich sein.','Melde Unfälle oder unklare Situationen sofort und kenne die Sicherheitseinrichtungen des Chemiesaals.'],
chemie_alltag_stoffe:['Ein Gegenstand hat eine Form und einen Zweck; seine Materialien besitzen bestimmte Eigenschaften.','Materialwahl verbindet Eigenschaften mit dem vorgesehenen Nutzen.','Auch Alltagsstoffe müssen sachgerecht verwendet und entsorgt werden.'],
chemie_stoffe_eigenschaften:['Stoffe lassen sich durch mehrere Eigenschaften eingrenzen; gleiches Aussehen reicht nicht.','Löslichkeit, Magnetismus, Dichte und Leitfähigkeit sind Beispiele für untersuchbare Eigenschaften.','Prüfungen müssen zur Frage passen und unter sicheren Bedingungen durchgeführt werden.'],
chemie_trennverfahren:['Trennverfahren nutzen unterschiedliche Eigenschaften der Bestandteile eines Gemisches.','Filtern trennt ungelöste Feststoffe von Flüssigkeiten; gelöste Stoffe werden nicht einfach herausgefiltert.','Magnettrennung nutzt Magnetismus, Eindampfen die unterschiedliche Flüchtigkeit der Bestandteile.'],
chemie_teilchenmodell:['Das Teilchenmodell erklärt Stoffeigenschaften mit Anordnung, Bewegung und Wechselwirkungen kleiner Teilchen.','Fest, flüssig und gasförmig unterscheiden sich im Modell durch Beweglichkeit und Anordnung.','Modelle sind vereinfachte Vorstellungen; Beobachtung und Modellbeschreibung bleiben unterscheidbar.'],
chemie_salze_wasser:['Beim Lösen bleibt der gelöste Stoff vorhanden, auch wenn keine Körnchen mehr sichtbar sind.','Eine gesättigte Lösung kann unter den gegebenen Bedingungen keinen weiteren Stoff lösen.','Beim Verdunsten von Wasser kann ein gelöster Stoff als Kristall zurückbleiben.'],
chemie_reaktionen_energie:['Bei einer chemischen Reaktion entstehen neue Stoffe mit neuen Eigenschaften.','Farbänderung, Gasbildung oder Temperaturänderung sind Hinweise, aber für sich allein kein sicherer Nachweis einer Reaktion.','Reaktionen können Energie an die Umgebung abgeben oder Energie aufnehmen.'],
chemie_sauerstoff_verbrennung:['Das Branddreieck beschreibt Brennstoff, Sauerstoff und ausreichende Temperatur.','Beim Löschen wird mindestens eine dieser Bedingungen entzogen; das Mittel muss zum Brand passen.','Versuche mit Flammen gehören unter die Anleitung der Lehrkraft und die festgelegten Sicherheitsregeln.'],
chemie_saeuren_basen:['Indikatoren zeigen durch Farbänderung unterschiedliche saure oder basische Bedingungen an.','Der pH-Wert hilft bei der Einordnung wässriger Lösungen.','Säuren und Basen können miteinander reagieren; Haushaltsreiniger dürfen nicht versuchsweise gemischt werden.'],
chemie_metalle_redox:['Rosten ist eine chemische Veränderung von Eisen unter Beteiligung von Wasser und Sauerstoff.','Salz kann die Korrosion beschleunigen; Schutzschichten können den Kontakt zur Umgebung vermindern.','Metallgewinnung, Korrosionsschutz und Recycling stehen mit chemischen Reaktionen in Zusammenhang.'],
chemie_atom_periodensystem:['Protonen und Neutronen gehören zum Atomkern, Elektronen zur Hülle.','Die Protonenzahl bestimmt das Element und entspricht seiner Ordnungszahl.','Ein neutrales Atom besitzt gleich viele Protonen und Elektronen; geänderte Elektronenzahl kann zu einem Ion führen.'],
chemie_bindungen:['Ionische Stoffe, Moleküle und Metalle werden mit unterschiedlichen Bindungsmodellen beschrieben.','Struktur und Bindung beeinflussen Eigenschaften wie Leitfähigkeit und Sprödigkeit.','Bei Salzen können bewegliche Ionen in Lösung oder Schmelze Strom transportieren; in Metallen übernehmen dies bewegliche Elektronen.'],
chemie_kohlenstoff_kunststoffe:['Kohlenstoff kann Ketten, Verzweigungen und Netzwerke bilden.','Polymere bestehen aus großen Molekülen mit vielen verknüpften Bausteinen.','Nutzen und Umweltfolgen eines Kunststoffprodukts hängen auch von Verwendung, Lebensdauer und Entsorgung ab.'],
chemie_umwelt_chemie:['Bewerte Produkte anhand von Nutzen, Risiken, benötigten Ressourcen und Entsorgung.','Natürlich bedeutet nicht automatisch harmlos; künstlich bedeutet nicht automatisch gefährlich.','Vermeidung, Wiederverwendung, Reparatur und Recycling sind unterschiedliche Möglichkeiten, Ressourcen zu schonen.']};
const prerequisite={chemie_roadmap:[],chemie_sicherheit:['chemie_roadmap'],chemie_alltag_stoffe:['chemie_sicherheit'],chemie_stoffe_eigenschaften:['chemie_alltag_stoffe'],chemie_trennverfahren:['chemie_stoffe_eigenschaften'],chemie_teilchenmodell:['chemie_stoffe_eigenschaften'],chemie_salze_wasser:['chemie_teilchenmodell','chemie_trennverfahren'],chemie_reaktionen_energie:['chemie_teilchenmodell'],chemie_sauerstoff_verbrennung:['chemie_sicherheit','chemie_reaktionen_energie'],chemie_saeuren_basen:['chemie_sicherheit','chemie_salze_wasser','chemie_reaktionen_energie'],chemie_metalle_redox:['chemie_reaktionen_energie'],chemie_atom_periodensystem:['chemie_teilchenmodell'],chemie_bindungen:['chemie_atom_periodensystem'],chemie_kohlenstoff_kunststoffe:['chemie_bindungen'],chemie_umwelt_chemie:['chemie_reaktionen_energie']};
for(const {id} of chapters){const t=d[id],$=cheerio.load(t.sections[0].content),goals=$('.lesson-goals li').map((_,li)=>$(li).text().replace(/^Du /,'')).get();if(goals.length)t.learningGoals=goals.map(s=>'Du '+s);if(!t.learningGoals?.length)throw Error('Missing authored goals '+id);t.summary=summaries[id];t.prerequisites=prerequisite[id];t.title=t.title.replace(/[34]\.\d+ /,'');}
roadmap.sources=[{label:'RIS: Lehrplan der Mittelschule, Chemie (4. Klasse)',url:'https://www.ris.bka.gv.at/NormDokument.wxe?Abfrage=Bundesnormen&Anlage=1&Gesetzesnummer=20007850'}];
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
const common=path.join(root,'js/topics/chemie_common.js');let s=fs.readFileSync(common,'utf8');s=s.replace("grade3: '3. Klasse: Starte", "grade3: 'Grundlagenblock: Starte").replace("grade4: '4. Klasse: Starte", "grade4: 'Reaktionen und Anwendungen: Starte");fs.writeFileSync(common,s);
