'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/responsibility')),topic='bio_4_sexualitaet_verantwortung';
const keys={bio_4_sex_s1:1,bio_4_sexualitaet_d1:2,bio_4_sex_hormone:0,bio_4_sex_s2:2,bio_4_sexualitaet_d2:0,bio_4_sex_kalender:1,bio_4_sex_s3:0,bio_4_sex_methoden:2,bio_4_sex_quellen:1,bio_4_sexualitaet_d3:2,bio_4_sex_hilfe:0},correct=[1,2,0,2,1,0];
const reasons=[[/keine Messung/,/belegt keinen sicheren Tag/,/garantiert keinen/],[/keinen gemeinsamen Schutz/,/keinen Infektionsschutz/,/getrennt zu beurteilen/],[/90 Prozent.*80 Prozent/,/Nenner/,/keine fachliche Richtigkeit/],[/verpflichtet nicht/,/Rechtfertigung/,/aktuelle Grenze/],[/Alex’ Zustimmung nicht/,/Alex entscheidet/,/ebenso verletzen/],[/zeitabhängig/,/Warten/,/Fremde Medikamente/]];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-responsibility-lab]')?.dataset.initialized==='true');
 const select=p.locator('[data-responsibility-select]'),check=p.locator('[data-responsibility-check]'),reset=p.locator('[data-responsibility-reset]'),result=p.locator('[data-responsibility-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 const choose=async(i,j)=>{await select.selectOption(String(i));assert.equal(await result.textContent(),'');await p.locator(`[data-responsibility-case="${i}"] input[value="${j}"]`).check();await check.click();};
 let decisions=0;for(let i=0;i<6;i++){await select.selectOption(String(i));await check.click();assert.equal(await result.getAttribute('data-invalid'),'answer');assert.equal(await p.locator(`[data-responsibility-case="${i}"] input`).first().evaluate(e=>e===document.activeElement),true);for(let j=0;j<3;j++){await choose(i,j);assert.equal(await result.getAttribute('data-supported'),String(j===correct[i]));assert.match(await result.textContent(),reasons[i][j]);assert.equal(await result.evaluate(e=>e===document.activeElement),true);decisions++;}}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(let i=0;i<6;i++){await choose(i,correct[i]);assert.equal(await p.locator('[data-responsibility-case]:visible').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);
   for(const el of await p.locator('[data-responsibility-lab] button,[data-responsibility-lab] select,[data-responsibility-case]:visible .responsibility-option').all()){const box=await el.boundingBox();assert.ok(box.height>=44);assert.ok(box.x>=0&&box.x+box.width<=width+1);}
   for(const text of await p.locator('.responsibility-map text').all())assert.ok(await text.evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('svg').getBoundingClientRect();return r.height>=12&&r.left>=s.left-1&&r.right<=s.right+1&&r.top>=s.top-1&&r.bottom<=s.bottom+1;}),'SVG text readable and contained');
   for(const cell of await p.locator('.responsibility-table :is(th,td)').all()){if(await cell.evaluate(e=>e.closest('thead')&&getComputedStyle(e.closest('thead')).position==='absolute'))continue;assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);}
   layouts.push({dark,width,case:i});if(width===390&&[0,2,5].includes(i))await p.locator('[data-responsibility-lab]').screenshot({path:path.join(out,'case-'+i+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});
  }
  for(const card of await p.locator('.responsibility-card').all())assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');
  if(width===390)for(const[name,selector]of [['map','.responsibility-map'],['hormones','.responsibility-hormones'],['methods','.responsibility-methods'],['survey','.responsibility-survey'],['aspects','.responsibility-aspects']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await select.evaluate(e=>e===document.activeElement),true);assert.equal(await select.inputValue(),'0');await p.keyboard.press('Tab');assert.equal(await p.locator('[data-responsibility-case="0"] input[value="0"]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[data-responsibility-case="0"] input[value="1"]').isChecked(),true);await p.keyboard.press('Tab');assert.equal(await check.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.equal(await result.getAttribute('data-supported'),'true');assert.equal(await result.evaluate(e=>e===document.activeElement),true);
 await p.locator('[data-responsibility-case="0"] input[value="2"]').check();assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const practice=p.locator('.practice-box[data-id="bio_4_sexualitaet_extra_einverstaendnis"]');for(const option of await practice.locator('button').all()){await option.click();assert.ok((await practice.locator('.feedback').textContent()).includes(await option.getAttribute('data-feedback')));assert.equal(await option.isEnabled(),true);}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,11);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[id];assert.equal(r.lastPercent,right?100:91);assert.deepEqual(r.reviewQuestionIds,right?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.responsibility-paper-case').count(),6);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-responsibility-solution]').count(),4);assert.equal(await paper.locator('#ws-solutions .responsibility-case-solution').count(),6);await paper.pdf({path:path.join(out,'responsibility-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,practiceAnswers:3,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 18 native decisions, 36 layouts, keyboard/reset/focus/storage, 33 graded and 3 practice answers, complete paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
