'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const id='math3_2_potenzen_terme',base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/scientific-notation'));
const keys=vm.runInNewContext('('+fs.readFileSync(path.join(__dirname,'test_powers_year3.js'),'utf8').match(/const answers=(\{[^;]+\});/)[1]+')'),source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+id);await p.waitForFunction(()=>document.querySelector('[data-sci-lab]')?.dataset.bound==='true');const lab=p.locator('[data-sci-lab]'),saved=await p.evaluate(()=>JSON.stringify(localStorage));let cases=0,paths=0;
 for(const direction of ['decimal','scientific'])for(let i=0;i<52;i++){
  await p.locator('#sci-direction').selectOption(direction);await p.locator('#sci-case').selectOption(String(i));const a=[-4.2,1,2.5,9.6][Math.floor(i/13)],n=i%13-6,expected=Number((a*10**n).toFixed(8)).toLocaleString('de-AT',{useGrouping:false,maximumFractionDigits:10});
  if(direction==='decimal'){await p.locator('#sci-decimal').fill(expected);await p.locator('#sci-decimal').press('Enter');}else{await p.locator('#sci-a').fill(String(a).replace('.',','));await p.locator('#sci-n').fill(String(n));await p.locator('#sci-n').press('Enter');}
  assert.match(await p.locator('#sci-status').innerText(),/^Richtig:/);await lab.locator('[data-sci-show]').click();assert.equal(await lab.locator('[data-sci-steps] tbody tr').count(),Math.abs(n)+1);cases++;
 }
 await lab.locator('[data-sci-reset]').focus();await p.keyboard.press('Space');assert.equal(await p.locator('#sci-direction').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('#sci-case').inputValue(),'35');await p.locator('#sci-decimal').fill('25e2');await p.locator('#sci-decimal').press('Enter');assert.match(await p.locator('#sci-status').innerText(),/^Gib eine/);await p.locator('#sci-decimal').fill('250');await p.locator('#sci-decimal').press('Enter');assert.match(await p.locator('#sci-status').innerText(),/^Noch nicht/);await p.locator('#sci-decimal').fill('2500');assert.equal(await p.locator('#sci-status').innerText(),'');
 for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await p.setViewportSize({width,height:1000});await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await p.waitForFunction(t=>getComputedStyle(document.body).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);await p.waitForTimeout(350);
  for(const direction of ['decimal','scientific'])for(let i=0;i<52;i++){
   await p.locator('#sci-direction').selectOption(direction);await p.locator('#sci-case').selectOption(String(i));await lab.locator('[data-sci-show]').click();const geometry=await lab.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,stepNumbersFit:[...e.querySelectorAll('[data-sci-steps] td:nth-child(2)')].every(c=>c.scrollWidth<=c.clientWidth+1&&getComputedStyle(c).whiteSpace==='nowrap'),controls:[...e.querySelectorAll('input,button,select')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,height:r.height};})};});assert.ok(!geometry.overflow&&geometry.left>=0&&geometry.right<=width+1,JSON.stringify({width,theme,direction,i,geometry}));assert.ok(geometry.stepNumbersFit);assert.ok(geometry.controls.every(c=>c.left>=geometry.left&&c.right<=geometry.right+1&&c.height>=44));layouts.push({width,theme,direction,index:i});
  }
  await p.locator('#sci-case').selectOption('0');await lab.locator('[data-sci-show]').click();await lab.screenshot({path:path.join(out,'lab-'+width+'-'+theme+'.png')});
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const q of source.sections.flatMap(s=>s.quizzes))for(const[i,a]of q.answers.entries()){const box=p.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:a.text,exact:true});await button.focus();await p.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===keys[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==keys[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));paths++;}
 await p.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id)),wrong='m32_sci_small';for(const[i,q]of ids.entries())await p.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?1:keys[q])+'"]').check();await p.locator('.chapter-submit-btn').click();const result=await p.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,96);assert.equal(result.contentRevision,4);assert.deepEqual(result.reviewQuestionIds,[wrong]);await p.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await p.locator('#learning-section-3').evaluate(e=>e.contains(document.activeElement)));
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-sci-paper]').count(),1);assert.equal(await paper.locator('[data-sci-generated]').count(),4);assert.equal(await paper.locator('#ws-content>.question-block').count(),26);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('.ws-paper-solution').count(),8);const generated=await paper.locator('[data-sci-generated]').evaluateAll(es=>es.map(e=>({coefficient:Number(e.dataset.coefficient),exponent:Number(e.dataset.exponent),text:e.textContent}))),answers=await paper.locator('[data-sci-answer]').evaluateAll(es=>es.map(e=>({value:Number(e.dataset.sciAnswer),text:e.textContent})));for(let i=0;i<4;i++)assert.equal(answers[i].value,Number((generated[i].coefficient*10**generated[i].exponent).toFixed(8)));
 await paper.pdf({path:path.join(out,'scientific-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),cases,paths,layouts,result,generated,answers,errors,scope:'Native conversions, all chapter answer paths, responsive controls, targeted chapter review and worksheet export. PDF visual review recorded separately; no full product acceptance.'},null,2)+'\n');console.log('PASS: scientific notation native: '+cases+' conversions, '+paths+' answer paths, '+layouts.length+' layouts; keyboard/reset/storage, targeted chapter review and print export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
