'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/sensory-contrast')),topic='bio_2_sinne_gehirn';
const keys={"bio_2_sinne_gehirn_s1":1,"bio_2_sinne_gehirn_s2":2,"bio_2_sinne_gehirn_d1":0,"bio_2_sinne_gehirn_d2":1,"bio_2_sinne_gehirn_s3":2,"bio_2_sinne_gehirn_d3":0,"bio_2_sinne_gehirn_d4":2,"bio_2_sinne_gehirn_s4":1,"bio_2_sinne_gehirn_data":0,"bio_2_sinne_gehirn_s5":2,"bio_2_sinne_gehirn_d5":1,"bio_2_sinne_gehirn_control":1};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-contrast-lab]')?.dataset.initialized==='true');const store=await p.evaluate(()=>JSON.stringify(localStorage)),zone=p.locator('[data-contrast-lab]'),reset=p.locator('[data-contrast-reset]'),expected={original:['#222222','#eeeeee'],swapped:['#eeeeee','#222222'],equal:['#bbbbbb','#bbbbbb']},centers=await p.locator('[data-contrast-center]').evaluateAll(es=>es.map(e=>e.outerHTML));
 const verify=async mode=>{assert.deepEqual(await p.locator('[data-contrast-background]').evaluateAll(es=>es.map(e=>e.getAttribute('fill'))),expected[mode]);assert.deepEqual(await p.locator('[data-contrast-center]').evaluateAll(es=>es.map(e=>e.outerHTML)),centers);assert.equal(await zone.locator('[aria-pressed="true"]').count(),1);assert.equal(await zone.locator('[aria-pressed="true"]').getAttribute('data-contrast-mode'),mode);};
 let transitions=0;for(const from of Object.keys(expected))for(const to of [...Object.keys(expected),'reset']){await p.locator('[data-contrast-mode="'+from+'"]').click();const button=to==='reset'?reset:p.locator('[data-contrast-mode="'+to+'"]');await button.focus();await p.keyboard.press('Enter');await verify(to==='reset'?'original':to);assert.equal(await (to==='reset'?p.locator('[data-contrast-mode="original"]'):button).evaluate(e=>e===document.activeElement),true);transitions++;}
 for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});await p.evaluate(dark=>{if(dark)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);for(const mode of Object.keys(expected)){await p.locator('[data-contrast-mode="'+mode+'"]').click();await verify(mode);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const control of await zone.locator('button,summary').all())assert.ok((await control.boundingBox()).height>=44);layouts.push({dark,width,mode});}if(width===390){await p.locator('[data-contrast-mode="original"]').click();await zone.screenshot({path:path.join(out,'contrast-'+(dark?'dark':'light')+'.png')});await p.locator('.senses-pathway').screenshot({path:path.join(out,'pathway-'+(dark?'dark':'light')+'.png')});await p.locator('.senses-data').screenshot({path:path.join(out,'data-'+(dark?'dark':'light')+'.png')});await p.locator('.senses-protocol').screenshot({path:path.join(out,'protocol-'+(dark?'dark':'light')+'.png')});}}
 await p.locator('[data-contrast-mode="original"]').focus();await p.keyboard.press('Tab');assert.equal(await p.locator('[data-contrast-mode="swapped"]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Space');await verify('swapped');await p.keyboard.press('Tab');await p.keyboard.press('Enter');await verify('equal');await reset.focus();await p.keyboard.press('Space');await verify('original');assert.equal(await p.locator('[data-contrast-mode="original"]').evaluate(e=>e===document.activeElement),true);await zone.locator('summary').click();assert.equal(await zone.locator('details').getAttribute('open'),'');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),store);
 let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:92);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-senses-paper] svg').count(),3);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-senses-solution]').count(),5);await paper.pdf({path:path.join(out,'senses-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),answers,transitions,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 12 contrast transitions, 18 layout states, keyboard/reset/focus/storage, 36 native quiz answers and paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
