'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/human-origins')),topic='bio_4_menschheitsentwicklung';
const keys={bio_4_mensch_s1:1,bio_4_mensch_d1:2,bio_4_mensch_stammbaum:0,bio_4_mensch_s2:2,bio_4_mensch_d3:0,bio_4_mensch_d2:1,bio_4_mensch_zeit:1,bio_4_mensch_begegnung:2,bio_4_mensch_grenzen:0,bio_4_mensch_s3:1,bio_4_mensch_verhalten:2};
const expected={'af-er':['neither','neither','second','second','first','first'],'af-ne':['neither','second','second','neither','first','first'],'af-sa':['second','second','second','neither','first','first'],'er-ne':['neither','second','both','first','neither','neither'],'er-sa':['second','second','both','first','neither','neither'],'ne-sa':['second','both','both','neither','neither','neither']};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-origins-lab]')?.dataset.initialized==='true');
 const pair=p.locator('[data-origins-pair]'),time=p.locator('[data-origins-time]'),prediction=p.locator('[data-origins-prediction]'),check=p.locator('[data-origins-check]'),reset=p.locator('[data-origins-reset]'),result=p.locator('[data-origins-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 let decisions=0;for(const[key,hits]of Object.entries(expected))for(const[i,t]of ['0','50','200','1000','3000','3500'].entries()){
  await pair.selectOption(key);await time.selectOption(t);assert.equal(await prediction.inputValue(),'');assert.equal(await result.textContent(),'');await prediction.selectOption(hits[i]);await check.click();assert.equal(await result.getAttribute('data-actual'),hits[i]);assert.equal(await result.getAttribute('data-correct'),'true');assert.equal(await result.evaluate(e=>e===document.activeElement),true);decisions++;
 }
 await pair.selectOption('ne-sa');await time.selectOption('200');await check.click();assert.equal(await result.getAttribute('data-invalid'),'prediction');assert.equal(await prediction.evaluate(e=>e===document.activeElement),true);
 for(const choice of ['both','first','second','neither']){await prediction.selectOption(choice);await check.click();assert.equal(await result.getAttribute('data-correct'),String(choice==='both'));decisions++;}
 console.log('Native predictions and feedback passed.');
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[key,t,guess]of [['ne-sa','200','both'],['af-er','3500','first'],['er-sa','50','second']]){
   await pair.selectOption(key);await time.selectOption(t);await prediction.selectOption(guess);await check.click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
   for(const cell of await p.locator('.origins-table :is(th,td)').all()){if(await cell.evaluate(e=>e.closest('thead')&&getComputedStyle(e.closest('thead')).position==='absolute'))continue;assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);}
   for(const svg of await p.locator('.origins-tree svg,.origins-chart svg').all())assert.equal(await svg.evaluate(e=>[...e.querySelectorAll('text')].every(t=>{const b=t.getBBox(),v=e.viewBox.baseVal;return b.x>=0&&b.y>=0&&b.x+b.width<=v.width&&b.y+b.height<=v.height;})),true);
   layouts.push({dark,width,pair:key,time:t});if(width===390)await p.locator('[data-origins-lab]').screenshot({path:path.join(out,key+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});
  }
  if(width===390)for(const[name,selector]of [['tree','.origins-tree'],['finds','.origins-finds'],['times','.origins-times'],['learning','.origins-learning']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await pair.evaluate(e=>e===document.activeElement),true);assert.equal(await pair.inputValue(),'ne-sa');await p.keyboard.press('Tab');assert.equal(await time.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Tab');assert.equal(await prediction.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Home');await p.keyboard.press('ArrowDown');assert.equal(await prediction.inputValue(),'both');await p.keyboard.press('Tab');assert.equal(await check.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.equal(await result.getAttribute('data-correct'),'true');assert.equal(await result.evaluate(e=>e===document.activeElement),true);await time.selectOption('0');assert.equal(await result.textContent(),'');assert.equal(await prediction.inputValue(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const practice=p.locator('.practice-box[data-id="bio_4_menschheitsentwicklung_extra_vielfalt"]');for(const option of await practice.locator('button').all()){await option.click();assert.ok((await practice.locator('.feedback').textContent()).includes(await option.getAttribute('data-feedback')));assert.equal(await option.isEnabled(),true);}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 console.log('Mobile/desktop, both themes, keyboard and point-free practice passed.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,11);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[id];assert.equal(r.lastPercent,right?100:91);assert.deepEqual(r.reviewQuestionIds,right?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.origins-paper').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-origins-solution]').count(),4);await paper.pdf({path:path.join(out,'human-origins-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,practiceAnswers:3,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 40 native predictions, 18 layouts, keyboard/reset/focus/storage, 33 graded and 3 practice answers, complete paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
