const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const data=require('../lang/de.json').wetter,keys=require('./fixtures/weather_assessment_keys.json'),base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/weather-assessment'));
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let practice=0,assessed=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic=wetter');await p.waitForFunction(()=>window.currentChapterQuiz?.questions.length===18);await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});const saved=await p.evaluate(()=>JSON.stringify(localStorage));
 for(const section of data.sections)for(const q of section.quizzes||[]){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [a,answer]of q.answers.entries()){const b=box.getByRole('button',{name:answer.text,exact:true});await b.focus();await b.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),a===keys[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));practice++;}}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  if(await p.locator('[onclick="closeChapterQuiz()"]').isVisible())await p.locator('[onclick="closeChapterQuiz()"]').click();
  const scroll=p.locator('.weather-humidity-scroll');
  if(width<620){await scroll.focus();await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('.weather-humidity-scroll').scrollLeft>0);await scroll.evaluate(e=>new Promise(resolve=>{let prev=e.scrollLeft,stable=0;const tick=()=>{stable=e.scrollLeft===prev?stable+1:0;prev=e.scrollLeft;if(stable===12)resolve();else requestAnimationFrame(tick);};requestAnimationFrame(tick);}));await scroll.evaluate(e=>{e.blur();e.scrollLeft=0;});}
  if(width===320&&dark){await p.locator('[data-weather-humidity]').screenshot({path:path.join(out,'humidity-320-dark.png'),style:'#score-board{visibility:hidden!important}'});await p.locator('[data-weather-high-pressure]').screenshot({path:path.join(out,'pressure-320-dark.png'),style:'#score-board{visibility:hidden!important}'});}
  if(width===1280&&!dark)await p.locator('[data-weather-humidity]').screenshot({path:path.join(out,'humidity-1280-light.png'),style:'#score-board{visibility:hidden!important}'});
  assert.deepEqual(await p.locator('.practice-box button').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width&&(r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1);}).map(e=>e.textContent)),[]);
  if(await p.locator('#chapter-quiz-launch').isVisible())await p.locator('#chapter-quiz-launch').click();
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(await p.locator('.chapter-question,.chapter-question label,.practice-box button').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width&& (r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1);}).map(e=>e.textContent)),[]);
 }
 for(const [qid,key]of Object.entries(keys))for(let a=0;a<3;a++){
  if(await p.locator('[onclick="restartChapterQuiz()"]').isVisible())await p.locator('[onclick="restartChapterQuiz()"]').click();
  await p.evaluate(({qid,a,keys})=>currentChapterQuiz.questions.forEach((q,i)=>document.querySelector(`input[name="chapter_q_${i}"][value="${q.id===qid?a:keys[q.id]}"]`).checked=true),{qid,a,keys});await p.locator('.chapter-submit-btn').click();const result=await p.evaluate(()=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results')).wetter);assert.equal(result.lastPercent,a===key?100:94);assert.equal(result.contentRevision,4);assert.deepEqual(result.reviewQuestionIds,a===key?[]:[qid]);assessed++;if(assessed%18===0)console.log("Assessed choices checked: "+assessed+"/54");
 }
 await p.goto(base+'/topics/worksheet.html?topic=wetter');await p.waitForFunction(()=>document.querySelectorAll('#ws-content>.question-block').length===18);assert.equal(await p.locator('#ws-solutions').isVisible(),false);await p.pdf({path:path.join(out,'weather-student.pdf'),format:'A4',printBackground:true,margin:{top:'14mm',bottom:'14mm',left:'14mm',right:'14mm'}});await p.locator('#ws-include-solutions').check();await p.pdf({path:path.join(out,'weather-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'14mm',bottom:'14mm',left:'14mm',right:'14mm'}});
 assert.equal(practice,39);assert.equal(assessed,54);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),layouts:6,practice,assessed,keyboardPractice:true,freePracticePreservesStorage:true,errors},null,2));console.log('PASS: six layouts, 39 keyboard-operated free choices and 54 independently keyed graded choices, revision 4, separate student and solution PDFs.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
