'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/invertebrate-key')),topic='bio_2_wirbellose';
const keys={"bio_2_wirbellose_s1":1,"bio_2_wirbellose_s2":2,"bio_2_wirbellose_d1":0,"bio_2_wirbellose_d2":1,"bio_2_wirbellose_d4":2,"bio_2_wirbellose_s3":0,"bio_2_wirbellose_comparison":1,"bio_2_wirbellose_s4":2,"bio_2_wirbellose_d3":1,"bio_2_wirbellose_s5":0,"bio_2_wirbellose_d5":2,"bio_2_wirbellose_ambiguity":2};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-invertebrate-key]')?.dataset.initialized==='true');const store=await p.evaluate(()=>JSON.stringify(localStorage)),legs=p.locator('[data-key-legs]'),shell=p.locator('[data-key-shell]'),foot=p.locator('[data-key-foot]'),status=p.locator('[data-key-status]');
 const sets={legs:{'':['ant','bee','spider','woodlouse','snail','slug','worm'],'0':['snail','slug','worm'],'6':['ant','bee'],'8':['spider'],many:['woodlouse']},shell:{'':['ant','bee','spider','woodlouse','snail','slug','worm'],yes:['snail'],no:['ant','bee','spider','woodlouse','slug','worm']},foot:{'':['ant','bee','spider','woodlouse','snail','slug','worm'],yes:['snail','slug'],no:['ant','bee','spider','woodlouse','worm']}};
 let combinations=0;for(const a of Object.keys(sets.legs))for(const c of Object.keys(sets.shell))for(const e of Object.keys(sets.foot)){await legs.selectOption(a);await shell.selectOption(c);await foot.selectOption(e);const expected=sets.legs[a].filter(id=>sets.shell[c].includes(id)&&sets.foot[e].includes(id));assert.deepEqual(await p.locator('[data-animal-example]').evaluateAll(es=>es.map(e=>e.dataset.animalExample)),expected);if(!expected.length)assert.match(await status.textContent(),/nicht, dass ein solches Tier unmöglich/);else if(expected.length===1)assert.match(await status.textContent(),/keine sichere Artbestimmung/);combinations++;}
 const scenarios=[['','',''],['6','no','no'],['0','no','yes'],['6','yes','']];
 for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});await p.evaluate(dark=>{if(dark)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);for(const [a,c,e]of scenarios){await legs.selectOption(a);await shell.selectOption(c);await foot.selectOption(e);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const control of await p.locator('[data-invertebrate-key] select,[data-key-reset]').all())assert.ok((await control.boundingBox()).height>=44);layouts.push({dark,width,legs:a,shell:c,foot:e});}if(width===390){await legs.selectOption('6');await shell.selectOption('no');await foot.selectOption('no');await p.locator('[data-invertebrate-key]').screenshot({path:path.join(out,'filter-'+(dark?'dark':'light')+'.png')});await p.locator('.invertebrate-profile').screenshot({path:path.join(out,'profile-'+(dark?'dark':'light')+'.png')});await p.locator('.invertebrate-data').screenshot({path:path.join(out,'data-'+(dark?'dark':'light')+'.png')});}}
 const reset=p.locator('[data-key-reset]');await reset.focus();await p.keyboard.press('Enter');assert.equal(await legs.evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('[data-animal-example]').count(),7);await p.keyboard.press('ArrowDown');assert.equal(await legs.inputValue(),'0');assert.equal(await p.locator('[data-animal-example]').count(),3);await p.keyboard.press('Tab');assert.equal(await shell.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Tab');assert.equal(await foot.evaluate(e=>e===document.activeElement),true);await reset.focus();await p.keyboard.press('Space');assert.equal(await legs.inputValue(),'');assert.equal(await shell.inputValue(),'');assert.equal(await foot.inputValue(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),store);
 let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:92);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-invertebrate-paper] tbody tr').count(),7);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-invertebrate-solution]').count(),5);await paper.pdf({path:path.join(out,'invertebrates-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),answers,combinations,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 45 filter combinations, 24 layout states, keyboard/reset/focus/storage, 36 native quiz answers and paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
