const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/equations-year2'),id='math2_5_var_gleichungen';
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const answers={m25_q1:0,m25_term_value:1,m25_fraction_term:2,m25_q2:0,m25_dip1:0,m25_reverse_order:1,m25_dip2:0,m25_valid_detour:2,m25_zero_step:1,m25_fraction_solution:2,m25_context_limit:1,m25_write_text:0,m25_formula_quantity:1,m25_formula_percent:2,m25_formula_rectangle:0};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===15&&document.querySelector('[data-equation2-step]')?.dataset.bound==='true');
  assert.equal(await page.locator('[data-equation2-tasks]>li').count(),15);let paths=0;
  for(const q of source.sections.flatMap(s=>s.quizzes))for(const[i,a]of q.answers.entries()){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:a.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===answers[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==answers[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));paths++;
  }
  const saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),probe=page.locator('[data-equation2-probe]'),select=probe.locator('select'),input=probe.locator('input'),feed=probe.locator('[role=status]');
  for(const[task,text,correct]of [[0,'4',true],[0,'7',false],[1,'15',true],[1,'5/3',false],[2,'2,5',true],[2,'5/2',true],[2,'2,4',false]]){
   await select.focus();await page.keyboard.press('Home');for(let i=0;i<task;i++)await page.keyboard.press('ArrowDown');assert.equal(await select.inputValue(),String(task));await input.fill(text);await input.press('Enter');assert.equal((await feed.innerText()).startsWith('Richtig:'),correct);
  }
  for(const bad of ['','2/0','1e2','2x']){await input.fill(bad);await input.press('Enter');assert.equal(await input.getAttribute('aria-invalid'),'true');assert.match(await feed.innerText(),/Gib eine Zahl/);}
  await probe.locator('[data-equation2-reset]').click();assert.equal(await select.evaluate(e=>e===document.activeElement),true);assert.equal(await input.inputValue(),'');
  const lab=page.locator('[data-equation2-step]'),caseSelect=lab.locator('select'),expected=['same','same','changed','changed','undefined','same'];let decisions=0;
  for(let i=0;i<6;i++){
   await caseSelect.focus();await page.keyboard.press('Home');for(let j=0;j<i;j++)await page.keyboard.press('ArrowDown');assert.equal(await caseSelect.inputValue(),String(i));assert.equal(await lab.locator('[role=status]').innerText(),'');
   for(const verdict of ['same','changed','undefined']){await lab.locator('[data-equation2-verdict='+verdict+']').focus();await page.keyboard.press('Enter');assert.equal((await lab.locator('[role=status]').innerText()).startsWith('Richtig:'),verdict===expected[i]);decisions++;}
  }
  await lab.locator('[data-equation2-step-reset]').click();assert.equal(await caseSelect.evaluate(e=>e===document.activeElement),true);assert.equal(await caseSelect.inputValue(),'0');assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('.equation2-lab h3')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(let i=0;i<6;i++){await caseSelect.selectOption(String(i));await lab.locator('[data-equation2-verdict='+expected[i]+']').click();const geometry=await lab.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('select,button')].map(b=>{const x=b.getBoundingClientRect();return {left:x.left,right:x.right,height:x.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow);assert.ok(geometry.controls.every(b=>b.left>=geometry.left&&b.right<=geometry.right+1&&b.height>=44));layouts.push({width,theme,case:i,geometry});if(width===390&&i===1)await lab.screenshot({path:path.join(out,'detour-'+theme+'.png')});}
   const labels=await page.locator('[data-equation2-chain]').evaluate(e=>[...e.querySelectorAll('text')].map(t=>{const b=t.getBBox();return {x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height};}));assert.ok(labels.every(b=>b.x>=0&&b.right<=360&&b.y>=0&&b.bottom<=220));
   await select.selectOption('2');await input.fill('5/2');await input.press('Enter');const b=await probe.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=width+1);if(width===390)await probe.screenshot({path:path.join(out,'probe-'+theme+'.png')});
  }
  const attempts=[];for(const[wrong,section]of [['m25_valid_detour',2],['m25_context_limit',3]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const[i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(answers[q]+1)%3:answers[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,93);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),15);assert.equal(await paper.locator('[data-equation2-case-paper] tbody tr').count(),6);assert.equal(await paper.locator('[data-equation2-probe-paper] tbody tr').count(),3);assert.equal(await paper.locator('#ws-math-material svg').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('.ws-generated-equation-solution').first().isVisible(),false);
  const generated=await paper.locator('[data-generated-equation]').evaluateAll(nodes=>nodes.map(e=>({a:Number(e.dataset.a),b:Number(e.dataset.b),r:Number(e.dataset.result),text:e.textContent})));assert.equal(generated.length,12);
  await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('.ws-paper-solution').count(),5);const generatedAnswers=await paper.locator('#ws-solutions .ws-generated-equation-solution').evaluateAll(nodes=>nodes.map(e=>({x:Number(e.dataset.generatedAnswer),text:e.textContent})));assert.equal(generatedAnswers.length,12);for(let i=0;i<12;i++){const {a,b,r}=generated[i],{x,text}=generatedAnswers[i];assert.equal((r-b)/a,x);assert.equal(a*x+b,r);assert.ok(text.includes(a+' · '+x+' + '+b+' = '+r));}
  await paper.locator('#ws-include-solutions').uncheck();assert.equal(await paper.locator('.ws-generated-equation-solution').first().isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.deepEqual(await paper.locator('[data-generated-equation]').allTextContents(),generated.map(x=>x.text));await paper.pdf({path:path.join(out,'equations-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),paths,decisions,layouts,attempts,errors,scope:'45 native quiz answers, 18 keyboard transformation judgements, fraction/decimal/invalid inputs, resets, 36 step layouts plus 6 probe/diagram layouts, two 93% checks and worksheet export. PDF visual review separate; no complete curriculum or classroom acceptance.'},null,2)+'\n');console.log('PASS: year-two equations native: 45 quiz answers, 18 keyboard judgements, probe inputs/reset/no storage, 36 step plus 6 probe/diagram layouts, two 93% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
