const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/powers-year3'),id='math3_2_potenzen_terme';
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const answers={m32_q1:1,m32_sign:0,m32_exponent:2,m32_product:0,m32_quotient:1,m32_power_power:2,m32_dip1:0,m32_collect:1,m32_q2:0,m32_expand:2,m32_factor:0,m32_cancel:1,m32_binomial_plus:1,m32_binomial_minus:2,m32_binomial_product:0,m32_counterexample:1,m32_border:2,m32_special_case:0};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===18&&document.querySelector('[data-power-lab]')?.dataset.bound==='true');let paths=0;
  assert.equal(await page.locator('[data-power-tasks]>li').count(),18);
  for(const q of source.sections.flatMap(s=>s.quizzes))for(const[i,a]of q.answers.entries()){const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:a.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===answers[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==answers[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));paths++;}
  const saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),lab=page.locator('[data-power-lab]'),mode=lab.locator('[data-power-mode]'),aInput=lab.locator('[data-power-a]'),bInput=lab.locator('[data-power-b]');
  async function keyboardSelect(locator,index){await locator.focus();await page.keyboard.press('Home');for(let i=0;i<index;i++)await page.keyboard.press('ArrowDown');}
  async function checkValue(key,a,b){const expected=key==='sum'?(a+b)*(a+b):key==='difference'?(a-b)*(a-b):(a+b)*(a-b);for(const s of ['[data-power-original]','[data-power-expanded]'])assert.equal(Number((await lab.locator(s).innerText()).split(' = ').at(-1)),expected);assert.equal(await lab.locator('[data-power-model]').isVisible(),key==='sum'||a>=b);}
  for(let m=0;m<3;m++){await keyboardSelect(mode,m);await keyboardSelect(aInput,0);await keyboardSelect(bInput,6);await checkValue(['sum','difference','product'][m],2,6);}
  await lab.locator('[data-power-reset]').click();assert.equal(await mode.evaluate(e=>e===document.activeElement),true);assert.equal(await aInput.inputValue(),'6');assert.equal(await bInput.inputValue(),'2');assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);
  let diagrams=0;for(const key of ['sum','difference','product'])for(let a=2;a<=8;a++)for(let b=0;b<=8;b++){
   await mode.selectOption(key);await aInput.selectOption(String(a));await bInput.selectOption(String(b));await checkValue(key,a,b);if(key!=='sum'&&a<b)continue;
   const bounds=await lab.locator('svg').evaluate(e=>{const v=e.viewBox.baseVal;return [...e.querySelectorAll('text')].map(t=>{const r=t.getBBox();return {text:t.textContent,left:r.x,right:r.x+r.width,top:r.y,bottom:r.y+r.height,width:v.width,height:v.height};});});assert.ok(bounds.every(r=>r.left>=0&&r.right<=r.width&&r.top>=0&&r.bottom<=r.height),JSON.stringify({key,a,b,bounds}));diagrams++;
  }
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('.power-lab h3')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(const key of ['sum','difference','product'])for(const[a,b]of [[6,2],[6,0],[2,6]]){await mode.selectOption(key);await aInput.selectOption(String(a));await bInput.selectOption(String(b));await checkValue(key,a,b);const geometry=await lab.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('select,button')].map(b=>{const x=b.getBoundingClientRect();return {left:x.left,right:x.right,height:x.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow,JSON.stringify({width,theme,key,a,b,geometry}));assert.ok(geometry.controls.every(c=>c.left>=geometry.left&&c.right<=geometry.right+1&&c.height>=44));layouts.push({width,theme,key,a,b,geometry});if(width===390&&a===6&&b===2)await lab.locator('[data-power-model]').screenshot({path:path.join(out,key+'-'+theme+'.png')});if(width===390&&key==='product'&&a===2)await lab.screenshot({path:path.join(out,'model-limit-'+theme+'.png')});}
   if(width===390)for(const key of ['sum','difference','product'])await page.locator('[data-power-static]').filter({has:page.locator('[data-power-diagram="'+key+'"]')}).screenshot({path:path.join(out,'static-'+key+'-'+theme+'.png')});
  }
  const attempts=[];for(const[wrong,section]of [['m32_binomial_minus',4],['m32_special_case',5]]){await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const[i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(answers[q]+1)%3:answers[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,94);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));}
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),18);assert.equal(await paper.locator('[data-power-paper] tbody tr').count(),9);assert.equal(await paper.locator('#ws-math-material svg').count(),3);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('[data-power-answer]').first().isVisible(),false);
  const generated=await paper.locator('[data-power-generated]').evaluateAll(nodes=>nodes.map(e=>({base:Number(e.dataset.base),exponent:Number(e.dataset.exponent),text:e.textContent})));assert.equal(generated.length,8);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('.ws-paper-solution').count(),6);const generatedAnswers=await paper.locator('#ws-solutions [data-power-answer]').evaluateAll(nodes=>nodes.map(e=>({answer:Number(e.dataset.powerAnswer),text:e.textContent})));assert.equal(generatedAnswers.length,8);for(let i=0;i<8;i++){let product=1;for(let k=0;k<generated[i].exponent;k++)product*=generated[i].base;assert.equal(product,generatedAnswers[i].answer);}
  await paper.locator('#ws-include-solutions').uncheck();assert.equal(await paper.locator('[data-power-answer]').first().isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.deepEqual(await paper.locator('[data-power-generated]').allTextContents(),generated.map(x=>x.text));await paper.pdf({path:path.join(out,'powers-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),paths,diagrams,layouts,attempts,generated,generatedAnswers,errors,scope:'54 native answers, keyboard models/reset, 189 calculations and 147 SVG text bounds, 54 layouts, two 94% checks and paper export; selected PDF visual review separately, no overall curriculum acceptance.'},null,2)+'\n');console.log('PASS: powers year three native: 54 answers, keyboard/reset, 189 calculations/147 diagrams, 54 layouts, two 94% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
