const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/orientation-models')),topic='dgb5_orientierung',keys=require('./fixtures/dgb5_orientation_keys.json'),chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic];
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let evaRuns=0,representations=0,decisions=0,answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-eva-lab]')?.dataset.bound==='1');const stored=await p.evaluate(()=>JSON.stringify(localStorage));
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const [value,limit,expected]of [[10,50,'AN'],[49,50,'AN'],[50,50,'AUS'],[80,50,'AUS'],[49,30,'AUS']]){
   await p.locator('#eva-value').fill(String(value));await p.locator('#eva-limit').selectOption(String(limit));const step=p.locator('[data-eva-step]');await step.focus();await p.keyboard.press('Enter');assert.match(await p.locator('[data-eva-input]').innerText(),new RegExp(' '+value+'\\.'));assert.equal(await p.locator('[data-eva-output]').innerText(),'Noch nicht ausgeführt.');await p.keyboard.press('Enter');assert.equal(await p.locator('[data-eva-output]').innerText(),'Noch nicht ausgeführt.');await p.keyboard.press('Enter');assert.equal(await p.locator('[data-eva-output]').innerText(),'Modellleuchte: '+expected+'.');assert.equal(await p.locator('[data-eva-reset]').evaluate(e=>e===document.activeElement),true);evaRuns++;
  }
  const reset=p.locator('[data-representation-reset]'),range=p.locator('#representation-value');await reset.click();assert.equal(await range.evaluate(e=>e===document.activeElement),true);
  for(const [moves,n,whole]of [[-3,211,'21'],[3,214,'21'],[1,215,'22']]){
   await range.focus();for(let i=0;i<Math.abs(moves);i++)await p.keyboard.press(moves<0?'ArrowLeft':'ArrowRight');assert.equal(await range.inputValue(),String(n));
   for(const [precision,expected]of [['10',whole],['1',(n/10).toFixed(1).replace('.',',')]]){await p.locator('#representation-step').selectOption(precision);assert.equal(await p.locator('[data-representation-digital]').innerText(),expected+' °C');representations++;}
  }
  const lab=p.locator('[data-orientation-cases]');for(const [i,key]of [1,2].entries()){await lab.locator('select').selectOption(String(i));for(let a=0;a<3;a++){const b=lab.locator('[data-boundary-case]').nth(i).getByRole('button').nth(a);await b.focus();await p.keyboard.press('Enter');assert.equal((await lab.locator('[role=status]').innerText()).startsWith('Richtig:'),a===key);decisions++;}}
  await lab.locator('[data-boundary-reset]').click();assert.equal(await lab.locator('select').evaluate(e=>e===document.activeElement),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  for(const selector of ['[data-media-change]','[data-media-day]']){const table=p.locator(selector);assert.equal(await table.getAttribute('role'),'table');assert.deepEqual(await table.locator('tbody th,tbody td').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.textContent)),[]);}
  if(width===320){await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});for(const [name,selector]of [['eva','[data-eva-lab]'],['scale','.orientation-model-grid'],['case','[data-orientation-cases]'],['history','[data-media-change]'],['day','[data-media-day]']]){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png'),animations:'disabled'});}}
 }
 await p.locator('#eva-value').fill('101');await p.locator('[data-eva-step]').click();assert.equal(await p.locator('#eva-value').getAttribute('aria-invalid'),'true');assert.equal(await p.locator('#eva-value').evaluate(e=>e===document.activeElement),true);await p.locator('[data-eva-reset]').click();assert.equal(await p.locator('#eva-value').inputValue(),'49');assert.equal(await p.locator('#eva-value').getAttribute('aria-invalid'),null);
 for(const q of chapter.sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly)){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [i,a]of q.answers.entries()){const b=box.getByRole('button',{name:a.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),i==={dgb5_orientierung_p1:0,dgb5_orientierung_p2:2,dgb5_orientierung_p3:1}[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));practiceAnswers++;}}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(ids,Object.keys(keys));
 for(const [n,id]of ids.entries())for(let a=0;a<3;a++){if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(result.lastPercent,a===keys[id]?100:88);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;}
 await p.goto(base+'/topics/worksheet.html?topic='+topic);await p.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await p.locator('#ws-solutions').isVisible(),false);assert.equal(await p.locator('[data-eva-paper] tbody tr').count(),5);assert.equal(await p.locator('[data-representation-paper] tbody tr').count(),3);await p.locator('#ws-include-solutions').check();await p.pdf({path:path.join(out,'dgb5_orientierung-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(evaRuns,30);assert.equal(representations,36);assert.equal(decisions,36);assert.equal(answers,24);assert.equal(practiceAnswers,9);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),evaRuns,representations,decisions,answers,practiceAnswers,layouts:6,keyboardAndFocus:true,workshopStorageUnchanged:true,errors},null,2));console.log('PASS: 30 native stepped EVA runs, 36 rounding views, 36 media decisions, 24 quiz answers, nine practices, six layouts, keyboard/focus/validation, unchanged workshop storage and chapter PDF.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
