const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/production-projects')),topic='dgb6_produktion',keys=require('./fixtures/dgb6_production_keys.json'),chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic];
const source='# mein Remix\nSETZE punkte 5\nFÜR JEDE ANTWORT\n WENN RICHTIG\n  ERHÖHE punkte 3\n ENDE\n WENN FALSCH\n  ERHÖHE punkte -1\n ENDE\n ZEIGE punkte\nENDE';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];let programRuns=0,mediaViews=0,answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));const save=async(button,name)=>{const promise=p.waitForEvent('download');await p.locator(button).click();const download=await promise,target=path.join(out,name);await download.saveAs(target);return target;};
 await p.goto(base+'/examples/punktewerkstatt.html');await p.locator('#program').fill(source);await p.locator('#prediction').fill('richtig – falsch – richtig: 8, 7, 10');await p.locator('#notes').fill('Erwartung 8,7,10 mit Ausgaben verglichen. SETZE muss vor die Wiederholung.');await p.locator('#credit').fill('SciVerse-Punktewerkstatt; eigener Start 5, richtig +3, falsch -1.');
 for(const width of [320,390,1280])for(const colorScheme of ['light','dark']){await p.setViewportSize({width,height:1000});await p.emulateMedia({colorScheme});for(const [values,expected]of [[['richtig','falsch','richtig'],['8','7','10']],[['falsch','falsch','falsch'],['4','3','2']],[['richtig','richtig','richtig'],['8','11','14']]]){for(let i=0;i<3;i++)await p.locator('#answer-'+(i+1)).selectOption(values[i]);await p.locator('#restart').click();await p.locator('#run').focus();await p.keyboard.press('Enter');assert.deepEqual(await p.locator('#output li').allTextContents(),expected);programRuns++;}assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);if(width===320){await p.locator('#editor-title').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'program-'+colorScheme+'.png')});}}
 await p.locator('#answer-2').selectOption('falsch');await p.locator('#run').click();const programFile=await save('#save','mein-punkteprogramm.html');await p.goto(pathToFileURL(programFile).href);assert.equal(await p.locator('#program').inputValue(),source);assert.ok((await p.locator('#notes').inputValue()).includes('SETZE'));await p.locator('#run').click();assert.deepEqual(await p.locator('#output li').allTextContents(),['8','7','10']);await p.locator('#program').fill('SETZE punkte 5\nZEIGE punkte');await p.locator('#step').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#memory').innerText(),'5');assert.equal(await p.locator('#output li').count(),0);await p.keyboard.press('Enter');assert.equal(await p.locator('#restart').evaluate(e=>e===document.activeElement),true);
 await p.locator('#program').fill('FÜR JEDE ANTWORT');await p.locator('#check').click();assert.match(await p.locator('#status').innerText(),/fehlt ENDE/);assert.equal(await p.locator('#output li').count(),0);
 await p.goto(base+'/examples/signalwerkstatt.html');await p.locator('#headline').fill('Unsere Besprechung beginnt');await p.locator('#meaning').fill('Bitte beendet euren Satz und kommt zur vereinbarten Besprechung.');await p.locator('#notes').fill('Fassung B: hoch – mittel – tief. Hörvergleich mit einer Testperson noch offen.');
 for(const width of [320,390,1280])for(const colorScheme of ['light','dark']){await p.setViewportSize({width,height:1000});await p.emulateMedia({colorScheme});await p.locator('#tone-1').selectOption('800');await p.locator('#tone-2').selectOption('600');await p.locator('#tone-3').selectOption('400');await p.locator('#duration').selectOption('0.4');await p.locator('#generate').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>document.getElementById('player').readyState>=1);assert.ok(Math.abs(await p.locator('#player').evaluate(e=>e.duration)-1.6)<.001);assert.equal(await p.locator('#player').evaluate(e=>e.paused),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await p.locator('#preview').click();assert.equal(await p.locator('#preview-title').evaluate(e=>e===document.activeElement),true);if(width===320){await p.screenshot({path:path.join(out,'signal-'+colorScheme+'.png')});}mediaViews++;}
 await p.locator('#player').evaluate(e=>e.play());await p.waitForFunction(()=>document.getElementById('player').currentTime>0);await p.locator('#duration').selectOption('0.2');assert.equal(await p.locator('#player').getAttribute('src'),null);assert.equal(await p.locator('#player').evaluate(e=>e.paused),true);await p.locator('#duration').selectOption('0.4');const mediaFile=await save('#save','mein-signal-arbeitsdatei.html'),resultFile=await save('#export','mein-gruppensignal.html'),wavFile=await save('#wav','mein-gruppensignal.wav');const bytes=fs.readFileSync(wavFile);assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.length,51244);
 await p.goto(pathToFileURL(mediaFile).href);assert.equal(await p.locator('#tone-1').inputValue(),'800');assert.ok((await p.locator('#notes').inputValue()).includes('noch offen'));assert.equal(await p.locator('#player').getAttribute('src'),null);await p.locator('#generate').click();await p.waitForFunction(()=>document.getElementById('player').readyState>=1);assert.ok(Math.abs(await p.locator('#player').evaluate(e=>e.duration)-1.6)<.001);await p.goto(pathToFileURL(resultFile).href);assert.equal(await p.locator('script').count(),0);assert.equal(await p.locator('textarea,select,button').count(),0);assert.equal(await p.locator('#card-title').innerText(),'Unsere Besprechung beginnt');await p.waitForFunction(()=>document.getElementById('player').readyState>=1);assert.equal(await p.locator('#player').evaluate(e=>e.paused),true);await p.locator('#player').evaluate(e=>e.play());await p.waitForFunction(()=>document.getElementById('player').currentTime>0);await p.locator('#player').evaluate(e=>e.pause());
 await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>window.currentChapterQuiz?.questions.length===12);const stored=await p.evaluate(()=>JSON.stringify(localStorage));for(const q of chapter.sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly)){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const a of q.answers){await box.getByRole('button',{name:a.text,exact:true}).click();assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));practiceAnswers++;}}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
 for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);if(width===320){await p.locator('[data-program-project]').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'chapter-'+(dark?'dark':'light')+'.png')});}}
 const questions=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(questions,Object.keys(keys));for(const [n,id]of questions.entries())for(let a=0;a<3;a++){if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(r.lastPercent,a===keys[id]?100:92);assert.equal(r.contentRevision,3);assert.deepEqual(r.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;}
 await p.goto(base+'/topics/worksheet.html?topic='+topic);await p.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await p.locator('#ws-solutions').isVisible(),false);await p.locator('#ws-include-solutions').check();await p.pdf({path:path.join(out,'dgb6_produktion-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(programRuns,18);assert.equal(mediaViews,6);assert.equal(answers,36);assert.equal(practiceAnswers,9);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),programRuns,mediaViews,answers,practiceAnswers,chapterLayouts:6,offlineFiles:3,downloads:4,audioDecodedAndPlayed:true,staleAudioStopped:true,errors},null,2));console.log('PASS: 18 program runs, six media layouts, four real downloads, three reopened offline HTML files, WAV decode/playback, 36 assessed answers, nine practices and final chapter PDF.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
