const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/skeleton-movement')),id='bio_1_skelett_bewegung',source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const correct={bio_skelett_s1:0,bio_skelett_s2a:0,bio_skelett_s3a:0,bio_skelett_s2:0,bio_skelett_s3:2,bio_skelett_s6:2,bio_skelett_d1:1,bio_skelett_d2:0,bio_skelett_d3:0,bio_skelett_d4:1,bio_skelett_d5:0,bio_skelett_d6:0,bio_skelett_absenken:2,bio_skelett_modell:1,bio_1_skelett_extra_muskeln:1};
const states={lift:{angles:[150,90],answer:'shorter'},hold:{angles:[90,90],answer:'same'},lower:{angles:[90,150],answer:'longer'}};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===14);assert.equal(await page.locator('.bio-training-card').count(),18);
  let paths=0;for(const q of source.sections.flatMap(s=>s.quizzes))for(const [i,answer]of q.answers.entries()){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:answer.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===correct[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==correct[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));assert.equal(await button.isDisabled(),false);paths++;
  }
  assert.equal(paths,45);const z=page.locator('[data-core-experiment="muscle-actions"]'),action=z.locator('[data-muscle-action]'),prediction=z.locator('[data-muscle-prediction]'),check=z.locator('[data-muscle-check]'),reset=z.locator('[data-muscle-reset]'),result=z.locator('[data-muscle-result]'),saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results'));let comparisons=0;
  for(const [index,[key,state]]of Object.entries(states).entries()){
   await action.focus();await page.keyboard.press('Home');for(let n=0;n<index;n++)await page.keyboard.press('ArrowDown');assert.equal(await action.inputValue(),key);assert.equal(await prediction.inputValue(),'');await check.focus();await page.keyboard.press('Enter');assert.match(await result.innerText(),/Wähle zuerst/);
   for(const [i,part]of ['start','end'].entries()){
    const coords=await z.locator('[data-muscle-'+part+']').evaluate(e=>[Number(e.getAttribute('x2')),Number(e.getAttribute('y2'))]);assert.ok(Math.abs(Math.hypot(coords[0]-105,coords[1]-150)-105)<1e-8);assert.ok(Math.abs(Math.acos((150-coords[1])/105)*180/Math.PI-state.angles[i])<1e-8);
   }
   for(const [i,answer]of ['shorter','same','longer'].entries()){
    await prediction.focus();await page.keyboard.press('Home');for(let n=0;n<=i;n++)await page.keyboard.press('ArrowDown');assert.equal(await prediction.inputValue(),answer);assert.equal(await result.innerText(),'Noch nicht geprüft.');await check.focus();await page.keyboard.press('Enter');assert.equal(await z.getAttribute('data-muscle-state'),answer===state.answer?'correct':'review');assert.match(await result.innerText(),/Zug/);comparisons++;
   }
  }
  assert.equal(comparisons,9);assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);await reset.click();assert.equal(await action.inputValue(),'lift');assert.equal(await prediction.inputValue(),'');assert.equal(await action.evaluate(e=>e===document.activeElement),true);
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('[data-core-experiment="muscle-actions"] p')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(const key of Object.keys(states)){
    await action.selectOption(key);await prediction.selectOption(states[key].answer);await check.click();const geometry=await z.evaluate(e=>{const r=e.getBoundingClientRect(),svg=e.querySelector('svg'),b=svg.getBoundingClientRect();return {left:r.left,right:r.right,width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,svgLeft:b.left,svgRight:b.right,labels:[...svg.querySelectorAll('text')].map(t=>{const b=t.getBBox();return {x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow);assert.ok(geometry.svgLeft>=0&&geometry.svgRight<=width+1);assert.ok(geometry.labels.every(t=>t.x>=0&&t.right<=320&&t.y>=0&&t.bottom<=330));layouts.push({width,theme,key,geometry});if(width===390)await z.screenshot({path:path.join(out,key+'-'+theme+'.png')});
   }
  }
  await page.setViewportSize({width:390,height:844});const table=page.locator('[data-muscle-protocol]'),parent=table.locator('..'),scrollable=await parent.getAttribute('role')==='region';
  if(scrollable){assert.equal(await parent.getAttribute('tabindex'),'0');await parent.focus();for(let i=0;i<100&&await parent.evaluate(e=>e.scrollLeft<e.scrollWidth-e.clientWidth-1);i++){await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);}assert.ok(await parent.evaluate(e=>e.scrollLeft>=e.scrollWidth-e.clientWidth-1));}else{const b=await table.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=391);}
  await (scrollable?parent:table).screenshot({path:path.join(out,'protocol-mobile.png')});
  const attempts=[];for(const [wrong,section]of [['bio_skelett_absenken',3],['bio_skelett_d4',4]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(correct[q]+1)%3:correct[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,93);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),14);assert.equal(await paper.locator('#ws-biology-material .bio-training-card').count(),18);assert.equal(await paper.locator('#ws-biology-material .ws-glossary-entry').count(),31);assert.equal(await paper.locator('[data-muscle-protocol] tbody tr').count(),3);assert.equal(await paper.locator('[data-muscle-paper] svg').count(),1);assert.equal(await paper.locator('#ws-biology-material select,#ws-biology-material button,#ws-biology-material [data-muscle-diagram]').count(),0);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);
  const printOptions={format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}};
  await paper.pdf({...printOptions,path:path.join(out,'skeleton.pdf')});await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions').isVisible(),true);assert.match(await paper.locator('#ws-solutions').innerText(),/Beugemuskeln länger unter Zug/);await paper.pdf({...printOptions,path:path.join(out,'skeleton-solutions.pdf')});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({generatedAt:new Date().toISOString(),base,browser:browser.version(),paths,comparisons,layouts,scrollableProtocol:scrollable,attempts,pageErrors:errors,scope:'45 native quiz choices, 9 keyboard predictions, angle and length checks, reset/focus/storage, 18 model/layout states, protocol access, two 93% checks and paper with separate solutions. Visual inspection separate; no classroom or whole-site acceptance.'},null,2)+'\n');console.log('PASS: skeleton native: 45 quiz choices, 9 keyboard predictions, 18 model/layout states, protocol, two 93% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
