'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/circulation')),topic='bio_3_blut_kreislauf';
const targets=['Lungenarterien','Lungenkapillaren','Lungenvenen','Linker Vorhof','Linke Herzkammer','Körperarterien','Körperkapillaren','Körpervenen','Rechter Vorhof','Rechte Herzkammer'];
const keys={bio_3_blut_s1:1,bio_3_blut_d1:2,bio_3_blut_d4:0,bio_3_blut_path:1,bio_3_blut_s2:1,bio_3_blut_d2:0,bio_3_blut_clot:2,bio_3_blut_s3:0,bio_3_blut_d3:2,bio_3_blut_volume:0,bio_3_blut_s4:1};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-circulation-lab]')?.dataset.initialized==='true');
const zone=p.locator('[data-circulation-lab]'),buttons=p.locator('[data-circulation-choice]'),next=p.locator('[data-circulation-next]'),reset=p.locator('[data-circulation-reset]'),current=p.locator('[data-circulation-current]'),feedback=p.locator('[data-circulation-feedback]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));let decisions=0;
for(let i=0;i<10;i++){assert.equal(await zone.getAttribute('data-step'),String(i));assert.equal(await next.isDisabled(),true);const labels=await buttons.allTextContents(),correct=labels.indexOf(targets[i]);assert.ok(correct>=0);for(let k=0;k<3;k++)if(k!==correct){await buttons.nth(k).click();assert.equal(await feedback.getAttribute('data-correct'),'false');assert.equal(await next.isDisabled(),true);assert.equal(await zone.getAttribute('data-step'),String(i));decisions++;}await buttons.nth(correct).focus();await p.keyboard.press('Enter');assert.equal(await feedback.getAttribute('data-correct'),'true');assert.equal(await next.isEnabled(),true);decisions++;await next.focus();await p.keyboard.press('Enter');assert.equal(await current.evaluate(e=>e===document.activeElement),true);}
assert.equal(await zone.getAttribute('data-step'),'10');assert.equal(await next.isVisible(),false);assert.equal(await p.locator('[data-circulation-options]').isVisible(),false);await reset.focus();await p.keyboard.press('Enter');assert.equal(await buttons.nth(0).evaluate(e=>e===document.activeElement),true);assert.equal(await zone.getAttribute('data-step'),'0');assert.equal(await feedback.textContent(),'');
for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);await reset.click();
for(const card of await p.locator('.circulation-card').all()){assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');assert.equal(await card.evaluate(e=>getComputedStyle(e).color),dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)');}
for(let i=0;i<10;i++){const correct=(await buttons.allTextContents()).indexOf(targets[i]);await buttons.nth(correct).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const c of [...await buttons.all(),next,reset])assert.ok((await c.boundingBox()).height>=44);layouts.push({dark,width,stage:i});if(width===390&&i===0)await zone.screenshot({path:path.join(out,'workshop-'+(dark?'dark':'light')+'.png')});await next.click();}
assert.equal(await next.isVisible(),false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);layouts.push({dark,width,stage:'complete'});
if(width===390){for(const [name,s]of [['schema','.circulation-map'],['vessels','.circulation-vessels'],['components','.circulation-components'],['pulse','.circulation-pulse'],['output','.circulation-output'],['cases','.circulation-cases']])await p.locator(s).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png')});}}
assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,11);for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){
if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);const f=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(f));answers++;}
const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.circulation-map svg').count(),1);assert.equal(await paper.locator('[data-circulation-paper]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-circulation-solution]').count(),4);await paper.pdf({path:path.join(out,'circulation-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,layouts,themeColors:true,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 30 route decisions, 66 layouts, keyboard/reset/focus/storage, 33 quiz answers, paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
