const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/puberty-boundaries')),id='bio_1_pubertaet_fortpflanzung',source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const correct={bio_pubertaet_s1:1,bio_pubertaet_d1:2,bio_pubertaet_s2:0,bio_pubertaet_d3:1,bio_pubertaet_organ:2,bio_pubertaet_s3:2,bio_pubertaet_d4:0,bio_pubertaet_s4:1,bio_pubertaet_d2:2,bio_pubertaet_d5:0,bio_pubertaet_s5:1,bio_pubertaet_d6:2,bio_pubertaet_hilfe:0,bio_1_pubertaet_extra_respekt:1};
const reasons=[[/erkennbar/,/ohne persönliche Angaben/,/Druck/],[/keine automatische Zustimmung/,/Zuschneiden ersetzt/,/eigene Klärung/],[/Schweigen ist kein Einverständnis/,/Verantwortung/,/nicht weitere Details/],[/beendet.*nicht/,/weitere Unterstützung/,/nicht von einer Abstimmung/]];
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===13);assert.equal(await page.locator('.bio-training-card').count(),15);
  let paths=0;for(const q of source.sections.flatMap(s=>s.quizzes))for(const [i,answer]of q.answers.entries()){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:answer.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===correct[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==correct[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));assert.equal(await button.isDisabled(),false);paths++;
  }
  assert.equal(paths,42);const z=page.locator('[data-core-experiment="boundary-cases"]'),control=z.locator('select'),result=z.locator('[role=status]'),saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results'));let decisions=0;
  for(let i=0;i<4;i++){
   await control.focus();await page.keyboard.press('Home');for(let n=0;n<i;n++)await page.keyboard.press('ArrowDown');assert.equal(await control.inputValue(),String(i));assert.equal(await result.innerText(),'Wähle eine Handlung.');assert.equal(await z.locator('[data-boundary-case]:visible').count(),1);
   for(let j=0;j<3;j++){const b=z.locator('[data-boundary-case="'+i+'"] button').nth(j);await b.focus();await page.keyboard.press('Enter');assert.match(await result.innerText(),reasons[i][j]);assert.equal(await b.evaluate(e=>e===document.activeElement),true);decisions++;}
  }
  assert.equal(decisions,12);assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);await z.locator('[data-boundary-reset]').click();assert.equal(await control.inputValue(),'0');assert.equal(await control.evaluate(e=>e===document.activeElement),true);
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('[data-core-experiment="boundary-cases"] p')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(let i=0;i<4;i++){
    await control.selectOption(String(i));await z.locator('[data-boundary-case="'+i+'"] button').nth([1,2,0,1][i]).click();const geometry=await z.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('select,button')].filter(b=>b.getClientRects().length).map(b=>{const r=b.getBoundingClientRect();return {x:r.x,right:r.right,height:r.height,clipped:b.scrollWidth>b.clientWidth+1};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow);assert.ok(geometry.controls.every(b=>b.x>=0&&b.right<=width+1&&b.height>=44&&!b.clipped));layouts.push({width,theme,case:i,geometry});if(width===390&&(i===1||i===3))await z.screenshot({path:path.join(out,'case-'+i+'-'+theme+'.png')});
   }
   if(width===390)await page.locator('[data-cycle-schema]').screenshot({path:path.join(out,'cycle-'+theme+'.png')});
  }
  await page.setViewportSize({width:390,height:844});const table=page.locator('[data-boundary-protocol]'),parent=table.locator('..'),scrollable=await parent.getAttribute('role')==='region';
  if(scrollable){assert.equal(await parent.getAttribute('tabindex'),'0');await parent.focus();for(let i=0;i<100&&await parent.evaluate(e=>e.scrollLeft<e.scrollWidth-e.clientWidth-1);i++){await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);}assert.ok(await parent.evaluate(e=>e.scrollLeft>=e.scrollWidth-e.clientWidth-1));}else{const b=await table.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=391);}
  const attempts=[];for(const [wrong,section]of [['bio_pubertaet_d2',3],['bio_pubertaet_hilfe',4]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(correct[q]+1)%3:correct[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const stored=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(stored.lastPercent,92);assert.equal(stored.contentRevision,2);assert.deepEqual(stored.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result:stored});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),13);assert.equal(await paper.locator('#ws-biology-material .bio-training-card').count(),15);assert.equal(await paper.locator('#ws-biology-material .ws-glossary-entry').count(),25);assert.equal(await paper.locator('[data-boundary-protocol] tbody tr').count(),4);assert.equal(await paper.locator('[data-boundary-paper-case]').count(),4);assert.equal(await paper.locator('#ws-biology-material select,#ws-biology-material button').count(),0);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);
  await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions').isVisible(),true);assert.match(await paper.locator('#ws-solutions').innerText(),/Fall 4, B/);await paper.pdf({format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'},path:path.join(out,'puberty-solutions.pdf')});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({generatedAt:new Date().toISOString(),base,browser:browser.version(),paths,decisions,layouts,scrollableProtocol:scrollable,attempts,pageErrors:errors,scope:'42 native quiz choices, 12 keyboard decisions, reset/focus/storage, 24 case/layout states, protocol access, two 92% checks and paper with separate solutions. Visual inspection separate; no classroom or whole-site acceptance.'},null,2)+'\n');console.log('PASS: puberty native: 42 quiz choices, 12 keyboard decisions, 24 case/layout states, protocol, two 92% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
