'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/bio4-path')),topic='bio_4_kompetenzplan';
const keys={bio_4_plan_s1:1,bio_4_plan_d1:2,bio_4_plan_s2:0,bio_4_plan_d2:2,bio_4_plan_d3:1,bio_4_plan_naechster_schritt:0,bio_4_plan_speicher:2,bio_4_plan_revision:1},correct=[1,2,0,2,1,0,2,1];
const topics=['bio_4_landwirtschaft_biodiversitaet','bio_4_siedlungsraeume','bio_4_kohlenstoff_klima','bio_4_genetik_gentechnik','bio_4_immunsystem_resistenzen','bio_4_nerven_hormone','bio_4_sexualitaet_verantwortung','bio_4_menschheitsentwicklung'],sections=[2,1,1,1,2,2,3,2];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-bio4path-lab]')?.dataset.initialized==='true');
 await p.evaluate(topics=>{localStorage.setItem('sciverse_chapter_quiz_results',JSON.stringify({[topics[0]]:{contentRevision:2,lastPercent:60,bestPercent:100},[topics[1]]:{contentRevision:1,lastPercent:100},[topics[2]]:{contentRevision:2,lastPercent:100}}));window.dispatchEvent(new StorageEvent('storage',{key:'sciverse_chapter_quiz_results'}));},topics);
 const select=p.locator('[data-bio4path-select]'),check=p.locator('[data-bio4path-check]'),reset=p.locator('[data-bio4path-reset]'),result=p.locator('[data-bio4path-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 let decisions=0;for(let i=0;i<8;i++){await select.selectOption(String(i));await check.click();assert.equal(await result.getAttribute('data-invalid'),'answer');assert.equal(await p.locator(`[data-bio4path-case="${i}"] input`).first().evaluate(e=>e===document.activeElement),true);for(let j=0;j<3;j++){await p.locator(`[data-bio4path-case="${i}"] input[value="${j}"]`).check();await check.click();assert.equal(await result.getAttribute('data-supported'),String(j===correct[i]));const feedback=await p.locator(`[data-bio4path-case="${i}"] input[value="${j}"]`).getAttribute('data-feedback');assert.ok((await result.textContent()).includes(feedback));assert.equal(await result.evaluate(e=>e===document.activeElement),true);decisions++;}}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(let i=0;i<8;i++){await select.selectOption(String(i));await p.locator(`[data-bio4path-case="${i}"] input[value="${correct[i]}"]`).check();await check.click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await p.locator(`[data-bio4path-case="${i}"]`).evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);layouts.push({dark,width,case:i});if(width===390&&[0,4,6].includes(i))await p.locator(`[data-bio4path-case="${i}"]`).screenshot({path:path.join(out,'case-'+i+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
  if(width===390)for(const[name,selector]of [['route','.bio4path-route'],['methods','.bio4path-method'],['next','.bio4path-next']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});
 }
 assert.equal(await p.locator('[data-bio4path-plan]').isVisible(),false);await reset.focus();await p.keyboard.press('Enter');assert.equal(await select.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Tab');assert.equal(await p.locator('[data-bio4path-case="0"] input[value="0"]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[data-bio4path-case="0"] input[value="1"]').isChecked(),true);await p.keyboard.press('Tab');assert.equal(await check.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.equal(await result.getAttribute('data-supported'),'true');
 await select.selectOption('1');await select.selectOption('0');assert.equal(await p.locator('[data-bio4path-case="0"] input[value="1"]').isChecked(),true);assert.equal(await result.getAttribute('data-supported'),'true');await p.locator('[data-bio4path-case="0"] input[value="2"]').check();assert.equal(await result.textContent(),'');assert.equal(await p.locator('li[data-bio4path-progress="0"]').getAttribute('data-state'),'unanswered');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const practice=p.locator('.practice-box[data-id="bio_4_kompetenzplan_extra_themenfrage"]');for(const option of await practice.locator('button').all()){await option.click();assert.ok((await practice.locator('.feedback').textContent()).includes(await option.getAttribute('data-feedback')));assert.equal(await option.isEnabled(),true);}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 console.log('24 diagnostic decisions, 48 layouts, keyboard, revisiting, invalidation and storage passed.');
 const links=await p.locator('.bio4path-route a').evaluateAll(nodes=>nodes.map(n=>n.href)),navigation=await b.newPage();let routes=0;
 for(const[i,url]of links.entries()){await navigation.goto(url);await navigation.waitForFunction(expected=>{const f=document.querySelector('#game-frame');return f?.contentWindow?.currentChapterQuiz?.topicId===expected&&!!f?.contentDocument?.querySelector('[data-core-navigation]');},topics[i]);const frame=navigation.frames().find(f=>f.parentFrame()&&new URL(f.url()).pathname.endsWith('/topics/template.html'));assert.ok(frame);assert.equal(new URL(frame.url()).searchParams.get('topic'),topics[i]);assert.equal(new URL(frame.url()).hash,'#learning-section-'+sections[i]);await frame.waitForFunction(section=>{const e=document.getElementById('learning-section-'+section);return e&&e.getBoundingClientRect().top>=-2&&e.getBoundingClientRect().top<100;},sections[i],{timeout:5000});routes++;}
 for(let i=0;i<8;i++){await select.selectOption(String(i));await p.locator(`[data-bio4path-case="${i}"] input[value="${i===3?0:correct[i]}"]`).check();await check.click();}
 const planURL=await p.locator('[data-bio4path-plan]').getAttribute('href');await navigation.goto(planURL);await navigation.waitForFunction(()=>document.querySelector('#game-frame')?.contentDocument?.querySelectorAll('#selected>li').length===1);const hub=navigation.frames().find(f=>f.parentFrame()&&new URL(f.url()).pathname.endsWith('/topics/learning.html'));assert.ok(hub);assert.deepEqual(await hub.evaluate(()=>JSON.parse(localStorage.getItem('sciverse_study_plan'))),[topics[3]]);assert.equal(await hub.locator('[data-mode="review"]').getAttribute('aria-pressed'),'true');await hub.locator('#share').click();assert.ok((await hub.locator('#share-url').inputValue()).includes(topics[3]));assert.doesNotMatch(await hub.locator('#share-url').inputValue(),/answer|lastPercent|bestPercent/);console.log('Eight real section jumps and one filtered study-list import/share passed.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,8);let answers=0;for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[id];assert.equal(r.lastPercent,right?100:88);assert.deepEqual(r.reviewQuestionIds,right?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.bio4path-paper-case').count(),8);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-bio4path-solution]').count(),3);assert.equal(await paper.locator('#ws-solutions .bio4path-case-solution').count(),8);await paper.pdf({path:path.join(out,'bio4-path-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,practiceAnswers:3,layouts,routes,filteredPlanImportAndShare:true,keyboard:true,storageUnchangedByDiagnostic:true,errors},null,2));console.log('PASS: 24 diagnostic and 24 graded answers, 3 practice answers, 48 layouts, eight actual section routes, study-list import/share, paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
