'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/city')),topic='bio_4_siedlungsraeume';
const keys={bio_4_stadt_s1:1,bio_4_stadt_d1:2,bio_4_stadt_s2:0,bio_4_stadt_messung:2,bio_4_stadt_d2:1,bio_4_stadt_speicher:1,bio_4_stadt_plan:0,bio_4_stadt_s3:2,bio_4_stadt_d3:1,bio_4_stadt_abfall:0};
const cases=[['A','10','20',0,4000],['A','10','5',0,4000],['A','30','20',0,12000],['A','30','5',0,12000],['A','50','20',0,20000],['A','50','5',0,20000],['B','10','20',1500,2500],['B','10','5',750,3250],['B','30','20',3000,9000],['B','30','5',750,11250],['B','50','20',3000,17000],['B','50','5',750,19250],['C','10','20',2500,1500],['C','10','5',1250,2750],['C','30','20',5000,7000],['C','30','5',1250,10750],['C','50','20',5000,15000],['C','50','5',1250,18750]];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-city-lab]')?.dataset.initialized==='true');
 const plan=p.locator('[data-city-plan]'),rain=p.locator('[data-city-rain]'),capacity=p.locator('[data-city-capacity]'),check=p.locator('[data-city-check]'),reset=p.locator('[data-city-reset]'),result=p.locator('[data-city-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 const fill=async(a,r,c)=>{await plan.selectOption(a);assert.equal(await result.textContent(),'');await rain.selectOption(r);await capacity.selectOption(c);await check.click();};
 const value=async key=>Number((await p.locator(`[data-city-value="${key}"]`).textContent()).replace(/[^\d]/g,''));
 for(const[a,r,c,held,runoff]of cases){await fill(a,r,c);assert.equal(await value('retained'),held);assert.equal(await value('runoff'),runoff);assert.equal(await value('total'),held+runoff);assert.equal(await result.evaluate(e=>e===document.activeElement),true);}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[a,r,c]of [cases[0],cases[5],cases[6],cases[9],cases[14],cases[17]]){await fill(a,r,c);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-city-lab] button,[data-city-lab] select').all())assert.ok((await el.boundingBox()).height>=44);layouts.push({dark,width,plan:a,rain:r,capacity:c});}
  for(const cell of await p.locator(':is(.city-habitats,.city-temperatures,.city-waste) tbody :is(th,td)').all())assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);
  for(const card of await p.locator('.city-card').all())assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');
  for(const text of await p.locator('.city-plans svg text').all())assert.ok((await text.boundingBox()).height>=12);
  if(width===390){await fill('B','30','5');for(const[name,selector]of [['habitats','.city-habitats'],['temperatures','.city-temperatures'],['plan-a','.city-plans figure:nth-child(1)'],['plan-b','.city-plans figure:nth-child(2)'],['plan-c','.city-plans figure:nth-child(3)'],['workshop','[data-city-lab]'],['waste','.city-waste']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await plan.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowDown');assert.equal(await plan.inputValue(),'B');await p.keyboard.press('Tab');await p.keyboard.press('ArrowDown');assert.equal(await rain.inputValue(),'30');await p.keyboard.press('Tab');await p.keyboard.press('ArrowDown');assert.equal(await capacity.inputValue(),'5');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await value('runoff'),11250);assert.equal(await result.evaluate(e=>e===document.activeElement),true);await plan.selectOption('C');assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),correct=choice===keys[id];assert.equal(r.lastPercent,correct?100:90);assert.deepEqual(r.reviewQuestionIds,correct?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-city-paper]').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),3);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('body').textContent()).includes('undefined'));await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-city-solution]').count(),4);await paper.pdf({path:path.join(out,'city-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),comparisons:18,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 18 native water balances, 36 layouts, keyboard/reset/focus/storage, 30 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
