const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/motor-learning');
const currents={fixed:[1,1,1,1,1,1,1,1],commutator:[1,1,0,-1,-1,-1,0,1]},directions={fixed:[1,1,0,-1,-1,-1,0,1],commutator:[1,1,0,1,1,1,0,1]};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];try{
 const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic=elektromagnetismus');await page.waitForFunction(()=>document.querySelector('[data-motor-lab]')?.dataset.bound==='true');const lab=page.locator('[data-motor-lab]'),angle=lab.locator('[data-motor-angle]'),mode=lab.locator('[data-motor-mode]'),polarity=lab.locator('[data-motor-polarity]'),power=lab.locator('[data-motor-power]'),initialStorage=await page.evaluate(()=>JSON.stringify(localStorage));let states=0,decisions=0;
 async function choice(el,index){await el.focus();await el.press('Home');if(index)await el.press('ArrowDown');}
 for(const m of ['commutator','fixed'])for(const p of ['normal','reverse'])for(const supply of ['on','off']){
  await choice(mode,m==='fixed'?1:0);await choice(polarity,p==='reverse'?1:0);await choice(power,supply==='off'?1:0);await angle.focus();await angle.press('Home');
  for(let i=0;i<8;i++){if(i){await angle.focus();await angle.press('ArrowRight');}assert.equal(await angle.inputValue(),String(i*45));const sign=p==='normal'?1:-1,current=supply==='off'?0:currents[m][i]*sign,expected=supply==='off'?0:directions[m][i]*sign;
   assert.ok(Number(await lab.locator('[data-motor-side=A]').getAttribute('data-current'))===current);assert.equal(await lab.locator('[data-motor-force]').count(),current===0?0:2);const geometry=await lab.locator('svg').evaluate(e=>({text:[...e.querySelectorAll('text')].map(t=>{const r=t.getBBox();return [r.x,r.y,r.x+r.width,r.y+r.height];}),all:[...e.querySelectorAll('[data-motor-side] circle,[data-motor-force]')].map(t=>{const r=t.getBBox();return [r.x,r.y,r.x+r.width,r.y+r.height];})}));assert.ok([...geometry.text,...geometry.all].every(r=>r[0]>=0&&r[1]>=0&&r[2]<=360&&r[3]<=280));
   for(const v of [-1,0,1]){const btn=lab.locator('[data-motor-verdict="'+v+'"]');await btn.focus();await btn.press('Enter');assert.equal((await lab.locator('[data-motor-feedback]').innerText()).startsWith('Richtig:'),v===expected);decisions++;}states++;
  }
 }
 await lab.locator('[data-motor-step="45"]').click();assert.equal(await angle.inputValue(),'0');await lab.locator('[data-motor-step="-45"]').click();assert.equal(await angle.inputValue(),'315');await page.evaluate(()=>initMotorLab());assert.equal(await angle.inputValue(),'315');await lab.locator('[data-motor-reset]').click();assert.deepEqual(await Promise.all([angle,mode,polarity,power].map(e=>e.inputValue())),['0','commutator','normal','on']);assert.equal(await angle.evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>JSON.stringify(localStorage)),initialStorage);
 const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('.em-motor-lab h3')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
  for(const degrees of [0,90,135,270]){await angle.focus();await angle.press('Home');for(let n=0;n<degrees/45;n++)await angle.press('ArrowRight');const r=await lab.evaluate(e=>({overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('input,button,select')].map(x=>{const r=x.getBoundingClientRect();return [r.left,r.right,r.height];}),statusFont:parseFloat(getComputedStyle(e.querySelector('[data-motor-status]')).fontSize)}));assert.ok(!r.overflow);assert.ok(r.controls.every(c=>c[0]>=0&&c[1]<=width+1&&c[2]>=44));assert.ok(r.statusFont>=16);layouts.push({width,theme,degrees});if(width===390&&(degrees===0||degrees===90||degrees===135)){await lab.locator('[data-motor-plot]').screenshot({path:path.join(out,'plot-'+degrees+'-'+theme+'.png')});if(degrees===135)await lab.screenshot({path:path.join(out,'lab-'+theme+'.png')});}}
 }
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic=elektromagnetismus');await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-motor-paper] tbody tr').count(),8);assert.equal(await paper.locator('[data-motor-static] svg').count(),2);assert.equal(await paper.locator('[data-motor-tasks]>li').count(),4);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('#ws-physics-material').innerText()).includes('Tabellenreihenfolge'));await paper.locator('#ws-include-solutions').check();assert.ok((await paper.locator('#ws-solutions').innerText()).includes('Tabellenreihenfolge'));await paper.pdf({path:path.join(out,'motor-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);assert.equal(states,64);assert.equal(decisions,192);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),states,decisions,layouts,errors,scope:'Momentary motor current/forces/torque directions, native controls and paper; no mechanical time integration or practical experiment.'},null,2)+'\n');console.log('PASS: native motor: 64 states, 192 classifications, keyboard/reset/wrap, SVG bounds, 24 layouts and separated paper solutions.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
