'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/regulation')),topic='bio_4_nerven_hormone';
const keys={bio_4_steuerung_s1:1,bio_4_steuerung_d1:2,bio_4_steuerung_synapse:0,bio_4_steuerung_s2:2,bio_4_steuerung_d4:1,bio_4_steuerung_d2:0,bio_4_steuerung_feedback:1,bio_4_steuerung_modell:2,bio_4_steuerung_s3:0,bio_4_steuerung_d3:2,bio_4_steuerung_daten:1};
const cases=[['40','-10',[40,30,35,40,45,50],[40,30,30,30,30,30]],['40','0',[40,40,45,50,50,50],[40,40,40,40,40,40]],['40','10',[40,50,50,50,50,50],[40,50,50,50,50,50]],['50','-10',[50,40,45,50,50,50],[50,40,40,40,40,40]],['50','0',[50,50,50,50,50,50],[50,50,50,50,50,50]],['50','10',[50,60,55,50,50,50],[50,60,60,60,60,60]],['60','-10',[60,50,50,50,50,50],[60,50,50,50,50,50]],['60','0',[60,60,55,50,50,50],[60,60,60,60,60,60]],['60','10',[60,70,65,60,55,50],[60,70,70,70,70,70]]];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-regulation-lab]')?.dataset.initialized==='true');
 const start=p.locator('[data-regulation-start]'),change=p.locator('[data-regulation-change]'),mode=p.locator('[data-regulation-mode]'),check=p.locator('[data-regulation-check]'),reset=p.locator('[data-regulation-reset]'),result=p.locator('[data-regulation-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 const fill=async(a,c,m)=>{await start.selectOption(a);assert.equal(await result.textContent(),'');await change.selectOption(c);await mode.selectOption(m);await check.click();};
 for(const[a,c,on,off]of cases)for(const m of ['on','off']){await fill(a,c,m);const expected=m==='on'?on:off;assert.deepEqual(await p.locator('[data-regulation-value]').evaluateAll(es=>es.map(e=>Number(e.dataset.regulationValue))),expected);const points=await p.locator('[data-regulation-line]').getAttribute('points');assert.deepEqual(points.split(' ').map(s=>(218-Number(s.split(',')[1]))/2),expected);assert.equal(await result.evaluate(e=>e===document.activeElement),true);}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[a,c,m]of [['40','-10','on'],['60','10','on'],['60','10','off'],['50','0','on']]){await fill(a,c,m);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-regulation-lab] button,[data-regulation-lab] select').all())assert.ok((await el.boundingBox()).height>=44);for(const text of await p.locator('.regulation-map text,.regulation-chart text').all())assert.ok(await text.evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('svg').getBoundingClientRect();return r.height>=12&&r.left>=s.left-1&&r.right<=s.right+1&&r.top>=s.top-1&&r.bottom<=s.bottom+1;}),'SVG label readable within bounds');
   for(const cell of await p.locator(':is(.regulation-rules,.regulation-targets,.regulation-comparison,.regulation-data,.regulation-results) :is(th,td)').all()){if(await cell.evaluate(e=>e.closest('thead')&&getComputedStyle(e.closest('thead')).position==='absolute'))continue;assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);}
   assert.ok(await p.locator('.regulation-results caption').evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=e.parentElement.getBoundingClientRect().width*.95&&r.height<=parseFloat(getComputedStyle(e).lineHeight)*7;}));layouts.push({dark,width,start:a,change:c,mode:m});
  }
  for(const card of await p.locator('.regulation-card').all())assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');
  if(width===390){await fill('60','10','on');for(const[name,selector]of [['map','.regulation-map'],['targets','.regulation-targets'],['comparison','.regulation-comparison'],['rules','.regulation-rules'],['data','.regulation-data'],['chart','.regulation-chart'],['results','.regulation-results'],['workshop','[data-regulation-lab]']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await start.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Home');assert.equal(await start.inputValue(),'40');await p.keyboard.press('Tab');await p.keyboard.press('Home');assert.equal(await change.inputValue(),'-10');await p.keyboard.press('Tab');await p.keyboard.press('Home');assert.equal(await mode.inputValue(),'on');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.deepEqual(await p.locator('[data-regulation-value]').evaluateAll(es=>es.map(e=>Number(e.dataset.regulationValue))),[40,30,35,40,45,50]);assert.equal(await result.evaluate(e=>e===document.activeElement),true);await start.selectOption('50');assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const practice=p.locator('.practice-box[data-id="bio_4_nerven_extra_stress"]');for(const option of await practice.locator('button').all()){await option.click();assert.ok((await practice.locator('.feedback').textContent()).includes(await option.getAttribute('data-feedback')));assert.equal(await option.isEnabled(),true);}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,11);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),correct=choice===keys[id];assert.equal(r.lastPercent,correct?100:91);assert.deepEqual(r.reviewQuestionIds,correct?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.ok((await paper.locator('body').textContent()).includes('Papierwerkstatt: Gegenregelung.'));assert.equal(await paper.locator('svg[data-worksheet-static]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('body').textContent()).includes('undefined'));await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-regulation-solution]').count(),4);await paper.pdf({path:path.join(out,'regulation-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),states:18,answers,practiceAnswers:3,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 18 native feedback trajectories, 24 layouts, keyboard/reset/focus/storage, 33 quiz and 3 practice answers, paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
