'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/microbe-kitchen')),topic='bio_2_mikroorganismen';
const keys={bio_2_mikroorganismen_s1:1,bio_2_mikroorganismen_d1:2,bio_2_mikroorganismen_d2:0,bio_2_mikroorganismen_s2:2,bio_2_microbe_samples:0,bio_2_mikroorganismen_s3:1,bio_2_mikroorganismen_d5:2,bio_2_mikroorganismen_s4:0,bio_2_mikroorganismen_d3:1,bio_2_mikroorganismen_d4:2,bio_2_microbe_late:1,bio_2_mikroorganismen_s5:1};
const paths={'000':[],'100':['touch'],'110':['cut'],'010':['cut','hands'],'111':['cut','salad'],'011':['cut','salad','hands'],'101':['cut','salad','tools'],'001':['cut','salad','hands','tools']};
const expected={touch:['100','101','110','111','100','101','110','111'],cut:['110','111','110','111','110','111','110','111'],hands:['000','001','010','011','000','001','010','011'],tools:['000','001','000','001','100','101','100','101'],salad:['000','111','111','111','111','111','111','111']};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:1280,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-kitchen-trace]')?.dataset.initialized==='true');const store=await p.evaluate(()=>JSON.stringify(localStorage)),reset=p.locator('[data-microbe-reset]'),status=p.locator('[data-microbe-status]'),state=()=>p.locator('[data-kitchen-trace]').evaluate(zone=>['hands','tools','salad'].map(id=>zone.querySelector(`[data-microbe-station="${id}"]`).dataset.marked==='true'?'1':'0').join('')),act=async id=>p.locator(`[data-microbe-action="${id}"]`).click();let transitions=0;
 for(const [before,sequence]of Object.entries(paths))for(const action of Object.keys(expected)){await reset.click();for(const a of sequence)await act(a);assert.equal(await state(),before);await act(action);assert.equal(await state(),expected[action][parseInt(before,2)]);assert.ok((await status.textContent()).startsWith('Schritt '+(sequence.length+1)+':'));transitions++;}
 for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:1000});await p.evaluate(dark=>{if(dark)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);for(const [before,sequence]of Object.entries(paths)){await reset.click();for(const a of sequence)await act(a);assert.equal(await state(),before);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const control of await p.locator('[data-kitchen-trace] button').all())assert.ok((await control.boundingBox()).height>=44);layouts.push({dark,width,state:before});}if(width===390){await reset.click();for(const a of ['cut','salad','hands','tools'])await act(a);await p.locator('[data-kitchen-trace]').screenshot({path:path.join(out,'kitchen-'+(dark?'dark':'light')+'.png')});await p.locator('.microbe-data').first().screenshot({path:path.join(out,'comparison-'+(dark?'dark':'light')+'.png')});}}
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await state(),'000');assert.equal(await p.locator('[data-microbe-action="touch"]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.equal(await state(),'100');await p.keyboard.press('Tab');assert.equal(await p.locator('[data-microbe-action="cut"]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Space');assert.equal(await state(),'110');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),store);
 let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(result.lastPercent,choice===keys[id]?100:92);assert.deepEqual(result.reviewQuestionIds,choice===keys[id]?[]:[id]);answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-microbe-paper] tbody tr').count(),6);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-microbe-solution]').count(),5);await paper.pdf({path:path.join(out,'microbes-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),answers,transitions,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 40 native transitions, 48 layout states, keyboard/reset/focus/storage, 36 native quiz answers and full paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
