const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/production-media')),topic='dgb5_produktion',keys=require('./fixtures/dgb5_production_keys.json'),chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic];
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let views=0,loopRuns=0,loopSteps=0,surveyCases=0,answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-production-views]')?.dataset.bound==='1');const stored=await p.evaluate(()=>JSON.stringify(localStorage));await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  const media=p.locator('[data-production-views]');
  for(const value of ['text','table','chart']){await media.locator('select').selectOption(value);assert.equal(await media.locator('[data-production-view]:visible').count(),1);assert.equal(await media.locator(`[data-production-view="${value}"]`).isVisible(),true);assert.match(await media.locator('[role=status]').innerText(),/acht erfundene Antworten, Lesen 3, Radfahren 4, Ballspiel 1/);assert.match(await media.locator('[data-production-view]:visible').innerText(),/Keine Aussage über alle Kinder in Wien/);views++;}
  const bars=await media.locator('[data-chart-value]').evaluateAll(es=>es.map(e=>({value:e.dataset.chartValue,fill:e.querySelector('.production-bar-fill').getBoundingClientRect().width,track:e.querySelector('.production-bar-track').clientWidth})));
  for(const [i,ratio]of [.75,1,.25].entries())assert.ok(Math.abs(bars[i].fill/bars[i].track-ratio)<.01,JSON.stringify(bars));
  assert.deepEqual(await media.locator('.production-chart-scale span').allTextContents(),['0','1','2','3','4']);
  if(width===320||width===1280){await media.scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,`chart-${width}-${dark?'dark':'light'}.png`),animations:'disabled'});}
  await media.locator('select').selectOption('table');assert.deepEqual(await media.locator('[data-media-counts] tbody tr').evaluateAll(es=>es.map(e=>[e.cells[0].textContent,e.cells[1].textContent])),[['Lesen','3'],['Radfahren','4'],['Ballspiel','1']]);
  assert.deepEqual(await media.locator('[data-media-counts] caption,[data-media-counts] th,[data-media-counts] td').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.textContent)),[]);
  await media.locator('[data-production-view-reset]').focus();await p.keyboard.press('Enter');assert.equal(await media.locator('select').inputValue(),'text');assert.equal(await media.locator('select').evaluate(e=>e===document.activeElement),true);
  const loop=p.locator('[data-simple-loop]');for(let n=0;n<=6;n++){await loop.locator('select').selectOption(String(n));assert.equal(await loop.locator('[data-loop-dots]').textContent(),'');for(let step=1;step<=n+1;step++){await loop.locator('[data-loop-step]').focus();await p.keyboard.press('Enter');assert.equal(((await loop.locator('[data-loop-dots]').textContent()).match(/●/g)||[]).length,step<=n?2*step:2*n+1);loopSteps++;}assert.equal(await loop.locator('[data-loop-step]').isDisabled(),true);assert.equal(await loop.locator('[data-loop-reset]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.equal(await loop.locator('[data-loop-dots]').textContent(),'');loopRuns++;}
  const survey=p.locator('[data-survey-check]'),inputs=survey.locator('input');for(const [values,expected]of [[['3','4','1'],/^Richtig:/],[['4','3','1'],/Summe ist 8, aber die Zuordnung/],[['3','4','0'],/Summe ist 7/],[['','4','1'],/Fülle jede Kategorie/],[['x','4','1'],/Fülle jede Kategorie/]]){for(let i=0;i<3;i++)await inputs.nth(i).fill(values[i]);assert.match(await survey.locator('[data-survey-status]').innerText(),/erneut/);await inputs.nth(2).press('Enter');assert.match(await survey.locator('[data-survey-status]').innerText(),expected);if(values[0]===''||values[0]==='x')assert.equal(await inputs.nth(0).getAttribute('aria-invalid'),'true');surveyCases++;}
  await survey.locator('[data-survey-reset]').click();assert.equal(await inputs.nth(0).evaluate(e=>e===document.activeElement),true);assert.deepEqual(await inputs.evaluateAll(es=>es.map(e=>e.value)),['','','']);
  for(const selector of ['[data-survey-records]','[data-survey-check] table','[data-media-observation]','[data-presentation-protocol]']){const table=p.locator(selector);assert.equal(await table.getAttribute('role'),'table');assert.deepEqual(await table.locator('caption,tbody th,tbody td').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.textContent)),[]);assert.ok(await table.locator('caption').evaluate(e=>e.getBoundingClientRect().width>100));}
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  if(width===320||width===1280)for(const [name,selector]of [['survey','[data-survey-check]'],['observation','[data-media-observation]'],['slides','[data-slide-plan]'],['protocol','[data-presentation-protocol]']]){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.screenshot({path:path.join(out,`${name}-${width}-${dark?'dark':'light'}.png`),animations:'disabled'});}
 }
 for(const [j,q]of chapter.sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).entries()){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [i,a]of q.answers.entries()){const b=box.getByRole('button',{name:a.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),i===[2,2,1][j]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));practiceAnswers++;}}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(ids,Object.keys(keys));
 for(const [n,id]of ids.entries())for(let a=0;a<3;a++){if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(result.lastPercent,a===keys[id]?100:89);assert.equal(result.contentRevision,4);assert.deepEqual(result.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;}
 await p.goto(base+'/topics/worksheet.html?topic='+topic);await p.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await p.locator('#ws-solutions').isVisible(),false);assert.equal(await p.locator('[data-media-paper] .production-medium').count(),3);assert.equal(await p.locator('[data-presentation-protocol] tbody tr').count(),5);assert.equal(await p.locator('#ws-solutions .ws-paper-solution').count(),5);assert.equal(await p.locator('#ws-content>.question-block').count(),9);await p.locator('#ws-include-solutions').check();for(const mode of ['screen','print']){await p.emulateMedia({media:mode});const ratios=await p.locator('[data-media-paper] [data-chart-value]').evaluateAll(es=>es.map(e=>e.querySelector('.production-bar-fill').getBoundingClientRect().width/e.querySelector('.production-bar-track').clientWidth));for(const [i,expected]of [.75,1,.25].entries())assert.ok(Math.abs(ratios[i]-expected)<.01,mode+': '+ratios);}await p.pdf({path:path.join(out,'dgb5_produktion-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(views,18);assert.equal(loopRuns,42);assert.equal(loopSteps,168);assert.equal(surveyCases,30);assert.equal(answers,27);assert.equal(practiceAnswers,9);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),views,loopRuns,loopSteps,surveyCases,answers,practiceAnswers,layouts:6,keyboardAndFocus:true,workshopStorageUnchanged:true,tableCellsWithinViewport:true,errors},null,2));console.log('PASS: 18 media views, 42 complete loop runs with 168 steps, 30 survey cases, 27 quiz answers, nine practice answers, six layouts, keyboard/focus, unchanged practice storage and chapter PDF.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
