'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/immunity')),topic='bio_4_immunsystem_resistenzen';
const keys={bio_4_immun_s1:1,bio_4_immun_d1:2,bio_4_immun_s2:0,bio_4_immun_d2:1,bio_4_immun_daten:2,bio_4_immun_s3:1,bio_4_immun_d3:0,bio_4_immun_anteil:2,bio_4_immun_entstehung:1,bio_4_immun_null:0,bio_4_immun_handeln:2};
const cases=[['0','N',100,0,'0 %'],['0','S',10,0,'0 %'],['0','V',0,0,'Nicht bestimmbar (keine Bakterien)'],['10','N',90,10,'10 %'],['10','S',9,10,'52,6 %'],['10','V',0,10,'100 %'],['40','N',60,40,'40 %'],['40','S',6,40,'87,0 %'],['40','V',0,40,'100 %']];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-immunity-lab]')?.dataset.initialized==='true');
 const start=p.locator('[data-immunity-start]'),rule=p.locator('[data-immunity-rule]'),rounds=p.locator('[data-immunity-rounds]'),check=p.locator('[data-immunity-check]'),reset=p.locator('[data-immunity-reset]'),result=p.locator('[data-immunity-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 const fill=async(a,s,n)=>{await start.selectOption(a);assert.equal(await result.textContent(),'');await rule.selectOption(s);await rounds.selectOption(String(n));await check.click();};
 for(const[a,s,e,r,share]of cases)for(const n of [0,1,2]){await fill(a,s,n);const rows=await p.locator('.immunity-results tbody tr').evaluateAll(es=>es.map(e=>[...e.children].map(c=>c.textContent)));assert.equal(rows.length,n+2);assert.deepEqual(rows[0],['Anfang',String(100-Number(a)),a,'100',a+' %']);for(let i=1;i<rows.length;i++){const factor=[1,2,4][i-1];assert.deepEqual(rows[i],[i===1?'Direkt nach Auswahl':'Teilungsrunde '+(i-1),String(e*factor),String(r*factor),String((e+r)*factor),share]);}assert.equal(await result.evaluate(e=>e===document.activeElement),true);}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[a,s,n]of [['0','V',2],['10','S',2],['10','V',1],['40','N',2]]){await fill(a,s,n);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-immunity-lab] button,[data-immunity-lab] select').all())assert.ok((await el.boundingBox()).height>=44);for(const text of await p.locator('.immunity-map text').all())assert.ok(await text.evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('svg').getBoundingClientRect();return r.height>=12&&r.left>=s.left-1&&r.right<=s.right+1;}));
   for(const cell of await p.locator(':is(.immunity-rules,.immunity-evidence,.immunity-actions,.immunity-results) :is(th,td)').all()){if(await cell.evaluate(e=>e.closest('thead')&&getComputedStyle(e.closest('thead')).position==='absolute'))continue;assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);}
   assert.ok(await p.locator('.immunity-results caption').evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=e.parentElement.getBoundingClientRect().width*.95&&r.height<=parseFloat(getComputedStyle(e).lineHeight)*7;}));layouts.push({dark,width,start:a,rule:s,rounds:n});
  }
  for(const card of await p.locator('.immunity-card').all())assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');
  if(width===390){await fill('10','S',2);for(const[name,selector]of [['map','.immunity-map'],['rules','.immunity-rules'],['evidence','.immunity-evidence'],['actions','.immunity-actions'],['workshop','[data-immunity-lab]']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});await fill('0','V',2);await result.screenshot({path:path.join(out,'empty-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await start.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Home');assert.equal(await start.inputValue(),'0');await p.keyboard.press('Tab');await p.keyboard.press('End');assert.equal(await rule.inputValue(),'V');await p.keyboard.press('Tab');await p.keyboard.press('End');assert.equal(await rounds.inputValue(),'2');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.ok((await result.textContent()).includes('Population leer'));assert.equal(await result.evaluate(e=>e===document.activeElement),true);await start.selectOption('40');assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const practice=p.locator('.practice-box[data-id="bio_4_immunsystem_extra_resistenz"]');for(const option of await practice.locator('button').all()){await option.click();assert.ok((await practice.locator('.feedback').textContent()).includes(await option.getAttribute('data-feedback')));assert.equal(await option.isEnabled(),true);}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,11);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),correct=choice===keys[id];assert.equal(r.lastPercent,correct?100:91);assert.deepEqual(r.reviewQuestionIds,correct?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.ok((await paper.locator('body').textContent()).includes('Papierwerkstatt: Auswahl und Vermehrung'));assert.equal(await paper.locator('svg[data-worksheet-static]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('body').textContent()).includes('undefined'));await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-immunity-solution]').count(),4);await paper.pdf({path:path.join(out,'immunity-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),states:27,answers,practiceAnswers:3,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 27 native selection/division states, 24 layouts, keyboard/reset/focus/storage, 33 quiz and 3 practice answers, paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
