const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/reproduction-learning')),id='bio_2_pflanzenvermehrung',source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const correct=Object.fromEntries(['s1','s2','s3','s4','s5','d1','d2','d3','d4','d5','extra_vergleich'].map(k=>['bio_2_pflanzenvermehrung_'+k,0]));Object.assign(correct,{bio_vermehrung_einzelbluete:2,bio_vermehrung_tageszahlen:1});
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===12&&document.querySelectorAll('[data-reproduction-item]').length===5);assert.equal(await page.locator('.bio-training-card').count(),15);
  let paths=0;for(const q of source.sections.flatMap(s=>s.quizzes))for(const [i,answer]of q.answers.entries()){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:answer.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===correct[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==correct[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));paths++;
  }
  assert.equal(paths,39);const saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),flower=page.locator('[data-flower-organization]'),kind=flower.locator('select'),timeline=page.locator('[data-germination-timeline]'),day=timeline.locator('select'),counts=[0,2,6,7,8];
  for(const [i,key]of ['both','mono','dio'].entries()){await kind.focus();await page.keyboard.press('Home');for(let n=0;n<i;n++)await page.keyboard.press('ArrowDown');assert.equal(await kind.inputValue(),key);assert.equal(await flower.locator('[data-flower-view]:visible').count(),1);assert.equal(await flower.locator('[data-flower-view="'+key+'"] [data-layout-plant]').count(),key==='dio'?2:1);}
  for(let i=0;i<5;i++){await day.focus();await page.keyboard.press('Home');for(let n=0;n<i;n++)await page.keyboard.press('ArrowDown');assert.equal(await day.inputValue(),String(i));assert.ok((await timeline.locator('[role=status]').innerText()).includes('B '+counts[i]+' von 10 = '+counts[i]*10+' %'));if(i)assert.ok((await timeline.locator('[role=status]').innerText()).includes('B '+(counts[i]-counts[i-1])+' Samen'));}
  const terms=['pollination','fertilization','development','dispersal','germination'],selects=page.locator('[data-reproduction-item]'),check=page.locator('[data-reproduction-check]');await check.click();assert.match(await page.locator('[data-reproduction-status]').innerText(),/5 noch nicht/);let assignments=0;
  for(let i=0;i<5;i++)for(let choice=0;choice<5;choice++){
   for(let j=0;j<5;j++)if(i!==j)await selects.nth(j).selectOption(terms[j]);await selects.nth(i).focus();await page.keyboard.press('Home');for(let n=0;n<=choice;n++)await page.keyboard.press('ArrowDown');assert.equal(await selects.nth(i).inputValue(),terms[choice]);await check.focus();await page.keyboard.press('Enter');assert.equal(await selects.nth(i).getAttribute('aria-invalid'),String(choice!==i));assert.match(await page.locator('[data-reproduction-status]').innerText(),new RegExp((choice===i?5:4)+' von 5'));assignments++;
  }
  for(const [zone,control,value]of [[flower,kind,'both'],[timeline,day,'0']]){await zone.locator('button').click();assert.equal(await control.inputValue(),value);assert.equal(await control.evaluate(e=>e===document.activeElement),true);}await page.locator('[data-reproduction-reset]').click();assert.equal(await selects.first().evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('[data-flower-organization] p')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   const states=[...['both','mono','dio'].map(value=>({zone:flower,control:kind,value,svg:'[data-flower-view]:visible svg',height:280})),...[0,1,2,3,4].map(i=>({zone:timeline,control:day,value:String(i),svg:'svg',height:290}))];
   for(const state of states){await state.control.selectOption(state.value);const geometry=await state.zone.locator(state.svg).evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,labels:[...e.querySelectorAll('text')].map(t=>{const b=t.getBBox();return {x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow);assert.ok(geometry.labels.every(b=>b.x>=0&&b.right<=360&&b.y>=0&&b.bottom<=state.height));layouts.push({width,theme,value:state.value,geometry});if(width===390&&['mono','dio','2','4'].includes(state.value))await state.zone.screenshot({path:path.join(out,'state-'+state.value+'-'+theme+'.png')});}
  }
  await page.setViewportSize({width:390,height:844});const tables=[];for(const selector of ['[data-germination-data]','[data-germination-protocol]']){
   await page.waitForFunction(selector=>{const table=document.querySelector(selector),parent=table.parentElement;return parent.classList.contains('responsive-table')&&(parent.scrollWidth<=parent.clientWidth+1||parent.getAttribute('role')==='region');},selector);const table=page.locator(selector),parent=table.locator('..'),scrollable=await parent.getAttribute('role')==='region';if(scrollable){assert.equal(await parent.getAttribute('tabindex'),'0');await parent.focus();for(let i=0;i<100&&await parent.evaluate(e=>e.scrollLeft<e.scrollWidth-e.clientWidth-1);i++){await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);}assert.ok(await parent.evaluate(e=>e.scrollLeft>=e.scrollWidth-e.clientWidth-1));}else{const b=await table.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=391);}tables.push({selector,scrollable});
  }
  const attempts=[];for(const [wrong,section]of [['bio_vermehrung_einzelbluete',0],['bio_vermehrung_tageszahlen',4]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(correct[q]+1)%3:correct[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,92);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),12);assert.equal(await paper.locator('#ws-biology-material .bio-training-card').count(),15);assert.equal(await paper.locator('[data-germination-protocol] tbody tr').count(),6);assert.equal(await paper.locator('[data-reproduction-paper] li').count(),5);assert.equal(await paper.locator('#ws-biology-material svg').count(),4);assert.equal(await paper.locator('#ws-biology-material select,#ws-biology-material button').count(),0);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.match(await paper.locator('#ws-solutions').innerText(),/0 \+ 2 \+ 6 \+ 7 \+ 8 = 23/);await paper.pdf({format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'},path:path.join(out,'reproduction-solutions.pdf')});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({generatedAt:new Date().toISOString(),base,browser:browser.version(),paths,assignments,layouts,tables,attempts,pageErrors:errors,scope:'39 native quiz choices, 25 keyboard classifications, three flower distributions and five daily states, reset/focus/storage, 48 layout states, two tables, two 92% checks and paper with four diagrams and separate solutions. Visual inspection separate; no real growing experiment or whole-site acceptance.'},null,2)+'\n');console.log('PASS: reproduction native: 39 quiz choices, 25 keyboard classifications, three flower/five daily states, 48 layouts, two tables, two 92% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
