const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/assistance-cases'));
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[],layouts=[];let decisions=0;try{const p=await browser.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic=dgb8_orientierung');await p.locator('[data-assistance-lab="health"]').waitFor();const stored=await p.evaluate(()=>JSON.stringify(localStorage));
 for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});await p.evaluate(dark=>{if(dark)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  const table=p.locator('[data-assistance-reference]');assert.equal(await table.evaluate(e=>e.scrollWidth<=e.parentElement.clientWidth+1),true);if(width<400)await table.screenshot({path:path.join(out,'table-'+width+'-'+(dark?'dark':'light')+'.png')});
  for(const [id,keys]of Object.entries({mobility:[1,0,2],health:[2,0,1]})){const zone=p.locator('[data-assistance-lab="'+id+'"]'),control=zone.locator('select'),result=zone.locator('[role="status"]');for(let c=0;c<3;c++){await control.selectOption(String(c));const card=zone.locator('[data-boundary-case]').nth(c);assert.equal(await card.isVisible(),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);const rect=await card.boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=width+1);for(let choice=0;choice<3;choice++){const b=card.locator('button').nth(choice);assert.ok((await b.boundingBox()).height>=44);await b.focus();await p.keyboard.press('Enter');assert.equal((await result.textContent()).startsWith('Richtig:'),choice===keys[c]);decisions++;}layouts.push({dark,width,lab:id,case:c});if(width===390&&c===2)await zone.screenshot({path:path.join(out,id+'-'+(dark?'dark':'light')+'.png')});}
  await zone.locator('[data-boundary-reset]').focus();await p.keyboard.press('Enter');assert.equal(await control.inputValue(),'0');assert.equal(await control.evaluate(e=>e===document.activeElement),true);assert.match(await result.textContent(),/Lies den Fall/);}
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),decisions,layouts,storageUnchanged:true,errors},null,2)+'\n');console.log('PASS: '+decisions+' native keyboard decisions across '+layouts.length+' layouts, focus/reset, no page overflow and unchanged storage.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
