const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/media-context')),topic='dgb8_kommunikation';
const keys={dgb8_kommunikation_q1:1,dgb8_http_status:2,dgb8_kommunikation_q2:0,dgb8_media_context:2,dgb8_kommunikation_q3:1,dgb8_kommunikation_q4:0,dgb8_media_business:2,dgb8_media_viral:1};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[],layouts=[];try{const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+topic);await page.locator('[data-crop-status]').waitFor();const view=page.locator('[data-crop-view]'),caption=page.locator('[data-crop-caption]'),pic=page.locator('[data-crop-image]'),status=page.locator('[data-crop-status]'),stored=await page.evaluate(()=>JSON.stringify(localStorage)),original=await pic.locator('[data-vote]').evaluateAll(nodes=>nodes.map(e=>e.outerHTML).join(''));
 for(const dark of [false,true])for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});await page.evaluate(value=>{if(value)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await page.waitForFunction(value=>getComputedStyle(document.body).color===(value?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);assert.equal(await page.locator('.crop-workshop label').first().evaluate(e=>getComputedStyle(e).color===getComputedStyle(document.body).color),true);
  for(const v of ['full','yes'])for(const c of ['careful','all']){await view.selectOption(v);await caption.selectOption(c);assert.equal(await pic.getAttribute('viewBox'),v==='full'?'0 0 420 320':'0 0 140 320');assert.equal(await pic.locator('[data-crop-clip]').getAttribute('width'),v==='full'?'420':'140');assert.equal(await pic.locator('[data-vote]').evaluateAll(nodes=>nodes.map(e=>e.outerHTML).join('')),original);assert.match(await status.textContent(),v==='full'?/Gesamtbild: 4 von 12/:/Ausschnitt: 4 von 4/);assert.equal((await status.textContent()).includes('Die Überschrift ist falsch'),c==='all');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const element of [view,caption,page.locator('[data-crop-reset]')])assert.ok((await element.boundingBox()).height>=44);layouts.push({dark,width,view:v,caption:c});if(width===390&&c==='all')await page.locator('.crop-workshop').screenshot({path:path.join(out,'crop-'+v+'-'+(dark?'dark':'light')+'.png')});}
 }
 await page.locator('[data-crop-reset]').focus();await page.keyboard.press('Enter');assert.equal(await view.inputValue(),'full');assert.equal(await caption.inputValue(),'careful');assert.equal(await view.evaluate(e=>e===document.activeElement),true);await page.keyboard.press('ArrowDown');assert.equal(await view.inputValue(),'yes');assert.match(await status.textContent(),/Ausschnitt: 4 von 4/);assert.equal(await page.evaluate(()=>JSON.stringify(localStorage)),stored);
 const qs=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,8);let answers=0;for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){if(!answers)await page.locator('#chapter-quiz-launch').click();else await page.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await page.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await page.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await page.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await page.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:88);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);answers++;}
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-crop-paper] svg').count(),2);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-media-solution]').count(),4);await paper.pdf({path:path.join(out,'media-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),answers,layouts,reset:true,storageUnchanged:true,errors},null,2));console.log('PASS: 24 native crop/caption/layout states, keyboard/reset/focus/storage, 24 assessed answers and two-view worksheet export.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
