const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/learning-progress'));
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const p=await browser.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/learning.html');await p.waitForFunction(()=>document.querySelectorAll('.chapter').length>0);
  await p.evaluate(()=>{localStorage.setItem('physik_score','0');localStorage.setItem('sciverse_chapter_quiz_results',JSON.stringify({farben:{attemptsUsed:3,availableAttempts:0,lockUntil:Date.now()+86400000,nextRefillAt:Date.now()+86400000,lastPercent:0,bestPercent:0}}));});
  await p.goto(base+'/topics/template.html?topic=farben');await p.waitForFunction(()=>window.currentChapterQuiz?.questions.length>0);await p.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();const snapshots=[];
  for(let attempt=0;attempt<7;attempt++){
   if(attempt)await p.getByRole('button',{name:'Neuen Versuch starten',exact:true}).click();const correct=attempt===5;
   await p.evaluate(correct=>currentChapterQuiz.questions.forEach((q,i)=>{const a=q.answers.findIndex(a=>Boolean(a.correct)===correct);document.querySelector('input[name="chapter_q_'+i+'"][value="'+a+'"]').checked=true;}),correct);
   await p.locator('.chapter-submit-btn').click();const r=await p.evaluate(()=>({result:JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results')).farben,points:Number(localStorage.getItem('physik_score')||0),count:currentChapterQuiz.questions.length}));
   assert.equal(r.result.lastPercent,correct?100:0);assert.equal(r.result.totalAttempts,attempt+1);assert.equal(r.result.lockUntil,0);assert.equal(r.result.nextRefillAt,0);assert.equal(r.result.reviewQuestionIds.length,correct?0:r.count);assert.equal(await p.getByRole('button',{name:'Neuen Versuch starten',exact:true}).isEnabled(),true);if(attempt<5)assert.equal(r.points,0);snapshots.push(r);
  }
  assert.equal(snapshots[6].result.bestPercent,100);assert.equal(snapshots[6].result.lastPercent,0);assert.equal(snapshots[6].points,snapshots[5].points,'An unsuccessful retry costs no points');
  const repeat=p.getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).first();const handler=await repeat.getAttribute('onclick');const match=/reviewChapterSection\((\d+)\)/.exec(handler);assert.ok(match);await repeat.click();assert.equal(await p.locator('#learning-section-'+match[1]+' h2').evaluate(e=>e===document.activeElement),true);
  await p.goto(base+'/topics/learning.html');await p.waitForFunction(()=>document.querySelector('[data-focus-key="catalog-toggle-farben"]'));const card=p.locator('.chapter').filter({has:p.locator('[data-focus-key="catalog-toggle-farben"]')});assert.match(await card.innerText(),/Letzter Kapitelcheck: 0 % · noch üben/);await card.locator('[data-focus-key="catalog-toggle-farben"]').click();assert.match(await p.locator('#selected').innerText(),/Letzter Kapitelcheck: 0 % · noch üben/);
  await p.locator('#storage-heading').click();assert.equal(await p.locator('#storage-explanation').isVisible(),true);assert.match(await p.locator('#storage-explanation').innerText(),/in diesem Browser auf diesem Gerät/);assert.match(await p.locator('#storage-explanation').innerText(),/keine Schulnote/);await p.locator('#storage-explanation').screenshot({path:path.join(out,'storage-explanation.png')});
  await card.screenshot({path:path.join(out,'latest-result.png')});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),snapshots,errors},null,2)+'\n');console.log('PASS: zero-point access with old saved lock, five failed retries, success then failure, unchanged points on retries, latest-result guidance instead of best-score mastery, targeted section focus and visible local-storage explanation.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
