'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/solid-mass')),topic='math3_9_koerper';
const keys={m39_q1:0,m39_q2:0,m39_q3:0,m39_prism_volume:0,m39_prism_surface:0,m39_pyramid_volume:0,m39_pyramid_height:0,m39_dip1:0,m39_dip2:0,m39_oblique_depth:1,m39_mass_prism:1,m39_density_inverse:0,m39_mass_hollow:2,m39_mass_compare:0};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-solid-mass]')?.dataset.ready==='true');const lab=p.locator('[data-solid-mass]'),input=lab.locator('input'),result=lab.locator('[data-solid-mass-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));let states=0;
 for(const kind of ['box','tri','pyramid'])for(const h of [3,6,9])for(const density of [0.5,1.2,2.7]){await lab.locator('#solid-mass-body').selectOption(kind);await lab.locator('#solid-mass-height').selectOption(String(h));await lab.locator('#solid-mass-material').selectOption(String(density));const mass=({box:12,tri:6,pyramid:16/3})[kind]*h*density;await input.fill(String(Number(mass.toFixed(6))).replace('.',','));await input.press('Enter');assert.equal(await result.getAttribute('data-correct'),'true');assert.equal(await result.evaluate(e=>e===document.activeElement),true);assert.ok((await result.innerText()).includes(mass.toLocaleString('de-AT')+' g'));states++;}
 await input.fill('2');await input.press('Enter');assert.equal(await result.getAttribute('data-correct'),'false');await input.fill('1e2');await input.press('Enter');assert.equal(await input.getAttribute('aria-invalid'),'true');assert.equal(await input.evaluate(e=>e===document.activeElement),true);await input.fill('3');assert.equal(await result.innerText(),'');await lab.locator('[data-solid-mass-reset]').click();assert.equal(await lab.locator('#solid-mass-body').evaluate(e=>e===document.activeElement),true);assert.equal(await input.inputValue(),'');
 await p.locator('#ans_m39_1').fill('3D');await p.locator('#ans_m39_1').press('Enter');assert.match(await p.locator('#res_m39_1').innerText(),/^Richtig/);
 for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:900});await p.evaluate(d=>document.documentElement.setAttribute('data-theme',d?'dark':'light'),dark);
  for(const kind of ['box','tri','pyramid']){await lab.locator('#solid-mass-body').selectOption(kind);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);layouts.push({width,dark,kind});if(width===320)await lab.screenshot({path:path.join(out,`mass-${kind}-${dark}.jpg`)});}
  for(const kind of ['prism','pyramid']){const figure=p.locator(`[data-solid-sketch="${kind}"]`);const bounds=await figure.locator('text').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBBox();return[r.x,r.y,r.x+r.width,r.y+r.height];}));assert.ok(bounds.every(r=>r[0]>=0&&r[1]>=0&&r[2]<=360&&r[3]<=330));if(width===320)await figure.locator('..').screenshot({path:path.join(out,`sketch-${kind}-${dark}.jpg`)});}
  if(width===320){await p.locator('#ans_m39_1').locator('..').screenshot({path:path.join(out,`model-${dark}.jpg`)});await p.locator('[data-prism-view="net"]').click();await p.locator('[data-prism-part="base"]').click();await p.locator('[data-prism-net]').screenshot({path:path.join(out,`net-${dark}.jpg`)});}
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);console.log('PASS: 27 native mass calculations, 18 layouts, keyboard/reset/storage; starting 39 graded answers.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,count:q.answers.length})));assert.equal(qs.length,14);let answers=0;
 for(const[index,{id,count}]of qs.entries())for(let choice=0;choice<count;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[id];assert.equal(r.lastPercent,right?100:93);assert.deepEqual(r.reviewQuestionIds,right?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.solid-extension-paper').count(),1);assert.equal(await paper.locator('.solid-drawing svg').count(),2);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-solid-extension-solution]').count(),2);await paper.pdf({path:path.join(out,'solid-mass-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),states,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 27 mass cases, 18 layouts, 39 graded answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
