const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/word-workshop')),topic='dgb_word_werkstatt',keys=require('./fixtures/dgb_word_keys.json'),chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic];
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>window.currentChapterQuiz?.questions.length===9);await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'page overflow '+width);
  if(width===320){const diagram=p.locator('.word-diagram').first();await diagram.focus();assert.equal(await diagram.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('.word-diagram').scrollLeft>0);await diagram.evaluate(e=>e.scrollLeft=0);}
  const overflowing=await p.locator('.word-task-card,.word-check-card,.word-path,.word-grid,.word-output').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.className+': '+e.textContent.slice(0,100)));assert.deepEqual(overflowing,[],'content overflow '+width);
  if(width===320||width===1280)for(const [name,n]of [['toc',5],['image',7],['table',8],['project',12]]){await p.locator('[data-chapter-section="'+n+'"]').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.screenshot({path:path.join(out,`${name}-${width}-${dark?'dark':'light'}.png`),animations:'disabled'});}
 }
 const stored=await p.evaluate(()=>JSON.stringify(localStorage));for(const q of chapter.sections.flatMap(s=>s.quizzes||[])){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [i,a]of q.answers.entries()){const b=box.getByRole('button',{name:a.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),i===keys[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));practiceAnswers++;}}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
 const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(ids,Object.keys(keys));for(const [n,id]of ids.entries())for(let a=0;a<3;a++){if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(result.lastPercent,a===keys[id]?100:89);assert.equal(result.contentRevision,1);assert.deepEqual(result.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;}
 await p.goto(base+'/topics/worksheet.html?topic='+topic);await p.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await p.locator('#ws-solutions').isVisible(),false);assert.equal(await p.locator('#ws-content>.question-block').count(),9);assert.equal(await p.locator('#ws-dgb-material>article').count(),13);await p.locator('#ws-include-solutions').check();await p.pdf({path:path.join(out,'dgb-word-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(answers,27);assert.equal(practiceAnswers,27);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),answers,practiceAnswers,layouts:6,keyboard:true,practiceStorageUnchanged:true,errors},null,2));console.log('PASS: 27 native quiz answers, 27 practice answers, six layouts, keyboard operation, unchanged practice storage and chapter PDF.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
