'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/functions'));
const test=fs.readFileSync(path.join(__dirname,'test_function_representations.js'),'utf8'),keys=vm.runInNewContext('('+test.match(/const keys=(\{[^;]+\});/)[1]+')');
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{const p=await b.newPage({viewport:{width:390,height:1400}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic=math4_4_funktionen_sys');await p.waitForFunction(()=>document.querySelector('[data-function-line]')?.dataset.bound==='true');const stored=await p.evaluate(()=>JSON.stringify(localStorage));let nativeModels=0,paths=0;
 for(const m of [-2,-1,-.5,0,.5,1,2])for(const bb of [-2,0,1,3])for(const dx of [1,2]){for(const [id,v]of [['m',m],['b',bb],['dx',dx],['x',4]])await p.locator('#function-'+id).selectOption(String(v));await p.locator('#function-answer').fill(String(m*4+bb).replace('.',','));await p.locator('#function-answer').press('Enter');assert.match(await p.locator('#function-status').textContent(),/^Richtig/);nativeModels++;}
 await p.locator('#function-answer').fill('abc');await p.locator('[data-function-check]').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'function-answer');await p.locator('[data-function-reset]').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'function-m');await p.locator('#function-m').press('ArrowUp');assert.equal(await p.locator('#function-m').inputValue(),'1');await p.locator('[data-function-reset]').click();
 for(let t=0;t<=8;t++){await p.locator('#function-time').fill(String(t));await p.locator('#function-time').dispatchEvent('input');await p.locator('#walk-answer').fill(String([0,60,120,120,120,90,60,30,0][t]));await p.locator('#walk-answer').press('Enter');assert.match(await p.locator('#walk-status').textContent(),/^Richtig/);}await p.locator('[data-walk-reset]').click();await p.locator('#function-time').press('ArrowRight');assert.equal(await p.locator('#function-time').inputValue(),'6');await p.locator('[data-walk-reset]').click();assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);console.log('PASS: 56 native line models, nine time cases and keyboard/reset/storage.');
 const combinations=[-2,-1,-.5,0,.5,1,2].flatMap(m=>[-2,0,1,3].flatMap(bb=>[1,2].map(dx=>[m,bb,dx])));
 for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:1500});await p.evaluate(d=>document.documentElement.setAttribute('data-theme',d?'dark':'light'),dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);await p.waitForTimeout(350);
  for(const values of combinations){for(let i=0;i<3;i++)await p.locator('#function-'+['m','b','dx'][i]).selectOption(String(values[i]));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);const bounds=await p.locator('.function-figure svg text').evaluateAll(ns=>ns.map(e=>{const r=e.getBBox(),v=e.ownerSVGElement.viewBox.baseVal;return r.x>=0&&r.y>=0&&r.x+r.width<=v.width&&r.y+r.height<=v.height;}));assert.ok(bounds.every(Boolean),'SVG labels clipped');layouts.push({width,dark,values});}
  for(let t=0;t<=8;t++){await p.locator('#function-time').fill(String(t));await p.locator('#function-time').dispatchEvent('input');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);layouts.push({width,dark,time:t});}
  await p.locator('[data-function-reset]').click();await p.locator('[data-walk-reset]').click();for(const selector of ['[data-function-line]','[data-function-walk]'])await p.locator(selector).screenshot({path:path.join(out,selector.includes('line')?`line-${width}-${dark}.png`:`walk-${width}-${dark}.png`)});
  const figures=p.locator('.function-figure svg[data-worksheet-static]');for(let i=0;i<await figures.count();i++){await figures.nth(i).evaluate(e=>e.scrollIntoView({block:'center'}));await figures.nth(i).screenshot({path:path.join(out,`static-${i}-${width}-${dark}.png`)});}
 }console.log('PASS: 390 line/time layout cases.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,length:q.answers.length})));for(const [i,q]of qs.entries())for(let choice=0;choice<q.length;choice++){if(!paths)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,i})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==i)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,i});await p.locator(`input[name="chapter_q_${i}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(()=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results')).math4_4_funktionen_sys);assert.equal(r.lastPercent,choice===keys[q.id]?100:95);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);paths++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic=math4_4_funktionen_sys');await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('[data-function-generated-answer]').count(),8);await paper.pdf({path:path.join(out,'functions-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),nativeModels,timeCases:9,paths,layouts,errors},null,2));console.log('PASS: 60 graded answer paths, worksheet exported.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
