const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/assignments-year3'),id='math3_6_zuordnungen';
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const answers={m36_q1:0,m36_dip1:0,m36_unit:2,m36_q2:0,m36_zero:0,m36_time:1,m36_graph:0,m36_falling:2,m36_fee_zero:1,m36_point:2,m36_difference:1,m36_domain:0,m36_work_parameter:1,m36_invariant:2,m36_assumptions:0};
const parameters={a:[2,3,4],b:[6,12,24],c:[0,5,10]};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===15&&document.querySelector('[data-assignment-graph]')?.dataset.bound==='true');let paths=0;
  assert.equal(await page.locator('[data-assignment-task]>li').count(),15);
  for(const q of source.sections.flatMap(s=>s.quizzes))for(const[i,a]of q.answers.entries()){const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:a.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===answers[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==answers[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));paths++;}
  const saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),lab=page.locator('[data-assignment-graph]'),model=lab.locator('#assignment-model'),parameter=lab.locator('[data-assignment-parameter]'),slider=lab.locator('#assignment-x'),verdict=lab.locator('[data-assignment-verdict-feedback]');
  for(const[text,correct]of [['50',true],['50,00',true],['20',false]]){await page.locator('#kino_in').fill(text);await page.locator('#kino_in').press('Enter');assert.equal((await page.locator('#kino_feedback').innerText()).startsWith('Richtig:'),correct);}for(const text of ['','50,001','1e2']){await page.locator('#kino_in').fill(text);await page.locator('#kino_in').press('Enter');assert.equal(await page.locator('#kino_in').getAttribute('aria-invalid'),'true');}
  async function keyboardSelect(locator,index){await locator.focus();await page.keyboard.press('Home');for(let i=0;i<index;i++)await page.keyboard.press('ArrowDown');}
  async function setX(x){await slider.focus();await slider.press('Home');for(let i=0;i<x;i++)await slider.press('ArrowRight');assert.equal(await slider.inputValue(),String(x));}
  let decisions=0;for(let m=0;m<3;m++)for(let pi=0;pi<3;pi++){const key=['a','b','c'][m],p=parameters[key][pi];await keyboardSelect(model,m);await keyboardSelect(parameter,pi);assert.equal(await model.inputValue(),key);assert.equal(await parameter.inputValue(),String(p));await setX(2);const expected=key==='b'?'inverse':key==='a'||p===0?'direct':'neither';for(const choice of ['direct','inverse','neither']){await lab.locator('[data-assignment-verdict='+choice+']').focus();await page.keyboard.press('Enter');assert.equal((await verdict.innerText()).startsWith('Richtig:'),choice===expected);decisions++;}}
  await lab.locator('[data-assignment-reset]').click();assert.equal(await model.inputValue(),'a');assert.equal(await parameter.inputValue(),'3');assert.equal(await slider.inputValue(),'2');assert.equal(await model.evaluate(e=>e===document.activeElement),true);assert.equal(await verdict.innerText(),'');assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);
  await page.addScriptTag({path:path.join(__dirname,'../js/topics/'+id+'.js')});await page.evaluate(()=>window.topicInit());assert.equal(await parameter.inputValue(),'3');assert.equal(await lab.locator('[data-assignment-live-table] tbody tr').count(),7);
  let states=0;for(const key of ['a','b','c'])for(const p of parameters[key])for(let x=0;x<=6;x++){
   await model.selectOption(key);await parameter.selectOption(String(p));await setX(x);const points=await lab.locator('[data-assignment-point]').evaluateAll(nodes=>nodes.map(e=>({x:Number(e.dataset.assignmentPoint),y:Number(e.dataset.value),extension:e.dataset.extension,cy:Number(e.getAttribute('cy'))})));assert.equal(points.length,key==='b'?6:7);for(const point of points){const expected=key==='a'?p*point.x:key==='b'?p/point.x:p+3*point.x;assert.equal(point.y,expected);assert.equal(point.extension,String(key==='c'&&p>0&&point.x===0));assert.ok(Math.abs(point.cy-(240-expected*200/(key==='b'?24:30)))<1e-8);}
   assert.equal(await lab.locator('[data-assignment-selected]').count(),key==='b'&&x===0?0:1);assert.equal(await lab.locator('[data-assignment-live-table] tbody tr').count(),7);assert.match(await lab.locator('[data-assignment-live-table] tr[data-selected] th').innerText(),new RegExp('^'+x+' '));if(key==='b'&&x===0)assert.match(await lab.locator('#assignment-result').innerText(),/nicht definiert/);if(key==='c'&&p>0&&x===0)assert.match(await lab.locator('#assignment-result').innerText(),/Ohne Bestellung/);
   const bounds=await lab.locator('svg').evaluate(e=>[...e.querySelectorAll('text')].map(t=>{const r=t.getBBox();return {text:t.textContent,x:r.x,y:r.y,right:r.x+r.width,bottom:r.y+r.height};}));assert.ok(bounds.every(r=>r.x>=0&&r.y>=0&&r.right<=360&&r.bottom<=300),JSON.stringify(bounds));states++;
  }
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('.assignment-lab h3')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(const key of ['a','b','c'])for(const p of parameters[key]){const x=(key==='b'&&p===12)||(key==='c'&&p===10)?0:6;await model.selectOption(key);await parameter.selectOption(String(p));await setX(x);const expected=key==='b'?'inverse':key==='a'||p===0?'direct':'neither';await lab.locator('[data-assignment-verdict='+expected+']').click();const geometry=await lab.evaluate(e=>{const r=e.getBoundingClientRect(),table=e.querySelector('.assignment-table-scroll');return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,tableClient:table.clientWidth,tableScroll:table.scrollWidth,controls:[...e.querySelectorAll('select,input,button')].map(b=>{const x=b.getBoundingClientRect();return {left:x.left,right:x.right,height:x.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow,JSON.stringify({width,theme,key,p,geometry}));assert.ok(geometry.controls.every(c=>c.left>=geometry.left&&c.right<=geometry.right+1&&c.height>=44));layouts.push({width,theme,key,p,x,geometry});if(width===390&&key==='c'&&p===10)await lab.screenshot({path:path.join(out,'fee-zero-input-'+theme+'.png')});if(width===390&&key==='b'&&p===12)await lab.screenshot({path:path.join(out,'undefined-'+theme+'.png')});}
   const scroll=lab.locator('.assignment-table-scroll');await scroll.focus();if(width===320){assert.ok(await scroll.evaluate(e=>e.scrollWidth>e.clientWidth));await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>{const e=document.querySelector('.assignment-table-scroll');return e.scrollLeft>20;},null,{timeout:3000});const pinned=await scroll.evaluate(e=>({container:e.getBoundingClientRect().left,column:e.querySelector('tbody th').getBoundingClientRect().left}));assert.ok(pinned.column>=pinned.container-1&&pinned.column<=pinned.container+2);}
   if(width===390)for(const key of ['a','b','c'])await page.locator('[data-assignment-static]').filter({has:page.locator('[data-assignment-svg="'+key+'"]')}).screenshot({path:path.join(out,'static-'+key+'-'+theme+'.png')});
  }
  const attempts=[];for(const[wrong,section]of [['m36_falling',2],['m36_work_parameter',4]]){await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const[i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(answers[q]+1)%3:answers[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,93);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));}
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),15);assert.equal(await paper.locator('[data-assignment-paper] tbody tr').count(),8);assert.equal(await paper.locator('#ws-math-material svg').count(),3);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('[data-assignment-answer]').first().isVisible(),false);
  const generated=await paper.locator('[data-assignment-generated]').evaluateAll(nodes=>nodes.map(e=>({kind:e.dataset.kind,unit:Number(e.dataset.unit),x:Number(e.dataset.x),fixed:Number(e.dataset.fixed),text:e.textContent})));assert.equal(generated.length,8);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('.ws-paper-solution').count(),5);const generatedAnswers=await paper.locator('#ws-solutions [data-assignment-answer]').evaluateAll(nodes=>nodes.map(e=>({kind:e.dataset.kind,answer:Number(e.dataset.assignmentAnswer),text:e.textContent})));assert.equal(generatedAnswers.length,8);for(let i=0;i<8;i++){const t=generated[i],s=generatedAnswers[i];assert.equal(s.kind,t.kind);assert.equal(s.answer,t.kind==='inverse'?t.fixed/t.x:t.fixed+t.unit*t.x);}
  await paper.locator('#ws-include-solutions').uncheck();assert.equal(await paper.locator('[data-assignment-answer]').first().isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.deepEqual(await paper.locator('[data-assignment-generated]').allTextContents(),generated.map(x=>x.text));await paper.pdf({path:path.join(out,'assignments-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),paths,decisions,states,layouts,attempts,generated,generatedAnswers,errors,scope:'45 quiz answers, 27 native classifications, keyboard controls/input/reset, 63 plot/table states, 54 layouts and scroll, two 93% checks and paper export. Selected visual PDF review separate; no full product acceptance.'},null,2)+'\n');console.log('PASS: assignments native: 45 answers, 27 classifications, 63 graph/table states, keyboard/reset, 54 layouts/scroll, two 93% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
