'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/farm')),topic='bio_4_landwirtschaft_biodiversitaet';
const keys={bio_4_land_s1:1,bio_4_land_d1:0,bio_4_land_s2:2,bio_4_land_d2:1,bio_4_land_bio_regeln:2,bio_4_land_bezugsflaeche:1,bio_4_land_arten:2,bio_4_land_ursache:0,bio_4_land_s3:1,bio_4_land_d3:2};
const cases=[['1','whole','A','-8,0 %'],['1','whole','B','+8,7 %'],['1','crop','A','+2,2 %'],['1','crop','B','-2,2 %'],['2','whole','A','-3,6 %'],['2','whole','B','+3,8 %'],['2','crop','A','+7,1 %'],['2','crop','B','-6,6 %'],['3','whole','A','-2,2 %'],['3','whole','B','+2,3 %'],['3','crop','A','+8,6 %'],['3','crop','B','-8,0 %']];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-farm-lab]')?.dataset.initialized==='true');
 const year=p.locator('[data-farm-year]'),basis=p.locator('[data-farm-basis]'),ref=p.locator('[data-farm-reference]'),check=p.locator('[data-farm-check]'),reset=p.locator('[data-farm-reset]'),result=p.locator('[data-farm-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 const fill=async(y,area,reference)=>{await year.selectOption(y);assert.equal(await result.textContent(),'');await basis.selectOption(area);await ref.selectOption(reference);await check.click();};
 for(const[y,area,reference,value]of cases){await fill(y,area,reference);assert.equal(await p.locator('[data-farm-percent]').textContent(),value);assert.equal(await result.evaluate(e=>e===document.activeElement),true);}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[y,area,reference]of [cases[0],cases[1],cases[2],cases[7],cases[9],cases[10]]){await fill(y,area,reference);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-farm-lab] button,[data-farm-lab] select').all())assert.ok((await el.boundingBox()).height>=44);layouts.push({dark,width,year:y,basis:area,reference});}
  for(const cell of await p.locator(':is(.farm-system,.farm-methods,.farm-data,.farm-shopping) tbody :is(th,td)').all())assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);
  for(const card of await p.locator('.farm-card').all()){assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');}
  if(width===390){await fill('1','crop','A');for(const[name,selector]of [['system','.farm-system'],['methods','.farm-methods'],['data','.farm-data'],['fields','.farm-fields'],['workshop','[data-farm-lab]'],['shopping','.farm-shopping']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await year.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowDown');assert.equal(await year.inputValue(),'2');await p.keyboard.press('Tab');await p.keyboard.press('ArrowDown');assert.equal(await basis.inputValue(),'crop');await p.keyboard.press('Tab');await p.keyboard.press('ArrowDown');assert.equal(await ref.inputValue(),'B');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await p.locator('[data-farm-percent]').textContent(),'-6,6 %');assert.equal(await result.evaluate(e=>e===document.activeElement),true);await year.selectOption('3');assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),correct=choice===keys[id];assert.equal(r.lastPercent,correct?100:90);assert.deepEqual(r.reviewQuestionIds,correct?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-farm-paper]').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),2);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('body').textContent()).includes('undefined'));await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-farm-solution]').count(),4);await paper.pdf({path:path.join(out,'farm-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),comparisons:12,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 12 native comparisons, 36 layouts, keyboard/reset/focus/storage, 30 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
