const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/recommendation-model')),topic='dgb7_orientierung',keys=require('./fixtures/dgb7_orientation_keys.json'),expected=require('./fixtures/feed_expectations');
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];let states=0,answers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.locator('#chapter-quiz-launch').waitFor();const stored=await p.evaluate(()=>JSON.stringify(localStorage)),lab=p.locator('.recommendation-model');
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(let s=0;s<=3;s++)for(let k=0;k<=3;k++)for(let z=0;z<=3;z++)for(const mode of ['common','profile','mix']){
   const result=await lab.evaluate((el,{counts,mode})=>{[...el.querySelectorAll('input')].forEach((e,i)=>{e.value=counts[i];e.dispatchEvent(new Event('input',{bubbles:true}));});const rule=el.querySelector('select');rule.value=mode;rule.dispatchEvent(new Event('change',{bubbles:true}));return {ids:[...el.querySelectorAll('[data-feed-selected]')].map(e=>Number(e.dataset.feedSelected)),overflow:document.documentElement.scrollWidth>innerWidth+1,status:el.querySelector('[role=status]').textContent};},{counts:[s,k,z],mode});assert.deepEqual(result.ids,expected([s,k,z],mode));assert.equal(result.overflow,false);assert.match(result.status,/keine Qualitätsbewertung/);states++;
  }
  await lab.locator('[data-feed-reset]').focus();await p.keyboard.press('Enter');assert.equal(await lab.locator('input').first().evaluate(e=>e===document.activeElement),true);
  for(let n=0;n<3;n++){const input=lab.locator('input').nth(n);await input.focus();await p.keyboard.press('Home');assert.equal(await input.inputValue(),'0');await p.keyboard.press('ArrowRight');assert.equal(await input.inputValue(),'1');await p.keyboard.press('End');assert.equal(await input.inputValue(),'3');}
  await lab.locator('[data-feed-reset]').click();if(width===390)await lab.screenshot({path:path.join(out,'feed-'+(dark?'dark':'light')+'.png')});
  if(width===320)await p.locator('[data-ai-tests]').screenshot({path:path.join(out,'ai-table-'+(dark?'dark':'light')+'.png')});
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(ids,Object.keys(keys));
 for(const [n,id]of ids.entries())for(let a=0;a<3;a++){if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(r.lastPercent,a===keys[id]?100:88);assert.equal(r.contentRevision,1);assert.deepEqual(r.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;}
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('[data-feed-paper] [data-feed-source]').count(),6);await paper.locator('#ws-include-solutions').check();await paper.pdf({path:path.join(out,'dgb7_orientierung-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(states,1152);assert.equal(answers,24);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),states,answers,chapterLayouts:6,keyboard:true,resetAndFocus:true,workshopStorageUnchanged:true,errors},null,2));console.log('PASS: 1152 browser model states, native keyboard/reset/focus, 24 quiz answers, six chapter layouts and complete worksheet export.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
