const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/growth-year3'),id='math3_10_prozent_zins';
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id],answers={m310_q1:0,m310_q2:1,m310_dip1:2,m310_factor:0,m310_chain:1,m310_points:2,m310_q3:0,m310_half:1,m310_interest:2,m310_compound_value:1,m310_dip2:0,m310_limits:2,m310_linear:2,m310_decay:0,m310_constant:1,m310_copy:1,m310_sheet_rate:0,m310_model:2};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===18&&document.querySelector('[data-growth-lab]')?.dataset.bound==='true');let paths=0;
  for(const q of source.sections.flatMap(s=>s.quizzes))for(const[i,a]of q.answers.entries()){const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:a.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===answers[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==answers[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));paths++;}
  const lab=page.locator('[data-growth-lab]'),start=lab.locator('#growth-start'),delta=lab.locator('#growth-delta'),rate=lab.locator('#growth-rate'),step=lab.locator('#growth-step'),saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results'));
  await start.focus();await start.press('End');assert.equal(await start.inputValue(),'1000');await delta.focus();await delta.press('Home');await rate.focus();await rate.press('Home');await step.focus();await step.press('Home');await step.press('ArrowRight');assert.equal(await step.inputValue(),'1');assert.match(await lab.locator('#growth-result').innerText(),/990,00 Euro; P = 900,00/);
  await page.locator('#ans_m310_1').fill('10,0');await page.locator('#ans_m310_1').press('Enter');assert.match(await page.locator('#res_m310_1').innerText(),/Richtig/);await page.locator('#ans_m310_1').fill('1e1');await page.locator('#ans_m310_1').press('Enter');assert.equal(await page.locator('#ans_m310_1').getAttribute('aria-invalid'),'true');
  await page.addScriptTag({path:path.join(__dirname,'../js/topics/'+id+'.js')});await page.evaluate(()=>topicInit());assert.equal(await start.inputValue(),'1000');await lab.locator('[data-growth-reset]').click();assert.equal(await start.inputValue(),'100');assert.equal(await start.evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);
  const states=await page.evaluate(()=>{const results=[];for(const s of [100,500,1000])for(const d of [-10,0,10])for(const p of [-10,0,10])for(let n=0;n<=6;n++){for(const[id,value,event]of [['growth-start',s,'change'],['growth-delta',d,'change'],['growth-rate',p,'change'],['growth-step',n,'input']]){const e=document.getElementById(id);e.value=value;e.dispatchEvent(new Event(event));}const lab=document.querySelector('[data-growth-lab]'),svg=lab.querySelector('svg');results.push({s,d,p,n,maximum:Number(svg.dataset.maximum),points:[...svg.querySelectorAll('[data-growth-point]')].map(e=>({key:e.dataset.growthPoint,n:Number(e.dataset.n),value:Number(e.dataset.value)})),bounds:[...svg.querySelectorAll('text')].map(e=>{const b=e.getBBox();return [b.x,b.y,b.x+b.width,b.y+b.height];}),selected:lab.querySelector('tr[data-selected] th').textContent,formula:lab.querySelector('[data-growth-formula]').textContent});}return results;});
  assert.equal(states.length,189);for(const st of states){assert.equal(st.points.length,14);for(const pt of st.points){const expected=pt.key==='linear'?st.s+st.d*pt.n:st.s*((100+st.p)/100)**pt.n;assert.ok(Math.abs(pt.value-expected)<1e-8);}assert.ok(st.bounds.every(b=>b[0]>=0&&b[1]>=0&&b[2]<=360&&b[3]<=300));assert.equal(st.selected,st.n+' ←');assert.ok(st.formula.includes(st.n?'C'+(st.n+2)+' = C'+(st.n+1)+'*(1+$H$2/100)':'=$F$2'));}
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('.growth-lab h3')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(const[s,a,p]of [[100,10,10],[100,-10,-10],[1000,0,0]]){await start.selectOption(String(s));await delta.selectOption(String(a));await rate.selectOption(String(p));const geometry=await lab.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('input,select,button')].map(x=>{const b=x.getBoundingClientRect();return {left:b.left,right:b.right,height:b.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow,JSON.stringify({width,theme,s,a,p,geometry}));assert.ok(geometry.controls.every(c=>c.left>=geometry.left&&c.right<=geometry.right+1&&c.height>=44));layouts.push({width,theme,s,a,p,geometry});if(width===390&&a===-10)await lab.screenshot({path:path.join(out,'decay-'+theme+'.png')});}
   const scroll=lab.locator('.growth-table-scroll');await scroll.focus();if(width===320){await scroll.evaluate(e=>e.scrollLeft=0);await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.growth-table-scroll').scrollLeft>20,null,{timeout:3000});const b=await scroll.evaluate(e=>({left:e.getBoundingClientRect().left,first:e.querySelector('tbody th').getBoundingClientRect().left}));assert.ok(Math.abs(b.left-b.first)<2);}
   const sheetScroll=page.locator('.growth-sheet-scroll');await sheetScroll.focus();if(width===320){await sheetScroll.evaluate(e=>e.scrollLeft=0);await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.growth-sheet-scroll').scrollLeft>20,null,{timeout:3000});const b=await sheetScroll.evaluate(e=>({left:e.getBoundingClientRect().left,first:e.querySelector('tbody th').getBoundingClientRect().left}));assert.ok(Math.abs(b.left-b.first)<2);}
   if(width===390){await page.locator('[data-growth-static]').screenshot({path:path.join(out,'static-'+theme+'.png')});await sheetScroll.evaluate(e=>e.scrollLeft=0);await sheetScroll.screenshot({path:path.join(out,'sheet-'+theme+'.png')});}
  }
  assert.ok((await page.locator('[data-growth-sheet]').innerText()).includes('=C2*(1+$H$2/100)'));
  const attempts=[];for(const[wrong,section]of [['m310_chain',1],['m310_copy',5]]){await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const[i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(answers[q]+1)%3:answers[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,94);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));}
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),18);assert.equal(await paper.locator('[data-growth-paper] tbody tr').count(),5);assert.equal(await paper.locator('#ws-math-material svg').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);
  const generated=await paper.locator('[data-growth-generated]').evaluateAll(nodes=>nodes.map(e=>({kind:Number(e.dataset.kind),start:Number(e.dataset.start),rate:Number(e.dataset.rate),steps:Number(e.dataset.steps),text:e.textContent})));assert.equal(generated.length,8);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('.ws-paper-solution').count(),6);const generatedAnswers=await paper.locator('#ws-solutions [data-growth-answer]').evaluateAll(nodes=>nodes.map(e=>({kind:Number(e.dataset.kind),value:Number(e.dataset.growthAnswer),text:e.textContent})));assert.equal(generatedAnswers.length,8);for(let i=0;i<8;i++){const t=generated[i],a=generatedAnswers[i];assert.equal(a.kind,t.kind);const expected=t.kind===0?t.start*(1-t.rate/100):t.kind===1?t.start*t.rate*t.steps/1200:t.kind===2?t.start+t.steps*t.rate:t.start*((100+t.rate)/100)**t.steps;assert.ok(Math.abs(a.value-expected)<1e-8);}
  await paper.locator('#ws-include-solutions').uncheck();assert.equal(await paper.locator('[data-growth-answer]').first().isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.deepEqual(await paper.locator('[data-growth-generated]').allTextContents(),generated.map(x=>x.text));await paper.pdf({path:path.join(out,'growth-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),paths,states:states.length,layouts,attempts,generated,generatedAnswers,errors,scope:'54 quiz answers, 189 models, keyboard/input/reset/reload, 18 layouts/scroll, two 94% checks and paper export. Selected visual review separate; no physical device, spreadsheet application or full product acceptance.'},null,2)+'\n');console.log('PASS: growth native: 54 answers, 189 models, keyboard/input/reset/reload, 18 layouts and scroll, two 94% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
