'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/cladograms')),topic='bio_3_kladogramme';
const keys={s1:0,d1:2,s2:1,d2:0,d4:2,s3:1,fehlend:0,konflikt:2,s4:1,d3:2};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-cladogram-evidence]')?.dataset.initialized==='true');
 const dataset=p.locator('[data-clad-data]'),model=p.locator('[data-clad-model]'),reason=p.locator('[data-clad-reason]'),check=p.locator('[data-clad-check]'),reset=p.locator('[data-clad-reset]'),result=p.locator('[data-clad-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));let decisions=0;
 const fill=async(mode,m,r)=>{await dataset.selectOption(mode);assert.equal(await model.inputValue(),'');assert.equal(await reason.inputValue(),'');assert.equal(await result.textContent(),'');await model.selectOption(m);await reason.selectOption(r);await check.click();};
 const expected={base:['none','shared'],bc:['bc','y'],ab:['ab','z'],conflict:['none','conflict']};
 for(const[mode,[mk,rk]]of Object.entries(expected))for(const m of ['bc','ab','ac','none'])for(const r of ['shared','y','z','conflict']){await fill(mode,m,r);assert.equal(await result.getAttribute('data-model-correct'),String(m===mk));assert.equal(await result.getAttribute('data-reason-correct'),String(r===rk));assert.equal(await result.evaluate(e=>e===document.activeElement),true);decisions++;}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[mode,m,r,name]of [['base','none','shared','missing-data'],['bc','bc','y','bc'],['ab','ab','z','ab'],['conflict','none','conflict','conflict'],['conflict','bc','y','wrong'],['base','','','incomplete']]){
   await fill(mode,m,r);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-cladogram-evidence] button,[data-cladogram-evidence] select,[data-cladogram-rotation] button').all())assert.ok((await el.boundingBox()).height>=44);layouts.push({dark,width,name});
  }
  for(const card of await p.locator('.clad-card').all()){assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');}
  // A page without horizontal overflow can still hide wide cells inside a clipped panel.
  for(const cell of await p.locator(':is(.clad-examples,.clad-elements,.clad-cases,.clad-vertebrates,.clad-matrix) tbody :is(th,td)').all())assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);
  for(const text of await p.locator('[data-cladogram-rotation] svg text').all())assert.ok(await text.evaluate(e=>e.getBoundingClientRect().height)>=12);
  if(width===390){await fill('conflict','none','conflict');for(const[name,selector]of [['examples','.clad-examples'],['rotation','[data-cladogram-rotation]'],['models','.clad-models'],['workshop','[data-cladogram-evidence]'],['vertebrates','.clad-vertebrates']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await dataset.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowDown');assert.equal(await dataset.inputValue(),'bc');await p.keyboard.press('Tab');await p.keyboard.press('ArrowDown');assert.equal(await model.inputValue(),'bc');await p.keyboard.press('Tab');await p.keyboard.press('ArrowDown');await p.keyboard.press('ArrowDown');assert.equal(await reason.inputValue(),'y');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await result.getAttribute('data-model-correct'),'true');assert.equal(await result.getAttribute('data-reason-correct'),'true');assert.equal(await result.evaluate(e=>e===document.activeElement),true);
 const rotation=p.locator('[data-cladogram-rotation]');for(const[selector,order]of [['[data-rotate-pair]','ACB'],['[data-rotate-root]','CBA'],['[data-rotate-pair]','BCA'],['[data-rotate-root]','ABC']]){const button=rotation.locator(selector);await button.focus();await p.keyboard.press('Enter');assert.equal(await rotation.locator('[data-tip]').evaluateAll(els=>els.sort((a,b)=>+a.getAttribute('y')-+b.getAttribute('y')).map(e=>e.dataset.tip).join('')),order);assert.equal(await button.evaluate(e=>e===document.activeElement),true);}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index,topic})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id.replace(topic+'_','')]}"]`).checked=true;}),{keys,index,topic});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),correct=choice===keys[id.replace(topic+'_','')];assert.equal(r.lastPercent,correct?100:90);assert.deepEqual(r.reviewQuestionIds,correct?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-clad-paper]').count(),1);assert.equal(await paper.locator('[data-clad-rotation-paper]').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),4);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-clad-solution]').count(),4);await paper.pdf({path:path.join(out,'cladograms-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 64 model/reason decisions, 36 layouts, four native rotations, keyboard/reset/focus/storage, 30 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
