const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/reaction-builder');
const correct={methane:[1,2,1,2],hydrogen:[2,1,2],peroxide:[2,2,1]};
const expected=(key,[a,b,c,d])=>key==='methane'?{C:[a,c],H:[4*a,2*d],O:[2*b,2*c+d]}:key==='hydrogen'?{H:[2*a,2*c],O:[2*b,c]}:{H:[2*a,2*b],O:[2*a,b+2*c]};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];try{
 const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic=chemie_reaktionen_energie');await page.waitForFunction(()=>document.querySelector('[data-chem-lab="reaction-builder"]')?.dataset.chemReady==='true');const lab=page.locator('[data-chem-lab="reaction-builder"]'),inputs=lab.locator('[data-chem-coeff]'),status=lab.locator('.chem-status'),initial=await page.evaluate(()=>JSON.stringify(localStorage));assert.equal(await lab.getAttribute('data-chem-reaction'),'hydrogen');
 async function setReaction(key){const btn=lab.locator('[data-chem-action="'+key+'"]');await btn.focus();await btn.press('Enter');}
 async function setValues(values){for(let i=0;i<values.length;i++)await inputs.nth(i).fill(String(values[i]));}
 async function verify(key,values){const count=values.reduce((a,b)=>a+b,0);assert.equal(await lab.locator('[data-reaction-molecule]').count(),count);const totals=expected(key,values);for(const[atom,[left,right]]of Object.entries(totals)){const row=lab.locator('[data-reaction-atom="'+atom+'"]');assert.equal(Number(await row.locator('td').nth(0).innerText()),left);assert.equal(Number(await row.locator('td').nth(1).innerText()),right);assert.equal(await row.locator('td').nth(2).innerText(),left===right?'ja':'nein');}assert.equal((await status.innerText()).startsWith('Richtig ausgeglichen:'),values.every(v=>v>0)&&Object.values(totals).every(([l,r])=>l===r));}
 let states=0,invalid=0;for(const[key,solution]of Object.entries(correct)){
  await setReaction(key);const n=solution.length;
  for(const values of [Array(n).fill(0),Array(n).fill(1),solution,solution.map(v=>v*2),Array(n).fill(9),solution.map((v,i)=>i===0?0:v)]){await setValues(values);await verify(key,values);states++;}
  for(let i=0;i<n;i++)for(const value of ['','-1','10','1.5']){const input=inputs.nth(i);await input.fill(value);assert.equal(await input.getAttribute('aria-invalid'),'true');assert.equal(await input.evaluate(e=>e===document.activeElement),true);assert.equal(await lab.locator('svg').count(),0);await input.fill('1');assert.equal(await input.getAttribute('aria-invalid'),'false');invalid++;}
  const reset=lab.locator('[data-chem-action="reset"]');await reset.focus();await reset.press('Enter');assert.equal(await reset.evaluate(e=>e===document.activeElement),true);assert.equal(await lab.getAttribute('data-chem-reaction'),key);for(let i=0;i<n;i++)assert.equal(await inputs.nth(i).inputValue(),'1');await page.evaluate(()=>ChemieLabs.topicInit());assert.equal(await lab.getAttribute('data-chem-reaction'),key);
 }
 assert.equal(await page.evaluate(()=>JSON.stringify(localStorage)),initial);const layouts=[];
 for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);
  for(const[key,solution]of Object.entries(correct))for(const values of [Array(solution.length).fill(0),solution,Array(solution.length).fill(9)]){
   await setReaction(key);await setValues(values);const result=await lab.evaluate(e=>({overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('input,button')].filter(x=>x.getClientRects().length).map(x=>{const r=x.getBoundingClientRect();return [r.left,r.right,r.height];}),texts:[...e.querySelectorAll('svg text')].map(t=>{const r=t.getBBox(),m=t.getScreenCTM();return {x:r.x,y:r.y,right:r.x+r.width,bottom:r.y+r.height,size:parseFloat(getComputedStyle(t).fontSize)*Math.hypot(m.a,m.b)};}),table:e.querySelector('[data-reaction-balance]').getBoundingClientRect().right}));
   assert.ok(!result.overflow,JSON.stringify({width,theme,key,values}));assert.ok(result.controls.every(c=>c[0]>=0&&c[1]<=width+1&&c[2]>=44));assert.ok(result.texts.every(t=>t.x>=0&&t.y>=0&&t.right<=100&&t.bottom<=100&&t.size>=16),JSON.stringify(result.texts));assert.ok(result.table<=width+1);layouts.push({width,theme,key,values});
   if(width===390&&values[0]===solution[0])await lab.locator('.reaction-model').screenshot({path:path.join(out,key+'-'+theme+'.png')});
  }
 }
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic=chemie_reaktionen_energie');await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-reaction-paper]').count(),3);assert.equal(await paper.locator('[data-reaction-paper] svg[data-worksheet-static]').count(),10);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('#ws-chemistry-material').innerText()).includes('Gleiche Molekülzahlen können vorkommen'));await paper.locator('#ws-include-solutions').check();assert.ok((await paper.locator('#ws-solutions').innerText()).includes('Gleiche Molekülzahlen können vorkommen'));await paper.pdf({path:path.join(out,'builder-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),states,invalid,layouts,errors,scope:'18 native model states, 40 invalid inputs, keyboard/focus/reset/storage, 54 layouts including zero and nine molecules per species, glyph size/bounds, paper and solutions; no chemical experiment.'},null,2)+'\n');console.log('PASS: 18 native balances, 40 invalid inputs, reset/focus/storage, 54 layouts with readable atom symbols and paper export.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
