'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),keys=require('./fixtures/column_arithmetic_answer_keys.json');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/column-arithmetic')),id='math1_3_add_sub';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.addInitScript(()=>{let n=58316;Math.random=()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};});await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.querySelector('#ws-print').disabled);
 assert.equal(await paper.locator('[data-column-paper],[data-column-quick-paper]').count(),4);assert.equal(await paper.locator('.ws-paper-solution').count(),5);assert.equal(await paper.locator('.column-reference').count(),3);await paper.locator('#ws-include-solutions').check();
 const generated=await paper.locator('[data-column-generated]').evaluateAll(es=>es.map(e=>({...e.dataset,text:e.textContent}))),answers=await paper.locator('[data-column-generated-answer]').evaluateAll(es=>es.map(e=>({...e.dataset,text:e.textContent})));assert.equal(generated.length,20);assert.equal(answers.length,20);
 for(let i=0;i<20;i++){const a=+generated[i].a,b=+generated[i].b;assert.equal(+answers[i].columnGeneratedAnswer,generated[i].kind==='add'?a+b:a-b);}
 const before=await paper.locator('[data-column-generated]').allTextContents();await paper.locator('#ws-include-solutions').uncheck();assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.deepEqual(await paper.locator('[data-column-generated]').allTextContents(),before);await paper.pdf({path:path.join(out,'column-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});console.log('Worksheet PDF exported; browser checks continue.');await paper.close();
 const p=await browser.newPage({viewport:{width:390,height:2200},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+id);await p.waitForFunction(()=>document.querySelectorAll('[data-column-lab][data-bound="true"]').length===2);const saved=await p.evaluate(()=>JSON.stringify(localStorage));
 for(const kind of ['add','subtract']){const host=p.locator('[data-column-lab="'+kind+'"]'),input=host.locator('input');await input.fill('2e1');await p.keyboard.press('Enter');assert.equal(await input.getAttribute('aria-invalid'),'true');assert.equal(await input.evaluate(e=>e===document.activeElement),true);await input.fill('99');await p.keyboard.press('Enter');assert.equal(await host.getAttribute('data-step'),'0');await input.fill(kind==='add'?'9':'13');await p.keyboard.press('Enter');assert.equal(await host.getAttribute('data-step'),'1');await host.locator('[data-column-reset]').focus();await p.keyboard.press('Space');assert.equal(await input.evaluate(e=>e===document.activeElement),true);while(await host.locator('[data-column-show]').isEnabled()){await host.locator('[data-column-show]').focus();await p.keyboard.press('Enter');}assert.equal(await host.locator('[data-column-status]').evaluate(e=>e===document.activeElement),true);assert.match(await host.locator('[data-column-status]').innerText(),/wurden gezeigt/);}
 for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await p.setViewportSize({width,height:2200});await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await p.waitForFunction(t=>getComputedStyle(document.body).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);await p.waitForTimeout(350);
  const rows=await p.evaluate(()=>{const rows=[];function record(host,kind,index){const r=host.getBoundingClientRect();rows.push({kind,index,left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1||host.scrollWidth>host.clientWidth+1,controls:[...host.querySelectorAll('input,select,button,summary')].map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,height:r.height};})});}
   for(const host of document.querySelectorAll('[data-column-lab]')){const select=host.querySelector('select'),input=host.querySelector('input'),kind=host.dataset.columnLab;for(let i=0;i<select.options.length;i++){select.value=i;select.dispatchEvent(new Event('change'));host.querySelector('details').open=false;record(host,kind,i+',0');const[a,b]=select.options[i].textContent.split(/[+−]/).map(Number),model=columnArithmeticModel(a,b,kind);for(const[j,step]of model.steps.entries()){input.value=step.expected;host.querySelector('[data-column-check]').click();record(host,kind,i+','+(j+1));}host.querySelector('details').open=true;record(host,kind+'-history',i);}}
   document.querySelectorAll('.column-reference,.written-lab:not([data-column-lab])').forEach((host,i)=>record(host,'reference',i));return rows;});
  for(const r of rows){assert.ok(!r.overflow&&r.left>=0&&r.right<=width+1,JSON.stringify({width,theme,...r}));assert.ok(r.controls.every(c=>c.height>=44&&c.left>=r.left&&c.right<=r.right+1),JSON.stringify({width,theme,...r}));layouts.push({width,theme,kind:r.kind,index:r.index});}
  for(const kind of ['add','subtract']){const host=p.locator('[data-column-lab="'+kind+'"]');await host.locator('select').selectOption(kind==='add'?'6':'3');for(let i=0;i<3;i++)await host.locator('[data-column-show]').click();await host.locator('details').evaluate(e=>e.open=false);await host.screenshot({path:path.join(out,kind+'-'+width+'-'+theme+'.png')});}
  if(width===320){for(let i=0;i<3;i++)await p.locator('.column-reference').nth(i).screenshot({path:path.join(out,'reference-'+i+'-'+theme+'.png')});for(let i=0;i<2;i++)await p.locator('.written-lab:not([data-column-lab])').nth(i).screenshot({path:path.join(out,'quick-'+i+'-'+theme+'.png')});}
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);await p.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();const questions=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,count:q.answers.length})));assert.equal(questions.length,9);let paths=0;
 for(const[i,q]of questions.entries())for(let a=0;a<q.count;a++){if(paths)await p.getByRole('button',{name:'Neuen Versuch starten',exact:true}).click();await p.evaluate(({i,a,keys})=>currentChapterQuiz.questions.forEach((q,j)=>document.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?a:keys[q.id])+'"]').checked=true),{i,a,keys});await p.locator('.chapter-submit-btn').click();const r=await p.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(r.lastPercent,a===keys[q.id]?100:89);assert.equal(r.contentRevision,2);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);paths++;}
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),layouts,paths,generated,answers,errors},null,2)+'\n');console.log('PASS: '+layouts.length+' column arithmetic layouts, keyboard/reset/reveal/focus/storage, '+paths+' quiz paths and 20 independently checked worksheet answers.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
