'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright'),base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/pythagoras'));
const keys={m38_q1:0,pyth_names:1,pyth_puzzle_1:0,m38_q2:0,m38_dip1:0,pyth_same_pieces:2,pyth_middle_square:0,pyth_general:1,pyth_converse:1,pyth_not_right:2,pyth_degenerate:0,m42_q1:0,m42_q2:0,m42_leg:0,m42_diagonal:0,m42_dip1:0,pyth_isosceles:1,pyth_triangle_area:2,pyth_rhombus:0,pyth_space_triangle:2,pyth_space_value:0,pyth_space_inverse:1,pyth_pyramid_height:1,pyth_pyramid_area:2,pyth_pyramid_edge:0};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[],reports=[];try{for(const topic of ['math3_8_pythagoras','math4_2_pythagoras']){
 const foundation=topic==='math3_8_pythagoras',p=await b.newPage({viewport:{width:390,height:1200}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(f=>document.querySelector(f?'[data-pyth-proof]':'[data-pyth-space]')?.dataset.bound==='true',foundation);const saved=await p.evaluate(()=>JSON.stringify(localStorage));let models=0,answers=0;
 const range=async(id,value)=>{await p.locator(id).fill(String(value));await p.locator(id).dispatchEvent('input');};
 if(foundation){for(let a=1;a<=6;a++)for(let bb=1;bb<=6;bb++){await range('#proof-a',a);await range('#proof-b',bb);await p.locator('#proof-answer').fill(String(a*a+bb*bb));await p.locator('#proof-answer').press('Enter');assert.match(await p.locator('#proof-status').textContent(),/^Richtig/);models++;}
  for(const [sides,expected]of [[[13,5,12],'Rechtwinklig.'],[[6,8,11],'Nicht rechtwinklig.'],[[2,3,5],'Kein Dreieck:'],[[1.5,2,2.5],'Rechtwinklig.']]){for(let i=0;i<3;i++)await p.locator('#converse-'+['x','y','z'][i]).fill(String(sides[i]).replace('.',','));await p.locator('#converse-z').press('Enter');assert.ok((await p.locator('[data-converse-status]').textContent()).includes(expected));}await p.locator('#converse-x').fill('0');await p.locator('[data-converse-check]').click();assert.equal(await p.locator('#converse-x').getAttribute('aria-invalid'),'true');await p.locator('[data-converse-reset]').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'converse-x');
  await p.locator('#pyth-puzzle-svg [role="button"]').first().focus();for(let i=0;i<25;i++)await p.keyboard.press(i%2?'Space':'Enter');assert.equal(await p.locator('#pyth-puzzle-svg [data-moved]').count(),25);assert.equal(await p.locator('[data-pyth-puzzle-reset]').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.equal(await p.locator('#pyth-puzzle-svg [data-moved]').count(),0);await p.locator('[data-pyth-next]').click();assert.equal(await p.locator('#pyth-puzzle-svg [data-moved]').count(),1);await p.locator('[data-pyth-puzzle-reset]').click();
  await p.locator('[data-proof-reset]').click();await p.locator('#proof-a').press('ArrowRight');assert.equal(await p.locator('#proof-a').inputValue(),'4');await p.locator('[data-proof-reset]').click();
 }else{for(const a of [2,3,4,6])for(const bb of [2,3,4,6])for(const h of [2,6,12]){for(const [id,value]of [['a',a],['b',bb],['h',h]])await p.locator('#space-'+id).selectOption(String(value));await p.locator('#space-answer').fill(Math.hypot(a,bb,h).toFixed(2).replace('.',','));await p.locator('#space-answer').press('Enter');assert.match(await p.locator('#space-status').textContent(),/^Richtig/);models++;}await p.locator('#space-answer').fill('falsch');await p.locator('[data-space-check]').click();assert.equal(await p.locator('#space-answer').getAttribute('aria-invalid'),'true');await p.locator('[data-space-reset]').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'space-a');}
 const quick=foundation?'#pyth_in':'#pyth1';await p.locator(quick).fill('5');await p.locator(quick).press('Enter');assert.match(await p.locator(foundation?'#pyth_feedback':'#fb_pyth1').textContent(),/^Richtig/);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:1500});await p.evaluate(d=>document.documentElement.setAttribute('data-theme',d?'dark':'light'),dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);await p.waitForTimeout(100);
  const combinations=foundation?Array.from({length:36},(_,i)=>[1+Math.floor(i/6),1+i%6]):[2,3,4,6].flatMap(a=>[2,3,4,6].flatMap(bb=>[2,6,12].map(h=>[a,bb,h])));
  for(const values of combinations){if(foundation){await range('#proof-a',values[0]);await range('#proof-b',values[1]);await p.locator('[data-proof-show]').click();}else{for(let i=0;i<3;i++)await p.locator('#space-'+['a','b','h'][i]).selectOption(String(values[i]));await p.locator('[data-space-show]').click();}assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);const svgBounds=await p.locator('.pyth-figure svg text').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBBox(),v=e.ownerSVGElement.viewBox.baseVal;return r.x>=0&&r.y>=0&&r.x+r.width<=v.width&&r.y+r.height<=v.height;}));assert.ok(svgBounds.every(Boolean),'clipped SVG text');layouts.push({topic,width,dark,values});}
  if(foundation){await range('#proof-a',3);await range('#proof-b',4);await p.locator('[data-proof-show]').click();for(const selector of ['[data-pyth-proof]','[data-pyth-converse]','.pyth-puzzle','.pyth-intro']){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'center'}));await p.locator(selector).screenshot({path:path.join(out,`${selector.replace(/[^a-z-]/g,'')}-${width}-${dark?'dark':'light'}.png`)});}}else{await p.locator('[data-space-reset]').click();await p.locator('[data-space-show]').click();await p.locator('[data-pyth-space]').screenshot({path:path.join(out,`space-${width}-${dark?'dark':'light'}.png`)});for(let i=0;i<4;i++){const svg=p.locator('svg[data-worksheet-static]').nth(i);await svg.evaluate(e=>e.scrollIntoView({block:'center'}));await svg.screenshot({path:path.join(out,`figure-${i}-${width}-${dark?'dark':'light'}.png`)});}}
 }
 console.log('PASS: '+topic+' native models and responsive layouts; testing quiz answers.');const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,length:q.answers.length})));for(const[index,q]of qs.entries())for(let choice=0;choice<q.length;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],topic),right=choice===keys[q.id];assert.equal(r.lastPercent,right?100:foundation?91:93);assert.deepEqual(r.reviewQuestionIds,right?[]:[q.id]);answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.pyth-paper').count(),foundation?4:2);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('[data-pyth-generated-answer]').count(),6);await paper.pdf({path:path.join(out,topic+'-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});reports.push({topic,models,answers});await p.close();await paper.close();console.log('PASS: '+topic+' '+models+' models, '+answers+' native quiz answers, worksheet exported.');
 }assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),reports,layouts,errors},null,2));console.log('PASS: both Pythagoras chapters, 84 native models, 504 layouts, 69 quiz answers.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
