'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/respiration')),topic='bio_3_atmung_energie';
const keys={bio_3_atmung_s1:1,bio_3_atmung_d1:2,bio_3_atmung_d2:0,bio_3_atmung_s2:0,bio_3_atmung_transport:1,bio_3_atmung_s3:0,bio_3_atmung_d3:1,bio_3_atmung_rates:2,bio_3_atmung_s4:1,bio_3_atmung_help:0};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-respiration-lab]')?.dataset.initialized==='true');
 const storage=await p.evaluate(()=>JSON.stringify(localStorage)),n=p.locator('[data-respiration-count]'),t=p.locator('[data-respiration-seconds]'),calc=p.locator('[data-respiration-calculate]'),reset=p.locator('[data-respiration-reset]'),feedback=p.locator('[data-respiration-output]');
 const result=async(count,seconds,rate,step)=>{await n.fill(String(count));await t.selectOption(String(seconds));assert.equal(await feedback.locator('[data-respiration-rate]').count(),0);await calc.focus();await p.keyboard.press('Enter');assert.equal(await feedback.locator('[data-respiration-rate]').getAttribute('data-respiration-rate'),String(rate));assert.equal(await feedback.locator('[data-respiration-difference]').getAttribute('data-respiration-difference'),String(step));assert.equal(await calc.evaluate(e=>e===document.activeElement),true);};
 let calculations=0;for(const a of [[8,30,16,2],[13,30,26,2],[9,30,18,2],[16,60,16,1],[4,15,16,4],[5,15,20,4],[17,60,17,1],[0,15,0,4],[120,15,480,4],[120,30,240,2],[120,60,120,1]]){await result(...a);calculations++;}
 for(const [i,[count,seconds,rate]]of [[8,30,16],[13,30,26],[9,30,18],[16,60,16]].entries()){await p.locator(`[data-respiration-preset="${i}"]`).click();assert.equal(await n.inputValue(),String(count));assert.equal(await t.inputValue(),String(seconds));assert.equal(await feedback.locator('[data-respiration-rate]').count(),0);await calc.click();assert.equal(await feedback.locator('[data-respiration-rate]').getAttribute('data-respiration-rate'),String(rate));}
 for(const value of ['','-1','121','1.5']){await n.fill(value);await calc.click();assert.match(await feedback.textContent(),/ganze Anzahl/);assert.equal(await n.getAttribute('aria-invalid'),'true');assert.equal(await feedback.locator('[data-respiration-rate]').count(),0);}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const control of [p.locator('.respiration-card').first(),n,t]){assert.equal(await control.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');assert.equal(await control.evaluate(e=>getComputedStyle(e).color),dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)');}
  for(const [kind,value]of [['result','120'],['invalid','1.5'],['missing','']]){await n.fill(value);await t.selectOption('15');await calc.click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const control of [calc,reset,n,t,...await p.locator('[data-respiration-preset]').all()])assert.ok((await control.boundingBox()).height>=44);layouts.push({dark,width,kind});}
  if(width===390){await result(13,30,26,2);for(const [name,selector]of [['workshop','[data-respiration-lab]'],['route','.respiration-route'],['animals','.respiration-animals'],['data','.respiration-data'],['cases','.respiration-cases']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png')});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await n.evaluate(e=>e===document.activeElement),true);assert.equal(await n.inputValue(),'8');assert.equal(await t.inputValue(),'30');assert.equal(await feedback.textContent(),'');await p.keyboard.press('ArrowUp');assert.equal(await n.inputValue(),'9');await p.keyboard.press('Tab');assert.equal(await t.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowDown');assert.equal(await t.inputValue(),'60');await calc.focus();await p.keyboard.press('Enter');assert.equal(await feedback.locator('[data-respiration-rate]').getAttribute('data-respiration-rate'),'9');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);const f=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(f));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.respiration-route svg').count(),1);assert.equal(await paper.locator('[data-respiration-paper]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-respiration-solution]').count(),4);await paper.pdf({path:path.join(out,'respiration-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),calculations,presets:4,invalidInputs:4,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: numerical examples, presets/errors, 18 layouts, keyboard/reset/focus/storage, 30 quiz answers and paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
