'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/soil')),topic='bio_3_boden_mikroorganismen';
const keys={bio_3_boden_s1:1,bio_3_boden_pores:2,bio_3_boden_s2:0,bio_3_boden_fair:1,bio_3_boden_loss:2,bio_3_boden_s3:0,bio_3_boden_water:1,bio_3_boden_roots:1,bio_3_boden_s4:2,bio_3_boden_plan:0};
const expected={moisture:[['same','fair','other','confounded'],['fair','same','confounded','other'],['other','confounded','same','fair'],['confounded','other','fair','same']],temperature:[['same','other','fair','confounded'],['other','same','confounded','fair'],['fair','confounded','same','other'],['confounded','fair','other','same']]};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-soil-lab]')?.dataset.initialized==='true');
 const factor=p.locator('[data-soil-factor]'),left=p.locator('[data-soil-left]'),right=p.locator('[data-soil-right]'),check=p.locator('[data-soil-check]'),reset=p.locator('[data-soil-reset]'),result=p.locator('[data-soil-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));let decisions=0;
 const choose=async(f,a,z)=>{await factor.selectOption(f);assert.equal(await result.textContent(),'');await left.selectOption(a);await right.selectOption(z);await check.click();assert.equal(await result.evaluate(e=>e===document.activeElement),true);};
 for(const[f,matrix]of Object.entries(expected))for(let i=0;i<4;i++)for(let j=0;j<4;j++){await choose(f,'ABCD'[i],'ABCD'[j]);assert.equal(await result.getAttribute('data-verdict'),matrix[i][j]);decisions++;}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[f,a,z,verdict]of [['moisture','A','B','fair'],['temperature','A','C','fair'],['moisture','A','D','confounded'],['moisture','A','C','other'],['moisture','D','D','same']]){
   await choose(f,a,z);assert.equal(await result.getAttribute('data-verdict'),verdict);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-soil-lab] button,[data-soil-lab] select').all())assert.ok((await el.boundingBox()).height>=44);layouts.push({dark,width,f,a,z,verdict});
  }
  for(const card of await p.locator('.soil-card').all()){assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');assert.equal(await card.evaluate(e=>getComputedStyle(e).color),dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)');}
  if(width===390){await choose('moisture','A','B');for(const[name,selector]of [['profile','.soil-profile'],['components','.soil-components'],['organisms','.soil-organisms'],['cycle','.soil-cycle'],['trials','.soil-trials'],['workshop','[data-soil-lab]'],['roots','.soil-roots'],['flow','.soil-flow'],['plans','.soil-plans']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await factor.evaluate(e=>e===document.activeElement),true);assert.equal(await result.textContent(),'');await p.keyboard.press('End');assert.equal(await factor.inputValue(),'temperature');await p.keyboard.press('Tab');assert.equal(await left.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Tab');await p.keyboard.press('c');assert.equal(await right.inputValue(),'C');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await result.getAttribute('data-verdict'),'fair');assert.equal(await result.evaluate(e=>e===document.activeElement),true);await right.selectOption('D');assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-soil-paper]').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),2);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-soil-solution]').count(),4);await paper.pdf({path:path.join(out,'soil-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 32 comparisons, 30 layouts, native keyboard/reset/focus/storage, 30 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
