'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/similarity')),topic='math3_7_aehnlichkeit';
const keys={m37_q1:0,m37_dilation_ray:0,m37_dilation_center:1,m37_area_factor:2,m37_area_reverse:1,m37_triangle_angles:0,m37_triangle_sides:2,m37_q2:0,m37_equal:0,m37_reverse:0,m37_dip1:0};
const area=points=>Math.abs(points.reduce((a,p,i)=>{const q=points[(i+1)%points.length];return a+p[0]*q[1]-q[0]*p[1];},0))/2;
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-dilation-lab]')?.dataset.ready==='true');
 const saved=await p.evaluate(()=>JSON.stringify(localStorage)),lab=p.locator('[data-dilation-lab]'),shape=p.locator('#dilation-shape'),center=p.locator('#dilation-center'),factor=p.locator('#dilation-factor'),x=p.locator('#dilation-x'),y=p.locator('#dilation-y'),result=lab.locator('[data-dilation-result]');let cases=0;
 const figures={triangle:[[2,1],[4,1],[2,3]],rectangle:[[2,1],[5,1],[5,3],[2,3]]},centers={origin:[0,0],vertex:[2,1],outside:[6,4]};
 for(const [figure,original]of Object.entries(figures))for(const [name,z]of Object.entries(centers))for(const k of [0.5,1,1.5,2]){
  await shape.selectOption(figure);await center.selectOption(name);await factor.selectOption(String(k));assert.equal(await lab.getAttribute('data-revealed'),'false');assert.equal(await x.inputValue(),'');
  const expected=original.map(p=>p.map((n,i)=>z[i]+(n-z[i])*k));await x.fill(String(expected[0][0]));await y.fill(String(expected[0][1]).replace('.',',').replace('-','−'));await y.press('Enter');assert.equal(await result.getAttribute('data-correct'),'true');assert.equal(await result.evaluate(e=>e===document.activeElement),true);
  const points=await lab.locator('[data-dilation-image]').getAttribute('points'),actual=points.split(' ').map(p=>p.split(',').map(Number)).map(([sx,sy])=>[(sx-50)/26-3,(330-sy)/26-3]);assert.deepEqual(actual,expected);assert.equal(area(actual)/area(original),k*k);
  const cells=await lab.locator('tbody tr').evaluateAll(rows=>rows.map(r=>r.lastElementChild.textContent));assert.deepEqual(cells,expected.map(p=>'('+p.map(v=>v.toLocaleString('de-AT')).join('|')+')'));
  await x.fill('999');await y.press('Enter');assert.equal(await result.getAttribute('data-correct'),'false');cases++;
 }
 await x.fill('1e2');await y.press('Enter');assert.equal(await x.getAttribute('aria-invalid'),'true');assert.equal(await x.evaluate(e=>e===document.activeElement),true);await x.fill('1');assert.equal(await result.innerText(),'');await y.fill('');await x.press('Enter');assert.equal(await y.getAttribute('aria-invalid'),'true');
 await lab.locator('[data-dilation-reset]').click();assert.equal(await shape.evaluate(e=>e===document.activeElement),true);assert.equal(await lab.getAttribute('data-revealed'),'false');await lab.locator('[data-dilation-show]').click();assert.equal(await lab.getAttribute('data-revealed'),'true');assert.equal(await result.getAttribute('data-correct'),null);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:900});await p.evaluate(dark=>document.documentElement.setAttribute('data-theme',dark?'dark':'light'),dark);await p.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const figure of Object.keys(figures))for(const name of Object.keys(centers))for(const k of ['0.5','1','1.5','2']){
   await shape.selectOption(figure);await center.selectOption(name);await factor.selectOption(k);await lab.locator('[data-dilation-show]').click();
   const boxes=await lab.locator('[data-dilation-label]').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBBox();return {text:e.textContent,x:r.x,y:r.y,w:r.width,h:r.height};}));
   assert.ok(boxes.every(r=>r.x>=0&&r.y>=0&&r.x+r.w<=480&&r.y+r.h<=390),JSON.stringify({figure,name,k,boxes}));
   for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],c=boxes[j];assert.ok(!(a.x<c.x+c.w&&a.x+a.w>c.x&&a.y<c.y+c.h&&a.y+a.h>c.y),JSON.stringify({figure,name,k,a,c}));}
   assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await lab.locator('[data-dilation-table]').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);assert.deepEqual(await lab.locator('tbody tr').first().locator('td').evaluateAll(nodes=>nodes.map(n=>n.dataset.label)),['Ausgangsfigur','Bildfigur']);layouts.push({width,dark,figure,name,k});
  }
  if(width===320){for(const [name,k]of [['origin','0.5'],['vertex','1'],['outside','1.5']]){await center.selectOption(name);await factor.selectOption(k);await lab.locator('[data-dilation-show]').click();await lab.screenshot({path:path.join(out,`lab-${name}-${dark?'dark':'light'}.png`)});}await p.locator('.dilation-example').screenshot({path:path.join(out,`figure-${dark?'dark':'light'}.png`)});await p.locator('.dilation-lab').first().screenshot({path:path.join(out,`legacy-${dark?'dark':'light'}.png`)});
   const drawing=lab.locator('[data-dilation-drawing]');await drawing.focus();await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('[data-dilation-drawing]').scrollLeft>0);
  }
 }
 console.log('PASS: 24 native constructions, geometry, labels in 144 layouts, keyboard and storage; starting 33 graded answers.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,11);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[id];assert.equal(r.lastPercent,right?100:91);assert.deepEqual(r.reviewQuestionIds,right?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.dilation-paper').count(),1);assert.equal(await paper.locator('.dilation-example svg').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('[data-dilation-tasks] > li').count(),9);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-dilation-solution]').count(),3);assert.equal(await paper.locator('#ws-solutions [data-dilation-plan-solution]').count(),1);await paper.pdf({path:path.join(out,'similarity-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),cases,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 24 constructions, 144 layouts, 33 graded answers and optional paper solutions; PDF exported.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
