'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright'),keys=require('./fixtures/ratio_answer_keys.json');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/ratio-proportions')),id='math3_5_verhaeltnisse';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:2200}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+id);await p.waitForFunction(()=>document.querySelector('[data-ratio-equation-lab]')?.dataset.bound==='true');const saved=await p.evaluate(()=>JSON.stringify(localStorage));
 await p.locator('#ratio-answer').fill('1e1');await p.keyboard.press('Enter');assert.equal(await p.locator('#ratio-answer').getAttribute('aria-invalid'),'true');assert.equal(await p.locator('#ratio-answer').evaluate(e=>e===document.activeElement),true);
 await p.locator('#ratio-case').selectOption('1');await p.locator('#ratio-answer').fill('0');await p.keyboard.press('Enter');assert.match(await p.locator('#ratio-result').innerText(),/Durch null/);
 await p.locator('#ratio-answer').fill('6,00');await p.keyboard.press('Enter');assert.match(await p.locator('#ratio-result').innerText(),/^Richtig/);await p.locator('[data-ratio-reveal]').focus();await p.keyboard.press('Space');assert.equal(await p.locator('[data-ratio-reveal]').getAttribute('aria-expanded'),'true');await p.locator('[data-ratio-reset]').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#ratio-answer').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('#ratio-answer').inputValue(),'');
 for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await p.setViewportSize({width,height:2200});await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await p.waitForFunction(t=>getComputedStyle(document.body).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);await p.waitForTimeout(350);
  const rows=await p.evaluate(()=>{const host=document.querySelector('[data-ratio-equation-lab]'),task=document.querySelector('#ratio-case'),input=document.querySelector('#ratio-answer'),rows=[],expected=[7.5,6,15,15,6,7.5,8,12];
   const record=(el,kind,index)=>{const r=el.getBoundingClientRect();rows.push({kind,index,left:r.left,right:r.right,overflow:el.scrollWidth>el.clientWidth+1||document.documentElement.scrollWidth>innerWidth+1,controls:[...el.querySelectorAll('input,select,button')].map(e=>{const x=e.getBoundingClientRect();return {left:x.left,right:x.right,height:x.height};})});};
   for(let i=0;i<8;i++){task.value=i;task.dispatchEvent(new Event('change'));record(host,'empty',i);input.value=expected[i]+1;host.querySelector('[data-ratio-check]').click();record(host,'incorrect',i);input.value=expected[i];host.querySelector('[data-ratio-check]').click();record(host,'correct',i);host.querySelector('[data-ratio-reveal]').click();record(host,'explanation',i);}
   record(document.querySelector('#sirup_in').closest('.interactive-zone'),'mixture',0);record(document.querySelector('.ratio-figure'),'figure',0);return rows;
  });
  for(const r of rows){assert.ok(!r.overflow&&r.left>=0&&r.right<=width+1,JSON.stringify({width,theme,...r}));assert.ok(r.controls.every(c=>c.height>=44&&c.left>=r.left&&c.right<=r.right+1),JSON.stringify({width,theme,...r}));layouts.push({width,theme,kind:r.kind,index:r.index});}
  const labels=await p.locator('.ratio-strip text').evaluateAll(es=>es.map(e=>{const s=e.ownerSVGElement,r=s.getBoundingClientRect(),bb=e.getBBox(),vb=s.viewBox.baseVal;return {size:parseFloat(getComputedStyle(e).fontSize)*r.width/vb.width,fit:bb.x>=0&&bb.y>=0&&bb.x+bb.width<=vb.width&&bb.y+bb.height<=vb.height};}));assert.ok(labels.every(x=>x.fit&&x.size>=12),JSON.stringify(labels));
  await p.locator('[data-ratio-equation-lab]').screenshot({path:path.join(out,'equation-'+width+'-'+theme+'.png')});await p.locator('.ratio-figure').screenshot({path:path.join(out,'figure-'+width+'-'+theme+'.png')});
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 await p.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(ids.length,13);let paths=0;
 for(const[i,qid]of ids.entries())for(let answer=0;answer<3;answer++){
  if(paths)await p.getByRole('button',{name:'Neuen Versuch starten',exact:true}).click();
  await p.evaluate(({i,answer,keys})=>{currentChapterQuiz.questions.forEach((q,j)=>document.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?answer:keys[q.id])+'"]').checked=true);},{i,answer,keys});await p.locator('.chapter-submit-btn').click();const result=await p.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,answer===keys[qid]?100:92);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,answer===keys[qid]?[]:[qid]);paths++;
 }
 await p.addInitScript(()=>{let n=37629;Math.random=()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};});await p.goto(base+'/topics/worksheet.html?topic='+id);await p.waitForFunction(()=>!document.querySelector('#ws-print').disabled);assert.equal(await p.locator('[data-ratio-paper]').count(),2);assert.equal(await p.locator('.ws-paper-solution').count(),4);assert.equal(await p.locator('#ws-math-material svg').count(),1);
 const generated=await p.locator('[data-ratio-generated]').evaluateAll(es=>es.map(e=>({...e.dataset,text:e.textContent})));await p.locator('#ws-include-solutions').check();const answers=await p.locator('[data-ratio-generated-answer]').evaluateAll(es=>es.map(e=>({value:e.dataset.ratioGeneratedAnswer,text:e.textContent}))),gcd=(a,b)=>b?gcd(b,a%b):a;
 for(let i=0;i<12;i++){const {kind}=generated[i],a=+generated[i].a,b=+generated[i].b,f=+generated[i].factor,v=answers[i].value;if(kind==='reduce'){const[x,y]=v.split(':').map(Number);assert.equal(x*b,y*a);assert.equal(gcd(x,y),1);}else if(kind==='share'){const[x,y]=v.split(':').map(Number);assert.equal(x+y,(a+b)*f);assert.equal(x*b,y*a);}else assert.equal(kind==='numerator'?+v/(b*f):(a*f)/+v,a/b);}
 const before=await p.locator('[data-ratio-generated]').allTextContents();await p.locator('#ws-include-solutions').uncheck();assert.equal(await p.locator('#ws-solutions').isVisible(),false);await p.locator('#ws-include-solutions').check();assert.deepEqual(await p.locator('[data-ratio-generated]').allTextContents(),before);await p.pdf({path:path.join(out,'ratio-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),layouts,paths,generated,answers,errors},null,2)+'\n');console.log('PASS: '+layouts.length+' ratio layouts, keyboard/focus/reset/storage, all '+paths+' quiz answers, worksheet controls and independent generated answers; PDF exported.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
