'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/genetics')),topic='bio_4_genetik_gentechnik';
const keys={bio_4_genetik_s1:1,bio_4_genetik_d1:2,bio_4_genetik_s2:0,bio_4_genetik_wahrscheinlichkeit:2,bio_4_genetik_dominanz:1,bio_4_genetik_d2:1,bio_4_genetik_mutation:0,bio_4_genetik_gesundheit:2,bio_4_genetik_s3:1,bio_4_genetik_d3:0,bio_4_genetik_daten:2};
const cases=[['AA','AA',[4,0,0]],['AA','Aa',[2,2,0]],['AA','aa',[0,4,0]],['Aa','AA',[2,2,0]],['Aa','Aa',[1,2,1]],['Aa','aa',[0,2,2]],['aa','AA',[0,4,0]],['aa','Aa',[0,2,2]],['aa','aa',[0,0,4]]],modes=['unknown','dominant','intermediate'];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-genetics-lab]')?.dataset.initialized==='true');
 const first=p.locator('[data-genetics-parent1]'),second=p.locator('[data-genetics-parent2]'),rule=p.locator('[data-genetics-rule]'),check=p.locator('[data-genetics-check]'),reset=p.locator('[data-genetics-reset]'),result=p.locator('[data-genetics-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 const fill=async(a,s,m)=>{await first.selectOption(a);assert.equal(await result.textContent(),'');await second.selectOption(s);await rule.selectOption(m);await check.click();};
 for(const[a,s,counts]of cases)for(const mode of modes){await fill(a,s,mode);assert.deepEqual(await p.locator('[data-genetics-count]').evaluateAll(es=>es.map(e=>Number(e.dataset.geneticsCount))),counts);const expected=mode==='unknown'?null:(mode==='dominant'?[counts[0]+counts[1],0,counts[2]]:counts).join(',');assert.equal(await p.locator('[data-genetics-phenotype]').getAttribute('data-genetics-colors'),expected);assert.equal(await result.evaluate(e=>e===document.activeElement),true);}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[a,s]of [['AA','aa'],['Aa','Aa']])for(const mode of modes){await fill(a,s,mode);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-genetics-lab] button,[data-genetics-lab] select').all())assert.ok((await el.boundingBox()).height>=44);for(const text of await p.locator('.genetics-map text').all())assert.ok(await text.evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('svg').getBoundingClientRect();return r.height>=12&&r.left>=s.left-1&&r.right<=s.right+1;}));layouts.push({dark,width,first:a,second:s,rule:mode});}
  for(const cell of await p.locator(':is(.genetics-rules,.genetics-growth,.genetics-uses,.genetics-distribution,.genetics-square) :is(th,td)').all()){if(await cell.evaluate(e=>e.closest('thead')&&getComputedStyle(e.closest('thead')).position==='absolute'))continue;assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);}
  assert.ok(await p.locator('.genetics-square caption').evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=e.parentElement.getBoundingClientRect().width*.95&&r.height<=parseFloat(getComputedStyle(e).lineHeight)*5;}));
  for(const card of await p.locator('.genetics-card').all())assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');
  if(width===390){await fill('Aa','Aa','intermediate');for(const[name,selector]of [['map','.genetics-map'],['rules','.genetics-rules'],['square','.genetics-square'],['distribution','.genetics-distribution'],['growth','.genetics-growth'],['uses','.genetics-uses']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});await p.locator('[data-genetics-lab]').screenshot({path:path.join(out,'workshop-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await first.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Home');assert.equal(await first.inputValue(),'AA');await p.keyboard.press('Tab');await p.keyboard.press('End');assert.equal(await second.inputValue(),'aa');await p.keyboard.press('Tab');await p.keyboard.press('End');assert.equal(await rule.inputValue(),'intermediate');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await p.locator('[data-genetics-phenotype]').getAttribute('data-genetics-colors'),'0,4,0');assert.equal(await result.evaluate(e=>e===document.activeElement),true);await first.selectOption('aa');assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,11);let answers=0;
 const practice=p.locator('.practice-box[data-id="bio_4_genetik_extra_dna"]');for(const option of await practice.locator('button').all()){await option.click();assert.ok((await practice.locator('.feedback').textContent()).includes(await option.getAttribute('data-feedback')));assert.equal(await option.isEnabled(),true);}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),correct=choice===keys[id];assert.equal(r.lastPercent,correct?100:91);assert.deepEqual(r.reviewQuestionIds,correct?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-genetics-paper]').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('body').textContent()).includes('undefined'));await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-genetics-solution]').count(),4);await paper.pdf({path:path.join(out,'genetics-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),states:27,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 27 native inheritance/rule states, 36 layouts, keyboard/reset/focus/storage, 33 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
