const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/reaction-evidence');
const cases={water:['physical','physical',0],bottle:['unknown','physical',1],sugar:['physical','physical',2],wax:['chemical','chemical',0],metal:['unknown','chemical',1],foam:['unknown','chemical',2]};
const keys={ch_chemie_reaktionen_energie_q1:1,ch_chemie_reaktionen_energie_q2:2,ch_chemie_reaktionen_energie_q3:0,dip_chemie_reaktionen_energie_1:2,dip_chemie_reaktionen_energie_2:1,dip_chemie_reaktionen_energie_3:0,dip_chemie_reaktionen_energie_4:2,reaction_mass:1,reaction_activation:0,reaction_controls:2,reaction_coefficients:1,reaction_molecules:0};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];try{
 const page=await browser.newPage({viewport:{width:390,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic=chemie_reaktionen_energie');await page.waitForFunction(()=>document.querySelector('[data-chem-lab="evidence-cases"]')?.dataset.chemReady==='true');const lab=page.locator('[data-chem-lab="evidence-cases"]'),select=lab.locator('select'),toggle=lab.locator('[data-evidence-toggle]'),feedback=lab.locator('[data-evidence-feedback]'),nextFeedback=lab.locator('[data-evidence-next-feedback]'),initial=await page.evaluate(()=>JSON.stringify(localStorage));let decisions=0;
 async function choose(index){await select.focus();await select.press('Home');for(let i=0;i<index;i++)await select.press('ArrowDown');}
 for(const[index,[name,expected]]of Object.entries(cases).entries()){
  await choose(index);assert.equal(await select.inputValue(),name);const card=lab.locator('[data-evidence-case="'+name+'"]');assert.equal(await card.isVisible(),true);
  for(let phase=0;phase<2;phase++){
   if(phase){await toggle.focus();await toggle.press('Enter');}assert.equal(await toggle.getAttribute('aria-expanded'),String(phase===1));
   for(const value of ['physical','chemical','unknown']){const btn=lab.locator('[data-evidence-verdict="'+value+'"]');await btn.focus();await btn.press('Enter');assert.equal(await feedback.getAttribute('data-correct'),String(value===expected[phase]));decisions++;}
  }
  for(let i=0;i<3;i++){const btn=card.locator('[data-evidence-next]').nth(i);await btn.focus();await btn.press('Enter');assert.equal(await nextFeedback.getAttribute('data-correct'),String(i===expected[2]));decisions++;}
 }
 await lab.locator('[data-evidence-reset]').click();assert.equal(await select.inputValue(),'water');assert.equal(await select.evaluate(e=>e===document.activeElement),true);assert.equal(await feedback.innerText(),'');assert.equal(await page.evaluate(()=>JSON.stringify(localStorage)),initial);
 const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);
  for(const name of Object.keys(cases)){await select.selectOption(name);for(let phase=0;phase<2;phase++){
   if(phase)await toggle.click();const r=await lab.evaluate(e=>({overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('button,select')].filter(x=>x.getClientRects().length).map(x=>{const r=x.getBoundingClientRect();return [r.left,r.right,r.height];}),font:parseFloat(getComputedStyle(e.querySelector('[data-evidence-observation]')).fontSize)}));assert.ok(!r.overflow,JSON.stringify({width,theme,name,phase}));assert.ok(r.controls.every(c=>c[0]>=0&&c[1]<=width+1&&c[2]>=44));assert.ok(r.font>=16);layouts.push({width,theme,name,phase});
   if(width===390&&name==='metal'&&phase===1){await lab.locator('[data-evidence-verdict="chemical"]').click();await lab.locator('[data-evidence-case="metal"] [data-evidence-next]').nth(1).click();await lab.screenshot({path:path.join(out,'lab-'+theme+'.png')});}
  }}
 }
 await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();const qs=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,sectionIndex:q.sectionIndex})));assert.equal(qs.length,12);let answers=0;const reviewed=new Set();
 for(const[i,q]of qs.entries())for(let choice=0;choice<3;choice++){
  if(answers)await page.locator('[onclick="restartChapterQuiz()"]').click();
  await page.evaluate(({qs,keys,skip})=>{for(const[index,q]of qs.entries())if(index!==skip)document.querySelector(`input[name="chapter_q_${index}"][value="${keys[q.id]}"]`).checked=true;},{qs,keys,skip:i});
  await page.locator(`input[name="chapter_q_${i}"][value="${choice}"]`).check();await page.locator('.chapter-submit-btn').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results')).chemie_reaktionen_energie);assert.equal(saved.lastPercent,choice===keys[q.id]?100:92);assert.equal(saved.contentRevision,3);assert.deepEqual(saved.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);answers++;
  if(choice!==keys[q.id]&&!reviewed.has(q.sectionIndex)){await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+q.sectionIndex).evaluate(e=>e.contains(document.activeElement)));reviewed.add(q.sectionIndex);await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();}
 }
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic=chemie_reaktionen_energie');await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-evidence-paper-case]').count(),6);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.ok((await paper.locator('#ws-solutions').innerText()).includes('Erstes Urteil: Noch nicht entscheidbar'));await paper.pdf({path:path.join(out,'reactions-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),decisions,answers,layouts,errors,scope:'Native keyboard classifications/investigation choices, all 36 quiz answers, reset/focus/storage, 72 layouts and paper export; not a physical experiment.'},null,2)+'\n');console.log('PASS: 54 native evidence choices, 36 chapter answers, 72 layouts, reset/focus/storage and paper export.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
