'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/fossils')),topic='bio_3_fossilien_erdgeschichte';
const keys={bio_3_fossilien_s1:1,bio_3_fossilien_d2:2,bio_3_fossilien_abdruck:0,bio_3_fossilien_s2:2,bio_3_fossilien_d1:1,bio_3_fossilien_s3:0,bio_3_fossilien_d3:2,bio_3_fossilien_massstab:1,bio_3_fossilien_s4:0,bio_3_fossilien_d4:1};
const perm=values=>values.length?values.flatMap((v,i)=>perm(values.filter((_,j)=>i!==j)).map(rest=>[v,...rest])):[[]];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-fossil-lab]')?.dataset.initialized==='true');
 const orders=p.locator('[data-fossil-order]'),context=p.locator('[data-fossil-context]'),age=p.locator('[data-fossil-age]'),check=p.locator('[data-fossil-check]'),reset=p.locator('[data-fossil-reset]'),result=p.locator('[data-fossil-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));let decisions=0;
 const fill=async(row,mode,answer)=>{for(let i=0;i<4;i++)await orders.nth(i).selectOption(row[i]);await context.selectOption(mode);assert.equal(await result.textContent(),'');assert.equal(await age.inputValue(),'');await age.selectOption(answer);await check.click();};
 for(const row of perm(['A','B','C','D'])){await fill(row,'original','bounded');assert.equal(await result.getAttribute('data-order-correct'),String(row.join('')==='ABCD'));assert.equal(await result.getAttribute('data-age-correct'),'true');decisions++;}
 for(const [mode,key]of Object.entries({original:'bounded',reworked:'minimum',loose:'unknown'}))for(const answer of ['bounded','minimum','unknown']){await fill(['A','B','C','D'],mode,answer);assert.equal(await result.getAttribute('data-age-correct'),String(answer===key));assert.equal(await result.evaluate(e=>e===document.activeElement),true);decisions++;}
 await reset.click();await check.click();assert.equal(await result.getAttribute('data-invalid'),'order');assert.equal(await orders.nth(0).evaluate(e=>e===document.activeElement),true);decisions++;
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const [row,mode,answer,name]of [['ABCD','original','bounded','original'],['ABCD','reworked','minimum','reworked'],['ABCD','loose','unknown','loose'],['DCBA','original','bounded','wrong-order'],['ABCD','reworked','bounded','wrong-age'],['AABC','original','bounded','duplicate']]){
   await fill(row,mode,answer);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-fossil-lab] button,[data-fossil-lab] select').all())assert.ok((await el.boundingBox()).height>=44);if(name==='duplicate')assert.equal(await result.getAttribute('data-invalid'),'duplicate');layouts.push({dark,width,name});
  }
  for(const card of await p.locator('.fossil-card').all()){assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');assert.equal(await card.evaluate(e=>getComputedStyle(e).color),dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)');}
  if(width===390){await fill('ABCD','reworked','minimum');for(const[name,selector]of [['preservation','.fossil-preservation'],['time','.fossil-time'],['profile','.fossil-profile'],['contexts','.fossil-contexts'],['workshop','[data-fossil-lab]'],['reports','.fossil-reports']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});for(let i=0;i<3;i++)await p.locator('.fossil-finds .fossil-card').nth(i).screenshot({path:path.join(out,'find-'+i+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await orders.nth(0).evaluate(e=>e===document.activeElement),true);for(const letter of ['a','b','c','d']){await p.keyboard.press(letter);await p.keyboard.press('Tab');}assert.equal(await context.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('End');assert.equal(await context.inputValue(),'loose');await p.keyboard.press('Tab');await p.keyboard.press('End');assert.equal(await age.inputValue(),'unknown');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await result.getAttribute('data-order-correct'),'true');assert.equal(await result.getAttribute('data-age-correct'),'true');assert.equal(await result.evaluate(e=>e===document.activeElement),true);await context.selectOption('original');assert.equal(await result.textContent(),'');assert.equal(await age.inputValue(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-fossil-paper]').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),4);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-fossil-solution]').count(),4);await paper.pdf({path:path.join(out,'fossils-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 24 layer permutations, 9 age/context decisions, incomplete input, 36 layouts, native keyboard/reset/focus/storage, 30 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
