const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/induction-learning'),id='elektromagnetismus',source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const keys={em_motor_commutator:1,em_motor_couple:0,em_motor_deadpoint:2,magnet_basis_1:0,magnet_basis_2:0,magnet_basis_3:0,em_d11:2,em_s1_q1:0,em_d1:1,em_d2:2,em_s2_q1:1,em_d3:0,em_d4:2,em_d5:1,em_d13:1,em_s_relay_q1:2,em_s3_q1:1,em_d6:2,em_d7:0,em_d14:0,em_s5_q1:0,em_d10:1,em_s4_q1:0,em_d8:1,em_d9:2,em_d12:0,em_d15:1,em_induction_speed:2,em_induction_controls:0,em_trans_power:2},signs={N:{rest:0,in:1,out:-1},S:{rest:0,in:-1,out:1}};
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
try{const context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===30&&document.querySelector('[data-induction-lab]')?.dataset.bound==='true');let paths=0;
for(const q of source.sections.flatMap(s=>s.quizzes||[]).filter(q=>q.id in keys))for(const[i,a]of q.answers.entries()){const box=page.locator('.practice-box[data-id="'+q.id+'"]'),b=box.getByRole('button',{name:a.text,exact:true});await b.focus();await b.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),i===keys[q.id]);assert.equal(await b.evaluate(e=>e.classList.contains('is-wrong')),i!==keys[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));paths++;}
assert.equal(paths,90);const lab=page.locator('[data-induction-lab]'),selectors=['pole-select','motion-select','speed','circuit'].map(k=>lab.locator('[data-induction-'+k+']')),stored=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results'));let states=0,decisions=0;
async function pick(locator,index){await locator.focus();await locator.press('Home');for(let i=0;i<index;i++)await locator.press('ArrowDown');}
for(const[pi,pole]of ['N','S'].entries())for(const[mi,motion]of ['rest','in','out'].entries())for(const[si,speed]of ['slow','fast'].entries())for(const[ci,circuit]of ['open','closed'].entries()){
 for(const[i,index]of [pi,mi,si,ci].entries())await pick(selectors[i],index);const sign=signs[pole][motion];assert.equal(await lab.locator('[data-induction-pointer]').getAttribute('data-sign'),String(sign));assert.equal(await lab.locator('[data-induction-motion]').count(),motion==='rest'?0:1);assert.equal(await lab.locator('[data-induction-pole]').textContent(),pole);
 for(const v of [-1,0,1]){const b=lab.locator('[data-induction-verdict="'+v+'"]');await b.focus();await b.press('Enter');assert.equal((await lab.locator('[data-induction-feedback]').innerText()).startsWith('Richtig:'),v===sign);decisions++;}
 const bounds=await lab.locator('svg').evaluate(e=>[...e.querySelectorAll('text')].map(t=>{const r=t.getBBox();return [r.x,r.y,r.x+r.width,r.y+r.height];}));assert.ok(bounds.every(b=>b[0]>=0&&b[1]>=0&&b[2]<=360&&b[3]<=310));states++;
}
await lab.locator('[data-induction-reset]').click();assert.deepEqual(await Promise.all(selectors.map(l=>l.inputValue())),['N','rest','slow','open']);assert.equal(await selectors[0].evaluate(e=>e===document.activeElement),true);assert.equal(await lab.locator('[data-induction-feedback]').innerText(),'');assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),stored);
const trans=page.locator('#transRange');await trans.focus();await trans.press('Home');for(let n=1;n<=10;n++){if(n>1)await trans.press('ArrowRight');const b=await page.evaluate(()=>({pri:Number(document.getElementById('voltBarPri').getAttribute('height')),sec:Number(document.getElementById('voltBarSec').getAttribute('height')),text:document.getElementById('voltValSec').textContent,turns:document.querySelectorAll('#coil2 path').length}));assert.equal(b.sec/b.pri,n/5);assert.equal(b.text,n*46+'V');assert.equal(b.turns,n);}
for(const n of [2,5,10]){await trans.focus();await trans.press('Home');for(let i=1;i<n;i++)await trans.press('ArrowRight');assert.ok((await page.locator('#transText').textContent()).includes(n*46+'V'));await trans.locator('..').screenshot({path:path.join(out,'transformer-'+n+'.png')});}
await page.locator('#flashlight').focus();await page.locator('#flashlight').press('Enter');assert.ok(Number(await page.locator('#energyLevel').innerText())>0);await page.evaluate(()=>topicInit());assert.equal(await page.locator('#energyLevel').innerText(),'0');
const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('.em-induction-lab h3')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);for(const motion of ['rest','in','out']){await selectors[1].selectOption(motion);const geo=await lab.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('select,button')].map(x=>{const b=x.getBoundingClientRect();return {left:b.left,right:b.right,height:b.height};})};});assert.ok(geo.left>=0&&geo.right<=width+1&&!geo.overflow,JSON.stringify({width,theme,motion,geo}));assert.ok(geo.controls.every(c=>c.height>=44&&c.left>=geo.left&&c.right<=geo.right+1));layouts.push({width,theme,motion,geo});if(width===390&&motion==='out')await lab.screenshot({path:path.join(out,'lab-'+theme+'.png')});}
const transformerGeo=await page.locator('.em-transformer-lab').evaluate(e=>({overflow:document.documentElement.scrollWidth>innerWidth+1,readings:[...e.querySelectorAll('.diagram-box p')].map(p=>({font:parseFloat(getComputedStyle(p).fontSize),left:p.getBoundingClientRect().left,right:p.getBoundingClientRect().right})),control:e.querySelector('input').getBoundingClientRect().height}));assert.ok(!transformerGeo.overflow&&transformerGeo.control>=44);assert.ok(transformerGeo.readings.every(p=>p.font>=16&&p.left>=0&&p.right<=width+1));if(width===320)await page.locator('.em-transformer-lab').screenshot({path:path.join(out,'transformer-mobile-'+theme+'.png')});const scroll=page.locator('.em-observation-scroll');await scroll.focus();if(width===320){await scroll.evaluate(e=>e.scrollLeft=0);await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.em-observation-scroll').scrollLeft>20,null,{timeout:3000});const b=await scroll.evaluate(e=>({left:e.getBoundingClientRect().left,first:e.querySelector('tbody th').getBoundingClientRect().left}));assert.ok(Math.abs(b.left-b.first)<2);}if(width===390){await page.locator('[data-induction-static]').screenshot({path:path.join(out,'static-'+theme+'.png')});await scroll.evaluate(e=>e.scrollLeft=0);await scroll.screenshot({path:path.join(out,'observation-'+theme+'.png')});}}
const attempts=[];for(const[wrong,section]of [['em_d11',0],['em_d1',1],['em_d4',2],['em_s_relay_q1',3],['em_d7',4],['em_d9',5],['em_d10',6]]){await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const qs=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,correct:q.answers.findIndex(a=>a.correct),count:q.answers.length})));for(const[i,q]of qs.entries()){const correct=q.id in keys?keys[q.id]:q.correct;await page.locator('input[name="chapter_q_'+i+'"][value="'+(q.id===wrong?(correct+1)%q.count:correct)+'"]').check();}await page.locator('.chapter-submit-btn').click();const r=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(r.lastPercent,97);assert.equal(r.contentRevision,6);assert.deepEqual(r.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result:r});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));}
const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),30);assert.equal(await paper.locator('[data-em-inquiry]>li').count(),12);assert.equal(await paper.locator('[data-transformer-paper] tbody tr').count(),3);assert.equal(await paper.locator('[data-induction-paper] tbody tr').count(),6);assert.equal(await paper.locator('[data-induction-observation] tbody tr').count(),6);assert.equal(await paper.locator('[data-induction-static] svg').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('#ws-physics-material').innerText()).includes('Protokoll in Zeilenfolge'));await paper.locator('#ws-include-solutions').check();assert.ok((await paper.locator('#ws-solutions').innerText()).includes('Protokoll in Zeilenfolge'));await paper.pdf({path:path.join(out,'induction-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),paths,states,decisions,transformers:10,layouts,attempts,errors,scope:'All 30 questions/90 choices, seven review destinations, qualitative induction and proportional transformer bars with readable HTML values. Not a full chapter, physical experiment or device acceptance.'},null,2)+'\n');console.log('PASS: induction native: 90 answer paths, 24 cases/72 classifications, 10 transformer ratios, keyboard/reset/flashlight, 18 layouts and scroll, seven 97% checks and paper.');await context.close();
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
