'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/aquatic-development')),topic='bio_3_wassertiere_entwicklung';
const keys={bio_3_wassertiere_s1:1,bio_3_wassertiere_d2:2,bio_3_wassertiere_air:0,bio_3_wassertiere_s2:2,bio_3_wassertiere_identity:1,bio_3_wassertiere_d1:0,bio_3_wassertiere_s3:1,bio_3_wassertiere_d3:2,bio_3_wassertiere_s4:0,bio_3_wassertiere_model:1};
const expected=['eggs','larva','froglet','adult'],permutations=a=>a.length?a.flatMap((v,i)=>permutations(a.filter((_,j)=>i!==j)).map(p=>[v,...p])):[[]];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-aquatic-order]')?.dataset.initialized==='true');
 const store=await p.evaluate(()=>JSON.stringify(localStorage)),slots=p.locator('[data-aquatic-slot]'),check=p.locator('[data-aquatic-check]'),reset=p.locator('[data-aquatic-reset]'),feedback=p.locator('[data-aquatic-feedback]');await check.click();assert.match(await feedback.textContent(),/jeden der vier/);let orders=0;
 const set=async values=>{for(let i=0;i<4;i++)await slots.nth(i).selectOption(values[i]);};
 for(const order of permutations(expected)){await set(order);assert.equal(await feedback.locator('li').count(),0);await check.focus();await p.keyboard.press('Enter');const matched=order.filter((v,i)=>v===expected[i]).length;assert.equal((await feedback.textContent()).startsWith('Alle vier'),matched===4);if(matched<4)assert.ok((await feedback.textContent()).includes(matched+' von 4'));assert.deepEqual(await feedback.locator('li').evaluateAll(a=>a.map(e=>e.textContent.startsWith('Passt.'))),order.map((v,i)=>v===expected[i]));assert.equal(await check.evaluate(e=>e===document.activeElement),true);orders++;}
 const cases={correct:expected,wrong:['adult','froglet','larva','eggs'],duplicate:['eggs','eggs','eggs','eggs'],missing:['','','','']};
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const [kind,values]of Object.entries(cases)){await set(values);await check.click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const c of [check,reset,...await slots.all()])assert.ok((await c.boundingBox()).height>=44);if(kind==='duplicate')assert.match(await feedback.textContent(),/doppelt/);if(kind==='missing')assert.match(await feedback.textContent(),/jeden der vier/);layouts.push({dark,width,kind});}
  if(width===390){await set(expected);await check.click();for(const [name,selector]of [['workshop','[data-aquatic-order]'],['stages','.aquatic-stages'],['profiles','.aquatic-profiles'],['observations','.aquatic-observations'],['forces','.aquatic-forces']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png')});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await slots.nth(0).evaluate(e=>e===document.activeElement),true);assert.equal(await feedback.textContent(),'');await p.keyboard.press('ArrowDown');assert.equal(await slots.nth(0).inputValue(),'adult');await p.keyboard.press('Tab');assert.equal(await slots.nth(1).evaluate(e=>e===document.activeElement),true);await set(expected);await check.focus();await p.keyboard.press('Enter');assert.match(await feedback.textContent(),/^Alle vier/);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),store);
 let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);const f=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(f));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.aquatic-stage svg').count(),4);assert.equal(await paper.locator('[data-aquatic-paper]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-aquatic-solution]').count(),4);await paper.pdf({path:path.join(out,'aquatic-development-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),orders,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 24 orders, 24 layouts with validation states, keyboard/reset/focus/storage, 30 quiz answers and paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
