'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright'),keys=require('./fixtures/decimal_calculation_answer_keys.json');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/decimal-calculation')),id='math1_9_dezimalzahlen',de=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'));
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.querySelector('#ws-print').disabled);assert.equal(await paper.locator('[data-decimal-paper]').count(),4);assert.equal(await paper.locator('.ws-paper-solution').count(),5);await paper.locator('#ws-include-solutions').check();
 const generated=await paper.locator('[data-decimal-generated]').evaluateAll(es=>es.map(e=>({id:e.dataset.decimalGenerated,text:e.textContent}))),answers=await paper.locator('[data-decimal-generated-answer]').evaluateAll(es=>es.map(e=>({id:e.dataset.decimalGeneratedAnswer,text:e.textContent})));assert.equal(generated.length,100);assert.equal(answers.length,100);assert.deepEqual(generated.map(e=>e.id),answers.map(e=>e.id));
 const before=await paper.locator('[data-decimal-generated]').allTextContents();await paper.locator('#ws-include-solutions').uncheck();assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.deepEqual(await paper.locator('[data-decimal-generated]').allTextContents(),before);await paper.pdf({path:path.join(out,'decimal-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});console.log('Worksheet PDF exported; browser checks continue.');await paper.close();
 const p=await browser.newPage({viewport:{width:390,height:2200},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+id);await p.waitForFunction(()=>document.querySelectorAll('[data-decimal-lab][data-bound="true"]').length===4);const saved=await p.evaluate(()=>JSON.stringify(localStorage));
 for(const kind of ['add','subtract','multiply','divide']){const host=p.locator('[data-decimal-lab="'+kind+'"]'),input=host.locator('input');await input.fill('2e1');await p.keyboard.press('Enter');assert.equal(await input.getAttribute('aria-invalid'),'true');assert.equal(await input.evaluate(e=>e===document.activeElement),true);await input.fill('99');await p.keyboard.press('Enter');assert.equal(await host.getAttribute('data-step'),'0');await input.fill(kind==='divide'?'3':'2');await p.keyboard.press('Enter');assert.equal(await host.getAttribute('data-step'),'1');await host.locator('[data-decimal-reset]').focus();await p.keyboard.press('Space');assert.equal(await input.evaluate(e=>e===document.activeElement),true);while(await host.locator('[data-decimal-show]').isEnabled()){await host.locator('[data-decimal-show]').focus();await p.keyboard.press('Enter');}assert.equal(await host.locator('[data-decimal-status]').evaluate(e=>e===document.activeElement),true);assert.match(await host.locator('[data-decimal-status]').innerText(),/wurden gezeigt/);}
 for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await p.setViewportSize({width,height:2200});await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await p.waitForFunction(t=>getComputedStyle(document.body).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);await p.waitForTimeout(350);
  const rows=await p.evaluate(()=>{const rows=[];function record(host,kind,index){const r=host.getBoundingClientRect();rows.push({kind,index,left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1||host.scrollWidth>host.clientWidth+1,controls:[...host.querySelectorAll('input,select,button,summary')].map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,height:r.height};})});}
   for(const host of document.querySelectorAll('[data-decimal-lab]')){const select=host.querySelector('select'),input=host.querySelector('input'),kind=host.dataset.decimalLab;for(let i=0;i<select.options.length;i++){select.value=i;select.dispatchEvent(new Event('change'));host.querySelector('details').open=false;record(host,kind,i+',0');const[a,b]=select.options[i].textContent.split(/[+−·:]/).map(x=>x.trim()),model=decimalCalculation(a,b,kind);for(const[j,step]of model.steps.entries()){input.value=step.expected;host.querySelector('[data-decimal-check]').click();record(host,kind,i+','+(j+1));}host.querySelector('details').open=true;record(host,kind+'-history',i);}}
   document.querySelectorAll('.written-static-table,.decimal-calc-grid,.decimal-bridge').forEach((host,i)=>record(host,'reference',i));return rows;});
  for(const r of rows){assert.ok(!r.overflow&&r.left>=0&&r.right<=width+1,JSON.stringify({width,theme,...r}));assert.ok(r.controls.every(c=>c.height>=44&&c.left>=r.left&&c.right<=r.right+1),JSON.stringify({width,theme,...r}));layouts.push({width,theme,kind:r.kind,index:r.index});}
  for(const kind of ['add','subtract','multiply','divide']){const host=p.locator('[data-decimal-lab="'+kind+'"]');await host.locator('select').selectOption(kind==='subtract'?'2':kind==='divide'?'2':'0');for(let i=0;i<3;i++)await host.locator('[data-decimal-show]').click();await host.locator('details').evaluate(e=>e.open=false);await host.screenshot({path:path.join(out,kind+'-'+width+'-'+theme+'.png')});}
  if(width===320)for(let i=0;i<7;i++)await p.locator('.written-static-table').nth(i).screenshot({path:path.join(out,'table-'+i+'-'+theme+'.png')});
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);let practicePaths=0;
 for(const q of de[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly)){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const[a,answer]of q.answers.entries()){await box.getByRole('button',{name:answer.text,exact:true}).click();assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));assert.equal(await box.getByRole('button',{name:answer.text,exact:true}).evaluate(e=>e.classList.contains('is-correct')),a===0);practicePaths++;}}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);await p.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();const questions=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,count:q.answers.length})));assert.equal(questions.length,23);let paths=0;
 for(const[i,q]of questions.entries())for(let a=0;a<q.count;a++){if(paths)await p.getByRole('button',{name:'Neuen Versuch starten',exact:true}).click();await p.evaluate(({i,a,keys})=>currentChapterQuiz.questions.forEach((q,j)=>document.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?a:keys[q.id])+'"]').checked=true),{i,a,keys});await p.locator('.chapter-submit-btn').click();const r=await p.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(r.lastPercent,a===keys[q.id]?100:96);assert.equal(r.contentRevision,4);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);paths++;}
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),layouts,paths,practicePaths,generated,answers,errors},null,2)+'\n');console.log('PASS: '+layouts.length+' decimal layouts, keyboard/reset/reveal/focus/storage, '+paths+' chapter paths, '+practicePaths+' practice paths and 100 mapped worksheet answers.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
