'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/brain-movement')),topic='bio_2_gehirn_bewegung';
const keys={"bio_2_gehirn_bewegung_s1":1,"bio_2_gehirn_bewegung_d1":2,"bio_2_gehirn_bewegung_s2":0,"bio_2_gehirn_bewegung_d2":1,"bio_2_gehirn_bewegung_s3":2,"bio_2_gehirn_bewegung_d3":0,"bio_2_gehirn_bewegung_d5":1,"bio_2_gehirn_bewegung_s4":2,"bio_2_gehirn_bewegung_d4":0,"bio_2_gehirn_bewegung_accuracy":1,"bio_2_gehirn_bewegung_s5":1,"bio_2_gehirn_bewegung_plan":2};
const cases={pressure:'sensory',command:'motor',correction:'both',unclear:'unknown'};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-movement-lab]')?.dataset.initialized==='true');const store=await p.evaluate(()=>JSON.stringify(localStorage)),select=p.locator('[data-movement-case]'),check=p.locator('[data-movement-check]'),feedback=p.locator('[data-movement-feedback]');
 await check.click();assert.match(await feedback.textContent(),/zuerst/);let decisions=0;
 for(const [kind,correct]of Object.entries(cases)){await select.selectOption(kind);assert.equal(await p.locator('[data-movement-lab] input:checked').count(),0);assert.equal(await feedback.textContent(),'');for(const choice of Object.values(cases)){await p.locator(`[data-movement-lab] input[value="${choice}"]`).check();assert.match(await feedback.textContent(),/geändert/);await check.focus();await p.keyboard.press('Enter');assert.equal((await feedback.textContent()).startsWith('Richtig.'),choice===correct);assert.equal(await check.evaluate(e=>e===document.activeElement),true);decisions++;}}
 for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});await p.evaluate(dark=>{if(dark)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);for(const kind of Object.keys(cases)){await select.selectOption(kind);await p.locator(`[data-movement-lab] input[value="${cases[kind]}"]`).check();await check.click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.ok((await check.boundingBox()).height>=44);assert.ok((await select.boundingBox()).height>=44);for(const label of await p.locator('[data-movement-lab] fieldset label').all())assert.ok((await label.boundingBox()).height>=44);layouts.push({dark,width,kind});}if(width===390){await p.locator('[data-movement-lab]').screenshot({path:path.join(out,'relations-'+(dark?'dark':'light')+'.png')});await p.locator('.movement-pathway').screenshot({path:path.join(out,'profile-'+(dark?'dark':'light')+'.png')});await p.locator('.movement-data').screenshot({path:path.join(out,'data-'+(dark?'dark':'light')+'.png')});await p.locator('.movement-plan').screenshot({path:path.join(out,'plan-'+(dark?'dark':'light')+'.png')});}}
 await p.locator('[data-movement-reset]').focus();await p.keyboard.press('Enter');assert.equal(await select.inputValue(),'pressure');assert.equal(await select.evaluate(e=>e===document.activeElement),true);assert.equal(await feedback.textContent(),'');await p.keyboard.press('ArrowDown');assert.equal(await select.inputValue(),'command');await p.locator('[data-movement-lab] input[value="sensory"]').focus();await p.keyboard.press('ArrowDown');assert.equal(await p.locator('[data-movement-lab] input[value="motor"]').isChecked(),true);await check.focus();await p.keyboard.press('Enter');assert.match(await feedback.textContent(),/^Richtig/);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),store);
 let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:92);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-movement-paper] .movement-material').count(),4);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-movement-solution]').count(),5);await paper.pdf({path:path.join(out,'brain-movement-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),answers,decisions,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 16 relation answers, 24 layout states, keyboard/reset/focus/storage, 36 native quiz answers and paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
