'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/round-bodies')),keys=vm.runInNewContext('('+fs.readFileSync(path.join(__dirname,'test_round_bodies.js'),'utf8').match(/const keys=(\{[^;]+\});/)[1]+')');
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{const p=await b.newPage({viewport:{width:390,height:1400}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic=math4_6_koerper');await p.waitForFunction(()=>document.querySelector('[data-round-inverse]')?.dataset.bound==='true');const saved=await p.evaluate(()=>JSON.stringify(localStorage)),modes=['cylinder_h','cylinder_r','cylinder_surface','cone_h','cone_r','cone_surface'];let inverse=0,mass=0,paths=0;
 for(const mode of modes)for(let i=0;i<6;i++){await p.locator('#round-mode').selectOption(mode);await p.locator('#round-case').selectOption(String(i));const [r,h]=[[3,4],[5,12],[8,15],[6,8],[10,24],[16,30]][i];await p.locator('#round-answer').fill(String(mode.endsWith('_r')?r:h));await p.locator('#round-answer').press('Enter');assert.match(await p.locator('#round-status').textContent(),/^Richtig/);inverse++;}
 const models=[];for(const shape of ['cylinder','cone'])for(const r of [2,3,5])for(const h of [6,12])for(let material=0;material<3;material++)for(const target of ['mass','density']){const values={shape,r,h,material,target};models.push(values);for(const [k,v]of Object.entries(values))await p.locator('#mass-'+k).selectOption(String(v));const rho=[.5,1.2,2.7][material],expected=target==='mass'?Math.PI*r*r*h/(shape==='cone'?3:1)*rho:rho;await p.locator('#mass-answer').fill(expected.toFixed(2).replace('.',','));await p.locator('#mass-answer').press('Enter');assert.match(await p.locator('#mass-status').textContent(),/^Richtig/);mass++;}
 for(const prefix of ['round','mass']){await p.locator('#'+prefix+'-answer').fill('ungültig');await p.locator('[data-'+prefix+'-check]').click();assert.equal(await p.evaluate(()=>document.activeElement.id),prefix+'-answer');await p.locator('[data-'+prefix+'-reset]').click();assert.equal(await p.evaluate(()=>document.activeElement.id),prefix==='round'?'round-mode':'mass-shape');}await p.locator('#round-mode').press('ArrowDown');assert.equal(await p.locator('#round-mode').inputValue(),'cylinder_r');await p.locator('[data-round-reset]').click();await p.locator('#cyl_v').fill('200');await p.locator('#cyl_v').press('Enter');assert.match(await p.locator('#koerper_feedback').textContent(),/^Richtig/);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);console.log('PASS: 36 native inverse and 72 mass/density answers; keyboard/focus/reset/storage.');
 for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:1500});await p.evaluate(d=>document.documentElement.setAttribute('data-theme',d?'dark':'light'),dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);await p.waitForTimeout(350);
  for(const mode of modes)for(let i=0;i<6;i++){await p.evaluate(({mode,i})=>{const a=document.getElementById('round-mode'),c=document.getElementById('round-case');a.value=mode;c.value=String(i);c.dispatchEvent(new Event('change'));},{mode,i});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);const bounds=await p.locator('.round-figure svg text').evaluateAll(ns=>ns.map(e=>{const r=e.getBBox(),v=e.ownerSVGElement.viewBox.baseVal;return r.x>=0&&r.y>=0&&r.x+r.width<=v.width&&r.y+r.height<=v.height;}));assert.ok(bounds.every(Boolean));layouts.push({width,dark,mode,case:i});}
  for(const values of models){await p.evaluate(values=>{for(const [k,v]of Object.entries(values))document.getElementById('mass-'+k).value=String(v);document.getElementById('mass-target').dispatchEvent(new Event('change'));},values);await p.locator('[data-mass-show]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);layouts.push({width,dark,...values});}
  await p.locator('[data-round-reset]').click();await p.locator('[data-round-show]').click();await p.locator('[data-mass-reset]').click();await p.locator('[data-mass-show]').click();for(const prefix of ['round-inverse','round-mass'])await p.locator('[data-'+prefix+']').screenshot({path:path.join(out,`${prefix}-${width}-${dark}.png`)});const figures=p.locator('.round-figure svg[data-worksheet-static]');for(let i=0;i<2;i++){await figures.nth(i).evaluate(e=>e.scrollIntoView({block:'center'}));await figures.nth(i).screenshot({path:path.join(out,`figure-${i}-${width}-${dark}.png`)});}
 }console.log('PASS: 648 layout cases.');
 const questions=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,length:q.answers.length})));for(const[i,q]of questions.entries())for(let choice=0;choice<q.length;choice++){if(!paths)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,i})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==i)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,i});await p.locator(`input[name="chapter_q_${i}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(()=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results')).math4_6_koerper);assert.equal(r.lastPercent,choice===keys[q.id]?100:94);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);paths++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic=math4_6_koerper');await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('[data-round-generated-answer]').count(),8);await paper.pdf({path:path.join(out,'round-bodies-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),inverse,mass,paths,layouts,errors},null,2));console.log('PASS: 48 quiz answer paths and worksheet export.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
