'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/root-rules')),topic='math4_1_reelle_zahlen';
const keys={m41_q1:0,m41_q2:0,m41_periodic:0,m41_bounds:0,m41_round:0,m41_equation:0,m41_sum:0,m41_dip1:0,m41_product:1,m41_quotient:2,m41_domain:0,m41_square:1,m41_cube_volume:2,m41_cube_negative:0,m41_cube_approx:1,m41_early:2,m41_area_error:0,m41_precision:1};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-root-rounding]')?.dataset.bound==='true');const saved=await p.evaluate(()=>JSON.stringify(localStorage)),lab=p.locator('[data-root-rounding]');let models=0;
 for(const area of [2,3,5,10,50])for(const digits of [0,1,2,3,4]){await p.locator('#root-area').selectOption(String(area));await p.locator('#root-digits').selectOption(String(digits));for(const method of ['early','late']){await p.locator('#root-method').selectOption(method);const side=Math.sqrt(area),rounded=Math.round(side*10**digits)/10**digits,expected=4*(method==='early'?rounded:side);await p.locator('#root-answer').fill(expected.toFixed(2).replace('.',','));await p.locator('#root-answer').press('Enter');assert.match(await p.locator('#root-round-status').textContent(),/^Richtig\./);assert.equal(await lab.locator('[data-root-row]').count(),2);models++;}}
 await p.locator('#root-answer').fill('kein Wert');await lab.locator('[data-root-check]').click();assert.equal(await p.locator('#root-answer').getAttribute('aria-invalid'),'true');await lab.locator('[data-root-reset]').click();assert.equal(await p.locator('#root-area').evaluate(e=>e===document.activeElement),true);
 // Tab through all workshop controls in their visible order.
 for(const id of ['root-digits','root-method','root-answer']){await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.id),id);}await p.locator('#root-answer').fill('5,64');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.hasAttribute('data-root-check')),true);await p.keyboard.press('Enter');assert.match(await p.locator('#root-round-status').textContent(),/^Richtig\./);
 await p.locator('#root1').fill('5');await p.locator('#root1').press('Enter');assert.match(await p.locator('#feedback1').textContent(),/^Richtig!/);await p.locator('#root_estimate').fill('1.414');await p.locator('#root_estimate').dispatchEvent('input');assert.match(await p.locator('#root_estimate_result').textContent(),/unter √2/);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:1300});await p.evaluate(d=>document.documentElement.setAttribute('data-theme',d?'dark':'light'),dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const area of [2,3,5,10,50])for(const digits of [0,1,2,3,4]){await p.locator('#root-area').selectOption(String(area));await p.locator('#root-digits').selectOption(String(digits));await lab.locator('[data-root-show]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await lab.locator('[data-root-comparison]').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);layouts.push({width,dark,area,digits});}
  await p.locator('#root-area').selectOption('2');await p.locator('#root-digits').selectOption('2');await lab.locator('[data-root-show]').click();await lab.screenshot({path:path.join(out,`lab-${width}-${dark?'dark':'light'}.png`)});await p.locator('.root-line').screenshot({path:path.join(out,`number-line-${width}-${dark?'dark':'light'}.png`)});
  const styles=await p.locator('#root-area').evaluate(e=>({color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}));assert.notEqual(styles.color,styles.background);
  const labelBoxes=await p.locator('.root-line svg text').evaluateAll(nodes=>nodes.map(e=>{const box=e.getBBox();return{font:parseFloat(getComputedStyle(e).fontSize)*e.getScreenCTM().a,left:box.x,right:box.x+box.width,top:box.y,bottom:box.y+box.height};}));assert.ok(labelBoxes.every(s=>s.font>=12&&s.left>=0&&s.right<=440&&s.top>=0&&s.bottom<=130));
 }
 console.log('PASS: 50 native calculations, 150 layouts, keyboard/focus/storage; checking 53 quiz answers.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,length:q.answers.length})));assert.equal(qs.length,18);let answers=0;
 for(const[index,q]of qs.entries())for(let choice=0;choice<q.length;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[q.id];assert.equal(result.lastPercent,right?100:94);assert.deepEqual(result.reviewQuestionIds,right?[]:[q.id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.root-line svg').count(),1);assert.equal(await paper.locator('.root-paper').count(),3);assert.equal(await paper.locator('[data-root-tasks] li').count(),11);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-root-solution]').count(),4);assert.equal(await paper.locator('#ws-solutions [data-root-generated-answer]').count(),8);
 await paper.pdf({path:path.join(out,'root-rules-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),models,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 50 calculations, 150 layouts, 53 quiz answers; worksheet with solutions exported.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
