const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/physics-year2'));
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));
 for(const [topic,keys,count,selector]of [['optik1',{o1_visibility:1,o1_light_time:2},21,'[data-visibility-transfer]'],['akustik',{ak_receiver:2},22,'[data-hearing-receiver]']]){
  await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(n=>window.currentChapterQuiz?.questions.length===n,count);await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});
  for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:1000});await p.evaluate(d=>document.documentElement.dataset.theme=d?'dark':'light',dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await p.locator(selector).evaluate(e=>e.scrollWidth<=e.clientWidth+1));if(width!==390){await p.locator(selector).evaluate(e=>{e.scrollIntoView({block:'start',behavior:'instant'});scrollBy(0,-85);});await p.screenshot({path:path.join(out,topic+'-'+width+'-'+(dark?'dark':'light')+'.png')});}}
  const stored=await p.evaluate(()=>JSON.stringify(localStorage)),questions=await p.evaluate(keys=>currentChapterQuiz.questions.filter(q=>q.id in keys),keys);
  for(const q of questions){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [a,choice]of q.answers.entries()){const b=box.getByRole('button',{name:choice.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),a===keys[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(choice.feedback));practiceAnswers++;}}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
  const summary=p.locator(selector+' details>summary');await summary.focus();await p.keyboard.press('Enter');assert.equal(await p.locator(selector+' details').evaluate(e=>e.open),true);await p.keyboard.press('Enter');
  for(const q of questions)for(let a=0;a<3;a++){
   if(await p.locator('#chapter-quiz-launch').isVisible())await p.locator('#chapter-quiz-launch').click();if(await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').isVisible())await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();
   const n=await p.evaluate(id=>currentChapterQuiz.questions.findIndex(q=>q.id===id),q.id);await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${q.id in keys?keys[q.id]:q.answers.findIndex(a=>a.correct)}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(r.lastPercent,a===keys[q.id]?100:95);assert.equal(r.contentRevision,5);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);if(a!==keys[q.id]){await p.locator('#chapter-quiz-result button[onclick="reviewChapterSection(0)"]').click();assert.ok(await p.locator('[data-chapter-section="0"] h2').evaluate(e=>e===document.activeElement));}answers++;
  }
  await p.goto(base+'/topics/worksheet.html?topic='+topic);await p.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await p.locator('#ws-solutions').isVisible(),false);assert.equal(await p.locator('#ws-content>.question-block').count(),count);await p.locator('#ws-include-solutions').check();await p.pdf({path:path.join(out,topic+'-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});console.log('Checked '+topic);
 }
 await p.goto(base+'/topics/learning.html?mode=teach&plan=akustik,optik1');await p.waitForFunction(()=>document.querySelectorAll('#chapters .chapter').length>0);await p.locator('#subject').selectOption('physik');await p.locator('#grade').selectOption('6');assert.deepEqual(await p.locator('#chapters [data-focus-key^="catalog-open-"]').evaluateAll(es=>es.map(e=>e.dataset.focusKey.slice(13))),['sieinheiten','optik1','erde_mond_sonne','linsen_spiegel','farben','akustik']);assert.deepEqual(await p.locator('#selected [data-focus-key^="plan-open-"]').evaluateAll(es=>es.map(e=>e.dataset.focusKey.slice(10))),['akustik','optik1']);assert.deepEqual(errors,[]);
 const report={time:new Date().toISOString(),answers,practiceAnswers,layouts:12,keyboard:true,catalogOrder:true,assignedPlanUnchanged:true,errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log('PASS '+JSON.stringify(report));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
