const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/workplace-action')),topic='dgb6_handeln';
const keys=require('./fixtures/dgb6_action_keys.json'),cases={system:[1,2],transfer:[0,2],participation:[1,0],balance:[2,1]};
const chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic];
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];let decisions=0,answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.locator('#chapter-quiz-launch').waitFor();const stored=await p.evaluate(()=>JSON.stringify(localStorage));
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  for(const [name,expected]of Object.entries(cases)){
   const lab=p.locator('[data-action-lab="'+name+'"]'),select=lab.locator('select'),status=lab.locator('[role=status]');
   for(let n=0;n<2;n++){await select.selectOption(String(n));const card=lab.locator('[data-boundary-case]').nth(n);assert.equal(await card.isVisible(),true);for(let a=0;a<3;a++){const b=card.locator('button').nth(a);await b.focus();await p.keyboard.press('Enter');assert.equal((await status.textContent()).startsWith('Richtig:'),a===expected[n]);assert.equal(await b.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);decisions++;}}
   await lab.locator('[data-boundary-reset]').focus();await p.keyboard.press('Enter');assert.equal(await select.inputValue(),'0');assert.equal(await select.evaluate(e=>e===document.activeElement),true);
  }
  if(width===320){await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});for(const [name,selector]of [['system','[data-action-system]'],['council','[data-action-council]'],['decision','[data-action-lab="transfer"]']]){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png'),animations:'disabled'});}}
 }
 // Follow the chapter's keyboard task: select a different case, Tab to an answer, Enter, reset.
 const access=p.locator('[data-action-lab="participation"]');await access.locator('select').focus();await p.keyboard.press('ArrowDown');assert.equal(await access.locator('select').inputValue(),'1');await p.keyboard.press('Tab');assert.equal(await access.locator('[data-boundary-case]').nth(1).getByRole('button').first().evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Enter');assert.match(await access.locator('[role=status]').innerText(),/^Richtig:/);
 for(const q of chapter.sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly)){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [n,a]of q.answers.entries()){const b=box.getByRole('button',{name:a.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),n==={dgb6_handeln_p1:2,dgb6_handeln_p2:1,dgb6_handeln_p3:0}[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));practiceAnswers++;}}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
 const downloadPromise=p.waitForEvent('download');await p.locator('[data-action-download]').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'datenaustausch-probe.txt');const target=path.join(out,download.suggestedFilename());await download.saveAs(target);assert.equal(fs.readFileSync(target,'utf8'),fs.readFileSync(path.join(__dirname,'../examples/datenaustausch-probe.txt'),'utf8'));
 const questions=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(questions,Object.keys(keys));
 for(const [n,id]of questions.entries())for(let a=0;a<3;a++){
  if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();
  await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();
  const result=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(result.lastPercent,a===keys[id]?100:88);assert.equal(result.contentRevision,1);assert.deepEqual(result.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;
 }
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('[data-action-paper] .ai-paper-case').count(),8);assert.equal(await paper.locator('#ws-dgb-material [data-action-solution]').count(),0);await paper.locator('#ws-include-solutions').check();await paper.pdf({path:path.join(out,'dgb6_handeln-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(decisions,144);assert.equal(answers,24);assert.equal(practiceAnswers,9);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),decisions,answers,practiceAnswers,chapterLayouts:6,keyboardSelection:true,resetAndFocus:true,workshopStorageUnchanged:true,downloadVerified:true,errors},null,2));console.log('PASS: 144 case decisions, 24 quiz answers, nine free answers, six layouts, native select/Tab/Enter/reset, unchanged workshop storage, text file download and worksheet export.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
