const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/handeln-system-help')),topic='dgb5_handeln',keys=require('./fixtures/dgb5_handeln_keys.json'),chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic];
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let decisions=0,answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-handeln-cases] [role=status]')?.textContent.includes('Lies die Beobachtung'));const stored=await p.evaluate(()=>JSON.stringify(localStorage));await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  const lab=p.locator('[data-handeln-cases]');for(const [i,key]of [1,0,2,1].entries()){
   await lab.locator('select').selectOption(String(i));assert.equal(await lab.locator('[data-boundary-case]:visible').count(),1);assert.match(await lab.locator('[role=status]').innerText(),/Lies die Beobachtung/);
   for(let a=0;a<3;a++){const b=lab.locator('[data-boundary-case]').nth(i).getByRole('button').nth(a);await b.focus();await p.keyboard.press('Enter');assert.equal((await lab.locator('[role=status]').innerText()).startsWith('Richtig:'),a===key);decisions++;}
  }
  await lab.locator('[data-boundary-reset]').click();assert.equal(await lab.locator('select').evaluate(e=>e===document.activeElement),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  for(const selector of ['[data-computer-parts]','[data-os-functions]','[data-help-protocol]','[data-writing-change]']){const table=p.locator(selector);assert.equal(await table.getAttribute('role'),'table');assert.deepEqual(await table.locator('caption,tbody th,tbody td').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.textContent)),[]);assert.ok(await table.locator('caption').evaluate(e=>e.getBoundingClientRect().width>100));}
  assert.deepEqual(await p.locator('[data-system-map]>div,[data-help-example],[data-history-evidence],[data-handeln-cases] button').evaluateAll(es=>es.filter(e=>!e.closest('[hidden]')).filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.textContent)),[]);
  if(width===320||width===1280)for(const [name,selector]of [['system','[data-system-map]'],['case','[data-handeln-cases]'],['help','[data-help-example]'],['protocol','[data-help-protocol]'],['history','[data-history-evidence]'],['change','[data-writing-change]']]){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.screenshot({path:path.join(out,`${name}-${width}-${dark?'dark':'light'}.png`),animations:'disabled'});}
 }
 for(const [j,q]of chapter.sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).entries()){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [i,a]of q.answers.entries()){const b=box.getByRole('button',{name:a.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),i===[2,0,1][j]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));practiceAnswers++;}}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(ids,Object.keys(keys));
 for(const [n,id]of ids.entries())for(let a=0;a<3;a++){if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(result.lastPercent,a===keys[id]?100:89);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;}
 await p.goto(base+'/topics/worksheet.html?topic='+topic);await p.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await p.locator('#ws-solutions').isVisible(),false);assert.equal(await p.locator('[data-handeln-paper] .ai-paper-case').count(),4);assert.equal(await p.locator('[data-help-protocol] tbody tr').count(),4);assert.equal(await p.locator('#ws-solutions .ws-paper-solution').count(),5);assert.equal(await p.locator('#ws-content>.question-block').count(),9);await p.locator('#ws-include-solutions').check();await p.pdf({path:path.join(out,'dgb5_handeln-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(decisions,72);assert.equal(answers,27);assert.equal(practiceAnswers,9);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),decisions,answers,practiceAnswers,layouts:6,keyboardAndFocus:true,workshopStorageUnchanged:true,tableCellsWithinViewport:true,errors},null,2));console.log('PASS: 72 native observation choices, 27 quiz answers, nine practice answers, six layouts, keyboard/focus, unchanged practice storage and chapter PDF.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
