'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/statistics-year3')),topic='math3_11_statistik';
const keys={m311_q1:0,m311_q2:0,m311_q3:0,m311_zero:0,m311_equal:0,m311_dip1:0,m311_dip2:0,m311_axis_change:1,m311_axis_picture:2,m311_compare_groups:0,m311_laplace:1,m311_bag:2,m311_complement:0,m311_empirical:1,m311_prediction:2,m311_estimate:0};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-stat3-chance]')?.dataset.ready==='true');const saved=await p.evaluate(()=>JSON.stringify(localStorage)),lab=p.locator('[data-stat3-chance]'),select=p.locator('#stat3-model'),axis=p.locator('[data-stat3-axis]');
 const models={six:{size:6,win:[6],p:1/6},even:{size:6,win:[2,4,6],p:.5},coin:{size:2,win:[1],p:.5},bag:{size:4,win:[1,2,3],p:.75}};let controlled=0;
 for(const [name,m]of Object.entries(models)){await select.selectOption(name);await p.evaluate(size=>{window.originalStatRandom=Math.random;let i=0;Math.random=()=>((i++%size)+.5)/size;},m.size);for(const n of [1,10,100]){await lab.locator(`[data-stat3-run="${n}"]`).click();const total=Number(await lab.getAttribute('data-total')),expected=Array.from({length:total},(_,i)=>i%m.size+1).filter(v=>m.win.includes(v)).length;assert.equal(Number(await lab.getAttribute('data-hits')),expected);assert.equal(Number(await lab.locator('[data-stat3-theory]').getAttribute('y1')),220-m.p*160);controlled++;}await p.evaluate(()=>{Math.random=window.originalStatRandom;delete window.originalStatRandom;});await lab.locator('[data-stat3-reset]').click();assert.equal(await select.evaluate(e=>e===document.activeElement),true);assert.equal(await lab.getAttribute('data-total'),'0');}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const width of [320,390,1280])for(const dark of [false,true]){await p.setViewportSize({width,height:900});await p.evaluate(d=>document.documentElement.setAttribute('data-theme',d?'dark':'light'),dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const start of ['0','30']){await axis.locator('select').selectOption(start);const bars=await axis.locator('[data-stat3-bar]').evaluateAll(nodes=>nodes.map(e=>+e.getAttribute('height')));assert.ok(Math.abs(bars[1]/bars[0]-(start==='0'?1.25:2))<1e-10);if(width===320)await axis.screenshot({path:path.join(out,`axis-${start}-${dark?'dark':'light'}.png`)});}
  for(const name of Object.keys(models)){await select.selectOption(name);await lab.locator('[data-stat3-run="100"]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await lab.locator('[data-stat3-chance-table]').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);const bounds=await lab.locator('svg text').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBBox();return[r.x,r.y,r.x+r.width,r.y+r.height];}));assert.ok(bounds.every(r=>r[0]>=0&&r[1]>=0&&r[2]<=360&&r[3]<=280));layouts.push({width,dark,name});if(width===320&&['six','bag'].includes(name))await lab.screenshot({path:path.join(out,`chance-${name}-${dark?'dark':'light'}.png`)});}
  if(width===320){await p.locator('.stat3-table').screenshot({path:path.join(out,`models-${dark?'dark':'light'}.png`)});await p.locator('.stat3-figure').first().screenshot({path:path.join(out,`figure-${dark?'dark':'light'}.png`)});const plot=lab.locator('[data-stat3-chance-plot]');await plot.focus();await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('[data-stat3-chance-plot]').scrollLeft>0);}
 }
 console.log('PASS: 12 controlled native batches, 24 model layouts, 12 axis layouts and keyboard; starting 43 graded answers.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,length:q.answers.length})));assert.equal(qs.length,16);let answers=0;for(const[index,q]of qs.entries())for(let choice=0;choice<q.length;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[q.id];assert.equal(r.lastPercent,right?100:94);assert.deepEqual(r.reviewQuestionIds,right?[]:[q.id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.stat3-figure svg').count(),2);assert.equal(await paper.locator('.stat3-paper').count(),2);assert.equal(await paper.locator('[data-stat3-tasks] li').count(),9);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-stat3-generated-answer]').count(),6);assert.equal(await paper.locator('#ws-solutions [data-stat3-solution]').count(),3);await paper.pdf({path:path.join(out,'statistics-year3-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),controlled,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 12 controlled batches, 36 layouts, 43 graded answers and optional worksheet solutions; PDF exported.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
