const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(__dirname,'../../browser-qa/equations-year3'),id='math3_3_gleichungen';
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const answers={m33_q1:0,m33_q2:0,m33_dip1:0,m33_twosteps:0,m33_expand:1,m33_negative:2,m33_check:0,m33_both:1,m33_route:2,m33_denominator:1,m33_fraction:2,m33_cost_compare:0,m33_formula_height:2,m33_none:0,m33_all:1};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===15&&document.querySelector('[data-equation3-lab]')?.dataset.bound==='true');
  assert.equal(await page.locator('[data-equation3-tasks]>li').count(),18);let paths=0;
  for(const q of source.sections.flatMap(s=>s.quizzes))for(const[i,a]of q.answers.entries()){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:a.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===answers[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==answers[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));paths++;
  }
  const saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),lab=page.locator('[data-equation3-lab]'),task=lab.locator('[data-equation3-task]'),op=lab.locator('[data-equation3-operation]'),input=lab.locator('input'),feedback=lab.locator('[role=status]'),current=lab.locator('[data-equation3-current]');
  async function keyboardSelect(locator,index){await locator.focus();await page.keyboard.press('Home');for(let i=0;i<index;i++)await page.keyboard.press('ArrowDown');}
  async function step(operation,value){await keyboardSelect(op,['add','subtract','addx','subtractx','multiply','divide'].indexOf(operation));assert.equal(await op.inputValue(),operation);await input.fill(String(value));await input.press('Enter');}
  const routes=[{task:0,steps:[['subtractx',2],['subtract',4]],text:'x = 5',probe:19},{task:0,steps:[['subtractx',3],['subtract',9],['divide',-1]],text:'5 = x',probe:19},{task:1,steps:[['subtractx',1],['add',6]],text:'x = 10',probe:14},{task:2,steps:[['subtract',5],['divide',-2]],text:'x = −3',probe:11},{task:3,steps:[['multiply',3],['subtract',2]],text:'x = 10',probe:4},{task:4,steps:[['subtractx',2]],text:'2 = 2',message:'Alle rationalen Zahlen'},{task:5,steps:[['subtractx',2]],text:'1 = 4',message:'keine Lösung'}];
  for(const route of routes){await keyboardSelect(task,route.task);assert.equal(await task.inputValue(),String(route.task));await lab.locator('[data-equation3-reset]').click();assert.equal(await op.evaluate(e=>e===document.activeElement),true);for(const args of route.steps)await step(...args);assert.equal(await current.innerText(),route.text);assert.ok((await feedback.innerText()).includes(route.message||'links '+route.probe+', rechts '+route.probe));assert.equal(await lab.locator('[data-equation3-history]>li').count(),route.steps.length);}
  await task.selectOption('0');const initial=await lab.getAttribute('data-linear-state');for(const operation of ['multiply','divide']){await step(operation,0);assert.equal(await lab.getAttribute('data-linear-state'),initial);assert.equal(await lab.locator('[data-equation3-history]>li').count(),0);assert.ok((await feedback.innerText()).includes(operation==='divide'?'nicht definiert':'Lösungsmenge verändern'));}
  for(const bad of ['','1/0','1e2','2x']){await input.fill(bad);await input.press('Enter');assert.equal(await input.getAttribute('aria-invalid'),'true');assert.equal(await lab.getAttribute('data-linear-state'),initial);}
  await step('add','1/3');assert.equal(await current.innerText(),'3x + 13/3 = 2x + 28/3');await lab.locator('[data-equation3-undo]').click();assert.equal(await lab.getAttribute('data-linear-state'),initial);assert.equal(await lab.locator('[data-equation3-apply]').evaluate(e=>e===document.activeElement),true);await step('add','−0,5');assert.equal(await current.innerText(),'3x + 7/2 = 2x + 17/2');await lab.locator('[data-equation3-reset]').click();assert.equal(await task.inputValue(),'0');assert.equal(await op.evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('.equation3-lab h3')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(let i=0;i<6;i++){await task.selectOption(String(i));const route=routes.find(r=>r.task===i);for(const args of route.steps)await step(...args);const geometry=await lab.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('select,input,button')].map(b=>{const x=b.getBoundingClientRect();return {left:x.left,right:x.right,height:x.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow,JSON.stringify({width,theme,i,geometry}));assert.ok(geometry.controls.every(b=>b.left>=geometry.left&&b.right<=geometry.right+1&&b.height>=44));layouts.push({width,theme,case:i,geometry});if(width===390&&i===2)await lab.screenshot({path:path.join(out,'negative-'+theme+'.png')});}
   const labels=await page.locator('[data-equation3-tiles]').evaluate(e=>[...e.querySelectorAll('text')].map(t=>{const b=t.getBBox();return {text:t.textContent,x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height};}));assert.ok(labels.every(b=>b.x>=0&&b.right<=340&&b.y>=0&&b.bottom<=240),JSON.stringify(labels));if(width===390)await page.locator('[data-equation3-tiles]').screenshot({path:path.join(out,'tiles-'+theme+'.png')});
  }
  const attempts=[];for(const[wrong,section]of [['m33_route',2],['m33_none',5]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const[i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(answers[q]+1)%3:answers[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,93);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),15);assert.equal(await paper.locator('[data-equation3-paper-history] tbody tr').count(),5);assert.equal(await paper.locator('[data-equation3-paper-cases]>li').count(),6);assert.equal(await paper.locator('#ws-math-material svg').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('.ws-generated-equation-solution').first().isVisible(),false);
  const generated=await paper.locator('[data-generated-equation3]').evaluateAll(nodes=>nodes.map(e=>({a:Number(e.dataset.a),b:Number(e.dataset.b),c:Number(e.dataset.c),d:Number(e.dataset.d),text:e.textContent})));assert.equal(generated.length,8);
  await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('.ws-paper-solution').count(),6);const generatedAnswers=await paper.locator('#ws-solutions .ws-generated-equation-solution').evaluateAll(nodes=>nodes.map(e=>({x:Number(e.dataset.generatedAnswer),text:e.textContent})));assert.equal(generatedAnswers.length,8);for(let i=0;i<8;i++){const {a,b,c,d}=generated[i],{x,text}=generatedAnswers[i];assert.equal((d-b)/(a-c),x);assert.equal(a*x+b,c*x+d);assert.ok(text.includes('links '+a+' · ('+x+') + '+b+' = '+(a*x+b)));assert.ok(text.includes('rechts '+c+' · ('+x+') + ('+d+') = '+(c*x+d)));}
  await paper.locator('#ws-include-solutions').uncheck();assert.equal(await paper.locator('.ws-generated-equation-solution').first().isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.deepEqual(await paper.locator('[data-generated-equation3]').allTextContents(),generated.map(x=>x.text));await paper.pdf({path:path.join(out,'equations-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),paths,routes,layouts,attempts,generated,generatedAnswers,errors,scope:'45 native quiz answers, seven keyboard solution routes, zero/invalid/fraction inputs, undo/reset, 36 layouts plus SVG bounds, two 93% checks and worksheet export. PDF visual review separate; no full curriculum or classroom acceptance.'},null,2)+'\n');console.log('PASS: year-three equations native: 45 quiz answers, seven keyboard routes, inputs/undo/reset/no storage, 36 layouts/diagram bounds, two 93% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
