const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/communication-media')),topic='dgb6_kommunikation',keys=require('./fixtures/dgb6_communication_keys.json');
const cases={channels:[1,0],business:[2,1],framing:[0,2]},chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic];
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];let decisions=0,answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>window.currentChapterQuiz?.questions.length===10);await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});const stored=await p.evaluate(()=>JSON.stringify(localStorage));
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const [name,expected]of Object.entries(cases)){
   const zone=p.locator('[data-communication-lab="'+name+'"]'),select=zone.locator('select');for(const [n,key]of expected.entries()){
    await select.selectOption(String(n));const card=zone.locator('[data-boundary-case]').nth(n);assert.equal(await card.isVisible(),true);for(let a=0;a<3;a++){const button=card.locator('button').nth(a);await button.focus();await p.keyboard.press('Enter');assert.equal((await zone.locator('[role=status]').innerText()).startsWith('Richtig:'),a===key);assert.equal(await button.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);decisions++;}
   }
   await zone.locator('[data-boundary-reset]').focus();await p.keyboard.press('Enter');assert.equal(await select.inputValue(),'0');assert.equal(await select.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowDown');assert.equal(await select.inputValue(),'1');await p.keyboard.press('Tab');assert.equal(await zone.locator('[data-boundary-case]').nth(1).locator('button').first().evaluate(e=>e===document.activeElement),true);
  }
  const packet=p.locator('[data-core-experiment="packet-order"]');await packet.locator('[data-packet-reset]').click();for(const n of [3,1,4,2]){await packet.locator('[data-packet-receive="'+n+'"]').focus();await p.keyboard.press('Enter');}assert.equal(await packet.locator('[data-packet-message]').innerText(),'Wir | lernen | heute | gemeinsam.');
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);if(width===320){for(const [name,selector]of [['route','[data-communication-route]'],['channels','[data-communication-lab="channels"]'],['business','[data-communication-lab="business"]'],['framing','[data-communication-lab="framing"]']]){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png'),animations:'disabled'});}}
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
 for(const q of chapter.sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly))for(const a of q.answers){const host=p.locator('.practice-box[data-id="'+q.id+'"]');await host.getByRole('button',{name:a.text,exact:true}).click();assert.ok((await host.innerText()).includes(a.feedback));practiceAnswers++;}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
 const questions=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(questions,Object.keys(keys));
 for(const [n,id]of questions.entries())for(let a=0;a<3;a++){
  if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(result.lastPercent,a===keys[id]?100:90);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;
 }
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('[data-communication-paper] .ai-paper-case').count(),6);assert.equal(await paper.locator('#ws-dgb-material [data-communication-solution]').count(),0);await paper.locator('#ws-include-solutions').check();await paper.pdf({path:path.join(out,'dgb6_kommunikation-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(decisions,108);assert.equal(answers,30);assert.equal(practiceAnswers,9);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),decisions,answers,practiceAnswers,chapterLayouts:6,keyboardSelection:true,resetAndFocus:true,workshopStorageUnchanged:true,packetAssembly:true,errors},null,2));console.log('PASS: 108 native case decisions, 30 assessed answers, nine free answers, six layouts, keyboard/select/reset, packet assembly and worksheet export.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
