'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/area-extensions')),topic='math3_4_flaechensatz';
const keys={area_figure_q0:0,area_figure_q1:0,area_figure_q2:0,area_figure_q3:0,area_figure_q4:0,area_figure_q5:0,area_figure_q6:0,area_figure_q7:0,area_inverse_triangle:1,area_inverse_trapezoid:2,area_inverse_units:0,area_hexagon_radius:1,area_hexagon_area:2,area_hexagon_regular:0};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-area-hex]')?.dataset.initialized==='true');
 const storage=await p.evaluate(()=>JSON.stringify(localStorage)),lab=p.locator('[data-area-hex]'),select=lab.locator('select'),next=lab.locator('[data-area-hex-next]'),prev=lab.locator('[data-area-hex-prev]');let states=0;
 for(const r of ['2','3','4']){await select.selectOption(r);for(let step=0;step<=6;step++){assert.equal(await lab.getAttribute('data-step'),String(step));assert.equal(await lab.locator('[data-hex-side]').count(),step);assert.equal(await next.isDisabled(),step===6);if(step<6){await next.focus();await p.keyboard.press('Enter');}states++;}assert.equal(await prev.evaluate(e=>e===document.activeElement),true);}
 await lab.locator('[data-area-hex-reset]').click();assert.equal(await select.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Home');await p.keyboard.press('ArrowDown');assert.equal(await select.inputValue(),'3');
 const inv=p.locator('[data-area-inverse]'),field=inv.locator('input'),result=inv.locator('[data-area-inverse-result]');
 for(const [type,value] of [['triangle','7'],['trapezoid','5'],['parallelogram','3,5']]){await inv.locator('select').selectOption(type);for(const [text,correct]of [[value,'true'],['2','false']]){await field.fill(text);await field.press('Enter');assert.equal(await result.getAttribute('data-correct'),correct);assert.equal(await result.evaluate(e=>e===document.activeElement),true);}await field.fill('1e2');await field.press('Enter');assert.equal(await field.getAttribute('aria-invalid'),'true');assert.equal(await field.evaluate(e=>e===document.activeElement),true);await field.fill(value);assert.equal(await result.innerText(),'');await field.press('Enter');}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:900});await p.evaluate(dark=>document.documentElement.setAttribute('data-theme',dark?'dark':'light'),dark);
  for(const r of ['2','3','4'])for(const step of [0,1,6]){await select.selectOption(r);for(let i=0;i<step;i++)await next.click();const bounds=await lab.locator('svg text').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBBox();return[r.x,r.y,r.x+r.width,r.y+r.height];}));assert.ok(bounds.every(r=>r[0]>=0&&r[1]>=0&&r[2]<=360&&r[3]<=360));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);layouts.push({width,dark,r,step});}
  if(width===320){for(const step of [1,6]){await select.selectOption('4');for(let i=0;i<step;i++)await next.click();await lab.screenshot({path:path.join(out,`hex-${step}-${dark?'dark':'light'}.jpg`)});}await inv.screenshot({path:path.join(out,`inverse-${dark?'dark':'light'}.jpg`)});await p.locator('.area-hex-figure').screenshot({path:path.join(out,`figure-${dark?'dark':'light'}.jpg`)});}
 }
 console.log('PASS: 21 native construction states, inverse inputs and 54 layouts; starting 42 graded answers.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,14);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[id];assert.equal(r.lastPercent,right?100:93);assert.deepEqual(r.reviewQuestionIds,right?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.area-extension-paper').count(),2);assert.equal(await paper.locator('.area-hex-figure svg').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-area-extension-solution]').count(),2);await paper.pdf({path:path.join(out,'area-extensions-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),states,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: construction, inverse inputs, 54 layouts, keyboard and 42 graded answers; paper exported.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
