const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/optics-research')),topic='linsen_spiegel',keys=require('./fixtures/optics_research_keys.json');
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let answers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>window.currentChapterQuiz?.questions.length===17);await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'page overflow '+width);
  const overflow=await p.locator('[data-optics-source],[data-optics-source-protocol],[data-optics-research-task]').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().right>innerWidth+1||e.scrollWidth>e.clientWidth+1).map(e=>e.textContent.slice(0,50)));assert.deepEqual(overflow,[]);
  if(width===320||width===1280)for(const [name,selector]of [['source','[data-optics-source="B"]'],['tasks','[data-optics-research-task]'],['eye','[data-chapter-section="3"]']]){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.evaluate(()=>scrollBy(0,-85));await p.screenshot({path:path.join(out,`${name}-${width}-${dark?'dark':'light'}.png`),animations:'disabled'});}
 }
 const stored=await p.evaluate(()=>JSON.stringify(localStorage)),summary=p.locator('[data-optics-research-solution]>summary');await summary.focus();await p.keyboard.press('Enter');assert.equal(await p.locator('[data-optics-research-solution]').evaluate(e=>e.open),true);await p.keyboard.press('Enter');assert.equal(await p.locator('[data-optics-research-solution]').evaluate(e=>e.open),false);
 const freeQuestions=await p.evaluate(()=>currentChapterQuiz.questions.filter(q=>q.id.startsWith('optics_')));for(const q of freeQuestions){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [a,choice]of q.answers.entries()){const b=box.getByRole('button',{name:choice.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),a===keys[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(choice.feedback));}}assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
 const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(ids,Object.keys(keys).slice(0,17));for(const [n,id]of ids.entries())for(let a=0;a<3;a++){
  if(await p.locator('#chapter-quiz-launch').isVisible())await p.locator('#chapter-quiz-launch').click();if(await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').isVisible())await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(r.lastPercent,a===keys[id]?100:94);assert.equal(r.contentRevision,8);assert.deepEqual(r.reviewQuestionIds,a===keys[id]?[]:[id]);
  if(a!==keys[id]){const section=await p.evaluate(n=>currentChapterQuiz.questions[n].sectionIndex,n),review=p.locator('#chapter-quiz-result button[onclick="reviewChapterSection('+section+')"]');await review.click();assert.equal(await p.locator('[data-chapter-section="'+section+'"] h2').evaluate(e=>e===document.activeElement),true);}
  answers++;
 }
 await p.goto(base+'/topics/worksheet.html?topic='+topic);await p.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await p.locator('#ws-solutions').isVisible(),false);assert.equal(await p.locator('#ws-content>.question-block').count(),17);assert.equal(await p.locator('#ws-physics-material [data-optics-source]').count(),4);await p.pdf({path:path.join(out,'optics-student.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});await p.locator('#ws-include-solutions').check();await p.pdf({path:path.join(out,'optics-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);
 const report={time:new Date().toISOString(),answers,practiceAnswers:12,layouts:6,keyboardDisclosure:true,reviewLinks:34,errors};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log('PASS '+JSON.stringify(report));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
