'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/geometry-models/worksheet'));
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[];try{
 const p=await b.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{let n=37629;Math.random=()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};});await p.goto(base+'/topics/worksheet.html?topic=math2_7_geometrie');await p.waitForFunction(()=>!document.querySelector('#ws-print').disabled);
 assert.equal(await p.locator('[data-geometry-model-paper]').count(),4);assert.equal(await p.locator('[data-geometry-model-paper] li').count(),11);assert.equal(await p.locator('#ws-math-material svg').count(),14);assert.equal(await p.locator('.prism-paper-figure').count(),4);
 const texts=await p.locator('[data-geometry-model-paper]').allTextContents();assert.ok(texts[0].includes('c = 7 cm')&&texts[0].includes('c = 8 cm'));assert.ok(texts[1].includes('P(3|−2)'));assert.ok(texts[2].includes('A(−2|−1)'));assert.ok(texts[3].includes('4 cm Breite und 3 cm Höhe'));
 await p.locator('#ws-include-solutions').check();assert.equal(await p.locator('.ws-paper-solution').count(),12);assert.equal(await p.locator('[data-geometry-model-solution]').count(),4);
 const generated=await p.locator('[data-quad-generated]').evaluateAll(es=>es.map(e=>({kind:e.dataset.quadGenerated,a:+e.dataset.a,b:+e.dataset.b,c:+e.dataset.c,text:e.textContent}))),answers=await p.locator('[data-quad-answer]').evaluateAll(es=>es.map(e=>({value:+e.dataset.quadAnswer,text:e.textContent})));
 for(let i=0;i<12;i++){const{kind,a,b,c}=generated[i];assert.equal(answers[i].value,kind==='trapezoid'?(a+b)*c/2:kind==='parallelogram'?a*b:a*b/2);}
 const before=await p.locator('[data-quad-generated]').allTextContents();await p.locator('#ws-include-solutions').uncheck();assert.equal(await p.locator('#ws-solutions').isVisible(),false);await p.locator('#ws-include-solutions').check();assert.deepEqual(await p.locator('[data-quad-generated]').allTextContents(),before);
 await p.pdf({path:path.join(out,'geometry-model-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),generated,answers,errors},null,2)+'\n');console.log('PASS: four model alternatives with 11 paper tasks, 14 static figures, 12 solution groups and stable generated answers; PDF exported.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
