'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/encryption-workshop'));
const pass='Probe-Wald-2026!',note='Übungsnotiz: Bibliothek, 14 Uhr. 🔑\n<img src=x onerror=alert(1)>',keys={dgb8_handeln_q3:1,dgb8_system_rights:2,dgb8_handeln_q1:1,dgb8_crypto_integrity:0,dgb8_handeln_q2:2,dgb8_consumer_help:0,dgb8_handeln_q4:2,dgb8_civic_participation:1};
function nodeOpen(file){const b=Buffer.from(file.data,'base64'),k=crypto.pbkdf2Sync(pass,Buffer.from(file.salt,'base64'),600000,32,'sha256'),dec=crypto.createDecipheriv('aes-256-gcm',k,Buffer.from(file.iv,'base64'));dec.setAuthTag(b.subarray(-16));return Buffer.concat([dec.update(b.subarray(0,-16)),dec.final()]).toString('utf8');}
function fixture(text=note){const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),k=crypto.pbkdf2Sync(pass,salt,600000,32,'sha256'),enc=crypto.createCipheriv('aes-256-gcm',k,iv),data=Buffer.concat([enc.update(text,'utf8'),enc.final(),enc.getAuthTag()]);return {format:'sciverse-text-v1',kdf:'PBKDF2-SHA-256',iterations:600000,salt:salt.toString('base64'),iv:iv.toString('base64'),data:data.toString('base64')};}
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[],layouts=[],requests=[];try{
 const context=await browser.newContext({viewport:{width:390,height:900},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await page.goto(base+'/examples/verschluesselungswerkstatt.html');await page.locator('#plain').waitFor();const storage=await page.evaluate(()=>[JSON.stringify(localStorage),JSON.stringify(sessionStorage)]),initialRequests=requests.length;
 const ready=()=>page.waitForFunction(()=>document.querySelector('#status').getAttribute('aria-busy')==='false');
 await page.locator('#plain').fill(note);await page.locator('#encrypt-password').fill(pass);await page.locator('#encrypt').focus();await page.keyboard.press('Enter');await ready();const first=JSON.parse(await page.locator('#encrypted').inputValue());assert.equal(nodeOpen(first),note);assert.equal(await page.locator('#plain').inputValue(),note);
 const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise,filePath=path.join(out,download.suggestedFilename());await download.saveAs(filePath);assert.deepEqual(JSON.parse(fs.readFileSync(filePath,'utf8')),first);assert.equal(fs.readFileSync(filePath,'utf8').includes(pass),false);assert.equal(fs.readFileSync(filePath,'utf8').includes('Bibliothek'),false);
 await page.locator('#encrypt').click();await ready();const second=JSON.parse(await page.locator('#encrypted').inputValue());assert.notEqual(first.salt,second.salt);assert.notEqual(first.iv,second.iv);assert.notEqual(first.data,second.data);assert.equal(nodeOpen(second),note);
 await page.locator('#transfer').click();assert.equal(await page.locator('#decrypt-password').evaluate(e=>e===document.activeElement),true);await page.locator('#decrypt-password').fill(pass);await page.locator('#decrypt').click();await ready();assert.equal(await page.locator('#opened').inputValue(),note);
 assert.equal(requests.length,initialRequests);await page.reload();await page.locator('#plain').waitFor();assert.equal(await page.locator('#cipher').inputValue(),'');assert.equal(await page.locator('#encrypt-password').inputValue(),'');await page.locator('#file').setInputFiles(filePath);await ready();await page.locator('#decrypt-password').fill(pass);await page.locator('#decrypt').click();await ready();assert.equal(await page.locator('#opened').inputValue(),note);
 await page.locator('#decrypt-password').fill('falsches-Passwort');assert.equal(await page.locator('#opened').inputValue(),'');await page.locator('#decrypt').click();await ready();assert.match(await page.locator('#status').textContent(),/Öffnen fehlgeschlagen/);assert.equal(await page.locator('#opened').inputValue(),'');
 await page.locator('#decrypt-password').fill(pass);const tampered={...first,data:(first.data[0]==='A'?'B':'A')+first.data.slice(1)};await page.locator('#cipher').fill(JSON.stringify(tampered));await page.locator('#decrypt').click();await ready();assert.match(await page.locator('#status').textContent(),/Öffnen fehlgeschlagen/);assert.equal(await page.locator('#opened').inputValue(),'');
 await page.locator('#cipher').fill(JSON.stringify(fixture()));await page.locator('#decrypt').click();await ready();assert.equal(await page.locator('#opened').inputValue(),note);assert.equal(await page.locator('#opened img').count(),0);
 for(const text of ['\ufeffNotiz mit führendem Unicode-Zeichen','界'.repeat(1000)]){await page.locator('#cipher').fill(JSON.stringify(fixture(text)));await page.locator('#decrypt').click();await ready();assert.equal(await page.locator('#opened').inputValue(),text);}
 for(const invalid of [{...first,iterations:1e12},{...first,salt:'@@'},{...first,extra:'unexpected'},null,[]]){await page.locator('#cipher').fill(JSON.stringify(invalid));await page.locator('#decrypt').click();await ready();assert.match(await page.locator('#status').textContent(),/Öffnen fehlgeschlagen/);assert.equal(await page.locator('#opened').inputValue(),'');}
 await page.locator('#file').setInputFiles({name:'oversize.json',mimeType:'application/json',buffer:Buffer.alloc(16385,32)});await ready();assert.match(await page.locator('#status').textContent(),/zu groß/);assert.equal(await page.locator('#cipher').inputValue(),'');
 await page.locator('#file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('<html>not a file</html>')});await ready();assert.match(await page.locator('#status').textContent(),/nicht das unterstützte/);
 await page.locator('#plain').fill('');await page.locator('#encrypt-password').fill(pass);await page.locator('#encrypt').click();await ready();assert.match(await page.locator('#status').textContent(),/1 bis 1.000/);await page.locator('#plain').fill('Text');await page.locator('#encrypt-password').fill('kurz');await page.locator('#encrypt').click();await ready();assert.match(await page.locator('#status').textContent(),/8 bis 128/);
 // Deterministically pause the actual browser derivation, reset, then release it.
 await page.evaluate(()=>{window.originalDerive=crypto.subtle.deriveKey.bind(crypto.subtle);crypto.subtle.deriveKey=(...args)=>new Promise(resolve=>{window.releaseDerivation=()=>resolve(window.originalDerive(...args));});});await page.locator('#encrypt-password').fill(pass);await page.locator('#encrypt').click();await page.waitForFunction(()=>!!window.releaseDerivation);await page.locator('#reset').click();assert.equal(await page.locator('#plain').evaluate(e=>e===document.activeElement),true);await page.evaluate(async()=>{window.releaseDerivation();crypto.subtle.deriveKey=window.originalDerive;await new Promise(r=>setTimeout(r,700));});assert.equal(await page.locator('#encrypted').inputValue(),'');assert.match(await page.locator('#status').textContent(),/Arbeitsfelder geleert/);
 await page.locator('#plain').fill('Übungsnotiz: Treffpunkt Bibliothek, 14 Uhr.');
 for(const colorScheme of ['light','dark'])for(const width of [320,390,1280]){await page.emulateMedia({colorScheme});await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const element of await page.locator('input,button').all())assert.ok((await element.boundingBox()).height>=44);layouts.push({surface:'workshop',colorScheme,width});if(width===390)await page.screenshot({path:path.join(out,'workshop-'+colorScheme+'.png'),fullPage:true});}
 assert.deepEqual(await page.evaluate(()=>[JSON.stringify(localStorage),JSON.stringify(sessionStorage)]),storage);
 const unsupported=await context.newPage();await unsupported.addInitScript(()=>Object.defineProperty(window,'isSecureContext',{value:false}));await unsupported.goto(base+'/examples/verschluesselungswerkstatt.html');assert.equal(await unsupported.locator('#encrypt').isDisabled(),true);assert.equal(await unsupported.locator('#decrypt').isDisabled(),true);assert.match(await unsupported.locator('#status').textContent(),/nicht verfügbar/);await unsupported.close();
 await page.goto(base+'/topics/template.html?topic=dgb8_handeln');await page.locator('[data-encryption-link]').waitFor();const popupPromise=page.waitForEvent('popup');await page.locator('[data-encryption-link]').click();const popup=await popupPromise;await popup.waitForLoadState();assert.equal(new URL(popup.url()).pathname,'/examples/verschluesselungswerkstatt.html');await popup.close();
 for(const dark of [false,true])for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});await page.evaluate(dark=>{if(dark)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await page.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);layouts.push({surface:'chapter',dark,width});if(width===390)await page.locator('[data-action-case]').nth(1).locator('..').screenshot({path:path.join(out,'consumer-'+(dark?'dark':'light')+'.png')});}
 const qs=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));let answers=0;for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){if(!answers)await page.locator('#chapter-quiz-launch').click();else await page.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await page.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await page.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await page.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await page.evaluate(()=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results')).dgb8_handeln);assert.equal(r.lastPercent,choice===keys[id]?100:88);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);answers++;}
 const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic=dgb8_handeln');await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-action-solution]').count(),4);await paper.pdf({path:path.join(out,'action-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),independentNodeInteropBothDirections:true,downloadReloadImport:true,wrongPasswordAndTamper:true,randomizedEncryption:true,invalidImports:7,resetDuringDerivation:true,storageUnchanged:true,unsupportedBrowser:true,layouts,answers,errors},null,2));console.log('PASS: real encryption, Node interoperability both ways, download/reload/import, wrong password/tamper, validation, reset during operation, 12 layouts, 24 quiz answers and worksheet export.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
