const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/dgb-learning-guide'));
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch(),errors=[];let choices=0;try{
 const p=await browser.newPage({viewport:{width:390,height:950}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/learning.html?mode=teach&plan=dgb7_information,energie');await p.waitForFunction(()=>document.querySelector('#selected li ul'));const stored=await p.evaluate(()=>JSON.stringify(localStorage)),guide=p.locator('#dgb-guide');
 await guide.locator('summary').focus();await p.keyboard.press('Enter');assert.equal(await guide.evaluate(e=>e.open),true);
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:950});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);
  for(const grade of ['5','6','7','8']){await p.locator('#search').fill('keinKapitelXYZ9473');const b=p.locator('[data-focus-key="dgb-guide-'+grade+'"]');await b.focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#grade').inputValue(),grade);assert.equal(await p.locator('#search').inputValue(),'');assert.equal(await p.locator('#count').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('#chapters>.chapter').count(),grade<'7'?6:5);assert.equal(await guide.evaluate(e=>e.open),true);choices++;}
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(await guide.locator('.guide-stage,button,summary').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.textContent)),[]);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
  if(width===320&&!dark)for(const grade of ['5','6','7','8'])await p.locator('[data-guide-grade="'+grade+'"]').screenshot({path:path.join(out,'year-'+grade+'-320.png')});if(width===1280&&dark)await guide.screenshot({path:path.join(out,'guide-1280-dark.png')});
 }
 for(const mode of ['learn','review','teach']){await p.locator('[data-mode="'+mode+'"]').click();assert.equal(await guide.isVisible(),true);assert.equal(await guide.evaluate(e=>e.open),true);}
 await p.locator('#subject').selectOption('physik');assert.equal(await guide.isVisible(),false);await p.locator('#subject').selectOption('dgb');assert.equal(await guide.isVisible(),true);assert.equal(await guide.evaluate(e=>e.open),true);
 await p.locator('#share').click();assert.match(decodeURIComponent(await p.locator('#share-url').inputValue()),/plan=dgb7_information,energie/);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);
 await p.emulateMedia({media:'print'});assert.equal(await guide.isVisible(),false);await p.pdf({path:path.join(out,'stoffliste.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});await p.emulateMedia({media:'screen'});
 await p.locator('[data-focus-key="dgb-guide-word"]').click();await p.waitForURL('**/index.html#**');assert.match(decodeURIComponent(p.url()),/topic=dgb_word_werkstatt/);assert.match(decodeURIComponent(p.url()),/mode=teach/);assert.match(decodeURIComponent(p.url()),/plan=dgb7_information,energie/);
 assert.equal(choices,24);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),choices,layouts:6,keyboardAndFocus:true,planAndStoragePreserved:true,hiddenInPrintedPlan:true,wordRoutePreservesContext:true,errors},null,2));console.log('PASS: 24 native year choices, six layouts, disclosure and keyboard focus, unchanged study plan/storage, subject/mode changes, print exclusion and contextual Word route.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
