'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/forest-workshop')),topic='bio_2_oekosysteme';
const keys={bio2_wald_s1:1,bio2_wald_d5:2,bio2_wald_s2:0,bio2_wald_d1:2,bio2_wald_s3:1,bio2_wald_s4:0,bio2_wald_d2:2,bio2_wald_d4:1,bio2_wald_puddle:2,bio2_wald_s5:0,bio2_wald_d3:2,bio2_wald_composition:1},samples=[[[18,2,0,0,0],[2,2,2,2,2]],[[10,5,0,0,0],[2,0,3,1,0]],[[5,4,2,0,0],[3,0,2,0,4]]];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelectorAll('[data-sampling-bar]').length===10);const store=await p.evaluate(()=>JSON.stringify(localStorage)),select=p.locator('[data-sampling-round]'),show=p.locator('[data-sampling-show]'),result=p.locator('[data-sampling-result]');
 for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});await p.evaluate(dark=>{if(dark)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(dark=>getComputedStyle(document.body).color===(dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);for(let n=0;n<3;n++){await select.selectOption(String(n));assert.equal(await result.isVisible(),false);await show.focus();await p.keyboard.press('Enter');assert.equal(await result.isVisible(),true);const rows=await p.locator('[data-sampling-rows] tr').evaluateAll(nodes=>nodes.map(r=>[...r.querySelectorAll('td')].map(c=>Number(c.textContent))));assert.deepEqual(rows,samples[n][0].map((v,i)=>[v,samples[n][1][i]]));const widths=await p.locator('[data-sampling-bar]').evaluateAll(nodes=>nodes.map(e=>Number(e.getAttribute('width'))));assert.deepEqual(widths,rows.flat().map(v=>v*12));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.ok((await show.boundingBox()).height>=44);assert.ok((await select.boundingBox()).height>=44);layouts.push({dark,width,round:n});if(width===390&&n===2)await p.locator('[data-habitat-sampling]').screenshot({path:path.join(out,'sampling-'+(dark?'dark':'light')+'.png')});}if(width===390)await p.locator('.forest-profile').screenshot({path:path.join(out,'profile-'+(dark?'dark':'light')+'.png')});}
 await p.locator('[data-sampling-reset]').focus();await p.keyboard.press('Enter');assert.equal(await select.inputValue(),'0');assert.equal(await select.evaluate(e=>e===document.activeElement),true);assert.equal(await result.isVisible(),false);await p.keyboard.press('ArrowDown');assert.equal(await select.inputValue(),'1');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),store);
 let answers=0;const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,n)=>{if(n!==index)document.querySelector(`input[name="chapter_q_${n}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:92);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);answers++;}
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-forest-paper] tbody tr').count(),15);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-forest-solution]').count(),5);await paper.pdf({path:path.join(out,'forest-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),answers,layouts,reset:true,storageUnchanged:true,errors},null,2));console.log('PASS: 18 sampling/layout states, table/bar agreement, keyboard reveal/reset/focus/storage, 36 quiz answers and paper export.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
