const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/wiki-workshop')),sample=require('./fixtures/wiki_sample.json'),fields=Object.keys(sample);
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const context=await browser.newContext({viewport:{width:390,height:900}}),chapter=await context.newPage();await chapter.goto(base+'/topics/template.html?topic=dgb8_information');await chapter.locator('[data-wiki-open]').waitFor();const opening=context.waitForEvent('page');await chapter.locator('[data-wiki-open]').click();const p=await opening;await p.waitForLoadState('domcontentloaded');p.on('pageerror',e=>errors.push(e.message));assert.equal(p.url(),base+'/examples/klassenwiki.html');
 const values=page=>page.evaluate(fields=>Object.fromEntries(fields.map(key=>[key,document.getElementById(key).value])),fields),fill=async(page,v)=>{for(const key of fields)await page.locator('#'+key).fill(v[key]);};
 await fill(p,sample);await p.locator('#compare').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#compare-heading').evaluate(e=>e===document.activeElement),true);assert.match(await p.locator('#compare-count').textContent(),/5 von 5.*nicht richtige Antworten/);
 for(const id of ['check-count','check-limit','check-reader'])await p.locator('#'+id).check();assert.match(await p.locator('#review-state').textContent(),/Selbstprüfung dokumentiert/);await p.locator('#reason').fill(sample.reason+' Erneut gelesen.');assert.equal(await p.locator('input[type=checkbox]:checked').count(),0);assert.equal(await p.locator('#comparison').isVisible(),false);await fill(p,sample);
 for(const dark of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});await p.emulateMedia({colorScheme:dark?'dark':'light'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const selector of ['#preview','#evidence','fieldset','#title','#reason'])assert.equal(await p.locator(selector).first().evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const key of fields)assert.equal(await p.locator('#preview-'+key).textContent(),sample[key]);layouts.push({dark,width});if(width===390)await p.locator('#preview').screenshot({path:path.join(out,'preview-'+(dark?'dark':'light')+'.png')});if(width===320&&!dark)await p.locator('#evidence').screenshot({path:path.join(out,'evidence-320.png')});}
 async function download(page,button,name){const pending=page.waitForEvent('download');await page.locator(button).click();const item=await pending;assert.equal(item.suggestedFilename(),name);const file=path.join(out,name);await item.saveAs(file);return file;}
 const saved=await download(p,'#save','klassenwiki-arbeitsstand.json');assert.deepEqual(JSON.parse(fs.readFileSync(saved,'utf8')).fields,sample);await p.reload();assert.notDeepEqual(await values(p),sample);await p.locator('#load').setInputFiles(saved);await p.locator('#notice').getByText(/Arbeitsstand geladen/).waitFor();assert.deepEqual(await values(p),sample);
 await p.locator('#reset').click();assert.notDeepEqual(await values(p),sample);await p.locator('#undo').focus();await p.keyboard.press('Enter');assert.deepEqual(await values(p),sample);
 await p.locator('#load').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await p.locator('#notice').getByText(/Datei nicht geladen/).waitFor();assert.deepEqual(await values(p),sample);
 const exportFile=await download(p,'#export','klassenwiki-beitrag.html'),readable=await context.newPage();readable.on('pageerror',e=>errors.push(e.message));await readable.goto(pathToFileURL(exportFile).href);assert.equal(await readable.locator('script,img,iframe,link[rel=stylesheet]').count(),0);for(const [key,id]of [['observations','article-observations'],['interpretation','article-interpretation'],['recommendation','article-recommendation']]){assert.equal(await readable.locator('#'+id+' + p').textContent(),sample[key]);await readable.locator('a[href="#'+id+'"]').click();assert.equal(new URL(readable.url()).hash,'#'+id);}
 await readable.pdf({path:path.join(out,'wiki-beitrag.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 const sourceDownload=chapter.waitForEvent('download');await chapter.locator('[data-wiki-download]').click();const source=await sourceDownload,sourcePath=path.join(out,'klassenwiki.html');assert.equal(source.suggestedFilename(),'klassenwiki.html');await source.saveAs(sourcePath);
 const offlineContext=await browser.newContext();await offlineContext.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('Blocked for QA');}}));const offline=await offlineContext.newPage();offline.on('pageerror',e=>errors.push(e.message));const network=[];offline.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await offline.goto(pathToFileURL(sourcePath).href);await offline.locator('#load').setInputFiles(saved);await offline.locator('#notice').getByText(/Arbeitsstand geladen/).waitFor();assert.deepEqual(await values(offline),sample);assert.equal(await offline.locator('#chapter-link').getAttribute('href'),'https://thingummyboop.github.io/physik_bay6/index.html#dgb8_information');assert.deepEqual(network,[]);await offlineContext.close();
 const attack='<img src=x onerror="window.attack=1"> & </script>';await p.locator('#observations').fill(attack);assert.equal(await p.locator('#preview-observations').textContent(),attack);assert.equal(await p.locator('#preview img,#preview script').count(),0);assert.equal(await p.evaluate(()=>window.attack),undefined);await fill(p,sample);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),layouts,downloads:['working JSON','readable HTML','offline editor'],reloadRestore:true,resetUndo:true,rejectedFilePreserved:true,offlineNetworkRequests:network,errors},null,2)+'\n');console.log('PASS: chapter launch, six layouts, editing/compare/review, three real downloads, reload/import/undo/error preservation, readable export links, offline editor without storage/network and safe literal text.');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
