'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/geology')),topic='bio_3_geologie_lebensraeume';
const keys={bio_3_geologie_s1:1,bio_3_geologie_d1:2,bio_3_geologie_path:0,bio_3_geologie_s2:1,bio_3_geologie_d2:2,bio_3_geologie_s3:0,bio_3_geologie_d3:1,bio_3_geologie_mean:2,bio_3_geologie_s4:0,bio_3_geologie_restore:1};
const actions=['cool','weather','compact','transform','melt'],outcomes={magma:['igneous',null,null,null,null],igneous:[null,'sediment',null,'metamorphic','magma'],sediment:[null,null,'sedimentary',null,null],sedimentary:[null,'sediment',null,'metamorphic','magma'],metamorphic:[null,'sediment',null,'metamorphic','magma']};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-geology-lab]')?.dataset.initialized==='true');
 const zone=p.locator('[data-geology-lab]'),start=p.locator('[data-geology-start]'),process=p.locator('[data-geology-process]'),check=p.locator('[data-geology-check]'),reset=p.locator('[data-geology-reset]'),feedback=p.locator('[data-geology-feedback]'),current=p.locator('[data-geology-current]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));let decisions=0;
 const act=async value=>{await process.selectOption(value);assert.equal(await feedback.textContent(),'');await check.click();};
 for(const [state,targets]of Object.entries(outcomes))for(const [i,target]of targets.entries()){await start.selectOption(state);await act(actions[i]);assert.equal(await zone.getAttribute('data-state'),target||state);assert.equal(await zone.getAttribute('data-steps'),target?'1':'0');assert.equal(await feedback.getAttribute('data-correct'),String(!!target));if(target)assert.equal(await current.evaluate(e=>e===document.activeElement),true);decisions++;}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  const layout=async state=>{assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);for(const control of [start,process,check,reset])assert.ok((await control.boundingBox()).height>=44);layouts.push({dark,width,state});};
  for(const [state,action]of [['magma','cool'],['igneous','transform'],['sediment','compact'],['sedimentary','melt'],['metamorphic','weather']]){await start.selectOption(state);await act(action);assert.equal(await feedback.getAttribute('data-correct'),'true');await layout(state);}
  await start.selectOption('sediment');await act('transform');assert.equal(await feedback.getAttribute('data-correct'),'false');await layout('invalid-direct-step');
  await start.selectOption('igneous');for(let n=0;n<6;n++){await act('melt');await act('cool');}assert.equal(await p.locator('[data-geology-history] li').count(),8);assert.equal(await p.locator('[data-geology-history]').getAttribute('start'),'5');await layout('12-step-history');
  for(const card of await p.locator('.geology-card').all()){assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');assert.equal(await card.evaluate(e=>getComputedStyle(e).color),dark?'rgb(224, 224, 224)':'rgb(45, 55, 72)');}
  if(width===390){for(const [name,selector]of [['routes','.geology-routes'],['rocks','.geology-rock-cases'],['workshop','[data-geology-lab]'],['soil','.geology-soil'],['sites','.geology-sites'],['resources','.geology-resources'],['claims','.geology-claims']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png')});for(let i=0;i<4;i++)await p.locator('.geology-plates .geology-card').nth(i).screenshot({path:path.join(out,'plate-'+i+'-'+(dark?'dark':'light')+'.png')});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await start.evaluate(e=>e===document.activeElement),true);assert.equal(await zone.getAttribute('data-state'),'igneous');assert.equal(await zone.getAttribute('data-steps'),'0');assert.equal(await feedback.textContent(),'');await process.focus();await p.keyboard.press('End');assert.equal(await process.inputValue(),'melt');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await zone.getAttribute('data-state'),'magma');assert.equal(await current.evaluate(e=>e===document.activeElement),true);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);let answers=0;for(const [index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic);assert.equal(r.lastPercent,choice===keys[id]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[id]?[]:[id]);const f=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(f));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-geology-paper]').count(),1);assert.equal(await paper.locator('.geology-plates svg').count(),4);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-geology-solution]').count(),4);await paper.pdf({path:path.join(out,'geology-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),decisions,answers,layouts,keyboard:true,storageUnchanged:true,themeColors:true,errors},null,2));console.log('PASS: 25 state/process decisions, 42 layouts, native keyboard/reset/focus/storage, 30 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
