'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/carbon')),topic='bio_4_kohlenstoff_klima';
const keys={bio_4_klima_s1:1,bio_4_klima_d1:2,bio_4_klima_bilanz:0,bio_4_klima_senke:1,bio_4_klima_s2:2,bio_4_klima_d2:0,bio_4_klima_strahlung:1,bio_4_klima_s3:2,bio_4_klima_d3:0,bio_4_klima_phaenologie:1};
const cases=[['A','S',[100,104,108,112,116]],['A','W',[100,104,109,115,122]],['B','S',[100,104,106,106,104]],['B','W',[100,104,107,109,110]],['C','S',[100,100,100,100,100]],['C','W',[100,100,101,103,106]]];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-carbon-lab]')?.dataset.initialized==='true');
 const pathInput=p.locator('[data-carbon-path]'),sink=p.locator('[data-carbon-sink]'),periods=p.locator('[data-carbon-periods]'),check=p.locator('[data-carbon-check]'),reset=p.locator('[data-carbon-reset]'),result=p.locator('[data-carbon-result]'),storage=await p.evaluate(()=>JSON.stringify(localStorage));
 const fill=async(a,s,n)=>{await pathInput.selectOption(a);assert.equal(await result.textContent(),'');await sink.selectOption(s);await periods.selectOption(String(n));await check.click();};
 for(const[a,s,trajectory]of cases)for(let n=1;n<=4;n++){await fill(a,s,n);assert.equal(Number(await p.locator('[data-carbon-final]').getAttribute('data-carbon-final')),trajectory[n]);assert.equal(await p.locator('.carbon-results tbody tr').count(),n);assert.deepEqual(await p.locator('[data-carbon-stock]').evaluateAll(es=>es.map(e=>Number(e.dataset.carbonStock))),trajectory.slice(0,n+1));assert.equal(await result.evaluate(e=>e===document.activeElement),true);}
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:900});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const[a,s]of cases){await fill(a,s,4);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await result.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const el of await p.locator('[data-carbon-lab] button,[data-carbon-lab] select').all())assert.ok((await el.boundingBox()).height>=44);for(const text of await p.locator('.carbon-chart text,.carbon-map text').all())assert.ok((await text.boundingBox()).height>=12);assert.notEqual(await p.locator('[data-carbon-line]').evaluate(e=>getComputedStyle(e).stroke),'none');layouts.push({dark,width,path:a,sink:s,periods:4});}
  for(const cell of await p.locator(':is(.carbon-routes,.carbon-inputs,.carbon-causes,.carbon-phenology,.carbon-actions,.carbon-results) tbody :is(th,td)').all())assert.equal(await cell.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}),true);
  for(const card of await p.locator('.carbon-card,.carbon-chart').all())assert.equal(await card.evaluate(e=>getComputedStyle(e).backgroundColor),dark?'rgb(30, 30, 30)':'rgb(255, 255, 255)');
  assert.ok(await p.locator('.carbon-results caption').evaluate(e=>{const box=e.getBoundingClientRect(),table=e.parentElement.getBoundingClientRect();return box.width>=table.width*.95&&box.height<=parseFloat(getComputedStyle(e).lineHeight)*5;}),'Bilanzüberschrift muss die Tabellenbreite nutzen und lesbar umbrechen');
  if(width===390){await fill('B','S',4);for(const[name,selector]of [['map','.carbon-map'],['routes','.carbon-routes'],['inputs','.carbon-inputs'],['chart','.carbon-chart'],['causes','.carbon-causes'],['phenology','.carbon-phenology'],['actions','.carbon-actions']])await p.locator(selector).screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});await fill('B','S',1);await p.locator('[data-carbon-lab]').screenshot({path:path.join(out,'workshop-'+(dark?'dark':'light')+'.jpg'),type:'jpeg'});}
 }
 await reset.focus();await p.keyboard.press('Enter');assert.equal(await pathInput.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowDown');assert.equal(await pathInput.inputValue(),'B');await p.keyboard.press('Tab');await p.keyboard.press('ArrowDown');assert.equal(await sink.inputValue(),'W');await p.keyboard.press('Tab');await p.keyboard.press('End');assert.equal(await periods.inputValue(),'4');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await p.locator('[data-carbon-final]').getAttribute('data-carbon-final'),'110');assert.equal(await result.evaluate(e=>e===document.activeElement),true);await pathInput.selectOption('C');assert.equal(await result.textContent(),'');assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),storage);
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.equal(qs.length,10);let answers=0;
 for(const[index,id]of qs.entries())for(let choice=0;choice<3;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const r=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),correct=choice===keys[id];assert.equal(r.lastPercent,correct?100:90);assert.deepEqual(r.reviewQuestionIds,correct?[]:[id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-carbon-paper]').count(),1);assert.equal(await paper.locator('svg[data-worksheet-static]').count(),1);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.ok(!(await paper.locator('body').textContent()).includes('undefined'));await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-carbon-solution]').count(),4);await paper.pdf({path:path.join(out,'carbon-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),states:24,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 24 native balance states, 36 layouts, keyboard/reset/focus/storage, 30 quiz answers and paper export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
