const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/digestion-nutrition')),id='bio_1_ernaehrung_verdauung',source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const correct={bio_ernaehrung_s1:1,bio_ernaehrung_s2:2,bio_ernaehrung_s3:0,bio_ernaehrung_s4:1,bio_ernaehrung_s5:2,bio_ernaehrung_d1:1,bio_ernaehrung_d2:2,bio_ernaehrung_d3:0,bio_ernaehrung_d4:1,bio_ernaehrung_d5:2,bio_ernaehrung_d6:0,bio_ernaehrung_portion:1,bio_ernaehrung_fehlend:2,bio_1_ernaehrung_extra_verdauung:2};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===13);assert.equal(await page.locator('.bio-training-card').count(),15);
  let paths=0;for(const q of source.sections.flatMap(s=>s.quizzes))for(const [i,answer]of q.answers.entries()){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:answer.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===correct[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==correct[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));assert.equal(await button.isDisabled(),false);paths++;
  }
  assert.equal(paths,42);const z=page.locator('[data-core-experiment="drink-portions"]'),model=page.locator('[data-core-experiment="digestion-model"]'),control=model.locator('select'),saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results'));let comparisons=0;
  for(let a=0;a<=500;a+=50)for(let b=0;b<=500;b+=50){
   await z.locator('input').evaluateAll((fields,values)=>fields.forEach((f,i)=>{f.value=String(values[i]);f.dispatchEvent(new Event('input',{bubbles:true}));}),[a,b]);
   const expected=[a*0.06,b*0.04];for(const [i,key]of ['a','b'].entries()){
    const width=Number(await z.locator('[data-drink-bar="'+key+'"]').getAttribute('width'));assert.ok(Math.abs(width-expected[i]/30*260)<1e-8);assert.equal(await z.locator('[data-drink-label="'+key+'"]').textContent(),key.toUpperCase()+': '+expected[i]+' g Zucker');
   }
   assert.ok((await z.locator('[role=status]').innerText()).includes(expected[0]===expected[1]?'gleich viel':expected[0]>expected[1]?'Menge A enthält mehr':'Menge B enthält mehr'));comparisons++;
  }
  await z.locator('button').click();assert.equal(await z.locator('input').first().inputValue(),'200');assert.equal(await z.locator('input').first().evaluate(e=>e===document.activeElement),true);await page.keyboard.press('ArrowRight');assert.equal(await z.locator('input').first().inputValue(),'250');assert.match(await z.locator('[role=status]').innerText(),/6 g × 2,5 = 15 g/);await page.keyboard.press('Home');assert.equal(await z.locator('input').first().inputValue(),'0');await page.keyboard.press('End');assert.equal(await z.locator('input').first().inputValue(),'500');await z.locator('button').click();
  for(let i=0;i<4;i++){
   await control.focus();await page.keyboard.press('Home');for(let n=0;n<i;n++)await page.keyboard.press('ArrowDown');assert.equal(await control.inputValue(),String(i));assert.equal(await model.locator('[data-digestion-stage]:visible').count(),1);const stage=model.locator('[data-digestion-stage="'+i+'"]');assert.equal(await stage.isVisible(),true);assert.equal(await stage.locator('[data-glucose-unit]').count(),6);assert.equal(await stage.locator('[data-starch-link]').count(),[4,4,0,0][i]);assert.equal(await stage.locator('[data-food-piece]').count(),[1,2,0,0][i]);assert.match(await model.locator('[role=status]').innerText(),new RegExp('Bild '+(i+1)+' von 4'));
  }
  await model.locator('button').click();assert.equal(await control.inputValue(),'0');assert.equal(await control.evaluate(e=>e===document.activeElement),true);assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('[data-core-experiment="drink-portions"] p')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(const [kind,zone,count]of [['digestion',model,4],['portions',z,1]])for(let i=0;i<count;i++){
    if(kind==='digestion')await control.selectOption(String(i));const geometry=await zone.evaluate(e=>{const r=e.getBoundingClientRect(),svg=[...e.querySelectorAll('svg')].find(s=>s.getBoundingClientRect().width),b=svg.getBoundingClientRect(),v=svg.viewBox.baseVal;return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,svgLeft:b.left,svgRight:b.right,labels:[...svg.querySelectorAll('text')].map(t=>{const b=t.getBBox();return {x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height};}),viewWidth:v.width,viewHeight:v.height};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow);assert.ok(geometry.svgLeft>=0&&geometry.svgRight<=width+1);assert.ok(geometry.labels.every(t=>t.x>=0&&t.right<=geometry.viewWidth&&t.y>=0&&t.bottom<=geometry.viewHeight));layouts.push({width,theme,kind,stage:i,geometry});if(width===390)await zone.screenshot({path:path.join(out,kind+'-'+i+'-'+theme+'.png')});
   }
  }
  await page.setViewportSize({width:390,height:844});const tables=[];for(const key of ['data-drink-label-table','data-digestion-protocol']){
   const table=page.locator('['+key+']'),parent=table.locator('..'),scrollable=await parent.getAttribute('role')==='region';if(scrollable){assert.equal(await parent.getAttribute('tabindex'),'0');await parent.focus();for(let i=0;i<100&&await parent.evaluate(e=>e.scrollLeft<e.scrollWidth-e.clientWidth-1);i++){await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);}assert.ok(await parent.evaluate(e=>e.scrollLeft>=e.scrollWidth-e.clientWidth-1));}else{const b=await table.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=391);}await (scrollable?parent:table).screenshot({path:path.join(out,key+'-mobile.png')});tables.push({key,scrollable});
  }
  const attempts=[];for(const [wrong,section]of [['bio_ernaehrung_portion',3],['bio_ernaehrung_d1',4]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(correct[q]+1)%3:correct[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,92);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),13);assert.equal(await paper.locator('#ws-biology-material .bio-training-card').count(),15);assert.equal(await paper.locator('#ws-biology-material .ws-glossary-entry').count(),27);assert.equal(await paper.locator('[data-digestion-paper] svg').count(),4);assert.equal(await paper.locator('[data-drink-paper] svg').count(),1);assert.equal(await paper.locator('[data-digestion-protocol] tbody tr').count(),4);assert.equal(await paper.locator('[data-drink-paper-table] tbody tr').count(),3);assert.equal(await paper.locator('#ws-biology-material select,#ws-biology-material input,#ws-biology-material button').count(),0);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions').isVisible(),true);assert.match(await paper.locator('#ws-solutions').innerText(),/200 ml A = 12 g und 300 ml B = 12 g/);await paper.pdf({path:path.join(out,'digestion-nutrition.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({generatedAt:new Date().toISOString(),base,browser:browser.version(),paths,comparisons,layouts,tables,attempts,pageErrors:errors,scope:'42 native quiz choices, 121 portion values by DOM input, native range ArrowRight/Home/End and four native select states, reset/focus/storage, 30 model/layout states, two tables, two 92% checks, five static paper diagrams and separate solutions. Visual inspection separate; no tasting/classroom/whole-site acceptance.'},null,2)+'\n');console.log('PASS: nutrition/digestion native: 42 quiz choices, 121 portion comparisons, native range/select controls, 30 layouts, two tables, two 92% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
