const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/byte-files')),topic='dgb6_information',keys=require('./fixtures/dgb6_information_keys.json');
const chapter=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[topic],samples=[['a','A',[65]],['aa','AA',[65,65]],['umlaut','Ä',[195,132]]];
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];let byteStates=0,retrievals=0,answers=0,practiceAnswers=0;try{
 const p=await browser.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.locator('#chapter-quiz-launch').waitFor();const stored=await p.evaluate(()=>JSON.stringify(localStorage));
 const byte=p.locator('[data-core-experiment="byte-pattern"]'),buttons=byte.locator('[data-byte-weight]'),file=p.locator('[data-core-experiment="file-bytes"]'),choice=file.locator('select'),result=file.locator('[data-file-result]');
 for(const dark of [false,true])for(const width of [320,390,1280]){
  await p.setViewportSize({width,height:1000});await p.evaluate(d=>{if(d)document.documentElement.dataset.theme='dark';else delete document.documentElement.dataset.theme;},dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(const value of [0,1,2,64,65,67,128,255]){const expected=value.toString(2).padStart(8,'0');for(let i=0;i<8;i++){const b=buttons.nth(i);if((await b.getAttribute('aria-pressed')==='true')!==(expected[i]==='1')){await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e===document.activeElement),true);}assert.equal(await b.locator('[data-byte-digit]').innerText(),expected[i]);assert.equal(await b.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);}assert.equal(await byte.locator('[data-byte-pattern]').textContent(),expected);assert.ok((await byte.locator('[role=status]').innerText()).startsWith('Als vorzeichenlose Zahl: '+value+'.'));byteStates++;}
  await byte.locator('[data-byte-reset]').focus();await p.keyboard.press('Enter');assert.equal(await buttons.first().evaluate(e=>e===document.activeElement),true);assert.equal(await byte.locator('[data-byte-pattern]').innerText(),'00000000');
  for(const [name,text,bytes]of samples){await choice.selectOption('../examples/bytes-'+name+'.txt');assert.equal(await file.locator('[data-file-details]').isVisible(),false);const responsePromise=p.waitForResponse(r=>r.url().endsWith('/examples/bytes-'+name+'.txt'));await file.locator('[data-file-fetch]').focus();await p.keyboard.press('Enter');const response=await responsePromise;assert.equal(response.status(),200);assert.deepEqual([...await response.body()],bytes);await p.waitForFunction(()=>!document.querySelector('[data-file-fetch]').disabled);assert.equal(await file.locator('[data-file-text]').innerText(),text);assert.ok((await result.innerText()).includes(bytes.length+' Byte = '+bytes.length*8+' Bit'));assert.deepEqual(await file.locator('[data-file-bits] code').allTextContents(),bytes.map(b=>b.toString(2).padStart(8,'0')));retrievals++;}
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  if(width===320){await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});for(const [name,selector]of [['byte','[data-core-experiment="byte-pattern"]'],['file','[data-core-experiment="file-bytes"]'],['route','[data-info-request-route]']]){await p.locator(selector).evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await p.screenshot({path:path.join(out,name+'-'+(dark?'dark':'light')+'.png'),animations:'disabled'});}}
 }
 await file.locator('[data-file-reset]').focus();await p.keyboard.press('Enter');assert.equal(await choice.evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowDown');assert.equal(await choice.inputValue(),'../examples/bytes-aa.txt');await p.keyboard.press('Tab');assert.equal(await file.locator('[data-file-fetch]').evaluate(e=>e===document.activeElement),true);
 // Responses and network failures clear any previous result instead of showing stale bytes.
 await choice.selectOption('../examples/bytes-a.txt');await p.route('**/examples/bytes-a.txt',route=>route.fulfill({status:404,body:'Not found',contentType:'text/plain'}));await file.locator('[data-file-fetch]').click();await p.waitForFunction(()=>document.querySelector('[data-file-result]').textContent.includes('HTTP 404'));assert.equal(await file.locator('[data-file-details]').isVisible(),false);await p.unroute('**/examples/bytes-a.txt');
 await p.route('**/examples/bytes-a.txt',route=>route.abort('failed'));await file.locator('[data-file-fetch]').click();await p.waitForFunction(()=>document.querySelector('[data-file-result]').textContent.includes('Abruf nicht gelungen'));assert.equal(await file.locator('[data-file-details]').isVisible(),false);await p.unroute('**/examples/bytes-a.txt');
 for(const [name,text,bytes]of samples){const promise=p.waitForEvent('download');await p.locator('[data-info-download="'+name+'"]').click();const download=await promise;assert.equal(download.suggestedFilename(),'bytes-'+name+'.txt');const target=path.join(out,download.suggestedFilename());await download.saveAs(target);assert.deepEqual([...fs.readFileSync(target)],bytes);assert.equal(fs.readFileSync(target,'utf8'),text);}
 fs.writeFileSync(path.join(out,'local-working-copy.txt'),'AA');await file.locator('[data-file-fetch]').click();await p.waitForFunction(()=>!document.querySelector('[data-file-fetch]').disabled);assert.equal(await file.locator('[data-file-text]').innerText(),'A');
 for(const q of chapter.sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly)){const box=p.locator('.practice-box[data-id="'+q.id+'"]');for(const [n,a]of q.answers.entries()){const b=box.getByRole('button',{name:a.text,exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await b.evaluate(e=>e.classList.contains('is-correct')),n==={dgb6_information_p1:1,dgb6_information_p2:0,dgb6_information_p3:2}[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(a.feedback));practiceAnswers++;}}
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),stored);const questions=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));assert.deepEqual(questions,Object.keys(keys));
 for(const [n,id]of questions.entries())for(let a=0;a<3;a++){if(answers===0)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,n})=>currentChapterQuiz.questions.forEach((q,j)=>{if(j!==n)document.querySelector(`input[name="chapter_q_${j}"][value="${keys[q.id]}"]`).checked=true;}),{keys,n});await p.locator(`input[name="chapter_q_${n}"][value="${a}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const saved=await p.evaluate(t=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[t],topic);assert.equal(saved.lastPercent,a===keys[id]?100:92);assert.equal(saved.contentRevision,4);assert.deepEqual(saved.reviewQuestionIds,a===keys[id]?[]:[id]);answers++;}
 const paper=await browser.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);assert.equal(await paper.locator('[data-info-byte-paper]').count(),1);assert.equal(await paper.locator('[data-info-file-paper]').count(),1);await paper.locator('#ws-include-solutions').check();await paper.pdf({path:path.join(out,'dgb6_information-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});
 assert.equal(byteStates,48);assert.equal(retrievals,18);assert.equal(answers,36);assert.equal(practiceAnswers,9);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:browser.version(),byteStates,retrievals,answers,practiceAnswers,layouts:6,http404:true,networkFailure:true,downloads:3,localCopyIsolation:true,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 48 native byte states, 18 real file responses, HTTP/network failures, three exact downloads, local copy isolation, 36 quiz paths, nine practices, keyboard/reset/focus, six layouts and worksheet export.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
