'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/circle-parts')),topic='math4_kreis_kreisteile';
const keys={circle_diameter:1,circle_ratio:2,circle_pi_exact:0,circle_u:1,circle_a:2,circle_scale:0,circle_half:0,circle_eighth:2,circle_full_edge:1,circle_inverse_u:1,circle_inverse_a:2,circle_inverse_quarter:0,circle_inner:1,circle_order:2,circle_area_unit:0};
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+topic);await p.waitForFunction(()=>document.querySelector('[data-circle-lab]')?.dataset.bound==='true');const saved=await p.evaluate(()=>JSON.stringify(localStorage)),lab=p.locator('[data-circle-lab]');let models=0;
 const setRadius=async n=>{await p.locator('#circle-radius').fill(String(n));await p.locator('#circle-radius').dispatchEvent('input');};
 for(let radius=1;radius<=8;radius++)for(const part of [1,2,4,8]){
  await setRadius(radius);await p.locator('#circle-part').selectOption(String(part));
  for(const quantity of ['arc','perimeter','area']){await p.locator('#circle-quantity').selectOption(quantity);const expected=quantity==='area'?Math.PI*radius**2/part:2*Math.PI*radius/part+(quantity==='perimeter'&&part!==1?2*radius:0);await p.locator('#circle-answer').fill(expected.toFixed(2).replace('.',','));await p.locator('#circle-answer').press('Enter');assert.match(await lab.locator('[data-circle-status]').textContent(),/^Richtig\./);assert.equal(await lab.locator('[data-circle-row]').count(),3);models++;}
 }
 await p.locator('#circle-answer').fill('kein Wert');await lab.locator('[data-circle-check]').click();assert.equal(await p.locator('#circle-answer').getAttribute('aria-invalid'),'true');await lab.locator('[data-circle-reset]').click();assert.equal(await p.locator('#circle-radius').evaluate(e=>e===document.activeElement),true);assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const width of [320,390,1280])for(const dark of [false,true]){
  await p.setViewportSize({width,height:1200});await p.evaluate(d=>document.documentElement.setAttribute('data-theme',d?'dark':'light'),dark);await p.waitForFunction(d=>getComputedStyle(document.body).color===(d?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),dark);
  for(let radius=1;radius<=8;radius++)for(const part of [1,2,4,8]){
   await setRadius(radius);await p.locator('#circle-part').selectOption(String(part));await lab.locator('[data-circle-show]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await lab.locator('[data-circle-calculation]').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);
   const bounds=await lab.locator('svg text').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBBox();return[r.x,r.y,r.x+r.width,r.y+r.height];}));assert.ok(bounds.every(r=>r[0]>=0&&r[1]>=0&&r[2]<=360&&r[3]<=310));layouts.push({width,dark,radius,part});
   if(width===320&&radius===4&&[1,4].includes(part)){await lab.locator('[data-circle-calculation]').screenshot({path:path.join(out,`results-${part}-${dark?'dark':'light'}.png`)});await lab.screenshot({path:path.join(out,`lab-${part}-${dark?'dark':'light'}.png`)});}
   if(width===1280&&!dark&&[1,4,8].includes(radius)){const svg=lab.locator('svg');await svg.evaluate(e=>e.scrollIntoView({block:'center'}));await svg.screenshot({path:path.join(out,`full-${radius}-${part}.png`)});}
  }
  if(width===320){for(const selector of ['[data-circle-drawing]','.circle-figure .circle-scroll','.circle-measurements']){const region=selector==='.circle-measurements'?p.locator(selector).locator('..'):p.locator(selector).first();await region.focus();await p.keyboard.press('ArrowRight');await p.waitForFunction(el=>el.scrollLeft>0,await region.elementHandle());await p.waitForTimeout(220);}await lab.locator('[data-circle-reset]').click();assert.ok(await lab.locator('[data-circle-drawing]').evaluate(e=>Math.abs(e.scrollLeft-Math.max(0,(e.scrollWidth-e.clientWidth)/2))<=1));await p.locator('.circle-measurements').locator('..').screenshot({path:path.join(out,`measurements-${dark?'dark':'light'}.png`)});}
 }
 for(let i=0;i<2;i++){const figure=p.locator('.circle-figure').nth(i);await figure.evaluate(e=>e.scrollIntoView({block:'center'}));await figure.screenshot({path:path.join(out,`figure-${i}.png`)});}
 console.log('PASS: 96 native calculations, 192 layouts, keyboard/focus/storage; starting 45 quiz answers.');
 const qs=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>({id:q.id,length:q.answers.length})));assert.equal(qs.length,15);let answers=0;
 for(const[index,q]of qs.entries())for(let choice=0;choice<q.length;choice++){
  if(!answers)await p.locator('#chapter-quiz-launch').click();else await p.locator('#chapter-quiz-result button[onclick="restartChapterQuiz()"]').click();await p.evaluate(({keys,index})=>currentChapterQuiz.questions.forEach((q,k)=>{if(k!==index)document.querySelector(`input[name="chapter_q_${k}"][value="${keys[q.id]}"]`).checked=true;}),{keys,index});await p.locator(`input[name="chapter_q_${index}"][value="${choice}"]`).check();await p.locator('#chapter-quiz-panel .chapter-submit-btn').click();const result=await p.evaluate(topic=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[topic],topic),right=choice===keys[q.id];assert.equal(result.lastPercent,right?100:93);assert.deepEqual(result.reviewQuestionIds,right?[]:[q.id]);const feedback=await p.evaluate(({index,choice})=>currentChapterQuiz.questions[index].answers[choice].feedback,{index,choice});assert.ok((await p.locator('#chapter-quiz-result').textContent()).includes(feedback));answers++;
 }
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+topic);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('.circle-figure svg').count(),2);assert.equal(await paper.locator('.circle-paper').count(),1);assert.equal(await paper.locator('[data-circle-tasks] li').count(),15);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('#ws-solutions [data-circle-solution]').count(),5);
 await paper.pdf({path:path.join(out,'circle-parts-solutions.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true,margin:{top:'15mm',right:'15mm',bottom:'15mm',left:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),models,answers,layouts,keyboard:true,storageUnchanged:true,errors},null,2));console.log('PASS: 96 native calculations, 192 layouts, 45 quiz answers and optional worksheet solutions; PDF exported.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
