const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/cell-learning')),id='bio_2_zellen',source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const correct={bio2_zelle_s1:0,bio2_zelle_s2:0,bio2_zelle_s3:0,bio2_zelle_s4:0,bio2_zelle_s5:0,bio2_zelle_d1:0,bio2_zelle_d2:0,bio2_zelle_d3:0,bio2_zelle_d4:0,bio2_zelle_d5:0,bio2_zelle_massstab:1,bio2_zelle_modellbefund:2,bio_2_zellen_extra_vergleich:0};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===12&&document.querySelectorAll('[data-cell-rows] tr').length===7);assert.equal(await page.locator('.bio-training-card').count(),15);
  let paths=0;for(const q of source.sections.flatMap(s=>s.quizzes))for(const [i,answer]of q.answers.entries()){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:answer.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===correct[q.id]);assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==correct[q.id]);assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));assert.equal(await button.isDisabled(),false);paths++;
  }
  assert.equal(paths,39);const z=page.locator('[data-cell-comparison]'),control=z.locator('select'),saved=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results'));
  for(const [i,kind]of ['leaf','root','animal'].entries()){
   await control.focus();await page.keyboard.press('Home');for(let n=0;n<i;n++)await page.keyboard.press('ArrowDown');assert.equal(await control.inputValue(),kind);assert.equal(await z.locator('[data-cell-view]:visible').count(),1);assert.equal(await z.locator('[data-cell-view="'+kind+'"]').isVisible(),true);assert.equal(await z.locator('[data-cell-view]:visible [data-cell-shape="chloroplasts"]').count(),kind==='leaf'?3:0);assert.equal(await z.locator('[data-cell-part="chloroplasts"] td').first().innerText(),kind==='leaf'?'Ja':'Nein');assert.equal(await control.evaluate(e=>e===document.activeElement),true);
  }
  assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),saved);await z.locator('button').click();assert.equal(await control.inputValue(),'leaf');assert.equal(await control.evaluate(e=>e===document.activeElement),true);
  const layouts=[];for(const width of [320,390,1280])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForFunction(t=>getComputedStyle(document.querySelector('[data-cell-comparison] p')).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);
   for(const kind of ['leaf','root','animal']){
    await control.selectOption(kind);const svg=z.locator('[data-cell-view]:visible svg'),geometry=await svg.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,labels:[...e.querySelectorAll('text')].map(t=>{const b=t.getBBox();return {x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height};})};});assert.ok(geometry.left>=0&&geometry.right<=width+1&&!geometry.overflow);assert.ok(geometry.labels.every(b=>b.x>=0&&b.right<=320&&b.y>=0&&b.bottom<=260));layouts.push({width,theme,kind,geometry});if(width===390)await z.screenshot({path:path.join(out,kind+'-'+theme+'.png')});
   }
   const scale=page.locator('[data-cell-scale] svg');const ratio=await scale.evaluate(svg=>{const a=svg.querySelector('[data-cell-outline]').getBoundingClientRect(),b=svg.querySelector('[data-cell-scale-bar]').getBoundingClientRect();return a.width/b.width;});assert.ok(Math.abs(ratio-4)<0.01);if(width===390)await page.locator('[data-cell-scale]').screenshot({path:path.join(out,'scale-'+theme+'.png')});
  }
  await page.setViewportSize({width:390,height:844});const tables=[];for(const selector of ['[data-cell-protocol]','[data-cell-observation] table','[data-cell-comparison] table']){
   await page.waitForFunction(selector=>{const table=document.querySelector(selector),parent=table.parentElement;return parent.classList.contains('responsive-table')&&(parent.scrollWidth<=parent.clientWidth+1||parent.getAttribute('role')==='region');},selector);
   const table=page.locator(selector),parent=table.locator('..'),scrollable=await parent.getAttribute('role')==='region';if(scrollable){assert.equal(await parent.getAttribute('tabindex'),'0');await parent.focus();for(let i=0;i<100&&await parent.evaluate(e=>e.scrollLeft<e.scrollWidth-e.clientWidth-1);i++){await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);}assert.ok(await parent.evaluate(e=>e.scrollLeft>=e.scrollWidth-e.clientWidth-1));}else{const b=await table.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=391);}tables.push({selector,scrollable});
  }
  const attempts=[];for(const [wrong,section]of [['bio2_zelle_massstab',3],['bio2_zelle_d2',2]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));for(const [i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?(correct[q]+1)%3:correct[q])+'"]').check();await page.locator('.chapter-submit-btn').click();const stored=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(stored.lastPercent,92);assert.equal(stored.contentRevision,2);assert.deepEqual(stored.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result:stored});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),12);assert.equal(await paper.locator('#ws-biology-material .bio-training-card').count(),15);assert.equal(await paper.locator('#ws-biology-material .ws-glossary-entry').count(),21);assert.equal(await paper.locator('[data-cell-protocol] tbody tr').count(),7);assert.equal(await paper.locator('#ws-biology-material svg').count(),5);assert.equal(await paper.locator('#ws-biology-material select,#ws-biology-material button').count(),0);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);await paper.locator('#ws-include-solutions').check();assert.match(await paper.locator('#ws-solutions').innerText(),/200 µm = 0,2 mm/);await paper.pdf({format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'},path:path.join(out,'cells-solutions.pdf')});assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({generatedAt:new Date().toISOString(),base,browser:browser.version(),paths,layouts,tables,attempts,pageErrors:errors,scope:'39 native quiz choices, three keyboard model selections, reset/focus/storage, 18 model/layout states, scale ratio at six layouts, three tables, two 92% checks and paper with five diagrams and separate solutions. Visual inspection separate; no real microscopy or whole-site acceptance.'},null,2)+'\n');console.log('PASS: cells native: 39 quiz choices, three keyboard models, 18 model/layout states, six scale ratios, three tables, two 92% checks and paper.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
