const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/habitat-relationships')),id='bio_1_lebensraeume',source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id];
const correct=id=>({bio_lebensraum_s1:1,bio_lebensraum_s2:2,bio_lebensraum_s4:1,bio_lebensraum_s5:2,bio_lebensraum_d2:1,bio_lebensraum_d3:2,bio_lebensraum_d5:2,bio_lebensraum_d6:1,bio_1_lebensraeume_extra_nahrungsnetz:1}[id]||0);
const expected={none:['grass-hopper','grass-mouse','hopper-frog','hopper-stork','frog-stork','mouse-stork'],grass:['hopper-frog','hopper-stork','frog-stork','mouse-stork'],hopper:['grass-mouse','frog-stork','mouse-stork'],mouse:['grass-hopper','hopper-frog','hopper-stork','frog-stork'],frog:['grass-hopper','grass-mouse','hopper-stork','mouse-stork'],stork:['grass-hopper','grass-mouse','hopper-frog']};
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[];
 try{
  const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/topics/template.html?topic='+id);await page.waitForFunction(()=>window.currentChapterQuiz?.questions.length===11);assert.equal(await page.locator('.bio-training-card').count(),15);
  const storage=await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results'));let paths=0;
  for(const q of source.sections.flatMap(s=>s.quizzes)){
   const box=page.locator('.practice-box[data-id="'+q.id+'"]');
   for(const [i,answer]of q.answers.entries()){
    const button=box.getByRole('button',{name:answer.text,exact:true});await button.focus();await page.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===correct(q.id));assert.equal(await button.evaluate(e=>e.classList.contains('is-wrong')),i!==correct(q.id));assert.ok((await box.locator('.feedback').innerText()).includes(answer.feedback));assert.equal(await button.isDisabled(),false);paths++;
   }
  }
  assert.equal(paths,36);const zone=page.locator('[data-core-experiment="food-web"]'),select=zone.locator('select'),layouts=[];
  for(const width of [320,390,1280])for(const theme of ['light','dark'])for(const state of Object.keys(expected)){
   await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await select.selectOption(state);assert.deepEqual(await zone.locator('[data-foodweb-from]').evaluateAll(nodes=>nodes.filter(e=>getComputedStyle(e).display!=='none').map(e=>e.dataset.foodwebFrom+'-'+e.dataset.foodwebTo)),expected[state]);
   assert.equal(await zone.locator('[data-foodweb-node-status]').evaluateAll(nodes=>nodes.filter(e=>e.textContent==='fehlt').length),state==='none'?0:1);const size=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert.ok(size.scroll<=size.width+1,JSON.stringify(size));layouts.push({state,theme,...size});
  }
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.removeAttribute('data-theme'));await select.focus();await page.keyboard.press('Home');assert.equal(await select.inputValue(),'none');await page.keyboard.press('ArrowDown');assert.equal(await select.inputValue(),'grass');await page.keyboard.press('End');assert.equal(await select.inputValue(),'stork');
  await select.selectOption('hopper');await zone.screenshot({path:path.join(out,'missing-hopper-mobile.png')});await zone.getByRole('button',{name:'Ausgangsnetz zeigen',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await select.inputValue(),'none');assert.equal(await select.evaluate(e=>document.activeElement===e),true);await zone.screenshot({path:path.join(out,'food-web-mobile.png')});
  assert.equal(await page.evaluate(()=>localStorage.getItem('sciverse_chapter_quiz_results')),storage);
  const tables=[];for(const key of ['data-foodweb-reference','data-habitat-protocol','data-habitat-sample']){
   const table=page.locator('['+key+']'),parent=table.locator('..'),scrollable=await parent.getAttribute('role')==='region',region=scrollable?parent:table;
   if(scrollable)assert.equal(await region.getAttribute('tabindex'),'0');else{const bounds=await table.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=391);}
   if(await region.evaluate(e=>e.scrollWidth>e.clientWidth+1)){
    await region.focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(e=>e.scrollLeft>0,await region.elementHandle());for(let i=0;i<100&&await region.evaluate(e=>e.scrollLeft<e.scrollWidth-e.clientWidth-1);i++){await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);}await page.waitForFunction(e=>e.scrollLeft>=e.scrollWidth-e.clientWidth-1,await region.elementHandle());assert.equal(await region.evaluate(e=>document.activeElement===e),true);
   }
   await region.screenshot({path:path.join(out,key+'-mobile.png')});tables.push({key,scrollable});
  }
  const attempts=[];for(const [wrong,section]of [['bio_lebensraum_d2',1],['bio_lebensraum_d6',4]]){
   await page.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();if(attempts.length)await page.locator('[onclick="restartChapterQuiz()"]').click();const ids=await page.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id));
   for(const [i,q]of ids.entries())await page.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?0:correct(q))+'"]').check();await page.locator('.chapter-submit-btn').click();const result=await page.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,91);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,[wrong]);attempts.push({wrong,section,result});await page.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await page.locator('#learning-section-'+section).evaluate(e=>e.contains(document.activeElement)));
  }
  const paper=await context.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('#ws-content>.question-block').count(),11);assert.equal(await paper.locator('#ws-biology-material .bio-training-card').count(),15);assert.equal(await paper.locator('#ws-biology-material .ws-glossary-entry').count(),23);assert.equal(await paper.locator('#ws-solutions').isVisible(),false);
  assert.equal(await paper.locator('#ws-content svg[data-foodweb-diagram]').count(),1);assert.equal(await paper.locator('#ws-content svg [data-foodweb-from]').count(),6);assert.equal(await paper.locator('#ws-content [data-foodweb-missing]').count(),0);assert.equal(await paper.locator('[data-habitat-protocol] tbody tr').count(),8);assert.equal(await paper.locator('[data-habitat-decision] ol li').count(),3);await paper.locator('#ws-include-solutions').check();await paper.pdf({path:path.join(out,'habitats.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),base,browser:browser.version(),paths,layouts,tables,attempts,pageErrors:errors,scope:'36 native practice answers, 36 food-web/width/theme states, keyboard selection/reset/focus, three tables fitting or scrolling to right edge by keyboard, two 91% chapter checks with exact review, paper static net and tasks/protocol/glossary/solutions and PDF export. No real field observation or whole-site factual/visual approval.'},null,2)+'\n');console.log('PASS: 36 native habitat answer paths, 36 model/layout states, keyboard/reset/storage and tables, two 91% chapter checks, paper net/tasks/protocol/glossary and PDF.');await context.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
