'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const id='math1_2_nat_zahlen',base=process.env.SCIVERSE_PREVIEW_URL||'http://127.0.0.1:4173',out=path.resolve(process.env.SCIVERSE_BROWSER_REPORT_DIR||path.join(__dirname,'../../browser-qa/roman-numbers'));
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../lang/de.json'),'utf8'))[id],keys={m12_ziffer_zahl:0,natural_place_zero:0,natural_numberline:0,natural_estimate:0,roman_read_pairs:1,roman_year:2,roman_clock:0,roman_place_value:2,roman_compare:1,roman_zero:0,m12_check_place:0,m12_check_build:0},expected=[1,4,6,9,12,14,19,24,39,40,44,49,58,90,94,99,400,444,900,944,1492,1848,1988,1999,2026,3999,4];
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),errors=[],layouts=[];try{
 const p=await b.newPage({viewport:{width:390,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/topics/template.html?topic='+id);await p.waitForFunction(()=>document.querySelector('[data-roman-lab]')?.dataset.bound==='true');const lab=p.locator('[data-roman-lab]'),saved=await p.evaluate(()=>JSON.stringify(localStorage));let cases=0,paths=0;
 for(let i=0;i<27;i++){await p.locator('#roman-case').selectOption(String(i));await p.locator('#roman-answer').fill(String(expected[i]));await p.locator('#roman-answer').press('Enter');assert.match(await p.locator('#roman-status').innerText(),/^Richtig:/);assert.equal(await p.locator('#roman-answer').evaluate(e=>e===document.activeElement),true);await lab.locator('[data-roman-show]').click();assert.ok((await lab.locator('[data-roman-steps]').innerText()).includes('= '+expected[i]));cases++;}
 await lab.locator('[data-roman-reset]').focus();await p.keyboard.press('Space');assert.equal(await p.locator('#roman-case').inputValue(),'11');assert.equal(await p.locator('#roman-case').evaluate(e=>e===document.activeElement),true);assert.equal(await lab.locator('[data-roman-steps]').isVisible(),false);
 await p.locator('#roman-answer').fill('49e0');await p.locator('#roman-answer').press('Enter');assert.match(await p.locator('#roman-status').innerText(),/^Gib eine/);await p.locator('#roman-answer').fill('61');await p.locator('#roman-answer').press('Enter');assert.match(await p.locator('#roman-status').innerText(),/^Noch nicht/);await p.locator('#roman-answer').fill('49');assert.equal(await p.locator('#roman-status').innerText(),'');await lab.locator('[data-roman-check]').click();assert.match(await p.locator('#roman-status').innerText(),/^Richtig/);
 await p.locator('#inputZehner').fill('8');await p.locator('#inputZehner').press('Enter');assert.match(await p.locator('#feedZ').innerText(),/Wert ist 80/);
 for(const width of [320,390,1280])for(const theme of ['light','dark']){
  await p.setViewportSize({width,height:1000});await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await p.waitForFunction(t=>getComputedStyle(document.body).color===(t==='dark'?'rgb(224, 224, 224)':'rgb(45, 55, 72)'),theme);await p.waitForTimeout(350);
  for(let i=0;i<27;i++){await p.locator('#roman-case').selectOption(String(i));await lab.locator('[data-roman-show]').click();const geometry=await lab.evaluate(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...e.querySelectorAll('input,button,select')].map(c=>{const r=c.getBoundingClientRect();return {left:r.left,right:r.right,height:r.height};})};});assert.ok(!geometry.overflow&&geometry.left>=0&&geometry.right<=width+1,JSON.stringify({width,theme,i,geometry}));assert.ok(geometry.controls.every(c=>c.left>=geometry.left&&c.right<=geometry.right+1&&c.height>=44));layouts.push({width,theme,index:i});}
  await p.locator('#roman-case').selectOption('25');await lab.locator('[data-roman-show]').click();await lab.screenshot({path:path.join(out,'lab-'+width+'-'+theme+'.png')});if(width===320)await p.locator('#learning-section-3').screenshot({path:path.join(out,'reading-'+theme+'.png')});
 }
 assert.equal(await p.evaluate(()=>JSON.stringify(localStorage)),saved);
 for(const q of source.sections.flatMap(s=>s.quizzes))for(const[i,a]of q.answers.entries()){const box=p.locator('.practice-box[data-id="'+q.id+'"]'),button=box.getByRole('button',{name:a.text,exact:true});await button.focus();await p.keyboard.press('Enter');assert.equal(await button.evaluate(e=>e.classList.contains('is-correct')),i===keys[q.id]);assert.ok((await box.innerText()).includes(a.feedback));paths++;}
 await p.getByRole('button',{name:'Zum Kapitelcheck',exact:true}).click();const ids=await p.evaluate(()=>currentChapterQuiz.questions.map(q=>q.id)),wrong='roman_compare';for(const[i,q]of ids.entries())await p.locator('input[name="chapter_q_'+i+'"][value="'+(q===wrong?0:keys[q])+'"]').check();await p.locator('.chapter-submit-btn').click();const result=await p.evaluate(id=>JSON.parse(localStorage.getItem('sciverse_chapter_quiz_results'))[id],id);assert.equal(result.lastPercent,92);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,[wrong]);await p.locator('#chapter-quiz-result').getByRole('button',{name:'Passenden Abschnitt wiederholen',exact:true}).click();assert.ok(await p.locator('#learning-section-4').evaluate(e=>e.contains(document.activeElement)));
 const paper=await b.newPage();paper.on('pageerror',e=>errors.push(e.message));await paper.goto(base+'/topics/worksheet.html?topic='+id);await paper.waitForFunction(()=>!document.getElementById('ws-print').disabled);assert.equal(await paper.locator('[data-natural-paper],[data-roman-paper]').count(),2);assert.equal(await paper.locator('[data-natural-generated]').count(),12);assert.equal(await paper.locator('#ws-content>.question-block').count(),12);await paper.locator('#ws-include-solutions').check();assert.equal(await paper.locator('.ws-paper-solution').count(),4);
 const generated=await paper.locator('[data-natural-generated]').evaluateAll(es=>es.map(e=>({kind:e.dataset.naturalGenerated,first:e.dataset.first,second:e.dataset.second,text:e.textContent}))),answers=await paper.locator('[data-natural-answer]').evaluateAll(es=>es.map(e=>({value:e.dataset.naturalAnswer,text:e.textContent})));
 await paper.pdf({path:path.join(out,'roman-solutions.pdf'),format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'15mm',right:'15mm'}});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({createdAt:new Date().toISOString(),browser:b.version(),cases,paths,layouts,result,generated,answers,errors,scope:'Native reading, 30 section practice answer paths, final chapter review, responsive controls and worksheet export. All 36 final-quiz paths are tested separately in JSDOM. PDF visual inspection recorded separately.'},null,2)+'\n');console.log('PASS: native Roman reading: '+cases+' cases, '+paths+' practice answer paths, '+layouts.length+' layouts, keyboard/reset/review and worksheet export.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
