const fs=require('fs'),path=require('path'),vm=require('vm');const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),id='geo_4_globalisierung',t=data[id];
const blocks=[
 ['global_limits','Menschen verändern die Erde',`<p>Landwirtschaft, Städte, Rohstoffabbau und Energieverbrauch verändern Landschaften, Stoffkreisläufe und Klima. Der Begriff <strong>Anthropozän</strong> betont diesen starken menschlichen Einfluss. Er wird in Umwelt- und Gesellschaftswissenschaften verwendet. Das bedeutet nicht, dass alle Menschen gleich viel verursachen oder gleich viel entscheiden können. Der Vorschlag, das Anthropozän als formale geologische Epoche festzulegen, wurde 2024 abgelehnt; der Begriff bleibt für die Diskussion menschlicher Einflüsse gebräuchlich.</p><p>Das Forschungsmodell der <strong>planetaren Belastungsgrenzen</strong> untersucht wichtige Prozesse des Erdsystems, etwa Klima, biologische Vielfalt, Süßwasser und Nährstoffkreisläufe. Die Grenzen beschreiben Bereiche, jenseits derer Risiken zunehmen. Sie sind keine Landesgrenzen und kein Datum, an dem die Erde plötzlich unbewohnbar wird. Eine Grenze ist auch nicht automatisch ein Kipppunkt. Die Prozesse beeinflussen einander: Waldverlust kann beispielsweise Lebensräume verkleinern und den Kohlenstoffkreislauf verändern.</p><p><strong>Quellenauftrag:</strong> Öffne die verlinkte Forschungsübersicht des Stockholm Resilience Centre. Notiere Veröffentlichungs- oder Aktualisierungsdatum, einen untersuchten Prozess und dessen Messgröße. Unterscheide eine Aussage der Quelle von deiner eigenen Schlussfolgerung. Aktuelle Zahlen müssen immer mit dem Stand der Untersuchung angegeben werden.</p>`,[
 ['Was meint Anthropozän in diesem Kapitel?',['Den starken menschlichen Einfluss auf Erde und Umwelt.','Dass jeder Mensch überall denselben Einfluss hat.','Dass natürliche Prozesse keine Rolle mehr spielen.'],['Der Begriff hilft, Veränderungen und Verantwortung zu untersuchen.','Einfluss, Ressourcen und Entscheidungsmacht sind ungleich verteilt.','Natürliche Prozesse wirken weiterhin und stehen mit menschlichen Eingriffen in Wechselwirkung.']],
 ['Was folgt aus dem Überschreiten einer planetaren Belastungsgrenze?',['Risiken nehmen zu; die Grenze ist nicht automatisch ein exakter Kipppunkt.','Ab diesem Tag sind alle Orte der Erde unbewohnbar.','Nur das Land mit dem höchsten Verbrauch ist betroffen.'],['Das Modell beschreibt Risiken im Erdsystem und keine punktgenaue Katastrophenuhr.','Diese Schlussfolgerung gibt das Modell nicht her.','Globale Prozesse können Wirkungen über Ländergrenzen hinweg haben.']]
 ]],
 ['global_reorganisation','Globalisierung und Deglobalisierung',`<p><strong>Globalisierung</strong> bezeichnet zunehmende weltweite Verflechtungen, etwa von Produktion, Handel, Informationen und Lebensweisen. Bei <strong>Deglobalisierung</strong> werden bestimmte grenzüberschreitende Verflechtungen geringer. Das kann einzelne Branchen betreffen, während andere weiterhin international zusammenarbeiten. Eine Verlagerung in eine näher gelegene Region ist nicht automatisch ein vollständiger Rückzug aus dem Welthandel.</p><p><strong>Erfundener Fall:</strong> Ein Wiener Bekleidungsbetrieb bezieht Stoff bisher von einem einzigen weit entfernten Unternehmen. Wiederholte Lieferausfälle führen zu zwei Vorschlägen: A verteilt Bestellungen auf mehrere Lieferanten in verschiedenen Ländern. B verlagert einen Teil der Produktion in eine näher gelegene Region. A kann die Abhängigkeit von einem Lieferanten senken, hält aber internationale Verflechtungen aufrecht. B kann Wege verändern, braucht jedoch passende Maschinen, Fachkräfte und Rohstoffe. Rohstoffe können weiterhin importiert werden.</p><p>Vergleiche Kosten, Versorgung, Arbeitsplätze und Umweltwirkungen. „Näher“ beweist weder gute Arbeitsbedingungen noch geringe Gesamtemissionen. Ohne Daten zu Herstellung und Energieversorgung ist kein vollständiger Umweltvergleich möglich.</p>`,[
 ['Welche Aussage über Vorschlag A ist belegt?',['Die Abhängigkeit von einem einzelnen Lieferanten kann sinken.','Alle internationalen Beziehungen werden beendet.','Lieferausfälle werden für immer unmöglich.'],['Mehrere Lieferanten können ein einzelnes Ausfallrisiko verteilen.','Die Lieferanten befinden sich ausdrücklich in verschiedenen Ländern.','Gemeinsame Risiken können weiterhin mehrere Lieferanten treffen.']],
 ['Warum ist Vorschlag B noch kein Beweis für geringe Umweltbelastung?',['Angaben etwa zu Herstellungsverfahren und Energieversorgung fehlen.','Eine kürzere Entfernung muss immer höhere Emissionen verursachen.','Der Produktionsort hat grundsätzlich keine Bedeutung.'],['Transport ist ein Teil des gesamten Produktlebenswegs.','Eine solche allgemeine Regel lässt sich daraus nicht ableiten.','Ort und Wege können relevant sein, reichen aber allein nicht zur Bewertung.']]
 ]],
 ['global_choices','Handlungsmöglichkeiten gemeinsam abwägen',`<p><strong>Erfundener Schulfall:</strong> Die Klasse benötigt für ein Theaterprojekt Kostüme. Vorschlag A kauft 20 neue Stücke zu je 10 €. Vorschlag B leiht 20 vorhandene Stücke zu je 4 € und bezahlt zusätzlich 40 € für Reinigung. A kostet 200 €, B kostet 120 €. Für die Umweltbewertung fehlen unter anderem Transport, Reinigung und die Zahl weiterer Nutzungen. Der niedrigere Preis allein beweist keine geringere Umweltwirkung.</p><p>Handlungsmöglichkeiten liegen auf mehreren Ebenen: Die Klasse kann Mengen planen und Kostüme wiederverwenden. Der Anbieter kann reparierbare Produkte und nachvollziehbare Angaben anbieten. Schule oder Gemeinde können bei der Beschaffung Kriterien für Haltbarkeit und Arbeitsbedingungen festlegen. Politik kann Regeln verändern; Beschäftigte und Interessenvertretungen können Arbeitsbedingungen mitgestalten.</p><p><strong>Entscheidungsauftrag:</strong> Vergleicht A und B in einer Gruppe. Berechnet die Kosten, nennt zwei weitere Kriterien und zwei fehlende Informationen. Begründet eine vorläufige Wahl. Erklärt anschließend, welche Maßnahme eure Klasse selbst umsetzen kann und wofür andere Beteiligte gebraucht werden. Berücksichtigt, dass nicht alle Familien gleich viel Geld oder Zeit beitragen können.</p>`,[
 ['Was kostet Vorschlag B insgesamt?',['120 €.','80 €.','160 €.'],['20 × 4 € + 40 € = 120 €.','80 € sind nur die Leihkosten; die Reinigung fehlt.','Die Reinigung wird einmal mit 40 € berechnet.']],
 ['Welche Aussage trennt Handlungsebenen richtig?',['Die Klasse kann leihen; Beschaffungsregeln der Gemeinde erfordern Entscheidungen der Gemeinde.','Die Klasse kann allein alle Arbeitsbedingungen der Lieferkette festlegen.','Nur private Kaufentscheidungen können etwas verändern.'],['Eigene Entscheidungen und öffentliche Regeln haben unterschiedliche Zuständigkeiten.','Die Klasse kann Kriterien fordern, aber nicht allein alle Bedingungen festlegen.','Auch Unternehmen, öffentliche Einrichtungen und politische Regeln spielen eine Rolle.']]
 ]]
];
t.sections=t.sections.filter(s=>!blocks.some(b=>b[0]===s.id));for(const [sectionId,title,html,raw]of blocks){const quizzes=raw.map(([question,answers,feedback],i)=>({id:sectionId+'_q'+i,question,answers:answers.map((text,j)=>({text,correct:j===0,pts:0,feedback:feedback[j]}))}));t.sections.push({id:sectionId,title:(t.sections.length+1)+'. '+title,content:html+quizzes.map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes});}
t.learningGoals=[...new Set([...t.learningGoals,'Anthropozän und planetare Belastungsgrenzen als Begriffe und Modelle erklären.','Globalisierung und veränderte Lieferbeziehungen anhand eines Falls beurteilen.','Handlungsmöglichkeiten von Haushalten, Unternehmen und öffentlichen Einrichtungen unterscheiden.'])];
t.summary=[...new Set([...t.summary,'Menschliche Eingriffe verändern das Erdsystem; Belastungsgrenzen beschreiben zunehmende Risiken und sind keine exakten Katastrophentermine.','Lieferketten können sich regional und weltweit neu ordnen; kürzere Wege allein beweisen keine nachhaltige Produktion.','Begründete Entscheidungen verbinden Kosten, Umwelt- und soziale Kriterien und benennen fehlende Informationen.'])];
t.subtitle='Lieferketten, Belastungsgrenzen und Entscheidungen in einer vernetzten Welt.';if(t.workshop)t.workshop.title='7. Eine Lieferkette beurteilen';
for(const source of [{title:'RIS: Lehrplan der Mittelschule',url:'https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20007850'},{title:'Stockholm Resilience Centre: Planetary boundaries (Englisch)',url:'https://www.stockholmresilience.org/research/planetary-boundaries.html'},{title:'IUGS/ICS: Stellungnahme zum Anthropozän (Englisch)',url:'https://www.iugs.org/the-anthropocene-iugs-ics-statement/'}])if(!t.sources.some(s=>s.url===source.url))t.sources.push(source);
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');const rf=path.join(root,'js/chapter-revisions.js'),src=fs.readFileSync(rf,'utf8'),c={window:{}};vm.runInNewContext(src,c);c.window.SCIVERSE_CHAPTER_REVISIONS[id]=Math.max(1,c.window.SCIVERSE_CHAPTER_REVISIONS[id]||0);fs.writeFileSync(rf,src.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));console.log('Global sustainability extended: six sections, ten questions, three application/research tasks.');
