const fs=require('fs'),path=require('path'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8')),t=d.math3_1_rationale_zahlen;
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const original1=t.sections.find(s=>s.id==='sec1'),original2=t.sections.find(s=>s.id==='sec2');
original1.title='Rationale Zahlen und ihre Reihenfolge';
original1.content='<p>Eine rationale Zahl lässt sich als Bruch a/b mit ganzen Zahlen a und b und b ≠ 0 schreiben. Dazu gehören positive und negative ganze Zahlen, Brüche und endliche oder periodische Dezimalzahlen: −3 = −3/1, −1/2 = −0,5 und 1/3 = 0,333… .</p><p>Auf dem Zahlenstrahl werden die Zahlen nach rechts größer. Daher gilt −5 &lt; −2 &lt; 0 &lt; 1/2. Bei −10 °C liegt die Temperatur zehn Grad unter 0 °C.</p><div class="interactive-zone"><p>Ein Spiel erlaubt negative Punkte. Du startest bei −3 Punkten und bekommst 5 dazu.</p><label for="kontostand1">Neuer Punktestand</label><input id="kontostand1" type="number"><button type="button" onclick="checkKonto()">Prüfen</button><p id="kontoFb"></p></div>{{QUIZ_m31_q1}}{{QUIZ_m31_order}}';
original1.quizzes=[q('m31_q1','Was bedeutet −10 °C?',[['Zehn Grad unter 0 °C.',true,'Das Minuszeichen kennzeichnet eine Temperatur unter dem Nullpunkt der Celsius-Skala.'],['Zehn Grad über 0 °C.',false,'Das wäre +10 °C. Das Minuszeichen beschreibt die andere Seite von 0 °C.']]),q('m31_order','Welche Zahl ist kleiner: −0,7 oder −0,2?',[['−0,7',true,'−0,7 liegt weiter links auf dem Zahlenstrahl als −0,2.'],['−0,2',false,'−0,2 liegt näher an 0 und ist deshalb größer als −0,7.']])];
const addition={id:'m31_add',title:'Addieren und Subtrahieren',content:'<p>Eine positive Zahl zu addieren bedeutet auf dem Zahlenstrahl nach rechts zu gehen. Eine negative Zahl zu addieren bedeutet nach links zu gehen. Beispiel: −3 + 5 = 2, aber −3 + (−5) = −8.</p><p><strong>Subtrahieren heißt die Gegenzahl addieren:</strong> a − b = a + (−b). Deshalb ist 2 − (−3) = 2 + 3 = 5. Das Minus als Rechenzeichen und das Vorzeichen einer Zahl erfüllen unterschiedliche Aufgaben.</p><div class="interactive-zone" data-signed-line><h3>Rechnen auf dem Zahlenstrahl</h3><label for="signed_start">Startwert</label><input id="signed_start" type="range" min="-5" max="5" step="0.5" value="-3"><label for="signed_change">Zahl</label><input id="signed_change" type="range" min="-5" max="5" step="0.5" value="5"><label for="signed_operation">Rechenart</label><select id="signed_operation"><option value="add">Addieren</option><option value="subtract">Subtrahieren</option></select><p data-signed-result role="status" aria-live="polite"></p><svg data-signed-svg viewBox="0 0 600 140" style="width:100%" role="img" aria-label="Zahlenstrahl von minus zehn bis zehn"></svg><p>Der Kreis markiert den Start, das Quadrat das Ergebnis. Der Pfeil zeigt die Rechenbewegung; bei Änderung 0 gibt es keine Bewegung.</p></div>{{QUIZ_m31_subtract}}{{QUIZ_m31_decimal}}',quizzes:[
q('m31_subtract','Was ist 2 − (−3)?',[['5',true,'Subtrahiere −3, indem du die Gegenzahl +3 addierst: 2 + 3 = 5.'],['−1',false,'Das wäre 2 − 3. Hier wird die negative Zahl −3 subtrahiert.'],['−5',false,'Beide Minuszeichen bedeuten hier zusammen Addition von 3, nicht ein negatives Ergebnis.']]),
q('m31_decimal','Was ist −1,5 + 0,5?',[['−1',true,'Von −1,5 gehst du um 0,5 nach rechts und erreichst −1.'],['−2',false,'Das wäre −1,5 − 0,5. Hier wird eine positive Zahl addiert.'],['1',false,'Die Bewegung um 0,5 reicht noch nicht bis über 0.']])]};
original2.title='Multiplizieren und Dividieren';
original2.content='<p>Bei zwei Faktoren ungleich 0 gilt: Gleiche Vorzeichen ergeben ein positives Produkt, verschiedene ein negatives. Die Beträge werden multipliziert. Zum Beispiel (−4) · (−3) = 12 und (−5) · 4 = −20. Ein Faktor 0 ergibt immer das Produkt 0.</p><p>Warum ist negativ mal negativ positiv? Betrachte die Folge (−2) · 2 = −4, (−2) · 1 = −2, (−2) · 0 = 0. Wenn der zweite Faktor jeweils um 1 sinkt, steigt das Produkt um 2. Das setzt sich fort zu (−2) · (−1) = 2.</p><p>Bei Division gelten dieselben Vorzeichenregeln. (−12) : (−3) = 4, denn 4 · (−3) = −12. Division durch 0 ist nicht definiert.</p><div class="interactive-zone"><label for="mult1">Ergebnis von (−4) · (−3)</label><input id="mult1" type="number"><button type="button" onclick="checkMult()">Prüfen</button><p id="multFb"></p></div>{{QUIZ_m31_q2}}{{QUIZ_m31_divide}}';
original2.quizzes=[q('m31_q2','Was ergibt (−5) · 4?',[['20',false,'Die Faktoren haben verschiedene Vorzeichen. Das Produkt ist negativ.'],['−20',true,'5 · 4 = 20; verschiedene Vorzeichen ergeben −20.']]),q('m31_divide','Was ergibt (−12) : (−3)?',[['4',true,'Gleiche Vorzeichen ergeben ein positives Ergebnis. Die Probe lautet 4 · (−3) = −12.'],['−4',false,'Bei zwei negativen Zahlen ist der Quotient positiv.'],['0',false,'Die beiden Minuszeichen heben nicht den Zahlenwert auf. Die Beträge 12 und 3 ergeben den Quotienten 4.']])];
const fractions={id:'m31_fraction',title:'Negative Brüche und der Betrag',content:'<p>Der <strong>Betrag</strong> ist der Abstand von 0 und daher nie negativ: |−3| = 3 und |3| = 3. Die Gegenzahl von −3 ist +3. Betrag und Gegenzahl sind unterschiedliche Begriffe: Der Betrag von +3 ist 3, seine Gegenzahl ist −3.</p><p>Für Brüche bleiben die Rechenregeln erhalten. −1/2 + 3/4 = −2/4 + 3/4 = 1/4. Beim Multiplizieren: (−2/3) · (3/4) = −6/12 = −1/2.</p><p>Beim Dividieren mit einem Bruch ungleich 0 multiplizierst du mit seinem Kehrwert: (−1/2) : (3/4) = (−1/2) · (4/3) = −4/6 = −2/3. Erst die Vorzeichen beachten, dann rechnen und kürzen.</p>{{QUIZ_m31_absolute}}{{QUIZ_m31_fraction_sum}}',quizzes:[
q('m31_absolute','Wie groß ist |−3,5|?',[['3,5',true,'Der Abstand von −3,5 zu 0 beträgt 3,5. Ein Abstand ist nicht negativ.'],['−3,5',false,'Der Betrag beschreibt den Abstand zu 0, nicht die Lage links oder rechts davon.']]),
q('m31_fraction_sum','Was ist −1/2 + 3/4?',[['1/4',true,'Schreibe −1/2 als −2/4. Dann gilt −2/4 + 3/4 = 1/4.'],['−4/6',false,'Beim Addieren musst du einen gemeinsamen Nenner herstellen; die Nenner werden nicht addiert.'],['−1/4',false,'Drei Viertel nach rechts sind mehr als die zwei Viertel nach links. Das Ergebnis ist positiv.']])]};
t.sections=[original1,addition,original2,fractions];t.subtitle='Vorzeichen, Brüche und Dezimalzahlen sicher verwenden.';
t.learningGoals=['Rationale Zahlen darstellen und der Größe nach ordnen.','Addition und Subtraktion mit Vorzeichen auf dem Zahlenstrahl erklären.','Rationale Zahlen multiplizieren und durch Zahlen ungleich 0 dividieren.','Betrag und Gegenzahl unterscheiden sowie mit negativen Brüchen rechnen.'];t.prerequisites=['math2_2_brueche','math2_4_relative_zahlen'];t.summary=['Rationale Zahlen lassen sich als Brüche ganzer Zahlen mit Nenner ungleich 0 schreiben. Auf dem Zahlenstrahl liegen größere Zahlen weiter rechts.','a − b = a + (−b): Subtraktion wird durch Addition der Gegenzahl ersetzt.','Bei Multiplikation und Division zweier Zahlen ungleich 0 ergeben gleiche Vorzeichen ein positives, verschiedene ein negatives Ergebnis.','Der Betrag ist der nichtnegative Abstand zu 0. Bruchregeln gelten auch für negative Brüche.'];
t.diplom.questions[0].answers[0].feedback='Von −5 führen drei weitere Schritte nach links zu −8: −5 − 3 = −8.';t.diplom.questions[0].answers[1].feedback='−2 wäre das Ergebnis beim Gewinnen von 3 Punkten. Verlieren bedeutet hier −3.';
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
