const fs=require('fs'),path=require('path'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8')),t=d.math2_1_teilbarkeit;
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const newSections=[
{id:'m21_quersumme',title:'Teilbarkeit durch 3 und 9',content:'<p>Die <strong>Quersumme</strong> ist die Summe der Ziffern einer Zahl. Bei 345 ist sie 3 + 4 + 5 = 12. Eine natürliche Zahl ist genau dann durch <strong>3</strong> teilbar, wenn ihre Quersumme durch 3 teilbar ist. Für die Teilbarkeit durch <strong>9</strong> gilt dieselbe Regel mit 9.</p><p>345 ist durch 3 teilbar, aber nicht durch 9. Bei 729 ist die Quersumme 18; deshalb ist 729 durch 3 und durch 9 teilbar. Jede durch 9 teilbare Zahl ist auch durch 3 teilbar; umgekehrt gilt das nicht immer.</p><details><summary>Warum hilft die Quersumme?</summary><p>345 = 3 · 100 + 4 · 10 + 5. Wenn du die Quersumme abziehst, bleibt 3 · 99 + 4 · 9. Dieser Unterschied ist durch 9 und damit auch durch 3 teilbar. Deshalb haben Zahl und Quersumme bei diesen Divisionen denselben Rest.</p></details>{{QUIZ_m21_q5}}{{QUIZ_m21_q6}}',quizzes:[
q('m21_q5','Welche Aussage über 345 stimmt?',[['Durch 3 teilbar, aber nicht durch 9.',true,'Die Quersumme 12 ist durch 3 teilbar, aber nicht durch 9.'],['Durch 3 und durch 9 teilbar.',false,'12 ist kein Vielfaches von 9. Teilbarkeit durch 3 genügt dafür nicht.'],['Weder durch 3 noch durch 9 teilbar.',false,'3 + 4 + 5 = 12. Weil 12 durch 3 teilbar ist, gilt das auch für 345.']]),
q('m21_q6','Welche Zahl ist durch 9 teilbar?',[['729',true,'7 + 2 + 9 = 18. Die Quersumme ist durch 9 teilbar.'],['123',false,'1 + 2 + 3 = 6. Die Zahl ist durch 3, aber nicht durch 9 teilbar.'],['109',false,'Eine 9 an der Einerstelle reicht nicht. Die Quersumme ist 10.']])]},
{id:'m21_prim',title:'Primzahlen und Primfaktoren',content:'<p>Eine <strong>Primzahl</strong> ist eine natürliche Zahl größer als 1 mit genau zwei positiven Teilern: 1 und sich selbst. Beispiele sind 2, 3, 5, 7, 11 und 13. Die 1 ist keine Primzahl: Sie hat nur einen positiven Teiler. Die 2 ist die einzige gerade Primzahl.</p><p>Bei der <strong>Primfaktorzerlegung</strong> schreibst du eine Zahl als Produkt von Primzahlen. Beispiel: 60 = 2 · 30 = 2 · 2 · 15 = <strong>2 · 2 · 3 · 5</strong>. Als Potenzen: 60 = 2² · 3 · 5. Prüfe am Ende, ob alle Faktoren prim sind und ihr Produkt die Ausgangszahl ergibt.</p><div class="interactive-zone" data-prime-exercise><h3>Zerlege 60 selbst</h3><label for="prime_factors">Primfaktoren, mit Leerzeichen getrennt</label><input id="prime_factors" type="text" autocomplete="off" placeholder="z. B. 2 3 5"><p>Jeden Faktor einzeln angeben. Die Reihenfolge ist egal.</p><button type="button">Prüfen</button></div>{{QUIZ_m21_q7}}{{QUIZ_m21_q8}}',quizzes:[
q('m21_q7','Warum ist 1 keine Primzahl?',[['Sie hat nur einen positiven Teiler.',true,'Primzahlen benötigen genau zwei verschiedene positive Teiler. Bei 1 fallen 1 und die Zahl selbst zusammen.'],['Primzahlen müssen gerade sein.',false,'Außer 2 sind alle Primzahlen ungerade. Entscheidend ist die Zahl ihrer Teiler.'],['Sie ist zu klein; Primzahlen beginnen bei 3.',false,'2 ist bereits eine Primzahl: Ihre positiven Teiler sind 1 und 2.']]),
q('m21_q8','Welche vollständige Primfaktorzerlegung ergibt 36?',[['2 · 2 · 3 · 3',true,'Alle Faktoren sind prim und das Produkt ist 36.'],['4 · 9',false,'Das Produkt stimmt, aber 4 und 9 sind nicht prim. Zerlege beide weiter.'],['2 · 3 · 3',false,'Dieses Produkt ist 18. Für 36 fehlt ein weiterer Faktor 2.']])]}
];
t.sections=t.sections.filter(s=>!newSections.some(n=>n.id===s.id));t.sections.splice(1,0,...newSections);
const g=t.sections.find(s=>s.id==='m21_s2');g.content=g.content.replace('Es ist die <b>größte Zahl</b>, durch die man zwei Zahlen teilen kann.','Für zwei positive natürliche Zahlen ist er der größte gemeinsame positive Teiler: Beide Divisionen gehen ohne Rest auf.');
if(!g.content.includes('data-prime-ggt'))g.content+='<div data-prime-ggt><h3>ggT mit Primfaktoren</h3><p>12 = 2² · 3 und 18 = 2 · 3². Nimm nur die gemeinsamen Primfaktoren, jeweils mit dem kleineren Exponenten: ggT(12, 18) = 2 · 3 = 6.</p><p><strong>Anwendung:</strong> 12 rote und 18 blaue Perlen sollen ohne Rest auf möglichst viele gleiche Sets verteilt werden. Es sind 6 Sets mit je 2 roten und 3 blauen Perlen.</p></div>';
const k=t.sections.find(s=>s.id==='m21_s3');if(!k.content.includes('data-prime-kgv'))k.content+='<div data-prime-kgv><h3>kgV mit Primfaktoren</h3><p>Nimm jeden vorkommenden Primfaktor mit dem größeren Exponenten: Bei 12 = 2² · 3 und 18 = 2 · 3² ist kgV(12, 18) = 2² · 3² = 36.</p><p>36 ist durch beide Zahlen teilbar und das kleinste positive gemeinsame Vielfache. Es eignet sich deshalb als gemeinsamer Nenner für Brüche mit den Nennern 12 und 18.</p></div>';
const feedback={m21_q1:['Die letzte Ziffer 8 ist gerade. Tatsächlich gilt 128 : 2 = 64.','Zahlen mit der Endziffer 0, 2, 4, 6 oder 8 sind gerade. 128 endet auf 8.'],m21_q2:['550 endet auf 0. Es gilt 550 : 10 = 55.','105 endet auf 5. Die Zahl ist durch 5 teilbar, aber nicht durch 10.'],m21_q3:['Gemeinsame positive Teiler von 10 und 15 sind 1 und 5. Der größte ist 5.','30 ist ein gemeinsames Vielfaches, kein Teiler von 10 und 15.'],m21_q4:['Vielfache von 4: 4, 8, 12 …; von 6: 6, 12 … . Die erste gemeinsame positive Zahl ist 12.','24 ist zwar ein gemeinsames Vielfaches, aber nicht das kleinste: 12 ist ebenfalls durch 4 und 6 teilbar.'],m21_dip1:['Die Endziffer 5 entscheidet über die Teilbarkeit durch 5: 255 : 5 = 51.','Die Quersumme hilft bei 3 und 9. Für 5 prüfst du die Endziffer.'],m21_dip2:['14 = 2 · 7 und 21 = 3 · 7. Ihr größter gemeinsamer Teiler ist 7.','42 ist ein gemeinsames Vielfaches. Gesucht ist eine Zahl, die 14 und 21 ohne Rest teilt.']};
for(const s of [...t.sections,{quizzes:t.diplom.questions}])for(const x of s.quizzes||[])if(feedback[x.id])x.answers.forEach((a,i)=>{a.feedback=feedback[x.id][i];a.pts=a.correct?10:0;});
t.learningGoals=['Teilbarkeit durch 2, 3, 5, 9 und 10 prüfen und begründen.','Primzahlen erkennen und natürliche Zahlen größer als 1 in Primfaktoren zerlegen.','ggT und kgV mithilfe von Listen oder Primfaktoren bestimmen.','ggT für gleiche Aufteilungen und kgV für gemeinsame Vielfache anwenden.'];
t.summary=['Teilbarkeit bedeutet Division ohne Rest. Für 2, 5 und 10 entscheidet die Endziffer, für 3 und 9 die Quersumme.','Eine Primzahl ist größer als 1 und hat genau zwei positive Teiler. Jede natürliche Zahl größer als 1 lässt sich als Produkt von Primzahlen schreiben.','Beim ggT nimmst du gemeinsame Primfaktoren mit den kleineren Exponenten, beim kgV alle vorkommenden Primfaktoren mit den größeren Exponenten.'];
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
