const fs=require('fs'),path=require('path'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const t=d.math4_7_statistik;t.title='Statistik: Mitte und Streuung';t.subtitle='Daten sortieren, Kennzahlen vergleichen und Boxplots lesen.';
t.sections=[
{id:'sec1',title:'Arithmetischer Mittelwert',content:'<p>Der arithmetische Mittelwert ist die Summe der Werte geteilt durch ihre Anzahl. Drei gemessene Zeiten von 10, 20 und 30 Minuten haben den Mittelwert (10 + 20 + 30) : 3 = 20 Minuten.</p><p>Der Mittelwert beschreibt einen rechnerischen Ausgleich. Er muss nicht selbst vorkommen und sagt nicht, was für eine einzelne Person „normal“ ist. Bei 2 und 5 ist er 3,5. Einzelne sehr große oder kleine Werte können ihn stark verändern.</p>{{QUIZ_m47_q1}}{{QUIZ_m47_mean}}',quizzes:[
q('m47_q1','Drei Zeiten sind 10, 20 und 30 Minuten. Wie groß ist ihr Mittelwert?',[['20 Minuten',true,'Die Summe 60 wird durch die Anzahl 3 geteilt.'],['60 Minuten',false,'60 ist die Summe. Für den Mittelwert fehlt noch die Division durch 3.']]),
q('m47_mean','Muss der Mittelwert in der Datenliste vorkommen?',[['Nein.',true,'Bei 2 und 5 beträgt er 3,5; dieser Wert steht nicht in der Liste.'],['Ja, immer.',false,'Der Mittelwert wird berechnet und muss kein beobachteter Wert sein.']])]},
{id:'sec2',title:'Median und Modus',content:'<p>Sortiere zuerst die Werte. Bei einer ungeraden Anzahl ist der <strong>Median</strong> der mittlere Wert: 1, 5, 9 ergibt 5. Bei gerader Anzahl berechnest du den Mittelwert der beiden mittleren Werte: 1, 3, 7, 9 ergibt (3 + 7) : 2 = 5.</p><p>Der <strong>Modus</strong> ist der am häufigsten vorkommende Wert. Bei 2, 2, 3, 7 ist er 2. Es kann mehrere gleich häufigste Werte geben: Bei 2, 2, 3, 3 sind 2 und 3 Modi. Wenn alle Werte gleich häufig sind, gibt es keinen einzelnen hervorstechenden Modus; das Labor kennzeichnet diesen Fall ausdrücklich.</p>{{QUIZ_m47_q2}}{{QUIZ_m47_even}}',quizzes:[
q('m47_q2','Was ist der Median der sortierten Werte 1, 5, 9?',[['5',true,'5 steht bei drei Werten genau in der Mitte.'],['9',false,'9 ist das Maximum. Der Median steht nach dem Sortieren in der Mitte.']]),
q('m47_even','Was ist der Median von 1, 3, 7, 9?',[['5',true,'Die beiden mittleren Werte sind 3 und 7: (3 + 7) : 2 = 5.'],['3',false,'Bei vier Werten gibt es zwei mittlere Werte. Du musst 3 und 7 mitteln.'],['7',false,'7 ist nur einer der beiden mittleren Werte. Auch 3 gehört zur Berechnung.']])]},
{id:'m47_box',title:'Spannweite, Quartile und Boxplot',content:'<p>Die <strong>Spannweite</strong> ist Maximum minus Minimum. Quartile gliedern geordnete Daten in vier Bereiche. Hier verwenden wir folgende Rechenregel: Bei ungerader Anzahl wird der Gesamtmedian aus den beiden Hälften ausgeschlossen. Der Median der unteren Hälfte ist Q1, der Median der oberen Hälfte Q3. Andere Bücher und Programme können andere Quartilregeln verwenden.</p><p>Beispiel: 2, 4, 6, 8, 10, 12. Median = 7; untere Hälfte 2, 4, 6 ergibt Q1 = 4; obere Hälfte 8, 10, 12 ergibt Q3 = 10. Die Spannweite ist 12 − 2 = 10.</p><p>Ein einfacher <strong>Boxplot</strong> stellt fünf Kennzahlen auf einer Zahlenskala dar: Minimum, Q1, Median, Q3 und Maximum. Die Box reicht von Q1 bis Q3, eine Linie darin markiert den Median. Hier reichen die äußeren Linien bis Minimum und Maximum. Varianten mit besonderen Ausreißergrenzen werden in diesem Labor nicht verwendet.</p>{{QUIZ_m47_boxread}}{{QUIZ_m47_range}}',quizzes:[
q('m47_boxread','Von wo bis wo reicht die Box im Boxplot?',[['Von Q1 bis Q3.',true,'Die Box liegt zwischen unterem und oberem Quartil. Der Median wird darin markiert.'],['Vom Minimum bis zum Maximum.',false,'Das ist die gesamte Spannweite der Darstellung, einschließlich der äußeren Linien.'],['Vom Mittelwert bis zum Maximum.',false,'Der Mittelwert ist für diesen einfachen Boxplot keine der fünf benötigten Kennzahlen.']]),
q('m47_range','Welche Spannweite haben die Werte 2, 4, 6, 8, 10, 12?',[['10',true,'Maximum minus Minimum: 12 − 2 = 10.'],['12',false,'12 ist das Maximum. Für die Spannweite musst du noch das Minimum 2 abziehen.'],['7',false,'7 ist hier Mittelwert und Median, nicht die Spannweite.']])]},
{id:'m47_lab',title:'Daten verändern und vergleichen',content:'<p>Die folgenden Zeiten sind erfundene Messwerte in Minuten. Vergleiche zuerst Mittelwert und Median. Ersetze dann den größten Wert durch 60. Begründe, warum sich die beiden Kennzahlen unterschiedlich verändern. Ein ungewöhnlich hoher Wert ist nicht automatisch ein Messfehler.</p><div class="interactive-zone" data-statistics-lab><label for="stats_values">2 bis 20 Werte zwischen 0 und 100 Minuten, getrennt durch Leerzeichen oder Semikolon</label><textarea id="stats_values" rows="3">2 4 6 8 10 12</textarea><p>Dezimalkomma ist erlaubt, z. B. 2,5; 3,5. Keine Namen oder persönlichen Daten nötig.</p><button type="button" data-stats-calculate>Auswerten</button><button type="button" data-stats-preset="base">Ausgangsdaten</button><button type="button" data-stats-preset="high">Größten Wert auf 60 setzen</button><p data-stats-status role="status" aria-live="polite"></p><div data-stats-output></div></div>{{QUIZ_m47_change}}',quizzes:[
q('m47_change','In 2, 4, 6, 8, 10, 12 wird nur 12 durch 60 ersetzt. Was passiert?',[['Der Mittelwert steigt, der Median bleibt 7.',true,'Die Summe steigt, aber die mittleren Werte 6 und 8 ändern sich nicht.'],['Mittelwert und Median bleiben gleich.',false,'Der Mittelwert berücksichtigt alle Werte und steigt durch die größere Summe.'],['Der Median wird 60.',false,'60 ist das neue Maximum. In der sortierten Liste stehen weiterhin 6 und 8 in der Mitte.']])]}];
t.diplom.questions=[q('m47_dip1','Was bezeichnet der Modus?',[['Einen am häufigsten vorkommenden Wert.',true,'Der Modus beschreibt die größte Häufigkeit. Es kann mehrere Modi geben.'],['Die Mitte der sortierten Werte.',false,'Das beschreibt den Median. Für den Modus zählst du die Häufigkeiten.']])];
t.learningGoals=['Arithmetischen Mittelwert, Median und Modus unterscheiden und bestimmen.','Spannweite und Quartile nach einer angegebenen Regel berechnen.','Einen einfachen Boxplot anhand seiner fünf Kennzahlen lesen.','Den Einfluss veränderter Daten auf Mittelwert und Median erklären.'];t.prerequisites=['math3_11_statistik'];t.summary=['Mittelwert = Summe : Anzahl. Der Median ist die Mitte der sortierten Daten; bei gerader Anzahl werden die zwei mittleren Werte gemittelt.','Der Modus beschreibt die größte Häufigkeit, die Spannweite den Abstand zwischen Maximum und Minimum.','Ein einfacher Boxplot zeigt Minimum, Q1, Median, Q3 und Maximum. Die Quartilregel muss angegeben sein.','Einzelne extreme Werte beeinflussen den Mittelwert stärker als den Median; keine einzelne Kennzahl beschreibt sämtliche Eigenschaften der Daten.'];t.sources=[{label:'NIST: Aufbau und Varianten von Boxplots',url:'https://www.itl.nist.gov/div898/handbook/eda/section3/boxplot.htm'}];
// Correct the earlier introduction without claiming that the full year-three chapter is reviewed.
for(const s of d.math3_11_statistik.sections)s.content=s.content.replace("Der Mittelwert (Durchschnitt) sagt dir, was 'normal' ist.",'Der Mittelwert (Durchschnitt) ist ein rechnerischer Ausgleich der Werte. Er muss nicht selbst vorkommen und beschreibt nicht, was für Einzelne normal ist.');
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
