const fs=require('fs'),path=require('path');const file=path.join(__dirname,'../lang/de.json');const data=JSON.parse(fs.readFileSync(file,'utf8'));
// Specific explanations for each existing distractor; not a generic fallback.
const notes={
'0:1':['Eine Vermutung wird erst durch Beobachtungen prüfbar. Vergleiche zum Beispiel die Mondform an mehreren Tagen.','Sternbildgeschichten sind Kulturgeschichte. Astronomie untersucht messbare Eigenschaften und Veränderungen am Himmel.'],
'0:2':['Namen allein erklären keine Beobachtung. Astrophysik nutzt etwa Gravitation, Strahlung und Energie für Erklärungen.','Wetter auf der Erde ist vor allem Gegenstand der Meteorologie. Astrophysik untersucht physikalische Vorgänge im Weltall.'],
'1:1':['Die Sonne im Mittelpunkt kennzeichnet ein heliozentrisches Modell. „Geo“ bezieht sich auf die Erde.','Geozentrisch beschreibt die Anordnung im Modell, nicht die Größe von Planeten.'],
'1:2':['Kepler beschrieb Planetenbahnen. Galileo beobachtete unter anderem Jupitermonde mit dem Fernrohr.','Diese Geräte gehören zu anderen Epochen. Tycho beobachtete lange vor Raumsonden; Aristoteles lebte in der Antike.'],
'2:1':['Die Gravitation wirkt auch nahe der Sonne. Der Flächensatz verknüpft den Abstand mit der Bewegung entlang der Bahn.','Der Planet bleibt nicht stehen. Nahe der Sonne legt er in gleicher Zeit eine längere Strecke auf seiner Bahn zurück.'],
'2:2':['Keplers drittes Gesetz verbindet Umlaufzeit und Bahngröße. Planetengröße und Helligkeit sind andere Eigenschaften.','Ein Jahr ist die Umlaufzeit der Erde. Weiter außen liegende Planeten benötigen für einen Sonnenumlauf länger.'],
'3:1':['Ohne Gravitation würde sich der Körper geradlinig weiterbewegen. Die Anziehung krümmt seine Bahn.','Ein Orbit ist eine Fallbewegung mit seitlicher Geschwindigkeit. Auch ein geostationärer Satellit bewegt sich um die Erde.'],
'3:2':['Die Erdgravitation reicht weit ins All. Sie hält den Satelliten auf seiner gekrümmten Bahn.','Ein Satellit wird nicht von Luft getragen. Luftwiderstand würde eine niedrige Umlaufbahn vielmehr abbremsen.'],
'4:1':['Webb misst elektromagnetische Strahlung, vor allem im Infrarotbereich. Schall benötigt ein materielles Medium.','Webb ist für astronomische Infrarotbeobachtungen ausgelegt. Wetterkarten liefern darauf spezialisierte Erdsatelliten.'],
'4:2':['Wiederholte Aufnahmen großer Himmelsflächen erlauben es, Veränderungen bei vielen Objekten zu erkennen.','Rubin ist ein bodengebundenes Observatorium. Probenrückführung ist eine andere Aufgabe für Raumsonden.'],
'4:3':['Nicht die Größe allein machte das Fernrohr bedeutsam. Die Beobachtungen lieferten neue Belege zu Himmelskörpern.','Dunkle Materie wird nicht wie eine leuchtende Oberfläche fotografiert. Galileo beobachtete etwa Jupitermonde und Venusphasen.'],
'5:1':['Die Hintergrundstrahlung stammt aus einer frühen Phase des Universums. Eine Taschenlampe ist eine lokale Lichtquelle.','Sie erreicht uns aus dem Kosmos und ist kein Wetterphänomen unserer Atmosphäre.'],
'5:2':['Galaxien entstanden erst nach der frühen heißen Phase. Die zeitliche Reihenfolge darf nicht umgekehrt werden.','Planeten entstanden nicht vor der frühen heißen Phase. Für ihre Entstehung mussten sich zuvor Strukturen und Sterne bilden.'],
'5:3':['Die Erde entstand viel später als die frühe heiße Phase des Universums. Sie kann daher nicht älter als das Universum sein.','Die Sonne entstand erst Milliarden Jahre später. Der Urknall bezeichnet die frühe Entwicklung des Universums, kein lokales Feuerwerk.'],
'6:1':['Planeten mussten erst aus Material in der jungen Scheibe wachsen. Sie waren nicht schon als fertige Planeten vorhanden.','Die Scheibe umgab die junge Sonne. Die Erde entstand selbst erst aus Material dieser Scheibe.'],
'6:2':['Die ähnlichen Bahnebenen erklären sich durch die gemeinsame Entstehungsscheibe, nicht durch eine feste Verbindung.','Die Ekliptik bezieht sich auf die Ebene der Erdbahn. Sie ist keine Oberfläche der Sonne.'],
'7:1':['Sterne sind große, selbstleuchtende Himmelskörper. Ein Meteor ist eine Leuchterscheinung in der Atmosphäre.','Der Sonnenuntergang entsteht durch Erdrotation. Eine Sternschnuppe hat mit dem täglichen Sonnenuntergang nichts zu tun.'],
'7:2':['Eine Feuerkugel ist eine besonders helle Meteorerscheinung in der Atmosphäre, kein Planet.','Ein Krater ist eine Struktur am Boden. Die Feuerkugel bezeichnet das helle Leuchten in der Atmosphäre.'],
'7:3':['Die Leuchterscheinungen entstehen durch kleine Teilchen in der Atmosphäre. Die Sterne selbst fallen dabei nicht zur Erde.','Der Mond bleibt als Körper erhalten. Mondphasen zeigen unterschiedliche Ansichten seiner beleuchteten Hälfte.'],
'8:1':['Gas und Staub treten aus erwärmtem Kometenmaterial aus. Ein Ring um Jupiter ist ein anderes Phänomen.','Ein natürlicher Komet braucht keinen Motor. Sonnenenergie erwärmt sein Material und ermöglicht das Ausgasen.'],
'8:2':['„Archiv“ ist hier ein Vergleich: Das Material enthält Hinweise auf frühere Bedingungen im Sonnensystem.','Viele dieser Körper bewahren sehr altes Material. Gerade dieses Material macht sie für die Entstehungsgeschichte interessant.'],
'9:1':['Merkur ist ein Gesteinsplanet mit äußerst dünner Gashülle. Eine dichte Atmosphäre könnte Wärme stärker verteilen.','Merkur ist der innerste Planet. Seine Entfernung allein erklärt die starken Unterschiede zwischen Tag- und Nachtseite nicht.'],
'9:2':['Auf dauerhaft heißen, beleuchteten Flächen wäre Eis nicht beständig. Geschützte Polkrater bleiben dagegen sehr kalt.','Merkur besitzt keine dichte Atmosphäre mit solchen Regenwolken. Dauerhaft verschattete Krater sind der wichtige Hinweis.'],
'10:1':['Die Wärmebedingungen lassen sich durch Sonnenenergie und Atmosphäre erklären. Venus enthält keinen eigenen Stern.','Eine dauernde Feuerdecke ist keine Erklärung. Die dichte Atmosphäre erschwert die Abgabe von Energie ins All.'],
'10:2':['Radar dient der Messung und Abbildung. Es ist keine Kühlanlage für einen Planeten.','Radar ist elektromagnetische Strahlung. Es kann Informationen liefern, ohne die Gravitation zu ersetzen.'],
'11:1':['Die Erde ist ein Gesteinsplanet. Ihre gut untersuchten Eigenschaften machen sie zu einem nützlichen Vergleichsbeispiel.','Die Erde besitzt eine Atmosphäre. Gerade diese können wir mit den Gashüllen anderer Planeten vergleichen.'],
'11:2':['Die wichtige Funktion ist die Beobachtung und Messung. Eine Änderung der Erdmasse ist nicht das Ziel solcher Satelliten.','Satelliten beobachten Wolken und Wetter. Sie beseitigen die Wolken nicht.'],
'12:1':['Mars besitzt heute keine weltweiten flüssigen Ozeane. Gesucht werden Hinweise auf frühere, wasserreichere Bedingungen.','Mars ist deutlich kälter als Venus. Spuren früheren Wassers begründen das Interesse an seiner Vergangenheit.'],
'12:2':['Perseverance arbeitet auf Mars. Saturnringe und Jupitermonde sind weit entfernte andere Ziele.','Auf Mars gibt es heute keine solchen offenen Meere. Untersucht und gesammelt werden Gesteinsproben.'],
'13:1':['Jupiter ist der größte Planet des Sonnensystems. Er besitzt keine feste Außenfläche wie ein kleiner Gesteinskörper.','Jupiter besteht überwiegend aus Wasserstoff und Helium. Sein Inneres lässt sich nicht als Sammlung von Eiswürfeln beschreiben.'],
'13:2':['Juno sammelt physikalische Messdaten. Pflanzen auf Jupiter sind nicht das Untersuchungsobjekt der Mission.','Juno untersucht Jupiter aus dem Raum. Eine Landung in einem Wassermeer beschreibt diese Mission nicht.'],
'14:1':['Die Ringe bestehen aus vielen einzelnen Teilchen. Sie sind keine zusammenhängende feste Platte.','Das Ringmaterial besteht vor allem aus Eispartikeln mit weiteren Bestandteilen. Es brennt nicht als flüssiges Feuer.'],
'14:2':['Beide Monde sind viel kleiner als die Sonne. Interessant sind ihre besonderen Stoffkreisläufe und inneren Bedingungen.','Titan und Enceladus umkreisen Saturn und sind Monde. Sie sind keine selbstleuchtenden Sterne.'],
'15:1':['Eine starke Achsenneigung verändert die Beleuchtung im Jahreslauf besonders stark. Sie beseitigt Jahreszeiten nicht.','Die Achsenneigung und der Abstand zur Sonne sind verschiedene Größen. Uranus liegt weit außerhalb der Erdbahn.'],
'15:2':['Die Beobachtungen betreffen unter anderem Atmosphäre und Ringe. Sie belegen keine bewachsene feste Oberfläche.','Uranus besitzt Ringe. Infrarotbeobachtungen können feine Strukturen davon sichtbar machen.'],
'16:1':['Neptun ist ein äußerer Eisriese. Der innerste Gesteinsplanet ist Merkur.'],
'17:1':['Sterne sind keine typischen Körper des Kuipergürtels. Dort befinden sich kleine eisige Körper und Zwergplaneten.','Der Kuipergürtel liegt weit jenseits der Erde. Wolken in unserer Atmosphäre gehören nicht zu dieser Region.'],
'17:2':['Die Energie der Sonne stammt aus Kernfusion in ihrem Inneren. Der Kuipergürtel bewahrt Material ihrer Entstehungszeit.','Galaxien sind viel größere Systeme. Der Kuipergürtel ist eine Region innerhalb unseres Sonnensystems.'],
'18:1':['Die Korona ist gasförmige Sonnenatmosphäre, keine feste Kruste. Sonnenwind bezeichnet einen Teilchenstrom, keinen Regen.','Die Photosphäre ist die sichtbare Schicht der Sonne. Die Ekliptik bezeichnet eine Bahnebene, nicht die Korona.'],
'18:2':['Segelboote nutzen Wind in der Erdatmosphäre. Sonnenwind ist ein Strom geladener Teilchen aus der Sonne.','Sonnenwind verändert vor allem die Umgebung des Erdmagnetfelds. Ein tägliches Größenwachstum der Erde folgt daraus nicht.'],
'18:3':['Die Sonde untersucht die Sonne und ihre Umgebung. Saturns Ringe sind kein Holzmaterial und nicht ihr Forschungsziel.','Die Mission misst Vorgänge nahe der Sonne. Das Wachstum von Meteoriten in Schulbüchern ist keine physikalische Fragestellung.'],
'19:1':['Eine Galaxie umfasst eine riesige Anzahl von Sternen und weiteres Material. Ein einzelner Planet ist viel kleiner.','Gas ist ein Bestandteil, aber keine vollständige Beschreibung. Sterne, Staub und weitere Masse gehören ebenfalls dazu.'],
'19:2':['Das Teleskop sammelt heute ankommendes Licht. Weil Licht Zeit zum Reisen braucht, zeigt es einen früheren Zustand.','Der Blick in die Vergangenheit folgt aus der Lichtlaufzeit, nicht aus einer täglichen Verkleinerung der Galaxie.'],
'19:3':['Die Abstände zwischen einzelnen Sternen sind im Vergleich zu ihren Größen riesig. Direkte Sternkollisionen sind daher selten.','Gravitation kann Form und Bewegung verändern. Galaxien verschwinden bei einer Begegnung nicht einfach.'],
'20:1':['Tinte wäre gewöhnliche Materie mit optischen Eigenschaften. Dunkle Materie wird vor allem durch ihre Gravitationswirkung erschlossen.','Eine längere Belichtung erklärt die beobachteten Gravitationswirkungen nicht. Dunkle Materie ist kein bloßer Fotofehler.'],
'20:2':['Die Ablenkung verändert beobachtete Formen und Positionen. Eine beliebige Farbgebung wäre keine Massenmessung.','Das Licht erreicht uns auf veränderten Wegen. Gerade seine beobachtete Ablenkung erlaubt Rückschlüsse auf Masse.'],
'21:1':['Saturnringe sind Material in unserem Sonnensystem. Die beiden Begriffe beziehen sich auf andere kosmologische Beobachtungen.','Dunkle Energie bezeichnet einen noch ungeklärten Beitrag in kosmologischen Modellen. Sie ist kein abgefüllter Stoff.'],
'21:2':['Die Daten werden genutzt, um kosmologische Modelle zu prüfen. Eine Sortierung ohne Auswertung erklärt keine Beobachtung.','Die Vermessungen nutzen Instrumente und große Datenmengen. Das Ziel ist nicht, alle Sterne mit bloßem Auge zu sehen.'],
'21:3':['Die physikalische Natur ist noch nicht abschließend geklärt. Beobachtungen begrenzen mögliche Erklärungen.','Sonnenwind ist ein Teilchenstrom unserer Sonne. Dunkle Energie betrifft die beschleunigte kosmische Expansion.']
};
notes['16:1'].push('Neptun umkreist die Sonne als Planet. Der Mond der Erde ist ein anderer Himmelskörper.');
notes['16:2']=['Neptun besitzt eine Atmosphäre. Die Lage der Polarlichter hängt auch mit der Geometrie seines Magnetfelds zusammen.','Saturns Ringe sind kein Auslöser der Neptun-Polarlichter. Entscheidend sind geladene Teilchen und Neptuns Magnetfeld.'];
let count=0;for(const[key,pair]of Object.entries(notes)){const[s,q]=key.split(':').map(Number);const question=data.astronomie.sections[s].quizzes[q];pair.forEach((feedback,i)=>{question.answers[i+1].feedback=feedback;count++;});}
// Avoid placing Eris in the classical belt without the scattered-disk distinction.
data.astronomie.sections[17].quizzes[1].answers[0].text='Viele eisige Körper und Zwergplaneten wie Pluto, Haumea und Makemake.';
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');console.log(`Added ${count} specific astronomy explanations.`);
