const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),file=path.join(__dirname,'../lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.math2_6_prop_prozent;
const direct=t.sections.find(s=>s.id==='sec1'),$=cheerio.load(direct.content);
$('p').first().text('Bei konstantem Stückpreis und ohne Grundgebühr ist der Gesamtpreis direkt proportional zur Menge. Doppelter Menge entspricht der doppelte Preis; der Quotient Preis : Menge bleibt gleich. Mengenrabatte können diese Zuordnung verändern.');
$('#pizza_slider').removeAttr('oninput');direct.content=$('body').html();direct.title='Direkte Proportionalität';
direct.quizzes[0].question='3 Hefte kosten 6 €. Der Stückpreis bleibt gleich. Was kosten 6 Hefte?';
for(const a of direct.quizzes[0].answers)a.feedback=a.feedback.replaceAll('Drinks','Hefte');
const discount=t.sections.find(s=>s.id==='sec2'),$d=cheerio.load(discount.content);$d('#rabatt_input').attr({min:0,max:100,step:'any'});$d('button').removeAttr('onclick');discount.content=$d('body').html();discount.title='Prozent und Rabatt';
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const added=[
{id:'m26_indirect',title:'Indirekte Proportionalität',content:'<p>Eine Gruppe teilt einen festen Gesamtbetrag von <strong>60 €</strong> gleichmäßig auf. Bei 2 Personen zahlt jede 30 €, bei 4 Personen 15 €. Doppelt so viele Personen bedeuten den halben Betrag pro Person. Das ist <strong>indirekte Proportionalität</strong>.</p><p>Hier bleibt das <strong>Produkt</strong> gleich: Personenanzahl · Betrag pro Person = 60 €. Allgemein gilt y = k : x mit x ungleich 0. Im Beispiel sind nur positive ganze Personenanzahlen sinnvoll. Der feste Gesamtbetrag ist Voraussetzung.</p><div class="interactive-zone" data-inverse-lab><h3>Einen festen Betrag teilen</h3><label for="inverse_people">Personenanzahl</label><input id="inverse_people" type="range" min="1" max="12" step="1" value="2"><p id="inverse_result" role="status" aria-live="polite"></p><p>Geldbeträge werden hier auf Cent gerundet; bei manchen Gruppengrößen bleibt beim tatsächlichen Verteilen ein kleiner Rest.</p><table><caption>Beispiele bei insgesamt 60 €</caption><thead><tr><th>Personen</th><th>Euro pro Person</th><th>Produkt</th></tr></thead><tbody><tr><td>2</td><td>30</td><td>60</td></tr><tr><td>3</td><td>20</td><td>60</td></tr><tr><td>4</td><td>15</td><td>60</td></tr><tr><td>6</td><td>10</td><td>60</td></tr></tbody></table></div>{{QUIZ_m26_inverse}}{{QUIZ_m26_product}}',quizzes:[
q('m26_inverse','60 € werden statt auf 3 auf 6 Personen gleichmäßig aufgeteilt. Wie ändert sich der Betrag pro Person?',[['Er halbiert sich von 20 € auf 10 €.',true,'Bei festem Gesamtbetrag führt die doppelte Personenanzahl zum halben Anteil.'],['Er verdoppelt sich von 20 € auf 40 €.',false,'Das würde den festen Gesamtbetrag überschreiten. Mehr Personen teilen sich dieselben 60 €.'],['Er bleibt bei 20 €.',false,'6 · 20 € wären 120 €. Der Gesamtbetrag beträgt weiterhin 60 €.']]),
q('m26_product','Was bleibt bei dieser indirekten Proportionalität gleich?',[['Personenanzahl · Betrag pro Person',true,'Das Produkt ergibt immer den festen Gesamtbetrag.'],['Betrag pro Person : Personenanzahl',false,'Ein konstanter Quotient kennzeichnet direkte Proportionalität. Hier bleibt das Produkt konstant.'],['Personenanzahl + Betrag pro Person',false,'Diese Summe hat hier keine sinnvolle gemeinsame Einheit und ist auch nicht konstant.']])]},
{id:'m26_decide',title:'Passt ein proportionales Modell?',content:'<p>„Je mehr, desto mehr“ reicht als Begründung für direkte Proportionalität nicht aus. Beispiel mit erfundenen Preisen: Eine Bestellung kostet <strong>5 € Grundgebühr plus 2 € je Heft</strong>. Zwei Hefte kosten 9 €, vier Hefte 13 €. Doppelte Menge kostet hier nicht doppelt so viel.</p><p>Prüfe bei einer Zuordnung zuerst die Bedingungen. Direkt proportional: Der Quotient y : x ist konstant. Indirekt proportional: Das Produkt x · y ist konstant. Trifft beides nicht zu, passt keines dieser beiden Modelle. In Sachaufgaben musst du außerdem prüfen, ob etwa Stückpreis, Gesamtmenge oder Arbeitsleistung tatsächlich gleich bleiben.</p>{{QUIZ_m26_fee}}{{QUIZ_m26_unit}}',quizzes:[
q('m26_fee','5 € Grundgebühr plus 2 € je Heft: Ist der Gesamtpreis direkt proportional zur Anzahl?',[['Nein, wegen der zusätzlichen Grundgebühr.',true,'2 Hefte kosten 9 €, 4 Hefte 13 €. Der Quotient Preis : Anzahl bleibt nicht gleich.'],['Ja, weil mehr Hefte mehr kosten.',false,'Steigender Preis allein genügt nicht. Bei direkter Proportionalität müsste doppelter Menge der doppelte Preis entsprechen.'],['Ja, weil jedes Heft 2 € kostet.',false,'Der Gesamtpreis enthält zusätzlich 5 €. Dieser feste Anteil verhindert die direkte Proportionalität.']]),
q('m26_unit','4 gleich teure Hefte kosten insgesamt 10 €. Was kosten 6 Hefte ohne Grundgebühr oder Rabatt?',[['15 €',true,'Ein Heft kostet 10 € : 4 = 2,50 €. Sechs kosten 6 · 2,50 € = 15 €.'],['12 €',false,'Zwei zusätzliche Hefte bedeuten nicht automatisch 2 € mehr. Bestimme zuerst den Stückpreis.'],['20 €',false,'20 € wäre der Preis für die doppelte Menge, also 8 Hefte.']])]},
{id:'m26_percent_values',title:'Grundwert, Prozentwert und Prozentsatz',content:'<p>Der <strong>Grundwert G</strong> ist das Ganze (100 %). Der <strong>Prozentwert W</strong> ist der betrachtete Anteil. Der <strong>Prozentsatz p %</strong> beschreibt die Größe dieses Anteils. In der Formel ist p die Zahl vor dem Prozentzeichen.</p><table><caption>Drei gesuchte Größen</caption><thead><tr><th>Gesucht</th><th>Rechnung</th><th>Beispiel</th></tr></thead><tbody><tr><td>Prozentwert W</td><td>W = G · p : 100</td><td>25 % von 80 €: 80 · 25 : 100 = 20 €</td></tr><tr><td>Prozentsatz p</td><td>p = W : G · 100</td><td>20 € von 80 €: 20 : 80 · 100 = 25, also 25 %</td></tr><tr><td>Grundwert G</td><td>G = W · 100 : p</td><td>20 € entsprechen 25 %: 20 · 100 : 25 = 80 €</td></tr></tbody></table><p>Bei der Berechnung des Prozentsatzes darf G nicht 0 sein; beim Berechnen des Grundwerts darf p nicht 0 sein. Kontrolliere den Bezug: Ein Rabattbetrag ist der abgezogene Anteil, nicht der neue Preis.</p><p><strong>Ohne Formel:</strong> Wenn 25 % genau 20 € sind, dann ist 1 % gleich 20 € : 25 = 0,80 €. Daher sind 100 % gleich 80 €.</p>{{QUIZ_m26_rate}}{{QUIZ_m26_base}}',quizzes:[
q('m26_rate','12 von 40 Lernenden kommen zu Fuß. Wie viel Prozent sind das?',[['30 %',true,'12 : 40 · 100 = 30. Der Grundwert sind alle 40 Lernenden.'],['12 %',false,'12 ist die Anzahl, nicht der Prozentsatz. Beziehe sie auf die Gesamtzahl 40.'],['40 %',false,'40 ist hier der Grundwert. Berechne den Anteil 12/40.']]),
q('m26_base','15 € entsprechen 20 % eines ursprünglichen Preises. Wie hoch war dieser Preis?',[['75 €',true,'1 % entspricht 15 € : 20 = 0,75 €. 100 % entsprechen 75 €.'],['3 €',false,'3 € wären 20 % von 15 €. Hier sind 15 € bereits der Prozentwert.'],['35 €',false,'20 % sind keine 20 €, die man einfach addieren kann. Gesucht ist der Grundwert.']])]}
];
t.sections=t.sections.filter(s=>!added.some(a=>a.id===s.id));t.sections.splice(1,0,added[0],added[1]);t.sections.push(added[2]);
t.learningGoals=['Direkte und indirekte Proportionalität anhand von Quotient und Produkt unterscheiden.','Passende proportionale Modelle für Sachaufgaben auswählen und ihre Voraussetzungen benennen.','Grundwert, Prozentwert und Prozentsatz bestimmen.','Rabattbetrag und neuen Preis unterscheiden und berechnen.'];
t.summary=['Direkte Proportionalität: y : x bleibt konstant. Indirekte Proportionalität: x · y bleibt konstant.','Mehr bedeutet nicht automatisch proportional mehr: Eine zusätzliche Grundgebühr kann die direkte Proportionalität verhindern.','W = G · p : 100; p = W : G · 100; G = W · 100 : p. Die Nenner dürfen nicht 0 sein.','Beim Rabatt wird der Rabattbetrag vom ursprünglichen Preis abgezogen.'];
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');
