const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),id='geo_1_ernaehrung_landwirtschaft';
const file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),topic=data[id];
const additions=[
 {id:'food_climate',title:'5. Wetter, Klima und unsere Ernten',content:`<p><strong>Wetter</strong> beschreibt den Zustand der Atmosphäre an einem Ort zu einer bestimmten Zeit: Heute regnet es in Wien. <strong>Klima</strong> beschreibt Wetterverhältnisse über viele Jahre, etwa typische Temperaturen, Niederschläge und ihre Schwankungen. Ein heißer Tag allein zeigt keinen Klimatrend. Dafür untersucht man lange Messreihen.</p><p>Treibhausgase wie Kohlendioxid nehmen einen Teil der Wärmestrahlung der Erde auf und geben selbst Strahlung ab. Der natürliche Treibhauseffekt wärmt die Erdoberfläche. Menschliche Aktivitäten, etwa das Verbrennen von Kohle, Erdöl und Erdgas, erhöhen die Menge an Treibhausgasen und verstärken diesen Effekt.</p><p>Für die Landwirtschaft zählt auch, <em>wann</em> Wärme und Wasser auftreten. Trockenheit während des Wachstums kann Ernten verringern; Hitze kann Pflanzen schädigen. Wirkungen unterscheiden sich nach Region, Pflanzenart und Anbauweise. Aus einem einzelnen Ernteausfall lässt sich sein Anteil durch den Klimawandel nicht einfach ablesen.</p>`,questions:[
 ['Welche Untersuchung kann eine langfristige Klimaänderung am Anbauort zeigen?',['Vergleich langer Messreihen von Temperatur und Niederschlag.','Messung der Temperatur an einem besonders heißen Nachmittag.','Vergleich zweier Fotos derselben Ernte.'],['Lange Messreihen machen Veränderungen gegenüber kurzfristigen Schwankungen erkennbar.','Ein Nachmittag beschreibt Wetter, keinen langfristigen Trend.','Fotos können Unterschiede zeigen, belegen aber deren klimatische Ursache nicht.']],
 ['Warum verstärkt das Verbrennen von Kohle den Treibhauseffekt?',['Dabei entsteht zusätzliches Kohlendioxid, ein Treibhausgas.','Dabei wird vor allem die Sonne heißer.','Dabei verschwindet der natürliche Treibhauseffekt.'],['Zusätzliches Kohlendioxid verändert den Strahlungshaushalt der Erde.','Die Erwärmung wird hier nicht durch eine heißere Sonne erklärt.','Der natürliche Effekt bleibt bestehen und wird verstärkt.']]
 ]},
 {id:'food_adaptation',title:'6. Anpassen und Ursachen begrenzen',content:`<p><strong>Anpassung</strong> bedeutet, mit veränderten Bedingungen besser umzugehen. Betriebe können zum Beispiel passendere Sorten erproben, Aussaatzeiten verändern oder Bodenfeuchtigkeit durch geeignete Bewirtschaftung erhalten. Ob eine Maßnahme hilft, hängt vom Standort ab. Bewässerung kann Trockenstress vermindern, benötigt aber verfügbares Wasser und kann andere Nutzungen oder Ökosysteme beeinträchtigen.</p><p><strong>Erfundener Entscheidungsfall:</strong> Ein Gemüsebetrieb hat in trockenen Wochen zu wenig Wasser. Vorschlag A ist zusätzliche Bewässerung aus einem Bach. Vorschlag B ist, auf einer kleinen Fläche eine trockenheitsverträglichere Sorte zu erproben. Bei A fehlen Daten zum Wasserangebot und zum Bedarf anderer Menschen und Lebewesen. Bei B müssen Erntemenge, Qualität, Kosten und Nachfrage geprüft werden. Keine Maßnahme garantiert jede künftige Ernte.</p><p><strong>Klimaschutz</strong> begrenzt die Ursachen: etwa durch weniger Treibhausgasemissionen bei Energieversorgung und Transport. Anpassung und Klimaschutz ergänzen sich. Auch Gemeinden, Unternehmen und Politik tragen Verantwortung; einzelne Haushalte können diese Aufgaben nicht allein lösen.</p><p><strong>Erkundungsauftrag:</strong> Vergleicht die Vorschläge A und B zu zweit. Notiert für jeden Vorschlag eine mögliche Hilfe, eine Grenze und eine fehlende Information. Legt fest, welche Information ihr zuerst beschaffen würdet, und begründet eure Wahl. Ihr müsst dafür weder einen Bach betreten noch Pflanzen behandeln.</p>`,questions:[
 ['Was muss vor zusätzlicher Bewässerung aus dem Bach geprüft werden?',['Wasserangebot und Folgen für andere Nutzungen und Ökosysteme.','Nur der Kaufpreis der Pumpe.','Nur die Entfernung zum nächsten Geschäft.'],['Wasser ist begrenzt und wird auch von anderen Menschen und Lebewesen benötigt.','Die Kosten sind relevant, sagen aber nichts über verfügbares Wasser und Folgen der Entnahme.','Die Entfernung zum Geschäft beantwortet die Wasserfrage nicht.']],
 ['Welche Zuordnung passt?',['Trockenheitsverträgliche Sorten erproben: Anpassung; fossile Energie einsparen: Klimaschutz.','Trockenheitsverträgliche Sorten erproben: Entfernen aller Treibhausgase.','Zusätzliche Bewässerung: sichere Verhinderung jeder zukünftigen Missernte.'],['Die erste Maßnahme reagiert auf Bedingungen, die zweite kann Emissionen vermindern.','Eine andere Sorte entfernt nicht alle Treibhausgase aus der Atmosphäre.','Bewässerung hat Grenzen; außerdem können andere Ursachen Ernten beeinträchtigen.']]
 ]}
];
topic.sections=topic.sections.filter(s=>!additions.some(a=>a.id===s.id));
for(const section of additions){const quizzes=section.questions.map(([question,answers,feedback],i)=>({id:section.id+'_q'+i,question,answers:answers.map((text,j)=>({text,correct:j===0,pts:0,feedback:feedback[j]}))}));topic.sections.push({id:section.id,title:section.title,content:section.content+quizzes.map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes});}
topic.learningGoals=[...new Set([...topic.learningGoals,'Wetter und Klima unterscheiden und den verstärkten Treibhauseffekt in einfachen Worten erklären.','Anpassung und Klimaschutz unterscheiden und Grenzen landwirtschaftlicher Maßnahmen begründen.'])];
topic.summary=[...new Set([...topic.summary,'Klima wird mit langen Wetter-Messreihen untersucht; zusätzliche Treibhausgase verstärken den natürlichen Treibhauseffekt.','Anpassung kann Ernterisiken vermindern, hat aber Grenzen. Klimaschutz begrenzt die Ursachen des Klimawandels.'])];
topic.workshop.title='7. Eine Jause begründet planen';
for(const source of [{title:'GeoSphere Austria: Klimaforschung und Klimadienstleistungen',url:'https://www.geosphere.at/de/themen/klima/klimaforschung-und-klimadienstleistungen'},{title:'GeoSphere Austria: Anthropogene Treibhausgase',url:'https://klimaportal.geosphere.at/informationsportal-klimawandel/anthropogene_treibhausgase.html'},{title:'IPCC AR6: Anpassung der Lebensmittelproduktion und ihre Grenzen (Englisch)',url:'https://www.ipcc.ch/report/ar6/wg2/chapter/summary-for-policymakers/'}])if(!topic.sources.some(s=>s.url===source.url))topic.sources.push(source);
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');
const revisionFile=path.join(root,'js/chapter-revisions.js'),source=fs.readFileSync(revisionFile,'utf8'),ctx={window:{}};vm.runInNewContext(source,ctx);const revisions=ctx.window.SCIVERSE_CHAPTER_REVISIONS;revisions[id]=Math.max(revisions[id]||0,1);fs.writeFileSync(revisionFile,source.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(revisions)+';'));
console.log('Extended food chapter: climate, adaptation and mitigation; six sections, twelve questions; revision 1.');
