const fs=require('fs'),path=require('path'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8')),t=d.math4_3_terme_gleichungen;
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
t.sections[0].content=t.sections[0].content.replaceAll('Lootboxen','Hefte');
const extras=[
{id:'m43_simplify',title:'Terme zusammenfassen und Klammern auflösen',content:'<p>Gleichartige Terme haben denselben Variablenteil: 3x + 2x = 5x. Dagegen kannst du 3x + 2 nicht zu 5x zusammenfassen. Bei x = 4 ist 3x + 2 gleich 14, aber 5x gleich 20.</p><p>Das Verteilungsgesetz gilt für alle Terme in der Klammer: 2(x + 3) = 2x + 6. Auch ein Minuszeichen betrifft die ganze Klammer: −(x − 4) = −x + 4. Prüfe durch Einsetzen eines Zahlenwerts, ob ein Umformungsschritt plausibel ist; ein einzelner Test beweist die Gleichheit zweier Terme aber nicht allgemein.</p>{{QUIZ_m43_combine}}{{QUIZ_m43_bracket}}',quizzes:[
q('m43_combine','Vereinfache 3x + 2x − 4.',[['5x − 4',true,'3x und 2x sind gleichartig und werden zu 5x. Die Konstante −4 bleibt.'],['x',false,'Die −4 hat keinen Faktor x und darf nicht mit den x-Termen zusammengefasst werden.'],['5x² − 4',false,'Beim Addieren von 3x und 2x entsteht 5x. x² entsteht bei x · x.']]),
q('m43_bracket','Welcher Term ist gleich 2(x − 3)?',[['2x − 6',true,'Multipliziere beide Teile der Klammer mit 2: 2 · x − 2 · 3.'],['2x − 3',false,'Auch die −3 muss mit 2 multipliziert werden.'],['2x + 6',false,'Das Minus vor der 3 bleibt beim Multiplizieren mit der positiven Zahl 2 erhalten.']])]},
{id:'m43_bothsides',title:'Variablen auf beiden Seiten',content:'<p>Bei einer Äquivalenzumformung bleibt die Lösungsmenge gleich. Du darfst auf beiden Seiten denselben Term addieren oder subtrahieren. Mit derselben Zahl ungleich 0 darfst du beide Seiten multiplizieren oder dividieren. Eine Division durch eine Variable ist ohne Prüfung problematisch: Sie könnte 0 sein.</p><table><caption>3x + 4 = 2x + 9 lösen</caption><thead><tr><th>Gleichung</th><th>Schritt</th></tr></thead><tbody><tr><td>3x + 4 = 2x + 9</td><td>Auf beiden Seiten 2x subtrahieren</td></tr><tr><td>x + 4 = 9</td><td>Auf beiden Seiten 4 subtrahieren</td></tr><tr><td>x = 5</td><td>In die ursprüngliche Gleichung einsetzen</td></tr></tbody></table><p>Probe: 3 · 5 + 4 = 19 und 2 · 5 + 9 = 19. Beide Seiten haben denselben Wert.</p><p>Mit Klammern: 2(x − 3) = x + 4 wird zu 2x − 6 = x + 4. Subtrahiere x und addiere 6 auf beiden Seiten: x = 10. Probe: 2(10 − 3) = 14 und 10 + 4 = 14.</p>{{QUIZ_m43_both}}{{QUIZ_m43_divzero}}',quizzes:[
q('m43_both','Löse 3x + 4 = 2x + 9.',[['x = 5',true,'Nach −2x auf beiden Seiten bleibt x + 4 = 9. Danach −4: x = 5.'],['x = 13',false,'Nach dem Sammeln der x-Terme steht x + 4 = 9. Du musst 4 abziehen, nicht addieren.'],['x = 1',false,'Einsetzen ergibt links 7 und rechts 11. Die beiden Werte stimmen nicht überein.']]),
q('m43_divzero','Welche Umformung ist immer unzulässig?',[['Beide Seiten durch 0 dividieren.',true,'Division durch 0 ist nicht definiert.'],['Auf beiden Seiten 4 subtrahieren.',false,'Dieselbe Zahl auf beiden Seiten abzuziehen ist zulässig.'],['Beide Seiten durch 2 dividieren.',false,'Division durch dieselbe Zahl ungleich 0 erhält die Gleichheit.']])]},
{id:'m43_cases',title:'Keine oder unendlich viele Lösungen',content:'<p>Nicht jede Gleichung hat genau eine Lösung. Bei 2(x + 1) = 2x + 2 führen die Umformungen zu 2 = 2. Diese Aussage ist unabhängig von x wahr: Jede reelle Zahl ist eine Lösung.</p><p>Bei 2(x + 1) = 2x + 5 bleibt 2 = 5. Das ist unmöglich: Es gibt keine Lösung. Eine wahre Aussage ohne x und eine falsche Aussage ohne x sind also verschiedene Ergebnisse.</p>{{QUIZ_m43_none}}{{QUIZ_m43_many}}',quizzes:[
q('m43_none','Nach korrekten Umformungen bleibt 2 = 5. Was folgt?',[['Die Gleichung hat keine Lösung.',true,'Kein Wert für x kann die falsche Aussage 2 = 5 wahr machen.'],['x = 3',false,'Die Differenz der beiden Konstanten ist keine Lösung. x ist bereits weggefallen.'],['Jede reelle Zahl ist eine Lösung.',false,'Dafür müsste die verbleibende Aussage wahr sein, etwa 2 = 2.']]),
q('m43_many','Welche Gleichung gilt für jede reelle Zahl x?',[['2(x + 1) = 2x + 2',true,'Nach Ausmultiplizieren stehen auf beiden Seiten dieselben Terme.'],['2x + 1 = 2x + 2',false,'Nach −2x bleibt 1 = 2. Diese Gleichung hat keine Lösung.'],['x + 1 = 2',false,'Diese Gleichung gilt nur für x = 1.']])]},
{id:'m43_apply',title:'Textaufgabe und Rechenschritte',content:'<p>Ein erfundener Materialeinkauf für ein Schulprojekt kostet 25 €. Darin sind 4 gleich teure Hefte und 5 € für Stifte enthalten. Gesucht ist der Preis x eines Hefts in Euro. Das Modell lautet <strong>4x + 5 = 25</strong>. Subtrahiere 5 und dividiere anschließend durch 4: x = 5. Antwort: Ein Heft kostet 5 €. Probe: 4 · 5 € + 5 € = 25 €.</p><p>Bei (x + 2) : 3 = 4 kannst du zuerst beide Seiten mit 3 multiplizieren. Danach steht x + 2 = 12, also x = 10. Der Nenner ist hier eine feste Zahl ungleich 0.</p><div class="interactive-zone" data-equation-practice><h3>Wähle den nächsten Rechenschritt</h3><label for="equation_task">Aufgabe</label><select id="equation_task"><option value="0">Variablen auf beiden Seiten</option><option value="1">Mit Klammer</option><option value="2">Mit festem Nenner</option></select><p data-equation-current></p><div data-equation-options></div><p data-equation-feedback role="status" aria-live="polite"></p><ol data-equation-history></ol><button type="button" data-equation-reset>Aufgabe neu beginnen</button></div>{{QUIZ_m43_model}}',quizzes:[
q('m43_model','4 gleich teure Hefte und 5 € für Stifte kosten zusammen 25 €. x ist der Preis eines Hefts in Euro. Welche Gleichung passt?',[['4x + 5 = 25',true,'4x beschreibt die vier Hefte, dazu kommen 5 € für die Stifte.'],['4(x + 5) = 25',false,'Damit würdest du auch die Stiftekosten viermal berechnen. Sie fallen nur einmal an.'],['x + 4 + 5 = 25',false,'Die Anzahl 4 ist kein Preis. Vier Hefte kosten 4 · x Euro.']])]}];
t.sections=t.sections.filter(s=>!extras.some(e=>e.id===s.id));t.sections.splice(1,0,extras[0]);t.sections.push(...extras.slice(1));
t.learningGoals=['Gleichartige Terme zusammenfassen und Klammern mit dem Verteilungsgesetz auflösen.','Lineare Gleichungen auch mit Variablen auf beiden Seiten lösen und durch Einsetzen prüfen.','Keine, eine oder unendlich viele Lösungen unterscheiden.','Textaufgaben als Gleichungen darstellen und das Ergebnis im Kontext deuten.'];t.prerequisites=['math3_3_gleichungen','math3_2_potenzen_terme'];t.summary=['Gleichartige Terme werden über ihre Koeffizienten zusammengefasst: 3x + 2x = 5x.','Führe dieselbe zulässige Operation auf beiden Seiten aus; eine Division durch 0 ist ausgeschlossen.','Eine wahre Aussage ohne x bedeutet bei diesen Gleichungen: alle reellen Zahlen sind Lösungen. Eine falsche Aussage bedeutet: keine Lösung.','Definiere die Variable, stelle die Gleichung auf, löse sie und prüfe durch Einsetzen sowie anhand der Sachaufgabe.'];
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
