const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8')),t=d.math4_1_reelle_zahlen;
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const first=t.sections.find(s=>s.id==='sec1'),$=cheerio.load(first.content);
$('p').first().text('Eine quadratische Fläche hat den Flächeninhalt 25 m². Welche nichtnegative Seitenlänge ergibt beim Quadrieren 25?');
$('#root1').attr({'aria-label':'Seitenlänge des Quadrats in Metern',min:0,step:'any'});
first.content=$('body').html();
if(!first.content.includes('data-root-definition'))first.content+='<p data-root-definition>Für a ≥ 0 bezeichnet √a die nichtnegative Zahl, deren Quadrat a ist. √25 = 5 und √0 = 0. Die Gleichung x² = 25 hat dagegen zwei Lösungen: x = 5 und x = −5. Eine geometrische Länge ist nicht negativ. Eine negative Zahl besitzt keine reelle Quadratwurzel, denn das Quadrat jeder reellen Zahl ist mindestens 0.</p>';
first.quizzes=[q('m41_q1','Was ist √36?', [['6',true,'6 ist nichtnegativ und 6 · 6 = 36.'],['18',false,'Die Quadratwurzel ist nicht die Hälfte. 18 · 18 = 324.'],['−6',false,'Auch (−6)² ist 36, aber das Wurzelzeichen bezeichnet die nichtnegative Wurzel.']])];
const newSections=[
{id:'sec2',title:'Rational oder irrational?',content:'<p>Eine <strong>rationale Zahl</strong> lässt sich als Bruch a/b mit ganzen Zahlen a und b und b ≠ 0 schreiben. Dazu gehören ganze Zahlen, etwa −3 = −3/1, und 0,75 = 3/4. Ihre Dezimaldarstellung endet oder wird periodisch.</p><p>Auch <strong>1/3 = 0,333…</strong> ist rational: Die Ziffer 3 wiederholt sich endlos. Eine unendliche Dezimaldarstellung allein reicht also nicht aus, um eine Zahl irrational zu nennen.</p><p>Eine <strong>irrationale Zahl</strong> lässt sich nicht als solcher Bruch schreiben. Ihre Dezimaldarstellung ist unendlich und nicht periodisch. Beispiele sind √2 und π. „Irrational“ ist hier ein mathematischer Begriff und bedeutet nicht unlogisch. Rationale und irrationale Zahlen bilden zusammen die <strong>reellen Zahlen</strong>.</p>{{QUIZ_m41_q2}}{{QUIZ_m41_periodic}}',quizzes:[
q('m41_q2','Welche Aussage über √2 stimmt?',[['Die Zahl ist reell und irrational.',true,'√2 ist eine Zahl auf der reellen Zahlengeraden, lässt sich aber nicht als Bruch zweier ganzer Zahlen schreiben.'],['Sie ist keine Zahl, weil ihre Dezimaldarstellung nicht endet.',false,'Auch unendliche Dezimaldarstellungen beschreiben Zahlen. √2 liegt zwischen 1 und 2.'],['Sie ist genau 1,5.',false,'1,5² = 2,25. Das ist größer als 2, also ist √2 kleiner als 1,5.']]),
q('m41_periodic','Ist 0,333… mit endlos wiederholter 3 rational?',[['Ja, die Zahl ist 1/3.',true,'Eine periodische Dezimaldarstellung lässt sich als Bruch schreiben.'],['Nein, weil sie unendlich viele Nachkommastellen hat.',false,'Unendlich allein bedeutet nicht irrational. Entscheidend ist hier die Periodizität.'],['Ja, sie ist genau 0,33.',false,'0,33 ist nur eine Näherung. 1/3 hat danach noch weitere Dreien.']])]},
{id:'m41_approx',title:'Eine Wurzel eingrenzen',content:'<p>1² = 1 und 2² = 4, also liegt √2 zwischen 1 und 2. Genauer: 1,4² = 1,96 und 1,5² = 2,25. Deshalb gilt <strong>1,4 &lt; √2 &lt; 1,5</strong>. Noch genauer: 1,41² = 1,9881 und 1,42² = 2,0164.</p><p>Auf zwei Nachkommastellen gerundet ist √2 ≈ 1,41. Das Zeichen ≈ bedeutet „ungefähr gleich“. Der Taschenrechner zeigt eine begrenzte Näherung, nicht alle Ziffern.</p><div class="interactive-zone" data-root-estimate><h3>Näherung für √2 untersuchen</h3><label for="root_estimate">Vermutete Wurzel zwischen 1 und 2</label><input id="root_estimate" type="range" min="1" max="2" step="0.001" value="1.4"><p id="root_estimate_result" role="status" aria-live="polite"></p><p>Vergleiche insbesondere 1,414 und 1,415. Keiner der einstellbaren Werte ist exakt √2.</p></div>{{QUIZ_m41_bounds}}{{QUIZ_m41_round}}',quizzes:[
q('m41_bounds','1,41² ist kleiner als 2; 1,42² ist größer als 2. Was folgt daraus?',[['√2 liegt zwischen 1,41 und 1,42.',true,'Bei nichtnegativen Zahlen wächst das Quadrat mit der Zahl. Die gesuchte Wurzel liegt zwischen den beiden Werten.'],['√2 ist genau 1,41.',false,'1,41² ist kleiner als 2. Deshalb ist 1,41 nur eine untere Näherung.'],['√2 liegt zwischen 2 und 3.',false,'Schon 2² ist 4. Die Wurzel aus 2 muss kleiner als 2 sein.']]),
q('m41_round','Welche Schreibweise ist richtig?',[['√2 ≈ 1,41',true,'Das Näherungszeichen zeigt, dass gerundet wurde.'],['√2 = 1,41',false,'Das Gleichheitszeichen würde exakte Gleichheit behaupten. 1,41² ist aber 1,9881.'],['√2 = 1,42',false,'Auch 1,42 ist nicht exakt √2: Das Quadrat ist 2,0164.']])]},
{id:'m41_apply',title:'Wurzel und Gleichung unterscheiden',content:'<p>Eine quadratische Fläche von 49 cm² hat eine Seitenlänge von √49 cm = 7 cm. Für die Gleichung x² = 49 sind dagegen 7 und −7 Lösungen. Prüfe durch Einsetzen: 7² = 49 und (−7)² = 49.</p><p><strong>Achtung bei Summen:</strong> √(9 + 16) = √25 = 5. Dagegen ist √9 + √16 = 3 + 4 = 7. Eine Wurzel darf nicht einfach auf die Summanden verteilt werden.</p>{{QUIZ_m41_equation}}{{QUIZ_m41_sum}}',quizzes:[
q('m41_equation','Welche reellen Zahlen lösen x² = 49?',[['7 und −7',true,'Beide Zahlen ergeben beim Quadrieren 49.'],['Nur 7',false,'Für √49 stimmt 7. Die Gleichung x² = 49 hat zusätzlich die Lösung −7.'],['24,5 und −24,5',false,'Halbieren macht Quadrieren nicht rückgängig. Die Probe zeigt: 24,5² ist nicht 49.']]),
q('m41_sum','Was ist √(9 + 16)?',[['5',true,'Zuerst die Summe unter der Wurzel berechnen: 9 + 16 = 25. Dann √25 = 5.'],['7',false,'7 entsteht durch √9 + √16. Das ist ein anderer Ausdruck.'],['12,5',false,'Die Wurzel aus 25 ist nicht die Hälfte von 25. Gesucht ist eine Zahl mit Quadrat 25.']])]}
];t.sections=[first,...newSections];
t.diplom.questions[0].answers[0].feedback='10 ist nichtnegativ und 10² = 100.';t.diplom.questions[0].answers[1].feedback='Halbieren ist nicht Wurzelziehen: 50² = 2500, nicht 100.';
t.learningGoals=['Quadratwurzeln als nichtnegative Zahlen erklären und einfache Wurzeln berechnen.','Rationale und irrationale Zahlen anhand ihrer Darstellung unterscheiden.','Eine Quadratwurzel durch Quadrieren eingrenzen und Näherungen kennzeichnen.','Das Wurzelzeichen von den Lösungen einer quadratischen Gleichung unterscheiden.'];t.prerequisites=['math1_8_brueche','math1_9_dezimalzahlen','math3_2_potenzen_terme'];t.summary=['√a ist für a ≥ 0 die nichtnegative Zahl mit Quadrat a.','Rationale Zahlen sind Brüche ganzer Zahlen mit Nenner ungleich 0. Ihre Dezimaldarstellung endet oder wird periodisch.','Irrationale Zahlen haben unendliche, nicht periodische Dezimaldarstellungen. Zusammen mit rationalen Zahlen bilden sie die reellen Zahlen.','√2 ≈ 1,41 ist eine Näherung. x² = 25 hat die Lösungen 5 und −5, während √25 = 5 gilt.'];
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
