const fs=require('fs'),path=require('path'),vm=require('vm'),root=path.join(__dirname,'..'),id='geo_3_europa',file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),topic=data[id];
const blocks=[
 ['eu_values','Gemeinsame Werte und unterschiedliche Interessen',`<p>Die EU beruht auf Menschenwürde, Freiheit, Demokratie, Gleichheit, Rechtsstaatlichkeit und der Achtung der Menschenrechte einschließlich der Rechte von Minderheiten. Friedliche Zusammenarbeit gehört zu ihren Zielen. Rechtsstaatlichkeit bedeutet unter anderem, dass staatliche Macht an Recht gebunden ist und unabhängige Gerichte Kontrolle ermöglichen.</p><p>Gemeinsame Werte bedeuten nicht, dass alle Menschen oder Staaten dieselbe politische Meinung haben. Demokratischer Streit braucht Informationen, Beteiligung und die Achtung von Rechten. Eine Mehrheit darf nicht einfach alle Rechte einer Minderheit abschaffen. Prüfe bei einer Forderung deshalb nicht nur, wie viele zustimmen, sondern auch, welche Rechte betroffen sind.</p><p>Europäische Integration ist ein Prozess engerer Zusammenarbeit. Gemeinsame Regeln können grenzüberschreitende Probleme bearbeiten, erfordern aber Einigungen zwischen unterschiedlichen Interessen. Kosten, Nutzen und Umsetzung können ungleich verteilt sein.</p>`],
 ['eu_institutions','Wer entscheidet auf EU-Ebene?',`<table><caption>Vereinfachter Überblick über zentrale EU-Institutionen</caption><thead><tr><th scope="col">Institution</th><th scope="col">Zentrale Rolle</th></tr></thead><tbody><tr><th scope="row">Europäisches Parlament</th><td>Direkt gewählte Vertretung der Bürger:innen; beschließt viele Gesetze gemeinsam mit dem Rat der EU.</td></tr><tr><th scope="row">Rat der Europäischen Union</th><td>Minister:innen der Mitgliedstaaten; verhandelt und beschließt viele Gesetze gemeinsam mit dem Parlament.</td></tr><tr><th scope="row">Europäische Kommission</th><td>Schlägt in der Regel EU-Gesetze vor und übernimmt Aufgaben bei Umsetzung und Überwachung des EU-Rechts.</td></tr><tr><th scope="row">Europäischer Rat</th><td>Staats- und Regierungschefs legen die allgemeinen politischen Richtungen und Prioritäten fest.</td></tr></tbody></table><p>Rat der EU und Europäischer Rat sind nicht dieselbe Institution. Der Europarat ist wiederum eine eigenständige internationale Organisation außerhalb der EU. Die EU kann nur innerhalb ihrer übertragenen Zuständigkeiten handeln; nicht jede örtliche Entscheidung wird in Brüssel getroffen. Die Tabelle vereinfacht und beschreibt nicht jedes besondere Verfahren.</p>`],
 ['eu_market','Vier Freiheiten und Alltag',`<p>Der Binnenmarkt beruht auf dem freien Verkehr von <strong>Waren, Personen, Dienstleistungen und Kapital</strong>. Ein Unternehmen verkauft Waren über eine Grenze, eine Person nutzt Möglichkeiten zum Arbeiten in einem anderen Mitgliedstaat, ein Betrieb erbringt eine grenzüberschreitende Dienstleistung oder Kapital wird grenzüberschreitend investiert. Diese Freiheiten gelten innerhalb rechtlicher Regeln, nicht als Befreiung von sämtlichen Anforderungen.</p><p>Die EU, der Euroraum und der Schengen-Raum haben unterschiedliche Aufgaben und sind nicht dieselbe Gebietsliste. Die gemeinsame Währung erleichtert Preisvergleiche ohne Umrechnung zwischen ihren Teilnehmern, macht Preise aber nicht automatisch gleich. Gemeinsame Produkt- und Verbraucherschutzregeln sollen den Austausch mit Schutz verbinden. Bildungskooperationen ermöglichen gemeinsame Projekte; Regionalentwicklung kann Unterschiede zwischen Regionen verringern helfen, erfordert aber Planung und Bewertung.</p><p>Kartenauftrag: Vergleiche die offiziellen Länderinformationen zu Österreich und einem anderen europäischen Staat. Notiere EU-Mitgliedschaft, Währung und Schengen-Zugehörigkeit mit Abrufdatum. Markiere auf einer Karte, welche Frage jede Einteilung beantwortet. Übernimm keine alte Länderzahl ohne Prüfung.</p>`],
 ['eu_participation','Beteiligung und gemeinsame Problemlösung',`<p>Menschen können sich informieren, Anliegen an gewählte Vertreter:innen richten und an geeigneten Beteiligungsverfahren mitwirken. Eine Europäische Bürgerinitiative kann die Kommission unter bestimmten Voraussetzungen auffordern, einen Rechtsakt vorzuschlagen. Sie beschließt nicht selbst ein Gesetz; auch eine erfolgreiche Initiative garantiert keinen Gesetzesvorschlag.</p><p>Fiktiver Fall: Ein Fluss verbindet mehrere Staaten. Oberhalb wünschen Betriebe kostengünstige Produktion, unterhalb werden sauberes Wasser und ein intaktes Ökosystem benötigt. Gemeinsame Messgrößen, Austausch und abgestimmte Regeln können helfen. Zu klären sind Verursachung, Zuständigkeit, Finanzierung und Kontrolle. Eine Grenze hält die Umweltfolgen nicht automatisch auf.</p><p>Rollengespräch im Unterricht: Vertretet Anwohnende, Betriebe und öffentliche Stellen. Formuliert ein gemeinsames Ziel und einen Vorschlag, nennt eine verbleibende Schwierigkeit und prüft die Vereinbarkeit mit Grundrechten. Das Gespräch ist ein vereinfachtes Planspiel, kein Nachbau eines konkreten EU-Gesetzgebungsverfahrens. Niemand muss dabei eine persönliche politische Position offenlegen.</p>`]
];
const raw=[
 ['Was gehört zur Rechtsstaatlichkeit?',['Staatliche Macht ist an Recht gebunden und kann gerichtlich kontrolliert werden.','Eine Mehrheit darf ohne Grenze jede Minderheitenposition verbieten.','Regierungen müssen sich grundsätzlich an keine Regeln halten.'],['Rechtsbindung und unabhängige Kontrolle sind wesentlich.','Mehrheiten bleiben an Rechte gebunden.','Gerade die Bindung staatlicher Macht ist zentral.']],
 ['Was folgt aus gemeinsamen EU-Werten?',['Meinungsunterschiede müssen unter Achtung von Rechten bearbeitet werden.','Alle Menschen müssen dieselbe politische Meinung haben.','Interessenkonflikte können nicht mehr vorkommen.'],['Demokratischer Streit und gemeinsame Rechte schließen einander nicht aus.','Meinungsvielfalt gehört zu demokratischer Freiheit.','Zusammenarbeit muss weiterhin unterschiedliche Interessen bearbeiten.']],
 ['Wer beschließt viele EU-Gesetze gemeinsam?',['Europäisches Parlament und Rat der Europäischen Union.','Ausschließlich der Europarat.','Jede einzelne Gemeinde allein für die gesamte EU.'],['Beide wirken im ordentlichen Gesetzgebungsverfahren zusammen.','Der Europarat ist keine EU-Institution.','Gemeinden beschließen keine Gesetze für die gesamte EU.']],
 ['Welche Zuordnung ist richtig?',['Im Rat der EU arbeiten Minister:innen der Mitgliedstaaten zusammen.','Rat der EU und Europäischer Rat sind identische Namen für dasselbe Gremium.','Die Kommission ist das direkt gewählte Europäische Parlament.'],['Die Zusammensetzung richtet sich nach dem behandelten Politikbereich.','Der Europäische Rat besteht insbesondere aus Staats- und Regierungschefs.','Kommission und gewähltes Parlament sind unterschiedliche Institutionen.']],
 ['Welche Gruppe nennt die vier Freiheiten des Binnenmarkts?',['Waren, Personen, Dienstleistungen und Kapital.','Wetter, Sprache, Währung und Tourismus.','Nur Waren und Bargeld.'],['Diese vier Bereiche bilden die Grundfreiheiten.','Das sind nicht die vier Grundfreiheiten.','Personen und Dienstleistungen fehlen; Kapital ist mehr als Bargeld.']],
 ['Warum müssen EU, Euroraum und Schengen getrennt betrachtet werden?',['Sie betreffen unterschiedliche Formen der Zusammenarbeit und Mitgliedschaften.','Alle drei Begriffe bezeichnen immer genau dieselben Staaten.','Jeder europäische Staat nutzt deshalb zwingend den Euro.'],['Politische Mitgliedschaft, Währung und Grenzregelungen sind verschiedene Fragen.','Die Gebietslisten sind nicht identisch.','Europa ist weder gleich EU noch gleich Euroraum.']],
 ['Was kann eine Europäische Bürgerinitiative bewirken?',['Die Kommission nach den Regeln des Verfahrens zu einem Vorschlag auffordern.','Direkt und automatisch ein EU-Gesetz beschließen.','Jede Zuständigkeitsgrenze der EU abschaffen.'],['Eine Initiative ist ein Beteiligungsinstrument, kein eigener Gesetzesbeschluss.','Ein Gesetz erfordert weitere zuständige Entscheidungsverfahren.','Auch Initiativen sind an Zuständigkeiten und Voraussetzungen gebunden.']],
 ['Was hilft im fiktiven grenzüberschreitenden Flusskonflikt?',['Gemeinsame Daten, geklärte Zuständigkeiten und verhandelte Maßnahmen.','Nur darauf vertrauen, dass die Staatsgrenze das Wasserproblem stoppt.','Kosten und betroffene Interessen gar nicht berücksichtigen.'],['Kooperation braucht überprüfbare Grundlagen und Umsetzung.','Wasser und Umweltfolgen können Grenzen überschreiten.','Ohne diese Fragen bleibt ein Vorschlag unvollständig.']]
];
const questions=raw.map(([question,answers,feedback],i)=>({id:id+'_integration_'+i,question,answers:answers.map((text,j)=>({text,correct:j===0,pts:0,feedback:feedback[j]}))}));
topic.sections=topic.sections.filter(s=>!blocks.some(b=>b[0]===s.id));blocks.forEach(([sectionId,title,content],i)=>topic.sections.push({id:sectionId,title:(i+4)+'. '+title,content:content+questions.slice(i*2,i*2+2).map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:questions.slice(i*2,i*2+2)}));
const add=(key,values)=>topic[key]=[...new Set([...(topic[key]||[]),...values])];
add('learningGoals',['EU-Grundwerte und die Rollen zentraler Institutionen erklären.','Die vier Grundfreiheiten sowie EU, Euroraum und Schengen unterscheiden.','Möglichkeiten und Grenzen gemeinsamer Problemlösung und Beteiligung erläutern.']);
add('summary',['Gemeinsame Grundwerte ermöglichen demokratische Auseinandersetzung unter Achtung von Rechten.','Parlament, Rat der EU, Kommission und Europäischer Rat haben unterschiedliche Aufgaben.','Waren, Personen, Dienstleistungen und Kapital bilden die vier Freiheiten; EU, Euro und Schengen sind getrennte Einteilungen.','Beteiligung und Zusammenarbeit brauchen Regeln; eine Bürgerinitiative beschließt kein Gesetz.']);
const sources=[['EU: Ziele und Werte','https://european-union.europa.eu/principles-countries-history/principles-and-values/aims-and-values_de'],['EU: Institutionen und Einrichtungen','https://european-union.europa.eu/institutions-law-budget/institutions-and-bodies_de'],['Rat der EU: Binnenmarkt','https://www.consilium.europa.eu/de/topics/single-market/'],['Europäische Bürgerinitiative: Verfahren','https://citizens-initiative.europa.eu/how-it-works_de'],['EU: Länderinformationen','https://european-union.europa.eu/principles-countries-history/eu-countries_de']];topic.sources=topic.sources||[];for(const [title,url]of sources)if(!topic.sources.some(s=>s.url===url))topic.sources.push({title,url});
topic.workshop.title='8. Zusammenarbeit begründen';topic.workshop.writing='Entwirf eine fiktive Zusammenarbeit zweier Schulen zum grenzüberschreitenden Flussbeispiel. Nenne gemeinsames Ziel, vergleichbare Daten, zwei Interessen und eine Schwierigkeit. Erkläre einen Bezug zu EU-Grundwerten. Beschreibe zusätzlich, welche Rollen Parlament, Rat der EU und Kommission bei einer gemeinsamen gesetzlichen Lösung gewöhnlich hätten und weshalb eine Bürgerinitiative allein kein Gesetz beschließt.';topic.workshop.rubric=['Gemeinsames Ziel und Datenvergleich sind konkret.','Zwei Interessen und eine Schwierigkeit sind benannt.','Grundwerte und Institutionen werden korrekt zugeordnet.','Die Grenze einer Bürgerinitiative ist erklärt.'];topic.workshop.model='Die Schulen könnten dieselbe Messgröße zur Wasserqualität im gleichen Zeitraum vergleichen, ohne daraus allein Verursachung abzuleiten. Anwohnende wünschen sauberes Wasser, Betriebe tragbare Kosten. Gemeinsame Kontrolle und Finanzierung bleiben zu klären. Rechtsstaatlichkeit verlangt rechtsgebundene Verfahren. Die Kommission schlägt gewöhnlich eine Regelung vor; Parlament und Rat der EU beraten und beschließen viele Gesetze gemeinsam. Eine Bürgerinitiative fordert eine Prüfung bzw. einen Vorschlag an, erlässt aber kein Gesetz.';
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');const p=path.join(root,'js/chapter-revisions.js'),s=fs.readFileSync(p,'utf8'),c={window:{}};vm.runInNewContext(s,c);c.window.SCIVERSE_CHAPTER_REVISIONS[id]=Math.max(1,c.window.SCIVERSE_CHAPTER_REVISIONS[id]||0);fs.writeFileSync(p,s.replace(/window.SCIVERSE_CHAPTER_REVISIONS=.*?;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));console.log('Expanded Europe to seven sections and twelve questions; updated goals, workshop, sources and result revision.');
