const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),topic=data.math4_4_funktionen_sys;
topic.title='📈 Lineare Funktionen und Gleichungssysteme';topic.subtitle='Funktionswerte, Geraden und gemeinsame Lösungen untersuchen.';
topic.learningGoals=['Funktionswerte berechnen sowie Steigung und Achsenabschnitt unterscheiden.','Die gemeinsame Lösung zweier linearer Gleichungen rechnerisch bestimmen und prüfen.','Eine, keine und unendlich viele Lösungen grafisch unterscheiden.'];topic.prerequisites=['math4_3_terme_gleichungen'];topic.summary=['Eine Funktion ordnet jedem erlaubten x genau einen y-Wert zu. Bei y = m · x + b beschreibt m die Steigung und b den y-Achsenabschnitt.','Eine Lösung eines Gleichungssystems erfüllt beide Gleichungen gleichzeitig. Ein Schnittpunkt liefert ein Wertepaar (x|y).','Verschiedene Steigungen ergeben bei zwei Geraden genau einen Schnittpunkt. Gleiche Steigungen ergeben parallele oder identische Geraden.'];
{const s=topic.sections[0],$=cheerio.load(s.content);$('p').filter((_,p)=>$(p).text().includes('Getränkeautomat')).text('Eine Funktion ordnet jedem x aus ihrem Definitionsbereich genau einen y-Wert zu. Bei y = x + 3 wird zu jeder eingegebenen Zahl 3 addiert. Ein und dasselbe x darf dabei nicht zwei verschiedene Funktionswerte erhalten.');s.content=$('body').html();}
topic.sections[1].content='<p>Ein Punkt (x|y) beschreibt eine Stelle im Koordinatensystem. Eine lineare Funktion hat die Form y = m · x + b. Wenn x um 1 zunimmt, verändert sich y um m. Der Wert b ist der Funktionswert bei x = 0 und damit der Schnittpunkt mit der y-Achse. Bei y = 2x + 1 liegen beispielsweise (0|1), (1|3) und (2|5) auf der Geraden.</p><p>Für alle reellen x ist der Graph eine Gerade. Bei einer Sachaufgabe kann der Definitionsbereich eingeschränkt sein: Bei ganzen Monaten sind nur passende einzelne Monatswerte sinnvoll. Prüfe daher immer, welche x-Werte im Kontext erlaubt sind.</p>{{QUIZ_m44_q2}}';
topic.sections[1].quizzes[0].question='Welche Aussage passt zu y = 2x + 1?';topic.sections[1].quizzes[0].answers=[{text:'Steigung 2 und y-Achsenabschnitt 1.',correct:true,pts:10,feedback:'Pro Schritt von 1 in x-Richtung steigt y um 2; bei x = 0 gilt y = 1.'},{text:'Steigung 1 und y-Achsenabschnitt 2.',correct:false,pts:0,feedback:'Die Zahl vor x ist die Steigung. Die addierte Konstante ist der Achsenabschnitt.'}];
const lab=`<div class="interactive-zone" data-system-lab><h3>Zwei Geraden vergleichen</h3><p>I wird blau und durchgezogen dargestellt, II violett und gestrichelt. Das Fenster zeigt auf beiden Achsen −5 bis 5. Auch ein Schnittpunkt außerhalb des Fensters wird berechnet. Die Zahlenwerte des Ergebnisses werden auf bis zu drei Nachkommastellen gerundet.</p><fieldset><legend>I: y = m₁ · x + b₁</legend><label>m₁ <input data-m1 type="number" min="-5" max="5" step="any" value="2"></label><label>b₁ <input data-b1 type="number" min="-10" max="10" step="any" value="1"></label></fieldset><fieldset><legend>II: y = m₂ · x + b₂</legend><label>m₂ <input data-m2 type="number" min="-5" max="5" step="any" value="-1"></label><label>b₂ <input data-b2 type="number" min="-10" max="10" step="any" value="4"></label></fieldset><button type="button" data-preset="one">Eine Lösung</button><button type="button" data-preset="none">Keine Lösung</button><button type="button" data-preset="many">Unendlich viele Lösungen</button><svg viewBox="0 0 460 460" role="img" aria-label="Zwei Geraden im Koordinatensystem"></svg><p data-status role="status" aria-live="polite"></p><p>Auftrag: Berechne für die Startwerte zunächst den Schnittpunkt. Ändere dann nur m₂ auf 2. Erkläre, warum nun keine Lösung vorhanden ist. Welcher weitere Wert muss geändert werden, damit beide Geraden identisch sind?</p></div>`;
const raw=[
['Welche Bedeutung hat die Lösung (1|3) für I: y = 2x + 1 und II: y = −x + 4?','Das Wertepaar erfüllt beide Gleichungen.','Nur die erste Gleichung muss erfüllt sein.','Die Zahl 1 ist bereits die vollständige Lösung ohne y-Wert.','2 · 1 + 1 = 3 und −1 + 4 = 3.','Eine Systemlösung muss alle beteiligten Gleichungen erfüllen.','Hier wird ein gemeinsames Wertepaar gesucht.'],
['Wie bestimmst du den Schnittpunkt von y = 2x + 1 und y = −x + 4 rechnerisch?','2x + 1 = −x + 4 setzen, x berechnen und y einsetzen.','Nur die beiden Achsenabschnitte addieren.','Die Steigungen immer gleichsetzen, ohne x zu berechnen.','Am Schnittpunkt haben beide Funktionen denselben y-Wert. Daraus folgt 3x = 3.','Die Summe der Achsenabschnitte liefert keinen Schnittpunkt.','Die Steigungen sind Eigenschaften der Geraden, nicht die gesuchte x-Koordinate.'],
['Was erhältst du durch Addieren von 2x + y = 8 und x − y = 1?','3x = 9.','3x + 2y = 9.','x = 7.','+y und −y heben sich auf; beide Seiten werden jeweils addiert.','y und −y ergeben 0, nicht 2y.','Beim Addieren entsteht zunächst 3x = 9.'],
['Welche Probe passt zur Lösung x = 3 und y = 2?','2 · 3 + 2 = 8 und 3 − 2 = 1.','Nur 3 + 2 = 5 prüfen.','Nur prüfen, ob beide Zahlen positiv sind.','Beide ursprünglichen Gleichungen werden kontrolliert.','Das ist keine der gegebenen Gleichungen.','Vorzeichen allein beweisen keine Lösung.'],
['Was gilt für y = x + 1 und y = x + 3?','Keine gemeinsame Lösung.','Genau eine Lösung bei x = 0.','Unendlich viele gemeinsame Lösungen.','Gleiche Steigung und verschiedene Achsenabschnitte ergeben parallele Geraden.','Bei x = 0 ergeben sich die unterschiedlichen Werte 1 und 3.','Identische Geraden bräuchten auch denselben Achsenabschnitt.'],
['Zwei fiktive Angebote kosten A: 3 + 2x Euro und B: 9 + 0,5x Euro. Wann kosten sie gleich viel?','Bei x = 4; beide kosten 11 Euro.','Bei x = 6; beide kosten 15 Euro.','Bei jedem x, weil beide Funktionen linear sind.','3 + 2x = 9 + 0,5x führt zu 1,5x = 6 und x = 4.','Bei x = 6 kostet A 15 Euro, B aber 12 Euro.','Linear bedeutet nicht, dass die Werte immer übereinstimmen.']
];
const qs=raw.map((q,i)=>({id:'linear_system_q'+i,question:q[0],answers:[1,2,3].map(j=>({text:q[j],correct:j===1,pts:0,feedback:q[j+3]}))}));
const sections=[['Gleichsetzen: zwei Bedingungen zugleich','Ein lineares Gleichungssystem stellt zwei Bedingungen an dieselben Unbekannten. Betrachte I: y = 2x + 1 und II: y = −x + 4. Am Schnittpunkt sind die y-Werte gleich: 2x + 1 = −x + 4. Addiere x und subtrahiere 1 auf beiden Seiten: 3x = 3, also x = 1. Einsetzen ergibt y = 3. Die Lösung lautet (1|3). Prüfe sie in beiden ursprünglichen Gleichungen.'],['Einsetzen und Addieren','Nicht jede Gleichung steht schon in der Form y = m · x + b. Beispiel: I: 2x + y = 8; II: x − y = 1. Aus II folgt y = x − 1. In I eingesetzt: 2x + (x − 1) = 8, also x = 3 und y = 2. Alternativ addierst du I und II: Die y-Terme heben sich auf und es bleibt 3x = 9. Beide Wege liefern dieselbe Lösung. Achte beim Umformen darauf, auf beiden Seiten dieselbe zulässige Operation auszuführen.'],['Lösungsfälle und Sachaufgaben','Zwei Geraden können sich einmal schneiden, parallel und verschieden sein oder vollständig zusammenfallen. Im letzten Fall gibt es unendlich viele gemeinsame Punkte. Bei den hier betrachteten Funktionen entscheidet zunächst die Steigung, ob die Geraden parallel sind; bei gleicher Steigung prüfst du zusätzlich den Achsenabschnitt. Bei einer Sachaufgabe musst du die rechnerische Lösung im Kontext deuten. Fiktiver Kostenvergleich: A kostet 3 + 2x Euro, B kostet 9 + 0,5x Euro. Bei x = 4 kosten beide 11 Euro. Ob x sinnvoll ist, hängt von der gezählten oder gemessenen Größe ab.']];
topic.sections=topic.sections.slice(0,2).concat(sections.map(([title,text],i)=>({id:'system'+i,title:(i+3)+'. '+title,content:'<p>'+text+'</p>'+(i===0?lab:'')+qs.slice(i*2,i*2+2).map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:qs.slice(i*2,i*2+2)})));
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');console.log('Completed functions chapter with three system sections, six questions and independent two-line lab; retained existing GeoGebra exploration.');
