const fs=require('fs'),path=require('path'),vm=require('vm');const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.sieinheiten;
for(const s of t.sections){s.content=s.content.replace('Messgr&ouml;&szlig;e = Zahlenwert + Einheit.','Ein Größenwert wird als Zahlenwert mal Einheit angegeben: 2,1 m bedeutet 2,1 · m.').replace('Eine Einheit sagt, womit gemessen wird.','Eine Einheit ist eine vereinbarte Vergleichsgröße; das Messgerät ist beispielsweise ein Lineal oder eine Stoppuhr.');}
t.sections[0].title='1. Messen: Zahlenwert und Einheit';
t.subtitle=t.subtitle.replace('Zahlenwert plus Einheit','Zahlenwert und Einheit');
t.sections[0].content=t.sections[0].content.replace('Messgr&ouml;&szlig;en als Zahlenwert plus Einheit lesen.','Messangaben mit Zahlenwert und Einheit lesen.');
t.sections.find(s=>s.id==='sec1').content=t.sections.find(s=>s.id==='sec1').content.replace('Eine <strong>Einheit</strong> sagt, womit gemessen wird.','Eine <strong>Einheit</strong> ist eine vereinbarte Vergleichsgröße. Das Messgerät ist beispielsweise ein Lineal oder eine Stoppuhr.');
const speed=t.sections.find(s=>s.id==='sec3');if(!speed.content.includes('data-average-speed'))speed.content='<p data-average-speed>Hier berechnen wir die <strong>mittlere Geschwindigkeit</strong>: gesamte zurückgelegte Strecke geteilt durch benötigte Zeit. Der Wert sagt nicht, dass du während der ganzen Bewegung gleich schnell warst. Bei einer Pause zählt auch die Pausenzeit zur betrachteten Gesamtzeit.</p>'+speed.content;
const graph=t.sections.find(s=>s.id==='sec4');if(!graph.content.includes('data-measurement-model'))graph.content='<p data-measurement-model>Die folgende Tabelle enthält vorgegebene Modellwerte, keine echten Messdaten. Die Animation überträgt diese Werte ins Diagramm. Bei eigenen Messungen protokollierst du zusätzlich Gerät und Bedingungen.</p>'+graph.content;
const questions=[
 ['Du misst mit einem Lineal mit Millimeterstrichen etwa 12,3 cm. Welche Aussage ist sinnvoll?',['12,3 cm ist eine abgelesene Näherung; Anlegen und Ablesen können das Ergebnis beeinflussen.','Die Länge ist damit auf beliebig viele Nachkommastellen genau bekannt.','12,300000 cm ist automatisch genauer, weil mehr Ziffern dastehen.'],['Skalenteilung und Messverfahren begrenzen die Aussage.','Keine reale Messung ist beliebig genau.','Zusätzliche Nullen verbessern weder das Gerät noch das Ablesen.']],
 ['Eine Gruppe misst dieselbe Strecke mit einem falsch eingestellten Gerät fünfmal. Was kann Wiederholen leisten?',['Schwankungen werden erkennbar; ein gleichbleibender Gerätefehler kann trotzdem bleiben.','Jeder Gerätefehler verschwindet nach fünf Messungen.','Der häufigste Wert ist unabhängig vom Gerät immer der wahre Wert.'],['Wiederholung und Kontrolle des Geräts erfüllen unterschiedliche Aufgaben.','Ein konstanter Versatz wird durch Wiederholen nicht automatisch behoben.','Übereinstimmung allein garantiert keine richtige Messung.']]
].map(([question,answers,feedback],i)=>({id:'measurement_quality_'+i,question,answers:answers.map((text,j)=>({text,correct:j===0,pts:0,feedback:feedback[j]}))}));
t.sections=t.sections.filter(s=>s.id!=='measurement_quality');t.sections.push({id:'measurement_quality',title:'6. Wie verlässlich ist ein Messwert?',content:'<p>Messwerte sind nicht beliebig genau. Die Skalenteilung eines Lineals, dein Blickwinkel und das Anlegen beeinflussen eine Längenmessung. Auch viele Ziffern auf einer digitalen Anzeige garantieren keine entsprechende Genauigkeit. Notiere nur Ziffern, die dein Messverfahren sinnvoll hergibt.</p><p><strong>Messauftrag:</strong> Miss mit einem Lineal dreimal dieselbe Kante eines Hefts. Lege das Lineal jedes Mal neu an. Notiere Gerät, kleinste Skalenteilung, Einheit und alle drei Werte. Vergleiche den kleinsten und größten Wert und erkläre mögliche Unterschiede. Stimmen die Werte überein, prüfe trotzdem, ob der Nullpunkt richtig angelegt war. Verändere anschließend den Blickwinkel und beschreibe, warum schräges Ablesen ungünstig sein kann.</p><p><strong>Erfundenes Beispiel:</strong> Drei Messungen ergeben 12,3 cm, 12,4 cm und 12,3 cm. Die Werte liegen zwischen 12,3 cm und 12,4 cm; die Spannweite beträgt 0,1 cm beziehungsweise 1 mm. Diese Spannweite beschreibt die beobachtete Streuung, ist aber nicht automatisch die gesamte Messunsicherheit. Ein verschobener Nullpunkt kann alle Werte ähnlich verfälschen.</p>'+questions.map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:questions});
t.diplom.questions.find(q=>q.id==='f3').answers.find(a=>!a.correct).feedback='Eine Stunde sind 3600 Sekunden. Die Stunde ist eine gebräuchliche Nicht-SI-Einheit; die SI-Basiseinheit ist die Sekunde.';
t.diplom.questions.find(q=>q.id==='f10').question='Du legst in 2 Sekunden insgesamt 10 Meter zurück. Wie groß ist deine mittlere Geschwindigkeit?';
t.learningGoals=[...new Set([...t.learningGoals,'Messwerte mit Gerät, Einheit und Bedingungen dokumentieren und Grenzen der Genauigkeit erklären.'])];t.summary=[...new Set([...t.summary,'Wiederholte Messungen zeigen Streuung; ein gleichbleibender Geräte- oder Anlegefehler kann trotzdem bleiben.','Strecke geteilt durch Gesamtzeit ergibt die mittlere Geschwindigkeit über diesen Vorgang.'])];t.sources=t.sources||[];if(!t.sources.some(s=>s.url==='https://www.bipm.org/en/publications/si-brochure'))t.sources.push({title:'BIPM: Internationales Einheitensystem (Englisch/Französisch)',url:'https://www.bipm.org/en/publications/si-brochure'});
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');const rf=path.join(root,'js/chapter-revisions.js'),src=fs.readFileSync(rf,'utf8'),c={window:{}};vm.runInNewContext(src,c);c.window.SCIVERSE_CHAPTER_REVISIONS.sieinheiten=Math.max(2,c.window.SCIVERSE_CHAPTER_REVISIONS.sieinheiten||0);fs.writeFileSync(rf,src.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
