const fs=require('fs'),path=require('path'),vm=require('vm');
let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.waermelehre;
const prose=[
 ['Temperatur, innere Energie und Wärme',`<p>Ein Thermometer misst die <strong>Temperatur</strong>, etwa in Grad Celsius (°C). In unserem einfachen Teilchenmodell bedeutet eine höhere Temperatur stärkere ungeordnete Teilchenbewegung. Teilchen eines Festkörpers schwingen um ihre Plätze; in Flüssigkeiten und Gasen wechseln sie ihre Nachbarn.</p><p>Die <strong>innere Energie</strong> hängt von der Bewegung und den Wechselwirkungen der Teilchen ab. <strong>Wärme</strong> bezeichnet Energie, die wegen eines Temperaturunterschieds übertragen wird. Stellst du eine warme Tasse in ein kühleres Zimmer, gibt sie Energie an ihre Umgebung ab. Wärme ist daher weder ein Stoff noch einfach ein anderer Name für Temperatur.</p><p>Zum Erwärmen von 2 kg Wasser von 20 °C auf 30 °C braucht man ungefähr doppelt so viel Energie wie für 1 kg Wasser bei derselben Temperaturänderung. Die Temperatur allein gibt also keine Energiemenge an. Hier werden Gefäße und Energieverluste nicht mitgerechnet.</p><p><strong>Modellgrenze:</strong> 0 Kelvin entsprechen −273,15 °C, dem absoluten Nullpunkt. Das einfache Bild stillstehender Kügelchen reicht dort nicht aus: Die Quantenphysik beschreibt eine verbleibende Nullpunktsbewegung. Für die Aufgaben genügt die Unterscheidung zwischen Temperatur und Energieübertragung.</p>`],
 ['Wärmeleitung und Wärmedämmung',`<p>Ein Löffel in warmer Suppe kann auch am Griff warm werden. Bei der <strong>Wärmeleitung</strong> wird Energie innerhalb eines Stoffes oder durch Kontakt übertragen, ohne dass der ganze Stoff mitströmt. Im Festkörper tragen Wechselwirkungen benachbarter Teilchen dazu bei; in Metallen transportieren auch bewegliche Elektronen Energie.</p><p>Metall leitet Wärme meist wesentlich besser als trockenes Holz. Ein Holzgriff erwärmt sich deshalb unter vergleichbaren Bedingungen langsamer, kann aber ebenfalls heiß werden. <strong>Ein Holzgriff ist keine Garantie gegen Verbrennungen.</strong> Die folgende Simulation benötigt keine heiße Suppe.</p><p>Eine Winterjacke bremst die Energieabgabe des Körpers, unter anderem durch eingeschlossene, wenig bewegte Luft. Wärmedämmung verlangsamt Wärmeübertragung; sie verhindert sie nicht vollständig und ist keine eigene Heizung.</p>`],
 ['Wärmestrahlung',`<p>Strahlung kann Energie auch durch das Vakuum übertragen. Die Sonnenstrahlung enthält sichtbares Licht und unsichtbare Anteile, darunter Infrarotstrahlung. Trifft sie auf einen Körper und wird aufgenommen, kann sie ihn erwärmen. <strong>Sonnenenergie erreicht uns nicht ausschließlich als Infrarotstrahlung.</strong></p><p>Unter sonst gleichen Bedingungen nimmt eine matte schwarze Oberfläche meist mehr Sonnenstrahlung auf als eine weiße. Die erreichte Temperatur hängt außerdem von Material, Umgebung und Energieabgabe ab. Farbe allein bestimmt weder die Temperatur eines Autos noch seine Sicherheit. Die folgenden Temperaturen sind vereinfachte Modellwerte.</p>`],
 ['Wärmeströmung und Auftrieb',`<p>Bei <strong>Konvektion</strong> transportiert strömende Flüssigkeit oder strömendes Gas Energie. Erwärmte Luft kann sich bei ungefähr gleichem Druck ausdehnen. In einem gleich großen Volumen befindet sich dann weniger Masse: Ihre Dichte ist geringer als die der kühleren Umgebungsluft. Auftrieb kann sie aufsteigen lassen.</p><p>Beim Heißluftballon wird die Luft in der offenen Hülle erwärmt. Der Ballon steigt, wenn die Auftriebskraft größer als das Gewicht von Hülle, Korb, Luft und Nutzlast zusammen ist. „Warme Luft steigt“ beschreibt Bedingungen mit Schwerkraft und einem passenden Dichteunterschied, kein ausnahmsloses Naturgesetz.</p>`],
 ['Aggregatzustände und ihre Änderungen',`<p>Im Teilchenmodell unterscheiden wir fest, flüssig und gasförmig. Im Festkörper schwingen Teilchen um feste Plätze; in einer Flüssigkeit bleiben sie nahe beieinander, können aber ihre Plätze wechseln. Im Gas sind die Abstände meist viel größer. Bei diesen Zustandsänderungen bleiben Wassermoleküle Wassermoleküle.</p><p><strong>Schmelzen:</strong> fest → flüssig. <strong>Erstarren:</strong> flüssig → fest. <strong>Verdampfen:</strong> flüssig → gasförmig. <strong>Kondensieren:</strong> gasförmig → flüssig. Wasser verdunstet auch unterhalb seiner Siedetemperatur. Unsichtbarer Wasserdampf ist von sichtbaren Nebeltröpfchen zu unterscheiden.</p><p>Bei normalem Luftdruck schmilzt reines Eis ungefähr bei 0 °C und Wasser siedet ungefähr bei 100 °C. Während des Schmelzens kann zugeführte Energie den Zustand ändern, ohne dass die Temperatur steigt. Druck beeinflusst die Übergangstemperaturen. Die Knöpfe unten zeigen ausgewählte Zustände, keine vollständige Heizkurve.</p>`],
 ['Wärmeausdehnung und ihre Grenzen',`<p>Viele Stoffe dehnen sich beim Erwärmen aus. Dabei werden nicht einfach die Teilchen größer; ihre mittleren Abstände können zunehmen. Bewegungsfugen und geeignete Lager geben Bauwerken Spielraum für Längenänderungen.</p><p>Es gibt Ausnahmen: Flüssiges Wasser zieht sich beim Erwärmen von 0 °C auf ungefähr 4 °C zusammen. Ein Gas in einem starren, geschlossenen Gefäß kann sein Volumen nicht vergrößern; beim Erwärmen steigt dort der Druck.</p><p>Ein Flüssigkeitsthermometer nutzt die stärkere Ausdehnung seiner Messflüssigkeit gegenüber dem Glas. Die Skala ordnet der Höhe eine Temperatur zu. Der Regler unten stellt eine vereinfachte Anzeige dar.</p>`]
];
for(let i=0;i<t.sections.length;i++){
 const s=t.sections[i],dom=new JSDOM('<body>'+s.content+'</body>'),d=dom.window.document;
 // Preserve existing experiment controls and diagram IDs, replace the contradictory prose.
 const zones=[...d.querySelectorAll('.interactive-zone')].filter(el=>!el.parentElement.closest('.interactive-zone')).map(el=>el.outerHTML).join('\n');
 s.title=(i+1)+'. '+prose[i][0];s.content=prose[i][1]+zones+s.quizzes.map(q=>'{{QUIZ_'+q.id+'}}').join('');dom.window.close();
 s.content=s.content.replace('🎥 High-Quality Animation: Temperatur als Bewegung','Teilchenbewegung im Modell').replace('Kalt bedeutet langsame Teilchen. Heiß bedeutet, sie flitzen wild umher und brauchen mehr Platz!','Bei höherer Temperatur bewegen sich die dargestellten Teilchen im Durchschnitt schneller. Die Animation zeigt ein vereinfachtes Modell.').replace('Dreh die Temperatur hoch und beobachte, wie die Teilchen verrücktspielen!','Verändere den Regler und beschreibe, wie sich die Teilchenbewegung im Modell ändert.').replace('Schwarze Kleidung wird in der Sonne schneller heiß als ein weißes Leiberl.','Vergleiche die beiden Oberflächen bei gleicher Bestrahlung. Andere Materialeigenschaften bleiben im Modell gleich.').replace('-10°C (Gefrieren)','-10°C (Eis)').replace('20°C (Schmelzen)','20°C (flüssiges Wasser)').replace('100°C (Verdampfen)','100°C (Dampfmodell)');
}
function question(collection,id,text,answers,feedback){const q=collection.find(q=>q.id===id);if(!q)throw Error(id);q.question=text;q.answers=answers.map((text,i)=>({text,correct:i===0,pts:0,feedback:feedback[i]}));}
const sectionQ=t.sections.flatMap(s=>s.quizzes),finalQ=t.diplom.questions;
question(sectionQ,'q1','Eine warme Tasse kühlt im Zimmer ab. Was bezeichnet hier Wärme?',['Energieübertragung von der wärmeren Tasse zur kühleren Umgebung.','Die am Thermometer abgelesene Temperatur.','Die gesamte in der Tasse vorhandene innere Energie.'],['Der Temperaturunterschied führt zur Energieübertragung.','Temperatur beschreibt einen Zustand, nicht die übertragene Energie.','Innere Energie ist eine Zustandsgröße; Wärme bezeichnet die Übertragung.']);
question(sectionQ,'q2','Warum werden Kochlöffel häufig aus Holz hergestellt?',['Trockenes Holz leitet Wärme schlechter als Metall; der Griff erwärmt sich meist langsamer.','Holz kann auch bei langem Erhitzen niemals heiß werden.','Holz leitet Energie schneller von der Suppe zur Hand.'],['Das vermindert die schnelle Erwärmung, garantiert aber keinen kühlen Griff.','Auch Holz kann heiß werden.','Schnelle Wärmeleitung zur Hand wäre hier gerade unerwünscht.']);
question(sectionQ,'q4','Warum kann erwärmte Luft in kühlerer Umgebungsluft aufsteigen?',['Bei ähnlichem Druck hat sie eine geringere Dichte und erfährt Auftrieb.','Jedes Luftteilchen verliert beim Erwärmen seine Masse.','Temperatur wirkt wie eine nach oben gerichtete Zugkraft.'],['Weniger Masse je Volumen erklärt den Auftrieb im Schwerefeld.','Die Teilchen verlieren nicht einfach ihre Masse; ihre Abstände ändern sich.','Temperatur ist keine Kraft. Entscheidend sind Dichteunterschied und Auftrieb.']);
question(finalQ,'f1','Welche Aussage unterscheidet Temperatur und Wärme richtig?',['Temperatur kennzeichnet den Zustand; Wärme bezeichnet Energieübertragung wegen eines Temperaturunterschieds.','Temperatur und Wärme sind dieselbe Größe mit verschiedenen Einheiten.','Wärme ist ein unsichtbarer Stoff in heißen Körpern.'],['Das unterscheidet Zustand und Übertragung.','Eine Temperatur ist keine Energiemenge.','Wärme ist kein Stoff.']);
question(finalQ,'f3','Welche Temperatur entspricht 0 Kelvin?',['−273,15 °C.','0 °C.','100 °C.'],['Dies ist der absolute Nullpunkt; das einfache Teilchenmodell hat dort Grenzen.','0 °C entsprechen 273,15 Kelvin.','100 °C entsprechen 373,15 Kelvin.']);
question(finalQ,'f8','Zwei sonst gleiche Platten werden gleich stark von der Sonne bestrahlt. Welche nimmt meist mehr Sonnenstrahlung auf?',['Die matt schwarze Platte.','Die weiße Platte, weil sie mehr Licht reflektiert.','Beide müssen gleich viel aufnehmen, weil die Bestrahlung gleich ist.'],['Die matte schwarze Oberfläche absorbiert meist mehr.','Reflektierte Energie wird nicht von der Platte aufgenommen.','Gleiche einfallende Strahlung bedeutet nicht gleiche Absorption.']);
question(finalQ,'f9','Was bedeutet: Warme Luft hat bei gleichem Druck eine geringere Dichte?',['Ein gleich großes Volumen warmer Luft enthält weniger Masse.','Jedes warme Luftteilchen ist leichter als vorher.','Ein Kilogramm warmer Luft wiegt weniger als ein Kilogramm kalter Luft.'],['Dichte ist Masse pro Volumen.','Die Teilchenmasse erklärt den Unterschied nicht.','Bei gleichem Ort haben beide ein Kilogramm Masse und dasselbe Gewicht.']);
question(finalQ,'f11','Wie heißt der Übergang von Wasserdampf zu flüssigen Tröpfchen?',['Kondensieren.','Erstarren.','Verdampfen.'],['Dabei wird aus Gas eine Flüssigkeit.','Erstarren bedeutet flüssig zu fest.','Verdampfen bezeichnet den umgekehrten Übergang.']);
question(finalQ,'f14','Wie verringert eine gewöhnliche Winterjacke die Abkühlung des Körpers?',['Sie bremst Wärmeübertragung, unter anderem durch eingeschlossene Luft.','Sie verhindert jeden Energieaustausch vollständig.','Sie heizt dauerhaft ohne Energiequelle.'],['Die Jacke dämmt; der Körper gibt weiterhin Energie ab.','Dämmung verlangsamt die Übertragung, stoppt sie aber nicht vollständig.','Eine gewöhnliche Jacke ist keine aktive Heizung.']);
t.subtitle='Temperatur messen, Energieübertragung erklären und Teilchenmodelle prüfen.';
t.sources=[{title:'OpenStax: Heat and Heat Transfer Methods (Englisch)',url:'https://openstax.org/books/college-physics/pages/14-introduction-to-heat-and-heat-transfer-methods'},{title:'OpenStax: Temperature Change and Heat Capacity (Englisch)',url:'https://openstax.org/books/college-physics-2e/pages/14-2-temperature-change-and-heat-capacity'},{title:'OpenStax: Temperature and Thermal Expansion (Englisch)',url:'https://openstax.org/books/college-physics-2e/pages/13-section-summary'},{title:'Max-Planck-Institut: Absoluter Nullpunkt',url:'https://www.ds.mpg.de/131758/22'}];
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');
const revisionFile=path.join(root,'js/chapter-revisions.js'),source=fs.readFileSync(revisionFile,'utf8'),ctx={window:{}};vm.runInNewContext(source,ctx);ctx.window.SCIVERSE_CHAPTER_REVISIONS.waermelehre=Math.max(2,ctx.window.SCIVERSE_CHAPTER_REVISIONS.waermelehre||0);fs.writeFileSync(revisionFile,source.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(ctx.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
console.log('Corrected thermal concepts in six sections and nine questions; preserved experiment IDs; revision 2.');
