const fs=require('fs'),path=require('path'),vm=require('vm');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.arbeit;
function edit(id,fn){const s=t.sections.find(s=>s.id===id),dom=new JSDOM(s.content);fn(dom.window.document.body);s.content=dom.window.document.body.innerHTML;dom.window.close();}
edit('sec0',b=>{b.querySelector('p').textContent='Mechanische Arbeit beschreibt eine Energieübertragung durch eine Kraft entlang eines Weges. Wir müssen angeben, welche Kraft auf welchen Körper wirkt. Bei einer konstanten Kraft in Wegrichtung gilt W = F · s. Wirkt die Kraft entgegen der Bewegung, ist ihre Arbeit negativ; steht sie genau senkrecht zum Weg, ist ihre Arbeit null.';b.querySelector('.remember-box').textContent='Ohne Verschiebung wird am betrachteten starren Gegenstand keine mechanische Arbeit verrichtet. Deine Muskeln setzen beim Halten trotzdem chemische Energie um. Das ist eine andere Betrachtung als die mechanische Arbeit am Gegenstand. Beim ideal waagrechten Tragen auf gleicher Höhe verrichtet die senkrechte Haltekraft keine Arbeit; echtes Gehen enthält zusätzliche Bewegungen.';const zone=b.querySelector('#forceRange').closest('.interactive-zone');zone.querySelector('p').textContent='Stelle Betrag der konstanten Kraft, Weg und Richtung ein. Vergleiche bei denselben Zahlen positive, negative und verschwindende Arbeit. Der Balken zeigt den Betrag; das Vorzeichen steht in der Rechnung.';if(!b.querySelector('#workDirection')){const label=b.ownerDocument.createElement('label');label.htmlFor='workDirection';label.textContent='Richtung der Kraft zum Weg';const select=b.ownerDocument.createElement('select');select.id='workDirection';select.setAttribute('onchange','calcWork()');select.setAttribute('aria-describedby','workEquation');select.innerHTML='<option value="along">In Wegrichtung</option><option value="against">Entgegen der Wegrichtung</option><option value="perpendicular">Senkrecht zum Weg</option>';zone.querySelector('p').after(label,select);}});
edit('sec1',b=>{b.querySelector('p').textContent='Beim gleichmäßigen Heben gegen die Gewichtskraft über die Höhe h nahe der Erdoberfläche verrichtest du die Hubarbeit W = m · g · h. Dabei nimmt die Lageenergie des Systems aus Gegenstand und Erde um diesen Betrag zu. Die Masse bleibt gleich; zusätzliche Reibung und Änderungen der Bewegungsenergie lassen wir in diesem Modell weg.';});
edit('sec2',b=>{b.querySelector('p').textContent='Beim Gleiten mit Reibung nimmt häufig die innere Energie der beteiligten Körper zu: Sie erwärmen sich. Die Reibungskraft wirkt der Bewegung entgegen und verrichtet am gleitenden Körper negative Arbeit. Zieht man gleichmäßig, verrichtet die Zugkraft gleichzeitig positive Arbeit. Wärme bezeichnet erst die Energieübertragung aufgrund eines Temperaturunterschieds.';b.querySelector('.interactive-zone p').textContent='Modell: Der Schlitten wird gleichmäßig waagrecht 4 m gezogen. Die konstante Zugkraft gleicht die Reibungskraft aus. Die Anzeige berechnet die positive Zugarbeit. Die Reibungsarbeit am Schlitten hat den gleichen Betrag mit negativem Vorzeichen; seine Bewegungsenergie bleibt unverändert.';});t.sections.find(s=>s.id==='sec2').title='3. Reibung: Körper erwärmen sich';
edit('sec3',b=>{b.querySelector('p').textContent='Eine ideale Rampe, ein idealer Hebel oder Flaschenzug spart Kraft, indem der Kraftweg länger wird. Für dieselbe Hubhöhe bleibt die nötige Arbeit ohne Reibung gleich. Bei realen Maschinen ist wegen Reibung zusätzliche zugeführte Arbeit nötig. Die Beispielwerte der Rampen gelten für dieselbe Last und Höhe; die Zeichnung ist nicht maßstäblich.';});
function change(id,question,answers,feedback){const q=[...t.sections.flatMap(s=>s.quizzes||[]),...t.diplom.questions].find(q=>q.id===id);Object.assign(q,{question,answers:answers.map((text,i)=>({text,correct:i===0,pts:0,feedback:feedback[i]}))});}
change('q1','Du drückst gegen eine starre Wand, die sich nicht bewegt. Welche mechanische Arbeit verrichtet deine Kraft an dieser Wand?',['0 J, weil sich der Angriffspunkt der Kraft nicht verschiebt.','Über 1000 J, sobald du dich sehr anstrengst.'],['Deine Muskeln setzen trotzdem Energie um. Die Frage betrachtet nur die Arbeit an der unbewegten Wand.','Anstrengung allein bestimmt nicht die mechanische Arbeit am betrachteten Gegenstand.']);
change('q2','Ein Gegenstand wird ohne zusätzliche Beschleunigung nach oben gehoben. Welche Energie nimmt dabei zu?',['Die Lageenergie des Systems aus Gegenstand und Erde.','Seine Bewegungsenergie muss dabei zunehmen.'],['Bei einer Höhenzunahme steigt die Lageenergie um m · g · h.','Bei gleichbleibender Geschwindigkeit bleibt die Bewegungsenergie gleich.']);
change('q3','Ein Schlitten wird durch Gleitreibung langsamer. Was geschieht mit der abnehmenden Bewegungsenergie?',['Sie erhöht unter anderem die innere Energie von Schlitten und Untergrund.','Sie wird vernichtet.'],['Die beteiligten Körper können sich erwärmen; Energie bleibt erhalten.','Die Energie wird umgewandelt, nicht vernichtet.']);
change('f2','Wann gilt für die Arbeit einer Kraft die einfache Formel W = F · s?',['Bei konstanter Kraft parallel zum Weg in Bewegungsrichtung.','Bei jeder beliebigen Kraftrichtung unverändert.'],['Hier ist die ganze Kraft in Wegrichtung wirksam.','Senkrechte Kräfte verrichten keine Arbeit; entgegengerichtete Kräfte negative Arbeit.']);
change('f4','Du hältst einen Sack vollkommen unbewegt. Was gilt für die mechanische Arbeit deiner Haltekraft am Sack?',['Sie ist 0 J; deine Muskeln setzen trotzdem Energie um.','Sie steigt allein mit der Dauer des Haltens.'],['Die Arbeit am Sack und die Energieumsetzung im Körper sind zu unterscheiden.','Ohne Verschiebung ist die mechanische Arbeit am Sack null.']);
change('f10','Ein idealer Flaschenzug hebt dieselbe Last auf dieselbe Höhe. Wie verändert er die nötige Zugarbeit?',['Sie bleibt gleich: weniger Zugkraft, dafür längerer Zugweg.','Er verringert Kraft und Zugweg gleichzeitig.'],['Dies gilt ohne Reibung. Ein realer Flaschenzug benötigt zusätzliche Arbeit gegen Reibung.','Kraft und Weg können beim idealen Flaschenzug nicht beide kleiner werden, wenn dieselbe Last gleich hoch gehoben wird.']);
t.learningGoals=[...new Set([...t.learningGoals,'Positive, negative und verschwindende Arbeit anhand der Kraftrichtung unterscheiden.'])];t.summary=[...new Set([...t.summary,'Entgegen der Bewegung wirkt eine Kraft mit negativer Arbeit; genau senkrecht zum Weg verrichtet sie keine Arbeit.','Beim Halten kann mechanische Arbeit am unbewegten Gegenstand null sein, obwohl die Muskeln Energie umsetzen.'])];t.sources=t.sources||[];const url='https://openstax.org/books/college-physics-2e/pages/7-1-work-the-scientific-definition';if(!t.sources.some(s=>s.url===url))t.sources.push({title:'OpenStax: Mechanische Arbeit',url});
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');const rf=path.join(root,'js/chapter-revisions.js'),src=fs.readFileSync(rf,'utf8'),c={window:{}};vm.runInNewContext(src,c);c.window.SCIVERSE_CHAPTER_REVISIONS.arbeit=Math.max(2,c.window.SCIVERSE_CHAPTER_REVISIONS.arbeit||0);fs.writeFileSync(rf,src.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
