const fs=require('fs'),path=require('path'),vm=require('vm');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.wetter;
const paragraphs=[
 'Wetter beschreibt den Zustand der Atmosphäre an einem Ort zu einer bestimmten Zeit. Temperatur, Luftdruck, Wind und Luftfeuchtigkeit sind messbare Wettergrößen. Notiere zu Messwerten immer Ort, Zeitpunkt, Einheit und Messbedingungen. Ein Thermometer in direkter Sonne liefert beispielsweise keinen gut vergleichbaren Wert für die Lufttemperatur im Schatten.',
 'Luftdruckunterschiede können Luft in Bewegung setzen. Die Druckgradientkraft wirkt vom höheren zum niedrigeren Druck. Die tatsächliche Windrichtung wird aber auch durch Erdrotation, Reibung und Gelände beeinflusst. Wind weht deshalb nicht immer auf einer geraden Linie vom Hoch zum Tief. Die folgende Animation zeigt nur den vereinfachten Druckausgleich.',
 'In Gewitterwolken können Zusammenstöße von Eisteilchen, Graupel und unterkühlten Tropfen elektrische Ladungen trennen. Auf- und Abwinde verteilen die geladenen Teilchen. Bei einem Blitz findet eine elektrische Entladung statt. Die rasche Erwärmung und Ausdehnung der Luft erzeugt eine Druckwelle: den Donner. Ladung wird dabei getrennt, nicht aus dem Nichts erzeugt. Die Prozentanzeige ist ein Spielmodell und keine Messung einer echten Gewitterwolke.',
 'Wolken bestehen aus kleinen Wassertröpfchen oder Eiskristallen. Werden Niederschlagsteilchen groß genug, fallen sie. Ihre Entstehung in der Wolke und ihr Weg durch die Luft bestimmen, ob Regen, Schnee, Graupel oder Hagel am Boden ankommen. Graupel wächst, wenn unterkühlte Wassertröpfchen an Schnee- oder Eisteilchen gefrieren. Hagel wächst in Gewitterwolken, in denen Aufwinde größere Eiskörner tragen können. Die Auswahl unten zeigt vereinfachte Beispiele; die Außentemperatur allein reicht zur Erklärung nicht aus.',
 'Meeresströmungen transportieren Wasser und Energie und beeinflussen dadurch Wetter und Klima. Wind treibt viele Oberflächenströmungen an. Temperatur und Salzgehalt beeinflussen die Dichte des Meerwassers und damit die Umwälzung; auch Gezeiten, Erdrotation und die Form der Meeresbecken spielen eine Rolle. Das Bild eines Förderbands vereinfacht ein verzweigtes System. Der Golfstrom und seine Fortsetzungen transportieren Wärme im Atlantik. Europas Klima hängt zusätzlich unter anderem von Westwinden, der Lage zum Meer und Gebirgen ab.'
];
for(let i=0;i<t.sections.length;i++){const s=t.sections[i],dom=new JSDOM(s.content),d=dom.window.document;for(const p of d.querySelectorAll('.interactive-zone p'))if(p.textContent.includes('Ohne den warmen Golfstrom'))p.remove();const zones=[...d.querySelectorAll('.interactive-zone')].filter(e=>!e.parentElement.closest('.interactive-zone')).map(e=>e.outerHTML).join('');s.content='<p>'+paragraphs[i]+'</p>'+zones+s.quizzes.map(q=>'{{QUIZ_'+q.id+'}}').join('');dom.window.close();}
const questions=[...t.sections.flatMap(s=>s.quizzes),...t.diplom.questions];
function set(id,question,answers,feedback){const q=questions.find(q=>q.id===id);q.question=question;q.answers=answers.map((text,i)=>({text,correct:i===0,pts:0,feedback:feedback[i]}));}
set('wetter_s2_q1','Was zeigt die vereinfachte Windanimation?',['Den Druckausgleich von höherem zu niedrigerem Druck ohne weitere Einflüsse.','Die genaue Windrichtung an jedem Ort der Erde.','Dass die Erdrotation keinen Einfluss auf Wind hat.'],['Reale Windrichtungen werden zusätzlich beeinflusst.','Gelände, Reibung und Erdrotation sind hier nicht dargestellt.','Die Erdrotation kann bewegte Luft ablenken.']);
set('wetter_s3_q1','Welche Beschreibung eines Blitzes stimmt?',['Ein Blitz ist eine elektrische Entladung nach Ladungstrennung.','In der Wolke entsteht elektrische Ladung aus dem Nichts.','Ein Blitz ist reflektiertes Sonnenlicht.'],['Ladungen werden getrennt und können sich durch eine Entladung ausgleichen.','Elektrische Ladung wird erhalten.','Reflexion erklärt keinen Blitz.']);
set('wetter_s5_q1','Was erhöht unter sonst gleichen Bedingungen die Dichte von Meerwasser?',['Abkühlung oder höherer Salzgehalt.','Erwärmung oder niedrigerer Salzgehalt.','Nur die blaue Farbe des Wassers.'],['Dichteres Wasser kann gegenüber weniger dichtem Wasser absinken.','Diese Änderungen verringern üblicherweise die Dichte.','Die Farbe bestimmt die Dichte nicht.']);
set('wetter_s5_q2','Welche Rolle spielt der Golfstrom für das Klima?',['Er transportiert Wärme im Atlantik; weitere Einflüsse bestimmen Europas Klima mit.','Er erklärt allein jeden europäischen Winter.','Er ist die einzige Meeresströmung auf der Erde.'],['Zum Klima tragen auch Luftströmungen und geografische Bedingungen bei.','Ein einzelner Faktor erklärt Europas Klima nicht vollständig.','Die Ozeane besitzen viele miteinander verbundene Strömungen.']);
set('w_d3','Was bedeutet eine relative Luftfeuchtigkeit von 50 %?',['Der Wasserdampfdruck beträgt die Hälfte des Sättigungswerts bei dieser Temperatur.','Die Luft besteht zur Hälfte aus Wasser.','Die Temperatur beträgt 50 °C.'],['Der Prozentwert bezieht sich auf den temperaturabhängigen Sättigungswert.','Relative Feuchtigkeit ist kein Volumenanteil von Wasser in der Luft.','Temperatur und relative Feuchtigkeit sind verschiedene Messgrößen.']);
set('w_d4','Was gilt häufig für ein Hochdruckgebiet?',['Absinkende Luft hemmt Wolkenbildung; trotzdem können Nebel oder Hochnebel bleiben.','Es ist unabhängig von Jahreszeit und Ort immer sonnig.','Der Luftdruck bestimmt allein alle Wettergrößen.'],['Gerade in der kühlen Jahreszeit ist Hochdruck nicht gleichbedeutend mit Sonnenschein.','Das Wort immer macht die Aussage falsch.','Auch Feuchtigkeit, Temperatur und andere Bedingungen zählen.']);
set('w_d5','Welche Aussage zu Meeresströmungen ist richtig?',['Wind, Dichteunterschiede und Gezeiten können Strömungen antreiben.','Alle Strömungen werden ausschließlich durch Salzgehalt angetrieben.','Gezeiten bewegen Wasser nur senkrecht, niemals seitlich.'],['Verschiedene Antriebe wirken zusammen.','Unter anderem Wind und Temperatur fehlen in dieser Erklärung.','Gezeiten können auch horizontale Strömungen erzeugen.']);
t.sources=[{title:'NOAA: Antriebe von Meeresströmungen (Englisch)',url:'https://oceanexplorer.noaa.gov/ocean-fact/currents/'},{title:'NOAA: Ozean, Wetter und Klima (Englisch)',url:'https://oceanexplorer.noaa.gov/ocean-fact/climate/'},{title:'MeteoSchweiz: Graupel und Schnee',url:'https://www.meteoschweiz.admin.ch/ueber-uns/meteoschweiz-blog/de/2024/04/hoehnenkaltluft-graupel-schnee.html'}];
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');
const rf=path.join(root,'js/chapter-revisions.js'),src=fs.readFileSync(rf,'utf8'),c={window:{}};vm.runInNewContext(src,c);c.window.SCIVERSE_CHAPTER_REVISIONS.wetter=Math.max(1,c.window.SCIVERSE_CHAPTER_REVISIONS.wetter||0);fs.writeFileSync(rf,src.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
