const fs=require('fs'),path=require('path'),vm=require('vm');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.energie;
const prose=[
 'Energie ist eine physikalische Größe. Sie kann gespeichert, übertragen und in verschiedene Formen umgewandelt werden. Damit beschreiben wir beispielsweise das Heben eines Gegenstands, das Erwärmen von Wasser oder das Leuchten einer Lampe. Ein ruhender Körper kann Energie besitzen. Gleichförmige Bewegung braucht keine ständige Energiezufuhr, wenn keine bremsenden Einflüsse wirken.',
 'In einem abgeschlossenen System, das weder Energie noch Materie mit seiner Umgebung austauscht, bleibt die Gesamtenergie erhalten. Innerhalb dieses Systems kann Energie übertragen und umgewandelt werden. Eine Lampe gibt Energie als Licht und durch Erwärmung an ihre Umgebung ab. Die Energie ist damit nicht verschwunden, aber für die Beleuchtung nicht vollständig nutzbar.',
 'Lebensmittel, Batterien und Brennstoffe enthalten chemische Energie. Im Körper wird sie durch chemische Reaktionen unter anderem für Muskelarbeit und das Aufrechterhalten der Körpertemperatur genutzt. Eine Batterie ermöglicht bei geschlossenem Stromkreis die Übertragung elektrischer Energie an die Lampe. Dort entstehen Licht und innere Energie; auch die Umgebung wird erwärmt.',
 'Wind, Sonnenstrahlung und fließendes Wasser liefern erneuerbare Energie: Natürliche Vorgänge stellen diese Quellen auf menschlichen Zeitskalen immer wieder bereit. Trotzdem ist nicht jederzeit beliebig viel Leistung verfügbar. Wetter, Tageszeit, Standort und Anlagen begrenzen die Nutzung. Auch erneuerbare Anlagen benötigen Material und Fläche und können Ökosysteme beeinflussen. Kohle, Erdöl und Erdgas sind begrenzte fossile Energieträger; ihre Verbrennung setzt unter anderem das Treibhausgas CO₂ frei.',
 'Im einfachen Batteriestromkreis fließt dauerhaft Strom, wenn der leitende Weg geschlossen ist und die Batterie eine Spannung bereitstellt. In Metallleitungen sind bewegliche Elektronen die Ladungsträger. Sie sind schon im Draht vorhanden und werden in der Lampe nicht verbraucht. Ein offener Schalter unterbricht den dauerhaften Stromfluss; das bedeutet nicht, dass jede Bewegung aller Elektronen aufhört. Elektrische Energie wird in der Lampe umgewandelt.'
];
for(let i=0;i<5;i++){const s=t.sections.find(s=>s.id==='sec'+i),dom=new JSDOM(s.content),b=dom.window.document.body;b.querySelector('p').textContent=prose[i];
 if(i===0){b.querySelector('#weightText').textContent='Die Hantel liegt am Boden. Für dieses Modell setzen wir hier die Lageenergie null; andere Energieformen sind trotzdem vorhanden.';b.querySelector('.remember-box').textContent='Energie wird in Joule (J) angegeben. Wir betrachten immer, welche Energieform sich verändert und zwischen welchen Körpern Energie übertragen wird.';}
 if(i===1){b.querySelector('.lexikon-box').innerHTML='<strong>Energieformen:</strong> Bewegungsenergie, Lageenergie, chemische Energie und innere Energie sind Beispiele. Wärme bezeichnet die Übertragung von Energie wegen eines Temperaturunterschieds. Ein warmer Körper besitzt innere Energie; er enthält nicht „Wärme“ als Stoff.';const zone=b.querySelector('.interactive-zone');zone.querySelector('h3').textContent='Das Pendel als ideales Modell';zone.querySelector('p').textContent='Das Modell vernachlässigt Reibung und Luftwiderstand. An den Umkehrpunkten ist das Pendel kurz in Ruhe und am höchsten; unten ist es am schnellsten. Ein echtes Pendel gibt Energie an Aufhängung und Luft ab und schwingt ohne erneute Zufuhr immer weniger weit.';}
 if(i===2)b.querySelector('#batteryText').textContent='Die Taschenlampe ist aus. Die Batterie ist noch nicht angeschlossen.';
 if(i===3){b.querySelector('.interactive-zone p').textContent='Der Regler wählt eine vereinfachte Windstufe, keine gemessene Windgeschwindigkeit oder Leistung. Das Modell zeigt auch eine Abschaltung zum Schutz bei Sturm. Die tatsächlichen Einschalt-, Nenn- und Abschaltgeschwindigkeiten hängen von der Anlage ab.';}
 s.content=b.innerHTML;dom.window.close();}
t.sections[0].title='1. Energie speichern und übertragen';t.sections[1].title='2. Energieumwandlung und Erhaltung';t.sections[4].title='5. Elektrische Energie im Stromkreis';
function change(id,question,answers,feedback){const q=[...t.sections.flatMap(s=>s.quizzes||[]),...t.diplom.questions].find(q=>q.id===id);Object.assign(q,{question,answers:answers.map((text,i)=>({text,correct:i===0,pts:0,feedback:feedback[i]}))});}
change('q4','Was bedeutet erneuerbar bei Wind- und Sonnenenergie?',['Natürliche Vorgänge liefern immer wieder Energie; ihre Verfügbarkeit ist zeitlich und örtlich begrenzt.','Jede Anlage liefert überall und jederzeit unbegrenzt Leistung.'],['Erneuerbar bedeutet nicht unbegrenzt verfügbar oder ohne Umweltwirkungen.','Nachts fehlt direkte Sonnenstrahlung; bei Windstille liefert ein Windrad keine Windenergie.']);
for(const id of ['q2','f3'])change(id,'Was bleibt in einem abgeschlossenen System ohne Energie- und Materieaustausch erhalten?',['Die Gesamtenergie, auch wenn ihre Formen sich ändern.','Jede einzelne Energieform muss unverändert bleiben.'],['Energie kann umgewandelt und innerhalb des Systems übertragen werden.','Beim Fallen nimmt Lageenergie ab und Bewegungsenergie zu.']);
change('f7','Was geschieht energetisch beim Einschalten eines Toasters?',['Elektrische Energie erhöht unter anderem die innere Energie der Heizdrähte.','Der Toaster erzeugt neue Energie aus dem Nichts.'],['Die Heizdrähte werden heiß und übertragen Energie an Brot und Umgebung.','Die Energie wird über den Stromkreis zugeführt und umgewandelt.']);
change('f3','Eine warme Tasse Tee kühlt im Zimmer ab. Widerspricht das der Energieerhaltung?',['Nein. Energie wird vom Tee an die kühlere Umgebung übertragen.','Ja. Sobald etwas abkühlt, verschwindet Energie.'],['Der Tee allein ist kein abgeschlossenes System. Die Umgebung muss in der Bilanz berücksichtigt werden.','Die Energie verlässt den Tee, wird aber nicht vernichtet.']);
const qs=[
 ['energy_budget','Eine Modelllampe erhält 100 J elektrische Energie: 20 J werden als Licht abgegeben, 80 J führen zur Erwärmung. Welche Aussage stimmt?',['Die Bilanz ist vollständig: 20 J + 80 J = 100 J.','80 J Energie wurden vernichtet.','Die Lampe gibt insgesamt nur 20 J ab.'],['Die für Beleuchtung weniger nützliche Energie bleibt Teil der Gesamtbilanz.','Erwärmung ist eine Energieumwandlung, keine Vernichtung.','Auch die Erwärmung muss berücksichtigt werden.']],
 ['energy_power','Ein Gerät überträgt 200 J in 10 s. Wie groß ist seine mittlere Leistung?',['20 W.','2000 W.','20 J.'],['P = E / t = 200 J / 10 s = 20 J/s = 20 W.','Teile die Energie durch die Zeit; multipliziere nicht.','Joule ist die Energieeinheit. Leistung wird in Watt angegeben.']]
].map(([id,question,answers,feedback])=>({id,question,answers:answers.map((text,i)=>({text,correct:i===0,pts:0,feedback:feedback[i]}))}));
t.sections=t.sections.filter(s=>s.id!=='energy_balance');t.sections.push({id:'energy_balance',title:'6. Energie bilanzieren und Leistung vergleichen',content:'<p><strong>Modellbilanz:</strong> Eine Lampe erhält 100 J elektrische Energie. Davon werden 20 J als Licht abgegeben und 80 J führen zur Erwärmung. Diese erfundenen Werte beschreiben kein bestimmtes Lampenmodell. Zeichne drei beschriftete Pfeile: Zufuhr, Licht und Erwärmung. Prüfe, ob die Beträge zusammenpassen. Erkläre, weshalb Energiesparen sinnvoll bleibt, obwohl Energie erhalten wird.</p><p><strong>Leistung</strong> beschreibt, wie viel Energie pro Zeit übertragen oder umgewandelt wird. Die mittlere Leistung ist P = E / t. Ihre Einheit Watt (W) bedeutet Joule pro Sekunde. Werden 200 J in 10 s übertragen, sind das 20 W; bei 200 J in 5 s sind es 40 W. Die Energiemenge bleibt gleich, die Übertragung dauert kürzer. Arbeit ist ebenfalls eine Energieübertragung. Verwechsle das Formelzeichen W für Arbeit nicht mit dem Einheitenzeichen W für Watt.</p>'+qs.map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:qs});
t.learningGoals=[...new Set([...t.learningGoals,'Eine einfache Energiebilanz aufstellen und Energie von Leistung unterscheiden.'])];t.summary=[...new Set([...t.summary,'Mittlere Leistung ist übertragene Energie geteilt durch Zeit: P = E/t; 1 W = 1 J/s.','Erneuerbare Energiequellen werden natürlich erneuert, sind aber nicht jederzeit unbegrenzt nutzbar.'])];t.sources=t.sources||[];for(const [title,url]of [['OpenStax: Energieerhaltung','https://openstax.org/books/college-physics-2e/pages/7-6-conservation-of-energy'],['EIA: Erneuerbare Energie','https://www.eia.gov/energyexplained/renewable-sources/']])if(!t.sources.some(s=>s.url===url))t.sources.push({title,url});
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');const rf=path.join(root,'js/chapter-revisions.js'),src=fs.readFileSync(rf,'utf8'),c={window:{}};vm.runInNewContext(src,c);c.window.SCIVERSE_CHAPTER_REVISIONS.energie=Math.max(2,c.window.SCIVERSE_CHAPTER_REVISIONS.energie||0);fs.writeFileSync(rf,src.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
