const fs=require('fs'),path=require('path'),vm=require('vm');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.kraft_und_bewegung;
function edit(id,fn){const s=t.sections.find(s=>s.id===id),dom=new JSDOM(s.content);fn(dom.window.document.body);s.content=dom.window.document.body.innerHTML;dom.window.close();}
edit('sec1',b=>{b.querySelector('p').textContent='Wenn ein Bus bremst, bewegt sich dein Körper zunächst weiter nach vorne. Erst Kräfte, etwa durch Sitz oder Gurt, ändern seine Bewegung. Diese Eigenschaft nennt man Trägheit.';b.querySelector('.lexikon-box').innerHTML='<strong>Trägheitsgesetz:</strong> Ist die Summe aller äußeren Kräfte auf einen Körper null, bleibt er in Ruhe oder bewegt sich geradlinig mit gleichbleibender Geschwindigkeit weiter. Einzelne Kräfte können dabei durchaus wirken: Bei einem Buch auf dem Tisch gleichen sich Gewichtskraft nach unten und Stützkraft nach oben aus.';});
t.sections.find(s=>s.id==='sec1').title='2. Trägheit und Kräftegleichgewicht';
edit('sec2',b=>{b.querySelector('p').textContent='Reibung zwischen Kontaktflächen wirkt dem Rutschen oder dem drohenden Rutschen entgegen. Sie hängt von den Materialien, der Oberflächenbeschaffenheit und der Anpresskraft ab. Mikroskopische Unebenheiten, Haftung und Verformungen spielen eine Rolle; Reibung ist nicht nur ein Verhaken von Unebenheiten.';b.querySelector('.remember-box').innerHTML='<strong>Haften, Gleiten, Rollen:</strong> Haftreibung verhindert zunächst das Rutschen und passt sich bis zu einem Grenzwert an. Sie ist nicht immer maximal und hilft beispielsweise beim Gehen. Gleitreibung wirkt beim Rutschen. Rollwiderstand ist bei geeigneten Rädern auf festem Boden oft kleiner als der Widerstand beim Gleiten; auf weichem Boden oder mit schlechten Lagern muss das nicht gelten.';});
edit('sec4',b=>{b.querySelector('.remember-box').innerHTML='<strong>Kraft und Gegenkraft wirken auf verschiedene Körper.</strong> Du drückst auf die Wand; die Wand drückt gleich stark in Gegenrichtung auf dich. Diese beiden Kräfte sind kein Kräftegleichgewicht an einem einzelnen Körper. Beim Buch auf dem Tisch wirken dagegen Gewichtskraft und Stützkraft beide auf das Buch. Die Gegenkraft zur Gewichtskraft des Buches ist dessen Anziehungskraft auf die Erde.';const p=[...b.querySelectorAll('p')].find(p=>p.textContent.includes('Partner-Auftrag'));if(p)p.innerHTML='<strong>Partner-Auftrag:</strong> Zeichnet Buch, Tisch und Erde. Beschriftet bei jedem Kraftpfeil, welcher Körper auf welchen anderen Körper wirkt. Markiert anschließend ein Kräftegleichgewicht am Buch und ein Kraft-Gegenkraft-Paar in verschiedenen Farben. Vergleicht eure Begründungen.';});
edit('sec5',b=>{b.querySelector('p').textContent='Für dieselbe Beschleunigung braucht ein volles Einkaufswagerl eine größere resultierende Kraft als ein leeres. Die resultierende Kraft ist die Summe aller äußeren Kräfte auf das betrachtete Wagerl, mit ihren Richtungen. Bei unveränderlicher Masse gilt F = m · a.';b.querySelector('.step-list li').innerHTML='<strong>F</strong> bedeutet hier resultierende Kraft, also die Summe aller äußeren Kräfte auf den Körper. Einheit: Newton (N).';const a=b.querySelector('.step-list li:last-child');a.innerHTML='<strong>a</strong> bedeutet Beschleunigung: Änderung der Geschwindigkeit pro Zeit, auch beim Bremsen oder Ändern der Richtung. Einheit: Meter pro Sekunde zum Quadrat (m/s²).';const zone=b.querySelector('.interactive-zone');zone.querySelector('p').textContent='Verändere die resultierende Kraft und die Masse. Die Rechnung gilt für die waagrechte Bewegung. Gewichtskraft und Stützkraft gleichen sich senkrecht dazu aus. Die Wagerlanimation veranschaulicht den Vergleich; sie ist keine maßstäbliche Weg-Zeit-Messung.';const txt=b.querySelector('#forceLabText');if(txt)txt.textContent='Bei gleicher Masse führt mehr resultierende Kraft zu größerer Beschleunigung. Bei gleicher resultierender Kraft führt mehr Masse zu kleinerer Beschleunigung.';});
const newQs=[
 ['force_balance','Auf ein bereits nach rechts rollendes Wagerl wirken waagrecht 6 N nach rechts und 6 N nach links. Was folgt in diesem Modell?',['Es rollt mit unveränderter Geschwindigkeit weiter.','Es muss sofort stehen bleiben.','Es wird schneller, weil insgesamt zwei Kräfte wirken.'],['Die resultierende Kraft ist null: Die bisherige Geschwindigkeit bleibt erhalten.','Kräftegleichgewicht bedeutet keine Beschleunigung, nicht automatisch Stillstand.','Die entgegengesetzten Kräfte gleichen sich aus.']],
 ['force_pair','Die Erde zieht ein Buch nach unten. Welche Kraft ist die zugehörige Gegenkraft nach dem Wechselwirkungsprinzip?',['Das Buch zieht die Erde nach oben, zum Buch hin.','Der Tisch drückt das Buch nach oben.','Die Luft bremst das Buch.'],['Die beiden Wechselwirkungskräfte wirken auf verschiedene Körper: Buch und Erde.','Diese Stützkraft wirkt ebenfalls auf das Buch. Sie gehört zum Kräftegleichgewicht am Buch.','Luftwiderstand ist nicht die Gegenkraft zur Anziehung durch die Erde.']]
].map(([id,question,answers,feedback])=>({id,question,answers:answers.map((text,i)=>({text,correct:i===0,pts:0,feedback:feedback[i]}))}));
const sec=t.sections.find(s=>s.id==='sec5');sec.quizzes=sec.quizzes.filter(q=>!newQs.some(n=>n.id===q.id)).concat(newQs);
edit('sec5',b=>{b.querySelector('[data-net-force-lab]')?.remove();const box=b.ownerDocument.createElement('div');box.className='interactive-zone';box.setAttribute('data-net-force-lab','');box.innerHTML='<h3>Zwei Kräfte auf ein Wagerl</h3><p>Wir betrachten nur waagrechte Kräfte auf ein Wagerl mit 2 kg Masse. Nach rechts ist die positive Richtung. Alle waagrechten Kräfte sind in den beiden Reglern zusammengefasst; zusätzliche Reibung wird nicht angesetzt.</p><p><strong>Vermute:</strong> Was passiert bei gleich großen Kräften, wenn das Wagerl schon rollt? Prüfe anschließend 10 N rechts und 4 N links. Vertausche die Kräfte und erkläre das Vorzeichen.</p><label for="net-force-right">Kraft nach rechts (N)</label><input id="net-force-right" type="range" min="0" max="20" step="1" value="6" oninput="updateNetForceLab()" aria-describedby="net-force-result"><label for="net-force-left">Kraft nach links (N)</label><input id="net-force-left" type="range" min="0" max="20" step="1" value="6" oninput="updateNetForceLab()" aria-describedby="net-force-result"><p id="net-force-result" role="status" aria-live="polite" aria-atomic="true"></p>'+newQs.map(q=>'{{QUIZ_'+q.id+'}}').join('');b.append(box);});
function question(id,question,correct,feedback){const q=[...t.sections.flatMap(s=>s.quizzes||[]),...t.diplom.questions].find(q=>q.id===id);q.question=question;const a=q.answers.find(a=>a.correct);a.text=correct;a.feedback=feedback;}
question('f2','Was besagt das Trägheitsgesetz?','Ein Körper bleibt in Ruhe oder bewegt sich geradlinig gleich schnell weiter, wenn die Summe der äußeren Kräfte null ist.','Einzelne Kräfte können sich ausgleichen. Entscheidend ist die resultierende Kraft.');
question('f8','Was bedeutet Aktion und Reaktion?','Zwei Körper üben aufeinander gleich große, entgegengesetzte Kräfte aus.','Die Kräfte wirken auf verschiedene Körper. Sie gleichen sich deshalb nicht an einem einzelnen Körper aus.');
const friction=t.sections.flatMap(s=>s.quizzes||[]).find(q=>q.id==='q_friction_types');
friction.question='Du drückst leicht gegen eine Kiste auf waagrechtem Boden. Sie rutscht noch nicht. Was gilt für die Haftreibung?';
friction.answers=[
 {text:'Sie gleicht die waagrechte Druckkraft aus, solange ihr Grenzwert nicht überschritten wird.',correct:true,pts:0,feedback:'Haftreibung passt sich der drohenden Gleitbewegung an und ist nicht automatisch maximal.'},
 {text:'Sie wirkt immer mit ihrem größtmöglichen Wert.',correct:false,pts:0,feedback:'Unterhalb der Haftgrenze genügt eine kleinere Reibungskraft, um das Rutschen zu verhindern.'},
 {text:'Sie entsteht erst, wenn die Kiste bereits rutscht.',correct:false,pts:0,feedback:'Haftreibung wirkt ohne relatives Rutschen. Beim Rutschen sprechen wir von Gleitreibung.'}
];
question('q_newton2','Die gleiche resultierende Kraft wirkt auf zwei Körper. Was gilt für den Körper mit größerer Masse?','Seine Beschleunigung ist kleiner.','Bei gleicher resultierender Kraft gilt a = F / m: Mehr Masse ergibt kleinere Beschleunigung.');
question('q3','Hammer und Feder werden auf dem Mond am gleichen Ort aus derselben Höhe gleichzeitig aus der Ruhe losgelassen. Was passiert?','Sie treffen praktisch gleichzeitig auf, weil der Luftwiderstand dort vernachlässigbar ist.','Am selben Ort werden beide gleich beschleunigt; bei gleicher Starthöhe und Startgeschwindigkeit ist auch die Fallzeit gleich.');
t.learningGoals=[...new Set([...t.learningGoals,'Kräftegleichgewicht an einem Körper von Kraft und Gegenkraft an zwei Körpern unterscheiden.'])];t.summary=[...new Set([...t.summary,'Für die Beschleunigung zählt die resultierende Kraft. Kräftegleichgewicht bedeutet unveränderte Geschwindigkeit, auch bei einem bereits bewegten Körper.','Kraft und Gegenkraft wirken auf verschiedene Körper; Haftreibung kann Rutschen verhindern, ohne dass sich die Kontaktflächen gegeneinander bewegen.'])];
t.sources=t.sources||[];for(const [title,url]of [['OpenStax: Newtons erstes Gesetz','https://openstax.org/books/university-physics-volume-1/pages/5-2-newtons-first-law'],['OpenStax: Newtons zweites Gesetz','https://openstax.org/books/university-physics-volume-1/pages/5-3-newtons-second-law'],['OpenStax: Reibung','https://openstax.org/books/university-physics-volume-1/pages/6-2-friction'],['The Physics Classroom: Newtons Gesetze','https://www.physicsclassroom.com/Class/newtlaws']])if(!t.sources.some(s=>s.url===url))t.sources.push({title,url});
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');const rf=path.join(root,'js/chapter-revisions.js'),src=fs.readFileSync(rf,'utf8'),c={window:{}};vm.runInNewContext(src,c);c.window.SCIVERSE_CHAPTER_REVISIONS.kraft_und_bewegung=Math.max(2,c.window.SCIVERSE_CHAPTER_REVISIONS.kraft_und_bewegung||0);fs.writeFileSync(rf,src.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
