const fs=require('fs'),path=require('path'),vm=require('vm');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),topic=data.elektrizitaet;
const texts=[
 ['Elektrische Ladungen','Atome enthalten positiv geladene Protonen im Kern und negativ geladene Elektronen in der Hülle. Ein neutrales Atom besitzt gleich viele Protonen wie Elektronen. Gleichnamige Ladungen stoßen sich ab; ungleichnamige ziehen sich an. Die Zeichnung zeigt ein vereinfachtes Atommodell: Elektronen fliegen nicht wie Planeten auf festen Kreisbahnen.'],
 ['Strom und Ladungsträger','Elektrischer Strom ist gerichteter Ladungstransport. In einem Metalldraht tragen bewegliche Elektronen dazu bei; in leitenden Flüssigkeiten können positive und negative Ionen Ladung transportieren. Elektronen sind bereits im gesamten Draht vorhanden. Sie werden in der Lampe nicht verbraucht: Dort wird elektrische Energie in andere Formen umgewandelt. Kupfer leitet gut. Trockener Kunststoff isoliert unter üblichen Bedingungen gut. Leitungswasser leitet wegen gelöster Ionen; sehr reines Wasser leitet wesentlich schlechter. Beschädigte Kabel dürfen nicht benutzt werden.'],
 ['Stromkreis und Widerstand','Für einen dauerhaften Gleichstrom braucht es einen geschlossenen leitenden Weg und eine Energiequelle. In einer Reihenschaltung ist die Stromstärke überall gleich. Wird der Weg unterbrochen, erlöschen alle Lampen. Bei einer Parallelschaltung liegen Zweige an derselben Spannung: Wird nur ein Zweig unterbrochen, können die anderen weiterarbeiten. Der Widerstand hängt unter anderem von Material, Länge, Querschnitt und Temperatur ab. Elektronen übertragen beim Stromfluss Energie an das Material; die Erwärmung ist nicht einfach Reibung von Elektronen aneinander. Ob ein Bauteil heiß wird, hängt auch von Stromstärke und Wärmeabgabe ab.'],
 ['Batterie und Spannung','Eine Batterie wandelt bei der Entladung chemische Energie in elektrische Energie um. Ihre Spannung beschreibt die Energieübertragung pro transportierter Ladungsmenge. Elektronen bewegen sich im äußeren metallischen Stromkreis im Mittel vom Minuspol zum Pluspol. Die vereinbarte technische Stromrichtung verläuft entgegengesetzt. Im Inneren ermöglicht der Elektrolyt den Ladungstransport durch Ionen. Er ist daher keine undurchlässige Mauer für jede Ladung. Beim Entladen heißt die negative Elektrode Anode und die positive Kathode; diese Polzuordnung gilt nicht allgemein für jeden elektrochemischen Vorgang.'],
 ['Kondensator als Energiespeicher','Ein Kondensator besitzt zwei leitende Flächen, getrennt durch einen Isolator. Beim Laden entsteht ein Überschuss negativer Ladung auf einer Fläche und ein entsprechender Mangel auf der anderen. Energie ist im elektrischen Feld gespeichert. Ein Kondensator kann Energie schnell abgeben, etwa in einem Kamerablitz. Die Entladedauer hängt aber von der gesamten Schaltung ab; sie ist nicht immer kurz. Geräte mit Kondensatoren werden für unsere Aufgaben nicht geöffnet.'],
 ['Spannung, Stromstärke und Widerstand','Die Spannung U wird in Volt (V), die Stromstärke I in Ampere (A) und der Widerstand R in Ohm (Ω) angegeben. Stromstärke bedeutet Ladungsmenge pro Zeit. Für einen ohmschen Widerstand bei gleichbleibenden Bedingungen gilt U = R · I, also I = U ÷ R. Bei 6 V und 50 Ω ergibt sich 0,12 A. Eine doppelte Spannung ergibt bei gleichem Widerstand die doppelte Stromstärke. Reale Glühlampen ändern beim Erwärmen ihren Widerstand. Der Rechner verwendet feste Widerstandswerte; die Lampenhelligkeit ist nur eine Anzeige für die berechnete Stromstärke, keine Vorhersage einer echten Lampe.']
];
for(let i=0;i<6;i++){
 const s=topic.sections[i],dom=new JSDOM('<body>'+s.content+'</body>'),d=dom.window.document;
 const models=[...d.querySelectorAll('.interactive-zone, .diagram-box')].filter(el=>!el.parentElement.closest('.interactive-zone, .diagram-box')).map(el=>el.outerHTML).join('');
 s.title=(i+1)+'. '+texts[i][0];s.content='<p>'+texts[i][1]+'</p>'+models+s.quizzes.map(q=>'{{QUIZ_'+q.id+'}}').join('');
 dom.window.close();
}
const all=topic.sections.flatMap(s=>s.quizzes||[]);
function revise(id,question,answers,feedback){const q=all.find(q=>q.id===id);q.question=question;q.answers=answers.map((text,i)=>({text,correct:i===0,pts:0,feedback:feedback[i]}));}
revise('elektrizitaet_s0_q1','Welche Teilchen transportieren Ladung im Kupferdraht?',['Bewegliche Elektronen.','Die positiven Atomkerne, die durch den Draht wandern.','Nur Elektronen, die neu aus der Batterie entstehen.'],['Bewegliche Elektronen sind schon im Metall vorhanden.','Die Atomkerne bleiben im Metallgitter gebunden.','Die Batterie liefert Energie; sie muss den Draht nicht erst mit Elektronen füllen.']);
revise('elektrizitaet_s1_q1','Wozu dient die intakte Kunststoffhülle eines Kabels?',['Sie isoliert die leitenden Adern und verhindert direkten Kontakt.','Sie macht ein beschädigtes Kabel immer sicher.','Sie erhöht absichtlich den Strom durch unsere Hand.'],['Die Hülle trennt Leiter voneinander und von der Umgebung.','Beschädigte Kabel dürfen nicht benutzt werden.','Die Hülle soll den Kontakt zum Leiter verhindern.']);
revise('elektrizitaet_s2_q1','Warum kann ein Heizdraht beim Stromfluss warm werden?',['Elektrische Energie wird an das Material übertragen und erhöht dessen innere Energie.','Elektronen werden verbraucht und verschwinden vollständig.','Der Widerstand erzeugt Energie aus dem Nichts.'],['Die Energie stammt aus der Energiequelle und wird umgewandelt.','Ladung wird im Draht nicht verbraucht.','Widerstand ist keine Energiequelle.']);
revise('elektrizitaet_s3_q0','Wie wird Ladung im Elektrolyten einer Batterie transportiert?',['Durch bewegliche Ionen.','Der Elektrolyt verhindert jeden Ladungstransport.','Durch einen leeren Tunnel für alle Elektronen.'],['Geladene Ionen ermöglichen den inneren Ladungstransport.','Ohne inneren Ladungstransport wäre kein dauerhafter Strom möglich.','Der Elektrolyt ist kein metallischer Elektronenleiter.']);
revise('elektrizitaet_s3_q1','Welche Richtung hat die mittlere Elektronenbewegung im äußeren Metallkreis einer entladenen Batterie während der Stromabgabe?',['Vom Minuspol zum Pluspol.','Vom Pluspol zum Minuspol.','Die Elektronen wechseln ständig zu Protonen.'],['Die technische Stromrichtung ist entgegengesetzt vereinbart.','Das ist die technische Stromrichtung, nicht die Richtung der Elektronenbewegung.','Elektronen werden im Draht nicht zu Protonen.']);
all.find(q=>q.id==='elektrizitaet_s3_q1').question='Welche Richtung hat die mittlere Elektronenbewegung im äußeren Metallkreis einer Batterie während der Stromabgabe?';
revise('elektrizitaet_s4_q0','Welche Aussage zum Kondensator stimmt?',['Er speichert Energie im elektrischen Feld und kann sie je nach Schaltung schnell abgeben.','Er erzeugt bei jeder Entladung neue Energie.','Er muss sich unabhängig von der Schaltung immer gleich schnell entladen.'],['Auch der angeschlossene Widerstand beeinflusst die Entladedauer.','Er gibt zuvor gespeicherte Energie ab.','Die Entladedauer hängt von Kondensator und Schaltung ab.']);
const finalQuestions=[
 ['Eine Lampe leuchtet in einem unverzweigten Stromkreis. Was gilt vor und nach der Lampe?',['Die Stromstärke ist gleich; Energie wird in der Lampe umgewandelt.','Nach der Lampe fließt weniger Strom, weil sie Strom verbraucht.','Vor der Lampe fließen Elektronen, danach nur Protonen.'],['Ladung wird erhalten; Energie wird beispielsweise in Licht und innere Energie umgewandelt.','Die Lampe verbraucht keine Ladung.','Die Ladungsträger wechseln nicht ihre Teilchenart.']],
 ['Im Ohm-Modell liegen 6 V an 50 Ω. Was ergibt sich bei 12 V und unveränderten 50 Ω?',['0,24 A.','0,06 A.','600 A.'],['12 geteilt durch 50 ergibt 0,24: doppelt so viel wie 0,12 A.','Das wäre halb so viel; bei festem Widerstand steigt die Stromstärke mit der Spannung.','Hier wird Spannung durch Widerstand geteilt, nicht multipliziert.']]
].map(([question,answers,feedback],i)=>({id:'electric_transfer_'+i,question,answers:answers.map((text,j)=>({text,correct:j===0,pts:0,feedback:feedback[j]}))}));
topic.sections[6]={id:'sec6',title:'7. Erklären und überprüfen',content:'<p>Stelle im Rechner zuerst 6 V und 50 Ω ein. Sage voraus, was bei doppelter Spannung geschieht, und prüfe deine Vermutung. Halte anschließend die Spannung fest und verdopple den Widerstand. Notiere jeweils Einstellung, Vorhersage, Ergebnis und Erklärung.</p><p>Diese Aufgaben finden am Bildschirm statt. Reale Schulversuche werden nur mit den dafür vorgesehenen Kleinspannungsquellen nach Anleitung der Lehrkraft durchgeführt; niemals an Steckdosen. Batteriepole nicht direkt miteinander verbinden.</p>'+finalQuestions.map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:finalQuestions};
topic.title='⚡ Elektrizität: Ladung, Stromkreis und Energie';topic.subtitle='Stromstärke, Spannung und Widerstand unterscheiden und mit Modellen untersuchen.';
topic.sources=[{title:'OpenStax: Elektrischer Strom (Englisch)',url:'https://openstax.org/books/college-physics-2e/pages/20-1-current'},{title:'OpenStax: Ohmsches Gesetz (Englisch)',url:'https://openstax.org/books/college-physics-2e/pages/20-2-ohms-law-resistance-and-simple-circuits'},{title:'OpenStax: Energiequellen und Batterien (Englisch)',url:'https://openstax.org/books/university-physics-volume-2/pages/10-1-electromotive-force'}];
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');
const rf=path.join(root,'js/chapter-revisions.js'),source=fs.readFileSync(rf,'utf8'),ctx={window:{}};vm.runInNewContext(source,ctx);ctx.window.SCIVERSE_CHAPTER_REVISIONS.elektrizitaet=Math.max(1,ctx.window.SCIVERSE_CHAPTER_REVISIONS.elektrizitaet||0);fs.writeFileSync(rf,source.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(ctx.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
console.log('Electricity concepts corrected; old inline final replaced with two assessed transfer tasks.');
