const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
function firstParagraph(topic,index,text){const s=d[topic].sections[index],$=cheerio.load(s.content);$('p').first().text(text);s.content=$('body').html();}
function replace(topic,from,to){for(const s of d[topic].sections)s.content=s.content.replaceAll(from,to);}
function question(topic,id,question,answers){const q=d[topic].sections.flatMap(s=>s.quizzes||[]).find(q=>q.id===id);if(!q)throw Error(id);q.question=question;q.answers=answers.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}));}
firstParagraph('farben',0,'Atome können Energie aufnehmen und dadurch angeregt werden. Beim Übergang in einen Zustand geringerer Energie können sie ein Lichtquant, ein Photon, abgeben. Im vereinfachten Modell stellen wir unterschiedliche Energieniveaus als Bahnen dar. Elektronen bewegen sich dabei nicht wie kleine Planeten auf gezeichneten Kreisbahnen.');
replace('farben','Sie machen einen Quantensprung auf eine höhere Bahn.','Sie wechseln in einen Zustand höherer Energie.');
replace('farben','<b>Blau:</b> Hat die kürzesten Wellen (ganz viel Energie!).','<b>Blau:</b> Hat kürzere Wellenlängen als Rot. Violett liegt am kurzwelligen Ende des sichtbaren Spektrums.');
replace('farben','Hat die kürzesten Wellen (ganz viel Energie!).','Hat kürzere Wellenlängen als Rot. Violett liegt am kurzwelligen Ende des sichtbaren Spektrums.');
// Correct the whole explanatory list item independently of its inline emphasis tags.
{const s=d.farben.sections[1],$=cheerio.load(s.content);$('li').each((_,el)=>{if($(el).text().includes('Hat die kürzesten Wellen'))$(el).text('Violett liegt am kurzwelligen Ende des sichtbaren Spektrums. Blau ist kurzwelliger als Rot.');});s.content=$('body').html();}
firstParagraph('farben',1,'Licht lässt sich als elektromagnetische Welle beschreiben. Die Wellenlänge ist der Abstand zwischen benachbarten Wellenbergen. Bei sichtbarem Licht einer einzelnen Wellenlänge hängt die wahrgenommene Spektralfarbe damit zusammen. Rot ist langwelliger als Blau; Violett liegt am kurzwelligen Ende. Gemischtes Licht kann ebenfalls einen Farbeindruck erzeugen.');
question('farben','farben_s1_q0','Ein angeregtes Atom sendet Licht aus. Welche Erklärung passt?',[['Es geht in einen Zustand geringerer Energie über und gibt ein Photon ab.',true,'Das Photon trägt die Energie des Übergangs. Das gezeichnete Bahnmodell ist eine Vereinfachung.'],['Es reflektiert dabei ausschließlich Licht aus einer anderen Quelle.',false,'Reflexion ist nicht die hier beschriebene eigene Lichtaussendung.'],['Die Anzahl seiner Elektronen muss sich dabei immer verringern.',false,'Bei einem solchen Übergang wird Energie abgegeben; ein Elektron muss das Atom dafür nicht verlassen.']]);
question('farben','farben_s2_q0','Wie unterscheiden sich rotes und blaues Licht einzelner Wellenlängen?',[['Blau hat kürzere Wellenlängen und energiereichere einzelne Photonen als Rot.',true,'Die Aussage betrifft die Energie eines einzelnen Photons, nicht automatisch die gesamte Lichtmenge.'],['Blau hat längere Wellenlängen als Rot.',false,'Im sichtbaren Spektrum ist Rot langwelliger als Blau.'],['Ein blauer Lichtstrahl überträgt unabhängig von seiner Stärke immer mehr Gesamtenergie.',false,'Die Gesamtenergie hängt auch von der Anzahl der Photonen ab.']]);
question('farben','farben_extra_itten_q0','Welche drei Primärfarben verwendet der hier behandelte Itten-Farbenkreis?',[['Rot, Gelb und Blau.',true,'Das sind die Primärfarben dieses traditionellen Malfarbenmodells. Es beschreibt nicht alle technisch mischbaren Farben.'],['Rot, Grün und Blau.',false,'RGB sind die Grundfarben des hier behandelten additiven Lichtmodells.'],['Cyan, Magenta und Gelb.',false,'Diese Kombination gehört zum subtraktiven CMY-Modell, nicht zum Itten-Kreis.']]);
question('farben','farben_extra_mischung_q0','Was kann die passende Mischung aus rotem, grünem und blauem Licht erzeugen?',[['Den Eindruck von weißem Licht.',true,'Bei geeigneten Intensitäten ergibt die additive RGB-Mischung einen weißen Farbeindruck.'],['Schwarz, weil sich die Lichtanteile gegenseitig aufbrauchen.',false,'Lichtanteile werden bei additiver Mischung hinzugefügt, nicht wie von Pigmenten absorbiert.'],['Immer denselben Farbeindruck, unabhängig von den Intensitäten.',false,'Das Verhältnis der Lichtanteile beeinflusst den wahrgenommenen Farbton.']]);
firstParagraph('linsen_spiegel',1,'Licht breitet sich in Wasser und Glas langsamer aus als im Vakuum. Beim schrägen Übergang zwischen Medien unterschiedlicher Brechzahl ändert sich im Allgemeinen auch die Ausbreitungsrichtung. Das nennen wir Brechung. Die Bezeichnung optisch dichter bezieht sich hier auf die Brechzahl und ist nicht mit einer größeren Massendichte gleichzusetzen.');
firstParagraph('linsen_spiegel',3,'Hornhaut und Augenlinse bündeln einfallendes Licht. Auf der Netzhaut entsteht bei scharfem Sehen ein umgekehrtes Bild. Sinneszellen wandeln Licht in Signale um, die im Nervensystem verarbeitet werden. Das Gehirn betrachtet dabei kein kleines Bild wie eine Person vor einem Bildschirm.');
replace('linsen_spiegel','bis sie sich alle in einem superheißen Punkt treffen: dem Brennpunkt (Fokus).','sodass achsennahe parallele Strahlen näherungsweise im Brennpunkt (Fokus) zusammentreffen.');
replace('linsen_spiegel','bis sie sich alle in einem superheißen Punkt treffen: dem <strong>Brennpunkt (Fokus)</strong>.','sodass achsennahe parallele Strahlen näherungsweise im <strong>Brennpunkt (Fokus)</strong> zusammentreffen.');
question('linsen_spiegel','q2','Warum ändert ein Lichtstrahl beim schrägen Übergang von Luft in Wasser seine Richtung?',[['Die Ausbreitungsgeschwindigkeit ist in beiden Medien unterschiedlich.',true,'Die Brechung hängt von der Brechzahl und dem Einfallswinkel ab.'],['Jede Flüssigkeit lenkt Licht immer um denselben Winkel ab.',false,'Stoff und Einfallswinkel beeinflussen die Richtungsänderung.']]);
question('linsen_spiegel','linsen_s6_q0','Welche beiden optischen Baugruppen verwendet das hier dargestellte zusammengesetzte Lichtmikroskop?',[['Objektiv und Okular.',true,'Das Objektiv erzeugt ein vergrößertes Zwischenbild, das mit dem Okular betrachtet wird. Beide können aus mehreren Linsen bestehen.'],['Nur einen ebenen Spiegel ohne Linsen.',false,'Das dargestellte System benötigt die abbildenden Baugruppen Objektiv und Okular. Eine einzelne Lupe ist ein anderes, einfacheres optisches System.']]);
// Keep numbering consistent with the real sequence of cards.
d.linsen_spiegel.sections.forEach((s,i)=>s.title=s.title.replace(/^\d+\./,(i+1)+'.'));
for(const[topic,source]of [['farben',{title:'NASA: Sichtbares Licht',url:'https://science.nasa.gov/ems/09_visiblelight/'}],['linsen_spiegel',{title:'OpenStax: Image Formation by Lenses',url:'https://openstax.org/books/college-physics-2e/pages/25-6-image-formation-by-lenses'}]]){d[topic].sources=d[topic].sources||[];if(!d[topic].sources.some(s=>s.url===source.url))d[topic].sources.push(source);}
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');console.log('Corrected spectral color, photon energy, color-model questions, refraction, eye and compound-microscope wording; numbered optics cards.');
