const fs=require('fs'),path=require('path'),vm=require('vm');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8')),t=data.elektromagnetismus;
const texts={sec1:'Eine stromdurchflossene Spule erzeugt ein Magnetfeld. Bei gleicher Geometrie und gleicher Stromstärke verstärken mehr Windungen das Feld. Ein geeigneter Weicheisenkern verstärkt die magnetische Wirkung zusätzlich; diese Verstärkung ist nicht unbegrenzt. Holz wirkt hier annähernd wie Luft.',sec3:'Auf bewegte elektrische Ladungen kann im Magnetfeld eine Kraft wirken. Sie steht senkrecht zu Bewegungsrichtung und Magnetfeld. Bei Bewegung genau entlang der Feldrichtung ist dieser magnetische Kraftanteil null. Auf einen stromdurchflossenen Leiter quer zum Feld wirkt dadurch eine Kraft. Im Motor erzeugen Kräfte ein Drehmoment; die Stromsteuerung sorgt dafür, dass die Drehung weitergeht.',sec4:'Ändert sich der magnetische Fluss durch eine Spule, wird eine Spannung induziert. Anschaulich hängt dieser Fluss davon ab, wie stark das Magnetfeld die Spulenfläche durchsetzt und wie die Fläche zum Feld ausgerichtet ist. Das kann sich beim Hinein- oder Herausbewegen eines Magneten, beim Drehen der Spule oder durch ein zeitlich veränderliches Feld ändern. Strom fließt erst, wenn ein geeigneter leitender Kreis geschlossen ist. Ein Generator überträgt mechanisch zugeführte Energie in elektrische Energie; er erzeugt keine Energie aus dem Nichts.',sec5:'Ein Transformator nutzt ein zeitlich veränderliches Magnetfeld zur Spannungsübertragung zwischen Spulen. Bei konstanter Gleichspannung gibt es nach dem Einschaltvorgang keine dauerhafte induzierte Sekundärspannung. Wechselspannung ermöglicht den fortlaufenden Betrieb. Im idealen Modell gilt U₂/U₁ = N₂/N₁. Mehr Sekundärwindungen erhöhen die Spannung, erzeugen aber keine zusätzliche Energie: Bei gleicher übertragener Leistung ist dann die mögliche Stromstärke kleiner. Reale Transformatoren haben Verluste.'};
for(const s of t.sections){const dom=new JSDOM(s.content),b=dom.window.document.body;if(texts[s.id])b.querySelector('p').textContent=texts[s.id];
 if(s.id==='sec0'){b.querySelector('.lexikon-box').textContent='Feldlinien sind ein Modell zur Darstellung von Richtung und Stärke des Magnetfelds. Um einen langen geraden Leiter verlaufen sie kreisförmig. Die Reglerstufen sind relative Einstellungen, keine Strommessung in Ampere.';}
 if(s.id==='sec3'){for(const h of b.querySelectorAll('h3'))if(h.textContent.includes('High-Quality'))h.textContent='Animation zur Lorentzkraft';for(const p of b.querySelectorAll('p'))if(p.textContent.includes('Manim'))p.textContent='Beobachte die Richtungen von Magnetfeld, technischem Strom und Kraft. Die technische Stromrichtung ist in einem Metall entgegengesetzt zur Bewegungsrichtung der Elektronen.';}
 if(s.id==='sec4')b.querySelector('.interactive-zone p').textContent='Jeder Klick steht für mechanische Arbeit beim Schütteln. Ein Energiespeicher versorgt anschließend die Lampe. Die Prozentanzeige ist ein vereinfachter Speicherstand, keine Messung elektrischer Ladung.';
 if(s.id==='sec5')b.querySelector('.interactive-zone p').textContent='Vergleiche die Ausgangsspannung bei 2, 5 und 10 Sekundärwindungen. Die Primärseite bleibt bei 5 Modellwindungen und 230 V Wechselspannung. Gezeigt wird der unbelastete ideale Transformator; deshalb sind keine strömenden Ladungen auf der offenen Sekundärseite eingezeichnet. Windungszahlen und Zeichnung sind schematisch. Dies ist ein Bildschirmmodell, keine Anleitung zum Experimentieren an Netzspannung.';
 s.content=b.innerHTML.replace('Ladung:','Modell-Speicherstand:');dom.window.close();}
function set(id,question,correct,wrong,yes,no){const q=[...t.sections.flatMap(s=>s.quizzes||[]),...t.diplom.questions].find(q=>q.id===id);Object.assign(q,{question,answers:[{text:correct,correct:true,pts:0,feedback:yes},{text:wrong,correct:false,pts:0,feedback:no}]});}
set('em_s4_q1','Was ist die entscheidende Voraussetzung für induzierte Spannung in einer Spule?','Der magnetische Fluss durch die Spule ändert sich.','Ein Magnet liegt unbewegt bei unverändertem Feld neben einer ruhenden Spule.','Eine Änderung kann durch Bewegung oder ein zeitlich veränderliches Feld entstehen.','Ein zeitlich unveränderter Fluss induziert keine Spannung.');
set('em_s5_q1','Warum liefert eine unveränderte Gleichspannung am gewöhnlichen Transformator keine dauerhafte Sekundärspannung?','Nach dem Einschaltvorgang fehlt die fortlaufende Änderung des magnetischen Flusses.','Gleichstrom ist grundsätzlich zu schwach.','Beim Ein- oder Ausschalten können kurzzeitig Spannungen induziert werden.','Die Stromstärke allein ist nicht entscheidend; Induktion braucht Flussänderung.');
set('em_d6','Wie heißt die magnetische Kraft auf eine Ladung, die quer zum Magnetfeld bewegt wird?','Lorentzkraft.','Zentrifugalkraft.','Ihre Richtung hängt von Ladungsvorzeichen, Bewegungsrichtung und Feldrichtung ab.','Die magnetische Kraft auf bewegte Ladungen gehört zur Lorentzkraft.');
set('em_d7','Welches Gerät wandelt elektrische Energie vor allem in mechanische Bewegung um?','Elektromotor.','Generator.','Ein Motor kann zum Beispiel einen Ventilator antreiben.','Ein Generator wird mechanisch angetrieben und liefert elektrische Energie.');
set('em_d8','Welches Prinzip nutzt ein Fahrraddynamo?','Elektromagnetische Induktion.','Reibung erzeugt direkt den elektrischen Strom.','Die Drehbewegung verändert den magnetischen Fluss durch Spulen.','Ein Reibrad kann den Dynamo antreiben; die elektrische Spannung entsteht durch Induktion.');
set('em_d9','Eine Spule hat offene Anschlüsse. Ein Magnet wird in sie hineingeschoben. Was ist möglich?','Eine induzierte Spannung, auch ohne geschlossenen Laststromkreis.','Es kann keine Spannung geben, weil kein dauerhafter Strom fließt.','Spannung und Strom sind zu unterscheiden. Für dauerhaften Laststrom braucht es einen geschlossenen Weg.','Auch an offenen Anschlüssen kann eine Spannung auftreten.');
set('em_d10','Welches Gerät verändert mithilfe gekoppelter Spulen eine Wechselspannung?','Transformator.','Ein einzelner Transistor.','Die Spannungen hängen im idealen Modell vom Windungsverhältnis ab.','Ein Transistor schaltet oder verstärkt Signale; er ist nicht dieser Spannungswandler aus gekoppelten Spulen.');
set('em_d11','Wie verlaufen die Feldlinien im üblichen Modell eines Stabmagneten?','Außen vom Nord- zum Südpol und im Inneren zurück.','Sie beginnen am Nordpol und enden am Südpol, ohne inneren Verlauf.','Magnetische Feldlinien haben keine Anfangs- oder Endpunkte; die Pole des Magneten bleiben trotzdem vorhanden.','Auch innerhalb des Magneten wird der Feldverlauf fortgesetzt.');
set('em_d12','Ein Permanentmagnet wird auf der Achse einer ruhenden Spule hinein- und herausbewegt. Kann das Spannung induzieren?','Ja, weil sich dabei der magnetische Fluss durch die Spule ändert.','Nein, ein Permanentmagnet kann nie Induktion bewirken.','Die mechanische Bewegung verändert hier den Fluss, obwohl der Magnet selbst dauerhaft magnetisch ist.','Ein zeitlich wechselnder Elektromagnet ist nicht die einzige Möglichkeit zur Flussänderung.');
set('em_d13','Welches Beispiel nutzt einen schaltbaren Elektromagneten?','Ein elektromagnetischer Hebekran für Eisenschrott.','Ein einfacher Holzstuhl ohne elektrische Bauteile.','Strom in einer Spule erzeugt die magnetische Wirkung des Krans.','Ohne entsprechende stromdurchflossene Spule ist der Stuhl kein Elektromagnet.');
set('em_d14','Ein stromdurchflossener Draht liegt quer in einem Magnetfeld. Die Stromrichtung wird umgekehrt, das Feld bleibt gleich. Was ändert sich?','Die magnetische Kraft auf den Draht kehrt ihre Richtung um.','Der Magnet muss dadurch schmelzen.','Bei unveränderter Feldrichtung kehrt die Umkehrung der technischen Stromrichtung die Kraftrichtung um.','Ein Schmelzen folgt nicht aus der Richtungsumkehr.');
set('em_d15','Welche Energieumwandlung findet in einem Generator statt?','Mechanisch zugeführte Energie wird in elektrische Energie umgewandelt.','Elektrische Energie wird ohne Energiezufuhr neu erzeugt.','Der Antrieb muss Arbeit leisten; zusätzlich treten Verluste etwa durch Erwärmung auf.','Ein Generator verletzt nicht die Energieerhaltung.');
t.sources=t.sources||[];for(const [title,url]of [['OpenStax: Induktion','https://openstax.org/books/physics/pages/20-3-electromagnetic-induction'],['OpenStax: Transformatoren','https://openstax.org/books/college-physics-2e/pages/23-7-transformers']])if(!t.sources.some(s=>s.url===url))t.sources.push({title,url});
fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');const rf=path.join(root,'js/chapter-revisions.js'),src=fs.readFileSync(rf,'utf8'),c={window:{}};vm.runInNewContext(src,c);c.window.SCIVERSE_CHAPTER_REVISIONS.elektromagnetismus=Math.max(2,c.window.SCIVERSE_CHAPTER_REVISIONS.elektromagnetismus||0);fs.writeFileSync(rf,src.replace(/window\.SCIVERSE_CHAPTER_REVISIONS=\{[^;]+;/,'window.SCIVERSE_CHAPTER_REVISIONS='+JSON.stringify(c.window.SCIVERSE_CHAPTER_REVISIONS)+';'));
