const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
const guides={
math3_2_potenzen_terme:[['math2_5_var_gleichungen'],['Basis und Exponent einer Potenz unterscheiden.','Einfache Potenzen berechnen und Produkte gleicher Basis zusammenfassen.','Terme für Alltagssituationen aufstellen und gleichartige Terme addieren.'],['aⁿ bedeutet bei positiver ganzer Zahl n ein Produkt aus n gleichen Faktoren a.','Bei gleicher Basis werden beim Multiplizieren die Exponenten addiert: aᵐ · aⁿ = aᵐ⁺ⁿ.','x + x + x = 3x, aber x · x · x = x³.']],
math3_3_gleichungen:[['math2_5_var_gleichungen','math3_2_potenzen_terme'],['Gleichungen durch gleiche Operationen auf beiden Seiten umformen.','Einfache lineare Gleichungen in zwei Schritten lösen.','Eine gefundene Lösung durch Einsetzen überprüfen.'],['Die Gleichheit bleibt erhalten, wenn du auf beiden Seiten dieselbe Zahl addierst oder subtrahierst.','Beide Seiten dürfen durch dieselbe Zahl ungleich 0 dividiert werden.','2x + 1 = 9 ergibt zunächst 2x = 8 und dann x = 4. Die Probe lautet 2 · 4 + 1 = 9.']],
math3_5_verhaeltnisse:[['math2_6_prop_prozent'],['Verhältnisse als Anzahlen gleich großer Teile deuten.','Eine Gesamtmenge in einem vorgegebenen Verhältnis aufteilen.','Mengenverhältnisse an Mischungen und Aufteilungen überprüfen.'],['Bei 1 : 5 bestehen insgesamt 6 Teile: ein Teil der ersten und fünf Teile der zweiten Menge.','Teile die Gesamtmenge durch die Summe der Verhältnisanteile und multipliziere den Einzelteil passend.','40 € im Verhältnis 3 : 5 ergeben 15 € und 25 €. Zusammen bleiben es 40 €.']],
math3_6_zuordnungen:[['math2_6_prop_prozent'],['Direkte und indirekte Proportionalität anhand ihrer Bedingungen unterscheiden.','Direkte Zuordnungen über den Wert einer Einheit berechnen.','Bei fester Arbeitsmenge eine indirekte Zuordnung im vereinfachten Modell berechnen.'],['Direkte Proportionalität: y : x bleibt konstant. Doppeltem x entspricht doppeltes y.','Indirekte Proportionalität: x · y bleibt konstant. Doppeltem x entspricht halbes y.','Bei Arbeitsaufgaben setzt das einfache Modell gleiche Leistung pro Person und eine entsprechend teilbare Arbeit ohne zusätzliche Verzögerung voraus.']],
math3_11_statistik:[['math2_8_statistik'],['Daten aus einem beschrifteten Säulendiagramm lesen.','Arithmetischen Mittelwert und Maximum bestimmen.','Säulen- und Liniendiagramme nach ihrer Aussage unterscheiden.'],['Diagramme brauchen Angaben zu dargestellter Größe, Einheiten und Skala.','Mittelwert = Summe : Anzahl; das Maximum ist der größte beobachtete Wert.','Der Mittelwert ist ein rechnerischer Ausgleich und muss nicht selbst vorkommen. Ein Liniendiagramm kann Veränderungen über eine geordnete Zeitachse zeigen.']]};
for(const[id,[prerequisites,learningGoals,summary]]of Object.entries(guides))Object.assign(d[id],{prerequisites,learningGoals,summary});
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const power=d.math3_2_potenzen_terme;
const ps={id:'m32_rules',title:'Basis, Exponent und Rechenregeln',content:'<p>Bei 2³ ist 2 die Basis und 3 der Exponent: 2³ = 2 · 2 · 2 = 8. Der Exponent zählt die gleichen Faktoren, nicht eine Multiplikation mit der Basis. Bei 2³ · 2² stehen insgesamt fünf Faktoren 2: 2⁵ = 32.</p><p>Für gleiche Basis gilt aᵐ · aⁿ = aᵐ⁺ⁿ. Dagegen ist 2³ + 2² = 8 + 4 = 12; die Produktregel gilt nicht für Summen. Für a ungleich 0 setzt man a⁰ = 1. Mit negativen Basen sind Klammern wichtig: (−2)² = 4, während −2² = −(2²) = −4.</p><p>Terme unterscheiden Addition und Multiplikation: x + x + x = 3x, aber x · x · x = x³.</p>{{QUIZ_m32_product}}{{QUIZ_m32_sign}}',quizzes:[q('m32_product','Was ist 2³ · 2²?',[['2⁵ = 32',true,'Drei Faktoren 2 und zwei weitere Faktoren 2 ergeben fünf Faktoren 2.'],['2⁶ = 64',false,'Bei Produkten gleicher Basis werden die Exponenten addiert, nicht multipliziert.'],['4⁵',false,'Die Basis bleibt 2. Du fasst nur die Anzahl der gleichen Faktoren zusammen.']]),q('m32_sign','Was ist (−2)²?',[['4',true,'Die ganze negative Zahl wird quadriert: (−2) · (−2) = 4.'],['−4',false,'−4 ist der Wert von −2² ohne Klammern. Mit Klammern wird auch das Vorzeichen mitquadriert.']])]};power.sections=power.sections.filter(s=>s.id!==ps.id);power.sections.splice(1,0,ps);
const term=power.sections.find(s=>s.id==='sec2').quizzes[0];term.question='5 Hefte kosten je x Euro, ein Stift kostet 2 Euro. Welcher Term beschreibt den Gesamtpreis in Euro?';term.answers[0].feedback='5x ist der Preis der fünf Hefte. Dazu kommen einmal 2 €.';term.answers[1].feedback='5 ist die Anzahl der Hefte, kein Preis. Die 2 gehört zum einzelnen Stift und wird nicht mit x multipliziert.';
const eq=d.math3_3_gleichungen,es={id:'m33_steps',title:'Zwei Schritte und die Probe',content:'<p>Löse 2x + 1 = 9. Zuerst auf beiden Seiten 1 subtrahieren: 2x = 8. Dann beide Seiten durch 2 dividieren: x = 4. Probe in der ursprünglichen Gleichung: 2 · 4 + 1 = 9.</p><p>Bei 3x − 6 = 15 addierst du zuerst 6: 3x = 21. Danach durch 3 dividieren: x = 7. Probe: 3 · 7 − 6 = 15. Eine Division durch 0 ist nicht definiert.</p>{{QUIZ_m33_twosteps}}{{QUIZ_m33_check}}',quizzes:[q('m33_twosteps','Löse 3x − 6 = 15.',[['x = 7',true,'+6 auf beiden Seiten ergibt 3x = 21. Durch 3 ergibt x = 7.'],['x = 3',false,'Du musst die −6 durch +6 aufheben. 3 · 3 − 6 wäre nur 3.'],['x = 21',false,'21 ist der Wert von 3x. Du musst noch durch 3 teilen.']]),q('m33_check','Wie prüfst du x = 4 für 2x + 1 = 9?',[['2 · 4 + 1 berechnen und mit 9 vergleichen.',true,'Setze die gefundene Zahl in die ursprüngliche Gleichung ein.'],['Nur prüfen, ob 4 kleiner als 9 ist.',false,'Diese Größenordnung reicht nicht. Beide Seiten müssen denselben Wert ergeben.']])]};eq.sections=eq.sections.filter(s=>s.id!==es.id);eq.sections.push(es);
const assignment=d.math3_6_zuordnungen;
if(!assignment.sections[0].content.includes('data-proportional-conditions'))assignment.sections[0].content='<p data-proportional-conditions>Direkte Proportionalität setzt einen gleichbleibenden Preis pro Stück ohne Grundgebühr oder Mengenrabatt voraus. Der Quotient Gesamtpreis : Stückzahl bleibt konstant.</p>'+assignment.sections[0].content;
if(!assignment.sections[1].content.includes('data-work-conditions'))assignment.sections[1].content='<p data-work-conditions>Das folgende Arbeitsmodell nimmt eine feste Arbeitsmenge und gleiche Leistung pro Person an. Die Arbeit muss ohne gegenseitige Behinderung aufteilbar sein. In der Wirklichkeit trifft das nicht immer zu.</p>'+assignment.sections[1].content;
const stat=d.math3_11_statistik;
{const $=cheerio.load(stat.sections[1].content);const p=$('p').filter((_,p)=>$(p).text().includes("was 'normal' ist"));p.text('Der Mittelwert ist ein rechnerischer Ausgleich der Daten. Er muss nicht selbst vorkommen und beschreibt nicht, was für eine einzelne Person normal ist. Wie berechnet man ihn?');stat.sections[1].content=$('body').html();}
{const $=cheerio.load(stat.sections[0].content);$('svg').replaceWith('<svg viewBox="0 0 320 220" role="img" aria-label="Erfundene Buchausleihen: Montag 4, Dienstag 7, Mittwoch 2." style="width:100%;max-width:500px"><path d="M40 15V180H305" fill="none" stroke="currentColor"/><text x="45" y="12" fill="currentColor">Anzahl ausgeliehener Bücher</text><text x="23" y="184" fill="currentColor">0</text><text x="23" y="104" fill="currentColor">4</text><text x="23" y="24" fill="currentColor">8</text><path d="M36 100H305 M36 20H305" stroke="currentColor" opacity="0.2"/><rect x="70" y="100" width="40" height="80" fill="blue"/><rect x="150" y="40" width="40" height="140" fill="red"/><rect x="230" y="140" width="40" height="40" fill="green"/><text x="90" y="203" text-anchor="middle" fill="currentColor">Mo</text><text x="170" y="203" text-anchor="middle" fill="currentColor">Di</text><text x="250" y="203" text-anchor="middle" fill="currentColor">Mi</text></svg><p>Erfundene Daten einer Schulbibliothek: Montag 4, Dienstag 7, Mittwoch 2 ausgeliehene Bücher. Die Skala beginnt bei 0.</p>');stat.sections[0].content=$('body').html();}
if(!stat.sections[1].content.includes('data-statistics-terms'))stat.sections[1].content+='<p data-statistics-terms>Das Maximum ist der größte Wert einer Datenliste, das Minimum der kleinste. Säulendiagramme vergleichen einzelne Häufigkeiten oder Werte. Liniendiagramme verbinden Werte entlang einer geordneten Achse, beispielsweise Messwerte im Zeitverlauf. Das Verbinden darf keinen irreführenden Zusammenhang nahelegen.</p>';
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
