const fs=require('fs'),path=require('path'),cheerio=require('cheerio'),file=path.join(__dirname,'../lang/de.json'),d=JSON.parse(fs.readFileSync(file,'utf8'));
const guides={
math3_7_aehnlichkeit:[['math2_6_prop_prozent'],['Ähnliche Figuren anhand gleicher Form und proportionaler Längen erkennen.','Entsprechende Seitenlängen mit einem gemeinsamen Faktor vergleichen.','Mit Maßstäben rechnen und Längeneinheiten umwandeln.'],['Bei ähnlichen Figuren sind entsprechende Winkel gleich und entsprechende Seitenlängen im gleichen Verhältnis.','Maßstab 1 : n bedeutet: Eine Längeneinheit im Modell entspricht n gleichen Einheiten in Wirklichkeit.','1 km = 100 000 cm. Zum Umrechnen von Zentimetern in Kilometer dividierst du durch 100 000.']],
math3_8_pythagoras:[['math3_2_potenzen_terme','math1_6_winkel'],['Die Hypotenuse im rechtwinkligen Dreieck erkennen.','Die Flächengleichheit a² + b² = c² am Beispiel 3–4–5 nachvollziehen.','Aus den Katheten die Hypotenuse berechnen.'],['Der Satz gilt für rechtwinklige Dreiecke. c liegt gegenüber dem rechten Winkel; a und b sind die Katheten.','a² + b² = c² beschreibt Flächeninhalte der Seitenquadrate.','Nach dem Berechnen von c² folgt c = √(a² + b²). Eine Seitenlänge wird mit Längeneinheit angegeben.']],
math3_9_koerper:[['math2_7_geometrie'],['Ebene Figuren und räumliche Körper als Modelle unterscheiden.','Volumen und Oberfläche begrifflich und anhand der Einheiten unterscheiden.','Das Volumen eines Quaders aus seinen Kantenlängen berechnen.'],['Eine geometrische Fläche ist zweidimensional, ein Körper dreidimensional. Reale Gegenstände werden durch solche Formen modelliert.','Volumen ist Rauminhalt, etwa in cm³; Oberfläche ist der gesamte äußere Flächeninhalt, etwa in cm².','Für den Quader gilt V = a · b · c, wenn die Kantenlängen in derselben Längeneinheit angegeben sind.']],
math4_2_pythagoras:[['math3_8_pythagoras','math4_1_reelle_zahlen'],['Hypotenuse und Katheten im rechtwinkligen Dreieck zuordnen.','Eine fehlende Hypotenuse oder Kathete berechnen.','Den Satz auf eine Rechteckdiagonale anwenden und die Voraussetzungen prüfen.'],['Die Hypotenuse liegt gegenüber dem rechten Winkel. Mit dieser Zuordnung gilt a² + b² = c².','Gesuchte Kathete: a = √(c² − b²). Die Hypotenuse muss länger als jede Kathete sein.','Eine Rechteckdiagonale bildet mit zwei benachbarten Seiten ein rechtwinkliges Dreieck.']],
math4_5_aehnlichkeit:[['math3_7_aehnlichkeit','math2_6_prop_prozent'],['Entsprechende Längen mit einem Ähnlichkeitsfaktor vergrößern oder verkleinern.','Längenfaktor und Flächenfaktor unterscheiden.','Eine Höhe aus Schattenlängen bestimmen und die Modellbedingungen nennen.'],['Bei positivem Faktor k werden entsprechende Längen mit k multipliziert. Winkel bleiben gleich.','Flächeninhalte ähnlicher Figuren verändern sich mit k². Halbe Seitenlängen bedeuten ein Viertel der Fläche.','Für die Schattenmethode müssen senkrechte Objekte auf waagrechtem Boden zur selben Zeit unter gleicher Sonnenrichtung betrachtet werden.']]};
for(const[id,[prerequisites,learningGoals,summary]]of Object.entries(guides))Object.assign(d[id],{prerequisites,learningGoals,summary});
const q=(id,question,rows)=>({id,question,answers:rows.map(([text,correct,feedback])=>({text,correct,pts:correct?10:0,feedback}))});
const scale=d.math3_7_aehnlichkeit;
{const $=cheerio.load(scale.sections[1].content);$('p').filter((_,p)=>$(p).text().includes('Streiche 5 Nullen')).text('Zum Umrechnen von Zentimetern in Kilometer dividierst du durch 100 000. Das funktioniert auch ohne Endnullen: 250 000 cm : 100 000 = 2,5 km.');scale.sections[1].content=$('body').html();}
if(!scale.sections[0].content.includes('Entsprechende Winkel'))scale.sections[0].content+='<p>Entsprechende Winkel sind gleich groß; entsprechende Seitenlängen haben denselben positiven Vergrößerungsfaktor. Ähnliche Figuren dürfen auch gleich groß sein (Faktor 1). Einseitiges Strecken verändert dagegen meist die Form.</p>';
for(const s of d.math3_8_pythagoras.sections){s.content=s.content.replaceAll('Glaube nicht nur, was du liest – beweise es selbst!','Untersuche diese Flächenbeziehung am Beispiel mit Seitenlängen 3 cm, 4 cm und 5 cm. Ein einzelnes Zahlenbeispiel ist noch kein allgemeiner Beweis.').replaceAll('🎉 Beweis erbracht!','🎉 Beispiel überprüft!');}
const puzzle=d.math3_8_pythagoras.sections.flatMap(s=>s.quizzes||[]).find(q=>q.id==='pyth_puzzle_1');puzzle.question='Welche Flächenbeziehung zeigt das Puzzle für das 3–4–5-Dreieck?';puzzle.answers=[{text:'9 cm² + 16 cm² = 25 cm².',correct:true,pts:10,feedback:'Die Flächen der beiden Kathetenquadrate ergeben zusammen die Fläche des Hypotenusenquadrats.'},{text:'3 cm + 4 cm = 5 cm.',correct:false,pts:0,feedback:'Es werden die Quadrate der Seitenlängen addiert. Die Seitenlängen selbst ergeben 3 + 4 = 7.'},{text:'Der Versuch beweist die Beziehung für jedes Dreieck.',correct:false,pts:0,feedback:'Das Puzzle zeigt ein bestimmtes rechtwinkliges Dreieck. Ein Zahlenbeispiel allein ist kein allgemeiner Beweis.'}];
const body=d.math3_9_koerper;if(!body.sections[1].content.includes('Alle Kantenlängen müssen'))body.sections[1].content+='<p>Alle Kantenlängen müssen in dieselbe Längeneinheit umgerechnet sein. 2 m · 3 m · 2 m = 12 m³. Oberfläche wird dagegen in Flächeneinheiten wie m² angegeben.</p>';
body.sections[0].quizzes[0].question='Die Fläche eines Papierblatts wird ohne Dicke modelliert. Ist dieses Modell zwei- oder dreidimensional?';body.sections[0].quizzes[0].answers[0].feedback='Das Flächenmodell ist zweidimensional. Ein echtes Blatt hat dennoch eine Dicke.';body.sections[0].quizzes[0].answers[1].feedback='Der reale Gegenstand ist dreidimensional. Gefragt ist das Modell seiner Fläche ohne Dicke.';
const p=d.math4_2_pythagoras,extension={id:'m42_apply',title:'Kathete und Diagonale berechnen',content:'<p>Wenn c = 13 cm und b = 5 cm gegeben sind, stellst du a² + b² = c² um: a² = 13² − 5² = 169 − 25 = 144. Daher ist a = 12 cm. Probe: 12² + 5² = 13².</p><p>Eine Rechteckdiagonale bildet mit Länge und Breite ein rechtwinkliges Dreieck. Bei 6 cm und 8 cm ist die Diagonale √(6² + 8²) cm = √100 cm = 10 cm. Prüfe vor dem Rechnen den rechten Winkel und die Rolle der längsten Seite.</p>{{QUIZ_m42_leg}}{{QUIZ_m42_diagonal}}',quizzes:[q('m42_leg','Ein rechtwinkliges Dreieck hat Hypotenuse 13 cm und eine Kathete 5 cm. Wie lang ist die andere Kathete?',[['12 cm',true,'√(13² − 5²) = √144 = 12.'],['18 cm',false,'Die fehlende Kathete muss kürzer als die Hypotenuse 13 cm sein. Seitenlängen werden hier nicht einfach addiert.'],['8 cm',false,'Du musst die Quadrate subtrahieren und danach die Wurzel ziehen, nicht 13 − 5 rechnen.']]),q('m42_diagonal','Wie lang ist die Diagonale eines Rechtecks mit 6 cm und 8 cm Seitenlänge?',[['10 cm',true,'√(6² + 8²) = √100 = 10.'],['14 cm',false,'14 cm ist die Summe der Seitenlängen, nicht die Diagonale.'],['100 cm',false,'100 cm² ist das Quadrat der Diagonalenlänge. Ziehe noch die Wurzel.']])]};p.sections=p.sections.filter(s=>s.id!==extension.id);p.sections.push(extension);
const a=d.math4_5_aehnlichkeit;a.sections[1].content='<p>Ein senkrechter 2 m langer Stab wirft einen 3 m langen Schatten. Ein senkrechter Baum wirft zur selben Zeit auf demselben waagrechten Boden einen 9 m langen Schatten. Die Lichtstrahlen sind näherungsweise parallel. Dadurch entstehen ähnliche rechtwinklige Dreiecke.</p><p>Der Faktor ist 9 : 3 = 3. Die Baumhöhe ist deshalb 2 m · 3 = 6 m. Bei geneigtem Boden oder unterschiedlichen Sonnenständen ist dieses einfache Modell nicht direkt anwendbar.</p>{{QUIZ_m45_q2}}';a.sections[1].quizzes[0].question='Unter diesen Bedingungen: Ein 2 m langer Stab hat 3 m Schatten, der Baum 9 m Schatten. Wie hoch ist der Baum?';a.sections[1].quizzes[0].answers[0].feedback='Die Schattenlänge wird verdreifacht. Wegen der ähnlichen Dreiecke gilt das auch für die Höhe: 2 m · 3 = 6 m.';a.sections[1].quizzes[0].answers[1].feedback='Schattenlänge und Höhe sind hier nicht gleich. Das Verhältnis Höhe : Schatten ist 2 : 3.';
const area={id:'m45_area',title:'Längen und Flächen beim Skalieren',content:'<p>Ein Rechteck ist 2 cm breit und 3 cm hoch, sein Flächeninhalt beträgt 6 cm². Bei Faktor 2 entstehen Seitenlängen 4 cm und 6 cm. Die Fläche beträgt nun 24 cm², also das Vierfache.</p><p>Allgemein werden Längen mit k, Flächen mit k² multipliziert. Bei k = 0,5 halbieren sich die Seitenlängen; die Fläche wird ein Viertel so groß. „Halb so groß“ ist ohne Angabe von Länge oder Fläche deshalb ungenau.</p>{{QUIZ_m45_area}}',quizzes:[q('m45_area','Alle Seitenlängen einer Figur werden verdoppelt. Wie verändert sich ihr Flächeninhalt?',[['Er wird viermal so groß.',true,'Der Flächenfaktor ist k² = 2² = 4.'],['Er wird doppelt so groß.',false,'Der Faktor 2 gilt für die Längen. Bei der Fläche wirken zwei Längenrichtungen.'],['Er bleibt gleich.',false,'Beim Vergrößern in beiden Richtungen wächst auch der Flächeninhalt.']])]};a.sections=a.sections.filter(s=>s.id!==area.id);a.sections.push(area);a.diplom.questions[0].answers[0].text='Alle Seitenlängen werden halbiert.';a.diplom.questions[0].answers[0].feedback='k = 0,5 multipliziert jede Länge mit einer Hälfte. Die Fläche wird dabei geviertelt.';
fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');
