const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..');
const lab=`<div class="interactive-zone" data-area-lab><h3>Flächenlabor</h3><p>Vermute zuerst, was sich beim Verdoppeln einer Länge ändert. Verändere dann die Werte. Die rote gestrichelte Strecke ist die senkrechte Höhe; sie kann auch auf der Verlängerung der Grundseite stehen. Alle Längen werden in Zentimetern eingegeben.</p><label>Figur <select data-shape><option value="rectangle">Rechteck</option><option value="triangle">Dreieck</option><option value="parallelogram">Parallelogramm</option><option value="trapezoid">Trapez</option></select></label><label>Grundseite b: <output data-value="b">6</output> cm<input data-base data-dimension="b" type="range" min="1" max="10" value="6"></label><label>Senkrechte Höhe h: <output data-value="h">4</output> cm<input data-height data-dimension="h" type="range" min="1" max="10" value="4"></label><label>Zweite parallele Seite a: <output data-value="a">3</output> cm<input data-top data-dimension="a" type="range" min="1" max="10" value="3"></label><svg viewBox="0 0 400 280" role="img" aria-label="Veränderbare ebene Figur"><line x1="40" x2="350" y1="240" y2="240" stroke="#64748b" stroke-dasharray="3 3"/><polygon fill="#bfdbfe" stroke="#1e3a8a" stroke-width="2"/><line data-height-line stroke="#b91c1c" stroke-width="2" stroke-dasharray="5 3"/><text data-height-label fill="#991b1b" font-size="13"/><text data-base-label y="264" text-anchor="middle" fill="#111827" font-size="13"/><text data-top-label x="50" fill="#111827" font-size="13"/></svg><p data-status role="status" aria-live="polite"></p><p>Vergleiche Dreieck und Parallelogramm mit b = 6 cm und h = 4 cm. Warum ist der Dreiecksinhalt halb so groß? Zeichne eine zweite passende Dreieckshälfte dazu.</p></div>`;
const questions=[
['Welche Einheit passt zum Flächeninhalt?','cm².','cm.','cm³.','Flächen werden mit Einheitsquadraten verglichen.','Zentimeter allein misst eine Länge.','Kubikzentimeter misst ein Volumen.'],
['Ein Rechteck ist 6 cm lang und 4 cm breit. Wie groß ist seine Fläche?','24 cm².','20 cm².','10 cm².','6 · 4 = 24.','20 cm wäre hier der Umfang: 2 · (6 + 4).','6 + 4 addiert Seitenlängen, berechnet aber keine Fläche.'],
['Ein Dreieck hat b = 6 cm und h = 4 cm. Wie groß ist A?','12 cm².','24 cm².','10 cm².','6 · 4 / 2 = 12.','Das wäre der Inhalt eines Parallelogramms mit derselben Grundseite und Höhe.','Addieren der Längen ist hier keine Flächenformel.'],
['Welche Länge gehört als h in A = b · h beim Parallelogramm?','Der senkrechte Abstand zwischen den parallelen Grundseiten.','Immer die schräge Seitenlänge.','Der gesamte Umfang.','Die Höhe steht senkrecht auf der Grundseite oder ihrer Verlängerung.','Die schräge Seite ist nur in einem besonderen Fall zugleich die Höhe.','Der Umfang ist eine Summe von Randlängen.'],
['Ein Trapez hat a = 3 cm, b = 7 cm und h = 4 cm. Wie groß ist A?','20 cm².','40 cm².','84 cm².','(3 + 7) · 4 / 2 = 20.','Hier fehlt die Division durch 2.','Alle drei Längen zu multiplizieren ergibt nicht die Trapezfläche.'],
['Du verdoppelst nur die Höhe eines Dreiecks, die Grundseite bleibt gleich. Was geschieht mit A?','Der Flächeninhalt verdoppelt sich.','Der Flächeninhalt vervierfacht sich.','Der Flächeninhalt bleibt gleich.','In b · h / 2 wird ein Faktor verdoppelt.','Vervierfachung entsteht, wenn Grundseite und Höhe beide verdoppelt werden.','Die Höhe beeinflusst die Fläche.'],
['Wie viele cm² sind 1 m²?','10 000 cm².','100 cm².','1000 cm².','Ein Quadrat von 1 m Seitenlänge ist 100 cm · 100 cm groß.','Der Faktor 100 gilt für Längen; bei Flächen wirken zwei Richtungen.','Der Flächenfaktor ist 100 · 100.'],
['Eine L-förmige Fläche besteht ohne Überlappung aus Rechtecken mit 12 m² und 8 m². Wie groß ist sie?','20 m².','96 m².','4 m².','Nicht überlappende Teilflächen werden addiert.','Die Teilflächen werden nicht miteinander multipliziert.','Subtraktion wäre nur bei einem ausgeschnittenen Teil passend.']
].map((q,i)=>({id:'area_figure_q'+i,question:q[0],answers:[1,2,3].map(j=>({text:q[j],correct:j===1,pts:0,feedback:q[j+3]}))}));
const texts=[
['Fläche und Umfang unterscheiden','Der Umfang beschreibt den Rand einer Figur und wird in Längeneinheiten angegeben. Der Flächeninhalt beschreibt, wie viel Ebene die Figur bedeckt. Ein Quadrat mit 1 cm Seitenlänge ist 1 cm² groß. Ein Rechteck mit Seitenlängen b und h enthält b · h solcher Einheitsquadrate, wenn beide Längen in Zentimetern angegeben sind. Beispiel: 6 cm · 4 cm = 24 cm². Sein Umfang ist dagegen 2 · (6 cm + 4 cm) = 20 cm.'],
['Dreieck und Parallelogramm verstehen','Ein Parallelogramm lässt sich durch Abschneiden und Ansetzen eines Randdreiecks zu einem flächengleichen Rechteck ergänzen beziehungsweise umlegen. Seine Fläche ist A = b · h. Dabei ist h der senkrechte Abstand zwischen den parallelen Seiten, nicht die schräge Seitenlänge. Zwei gleiche Dreiecke lassen sich zu einem Parallelogramm zusammensetzen. Deshalb gilt für ein Dreieck A = b · h / 2. Zeichne beide Zerlegungen auf kariertem Papier.'],
['Trapeze und zusammengesetzte Figuren','Ein Trapez hat ein Paar paralleler Seiten mit Längen a und b. Der senkrechte Abstand ist h. Zwei gleiche Trapeze lassen sich zu einem Parallelogramm mit Grundseite a + b und Höhe h zusammensetzen. Ein Trapez hat daher A = (a + b) · h / 2. Zerlege kompliziertere Figuren in bekannte Teilflächen. Addiere nur nicht überlappende Teile; bei einer ausgeschnittenen Ecke kannst du ihre Fläche von der Gesamtfläche abziehen.'],
['Einheiten und Ergebnisse prüfen','Rechne vor dem Einsetzen in eine Flächenformel alle Längen in dieselbe Einheit um. Weil 1 m = 100 cm gilt, enthält 1 m² genau 100 · 100 = 10 000 cm². Bei einer Vergrößerung mit Faktor 2 in beiden Richtungen vervierfacht sich die Fläche. Prüfe Ergebnisse durch eine Skizze und eine Abschätzung: Die Dreiecksfläche muss bei gleicher Grundseite und Höhe halb so groß wie die entsprechende Parallelogrammfläche sein.']
];
const chapter={title:'📐 Flächeninhalte ebener Figuren',subtitle:'Flächen durch Zerlegen, Ergänzen und Rechnen bestimmen.',contentLanguage:'de',script:false,learningGoals:['Flächeninhalt und Umfang unterscheiden und passende Einheiten verwenden.','Flächen von Rechteck, Dreieck, Parallelogramm und Trapez berechnen.','Zusammengesetzte Flächen zerlegen und Ergebnisse prüfen.'],prerequisites:['math1_5_geo_grundbegriffe','math1_10_groessen'],summary:['Rechteck und Parallelogramm: A = b · h; h ist die senkrechte Höhe.','Dreieck: A = b · h / 2. Trapez: A = (a + b) · h / 2 für die parallelen Seiten a und b.','Flächen addieren oder abziehen setzt eine passende Zerlegung voraus; 1 m² = 10 000 cm².'],sections:texts.map(([title,text],i)=>({id:'section'+i,title:(i+1)+'. '+title,content:'<p>'+text+'</p>'+(i===1?lab:'')+questions.slice(i*2,i*2+2).map(q=>'{{QUIZ_'+q.id+'}}').join(''),quizzes:questions.slice(i*2,i*2+2)})),workshop:{title:'5. Einen Grundriss berechnen',navLabel:'Flächenwerkstatt',instruction:'Ordne die Formeln zu und löse anschließend die Grundrissaufgabe.',categories:['b · h','b · h / 2','(a + b) · h / 2'],items:[{text:'Parallelogramm mit Grundseite b und senkrechter Höhe h.',answer:'b · h',feedback:'Umlegen einer Ecke führt zu einem flächengleichen Rechteck.'},{text:'Dreieck mit Grundseite b und passender Höhe h.',answer:'b · h / 2',feedback:'Zwei passende Dreieckshälften ergeben ein Parallelogramm.'},{text:'Trapez mit parallelen Seiten a und b und Höhe h.',answer:'(a + b) · h / 2',feedback:'Zwei gleiche Trapeze ergeben ein Parallelogramm mit Grundseite a + b.'}],writing:'Ein fiktiver Raum hat einen rechteckigen Grundriss von 6 m × 4 m. An einer Ecke fehlt ein rechteckiger Teil von 2 m × 1 m. Zeichne eine beschriftete Skizze und berechne die verbleibende Bodenfläche auf zwei Wegen. Erkläre, warum beide Wege dasselbe ergeben.',rubric:['Alle Längen stehen in derselben Einheit.','Meine Teilflächen überlappen nicht.','Ich gebe das Ergebnis in m² an und prüfe es mit einem zweiten Weg.'],model:'Weg 1: 6 · 4 − 2 · 1 = 24 − 2 = 22 m². Weg 2: In ein Rechteck 6 m × 3 m und ein Rechteck 4 m × 1 m zerlegen: 18 + 4 = 22 m². Beide erfassen dieselbe Fläche ohne die ausgeschnittene Ecke.'}};
const file=path.join(root,'lang/de.json'),data=JSON.parse(fs.readFileSync(file,'utf8'));data.math3_4_flaechensatz=chapter;fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');console.log('Replaced misplaced duplicate Pythagoras topic with area chapter, 8 questions and geometric lab.');
// Old translations describe the wrong topic too. Use the explicit German fallback
// until a translation of the replacement exists; preserve future corrected versions.
for(const name of fs.readdirSync(path.join(root,'lang'))){if(name==='de.json'||!name.endsWith('.json'))continue;const target=path.join(root,'lang',name),translated=JSON.parse(fs.readFileSync(target,'utf8')),old=translated.math3_4_flaechensatz;if(old?.sections?.some(s=>s.quizzes?.some(q=>q.id==='m34_q1'))){delete translated.math3_4_flaechensatz;fs.writeFileSync(target,JSON.stringify(translated,null,2)+'\n');console.log(name+': removed wrong-topic entry; explicit German area chapter fallback.');}}
