'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),id='bio_3_atmung_energie';
// Keys and numerical examples independent of the chapter's flags and workshop implementation.
const keys={bio_3_atmung_s1:[1,0],bio_3_atmung_d1:[2,0],bio_3_atmung_d2:[0,0],bio_3_atmung_s2:[0,1],bio_3_atmung_transport:[1,1],bio_3_atmung_s3:[0,2],bio_3_atmung_d3:[1,2],bio_3_atmung_rates:[2,2],bio_3_atmung_s4:[1,3],bio_3_atmung_help:[0,3]};
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-respiration-lab]'),n=zone.querySelector('input'),t=zone.querySelector('select'),out=zone.querySelector('[data-respiration-output]'),calc=zone.querySelector('[data-respiration-calculate]'),reset=zone.querySelector('[data-respiration-reset]'),storage=JSON.stringify(w.localStorage);
 let cases=0;for(const [count,seconds,rate,step]of [[8,30,16,2],[13,30,26,2],[9,30,18,2],[16,60,16,1],[4,15,16,4],[5,15,20,4],[9,30,18,2],[17,60,17,1],[0,15,0,4],[120,15,480,4],[120,30,240,2],[120,60,120,1]]){
  n.value=String(count);n.dispatchEvent(new w.Event('input'));t.value=String(seconds);t.dispatchEvent(new w.Event('change'));assert.equal(out.querySelector('[data-respiration-rate]'),null);calc.click();assert.equal(out.querySelector('[data-respiration-rate]').dataset.respirationRate,String(rate));assert.equal(out.querySelector('[data-respiration-difference]').dataset.respirationDifference,String(step));assert.match(out.textContent,/Atemtiefe/);cases++;
 }
 for(const [i,[count,seconds,rate]]of [[8,30,16],[13,30,26],[9,30,18],[16,60,16]].entries()){zone.querySelector(`[data-respiration-preset="${i}"]`).click();assert.equal(n.value,String(count));assert.equal(t.value,String(seconds));assert.equal(out.querySelector('[data-respiration-rate]'),null);calc.click();assert.equal(out.querySelector('[data-respiration-rate]').dataset.respirationRate,String(rate));}
 for(const value of ['',-1,121,1.5,'Infinity','text']){n.value=String(value);n.dispatchEvent(new w.Event('input'));calc.click();assert.match(out.textContent,/ganze Anzahl/);assert.equal(n.getAttribute('aria-invalid'),'true');assert.equal(out.querySelector('[data-respiration-rate]'),null);}
 n.value='8';n.dispatchEvent(new w.Event('input'));assert.equal(n.hasAttribute('aria-invalid'),false);t.value='';calc.click();assert.match(out.textContent,/Messdauer/);reset.click();assert.equal(n.value,'8');assert.equal(t.value,'30');assert.equal(out.textContent,'');assert.equal(d.activeElement,n);assert.equal(JSON.stringify(w.localStorage),storage);
 assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));
 for(const [i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('.respiration-route svg[data-worksheet-static]').length,1);assert.equal(d.querySelectorAll('.respiration-animals .respiration-card').length,3);assert.equal(d.querySelectorAll('.respiration-cases .respiration-card').length,3);assert.equal(d.querySelectorAll('[data-respiration-solution]').length,4);assert.equal(d.querySelectorAll('img').length,0);
 assert.deepEqual([...d.querySelectorAll('.respiration-data tbody tr')].map(r=>[...r.querySelectorAll('td')].map(e=>Number(e.textContent))),[[8,30],[13,30],[9,30],[16,60]]);assert.ok(data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).every(q=>q.answers.every(a=>a.pts===0)));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-respiration-paper]').length,1);assert.equal(pd.querySelectorAll('.respiration-route svg').length,1);assert.equal(pd.querySelectorAll('.respiration-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('.respiration-data tbody tr').length,4);assert.equal(pd.querySelectorAll('#ws-solutions [data-respiration-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-respiration-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material input,#ws-biology-material select').length,0);paper.window.close();
 console.log(`PASS: ${cases} independent numerical examples, four presets, invalid counts/time, reset/focus/storage, 30 quiz answers, 12 tasks, 16 terms, route diagram and complete paper data with separate solutions.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
