'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{JSDOM}=require('jsdom'),read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math3_9_koerper';
const keys={m39_q1:0,m39_q2:0,m39_q3:0,m39_prism_volume:0,m39_prism_surface:0,m39_pyramid_volume:0,m39_pyramid_height:0,m39_dip1:0,m39_dip2:0,m39_oblique_depth:1,m39_mass_prism:1,m39_density_inverse:0,m39_mass_hollow:2,m39_mass_compare:0};
const near=(a,b)=>assert.ok(Math.abs(a-b)<0.0001,`${a} != ${b}`);
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','language-workshop','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();
 const lab=d.querySelector('[data-solid-mass]'),body=lab.querySelector('#solid-mass-body'),height=lab.querySelector('#solid-mass-height'),material=lab.querySelector('#solid-mass-material'),input=lab.querySelector('input'),result=lab.querySelector('[data-solid-mass-result]'),check=lab.querySelector('[data-solid-mass-check]'),storage=JSON.stringify(w.localStorage),change=el=>el.dispatchEvent(new w.Event('change'));let states=0;
 for(const kind of ['box','tri','pyramid'])for(const h of [3,6,9])for(const density of [0.5,1.2,2.7]){
  body.value=kind;height.value=String(h);material.value=String(density);change(body);assert.equal(input.value,'');assert.equal(result.textContent,'');
  // Independent geometric volumes: rectangular prism 12h, right-triangular prism 6h, square pyramid 16h/3.
  const volume=({box:12,tri:6,pyramid:16/3})[kind]*h,mass=volume*density;
  assert.match(lab.querySelector('[data-solid-mass-givens]').textContent,new RegExp('h = '+h+' cm'));assert.ok(lab.textContent.includes(density.toLocaleString('de-AT')+' g/cm³'));
  input.value=String(Number(mass.toFixed(6))).replace('.',',');check.click();assert.equal(result.dataset.correct,'true');assert.ok(result.textContent.includes(mass.toLocaleString('de-AT')+' g'));assert.ok(result.textContent.includes(volume.toLocaleString('de-AT')+' cm³'));assert.equal(d.activeElement,result);
  input.value=String(mass+1);check.click();assert.equal(result.dataset.correct,'false');input.dispatchEvent(new w.Event('input'));assert.equal(result.textContent,'');states++;
 }
 for(const text of ['','0','-1','43g','1e2','2,4.5','Infinity']){input.value=text;check.click();assert.equal(input.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,input);assert.equal(result.dataset.correct,undefined);}
 lab.querySelector('[data-solid-mass-reset]').click();assert.equal(body.value,'box');assert.equal(height.value,'6');assert.equal(material.value,'1.2');assert.equal(input.value,'');assert.equal(result.textContent,'');assert.equal(d.activeElement,body);input.value='86.4';input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter'}));assert.equal(result.dataset.correct,'true');w.topicInit();assert.equal(input.value,'86.4');assert.equal(JSON.stringify(w.localStorage),storage);
 const phone=d.getElementById('ans_m39_1');phone.value='3D';phone.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter'}));assert.match(d.getElementById('res_m39_1').textContent,/^Richtig/);phone.dispatchEvent(new w.Event('input'));assert.equal(d.getElementById('res_m39_1').textContent,'');
 const prism=d.querySelector('[data-solid-sketch="prism"]'),front=prism.querySelector('polygon').getAttribute('points').split(' ').map(p=>p.split(',').map(Number)),side=prism.querySelectorAll('polygon')[1].getAttribute('points').split(' ').map(p=>p.split(',').map(Number));near(Math.hypot(front[1][0]-front[0][0],front[1][1]-front[0][1])/30,3);near(Math.hypot(front[2][0]-front[0][0],front[2][1]-front[0][1])/30,4);for(const [a,b]of [[side[1],side[2]],[side[0],side[3]]]){near(Math.hypot(b[0]-a[0],b[1]-a[1])/30,3);near(b[0]-a[0],a[1]-b[1]);}
 const pyramid=d.querySelector('[data-solid-sketch="pyramid"]'),pf=pyramid.querySelector('polygon').getAttribute('points').split(' ').map(p=>p.split(',').map(Number)),ps=pyramid.querySelectorAll('polygon')[1].getAttribute('points').split(' ').map(p=>p.split(',').map(Number)),foot=pyramid.querySelector('circle');near(Math.hypot(pf[1][0]-pf[0][0],pf[1][1]-pf[0][1])/25,6);near(Math.hypot(ps[1][0]-ps[0][0],ps[1][1]-ps[0][1])/25,3);near(+foot.getAttribute('cx'),(pf[0][0]+ps[1][0])/2);near(+foot.getAttribute('cy'),(pf[0][1]+ps[1][1])/2);near(+foot.getAttribute('cx'),pf[2][0]);near((+foot.getAttribute('cy')-pf[2][1])/25,6);
 assert.equal(d.querySelectorAll('[data-solid-extension-tasks] > li').length,6);assert.equal(w.chapterRevision(id),3);assert.equal(w.currentChapterResult(id,{contentRevision:2,lastPercent:100}).outdated,true);let answers=0;const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,14);
 for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let choice=0;choice<q.answers.length;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const saved=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(saved.lastPercent,choice===keys[q.id]?100:93);assert.deepEqual(saved.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));answers++;}}assert.equal(answers,39);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.solid-drawing svg').length,2);assert.equal(pd.querySelectorAll('.solid-extension-paper').length,1);assert.equal(pd.querySelectorAll('#ws-solutions [data-solid-extension-solution]').length,2);assert.equal(pd.querySelectorAll('[data-solid-extension-tasks] > li').length,6);assert.match(pd.querySelector('#ws-solutions').textContent,/145,8.*8 g/s);assert.equal(pd.querySelectorAll('[data-solid-mass] input').length,0);paper.window.close();
 console.log(`PASS: ${states} independent mass calculations, wrong/invalid/reset/keyboard/storage; prism and pyramid projections; ${answers} graded paths, revision and paper material.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
