const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{
const dom=new JSDOM('<div id="sections-container"></div>',{url:'https://example.test/topics/template.html?topic=math3_4_flaechensatz',runScripts:'outside-only'}),w=dom.window;await new Promise(resolve=>setImmediate(resolve));w.eval(read('js/chapter-revisions.js'));w.eval(read('js/renderer.js'));w.eval('globalPhysikScore=0');
const id='math3_4_flaechensatz',old={passed:true,bestPercent:100,lastPercent:100,reviewQuestionIds:['old'],lastAttemptAt:123};w.localStorage.setItem('sciverse_chapter_quiz_results',JSON.stringify({[id]:old,geo_1_karten_raeume:old}));assert.equal(w.chapterRevision('geo_1_karten_raeume'),0);assert.equal(w.getChapterQuizResult(id).passed,false);assert.equal(w.getChapterQuizResult('geo_1_karten_raeume').passed,true);
const questions=[{id:'new',question:'Fläche?',answers:[{text:'Richtig',correct:true,feedback:'Richtig gerechnet.'},{text:'Falsch',correct:false,feedback:'Rechne erneut.'}]}];w.currentChapterQuiz={topicId:id,topicTitle:'Flächen',questions};const host=w.document.getElementById('sections-container');host.innerHTML=w.renderChapterQuizPanel(id,{title:'Flächen'},questions);assert.equal(w.getChapterQuizResult(id).outdated,true);assert.match(w.renderChapterQuizCard(id,{title:'Flächen'},questions),/Kapitel überarbeitet/);
w.document.querySelector('input[value="1"]').checked=true;w.submitChapterQuiz();let r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.contentRevision,1);assert.equal(r.bestPercent,0);assert.equal(r.passed,false);assert.equal(r.previousVersions.length,1);assert.equal(r.previousVersions[0].bestPercent,100);
host.innerHTML=w.renderChapterQuizPanel(id,{title:'Flächen'},questions);w.document.querySelector('input[value="0"]').checked=true;w.submitChapterQuiz();r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.bestPercent,100);assert.equal(r.previousVersions.length,1);dom.window.close();
const hub=new JSDOM(read('topics/learning.html'),{url:'https://example.test/topics/learning.html?plan='+id,runScripts:'outside-only'}),h=hub.window;h.localStorage.setItem('sciverse_chapter_quiz_results',JSON.stringify({[id]:old}));h.fetch=async()=>({ok:true,json:async()=>JSON.parse(read('lang/de.json'))});for(const f of ['curriculum','chapter-revisions','learning'])h.eval(read('js/'+f+'.js'));await new Promise(resolve=>setImmediate(resolve));assert.match(h.document.getElementById('selected').textContent,/Kapitel überarbeitet/);assert.match(h.document.getElementById('plan-progress').textContent,/0 im letzten Kapitelcheck/);hub.window.close();
console.log('PASS: changed content invalidates current mastery without deleting old records, unchanged chapters preserve status, new attempt starts fresh best and archives previous version once; study plan excludes stale result.');
})().catch(error=>{console.error(error);process.exitCode=1;});
