const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const source=fs.readFileSync(path.join(__dirname,'../js/language-workshop.js'),'utf8');
const spec={items:[],categories:[],writing:'Task',rubric:['Criterion A','Criterion B'],model:'Example'};
function setup(language,record,blocked=false,rubric=spec.rubric){const dom=new JSDOM('<div id="sections-container"></div>',{url:'https://example.test/',runScripts:'outside-only'}),w=dom.window;if(record!==undefined)w.localStorage.setItem('sciverse_draft_test_reflection',record);if(blocked)Object.defineProperty(w,'localStorage',{get(){throw new Error('denied');}});w.eval(source);w.buildLanguageWorkshop({contentLanguage:language,workshop:{...spec,rubric}},'test');return dom;}
for(const language of ['de','en','ar','uk','sr','tr']){
 let dom=setup(language),w=dom.window,d=w.document;d.querySelector('#workshop-draft').value='Independent draft';
 const note=d.querySelector('#rubric-note-0'),check=d.querySelector('#rubric-0');note.value='My evidence <script> is plain text';note.dispatchEvent(new w.Event('input'));check.checked=true;check.dispatchEvent(new w.Event('change'));
 const record=w.localStorage.getItem('sciverse_draft_test_reflection');assert.equal(JSON.parse(record)[0].checked,true);assert.equal(d.querySelector('#workshop-draft').value,'Independent draft');assert.ok(d.getElementById(note.getAttribute('aria-describedby')));assert.ok(d.querySelector('label[for="rubric-note-0"]'));dom.window.close();
 dom=setup(language,record,false,['Criterion B','Criterion A','New criterion']);d=dom.window.document;assert.equal(d.querySelector('#rubric-0').checked,false);assert.equal(d.querySelector('#rubric-1').checked,true);assert.equal(d.querySelector('#rubric-note-1').value,'My evidence <script> is plain text');assert.equal(d.querySelector('#rubric-note-2').value,'');assert.equal(d.querySelectorAll('script').length,0);dom.window.close();
 dom=setup(language,undefined,true);d=dom.window.document;d.querySelector('#rubric-note-0').value='Still editable';d.querySelector('#rubric-note-0').dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelector('#rubric-note-0').value,'Still editable');assert.ok(d.querySelector('fieldset [role="status"]').textContent.length>10);dom.window.close();
}
for(const invalid of ['not json','null','{}','[null,2,{"criterion":"Criterion A","note":12,"checked":"true"}]']){const dom=setup('de',invalid);assert.equal(dom.window.document.querySelector('#rubric-note-0').value,'');assert.equal(dom.window.document.querySelector('#rubric-0').checked,false);dom.window.close();}
console.log('PASS: reflection evidence and checkmarks persist in six languages, follow criterion text after reordering, preserve independent drafts, reject damaged records, and remain editable when storage is denied.');
