'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),data=JSON.parse(read('lang/de.json')),id='math2_2_brueche';
const keys={m22_expand:0,m22_reduce:0,m22_same_whole:1,m22_q1:0,m22_q2:0,m22_dip1:0,m22_sum:0,m22_difference:0,m22_common_units:2,m22_q3:0,m22_dip2:0,m22_product_model:1,m22_q4:0,m22_div_remainder:2,m22_div_zero:1,m22_rules_order:2,m22_rules_change:0,m22_rules_bounds:1};
const expected={multiply:[[3,8],[8,15],[3,10],[2,9],[1,2],[9,8],[9,4],[0,1],[3,4],[3,4],[5,6],[5,36],[25,36],[1,1],[0,1],[1,1]],divide:[[2,1],[6,1],[4,3],[2,3],[6,1],[2,1],[3,4],[1,2],[0,1],[3,2],[5,2],[7,4]]};
const gcd=(a,b)=>{while(b){const r=a%b;a=b;b=r;}return a;};
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();w.topicInit();const q=s=>d.querySelector(s),saved=JSON.stringify(w.localStorage);let cases=0,cellChecks=0;
 for(const kind of ['multiply','divide']){const host=q('[data-fraction-model="'+kind+'"]'),get=s=>host.querySelector(s),sel=get('[data-fraction-case]'),n=get('[data-fraction-n]'),den=get('[data-fraction-d]'),out=get('[data-fraction-status]');assert.equal(sel.options.length,expected[kind].length);
  for(let i=0;i<expected[kind].length;i++){const m=w.fractionOperationModel(kind,i),[a,b]=expected[kind][i];assert.equal(m.n,a);assert.equal(m.q,b);assert.equal(gcd(m.n,m.q),1);assert.equal(kind==='multiply'?m.a*m.c*m.q:m.a*m.d*m.q,m.n*(kind==='multiply'?m.b*m.d:m.b*m.c));sel.value=String(i);sel.dispatchEvent(new w.Event('change'));assert.equal(get('[data-fraction-view]').hidden,true);assert.equal(n.value,'');
   for(const factor of [1,2]){n.value=String(a*factor);den.value=String(b*factor);den.focus();den.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.match(out.textContent,/^Richtig:/);assert.equal(d.activeElement,den);}
   get('[data-fraction-show]').click();assert.equal(get('[data-fraction-view]').hidden,false);assert.ok(get('[data-fraction-view]').textContent.includes(a+'/'+b));
   if(kind==='multiply'){const cells=[...host.querySelectorAll('[data-area-cell]')],overlap=cells.filter(e=>e.dataset.areaOverlap==='true');assert.equal(overlap.length,m.a*m.c);assert.equal(cells.length,Math.max(1,Math.ceil(m.a/m.b))*Math.max(1,Math.ceil(m.c/m.d))*m.b*m.d);const area=overlap.reduce((sum,e)=>sum+Number(e.getAttribute('width'))*Number(e.getAttribute('height')),0);assert.ok(Math.abs(area/(120*120)-a/b)<1e-12);for(const cell of cells){const x=Number(cell.getAttribute('x')),y=Number(cell.getAttribute('y')),cw=Number(cell.getAttribute('width')),ch=Number(cell.getAttribute('height'));assert.equal(cell.dataset.areaOverlap==='true',x+cw/2<35+120*m.a/m.b&&y+ch/2<30+120*m.c/m.d);cellChecks++;}assert.equal(host.querySelectorAll('[data-area-whole]').length,Math.max(1,Math.ceil(m.a/m.b))*Math.max(1,Math.ceil(m.c/m.d)));}
   else{assert.equal(m.common*m.a,m.first*m.b);assert.equal(m.common*m.c,m.second*m.d);assert.equal(m.full*m.second+m.remainder,m.first);assert.ok(m.remainder>=0&&m.remainder<m.second);for(const row of [0,1,2])assert.equal(host.querySelectorAll('[data-division-row="'+row+'"][data-division-filled="true"]').length,row===1?m.second:m.first);assert.equal(host.querySelectorAll('[data-division-group]').length,Math.ceil(m.first/m.second));const leftoverLitres=(m.a/m.b)-m.full*(m.c/m.d);assert.ok(Math.abs(leftoverLitres-m.remainder/m.common)<1e-12);assert.ok(Math.abs((m.full+m.remainder/m.second)-a/b)<1e-12);}
   cases++;
  }
  for(const [a,b]of [['',''],['1','0'],['-1','2'],['1.0','2'],['1e0','2'],['0x1','2'],['1','-2'],['1000000','2']]){n.value=a;den.value=b;get('[data-fraction-check]').click();assert.match(out.textContent,/^Gib einen/);}
  get('[data-fraction-reset]').click();assert.equal(sel.value,kind==='divide'?'2':'0');assert.equal(d.activeElement,sel);assert.equal(get('[data-fraction-view]').hidden,true);n.value='9';den.value='1';get('[data-fraction-check]').click();assert.match(out.textContent,/^Noch nicht/);n.dispatchEvent(new w.Event('input'));assert.equal(out.textContent,'');
 }
 const staticShares={'fraction-equivalent-title':[2/3,2/3],'fraction-add-title':[3/8,2/8,5/8],'fraction-common-title':[1/2,1/3,5/6],'fraction-division-title':[2/3,1/2]};
 for(const [title,shares]of Object.entries(staticShares)){const svg=d.getElementById(title).parentElement,rows=new Map();for(const rect of svg.querySelectorAll('rect')){const y=rect.getAttribute('y'),row=rows.get(y)||{total:0,filled:0},area=Number(rect.getAttribute('width'))*Number(rect.getAttribute('height'));row.total+=area;if(rect.getAttribute('fill')==='#2563eb')row.filled+=area;rows.set(y,row);}assert.equal(rows.size,shares.length);[...rows.values()].forEach((row,i)=>assert.ok(Math.abs(row.filled/row.total-shares[i])<1e-12));}
 const areaRects=[...d.getElementById('fraction-area-title').parentElement.querySelectorAll('rect')],areaOf=r=>Number(r.getAttribute('width'))*Number(r.getAttribute('height'));assert.equal(areaRects.filter(r=>r.getAttribute('fill')==='#2563eb').reduce((s,r)=>s+areaOf(r),0)/areaRects.reduce((s,r)=>s+areaOf(r),0),3/8);
 assert.equal(JSON.stringify(w.localStorage),saved);for(const kind of ['multiply','divide','unknown'])for(const index of [-1,1.5,100,NaN,'1'])assert.equal(w.fractionOperationModel(kind,index),null);
 for(const [ids,feedback,values]of [[['bruch_z'],'bruch_z_feedback',['3']],[['bruch_common_n','bruch_common_d'],'bruch_common_feedback',['6','8']],[['bruch_m1','bruch_m2'],'bruch_m_feedback',['6','16']],[['bruch_d1','bruch_d2'],'bruch_d_feedback',['8','6']]]){const fields=ids.map(id=>d.getElementById(id));fields.forEach((e,i)=>e.value=values[i]);fields[0].focus();fields[0].dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.match(d.getElementById(feedback).innerText,/Richtig|Super/);fields[0].dispatchEvent(new w.Event('input'));assert.equal(d.getElementById(feedback).innerText,'');fields[0].value='3e0';fields[0].closest('.interactive-zone').querySelector('button').click();assert.ok(!/Richtig|Super/.test(d.getElementById(feedback).innerText));}
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,18);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;for(const [i,item]of qs.entries()){assert.equal(item.sectionIndex,Math.floor(i/3));for(let a=0;a<3;a++){assert.equal(item.answers[a].correct,a===keys[item.id]);qs.forEach((q,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?a:keys[q.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[item.id]?100:94);assert.deepEqual(result.reviewQuestionIds,a===keys[item.id]?[]:[item.id]);assert.equal(result.contentRevision,2);assert.ok(q('#chapter-quiz-result').textContent.includes(item.answers[a].feedback));paths++;}}
 assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('#ws-math-material article').length,6);assert.equal(pd.querySelectorAll('[data-fraction-tasks]>li').length,18);assert.equal(pd.querySelectorAll('[data-fraction-model-paper],[data-fraction-quick-paper]').length,6);assert.equal(pd.querySelectorAll('#ws-math-material svg').length,5);assert.equal(pd.querySelectorAll('#ws-math-material input,#ws-math-material button,#ws-math-material select').length,0);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,6);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,18);
 function verify(host,solution){const tasks=host.querySelectorAll('[data-fraction-generated]'),answers=solution.querySelectorAll('[data-fraction-answer]');assert.equal(tasks.length,12);assert.equal(answers.length,12);for(let i=0;i<12;i++){const t=tasks[i],a=Number(t.dataset.a),b=Number(t.dataset.b),c=Number(t.dataset.c),dd=Number(t.dataset.d),kind=t.dataset.fractionGenerated,[n,q]=answers[i].dataset.fractionAnswer.split('/').map(Number);const actual=kind==='add'?a/b+c/dd:kind==='subtract'?a/b-c/dd:kind==='multiply'?a/b*c/dd:(a/b)/(c/dd);assert.ok(Math.abs(n/q-actual)<1e-12);assert.equal(gcd(n,q),1);assert.ok(n>=0&&q>0);assert.ok(answers[i].textContent.startsWith('A'+(i+1)+'.'));}}
 verify(pd,pd.getElementById('ws-solutions'));for(const seed of [0,.5,.99999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify(host,host.querySelector('template').content);}const before=Array.from(pd.querySelectorAll('[data-fraction-generated]'),e=>e.textContent);for(const checked of [true,false,true]){pd.getElementById('ws-include-solutions').checked=checked;pd.getElementById('ws-include-solutions').dispatchEvent(new pw.Event('change'));assert.deepEqual(Array.from(pd.querySelectorAll('[data-fraction-generated]'),e=>e.textContent),before);}paper.window.close();
 console.log('PASS: fraction models: '+cases+' exact models, '+cellChecks+' geometric cells, all '+paths+' chapter answer paths, equivalent/invalid inputs, Enter/reset/storage/revision; six-section worksheet, five figures, six alternatives/solutions, 48 generated solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
