const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='bio_1_skelett_bewegung';
// Independent expectations: keep them separate from authored answer flags and model option attributes.
const correct={bio_skelett_s1:0,bio_skelett_s2a:0,bio_skelett_s3a:0,bio_skelett_s2:0,bio_skelett_s3:2,bio_skelett_s6:2,bio_skelett_d1:1,bio_skelett_d2:0,bio_skelett_d3:0,bio_skelett_d4:1,bio_skelett_d5:0,bio_skelett_d6:0,bio_skelett_absenken:2,bio_skelett_modell:1};
const sections={bio_skelett_s1:0,bio_skelett_s2a:1,bio_skelett_s3a:2,bio_skelett_s2:3,bio_skelett_s3:4,bio_skelett_s6:5,bio_skelett_d1:0,bio_skelett_d2:3,bio_skelett_d3:2,bio_skelett_d4:4,bio_skelett_d5:1,bio_skelett_d6:5,bio_skelett_absenken:3,bio_skelett_modell:3};
const movements={lift:{angles:[150,90],answer:'shorter',term:'kürzer'},hold:{angles:[90,90],answer:'same',term:'gleich lang'},lower:{angles:[90,150],answer:'longer',term:'länger'}};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')),texts=doc=>[...doc.querySelectorAll('.bio-training-card')].map(e=>e.textContent);assert.equal(texts(d).length,18);assert.deepEqual(texts(d),texts(authored.window.document));assert.equal(d.querySelectorAll('.bio-training-direct-text').length,0);authored.window.close();
 const z=d.querySelector('[data-core-experiment="muscle-actions"]'),action=z.querySelector('[data-muscle-action]'),prediction=z.querySelector('[data-muscle-prediction]'),result=z.querySelector('[data-muscle-result]'),check=z.querySelector('[data-muscle-check]'),reset=z.querySelector('[data-muscle-reset]'),before=JSON.stringify(w.localStorage);assert.equal(d.getElementById(prediction.getAttribute('aria-describedby')),result);let comparisons=0;
 for(const [key,state]of Object.entries(movements)){
  action.value=key;action.dispatchEvent(new w.Event('change'));assert.equal(prediction.value,'');assert.equal(result.textContent,'Noch nicht geprüft.');check.click();assert.equal(z.dataset.muscleState,'open');assert.match(result.textContent,/Wähle zuerst/);
  for(const [i,part]of ['start','end'].entries()){
   const line=z.querySelector('[data-muscle-'+part+']'),x=Number(line.getAttribute('x2')),y=Number(line.getAttribute('y2'));assert.ok(Math.abs(Math.hypot(x-105,y-150)-105)<1e-8);const measured=Math.acos((150-y)/105)*180/Math.PI;assert.ok(Math.abs(measured-state.angles[i])<1e-8);
  }
  assert.ok(z.querySelector('[data-muscle-diagram]').getAttribute('aria-label').includes('von '+state.angles[0]+' auf '+state.angles[1]));
  for(const answer of ['shorter','same','longer']){prediction.value=answer;prediction.dispatchEvent(new w.Event('change'));assert.equal(z.dataset.muscleState,undefined);assert.equal(result.textContent,'Noch nicht geprüft.');check.click();assert.equal(z.dataset.muscleState,answer===state.answer?'correct':'review');assert.ok(result.textContent.includes(state.term));assert.match(result.textContent,/Zug/);comparisons++;}
 }
 assert.equal(comparisons,9);assert.equal(JSON.stringify(w.localStorage),before);w.enhanceCoreLearning(data[id],id,'de');assert.equal(action.value,'lower');reset.click();assert.equal(action.value,'lift');assert.equal(prediction.value,'');assert.equal(z.dataset.muscleState,undefined);assert.equal(d.activeElement,action);assert.equal(JSON.stringify(w.localStorage),before);
 const questions=w.currentChapterQuiz.questions;assert.equal(questions.length,14);assert.deepEqual(Array.from(questions,q=>q.id).sort(),Object.keys(correct).sort());assert.equal(data[id].diplom.questions.length,0);let paths=0;
 for(const [i,q]of questions.entries()){
  assert.equal(q.sectionIndex,sections[q.id]);
  for(let choice=0;choice<3;choice++){
   questions.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?choice:correct[item.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,choice===correct[q.id]?100:93);assert.deepEqual(result.reviewQuestionIds,choice===correct[q.id]?[]:[q.id]);assert.equal(result.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;
  }
 }
 assert.equal(paths,42);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).passed,true);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pw.document.getElementById('ws-biology-material'),solutions=pw.document.getElementById('ws-solutions');assert.equal(material.querySelectorAll('article').length,6);assert.equal(material.querySelectorAll('.bio-training-card').length,18);assert.equal(material.querySelectorAll('.ws-glossary-entry').length,31);assert.equal(material.querySelectorAll('[data-muscle-protocol] tbody tr').length,3);assert.equal(material.querySelectorAll('[data-muscle-paper] svg[data-worksheet-static]').length,1);assert.equal(material.querySelectorAll('select,button,[data-muscle-result],[data-muscle-diagram]').length,0);assert.equal(solutions.hidden,true);assert.ok(solutions.textContent.includes('Bewegungsprotokoll: Erklärung vergleichen'));assert.ok(solutions.textContent.includes('Beugemuskeln länger unter Zug'));assert.ok(!material.textContent.includes('Beugemuskeln länger unter Zug'));paper.window.close();
 console.log('PASS: skeleton movement: 42 independently keyed assessed paths, section/revision checks, 18 preserved tasks, 9 model predictions, independently measured angles and invariant bone lengths, empty/change/reset/focus/storage and paper protocol/diagram/separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
