'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_kohlenstoff_klima';
const keys={bio_4_klima_s1:[1,0],bio_4_klima_d1:[2,0],bio_4_klima_bilanz:[0,1],bio_4_klima_senke:[1,1],bio_4_klima_s2:[2,2],bio_4_klima_d2:[0,2],bio_4_klima_strahlung:[1,2],bio_4_klima_s3:[2,3],bio_4_klima_d3:[0,3],bio_4_klima_phaenologie:[1,3]};
// Independent complete stock trajectories, including the initial stock.
const cases=[['A','S',[100,104,108,112,116]],['A','W',[100,104,109,115,122]],['B','S',[100,104,106,106,104]],['B','W',[100,104,107,109,110]],['C','S',[100,100,100,100,100]],['C','W',[100,100,101,103,106]]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-carbon-lab]'),pathInput=zone.querySelector('[data-carbon-path]'),sink=zone.querySelector('[data-carbon-sink]'),periods=zone.querySelector('[data-carbon-periods]'),check=zone.querySelector('[data-carbon-check]'),reset=zone.querySelector('[data-carbon-reset]'),result=zone.querySelector('[data-carbon-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.invalid,undefined);};
 for(const[p,s,trajectory]of cases)for(let n=1;n<=4;n++){
  set(pathInput,p);set(sink,s);set(periods,String(n));check.click();assert.equal(d.activeElement,result);assert.equal(Number(result.querySelector('[data-carbon-final]').dataset.carbonFinal),trajectory[n]);
  const rows=[...result.querySelectorAll('tbody tr')].map(r=>[...r.children].map(e=>Number(e.dataset.carbonNumber)));assert.equal(rows.length,n);
  for(const[i,row]of rows.entries()){assert.equal(row[0],i+1);assert.equal(row[3],trajectory[i+1]-trajectory[i]);assert.equal(row[4],trajectory[i+1]);assert.equal(row[1]-row[2],row[3]);}
  const delta=trajectory[n]-trajectory[n-1];assert.equal(result.querySelector('[data-carbon-trend]').dataset.carbonTrend,delta>0?'up':delta<0?'down':'equal');
  const points=[...result.querySelectorAll('[data-carbon-stock]')];assert.deepEqual(points.map(e=>Number(e.dataset.carbonStock)),trajectory.slice(0,n+1));assert.deepEqual(points.map(e=>[Number(e.getAttribute('cx')),Number(e.getAttribute('cy'))]),trajectory.slice(0,n+1).map((v,i)=>[48+i*50,160-(v-98)*5]));assert.equal(result.querySelector('[data-carbon-line]').getAttribute('points'),points.map(e=>e.getAttribute('cx')+','+e.getAttribute('cy')).join(' '));assert.match(result.textContent,/Ausschnitt von 98 bis 124 E/);assert.match(result.textContent,/keine CO₂- oder Temperaturprognose/);
  if(p==='B'&&s==='S'&&n===4)assert.match(result.textContent,/sinkt im letzten Schritt, liegt aber noch über dem Anfangswert/);
 }
 for(const[input,name]of [[pathInput,'path'],[sink,'sink'],[periods,'periods']]){reset.click();set(input,'');check.click();assert.equal(result.dataset.invalid,name);assert.equal(d.activeElement,input);}reset.click();assert.equal(pathInput.value,'A');assert.equal(sink.value,'S');assert.equal(periods.value,'1');assert.equal(result.textContent,'');assert.equal(d.activeElement,pathInput);assert.equal(JSON.stringify(w.localStorage),storage);
 const inputs=[...d.querySelectorAll('.carbon-inputs tbody tr')].map(r=>[...r.children].slice(1).map(e=>e.textContent));assert.deepEqual(inputs,[['10 E','10 E','10 E','10 E'],['10 E','8 E','6 E','4 E'],['6 E','6 E','6 E','6 E'],['6 E','6 E','6 E','6 E'],['6 E','5 E','4 E','3 E']]);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('[data-carbon-solution]').length,4);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].id,'bio_4_klima_extra_treibhauseffekt');assert.ok(practice[0].answers.every(a=>a.pts===0));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-carbon-paper]').length,1);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(pd.querySelectorAll('.carbon-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('#ws-solutions [data-carbon-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-carbon-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);assert.doesNotMatch(pd.body.textContent,/undefined/);for(const s of data[id].sources){assert.ok(s.title&&s.url.startsWith('https://'));assert.ok(pd.body.textContent.includes(s.title));}
 const solution=pd.querySelector('#ws-solutions [data-carbon-solution="1"]').textContent;for(const[p,s,trajectory]of cases)assert.ok(solution.includes(p+'/'+s+' '+trajectory.slice(1).join('/')+' E'));const phenology=pd.querySelector('#ws-solutions [data-carbon-solution="3"]').textContent;assert.match(phenology,/÷ 3 = 108/);assert.match(phenology,/÷ 3 = 102/);assert.match(phenology,/6 Tage früher/);assert.match(phenology,/Gruppen überlappen/);paper.window.close();
 console.log('PASS: 24 balance states, six independent stock trajectories, matching graph/table, invalid/reset/focus/storage, 30 quiz answers and complete paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
