const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),data=JSON.parse(read('lang/de.json')),id='elektromagnetismus';
// Expectations authored from the physical cases, not derived from answer.correct.
const keys={em_motor_commutator:1,em_motor_couple:0,em_motor_deadpoint:2,magnet_basis_1:0,magnet_basis_2:0,magnet_basis_3:0,em_d11:2,em_s1_q1:0,em_d1:1,em_d2:2,em_s2_q1:1,em_d3:0,em_d4:2,em_d5:1,em_d13:1,em_s_relay_q1:2,em_s3_q1:1,em_d6:2,em_d7:0,em_d14:0,em_s4_q1:0,em_d8:1,em_d9:2,em_d12:0,em_d15:1,em_induction_speed:2,em_induction_controls:0,em_s5_q1:0,em_trans_power:2,em_d10:1};
const sections=[['magnet_basis_1','magnet_basis_2','magnet_basis_3','em_d11'],['em_s1_q1','em_d1','em_d2'],['em_s2_q1','em_d3','em_d4','em_d5','em_d13'],['em_s_relay_q1'],['em_s3_q1','em_d6','em_d7','em_d14','em_motor_commutator','em_motor_couple','em_motor_deadpoint'],['em_s4_q1','em_d8','em_d9','em_d12','em_d15','em_induction_speed','em_induction_controls'],['em_s5_q1','em_trans_power','em_d10']];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/physik_bay6/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,30);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());assert.equal(d.querySelectorAll('.practice-box').length,30);assert.equal(d.querySelectorAll('[data-em-inquiry]>li').length,12);assert.equal(d.querySelectorAll('[data-em-inquiry]').length,4);let paths=0;
 for(const q of qs){assert.equal(q.answers.length,3);assert.equal(q.sectionIndex,sections.findIndex(ids=>ids.includes(q.id)));assert.equal(q.answers.filter(a=>a.correct).length,1);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);assert.equal(d.querySelector('.practice-box[data-id="'+q.id+'"]').closest('[data-chapter-section]').dataset.chapterSection,String(q.sectionIndex));const qi=qs.indexOf(q);
  for(let choice=0;choice<3;choice++){for(const[i,other]of qs.entries())d.querySelector('input[name="chapter_q_'+i+'"][value="'+(i===qi?choice:keys[other.id])+'"]').checked=true;w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id]?100:97);assert.equal(r.contentRevision,6);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;}
 }
 assert.equal(paths,90);assert.equal(w.currentChapterResult(id,{contentRevision:5,passed:true,bestPercent:100}).passed,false);
 const text=data[id].sections.map(s=>s.quizzes.map(q=>q.question+' '+q.answers.map(a=>a.text+' '+a.feedback).join(' ')).join(' ')).join(' ');assert.doesNotMatch(text,/Ein Vakuum|Magnet muss dadurch schmelzen|Holzstuhl|Wer entdeckte 1820/);
 assert.equal(d.getElementById('voltValSec').namespaceURI,'http://www.w3.org/1999/xhtml');assert.equal(d.getElementById('transRange').labels.length,1);
 for(let n=1;n<=10;n++){w.updateTransformer(n);assert.equal(d.querySelector('[data-transformer-turns]').textContent,String(n));assert.equal(d.getElementById('voltValSec').textContent,n*46+'V');assert.ok(d.getElementById('transText').textContent.includes(n*46+'V'));}
 w.setMaterial('iron');assert.doesNotMatch(d.getElementById('materialText').innerText,/Maximum/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/physik_bay6/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-physics-material'),solutions=pd.getElementById('ws-solutions');assert.equal(material.querySelectorAll('[data-em-inquiry]>li').length,12);assert.equal(material.querySelectorAll('[data-em-paper]').length,4);assert.ok(material.textContent.includes('Dessen Spannungsquelle versorgt die Lampe'));assert.ok(material.textContent.includes('Ohne Leiterstrom bleibt zum Beispiel das Erdmagnetfeld bestehen'));assert.equal(material.querySelectorAll('[data-transformer-paper] tbody tr').length,3);assert.equal(solutions.hidden,true);assert.ok(!material.textContent.includes('100 J − 70 J = 30 J'));assert.ok(solutions.textContent.includes('100 J − 70 J = 30 J'));assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,30);assert.equal(pd.getElementById('ws-print').disabled,false);paper.window.close();console.log('PASS: all 30 electromagnetism questions, 90 independently keyed answers, seven section mappings, revision 6, 12 inquiry tasks, ten readable transformer states and paper/solution separation.');
})().catch(e=>{console.error(e);process.exitCode=1;});
