const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{const dom=new JSDOM(read('topics/learning.html'),{url:'https://example.test/topics/learning.html',runScripts:'outside-only'}),w=dom.window,d=w.document;w.localStorage.setItem('physik_lang','en');w.fetch=async()=>({ok:true,json:async()=>JSON.parse(read('lang/de.json'))});for(const name of ['curriculum','chapter-revisions','chapter-title-index','learning'])w.eval(read('js/'+name+'.js'));await new Promise(r=>setImmediate(r));
assert.equal(d.querySelector('header h1').textContent,'What would you like to learn?');assert.equal(d.querySelector('.filters').lang,'en');assert.equal(d.querySelector('[data-mode="teach"]').textContent,'Plan lessons');assert.equal(d.querySelector('#subject option[value="kunst"]').textContent,'Art and design');assert.match(d.querySelector('#grade option[value="5"]').textContent,/year 1 · school year 5/);
const subject=d.getElementById('subject'),grade=d.getElementById('grade'),search=d.getElementById('search');subject.value='kunst';grade.value='5';search.value='museum';search.dispatchEvent(new w.Event('input'));assert.ok(d.querySelector('[data-focus-key="catalog-open-kunst_1_museum"]'));
search.value='Encountering art';search.dispatchEvent(new w.Event('input'));
const add=()=>d.querySelector('[data-focus-key="catalog-toggle-kunst_1_museum"]');assert.equal(add().textContent,'Add to test material');add().click();assert.equal(add().textContent,'✓ In test material');assert.equal(add().getAttribute('aria-pressed'),'true');assert.equal(d.getElementById('count').textContent,'1 chapter');assert.equal(d.querySelector('.chapter .actions').lang,'en');assert.equal(d.querySelector('.chapter [data-chapter-metadata]').textContent,'Art and design · Mittelschule year 1 · school year 5');assert.equal(d.querySelector('#selected [data-chapter-metadata]').textContent,'Art and design · Mittelschule year 1 · school year 5');
for(const [record,expected]of [[null,'No chapter check yet'],[{contentRevision:1,lastPercent:50},'keep practising'],[{contentRevision:1,lastPercent:100},'review again later'],[{contentRevision:0,lastPercent:100},'Chapter updated']]){w.localStorage.setItem('sciverse_chapter_quiz_results',JSON.stringify(record?{kunst_1_museum:record}:{}));w.dispatchEvent(new w.StorageEvent('storage'));const status=d.querySelector('.chapter .personal-result');assert.ok(status.textContent.includes(expected));assert.equal(status.lang,'en');}
search.value='no-such-museum-topic';search.dispatchEvent(new w.Event('input'));assert.equal(d.getElementById('count').textContent,'0 chapters');assert.match(d.querySelector('.empty').textContent,/No matching chapters/);search.value='museum';search.dispatchEvent(new w.Event('input'));
d.querySelector('[data-mode="review"]').click();assert.match(d.getElementById('mode-help').textContent,/Choose your test material/);
search.focus();w.dispatchEvent(new w.MessageEvent('message',{origin:w.location.origin,data:{type:'languageChange',lang:'de'}}));assert.equal(d.activeElement,search);assert.equal(subject.value,'kunst');assert.equal(grade.value,'5');assert.equal(search.value,'museum');assert.equal(d.querySelector('header h1').lang,'de');assert.equal(d.getElementById('subject-label').textContent,'Fach');assert.match(d.querySelector('#selected [data-chapter-metadata]').textContent,/Kunst und Gestaltung.*5. Schulstufe/);assert.match(d.getElementById('mode-help').textContent,/Prüfungsstoff/);assert.equal(d.querySelector('#subject option[value="kunst"]').textContent,'Kunst und Gestaltung');
w.dispatchEvent(new w.MessageEvent('message',{origin:w.location.origin,data:{type:'languageChange',lang:'en'}}));assert.equal(d.activeElement,search);assert.equal(d.querySelectorAll('#subject option[value="kunst"]').length,1);assert.equal(d.querySelector('.modes').getAttribute('aria-label'),'Learning path');dom.window.close();console.log('PASS: English learning entry, card actions, four result states, empty search, subject/year labels, mode help, German restoration and preserved filters, query and focus across language switches.');})().catch(e=>{console.error(e);process.exitCode=1;});
