const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math3_2_potenzen_terme';
const answers={m32_q1:1,m32_sign:0,m32_exponent:2,m32_product:0,m32_quotient:1,m32_power_power:2,m32_dip1:0,m32_collect:1,m32_q2:0,m32_expand:2,m32_factor:0,m32_cancel:1,m32_binomial_plus:1,m32_binomial_minus:2,m32_binomial_product:0,m32_counterexample:1,m32_border:2,m32_special_case:0,m32_ten_negative:1,m32_ten_zero:2,m32_ten_scale:0,m32_ten_sign:2,m32_sci_large:1,m32_sci_small:0,m32_sci_compare:1,m32_sci_display:2};
const sections=[['m32_q1','m32_sign','m32_exponent'],['m32_product','m32_quotient','m32_power_power'],['m32_ten_negative','m32_ten_zero','m32_ten_scale','m32_ten_sign'],['m32_sci_large','m32_sci_small','m32_sci_compare','m32_sci_display'],['m32_dip1','m32_collect','m32_q2'],['m32_expand','m32_factor','m32_cancel'],['m32_binomial_plus','m32_binomial_minus','m32_binomial_product'],['m32_counterexample','m32_border','m32_special_case']];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 assert.equal(data[id].sections.length,8);assert.equal(d.querySelectorAll('[data-power-tasks]>li').length,18);assert.equal(d.querySelectorAll('[data-power-static] svg').length,3);
 const lab=d.querySelector('[data-power-lab]'),mode=lab.querySelector('[data-power-mode]'),aInput=lab.querySelector('[data-power-a]'),bInput=lab.querySelector('[data-power-b]'),model=lab.querySelector('[data-power-model]'),saved=JSON.stringify(w.localStorage);let states=0,diagrams=0;
 for(const key of ['sum','difference','product'])for(let a=2;a<=8;a++)for(let b=0;b<=8;b++){
  mode.value=key;aInput.value=String(a);bInput.value=String(b);mode.dispatchEvent(new w.Event('change'));
  const expected=key==='sum'?(a+b)*(a+b):key==='difference'?(a-b)*(a-b):(a+b)*(a-b),wrong=key==='sum'?a*a+b*b:key==='difference'?a*a-b*b:(a-b)*(a-b);
  for(const selector of ['[data-power-original]','[data-power-expanded]'])assert.equal(Number(lab.querySelector(selector).textContent.split(' = ').at(-1)),expected);
  const written=lab.querySelector('[data-power-expanded]').textContent.split(' = ')[0],sum=written.match(/[−-]?\s*\d+/g).reduce((n,s)=>n+Number(s.replace('−','-').replace(/\s/g,'')),0);assert.equal(sum,expected);
  assert.equal(Number(lab.querySelector('[data-power-mistake]').textContent.split(': ').at(-1)),wrong);assert.ok(lab.querySelector('[data-power-comparison]').textContent.includes(expected===wrong?'kein':'widerlegt'));
  const hidden=key!=='sum'&&a<b;assert.equal(model.hidden,hidden);if(hidden){assert.equal(model.children.length,0);assert.match(lab.querySelector('[role=status]').textContent,/algebraische Formel gilt weiterhin/);}else{
   const svg=model.querySelector('svg'),u=key==='difference'?240/a:key==='sum'?260/(a+b):144/a;assert.ok(svg);const area={};for(const r of svg.querySelectorAll('rect')){area[r.dataset.powerPiece]=Number(r.dataset.area);assert.ok(Math.abs(Number(r.getAttribute('width'))*Number(r.getAttribute('height'))/(u*u)-Number(r.dataset.area))<1e-9);assert.ok(Number(r.getAttribute('width'))>0&&Number(r.getAttribute('height'))>0);}
   if(key==='sum')assert.equal(Object.values(area).reduce((a,b)=>a+b,0),expected);
   if(key==='difference'){assert.equal((area.remaining||0),expected);assert.equal(Object.values(area).reduce((a,b)=>a+b,0),a*a);assert.equal((area.right||0)+(area.overlap||0),a*b);assert.equal((area.bottom||0)+(area.overlap||0),a*b);}
   if(key==='product'){assert.equal((area.top||0)+(area.bottom||0),expected);assert.equal((area.newLeft||0)+(area.newRight||0),expected);assert.equal((area.removed||0),b*b);}
   diagrams++;
  }states++;
 }
 assert.equal(states,189);assert.equal(diagrams,147);mode.value='product';mode.dispatchEvent(new w.Event('change'));w.topicInit();assert.equal(mode.value,'product');lab.querySelector('[data-power-reset]').click();assert.equal(mode.value,'sum');assert.equal(aInput.value,'6');assert.equal(bInput.value,'2');assert.equal(d.activeElement,mode);assert.equal(JSON.stringify(w.localStorage),saved);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,26);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(answers).sort());let paths=0;
 for(const[i,q]of qs.entries()){assert.equal(q.sectionIndex,sections.findIndex(s=>s.includes(q.id)));for(let answer=0;answer<3;answer++){qs.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?answer:answers[item.id])+'"]').checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,answer===answers[q.id]?100:96);assert.deepEqual(r.reviewQuestionIds,answer===answers[q.id]?[]:[q.id]);assert.equal(r.contentRevision,4);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[answer].feedback));paths++;}}
 assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:3}).passed,false);dom.window.close();
 const legacy=new JSDOM('<input id="pot1"><p id="potFb"></p>',{runScripts:'outside-only'});legacy.window.eval(read('js/topics/'+id+'.js'));legacy.window.document.getElementById('pot1').value='4';legacy.window.checkPot();assert.match(legacy.window.document.getElementById('potFb').textContent,/^Richtig:/);legacy.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pd.getElementById('ws-math-material');assert.equal(material.querySelectorAll('article').length,8);assert.equal(material.querySelectorAll('[data-power-tasks]>li').length,18);assert.equal(material.querySelectorAll('svg[data-worksheet-static]').length,3);assert.equal(material.querySelectorAll('[data-power-paper] tbody tr').length,9);assert.equal(material.querySelectorAll('button,input,select,[role=status]').length,0);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,26);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,8);assert.equal(pd.getElementById('ws-print').disabled,false);
 function checkGenerated(tasks,solutions){assert.equal(tasks.length,8);assert.equal(solutions.length,8);for(let i=0;i<8;i++){const base=Number(tasks[i].dataset.base),exponent=Number(tasks[i].dataset.exponent),answer=Number(solutions[i].dataset.powerAnswer);let product=1;for(let k=0;k<exponent;k++)product*=base;assert.equal(answer,product);assert.ok(base*(i%2?-1:1)>0);assert.ok(solutions[i].textContent.includes('= '+answer));assert.equal(solutions[i].querySelector('h3').textContent,'Zusatzübung A'+(i+1));}}
 const tasks=pd.querySelectorAll('[data-power-generated]');checkGenerated(tasks,pd.querySelectorAll('#ws-solutions [data-power-answer]'));assert.equal(pd.querySelectorAll('template[data-generated-worksheet-solutions]').length,0);assert.equal(pd.getElementById('ws-solutions').hidden,true);const draw=Array.from(tasks,e=>e.textContent),toggle=pd.getElementById('ws-include-solutions');for(const checked of [true,false,true]){toggle.checked=checked;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,!checked);assert.deepEqual(Array.from(tasks,e=>e.textContent),draw);}
 for(const seed of [0,.5,.999999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);checkGenerated(host.querySelectorAll('[data-power-generated]'),host.querySelector('template').content.querySelectorAll('[data-power-answer]'));}paper.window.close();
 console.log(`PASS: powers/terms year three: ${paths} independently keyed answer paths, eight sections/revision; ${states} formula comparisons, ${diagrams} scaled area decompositions, model limits/counterexamples/reset/no storage; eight-section paper, three figures/nine rows and 32 generated solutions.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
