const fs=require('fs'),assert=require('node:assert/strict'),path=require('path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
(async()=>{for(const [id,key,outId,correct]of [['math3_10_prozent_zins','ans_m310_1','res_m310_1',10],['math4_1_reelle_zahlen','root1','feedback1',5],['math4_3_terme_gleichungen','term1','fb_term1',6],['math4_4_funktionen_sys','func1','fb_func1',5]]){
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();const input=d.getElementById(key),out=d.getElementById(outId),stored=w.localStorage.getItem('sciverse_chapter_quiz_results');assert.equal(input.type,'text');assert.ok(input.getAttribute('aria-label'));assert.equal(out.getAttribute('aria-live'),'polite');
 const submit=value=>{input.value=value;input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));};
 for(const value of [String(correct),correct+',0',correct+'.00','+'+correct]){submit(value);assert.match(out.textContent,/Richtig|Korrekt/,id);}
 for(const value of ['', ' ', '0x5','5e0','1,2,3','Infinity']){submit(value);assert.match(out.textContent,/Gib eine ganze Zahl oder Dezimalzahl/,id);}
 submit(String(correct+1));assert.doesNotMatch(out.textContent,/Richtig|Korrekt|Gib eine ganze Zahl/);input.dispatchEvent(new w.Event('input'));assert.equal(out.textContent,'');assert.equal(w.localStorage.getItem('sciverse_chapter_quiz_results'),stored);dom.window.close();
}console.log('PASS: four rendered quick-answer tasks, equivalent decimal formats, invalid input, Enter, stale feedback clearing, accessible labels and unchanged quiz storage.');})().catch(e=>{console.error(e);process.exitCode=1;});
