'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),data=JSON.parse(read('lang/de.json')),id='math2_7_geometrie';
const keys=require('./fixtures/geometry_answer_keys.json');
const expectedPoints=[[[0,0],[6,0],[5,3],[1,3]],[[0,0],[8,0],[5,4],[2,4]],[[0,0],[4,0],[5,3],[1,3]],[[0,2],[2,0],[0,-4],[-2,0]],[[0,3],[3,0],[0,-5],[-3,0]],[[0,3],[2,0],[0,-3],[-2,0]],[[0,3],[3,0],[0,-3],[-3,0]]];
const polygonArea=ps=>Math.abs(ps.reduce((s,p,i)=>{const q=ps[(i+1)%ps.length];return s+p[0]*q[1]-q[0]*p[1];},0))/2,dist=(p,q)=>Math.hypot(p[0]-q[0],p[1]-q[1]);
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`),points=el=>el.getAttribute('points').split(' ').map(p=>p.split(',').map(Number));
async function render(){const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','language-workshop','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();w.topicInit();return dom;}
(async()=>{const dom=await render(),w=dom.window,d=w.document,q=s=>d.querySelector(s),saved=JSON.stringify(w.localStorage),lab=q('[data-quad-construction]'),select=q('#quad-case'),next=q('[data-quad-next]'),prev=q('[data-quad-prev]');let steps=0,models=0;
for(let i=0;i<7;i++){const m=w.quadConstructionModel(i),ps=expectedPoints[i];assert.deepEqual(JSON.parse(JSON.stringify(m.points)),ps);near(m.area,polygonArea(ps));select.value=String(i);select.dispatchEvent(new w.Event('change'));assert.equal(lab.dataset.step,'0');assert.ok(prev.disabled);for(let step=0;step<=5;step++){assert.equal(lab.dataset.step,String(step));const svg=lab.querySelector('svg');assert.ok(svg.getAttribute('aria-label').includes(step===0?'Planfigur':step+'.'));const poly=svg.querySelector('[data-quad-polygon]');assert.equal(!!poly,step===0||step===5);if(poly){const drawn=points(poly),scale=i<3?25:22;near(polygonArea(drawn)/scale**2,polygonArea(ps));for(let j=0;j<4;j++)near(dist(drawn[j],drawn[(j+1)%4])/scale,dist(ps[j],ps[(j+1)%4]));}steps++;if(step<5)next.click();}assert.ok(next.disabled);prev.click();assert.equal(lab.dataset.step,'4');}
q('[data-quad-reset]').click();assert.equal(select.value,'0');assert.equal(lab.dataset.step,'0');assert.equal(d.activeElement,select);next.click();assert.equal(lab.dataset.step,'1');for(const index of [-1,7,.5,'0'])assert.equal(w.quadConstructionModel(index),null);
const e=q('[data-diagonal-e]'),f=q('[data-diagonal-f]'),u=q('[data-diagonal-u]');for(const ev of [4,6,8])for(const fv of [2,4,6])for(let uv=1;uv<ev;uv++){e.value=String(ev);f.value=String(fv);e.dispatchEvent(new w.Event('change'));u.value=String(uv);u.dispatchEvent(new w.Event('input'));const m=w.diagonalAreaModel(ev,fv,uv),ps=Array.from(m.points,p=>Array.from(p));near(dist(ps[0],ps[1]),dist(ps[0],ps[3]));near(dist(ps[2],ps[1]),dist(ps[2],ps[3]));near(dist(ps[0],ps[2]),ev);near(dist(ps[1],ps[3]),fv);assert.equal(ps[1][1],ps[3][1]);assert.equal(ps[0][0],ps[2][0]);assert.equal((ps[1][0]+ps[3][0])/2,0);near(m.area,polygonArea(ps));assert.equal(m.rhombus,dist(ps[0],ps[1])===dist(ps[1],ps[2]));assert.equal(m.square,m.rhombus&&ev===fv);const upper=points(q('[data-diagonal-area] [data-diagonal-upper]')),lower=points(q('[data-diagonal-area] [data-diagonal-lower]'));near(polygonArea(upper)/22**2,m.upper);near(polygonArea(lower)/22**2,m.lower);near(m.upper+m.lower,m.area);assert.equal(u.max,String(ev-1));assert.ok(q('[data-diagonal-status]').textContent.includes('= '+m.area+' cm²'));models++;}
for(const args of [[5,4,2],[6,5,2],[6,4,0],[6,4,6],[6,4,1.5],['6',4,2]])assert.equal(w.diagonalAreaModel(...args),null);e.value='8';e.dispatchEvent(new w.Event('change'));u.value='7';e.value='4';e.dispatchEvent(new w.Event('change'));assert.equal(u.value,'3');q('[data-diagonal-reset]').click();assert.equal(e.value,'6');assert.equal(f.value,'4');assert.equal(u.value,'2');assert.equal(d.activeElement,e);assert.equal(JSON.stringify(w.localStorage),saved);
const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,40);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;for(const[i,item]of qs.entries()){assert.equal(item.sectionIndex,data[id].sections.findIndex(s=>s.quizzes.some(q=>q.id===item.id)));for(let a=0;a<3;a++){assert.equal(item.answers[a].correct,a===keys[item.id]);qs.forEach((q,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?a:keys[q.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[item.id]?100:98);assert.equal(result.contentRevision,9);assert.deepEqual(result.reviewQuestionIds,a===keys[item.id]?[]:[item.id]);assert.ok(q('#chapter-quiz-result').textContent.includes(item.answers[a].feedback));paths++;}}assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:8}).passed,false);dom.window.close();
const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('#ws-math-material article').length,9);assert.equal(pd.querySelectorAll('[data-quad-tasks]>li').length,6);assert.equal(pd.querySelectorAll('[data-quad-paper]').length,2);assert.equal(pd.querySelectorAll('#ws-math-material svg.quad-svg').length,4);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,12);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,40);
assert.equal(pd.querySelectorAll('#ws-math-material svg').length,14);
const doubling=pd.querySelectorAll('.quad-figure')[2].querySelectorAll('polygon'),one=points(doubling[0]),two=points(doubling[1]);near(polygonArea(one),6000);near(polygonArea(two),6000);for(let i=0;i<4;i++){near(one[i][0]+two[(i+2)%4][0],300);near(one[i][1]+two[(i+2)%4][1],250);}
function verify(host,solutions){const tasks=host.querySelectorAll('[data-quad-generated]'),answers=solutions.querySelectorAll('[data-quad-answer]');assert.equal(tasks.length,12);assert.equal(answers.length,12);assert.notEqual(tasks[10].dataset.a,tasks[11].dataset.a);for(let i=0;i<12;i++){const t=tasks[i],a=Number(t.dataset.a),b=Number(t.dataset.b),c=Number(t.dataset.c),kind=t.dataset.quadGenerated,area=kind==='trapezoid'?(a+b)*c/2:kind==='parallelogram'?a*b:a*b/2;assert.equal(Number(answers[i].dataset.quadAnswer),area);if(kind==='kite')assert.ok(c>0&&c<a);}}
verify(pd,pd.getElementById('ws-solutions'));for(const seed of [0,.5,.99999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify(host,host.querySelector('template').content);}const before=[...pd.querySelectorAll('[data-quad-generated]')].map(e=>e.textContent);for(const checked of [true,false,true]){pd.getElementById('ws-include-solutions').checked=checked;pd.getElementById('ws-include-solutions').dispatchEvent(new pw.Event('change'));assert.deepEqual([...pd.querySelectorAll('[data-quad-generated]')].map(e=>e.textContent),before);}paper.window.close();console.log('PASS: '+steps+' construction states, '+models+' independently measured diagonal-area models, all '+paths+' answer paths, revision/focus/reset/storage and 48 generated worksheet cases.');})().catch(e=>{console.error(e);process.exitCode=1;});
