const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const options={url:'https://example.test/site/examples/signalwerkstatt.html',runScripts:'dangerously',beforeParse(w){w.HTMLMediaElement.prototype.load=function(){};w.HTMLMediaElement.prototype.pause=function(){};}};
const dom=new JSDOM(read('examples/signalwerkstatt.html'),options),w=dom.window,d=w.document,get=id=>d.getElementById(id),api=w.SignalWerkstatt;let cases=0;
for(const a of [400,600,800])for(const b of [400,600,800])for(const c of [400,600,800])for(const duration of [.2,.4,.6]){
 const wav=Buffer.from(api.wav([a,b,c],duration)),count=duration*16000,gap=3200;assert.equal(wav.toString('ascii',0,4),'RIFF');assert.equal(wav.toString('ascii',8,12),'WAVE');assert.equal(wav.readUInt32LE(4),wav.length-8);assert.equal(wav.readUInt32LE(24),16000);assert.equal(wav.readUInt16LE(22),1);assert.equal(wav.readUInt16LE(34),16);assert.equal(wav.readUInt32LE(40),wav.length-44);assert.equal((wav.length-44)/2,count*3+gap*2);
 for(const [n,f]of [a,b,c].entries()){const base=44+n*(count+gap)*2;let crossings=0;for(let i=1;i<count;i++){const prev=wav.readInt16LE(base+(i-1)*2),v=wav.readInt16LE(base+i*2);assert.ok(Math.abs(v)<=5000);if(prev<0&&v>=0)crossings++;}assert.ok(Math.abs(crossings-f*duration)<=1,`${f}Hz ${duration}s: ${crossings}`);assert.equal(wav.readInt16LE(base),0);assert.equal(wav.readInt16LE(base+(count-1)*2),0);if(n<2)for(let i=0;i<gap;i++)assert.equal(wav.readInt16LE(base+(count+i)*2),0);}
 cases++;
}
assert.equal(cases,81);assert.throws(()=>api.wav([300,600,800],.4));assert.throws(()=>api.wav([400,600,800],1));assert.equal(d.querySelectorAll('script[src],iframe,img,link[rel=stylesheet]').length,0);assert.equal(get('player').hasAttribute('autoplay'),false);assert.equal(get('player').hasAttribute('src'),false);
const change=(id,value)=>{get(id).value=value;get(id).dispatchEvent(new w.Event('input'));};change('headline','<img src=x onerror=alert(1)>');change('meaning','</textarea><script>window.unwanted=true</script>');change('tone-1','800');change('tone-2','400');change('tone-3','600');change('duration','0.6');change('palette','wald');change('notes','Fassung B; eigener Test steht noch aus.');
assert.equal(get('card-title').textContent,'<img src=x onerror=alert(1)>');assert.equal(get('card').querySelectorAll('img,script').length,0);assert.match(get('timing').textContent,/2,2 s/);get('generate').click();const first=get('player').src;assert.ok(first.startsWith('data:audio/wav;base64,'));assert.equal(Buffer.from(first.split(',')[1],'base64').length,70444);
change('duration','0.2');assert.equal(get('player').hasAttribute('src'),false);assert.match(get('status').textContent,/geändert/);const result=api.resultHTML(),product=new JSDOM(result),pd=product.window.document;assert.equal(pd.querySelectorAll('script,textarea,select,button').length,0);assert.equal(pd.querySelector('h2').textContent,'<img src=x onerror=alert(1)>');assert.ok(pd.querySelector('audio').src.startsWith('data:audio/wav'));assert.equal(pd.querySelector('audio').hasAttribute('autoplay'),false);assert.equal(pd.querySelectorAll('.signal-list li').length,3);assert.equal(pd.querySelectorAll('.editor').length,0);assert.ok(!pd.body.textContent.includes('Fassung B; eigener Test'));
const saved=api.workingHTML(),again=new JSDOM(saved,{...options,url:'file:///C:/test/signal.html'}),rd=again.window.document;for(const id of ['headline','meaning','tone-1','tone-2','tone-3','duration','palette','notes'])assert.equal(rd.getElementById(id).value,get(id).value);assert.equal(again.window.unwanted,undefined);assert.equal(rd.getElementById('player').hasAttribute('src'),false);rd.getElementById('generate').click();assert.equal(rd.getElementById('player').src,get('player').src);assert.equal(w.localStorage.length,0);product.window.close();again.window.close();dom.window.close();
(async()=>{const data=JSON.parse(read('lang/de.json')),id='dgb6_produktion',paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const m=pw.document.getElementById('ws-dgb-material'),s=pw.document.getElementById('ws-solutions');assert.equal(m.querySelectorAll('[data-signal-project-tasks]>li').length,8);assert.equal(m.querySelectorAll('[data-signal-test-plan] tbody tr').length,3);assert.equal(m.querySelectorAll('[data-license-cards] tbody tr').length,3);assert.equal(m.querySelectorAll('[data-signal-project-solution]').length,0);assert.equal(s.querySelectorAll('[data-signal-project-solution]').length,1);assert.equal(s.hidden,true);assert.ok(s.textContent.includes('1,6 s'));paper.window.close();console.log('PASS: 81 WAV variants with measured frequency cycles, pauses and length; no autoplay, stale-audio reset, safe text, offline workfile round-trip, script-free result and chapter paper materials.');})().catch(e=>{console.error(e);process.exitCode=1;});
