const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math2_5_var_gleichungen';
const answers={m25_q1:0,m25_term_value:1,m25_fraction_term:2,m25_q2:0,m25_dip1:0,m25_reverse_order:1,m25_dip2:0,m25_valid_detour:2,m25_zero_step:1,m25_fraction_solution:2,m25_context_limit:1,m25_write_text:0,m25_formula_quantity:1,m25_formula_percent:2,m25_formula_rectangle:0};
const sectionKeys=[['m25_q1','m25_term_value','m25_fraction_term'],['m25_q2','m25_dip1','m25_reverse_order'],['m25_dip2','m25_valid_detour','m25_zero_step'],['m25_fraction_solution','m25_context_limit','m25_write_text'],['m25_formula_quantity','m25_formula_percent','m25_formula_rectangle']];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 assert.equal(data[id].sections.length,5);assert.equal(d.querySelectorAll('[data-equation2-tasks]>li').length,15);assert.equal(d.querySelectorAll('[data-equation2-chain]').length,1);
 const saved=JSON.stringify(w.localStorage),probe=d.querySelector('[data-equation2-probe]'),select=probe.querySelector('select'),input=probe.querySelector('input'),feedback=probe.querySelector('[role=status]');
 let calculations=0;
 const probes=[...Array.from({length:61},(_,i)=>({text:String(i/2).replace('.',','),value:i/2})),...[3,4].flatMap(den=>Array.from({length:46},(_,n)=>({text:n+'/'+den,value:n/den})))];
 for(let task=0;task<3;task++){
  select.value=String(task);select.dispatchEvent(new w.Event('change'));
  for(const entry of probes){input.value=entry.text;input.dispatchEvent(new w.Event('input'));assert.equal(feedback.textContent,'');input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));const left=[2*entry.value+3,entry.value/3+2,3*entry.value][task],right=[11,7,7.5][task];assert.equal(feedback.textContent.startsWith('Richtig:'),left===right,task+' '+entry.text);assert.equal(input.hasAttribute('aria-invalid'),false);if(left!==right)assert.ok(feedback.textContent.includes(left<right?'links kleiner':'links größer'));calculations++;}
 }
 for(const text of ['', ' ', '2/0','2/00','abc','2,5x','1+3','1e2','Infinity','NaN','4/2/2','3.9999','1000000']){input.value=text;probe.querySelector('[data-equation2-check]').click();assert.equal(input.getAttribute('aria-invalid'),'true',text);assert.match(feedback.textContent,/Gib eine Zahl/);}
 select.value='2';select.dispatchEvent(new w.Event('change'));for(const text of ['2,5','2.5','5/2',' 10 / 4 ','0002.500']){input.value=text;probe.querySelector('[data-equation2-check]').click();assert.match(feedback.textContent,/^Richtig:/,text);}
 input.value='−1';probe.querySelector('[data-equation2-check]').click();assert.match(feedback.textContent,/links kleiner/);assert.equal(input.hasAttribute('aria-invalid'),false);
 input.value='999999.999';probe.querySelector('[data-equation2-check]').click();assert.match(feedback.textContent,/links größer/);assert.ok(!/NaN|Infinity/.test(feedback.textContent));
 select.value='0';select.dispatchEvent(new w.Event('change'));assert.equal(input.value,'');assert.equal(feedback.textContent,'');
 probe.querySelector('[data-equation2-reset]').click();assert.equal(d.activeElement,select);assert.equal(select.value,'0');
 const lab=d.querySelector('[data-equation2-step]'),caseSelect=lab.querySelector('select'),stepFeedback=lab.querySelector('[role=status]'),correct=['same','same','changed','changed','undefined','same'];let decisions=0;
 for(let i=0;i<6;i++){caseSelect.value=String(i);caseSelect.dispatchEvent(new w.Event('change'));assert.equal(stepFeedback.textContent,'');for(const button of lab.querySelectorAll('[data-equation2-verdict]')){button.click();assert.equal(stepFeedback.textContent.startsWith('Richtig:'),button.dataset.equation2Verdict===correct[i],i);assert.ok(stepFeedback.textContent.length>55);decisions++;}}
 caseSelect.value='1';caseSelect.dispatchEvent(new w.Event('change'));lab.querySelector('[data-equation2-verdict=same]').click();assert.match(stepFeedback.textContent,/Umweg ist kein Rechenfehler/);w.topicInit();assert.equal(caseSelect.value,'1');assert.match(stepFeedback.textContent,/Umweg ist kein Rechenfehler/);
 lab.querySelector('[data-equation2-step-reset]').click();assert.equal(caseSelect.value,'0');assert.equal(d.activeElement,caseSelect);assert.equal(JSON.stringify(w.localStorage),saved);
 const questions=w.currentChapterQuiz.questions;assert.equal(questions.length,15);assert.deepEqual(Array.from(questions,q=>q.id).sort(),Object.keys(answers).sort());let paths=0;
 for(const [i,q] of questions.entries()){assert.equal(q.sectionIndex,sectionKeys.findIndex(keys=>keys.includes(q.id)));for(let answer=0;answer<3;answer++){questions.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?answer:answers[item.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,answer===answers[q.id]?100:93);assert.deepEqual(result.reviewQuestionIds,answer===answers[q.id]?[]:[q.id]);assert.equal(result.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[answer].feedback));paths++;}}
 assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:1}).passed,false);
 dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pd.querySelector('#ws-math-material');assert.equal(material.querySelectorAll('article').length,5);assert.equal(material.querySelectorAll('[data-equation2-tasks]>li').length,15);assert.equal(material.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(material.querySelectorAll('[data-equation2-probe-paper] tbody tr').length,3);assert.equal(material.querySelectorAll('[data-equation2-case-paper] tbody tr').length,6);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,15);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,5);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(material.querySelectorAll('button,input,select,[role=status]').length,0);assert.equal(pd.getElementById('ws-print').disabled,false);
 function checkGenerated(tasks,solutions){assert.equal(tasks.length,12);assert.equal(solutions.length,12);for(let i=0;i<12;i++){const a=Number(tasks[i].dataset.a),b=Number(tasks[i].dataset.b),r=Number(tasks[i].dataset.result),x=Number(solutions[i].dataset.generatedAnswer);assert.equal((r-b)/a,x);assert.equal(a*x+b,r);assert.ok(tasks[i].textContent.includes(a+'x + '+b+' = '+r));assert.ok(solutions[i].textContent.includes('x = '+x));assert.ok(solutions[i].textContent.includes(a+' · '+x+' + '+b+' = '+r));assert.equal(solutions[i].querySelector('h3').textContent,'Zusatzübung A'+(i+1));}}
 const generatedTasks=pd.querySelectorAll('[data-generated-equation]'),generatedAnswers=pd.querySelectorAll('#ws-solutions .ws-generated-equation-solution');checkGenerated(generatedTasks,generatedAnswers);assert.equal(pd.querySelectorAll('template[data-generated-worksheet-solutions]').length,0);
 const originalDraw=Array.from(generatedTasks,e=>e.textContent);const toggle=pd.getElementById('ws-include-solutions');toggle.checked=true;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,false);assert.deepEqual(Array.from(generatedTasks,e=>e.textContent),originalDraw);toggle.checked=false;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,true);
 for(const seed of [0,.25,.999999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);checkGenerated(host.querySelectorAll('[data-generated-equation]'),host.querySelector('template[data-generated-worksheet-solutions]').content.querySelectorAll('.ws-generated-equation-solution'));}paper.window.close();
 console.log(`PASS: year-two equations: ${paths} independently keyed quiz paths, five section/revision mappings, ${calculations} exact comparison cases, invalid/fraction/decimal inputs, ${decisions} step verdicts, reset/focus/no storage, five-section paper and 48 generated exercises with independently verified matching solutions/toggle.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
