const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
// Connectivity is reconstructed from the actual drawn wire endpoints and component terminals.
function circuitGraph(svg){const graph=new Map(),key=p=>p.join(','),connect=(a,b)=>{a=key(a);b=key(b);for(const[x,y]of [[a,b],[b,a]]){if(!graph.has(x))graph.set(x,new Set());graph.get(x).add(y);}};
 for(const line of svg.querySelectorAll('[data-relay-wire]'))connect(['x1','y1'].map(a=>Number(line.getAttribute(a))),['x2','y2'].map(a=>Number(line.getAttribute(a))));
 const coil=svg.querySelector('[data-relay-coil]'),x=Number(coil.getAttribute('x')),y=Number(coil.getAttribute('y'))+Number(coil.getAttribute('height'))/2;connect([x,y],[x+Number(coil.getAttribute('width')),y]);
 const lamp=svg.querySelector('[data-relay-lamp]');if(lamp.dataset.present==='true'){const cx=Number(lamp.getAttribute('cx')),cy=Number(lamp.getAttribute('cy')),r=Number(lamp.getAttribute('r'));connect([cx,cy-r],[cx,cy+r]);}
 const terminals=name=>{const n=svg.querySelector('[data-relay-source="'+name+'"] path').getAttribute('d').match(/-?\d+(?:\.\d+)?/g).map(Number);return [[(n[0]+n[2])/2,n[1]],[(n[3]+n[5])/2,n[4]]];};
 const reachable=(from,to)=>{const seen=new Set(),queue=[key(from)],end=key(to);while(queue.length){const v=queue.shift();if(v===end)return true;if(seen.has(v))continue;seen.add(v);queue.push(...graph.get(v)||[]);}return false;};return{terminals,reachable};}
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=elektromagnetismus',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer','topics/elektromagnetismus'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 const lab=d.querySelector('[data-relay-lab]'),supply=lab.querySelector('[data-relay-supply]'),lamp=lab.querySelector('[data-relay-lamp-select]'),stored=JSON.stringify(w.localStorage);let states=0,decisions=0;
 for(const control of [false,true])for(const on of [false,true])for(const present of [false,true]){
  w.updateRelay(control);for(const[el,value]of [[supply,on?'on':'off'],[lamp,present?'present':'removed']]){el.value=value;el.focus();el.dispatchEvent(new w.Event('change'));assert.equal(d.activeElement,el);}const state=w.sciverseRelayState(control,on,present),svg=lab.querySelector('svg'),graph=circuitGraph(svg),ct=graph.terminals('control'),lt=graph.terminals('load');
  assert.equal(graph.reachable(...ct),control);assert.equal(graph.reachable(...lt),control&&present);for(const a of ct)for(const b of lt)assert.equal(graph.reachable(a,b),false,'No conducting connection across circuits');
  assert.equal(state.coil,graph.reachable(...ct));assert.equal(state.loadClosed,graph.reachable(...lt));assert.equal(state.lit,on&&graph.reachable(...lt));assert.equal(svg.querySelector('[data-relay-lamp]').dataset.lit,String(state.lit));assert.equal(lab.querySelector('#relayBtn').getAttribute('aria-pressed'),String(control));
  const contact=svg.querySelector('[data-relay-contact]');assert.equal(Number(contact.getAttribute('x2')),control?210:193);assert.equal(Number(contact.getAttribute('y2')),control?330:305);assert.equal(svg.querySelectorAll('[data-relay-mechanical][data-relay-wire]').length,0);assert.ok(svg.getAttribute('aria-label').includes('elektrisch getrennte'));assert.equal(lab.querySelector('[data-relay-feedback]').textContent,'');
  const expected=!graph.reachable(...ct)?0:on&&graph.reachable(...lt)?2:1;for(const b of lab.querySelectorAll('[data-relay-verdict]')){b.click();assert.equal(lab.querySelector('[data-relay-feedback]').textContent.startsWith('Richtig:'),Number(b.dataset.relayVerdict)===expected);decisions++;}states++;
 }
 assert.equal(states,8);assert.equal(decisions,24);for(const el of [supply,lamp]){assert.equal(el.labels.length,1);assert.equal(el.getAttribute('aria-describedby'),'relayStatus');}w.initRelayLab();assert.equal(lab.dataset.control,'true');w.toggleRelay();assert.equal(lab.dataset.control,'false');w.toggleRelay();assert.equal(lab.dataset.control,'true');lab.querySelector('[data-relay-reset]').click();assert.deepEqual([lab.dataset.control,supply.value,lamp.value],['false','on','present']);assert.equal(d.activeElement,lab.querySelector('#relayBtn'));assert.equal(JSON.stringify(w.localStorage),stored);assert.equal(d.querySelectorAll('#relayContact').length,1);assert.equal(d.querySelectorAll('#relayBulb').length,1);assert.equal(d.querySelectorAll('[data-relay-static] svg[data-worksheet-static]').length,1);for(const p of [[1,true,true],[true,'on',true],[false,true,null]])assert.equal(w.sciverseRelayState(...p),null);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=elektromagnetismus',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-relay-paper] tbody tr').length,8);assert.equal(pd.querySelectorAll('[data-relay-static] svg').length,1);assert.equal(pd.querySelectorAll('[data-relay-tasks]>li').length,2);assert.ok(!pd.getElementById('ws-physics-material').textContent.includes('In den ersten vier Tabellenzeilen'));assert.ok(pd.getElementById('ws-solutions').textContent.includes('In den ersten vier Tabellenzeilen'));assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.getElementById('ws-print').disabled,false);paper.window.close();console.log('PASS: relay: eight circuit cases/24 classifications, independent graph connectivity from SVG geometry, separated circuits, correct contact geometry, keyboard metadata/reset/legacy toggle, no storage and paper.');
})().catch(e=>{console.error(e);process.exitCode=1;});
