'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),data=JSON.parse(read('lang/de.json')),id='math2_3_dezimalzahlen';
const keys={m23_q1:0,m23_q2:0,m23_dip1:0,m23_q3:0,m23_dip2:0,m23_direct_round:1,m23_q4:0,m23_decimal_product:2,m23_decimal_quotient:0,m23_repeat_remainder:1,m23_period_digits:2,m23_terminating:0,m23_repeat_fraction:1,m23_mixed_fraction:0,m23_period_zero:2,m23_exact_third:0,m23_nines:2,m23_reduce_end:1};
const expectedFractions=[[1,3],[2,3],[3,11],[1,6],[1,12],[11,9],[1,1],[1,8],[3,4],[5,2],[0,1],[2,1]];
function rationalOf(model){const base=10n**BigInt(model.prefix.length),front=BigInt(String(model.whole)+model.prefix);if(!model.period)return [front,base];const cycle=10n**BigInt(model.period.length)-1n;return [front*cycle+BigInt(model.period),base*cycle];}
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 const q=s=>d.querySelector(s),change=(s,value)=>{q(s).value=String(value);q(s).dispatchEvent(new w.Event('change'));},saved=JSON.stringify(w.localStorage);let cases=0;
 for(const n of [0,1,2,5,7,13])for(const den of [2,3,4,6,7,8,9,11,12,16]){
  const m=w.periodDivisionModel(n,den),[rn,rd]=rationalOf(m);assert.equal(rn*BigInt(den),BigInt(n)*rd);assert.equal(m.whole*den+m.initialRest,n);let rest=m.initialRest;const seen=[];
  for(const row of m.rows){assert.equal(row.before,rest);assert.ok(!seen.includes(rest));seen.push(rest);assert.equal(row.scaled,rest*10);assert.equal(row.digit*den+row.after,row.scaled);assert.ok(row.digit>=0&&row.digit<=9&&row.after>=0&&row.after<den);rest=row.after;}
  if(m.period){assert.ok(seen.includes(rest));assert.equal(seen.indexOf(rest),m.prefix.length);assert.equal(m.repeatedRest,rest);}else assert.equal(rest,0);
  change('#period-num',n);change('#period-den',den);assert.equal(q('[data-period-table] tbody').rows.length,0);for(let i=0;i<m.rows.length;i++){q('[data-period-next]').click();assert.equal(q('[data-period-table] tbody').rows.length,i+1);}assert.ok(q('#period-status').textContent.includes(m.exact));assert.equal(q('[data-period-next]').disabled,true);if(m.rows.length)assert.equal(d.activeElement,q('[data-period-reset]'));cases++;
 }
 assert.equal(w.periodDivisionModel(1,0),null);assert.equal(w.periodDivisionModel(-1,3),null);assert.equal(w.periodDivisionModel(1.2,3),null);assert.equal(w.periodDivisionModel(1,101),null);
 q('[data-period-reset]').click();assert.equal(q('#period-num').value,'1');assert.equal(q('#period-den').value,'6');assert.equal(d.activeElement,q('#period-num'));q('[data-period-all]').click();assert.equal(q('[data-period-table] tbody').rows.length,2);assert.match(q('#period-status').textContent,/1\/6 = 0,1\(6\)/);assert.equal(d.activeElement,q('[data-period-reset]'));
 for(let i=0;i<12;i++){change('#period-case',i);const m=w.periodFractionModel(i),[n,den]=expectedFractions[i];assert.equal(m.reducedNumerator,n);assert.equal(m.reducedDenominator,den);assert.equal(q('#period-case').selectedOptions[0].textContent,m.label);q('#period-answer-num').value=String(n*2);q('#period-answer-den').value=String(den*2);q('[data-period-check]').click();assert.match(q('#period-back-status').textContent,/Der Wert stimmt/);q('#period-answer-num').value=String(n);q('#period-answer-den').value=String(den);q('#period-answer-den').focus();q('#period-answer-den').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(q('#period-back-status').textContent,/^Richtig:/);assert.equal(d.activeElement,q('#period-answer-den'));q('[data-period-solution]').click();assert.equal(q('[data-period-solution-text]').hidden,false);assert.ok(q('[data-period-solution-text]').textContent.includes(n+'/'+den));}
 for(const [n,den]of [['','3'],['1','0'],['-1','3'],['1.5','3'],['1e2','3'],['1000001','3'],['1','Infinity']]){q('#period-answer-num').value=n;q('#period-answer-den').value=den;q('[data-period-check]').click();assert.match(q('#period-back-status').textContent,/^Gib einen/);}
 change('#period-case',0);q('#period-answer-num').value='3';q('#period-answer-den').value='10';q('[data-period-check]').click();assert.match(q('#period-back-status').textContent,/^Noch nicht/);q('#period-answer-num').dispatchEvent(new w.Event('input'));assert.equal(q('#period-back-status').textContent,'');q('[data-period-back-reset]').click();assert.equal(q('#period-case').value,'0');assert.equal(d.activeElement,q('#period-case'));assert.equal(q('[data-period-solution-text]').hidden,true);w.topicInit();assert.equal(JSON.stringify(w.localStorage),saved);
 assert.equal(data[id].sections.length,6);assert.equal(q('[data-period-lab]').dataset.bound,'true');const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,18);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;
 for(const [i,item]of qs.entries()){assert.equal(item.sectionIndex,Math.floor(i/3));for(let answer=0;answer<3;answer++){qs.forEach((item,j)=>q('input[name="chapter_q_'+j+'"][value="'+(j===i?answer:keys[item.id])+'"]').checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,answer===keys[item.id]?100:94);assert.deepEqual(r.reviewQuestionIds,answer===keys[item.id]?[]:[item.id]);assert.equal(r.contentRevision,2);assert.ok(q('#chapter-quiz-result').textContent.includes(item.answers[answer].feedback));paths++;}}
 assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:1}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-decimal-tasks]>li').length,18);assert.equal(pd.querySelectorAll('#ws-math-material article').length,6);assert.equal(pd.querySelectorAll('#ws-math-material input,#ws-math-material select,#ws-math-material button').length,0);assert.equal(pd.querySelectorAll('[data-period-paper],[data-period-back-paper]').length,2);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,6);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,18);
 function verify(host,solutions){const tasks=host.querySelectorAll('[data-decimal-generated]'),answers=solutions.querySelectorAll('[data-decimal-answer]');assert.equal(tasks.length,8);assert.equal(answers.length,8);for(let i=0;i<8;i++){const t=tasks[i],n=Number(t.dataset.first),m=Number(t.dataset.second),expected=i<4?n*m/100:n;assert.equal(Number(answers[i].dataset.decimalAnswer),expected);if(i<4){assert.ok(t.textContent.includes((n/10).toFixed(1).replace('.',',')+' · '+(m/10).toFixed(1).replace('.',',')));assert.ok(answers[i].textContent.includes(expected.toFixed(2).replace('.',',')));}assert.ok(answers[i].textContent.includes(expected.toLocaleString('de-AT',{useGrouping:false,maximumFractionDigits:3})));}const fractions=host.querySelectorAll('[data-period-generated]'),solution=solutions.querySelectorAll('[data-period-generated-answer]');assert.equal(fractions.length,4);assert.equal(solution.length,4);for(let i=0;i<4;i++){const t=fractions[i],n=Number(t.dataset.num),den=Number(t.dataset.den);assert.equal(solution[i].dataset.periodGeneratedAnswer,n+'/'+den);const [whole,tail]=t.dataset.written.split(','),[prefix,cycle]=tail.split('('),m={whole:Number(whole),prefix,period:cycle?cycle.slice(0,-1):''},[rn,rd]=rationalOf(m);assert.equal(rn*BigInt(den),BigInt(n)*rd);assert.ok(solution[i].textContent.includes(t.dataset.written));}}
 verify(pd,pd.getElementById('ws-solutions'));for(const seed of [0,.5,.99999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify(host,host.querySelector('template').content);}const before=Array.from(pd.querySelectorAll('[data-decimal-generated],[data-period-generated]'),e=>e.textContent),toggle=pd.getElementById('ws-include-solutions');for(const checked of [true,false,true]){toggle.checked=checked;toggle.dispatchEvent(new pw.Event('change'));assert.deepEqual(Array.from(pd.querySelectorAll('[data-decimal-generated],[data-period-generated]'),e=>e.textContent),before);}paper.window.close();console.log(`PASS: periodic decimals: ${cases} exact rational division models and step paths, 12 reverse conversions, ${paths} keyed quiz paths, keyboard/reset/storage/revision; six sections, five paper alternatives, 48 matched generated tasks.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
