'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math4_1_reelle_zahlen';
const keys={m41_q1:0,m41_q2:0,m41_periodic:0,m41_bounds:0,m41_round:0,m41_equation:0,m41_sum:0,m41_dip1:0,m41_product:1,m41_quotient:2,m41_domain:0,m41_square:1,m41_cube_volume:2,m41_cube_negative:0,m41_cube_approx:1,m41_early:2,m41_area_error:0,m41_precision:1};
// Reference via bisection and integer arithmetic, independent of the runtime's Math.sqrt / rounding sequence.
function reference(area,digits){let lo=0,hi=area;for(let i=0;i<80;i++){const mid=(lo+hi)/2;if(mid*mid<area)lo=mid;else hi=mid;}const side=(lo+hi)/2,scale=10**digits,units=Math.floor(side*scale+.5);return {side,rounded:units/scale,earlyCents:Math.floor(400*units/scale+.5),lateCents:Math.floor(side*400+.5),square:units*units/(scale*scale),error:Math.abs(units*units-area*scale*scale)/(scale*scale)};}
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{revision:1,passed:true,bestPercent:100}).passed,false);assert.equal(w.currentChapterQuiz.questions.length,18);assert.equal(d.querySelectorAll('[data-root-tasks] li').length,11);
 const set=(selector,value)=>{const el=d.querySelector(selector);el.value=String(value);el.dispatchEvent(new w.Event('change'));},input=d.querySelector('#root-answer'),status=d.querySelector('#root-round-status'),check=d.querySelector('[data-root-check]'),saved=JSON.stringify(w.localStorage);let models=0;
 const fmt=(x,n)=>x.toLocaleString('de-AT',{minimumFractionDigits:n,maximumFractionDigits:n});
 for(const area of [2,3,5,10,50])for(let digits=0;digits<=4;digits++){
  const ref=reference(area,digits),m=w.rootRoundingModel(area,digits);assert.ok(Math.abs(m.side-ref.side)<1e-12);assert.equal(m.roundedSide,ref.rounded);assert.ok(Math.abs(m.reconstructed-ref.square)<1e-12);assert.ok(Math.abs(m.error-ref.error)<1e-12);set('#root-area',area);set('#root-digits',digits);
  for(const method of ['early','late']){set('#root-method',method);assert.equal(input.value,'');assert.equal(status.textContent,'');assert.equal(d.querySelectorAll('[data-root-row]').length,0);input.value=(ref[method+'Cents']/100).toFixed(2).replace('.',',');check.click();assert.match(status.textContent,/^Richtig\./);assert.equal(d.activeElement,status);const rows=d.querySelectorAll('[data-root-row]');assert.equal(rows.length,2);assert.ok(rows[0].textContent.includes(fmt(ref.earlyCents/100,2)+' m'));assert.ok(rows[0].textContent.includes(fmt(ref.square,8)+' m²'));assert.ok(rows[1].textContent.includes(fmt(ref.lateCents/100,2)+' m'));assert.ok(d.querySelector('[data-root-comparison]').textContent.includes(fmt(ref.error,8)+' m²'));
   input.value='99';check.click();assert.match(status.textContent,/^Noch nicht richtig\./);input.dispatchEvent(new w.Event('input'));assert.equal(status.textContent,'');assert.equal(d.querySelectorAll('[data-root-row]').length,0);d.querySelector('[data-root-show]').click();assert.equal(d.querySelectorAll('[data-root-row]').length,2);models++;}
 }
 for(const raw of ['','-1','101','3m','1e1','NaN','3,4,5','.5']){input.value=raw;check.click();assert.equal(input.getAttribute('aria-invalid'),'true',raw);assert.equal(d.activeElement,input);assert.equal(d.querySelectorAll('[data-root-row]').length,0);}
 d.querySelector('[data-root-reset]').click();assert.equal(d.activeElement.id,'root-area');assert.equal(d.querySelector('#root-area').value,'2');assert.equal(d.querySelector('#root-digits').value,'2');assert.equal(d.querySelector('#root-method').value,'early');input.value='5.64';input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(status.textContent,/^Richtig\./);assert.equal(JSON.stringify(w.localStorage),saved);
 let paths=0;for(const [i,q]of w.currentChapterQuiz.questions.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id],q.id);for(let answer=0;answer<q.answers.length;answer++){w.currentChapterQuiz.questions.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?answer:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,answer===keys[q.id]?100:94);assert.deepEqual(result.reviewQuestionIds,answer===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[answer].feedback));paths++;}}assert.equal(paths,53);
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 assert.equal(pd.querySelectorAll('.root-line svg').length,1);assert.equal(pd.querySelectorAll('.root-paper').length,3);assert.equal(pd.querySelectorAll('[data-root-tasks] li').length,11);assert.equal(pd.querySelectorAll('#ws-solutions [data-root-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);const toggle=pd.getElementById('ws-include-solutions');toggle.checked=true;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,false);
 const verify=(tasks,answers)=>{assert.equal(tasks.length,8);assert.equal(answers.length,8);tasks.forEach((task,i)=>{const a=Number(task.dataset.a),b=Number(task.dataset.b),n=Number(task.dataset.n),kind=Number(task.dataset.kind),expected=kind===0?a+b:kind===1?Math.sqrt(n*2):kind===2?Math.sqrt(n/2):Math.cbrt(n);assert.equal(Number(answers[i].dataset.rootGeneratedAnswer),expected);assert.ok(a>=2&&a<=9&&b>=2&&b<=9);assert.ok(answers[i].textContent.includes('= '+expected));if(kind===3)assert.ok(task.textContent.includes('³√('+n+')'));});};
 verify([...pd.querySelectorAll('[data-root-generated]')],[...pd.querySelectorAll('#ws-solutions [data-root-generated-answer]')]);for(const random of [0,.2,.5,.8,.99999]){pw.Math.random=()=>random;const block=pd.createElement('div');block.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify([...block.querySelectorAll('[data-root-generated]')],[...block.querySelector('template[data-generated-worksheet-solutions]').content.querySelectorAll('[data-root-generated-answer]')]);}
 // Check the published cubic probes against exact integer cubes, not floating-point approximations.
 assert.equal(2714n**3n,19990770344n);assert.equal(3684n**3n,49998717504n);assert.ok(data[id].sections.find(s=>s.id==='m41_cubes').content.includes('49,998717504'));
 paper.window.close();dom.window.close();console.log(`PASS: ${models} rounding cases against bisection/integer reference, feedback/focus/reset/storage, ${paths} quiz paths, 11 tasks, three paper alternatives, four authored and eight generated solutions (plus 40 controlled generated cases).`);
})().catch(e=>{console.error(e);process.exitCode=1;});
