'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
const keys={m44_q1:0,m44_q2:0,m44_dip1:0,function_rental_term:1,function_rental_table:2,function_rental_domain:0,function_slope_ratio:2,function_slope_intercept:0,function_slope_zero:1,function_walk_pause:0,function_walk_return:2,function_walk_total:1,function_unique_table:1,function_unique_conflict:0,function_unique_circle:2,linear_system_q0:0,linear_system_q1:0,linear_system_q2:0,linear_system_q3:0,linear_system_q4:0,linear_system_q5:0};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=math4_4_funktionen_sys',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','system-lab','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/math4_4_funktionen_sys.js'));let injections=0;w.GGBApplet=function(params){assert.ok(params.width>=200);this.inject=id=>{assert.equal(id,'ggb-funktionen');injections++;};};w.topicInit();w.topicInit();assert.equal(injections,0);const disclosure=d.querySelector('.function-optional');disclosure.open=true;disclosure.dispatchEvent(new w.Event('toggle'));assert.equal(injections,1);disclosure.open=false;disclosure.dispatchEvent(new w.Event('toggle'));disclosure.open=true;disclosure.dispatchEvent(new w.Event('toggle'));assert.equal(injections,1);
 assert.equal(w.chapterRevision('math4_4_funktionen_sys'),3);assert.equal(w.currentChapterResult('math4_4_funktionen_sys',{revision:2,passed:true}).passed,false);assert.equal(w.currentChapterQuiz.questions.length,21);assert.equal(d.querySelectorAll('[data-function-tasks] li').length,12);assert.equal(d.querySelectorAll('[data-function-solution]').length,4);
 const saved=JSON.stringify(w.localStorage),set=(id,v,event='change')=>{const el=d.getElementById(id);el.value=String(v);el.dispatchEvent(new w.Event(event));},answer=d.getElementById('function-answer'),out=d.getElementById('function-status');let cases=0;
 for(const m of [-2,-1,-.5,0,.5,1,2])for(const b of [-2,0,1,3])for(const dx of [1,2])for(const x of [-2,0,2,4]){
  set('function-m',m);set('function-b',b);set('function-dx',dx);set('function-x',x);const expected=b+m*x,model=w.functionLineModel(m,b,dx,x);assert.equal(model.y,expected);assert.equal(model.dy/dx,m);assert.equal(answer.value,'');assert.equal(out.textContent,'');
  const rows=[...d.querySelectorAll('[data-function-table] tr')];assert.equal(rows.length,7);rows.forEach((row,i)=>{assert.equal(Number(row.cells[0].textContent),i-2);assert.equal(Number(row.cells[1].textContent.replace(',','.')),b+m*(i-2));});
  const seg=d.querySelector('[data-function-line-segment]');for(const [attr,min,max]of [['x1',52,432],['x2',52,432],['y1',52,374],['y2',52,374]])assert.ok(Number(seg.getAttribute(attr))>=min&&Number(seg.getAttribute(attr))<=max,attr);for(const [xx,yy]of [[-3,'y1'],[5,'y2']])assert.ok(Math.abs((374-Number(seg.getAttribute(yy)))*26/322-12-(m*xx+b))<1e-12);
  answer.value=String(expected).replace('.',',');answer.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(out.textContent,/^Richtig/);assert.equal(d.activeElement,out);answer.value=String(expected+1);d.querySelector('[data-function-check]').click();assert.match(out.textContent,/^Noch nicht/);answer.dispatchEvent(new w.Event('input'));assert.equal(out.textContent,'');cases++;
 }
 for(const bad of ['','1e1','3cm','21','NaN']){answer.value=bad;d.querySelector('[data-function-check]').click();assert.equal(answer.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,answer);}d.querySelector('[data-function-reset]').click();assert.equal(d.activeElement.id,'function-m');assert.equal(d.getElementById('function-m').value,'2');assert.equal(answer.getAttribute('aria-invalid'),null);
 const waypoints=[[0,0],[2,120],[4,120],[8,0]];for(let t=0;t<=8;t+=.25){const i=t<=2?0:t<=4?1:2,[ta,sa]=waypoints[i],[tb,sb]=waypoints[i+1],expected=sa+(sb-sa)*(t-ta)/(tb-ta);assert.equal(w.functionWalkValue(t),expected);}assert.equal(w.functionWalkValue(-1),null);assert.equal(w.functionWalkValue(9),null);
 for(let t=0;t<=8;t++){set('function-time',t,'input');const a=d.getElementById('walk-answer'),o=d.getElementById('walk-status'),expected=[0,60,120,120,120,90,60,30,0][t];a.value=String(expected);a.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(o.textContent,/^Richtig/);assert.equal(d.activeElement,o);const p=d.querySelector('[data-walk-point]');assert.equal(Number(p.getAttribute('cx')),65+44*t);assert.equal(Number(p.getAttribute('cy')),300-1.65*expected);a.value=String(expected+1);d.querySelector('[data-walk-check]').click();assert.match(o.textContent,/^Noch nicht/);a.dispatchEvent(new w.Event('input'));assert.equal(o.textContent,'');}
 for(const bad of ['','-1','201','1e2','40m']){d.getElementById('walk-answer').value=bad;d.querySelector('[data-walk-check]').click();assert.equal(d.getElementById('walk-answer').getAttribute('aria-invalid'),'true');}d.querySelector('[data-walk-reset]').click();assert.equal(d.activeElement.id,'function-time');assert.equal(d.getElementById('function-time').value,'5');assert.equal(JSON.stringify(w.localStorage),saved);
 let paths=0;for(const [i,q]of w.currentChapterQuiz.questions.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let answer=0;answer<q.answers.length;answer++){w.currentChapterQuiz.questions.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?answer:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results')).math4_4_funktionen_sys;assert.equal(result.lastPercent,answer===keys[q.id]?100:95);assert.deepEqual(result.reviewQuestionIds,answer===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[answer].feedback));paths++;}}
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=math4_4_funktionen_sys',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.function-paper').length,4);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,3);assert.equal(pd.querySelectorAll('#ws-solutions [data-function-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);
 const verify=(tasks,solutions)=>{assert.equal(tasks.length,8);assert.equal(solutions.length,8);tasks.forEach((task,i)=>{const a=solutions[i];if(task.dataset.kind==='line'){assert.equal(a.dataset.m,task.dataset.m);assert.equal(a.dataset.b,task.dataset.b);assert.ok(a.textContent.includes('Δx = 3 − (−1) = 4'));}else{const x=Number(a.dataset.x),y=Number(a.dataset.y);assert.equal(Number(task.dataset.a)*x+Number(task.dataset.b)*y,Number(task.dataset.r1));assert.equal(x-y,Number(task.dataset.r2));assert.ok(a.textContent.includes('x = '+x));}});};
 verify([...pd.querySelectorAll('[data-function-generated]')],[...pd.querySelectorAll('[data-function-generated-answer]')]);for(const rand of [0,.25,.5,.75,.99999]){pw.Math.random=()=>rand;const box=pd.createElement('div');box.innerHTML=pw.generateWorksheetContent('math4_4_funktionen_sys','Funktionen');verify([...box.querySelectorAll('[data-function-generated]')],[...box.querySelector('template[data-generated-worksheet-solutions]').content.querySelectorAll('[data-function-generated-answer]')]);}
 assert.equal(cases,224);assert.equal(paths,60);paper.window.close();dom.window.close();console.log('PASS: 224 line answers, plotted endpoints/tables, 33 interpolated time values, nine DOM time cases, 60 graded answer paths, focus/reset/storage; four paper alternatives, three static graphs and eight generated task/solution pairs plus 40 controlled cases.');
})().catch(e=>{console.error(e);process.exitCode=1;});
