const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),data=JSON.parse(read('lang/de.json'));
function page(id,review=false,plan){const dom=new JSDOM('<div id="sections-container"></div>',{url:'https://example.test/physik_bay6/topics/template.html?topic='+id+(review?'&mode=review':''),runScripts:'outside-only'}),w=dom.window;if(plan!==undefined)w.localStorage.setItem('sciverse_study_plan',JSON.stringify(plan));w.eval(read('js/curriculum.js'));w.eval(read('js/core-learning.js'));w.enhanceCoreLearning(data[id],id,'de');return dom;}
for(const [id,expected]of [['sieinheiten',['optik1']],['elektrizitaet',['energie','elektromagnetismus']],['rechenbeispiele',['astronomie']]]){const dom=page(id),links=[...dom.window.document.querySelectorAll('[data-chapter-continuation] li a')];assert.deepEqual(links.map(a=>a.hash.slice(1)),expected);for(const a of links){assert.match(a.href,/\/physik_bay6\/index.html#/);assert.equal(a.target,'_top');}dom.window.close();}
const dom=page('elektrizitaet',true,['geo_3_europa','elektrizitaet','unknown','elektrizitaet','waermelehre']),w=dom.window;
assert.deepEqual([...w.document.querySelectorAll('[data-chapter-continuation] li a')].map(a=>a.hash),['#topics/template.html?topic=geo_3_europa&mode=review&plan=geo_3_europa%2Celektrizitaet%2Cwaermelehre','#topics/template.html?topic=waermelehre&mode=review&plan=geo_3_europa%2Celektrizitaet%2Cwaermelehre']);w.enhanceCoreLearning(data.elektrizitaet,'elektrizitaet','de');assert.equal(w.document.querySelectorAll('[data-chapter-continuation]').length,1);dom.window.close();
for(const plan of [undefined,{},['energie']]){const dom=page('elektrizitaet',true,plan);assert.equal(dom.window.document.querySelectorAll('[data-chapter-continuation]').length,0);dom.window.close();}
const full=page('sieinheiten');for(const [subject,s]of Object.entries(full.window.SCIVERSE_CURRICULUM)){s.topics.forEach((t,index)=>{for(const prerequisite of data[t.id]?.prerequisites||[]){const prior=s.topics.findIndex(t=>t.id===prerequisite);assert.ok(prior<index,subject+': '+t.id+' requires later chapter '+prerequisite);}});}full.window.close();
console.log('PASS: first/middle/last chapter routes, no cross-subject learning jumps, selected review order across subjects, invalid plans, no duplicate navigation and all same-subject prerequisites precede their chapters.');
