'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),id='bio_3_kladogramme';
const keys={s1:[0,0],d1:[2,0],s2:[1,1],d2:[0,1],d4:[2,1],s3:[1,2],fehlend:[0,2],konflikt:[2,2],s4:[1,3],d3:[2,3]};
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 assert.equal(data[id].sources.length,4);assert.ok(data[id].sources.every(s=>typeof s.title==='string'&&s.title.length>5&&s.url.startsWith('https://')));
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-cladogram-evidence]'),dataset=zone.querySelector('[data-clad-data]'),model=zone.querySelector('[data-clad-model]'),reason=zone.querySelector('[data-clad-reason]'),check=zone.querySelector('[data-clad-check]'),reset=zone.querySelector('[data-clad-reset]'),result=zone.querySelector('[data-clad-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.modelCorrect,undefined);assert.equal(result.dataset.reasonCorrect,undefined);};
 const expectations={base:['none','shared',[[0,'?','?'],[1,'?','?'],[1,'?','?'],[1,'?','?']]],bc:['bc','y',[[0,0,'?'],[1,0,'?'],[1,1,'?'],[1,1,'?']]],ab:['ab','z',[[0,'?',0],[1,'?',1],[1,'?',1],[1,'?',0]]],conflict:['none','conflict',[[0,0,0],[1,0,1],[1,1,1],[1,1,0]]]};let count=0;
 for(const [mode,[answer,why,matrix]]of Object.entries(expectations)){
  set(dataset,mode);assert.equal(model.value,'');assert.equal(reason.value,'');assert.deepEqual([...zone.querySelectorAll('[data-clad-matrix] tbody tr')].map(r=>[...r.querySelectorAll('td')].map(c=>c.textContent)),matrix.map(row=>row.map(String)));
  for(const m of ['bc','ab','ac','none'])for(const r of ['shared','y','z','conflict']){set(model,m);set(reason,r);check.click();assert.equal(result.dataset.modelCorrect,String(m===answer));assert.equal(result.dataset.reasonCorrect,String(r===why));assert.equal(d.activeElement,result);assert.equal(result.children.length,3);if(mode==='base')assert.match(result.textContent,/fehlende Information/);if(mode==='conflict')assert.match(result.textContent,/Kein vorgeschlagener Baum/);count++;}
 }
 reset.click();check.click();assert.equal(result.dataset.invalid,'model');assert.equal(d.activeElement,model);set(model,'bc');check.click();assert.equal(result.dataset.invalid,'reason');assert.equal(d.activeElement,reason);set(dataset,'');check.click();assert.equal(result.dataset.invalid,'data');assert.equal(d.activeElement,dataset);reset.click();assert.equal(dataset.value,'base');assert.equal(model.value,'');assert.equal(reason.value,'');assert.equal(d.activeElement,dataset);assert.equal(JSON.stringify(w.localStorage),storage);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('[data-clad-solution]').length,4);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id.replace(id+'_',''))),new Set(Object.keys(keys)));
 for(const [i,q]of qs.entries()){const [key,section]=keys[q.id.replace(id+'_','')];assert.equal(q.answers.findIndex(a=>a.correct),key);assert.equal(q.sectionIndex,section);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id.replace(id+'_','')][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===key?100:90);assert.deepEqual(r.reviewQuestionIds,choice===key?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.ok(practice[0].answers.every(a=>a.pts===0));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-clad-paper]').length,1);assert.equal(pd.querySelectorAll('[data-clad-rotation-paper]').length,1);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,4);assert.equal(pd.querySelectorAll('.clad-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('#ws-solutions [data-clad-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-clad-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);paper.window.close();
 console.log(`PASS: ${count} independently checked model/reason combinations, four matrices, stale/invalid/reset/focus/storage, 30 quiz answers, 12 direct tasks, source titles and two complete paper alternatives.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
