const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb5_orientierung',keys=require('./fixtures/dgb5_orientation_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/dgb5_orientierung.js'));w.topicInit();w.topicInit();
 const storage=JSON.stringify(w.localStorage),value=d.getElementById('eva-value'),limit=d.getElementById('eva-limit'),step=d.querySelector('[data-eva-step]'),reset=d.querySelector('[data-eva-reset]');
 let evaRuns=0;for(const boundary of [30,50,70])for(let n=0;n<=100;n++){
  value.value=String(n);value.dispatchEvent(new w.Event('input'));limit.value=String(boundary);limit.dispatchEvent(new w.Event('change'));
  assert.equal(d.querySelector('[data-eva-output]').textContent,'Noch nicht ausgeführt.');step.click();assert.match(d.querySelector('[data-eva-input]').textContent,new RegExp(' '+n+'\\.'));assert.equal(d.querySelector('[data-eva-process]').textContent,'Noch nicht ausgeführt.');
  step.click();assert.ok(d.querySelector('[data-eva-process]').textContent.includes(n<boundary?'ist wahr':'ist falsch'));assert.equal(d.querySelector('[data-eva-output]').textContent,'Noch nicht ausgeführt.');step.focus();step.click();assert.equal(d.querySelector('[data-eva-output]').textContent,n<boundary?'Modellleuchte: AN.':'Modellleuchte: AUS.');assert.equal(step.disabled,true);assert.equal(d.activeElement,reset);evaRuns++;
 }
 for(const invalid of ['', '-1','101','1.5']){value.value=invalid;value.dispatchEvent(new w.Event('input'));step.click();assert.equal(value.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,value);assert.equal(d.querySelector('[data-eva-input]').textContent,'Noch nicht ausgeführt.');}
 reset.click();assert.equal(value.value,'49');assert.equal(limit.value,'50');assert.equal(d.activeElement,value);assert.equal(value.hasAttribute('aria-invalid'),false);step.click();value.value='80';value.dispatchEvent(new w.Event('input'));assert.equal(d.querySelector('[data-eva-input]').textContent,'Noch nicht ausgeführt.');
 const temperature=d.getElementById('representation-value'),precision=d.getElementById('representation-step'),display=d.querySelector('[data-representation-digital]');let views=0;
 // Independent intervals fixed by the lesson's half-up rule, including both endpoints.
 const bins=[[180,184,18],[185,194,19],[195,204,20],[205,214,21],[215,224,22],[225,234,23],[235,240,24]];
 for(const [low,high,expected]of bins)for(let n=low;n<=high;n++){
  temperature.value=String(n);temperature.dispatchEvent(new w.Event('input'));precision.value='10';precision.dispatchEvent(new w.Event('change'));assert.equal(display.textContent,expected+' °C');
  precision.value='1';precision.dispatchEvent(new w.Event('change'));assert.equal(display.textContent,(n/10).toFixed(1).replace('.',',')+' °C');assert.match(temperature.getAttribute('aria-valuetext'),/Grad Celsius/);views+=2;
 }
 for(const [n,y,height]of [[180,230,15],[210,140,105],[240,50,195]]){temperature.value=String(n);temperature.dispatchEvent(new w.Event('input'));assert.equal(d.querySelector('[data-representation-column]').getAttribute('y'),String(y));assert.equal(d.querySelector('[data-representation-column]').getAttribute('height'),String(height));assert.equal(d.querySelector('[data-representation-marker]').getAttribute('y1'),String(y));}
 d.querySelector('[data-representation-reset]').click();assert.equal(temperature.value,'214');assert.equal(precision.value,'10');assert.equal(display.textContent,'21 °C');assert.equal(d.activeElement,temperature);
 const lab=d.querySelector('[data-orientation-cases]'),control=lab.querySelector('select'),cards=[...lab.querySelectorAll('[data-boundary-case]')],status=lab.querySelector('[role=status]');
 for(const [i,key]of [1,2].entries()){control.value=String(i);control.dispatchEvent(new w.Event('change'));assert.equal(cards.filter(c=>!c.hidden).length,1);for(let a=0;a<3;a++){cards[i].querySelectorAll('button')[a].click();assert.equal(status.textContent.startsWith('Richtig:'),a===key);}}
 lab.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.equal(JSON.stringify(w.localStorage),storage);
 const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);assert.equal(d.querySelectorAll('[data-orientation-tasks]>li').length,16);assert.equal(d.querySelectorAll('[data-media-change-task]>li').length,4);assert.equal(d.querySelectorAll('[data-media-day] tbody tr').length,5);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));assert.deepEqual(Array.from(qs,q=>q.sectionIndex),[0,0,0,1,1,2,3,3]);for(const [i,q]of qs.entries())for(let a=0;a<3;a++){qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:88);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));}
 assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).outdated,true);const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[0,2,1]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));assert.equal(evaRuns,303);assert.equal(views,122);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-eva-paper] tbody tr').length,5);assert.equal(material.querySelectorAll('[data-representation-paper] tbody tr').length,3);assert.equal(material.querySelectorAll('[data-orientation-case-paper] .ai-paper-case').length,2);assert.equal(material.querySelectorAll('[data-orientation-tasks]>li').length,16);assert.equal(material.querySelectorAll('[data-media-change-task]>li').length,4);assert.equal(material.querySelectorAll('button,input,select,[data-orientation-solution],[data-media-change-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-orientation-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions .ws-paper-solution').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,8);paper.window.close();
 console.log('PASS: 303 stepped EVA runs, invalid/reset/focus/re-init cases, 122 rounding views and scale endpoints, six media decisions, 24 independent quiz paths, 20 tasks and four separate paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
