const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='bio_2_zellen';
const correct={bio2_zelle_s1:0,bio2_zelle_s2:0,bio2_zelle_s3:0,bio2_zelle_s4:0,bio2_zelle_s5:0,bio2_zelle_d1:0,bio2_zelle_d2:0,bio2_zelle_d3:0,bio2_zelle_d4:0,bio2_zelle_d5:0,bio2_zelle_massstab:1,bio2_zelle_modellbefund:2};
const section={bio2_zelle_s1:0,bio2_zelle_s2:1,bio2_zelle_s3:2,bio2_zelle_s4:3,bio2_zelle_s5:4,bio2_zelle_d1:1,bio2_zelle_d2:2,bio2_zelle_d3:3,bio2_zelle_d4:2,bio2_zelle_d5:1,bio2_zelle_massstab:3,bio2_zelle_modellbefund:4};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/bio_2_zellen'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')),texts=doc=>[...doc.querySelectorAll('.bio-training-card')].map(e=>e.textContent);assert.equal(texts(d).length,15);assert.deepEqual(texts(d),texts(authored.window.document));authored.window.close();
 const z=d.querySelector('[data-cell-comparison]'),select=z.querySelector('select'),saved=JSON.stringify(w.localStorage);
 for(const kind of ['leaf','root','animal']){
  select.value=kind;select.dispatchEvent(new w.Event('change'));assert.equal(z.querySelectorAll('[data-cell-view]:not([hidden])').length,1);const svg=z.querySelector('[data-cell-view="'+kind+'"] svg');assert.equal(svg.closest('figure').hidden,false);
  for(const part of ['membrane','nucleus','mitochondria'])assert.equal(svg.querySelectorAll('[data-cell-shape="'+part+'"]').length,1);
  for(const part of ['wall','vacuole'])assert.equal(svg.querySelectorAll('[data-cell-shape="'+part+'"]').length,kind==='animal'?0:1);
  assert.equal(svg.querySelectorAll('[data-cell-shape="chloroplasts"]').length,kind==='leaf'?3:0);
  const rows=[...z.querySelectorAll('tbody tr')];assert.equal(rows.length,7);const yes=rows.filter(r=>r.querySelector('td').textContent==='Ja').map(r=>r.dataset.cellPart);assert.deepEqual(yes,kind==='leaf'?['membrane','plasma','nucleus','mitochondria','wall','vacuole','chloroplasts']:kind==='root'?['membrane','plasma','nucleus','mitochondria','wall','vacuole']:['membrane','plasma','nucleus','mitochondria']);
  for(const e of svg.querySelectorAll('[data-cell-shape]')){if(e.tagName==='circle'){assert.ok(Number(e.getAttribute('cx'))-Number(e.getAttribute('r'))>=28);assert.ok(Number(e.getAttribute('cx'))+Number(e.getAttribute('r'))<=292);}if(e.dataset.cellShape==='vacuole'){assert.ok(Number(e.getAttribute('x'))>28);assert.ok(Number(e.getAttribute('x'))+Number(e.getAttribute('width'))<292);}}
 }
 w.topicInit();assert.equal(select.value,'animal');z.querySelector('[data-cell-reset]').click();assert.equal(select.value,'leaf');assert.equal(d.activeElement,select);assert.equal(JSON.stringify(w.localStorage),saved);
 const scale=d.querySelector('[data-cell-scale]'),outline=scale.querySelector('[data-cell-outline]'),bar=scale.querySelector('[data-cell-scale-bar]');assert.equal(Number(outline.getAttribute('width'))/(Number(bar.getAttribute('x2'))-Number(bar.getAttribute('x1'))),4);assert.match(scale.textContent,/50 µm/);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,12);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(correct).sort());let paths=0;
 for(const [i,q]of qs.entries()){assert.equal(q.sectionIndex,section[q.id]);for(let choice=0;choice<3;choice++){
  qs.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?choice:correct[item.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,choice===correct[q.id]?100:92);assert.deepEqual(result.reviewQuestionIds,choice===correct[q.id]?[]:[q.id]);assert.equal(result.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;
 }}
 assert.equal(paths,36);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const m=pw.document.getElementById('ws-biology-material'),s=pw.document.getElementById('ws-solutions');assert.equal(m.querySelectorAll('article').length,5);assert.equal(m.querySelectorAll('.bio-training-card').length,15);assert.equal(m.querySelectorAll('.ws-glossary-entry').length,21);assert.equal(m.querySelectorAll('[data-cell-protocol] tbody tr').length,7);assert.equal(m.querySelectorAll('[data-cell-paper] figure').length,3);assert.equal(m.querySelectorAll('svg[data-worksheet-static]').length,5);assert.equal(m.querySelectorAll('select,button,input,[data-cell-view]').length,0);assert.equal(s.querySelectorAll('.ws-paper-solution').length,2);assert.equal(s.hidden,true);assert.match(s.textContent,/200 µm = 0,2 mm/);assert.ok(!m.textContent.includes('4 × 50 µm = 200 µm'));paper.window.close();
 console.log('PASS: cell learning: 36 independently keyed paths, section/revision, 15 preserved tasks, three diagrams with matching presence tables, shape checks, reset/focus/no storage, independent 4:1 scale, five paper diagrams, seven-row protocol, 21 glossary entries and separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
