'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),data=JSON.parse(read('lang/de.json')),id='math3_2_potenzen_terme';
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const file of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+file+'.js'));await w.renderTopic();w.topicInit();
 const lab=d.querySelector('[data-sci-lab]'),q=s=>lab.querySelector(s),saved=JSON.stringify(w.localStorage),select=(s,v)=>{q(s).value=String(v);q(s).dispatchEvent(new w.Event('change'));},input=(s,v)=>{q(s).value=String(v);q(s).dispatchEvent(new w.Event('input'));},check=()=>q('[data-sci-check]').click();
 assert.equal(lab.dataset.bound,'true');assert.equal(q('#sci-case').options.length,52);let cases=0;
 for(const direction of ['decimal','scientific'])for(let i=0;i<52;i++){
  select('#sci-direction',direction);select('#sci-case',i);const a=[-4.2,1,2.5,9.6][Math.floor(i/13)],n=i%13-6,expected=Number((a*10**n).toFixed(8)),m=w.sciverseScientificModel(i);
  assert.equal(Number(m.decimal),expected);assert.equal(m.exponent,n);assert.equal(m.coefficient,a);assert.ok(!m.decimal.includes('e'));assert.equal(m.steps.length,Math.abs(n)+1);for(const step of m.steps)assert.equal(Number(step.decimal),Number((a*10**step.exponent).toFixed(8)));
  if(direction==='decimal'){assert.ok(q('[data-sci-scientific-fields]').hidden);input('#sci-decimal',m.decimal.replace('.',','));}else{assert.ok(q('[data-sci-decimal-field]').hidden);input('#sci-a',String(a).replace('.',','));input('#sci-n',n);}
  check();assert.match(q('#sci-status').textContent,/^Richtig:/);q('[data-sci-show]').click();assert.equal(q('[data-sci-steps]').hidden,false);assert.equal(q('[data-sci-steps] tbody').rows.length,Math.abs(n)+1);assert.ok(q('[data-sci-steps]').textContent.includes(m.decimal.replace('.',',').replace('-','−')));cases++;
 }
 select('#sci-direction','decimal');select('#sci-case',35);for(const bad of ['', ' ', '2e3','Infinity','NaN','2,5,0','2 500','2500xyz']){input('#sci-decimal',bad);check();assert.match(q('#sci-status').textContent,/^Gib eine/);}
 input('#sci-decimal','250');check();assert.match(q('#sci-status').textContent,/^Noch nicht/);input('#sci-decimal','2500');assert.equal(q('#sci-status').textContent,'');q('#sci-decimal').focus();q('#sci-decimal').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(q('#sci-status').textContent,/^Richtig:/);assert.equal(d.activeElement,q('#sci-decimal'));
 select('#sci-direction','scientific');for(const [av,nv,message]of [['25','2','Der Vorfaktor'],['.25','4','Gib einen'],['2,5','3.1','Gib einen'],['2,5','-3','Noch nicht'],['2,5','3','Richtig']]){input('#sci-a',av);input('#sci-n',nv);check();assert.ok(q('#sci-status').textContent.startsWith(message));}
 q('[data-sci-show]').click();select('#sci-case',0);assert.equal(q('[data-sci-steps]').hidden,true);assert.equal(q('#sci-a').value,'');q('[data-sci-reset]').click();assert.equal(q('#sci-case').value,'35');assert.equal(q('#sci-direction').value,'decimal');assert.equal(d.activeElement,q('#sci-direction'));assert.equal(JSON.stringify(w.localStorage),saved);w.topicInit();assert.equal(q('#sci-case').value,'35');assert.equal(w.sciverseScientificModel(-1),null);assert.equal(w.sciverseScientificModel(52),null);assert.equal(w.sciverseScientificModel(1.5),null);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const file of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+file+'.js'));await new Promise(r=>setImmediate(r));
 assert.equal(pd.querySelectorAll('[data-sci-tasks]>li').length,6);assert.equal(pd.querySelectorAll('[data-sci-paper]').length,1);assert.equal(pd.querySelectorAll('#ws-math-material input,#ws-math-material select,#ws-math-material button').length,0);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,8);assert.equal(pd.querySelectorAll('#ws-solutions [data-sci-answer]').length,4);
 let generated=0;function verify(tasks,answers){assert.equal(tasks.length,4);assert.equal(answers.length,4);for(let i=0;i<4;i++){const t=tasks[i],a=answers[i],expected=Number((Number(t.dataset.coefficient)*10**Number(t.dataset.exponent)).toFixed(8));assert.equal(Number(a.dataset.sciAnswer),expected);assert.ok(a.textContent.includes(expected.toLocaleString('de-AT',{useGrouping:false,maximumFractionDigits:10})));assert.ok(t.textContent.includes('A'+(i+9)));assert.ok(a.textContent.includes('A'+(i+9)));generated++;}}
 verify(pd.querySelectorAll('[data-sci-generated]'),pd.querySelectorAll('#ws-solutions [data-sci-answer]'));
 for(const seed of [0,.25,.5,.75,.99999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify(host.querySelectorAll('[data-sci-generated]'),host.querySelector('template').content.querySelectorAll('[data-sci-answer]'));}
 const before=Array.from(pd.querySelectorAll('[data-sci-generated]'),e=>e.textContent),toggle=pd.getElementById('ws-include-solutions');for(const value of [true,false,true]){toggle.checked=value;toggle.dispatchEvent(new pw.Event('change'));assert.deepEqual(Array.from(pd.querySelectorAll('[data-sci-generated]'),e=>e.textContent),before);}paper.window.close();console.log(`PASS: scientific notation: ${cases} conversions, exact decimal text, invalid input, Enter/focus/reset/no storage, paper alternative and ${generated} matched generated tasks.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
