'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),data=JSON.parse(read('lang/de.json')),id='math2_4_relative_zahlen';
const keys={m24_q1:0,m24_dip1:0,m24_reference:1,m24_q2:0,m24_dip2:0,m24_no_steps:2,m24_six_thirds:0,m24_negative_domain:2,m24_decimal_integer:1,m24_integer_neighbor:1,m24_zero_predecessor:0,m24_fraction_successor:2,m24_between_value:0,m24_between_whole:2,m24_midpoint:1,m24_same_point:1,m24_third_exact:0,m24_decimal_zero:2};
const flags=[[true,true,true],[true,true,true],[false,true,false],[false,false,true],[true,true,true],[false,false,true],[true,true,true],[true,true,true],[false,false,true],[false,true,false],[false,false,true],[true,true,true]],values=[[0,1],[4,1],[-4,1],[1,2],[2,1],[1,2],[2,1],[0,1],[7,4],[-12,1],[1,3],[1,1]],intervals=[[[0,1],[1,1]],[[3,1],[4,1]],[[1,2],[3,4]],[[1,3],[1,2]],[[2,5],[3,5]],[[1,1],[3,2]],[[7,4],[2,1]],[[1,10],[1,5]],[[4,1],[5,1]],[[0,1],[1,1000]],[[999,1000],[1,1]],[[5,6],[1,1]]];
const gcd=(a,b)=>{a=Math.abs(a);while(b){const r=a%b;a=b;b=r;}return a;},less=(a,b)=>a.n*b.d<b.n*a.d;
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();w.topicInit();const q=s=>d.querySelector(s),saved=JSON.stringify(w.localStorage),select=q('#number-class-case'),boxes=[...d.querySelectorAll('[data-number-classify] input')],classOut=q('[data-number-class-status]');assert.equal(select.options.length,12);let classifications=0,bisections=0;
for(let i=0;i<12;i++){const m=w.numberClassModel(i);assert.deepEqual(Array.from(m.flags),flags[i]);assert.equal(m.n,values[i][0]);assert.equal(m.d,values[i][1]);select.value=String(i);select.dispatchEvent(new w.Event('change'));assert.ok(boxes.every(b=>!b.checked));for(let mask=0;mask<8;mask++){boxes.forEach((b,j)=>b.checked=Boolean(mask&(1<<j)));q('[data-number-class-check]').click();const correct=boxes.every((b,j)=>b.checked===flags[i][j]);assert.equal(classOut.textContent.startsWith('Richtig:'),correct);assert.ok(classOut.textContent.includes(m.explanation));classifications++;}boxes[0].dispatchEvent(new w.Event('change'));assert.equal(classOut.textContent,'');}q('[data-number-class-reset]').click();assert.equal(select.value,'4');assert.equal(d.activeElement,select);
const sel=q('#number-between-case'),n=q('#number-between-n'),den=q('#number-between-d'),out=q('[data-number-between-status]'),stepButton=q('[data-number-between-step]');assert.equal(sel.options.length,12);
for(let i=0;i<12;i++){sel.value=String(i);sel.dispatchEvent(new w.Event('change'));assert.equal(stepButton.disabled,false);assert.equal(d.querySelectorAll('[data-number-between-history] li').length,0);let prev=null;for(let step=1;step<=6;step++){const m=w.numberBetweenModel(i,step),h=m.current,[[an,ad],[bn,bd]]=intervals[i];assert.equal(m.a.n*ad,an*m.a.d);assert.equal(m.b.n*bd,bn*m.b.d);assert.ok(less(h.left,h.mid)&&less(h.mid,h.right));assert.equal(2*h.mid.n*h.left.d*h.right.d,(h.left.n*h.right.d+h.right.n*h.left.d)*h.mid.d);assert.equal(gcd(h.mid.n,h.mid.d),1);if(prev){assert.equal(h.right.n,prev.n);assert.equal(h.right.d,prev.d);}prev=h.mid;stepButton.click();assert.equal(d.querySelectorAll('[data-number-between-history] li').length,step);assert.ok(q('[data-number-between-view]').textContent.includes(w.numberRangeLabel(h.mid)));assert.match(out.textContent,/liegt strikt/);bisections++;}assert.equal(stepButton.disabled,true);assert.equal(d.activeElement,q('[data-number-between-reset]'));assert.match(out.textContent,/mathematisch.*immer fortsetzen/);
 const m=w.numberBetweenModel(i,0),candidates=[{n:m.a.n*m.b.d+m.b.n*m.a.d,d:2*m.a.d*m.b.d},{n:2*m.a.n*m.b.d+m.b.n*m.a.d,d:3*m.a.d*m.b.d}];for(const c of candidates){const g=gcd(c.n,c.d);n.value=String(c.n/g);den.value=String(c.d/g);den.focus();den.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.match(out.textContent,/^Richtig:/);assert.equal(d.activeElement,den);}for(const edge of [m.a,m.b]){n.value=String(edge.n);den.value=String(edge.d);q('[data-number-between-check]').click();assert.match(out.textContent,/^Noch nicht/);}n.dispatchEvent(new w.Event('input'));assert.equal(out.textContent,'');}
for(const [a,b]of [['',''],['1','0'],['-1','2'],['1.5','2'],['1e0','2'],['1','1000000']]){n.value=a;den.value=b;q('[data-number-between-check]').click();assert.match(out.textContent,/^Gib einen/);}q('[data-number-between-reset]').click();assert.equal(sel.value,'2');assert.equal(d.activeElement,sel);assert.equal(stepButton.disabled,false);assert.equal(d.querySelectorAll('[data-number-between-history] li').length,0);
for(const bad of [-1,12,1.5,'1',NaN]){assert.equal(w.numberClassModel(bad),null);assert.equal(w.numberBetweenModel(bad,0),null);}for(const bad of [-1,7,1.5,'1',NaN])assert.equal(w.numberBetweenModel(0,bad),null);
let movements=0;for(const s of [-10,-1,0,1,10])for(const n of [0,1,10])for(const direction of ['plus','minus']){q('#integer-start').value=String(s);q('#integer-steps').value=String(n);q('#integer-direction').value=direction;q('[data-integer-run]').click();const end=s+(direction==='plus'?n:-n),min=Math.min(s,end,0)-1,max=Math.max(s,end,0)+1,x=a=>25+(a-min)*280/(max-min);assert.equal(Number(q('[data-integer-origin]').getAttribute('cx')),x(s));assert.equal(Number(q('[data-integer-end]').getAttribute('x'))+4,x(end));assert.equal(d.querySelectorAll('[data-integer-arrow]').length,n?1:0);movements++;}q('[data-integer-reset]').click();assert.equal(q('#integer-start').value,'3');assert.equal(q('#integer-steps').value,'5');assert.equal(d.activeElement,q('#integer-start'));assert.equal(q('[data-integer-figure]').hidden,true);assert.equal(JSON.stringify(w.localStorage),saved);
const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,18);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;for(const [i,item]of qs.entries()){assert.equal(item.sectionIndex,Math.floor(i/3));for(let a=0;a<3;a++){assert.equal(item.answers[a].correct,a===keys[item.id]);qs.forEach((q,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?a:keys[q.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[item.id]?100:94);assert.deepEqual(result.reviewQuestionIds,a===keys[item.id]?[]:[item.id]);assert.equal(result.contentRevision,2);assert.ok(q('#chapter-quiz-result').textContent.includes(item.answers[a].feedback));paths++;}}assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:1}).passed,false);dom.window.close();
const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('#ws-math-material article').length,6);assert.equal(pd.querySelectorAll('[data-number-range-tasks]>li').length,19);assert.equal(pd.querySelectorAll('[data-number-range-paper]').length,3);assert.equal(pd.querySelectorAll('#ws-math-material svg').length,3);assert.equal(pd.querySelectorAll('#ws-math-material input,#ws-math-material button,#ws-math-material select').length,0);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,6);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,18);
function verify(host,solution){const tasks=host.querySelectorAll('[data-number-range-generated]'),answers=solution.querySelectorAll('[data-number-range-answer]');assert.equal(tasks.length,12);assert.equal(answers.length,12);for(let i=0;i<12;i++){const t=tasks[i],a=Number(t.dataset.a),b=Number(t.dataset.b),c=Number(t.dataset.c),dd=Number(t.dataset.d),kind=t.dataset.numberRangeGenerated,value=answers[i].dataset.numberRangeAnswer;if(kind==='add'||kind==='subtract'){assert.ok(b>=0);assert.equal(Number(value),kind==='add'?a+b:a-b);}else if(kind==='neighbors'){assert.equal(value,(a-1)+';'+(a+1));}else{const[n,d]=value.split('/').map(Number);assert.equal(gcd(n,d),1);if(kind==='between'){assert.ok(n*b>a*d&&n*dd<c*d);assert.equal(2*n*b*dd,(a*dd+c*b)*d);}else{assert.equal(kind,'equivalent');assert.equal(n*b,a*d);}}}}
verify(pd,pd.getElementById('ws-solutions'));for(const seed of [0,.5,.99999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify(host,host.querySelector('template').content);}const before=Array.from(pd.querySelectorAll('[data-number-range-generated]'),e=>e.textContent);for(const checked of [true,false,true]){pd.getElementById('ws-include-solutions').checked=checked;pd.getElementById('ws-include-solutions').dispatchEvent(new pw.Event('change'));assert.deepEqual(Array.from(pd.querySelectorAll('[data-number-range-generated]'),e=>e.textContent),before);}paper.window.close();console.log('PASS: number ranges: '+classifications+' classification paths, '+bisections+' exact bisections, 24 valid intermediate fractions, '+movements+' movement drawings, '+paths+' keyed quiz paths; six-section paper, three figures/alternatives, six solutions and 48 generated tasks.');
})().catch(e=>{console.error(e);process.exitCode=1;});
