const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),data=JSON.parse(read('lang/de.json'));
// Counts and ratios are authored independently from the runtime reaction definitions.
const species={methane:[['CH4',{C:1,H:4}],['O2',{O:2}],['CO2',{C:1,O:2}],['H2O',{H:2,O:1}]],hydrogen:[['H2',{H:2}],['O2',{O:2}],['H2O',{H:2,O:1}]],peroxide:[['H2O2',{H:2,O:2}],['H2O',{H:2,O:1}],['O2',{O:2}]]};
const correct={methane:[1,2,1,2],hydrogen:[2,1,2],peroxide:[2,2,1]},sideLength={methane:2,hydrogen:2,peroxide:1};
const expected=(key,[a,b,c,d])=>key==='methane'?{left:{C:a,H:4*a,O:2*b},right:{C:c,H:2*d,O:2*c+d},ok:a>0&&c===a&&b===2*a&&d===2*a,factor:a}:key==='hydrogen'?{left:{H:2*a,O:2*b},right:{H:2*c,O:c},ok:b>0&&a===2*b&&c===2*b,factor:b}:{left:{H:2*a,O:2*a},right:{H:2*b,O:b+2*c},ok:c>0&&a===2*c&&b===2*c,factor:c};
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/physik_bay6/topics/template.html?topic=chemie_reaktionen_energie',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/chemie_common.js'));w.ChemieLabs.topicInit();const calc=w.ChemieLabs.reactionBalance,lab=d.querySelector('[data-chem-lab="reaction-builder"]'),inputs=[...lab.querySelectorAll('[data-chem-coeff]')],status=lab.querySelector('.chem-status'),storage=JSON.stringify(w.localStorage);let balances=0,balanced=0,drawings=0;
assert.equal(lab.dataset.chemReaction,'hydrogen');assert.equal(inputs[3].disabled,true);
for(const key of Object.keys(species))for(let a=0;a<=9;a++)for(let b=0;b<=9;b++)for(let c=0;c<=9;c++)for(let dd=0;dd<=(key==='methane'?9:0);dd++){
 const coeff=[a,b,c,dd],e=expected(key,coeff),actual=calc(key,{a,b,c,d:dd});assert.deepEqual(JSON.parse(JSON.stringify(actual.left)),e.left);assert.deepEqual(JSON.parse(JSON.stringify(actual.right)),e.right);assert.equal(actual.balanced,e.ok);assert.equal(actual.factor,e.ok?e.factor:null);balances++;if(e.ok)balanced++;
}
assert.equal(balances,12000);assert.equal(balanced,12);for(const key of ['missing','toString','__proto__'])assert.equal(calc(key,{a:1,b:1,c:1,d:1}),null);for(const bad of [null,NaN,Infinity,-1,10,1.5,'1',true])assert.equal(calc('hydrogen',{a:bad,b:1,c:1}),null);
for(const key of Object.keys(species)){
 lab.querySelector('[data-chem-action="'+key+'"]').click();const n=species[key].length;assert.equal(inputs.filter(i=>!i.disabled).length,n);assert.equal(lab.querySelector('[data-chem-action="'+key+'"]').getAttribute('aria-pressed'),'true');
 const scenarios=[Array(n).fill(0),Array(n).fill(1),correct[key],correct[key].map(x=>x*2),Array(n).fill(9)];for(let index=0;index<n;index++)for(const value of [0,1,3,9]){const c=correct[key].slice();c[index]=value;scenarios.push(c);}
 for(const coeff of scenarios){coeff.forEach((value,i)=>inputs[i].value=String(value));inputs[0].dispatchEvent(new w.Event('input'));const e=expected(key,coeff);assert.equal(status.textContent.startsWith('Richtig ausgeglichen:'),e.ok);if(coeff.every(c=>c===0))assert.ok(status.textContent.startsWith('Keine Reaktion dargestellt:'));if(e.ok&&e.factor>1)assert.ok(status.textContent.includes('durch '+e.factor));
  for(const[side,totals]of [['left',e.left],['right',e.right]]){const group=lab.querySelector('[data-reaction-side="'+side+'"]'),letters=[...group.querySelectorAll('svg text')].map(t=>t.textContent);for(const[atom,count]of Object.entries(totals))assert.equal(letters.filter(s=>s===atom).length,count);}
  for(const[atom,count]of Object.entries(e.left)){const cells=[...lab.querySelector('[data-reaction-atom="'+atom+'"]').children];assert.equal(Number(cells[1].textContent),count);assert.equal(Number(cells[2].textContent),e.right[atom]);assert.equal(cells[3].textContent,count===e.right[atom]?'ja':'nein');}
  for(const[i,[formula,atoms]]of species[key].entries()){const card=lab.querySelector('[data-reaction-species="'+formula+'"]');assert.equal(card.querySelectorAll('svg').length,coeff[i]);assert.ok(card.querySelector('figcaption').textContent.includes(coeff[i]+' Molekül'));assert.ok(lab.querySelector('[data-reaction-equation]').textContent.includes(coeff[i]+' '+formula.replace(/([0-9])/g,'$1')));}
  assert.equal(lab.querySelectorAll('[data-reaction-molecule]').length,coeff.reduce((a,b)=>a+b,0));drawings++;
 }
 for(const field of inputs.filter(i=>!i.disabled))for(const bad of ['','-1','10','1.5']){field.value=bad;field.focus();field.dispatchEvent(new w.Event('input'));assert.equal(field.value,bad);assert.equal(field.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,field);assert.equal(lab.querySelectorAll('svg').length,0);field.value='1';field.dispatchEvent(new w.Event('input'));assert.equal(field.getAttribute('aria-invalid'),'false');}
 const reset=lab.querySelector('[data-chem-action="reset"]');reset.focus();reset.click();assert.equal(d.activeElement,reset);assert.equal(reset.hasAttribute('aria-pressed'),false);assert.equal(lab.dataset.chemReaction,key);assert.deepEqual(inputs.filter(i=>!i.disabled).map(i=>i.value),Array(n).fill('1'));w.ChemieLabs.topicInit();assert.equal(lab.dataset.chemReaction,key);
}
assert.equal(drawings,55);assert.equal(JSON.stringify(w.localStorage),storage);assert.equal(d.querySelectorAll('[data-reaction-builder-tasks]>li').length,4);dom.window.close();
const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/physik_bay6/topics/worksheet.html?topic=chemie_reaktionen_energie',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-chemistry-material'),solutions=pd.getElementById('ws-solutions');assert.equal(material.querySelectorAll('[data-reaction-paper]').length,3);assert.equal(material.querySelectorAll('[data-reaction-paper] svg[data-worksheet-static="true"]').length,10);assert.equal(material.querySelectorAll('[data-reaction-builder-tasks]>li').length,4);for(const[key,terms]of Object.entries(species)){const card=material.querySelector('[data-reaction-paper="'+key+'"]');assert.equal(card.querySelectorAll('svg').length,terms.length);for(const cell of card.querySelectorAll('[data-reaction-balance] td'))assert.equal(cell.textContent,'…');}
assert.equal(solutions.hidden,true);assert.ok(solutions.textContent.includes('Gleiche Molekülzahlen können vorkommen'));assert.ok(!material.textContent.includes('Gleiche Molekülzahlen können vorkommen'));assert.equal(pd.getElementById('ws-print').disabled,false);paper.window.close();console.log('PASS: 12,000 independent balances (12 valid ratios), 55 rendered states with atom-symbol counts, zero/multiple/missing feedback, invalid inputs, reset/focus/storage and three static paper cases.');
})().catch(e=>{console.error(e);process.exitCode=1;});
