const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math1_3_add_sub';
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();
const before=d.getElementById('addA').textContent;w.topicInit();assert.equal(d.getElementById('addA').textContent,before);
for(const [prefix,add]of [['add',true],['sub',false]]){const input=d.getElementById(prefix+'I'),feedback=d.getElementById(prefix+'F');assert.ok(d.querySelector('label[for="'+prefix+'I"]'));assert.equal(feedback.getAttribute('role'),'status');
 for(let left=add?10:50;left<=(add?49:99);left++)for(let right=10;right<=49;right++){const expected=add?left+right:left-right;input.value=String(expected);w.checkArithmetic(prefix,left,right,add);assert.match(feedback.textContent,/^Richtig/);input.value=String(expected+1);w.checkArithmetic(prefix,left,right,add);assert.doesNotMatch(feedback.textContent,/^Richtig/);}
 for(const value of ['', '20.9','20,9','2e1','0x14','20abc','-1','9007199254740992']){input.value=value;w.checkArithmetic(prefix,add?10:30,10,add);assert.match(feedback.textContent,/Gib eine ganze Zahl/);}
 input.value='20';input.dispatchEvent(new w.Event('input'));assert.equal(feedback.textContent,'');const random=w.Math.random;w.Math.random=()=>0;(add?w.newA:w.newS)();w.Math.random=random;input.value=add?'20':'40';input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(feedback.textContent,/^Richtig/);(add?w.newA:w.newS)();assert.equal(input.value,'');assert.equal(feedback.textContent,'');
}
let paths=0;for(const [i,q]of w.currentChapterQuiz.questions.entries())if(q.id.startsWith('addsub_'))for(let a=0;a<q.answers.length;a++){assert.equal(q.sectionIndex,['addsub_alignment','addsub_carry','addsub_zero'].indexOf(q.id));w.currentChapterQuiz.questions.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?a:item.answers.findIndex(x=>x.correct)}"]`).checked=true);w.submitChapterQuiz();const n=w.currentChapterQuiz.questions.length;assert.equal(JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id].lastPercent,Math.round(100*(n-(q.answers[a].correct?0:1))/n));assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));paths++;}assert.equal(paths,9);assert.equal(w.currentChapterResult(id,{contentRevision:0,passed:true,bestPercent:100}).passed,false);assert.equal(d.querySelectorAll('[data-regrouping-task] li').length,4);dom.window.close();console.log('PASS: 3600 arithmetic pairs, strict whole-number input, feedback clearing, Enter, repeated initialization, nine assessed answer paths and stale revision.');})().catch(e=>{console.error(e);process.exitCode=1;});
