const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),topic='dgb8_orientierung';
const expected={mobility:{keys:[1,0,2],reasons:[/Überwachungsauftrag.*vollständigen Selbstständigkeit/,/Einsatzbereichs.*außerhalb/,/Zeitstempel.*Sensorzustand/]},health:{keys:[2,0,1],reasons:[/P17 und P71.*verschiedene Personen/,/Fehlende Daten.*kein gemessener Nullwert/,/A, B, C.*E, F.*D/]}};
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+topic,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const file of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+file+'.js'));await w.renderTopic();const before=JSON.stringify(w.localStorage);let decisions=0;
 for(const [id,e]of Object.entries(expected)){
  const zone=d.querySelector('[data-assistance-lab="'+id+'"]'),control=zone.querySelector('select'),cases=[...zone.querySelectorAll('[data-boundary-case]')],result=zone.querySelector('[role="status"]');assert.equal(cases.length,3);assert.equal(d.getElementById(control.getAttribute('aria-describedby')),result);
  for(let c=0;c<3;c++){control.value=String(c);control.dispatchEvent(new w.Event('change'));assert.equal(cases.filter(x=>!x.hidden).length,1);assert.equal(cases[c].hidden,false);assert.match(result.textContent,/Lies den Fall/);for(let choice=0;choice<3;choice++){const button=cases[c].querySelectorAll('button')[choice];button.click();assert.equal(result.textContent.startsWith('Richtig:'),choice===e.keys[c]);assert.ok(result.textContent.length>85);if(choice===e.keys[c])assert.match(result.textContent,e.reasons[c]);assert.equal(button.getAttribute('aria-describedby'),result.id);decisions++;}}
  zone.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.match(result.textContent,/Lies den Fall/);
 }
 assert.equal(JSON.stringify(w.localStorage),before);const ids=[...d.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length,'No duplicate DOM IDs');
 const rows=[...d.querySelectorAll('[data-assistance-reference] tbody tr')].map(r=>[...r.cells].map(c=>c.textContent));assert.deepEqual(rows.map(r=>r[0]),'ABCDEFGHIJ'.split(''));
 const grouped={match:[],extra:[],miss:[],negative:[]};for(const [id,reference,marked]of rows){assert.equal(reference,'ABCD'.includes(id)?'ja':'nein');assert.equal(marked,'ABCEF'.includes(id)?'ja':'nein');grouped[reference==='ja'?(marked==='ja'?'match':'miss'):(marked==='ja'?'extra':'negative')].push(id);}assert.deepEqual(grouped,{match:['A','B','C'],extra:['E','F'],miss:['D'],negative:['G','H','I','J']});assert.equal(d.querySelectorAll('[data-assistance-tasks]>li').length,8);assert.equal(d.querySelectorAll('[data-assistance-solution]').length,2);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+topic,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const file of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+file+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-assistance-paper] .ai-paper-case').length,6);assert.equal(material.querySelectorAll('[data-assistance-reference] tbody tr').length,10);assert.equal(material.querySelectorAll('[data-assistance-tasks]>li').length,8);assert.equal(material.querySelectorAll('[data-assistance-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-assistance-solution]').length,2);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(material.querySelectorAll('button,select,input').length,0);paper.window.close();console.log('PASS: '+decisions+' independently keyed judgments, resets/focus/no storage writes, unique IDs, independent four-group data analysis, six printable cases, eight tasks and separated solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
