const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),html=read('examples/punktewerkstatt.html');
const source='# eigene Regel\nSETZE punkte 5\nFÜR JEDE ANTWORT\n WENN RICHTIG\n  ERHÖHE punkte 3\n ENDE\n WENN FALSCH\n  ERHÖHE punkte -1\n ENDE\n ZEIGE punkte\nENDE';
const trials=[{answers:[false,false,false],values:[4,3,2]},{answers:[false,false,true],values:[4,3,6]},{answers:[false,true,false],values:[4,7,6]},{answers:[false,true,true],values:[4,7,10]},{answers:[true,false,false],values:[8,7,6]},{answers:[true,false,true],values:[8,7,10]},{answers:[true,true,false],values:[8,11,10]},{answers:[true,true,true],values:[8,11,14]}];
const dom=new JSDOM(html,{url:'https://example.test/site/examples/punktewerkstatt.html',runScripts:'dangerously'}),w=dom.window,d=w.document,api=w.PunkteWerkstatt,get=id=>d.getElementById(id),input=code=>{get('program').value=code;get('program').dispatchEvent(new w.Event('input'));};
assert.ok(api);assert.equal(d.querySelectorAll('script[src],iframe,img,link[rel=stylesheet]').length,0);const initialStorage=w.localStorage.length;
for(const t of trials){input(source);t.answers.forEach((v,i)=>{get('answer-'+(i+1)).value=v?'richtig':'falsch';get('answer-'+(i+1)).dispatchEvent(new w.Event('change'));});get('check').click();assert.match(get('status').textContent,/Schreibweise gültig/);get('run').click();assert.deepEqual([...get('output').children].map(e=>Number(e.textContent)),t.values);assert.equal(Number(get('memory').textContent),t.values[2]);assert.equal(get('step').disabled,true);assert.match(get('status').textContent,/keine automatische Bewertung/);}
// Independently known reset defect: the same input must reveal different intermediate states.
const misplaced=source.replace('SETZE punkte 5\n','').replace('FÜR JEDE ANTWORT','FÜR JEDE ANTWORT\nSETZE punkte 5');assert.deepEqual(Array.from(api.execute(api.parse(misplaced),[true,false,true])).filter(s=>s.output!==null).map(s=>s.output),[8,4,8]);
const output=code=>Array.from(api.execute(api.parse(code),[true,false,true])).filter(s=>s.output!==null).map(s=>s.output);
assert.deepEqual(output('SETZE punkte -2\nERHÖHE punkte 0\nZEIGE punkte\nERHÖHE punkte -3\nZEIGE punkte'),[-2,-5]);
assert.deepEqual(output('setze punkte 1\nfür jede antwort\n wenn richtig\n  wenn falsch\n   erhöhe punkte 50\n  ende\n ende\nende\nzeige punkte'),[1]);
assert.deepEqual(output('SETZE punkte 2\nSETZE punkte 7\nZEIGE punkte'),[7]);
for(const [code,reason]of [['',/mindestens/],['ENDE',/keinen offenen/],['SETZE punkte 5\nFÜR JEDE ANTWORT',/fehlt ENDE/],['WENN RICHTIG\nENDE',/gehört in/],['SETZE punkte 51',/ganze Zahl/],['SETZE punkte -51',/ganze Zahl/],['SETZE punkte 2.5',/Unbekannte/],['SETZE punkte 1\nFÜR JEDE ANTWORT\nFÜR JEDE ANTWORT\nENDE\nENDE',/höchstens eine/],['#x\n'.repeat(41),/40 Zeilen/],['x'.repeat(4001),/4000 Zeichen/],['SETZE punkte 1\nalert(1)',/Zeile 2/]])assert.throws(()=>api.parse(code),reason);
assert.throws(()=>api.execute(api.parse('ERHÖHE punkte 3'),[true,false,true]),/noch nicht gesetzt/);assert.throws(()=>api.execute(api.parse('ZEIGE punkte'),[true,false,true]),/noch nicht gesetzt/);
input('SETZE punkte 5\nZEIGE punkte');get('step').focus();get('step').click();assert.equal(get('output').children.length,0);assert.equal(get('memory').textContent,'5');get('step').click();assert.equal(d.activeElement,get('restart'));get('restart').click();assert.equal(d.activeElement,get('step'));assert.equal(get('trace').tBodies[0].rows.length,0);
get('run').click();input('ZEIGE punkte');get('run').click();assert.match(get('status').textContent,/noch nicht gesetzt/);assert.equal(get('program').getAttribute('aria-invalid'),'true');assert.equal(get('output').children.length,0);assert.equal(get('trace').tBodies[0].rows.length,0);
input(source);get('prediction').value='8, 7, 10';get('notes').value='</textarea><script>window.unwanted=true</script> & Test';get('credit').value='Vorlage SciVerse; Start 5; +3/-1.';get('answer-2').value='falsch';const snapshot=api.workingHTML();assert.ok(!snapshot.includes('</textarea><script>window.unwanted'));const reopened=new JSDOM(snapshot,{url:'file:///C:/test/mein-punkteprogramm.html',runScripts:'dangerously'}),rd=reopened.window.document;
assert.equal(rd.getElementById('program').value,source);assert.equal(rd.getElementById('notes').value,get('notes').value);assert.equal(rd.getElementById('prediction').value,'8, 7, 10');assert.equal(rd.getElementById('credit').value,get('credit').value);assert.equal(rd.getElementById('answer-2').value,'falsch');assert.equal(reopened.window.unwanted,undefined);rd.getElementById('run').click();assert.deepEqual([...rd.getElementById('output').children].map(e=>Number(e.textContent)),[8,7,10]);assert.match(rd.getElementById('chapter-link').href,/thingummyboop.github.io/);assert.equal(w.localStorage.length,initialStorage);reopened.window.close();dom.window.close();
(async()=>{const data=JSON.parse(read('lang/de.json')),id='dgb6_produktion',keys=require('./fixtures/dgb6_production_keys.json'),page=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),pw=page.window,pd=pw.document;await new Promise(r=>setImmediate(r));pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])pw.eval(read('js/'+f+'.js'));await pw.renderTopic();
 const qs=pw.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));assert.deepEqual(Array.from(qs,q=>q.sectionIndex),[0,2,2,3,3,3,3,4,4,4,4,5]);assert.equal(pd.querySelectorAll('[data-program-project-tasks]>li').length,8);assert.equal(pd.querySelector('[data-points-workshop]').href,'https://example.test/site/examples/punktewerkstatt.html');assert.equal(pd.querySelectorAll('[data-program-test-plan] tbody tr').length,4);
 for(const [n,q]of qs.entries())for(let a=0;a<3;a++){qs.forEach((item,j)=>pd.querySelector(`input[name="chapter_q_${j}"][value="${j===n?a:keys[item.id]}"]`).checked=true);pw.submitChapterQuiz();const r=JSON.parse(pw.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,a===keys[q.id]?100:92);assert.equal(r.contentRevision,3);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(pd.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[1,2,0]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));assert.equal(pw.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).outdated,true);page.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),sw=paper.window;sw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])sw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const m=sw.document.getElementById('ws-dgb-material'),s=sw.document.getElementById('ws-solutions');assert.equal(m.querySelectorAll('[data-program-project-tasks]>li').length,8);assert.equal(m.querySelectorAll('[data-program-project-solution]').length,0);assert.equal(s.querySelectorAll('[data-program-project-solution]').length,1);assert.equal(s.hidden,true);assert.ok(s.textContent.includes('8, 7, 10'));assert.ok(m.textContent.includes('ersetzt aber nicht'));paper.window.close();console.log('PASS: eight independently calculated programs, reset defect, parser/runtime errors, stepwise memory and output, safe offline workfile round-trip, 36 chapter answers and worksheet separation.');})().catch(e=>{console.error(e);process.exitCode=1;});
