const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='elektromagnetismus';
const answers={em_s4_q1:0,em_d8:1,em_d9:2,em_d12:0,em_d15:1,em_induction_speed:2,em_induction_controls:0,em_trans_power:2};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 const lab=d.querySelector('[data-induction-lab]'),selects=['pole-select','motion-select','speed','circuit'].map(k=>lab.querySelector('[data-induction-'+k+']')),stored=JSON.stringify(w.localStorage);let states=0,decisions=0;
 // An explicit case table, independent of the implementation's multiplication of signs.
 const expected={N:{rest:0,in:1,out:-1},S:{rest:0,in:-1,out:1}};
 for(const pole of ['N','S'])for(const motion of ['rest','in','out'])for(const speed of ['slow','fast'])for(const circuit of ['open','closed']){
  for(const[i,v]of [pole,motion,speed,circuit].entries()){selects[i].value=v;selects[i].focus();selects[i].dispatchEvent(new w.Event('change'));assert.equal(d.activeElement,selects[i]);}
  const sign=expected[pole][motion],level=sign*(speed==='fast'?2:1),s=w.inductionState(pole,motion,speed,circuit);assert.equal(s.sign,sign);assert.equal(s.level,level);assert.equal(s.current,sign!==0&&circuit==='closed');assert.equal(lab.querySelector('[data-induction-feedback]').textContent,'');
  const pointer=lab.querySelector('[data-induction-pointer]');assert.equal(Number(pointer.dataset.sign),sign);assert.equal(Number(pointer.dataset.level),level);assert.ok(pointer.getAttribute('d').startsWith('M'+(180+50*level)+' '));assert.equal(lab.querySelectorAll('[data-induction-motion]').length,motion==='rest'?0:1);assert.equal(lab.querySelector('[data-induction-pole]').textContent,pole);
  const arrow=lab.querySelector('[data-induction-motion]');if(arrow)assert.equal(arrow.getAttribute('d').startsWith(motion==='in'?'M151 74H210':'M210 74H151'),true);
  assert.ok(lab.querySelector('[data-induction-status]').textContent.includes(sign===0?'Keine induzierte Spannung':sign>0?'Positive':'Negative'));assert.ok(lab.querySelector('[data-induction-status]').textContent.includes(s.current?'Strom möglich':circuit==='open'?'kein Laststrom':'kein Strom'));
  for(const b of lab.querySelectorAll('[data-induction-verdict]')){b.click();assert.equal(lab.querySelector('[data-induction-feedback]').textContent.startsWith('Richtig:'),Number(b.dataset.inductionVerdict)===sign);decisions++;}states++;
 }
 assert.equal(states,24);assert.equal(decisions,72);for(const el of selects){assert.equal(el.labels.length,1);assert.equal(el.getAttribute('aria-describedby'),'induction-status');}w.initInductionLab();assert.equal(selects[0].value,'S');lab.querySelector('[data-induction-reset]').click();assert.deepEqual(selects.map(e=>e.value),['N','rest','slow','open']);assert.equal(d.activeElement,selects[0]);assert.equal(JSON.stringify(w.localStorage),stored);assert.equal(w.inductionState('X','rest','slow','open'),null);
 const pri=d.getElementById('voltBarPri'),sec=d.getElementById('voltBarSec');assert.equal(Number(pri.getAttribute('height')),50);for(let n=1;n<=10;n++){w.updateTransformer(n);assert.equal(d.getElementById('voltValSec').textContent,n*46+'V');assert.equal(Number(sec.getAttribute('height'))/Number(pri.getAttribute('height')),n/5);assert.equal(Number(sec.getAttribute('y'))+Number(sec.getAttribute('height')),160);assert.equal(d.getElementById('transRange').value,String(n));assert.equal(d.querySelectorAll('#coil2 path').length,n);}for(const v of [0,11,NaN,Infinity,'5x']){w.updateTransformer(v);assert.equal(d.getElementById('transRange').value,'10');}
 assert.equal(d.getElementById('currentRange').getAttribute('aria-describedby'),'currentFieldStatus');w.updateMagnetField(0);assert.equal(d.getElementById('currentArrow').style.opacity,'0');assert.match(d.getElementById('currentFieldStatus').textContent,/kein durch diesen Leiter/);w.updateMagnetField(60);assert.match(d.getElementById('currentFieldStatus').textContent,/60/);
 const flashlight=d.getElementById('flashlight');assert.equal(flashlight.tagName,'BUTTON');assert.ok(flashlight.getAttribute('aria-label'));w.shakeFlashlight();assert.equal(d.getElementById('energyLevel').innerText,15);w.topicInit();assert.equal(d.getElementById('energyLevel').innerText,'0');
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,29);let paths=0;for(const q of qs.filter(q=>q.id in answers)){assert.equal(q.sectionIndex,q.id==='em_trans_power'?6:5);const index=qs.indexOf(q);for(let choice=0;choice<3;choice++){qs.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(index===j?choice:item.id in answers?answers[item.id]:item.answers.findIndex(a=>a.correct))+'"]').checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===answers[q.id]?100:97);assert.equal(r.contentRevision,7);assert.deepEqual(r.reviewQuestionIds,choice===answers[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;}}assert.equal(paths,21);assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:6}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-physics-material');assert.equal(material.querySelectorAll('article').length,7);assert.equal(material.querySelectorAll('[data-induction-paper] tbody tr').length,6);assert.equal(material.querySelectorAll('[data-induction-observation] tbody tr').length,6);assert.equal(material.querySelectorAll('[data-induction-tasks]>li').length,4);assert.equal(material.querySelectorAll('[data-induction-experiment]>li').length,4);assert.equal(material.querySelectorAll('[data-transformer-tasks]>li').length,2);assert.equal(material.querySelectorAll('[data-transformer-paper] tbody tr').length,3);assert.equal(material.querySelectorAll('[data-induction-svg][data-worksheet-static]').length,1);assert.equal(material.querySelectorAll('input,button,select,[role=status]').length,0);assert.ok(material.textContent.includes('Ohne Geräte bleibt die Beobachtungsspalte leer'));assert.ok(material.textContent.includes('Eine Schüttellampe besitzt Generator'));assert.ok(!material.textContent.includes('Protokoll in Zeilenfolge'));assert.ok(pd.getElementById('ws-solutions').textContent.includes('Protokoll in Zeilenfolge'));assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,29);assert.equal(pd.getElementById('ws-print').disabled,false);paper.window.close();
 console.log(`PASS: induction: ${states} controlled cases, ${decisions} classifications, ${paths} independently keyed answer paths, 10 proportional transformer bars, input/focus/reset and real/virtual paper protocols.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
