'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),id='bio_4_landwirtschaft_biodiversitaet';
const keys={bio_4_land_s1:[1,0],bio_4_land_d1:[0,0],bio_4_land_s2:[2,1],bio_4_land_d2:[1,1],bio_4_land_bio_regeln:[2,1],bio_4_land_bezugsflaeche:[1,2],bio_4_land_arten:[2,2],bio_4_land_ursache:[0,2],bio_4_land_s3:[1,3],bio_4_land_d3:[2,3]};
// Expected percentages were calculated separately from the taught fractions, rounded only at the end.
const cases=[['1','whole','A',100,92,-8],['1','whole','B',100,92,8.7],['1','crop','A',100,102.2,2.2],['1','crop','B',100,102.2,-2.2],['2','whole','A',110,106,-3.6],['2','whole','B',110,106,3.8],['2','crop','A',110,117.8,7.1],['2','crop','B',110,117.8,-6.6],['3','whole','A',90,88,-2.2],['3','whole','B',90,88,2.3],['3','crop','A',90,97.8,8.6],['3','crop','B',90,97.8,-8]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-farm-lab]'),year=zone.querySelector('[data-farm-year]'),basis=zone.querySelector('[data-farm-basis]'),reference=zone.querySelector('[data-farm-reference]'),check=zone.querySelector('[data-farm-check]'),reset=zone.querySelector('[data-farm-reset]'),result=zone.querySelector('[data-farm-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.invalid,undefined);};
 const number=selector=>Number(result.querySelector(selector).textContent.replace(/[AB]: | kg| %|\+/g,'').replace(',','.'));
 for(const [y,b,r,aVal,bVal,percent] of cases){set(year,y);set(basis,b);set(reference,r);check.click();assert.equal(number('[data-farm-value="A"]'),aVal);assert.equal(number('[data-farm-value="B"]'),bVal);assert.equal(number('[data-farm-percent]'),percent);assert.equal(result.children.length,5);assert.equal(d.activeElement,result);assert.match(result.textContent,/nicht Bio mit konventioneller/);assert.match(result.textContent,new RegExp('Nenner ist '+r));assert.match(result.textContent,b==='crop'?/keine höhere Gesamternte/:/einschließlich des Blühstreifens/);}
 for(const [input,invalid] of [[year,'year'],[basis,'basis'],[reference,'reference']]){reset.click();set(input,'');check.click();assert.equal(result.dataset.invalid,invalid);assert.equal(d.activeElement,input);}reset.click();assert.equal(year.value,'1');assert.equal(basis.value,'whole');assert.equal(reference.value,'A');assert.equal(d.activeElement,year);assert.equal(JSON.stringify(w.localStorage),storage);
 const table=[...d.querySelectorAll('.farm-data tbody tr')].map(r=>[...r.children].map(e=>e.textContent));assert.deepEqual(table,[['1','1.000 kg','920 kg','3','7'],['2','1.100 kg','1.060 kg','4','6'],['3','900 kg','880 kg','2','5']]);assert.match(d.querySelector('[data-farm-solution="3"]').textContent,/4,5 kg/);assert.match(d.querySelector('[data-farm-solution="3"]').textContent,/10,80 €/);assert.match(d.querySelector('[data-farm-solution="3"]').textContent,/25 %/);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,2);assert.equal(d.querySelectorAll('[data-farm-solution]').length,4);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);assert.ok(data[id].sources.every(s=>s.title&&s.url.startsWith('https://')));
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.ok(practice[0].answers.every(a=>a.pts===0));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-farm-paper]').length,1);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,2);assert.equal(pd.querySelectorAll('.farm-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('#ws-solutions [data-farm-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-farm-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);assert.doesNotMatch(pd.body.textContent,/undefined/);for(const s of data[id].sources)assert.ok(pd.body.textContent.includes(s.title));paper.window.close();
 console.log('PASS: 12 independently calculated comparisons, three source rows, reference/area changes, invalid/reset/focus/storage, 30 quiz answers, 12 direct tasks and complete paper material.');
})().catch(e=>{console.error(e);process.exitCode=1;});
