'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{JSDOM}=require('jsdom'),keys=require('./fixtures/decimal_calculation_answer_keys.json');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),de=JSON.parse(read('lang/de.json')),id='math1_9_dezimalzahlen';
const fraction=text=>{const[a,b='']=text.split(',');return [BigInt(a+b),10n**BigInt(b.length)];};
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>de});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();w.topicInit();
 let models=0,steps=0;const weighted=ds=>Array.from(ds).reduce((n,x,i)=>n+x*10**i,0);
 function verify(a,b,kind){const m=w.decimalCalculation(a,b,kind),[an,ad]=fraction(a),[bn,bd]=fraction(b),[rn,rd]=fraction(m.result);let n,z;if(kind==='add'||kind==='subtract'){n=an*bd+(kind==='add'?1n:-1n)*bn*ad;z=ad*bd;}else if(kind==='multiply'){n=an*bn;z=ad*bd;}else{n=an*bd;z=ad*bn;}assert.equal(rn*z,n*rd);
  let value=0;for(const s of m.steps){if(s.type==='exchange'){assert.equal(weighted(s.before),weighted(m.board.left));assert.equal(weighted(s.after),weighted(m.board.left));assert.equal(s.after[s.source],s.before[s.source]-1);assert.equal(s.after[s.column],s.before[s.column]+10);}if(s.type==='add'){assert.equal(s.digit+10*s.carry,s.expected);value+=s.digit*10**s.column;}if(s.type==='subtract'){assert.ok(s.digit>=0&&s.digit<=9);value+=s.digit*10**s.column;}if(s.type==='divide'){assert.equal(s.partial,s.previous*10+s.brought);assert.equal(s.partial,s.quotient*Number(b)+s.remainder);assert.ok(s.remainder>=0&&s.remainder<Number(b));assert.ok(s.quotient>=0&&s.quotient<=9);}if(s.type==='multiply')assert.equal(s.expected,s.digit*s.factor+s.incoming);}
  if(['add','subtract'].includes(kind))assert.equal(value,m.resultUnits);if(kind==='multiply')assert.equal(m.board.partials.reduce((a,b)=>a+b,0),m.resultUnits);models++;return m;
 }
 for(let a=0;a<=60;a++)for(let b=0;b<=60;b++){const A=w.decimalFormat(a,a%4),B=w.decimalFormat(b,b%4);verify(A,B,'add');verify(A,B,'multiply');if(a/10**(a%4)>=b/10**(b%4))verify(A,B,'subtract');}
 for(let a=0;a<=100;a++)for(const b of [1,2,4,5,8,10,16,20,25])verify(w.decimalFormat(a,2),String(b),'divide');
 for(const kind of ['add','subtract','multiply'])verify('9999,999',kind==='subtract'?'0,001':'9999,999',kind);
 assert.equal(w.decimalCalculation('1','8','divide').result,'0,125');assert.equal(w.decimalCalculation('10,05','5','divide').result,'2,01');assert.equal(w.decimalCalculation('0,04','0,09','multiply').result,'0,0036');
 for(const args of [['-1','2','add'],['1.2','2','add'],['1,0001','2','add'],['1','2','subtract'],['1','0','divide'],['1','0,5','divide'],['1','3','divide'],['1','2','power']])assert.throws(()=>w.decimalCalculation(...args));
 const saved=JSON.stringify(w.localStorage);
 for(const host of d.querySelectorAll('[data-decimal-lab]')){const select=host.querySelector('select'),input=host.querySelector('input'),check=host.querySelector('[data-decimal-check]'),show=host.querySelector('[data-decimal-show]'),reset=host.querySelector('[data-decimal-reset]'),status=host.querySelector('[data-decimal-status]');
  for(let i=0;i<select.options.length;i++){select.value=i;select.dispatchEvent(new w.Event('change'));const[a,b]=select.options[i].textContent.split(/[+−·:]/).map(x=>x.trim()),m=verify(a,b,host.dataset.decimalLab);
   for(const[j,s]of m.steps.entries()){input.value='999999999999';check.click();assert.equal(host.dataset.step,String(j));assert.doesNotMatch(status.textContent,/^Richtig/);input.value=String(s.expected);if(s.decimal)input.value=(input.value.includes(',')?input.value+'0':input.value+',0').replace(',','.');input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(host.dataset.step,String(j+1));assert.match(status.textContent,/^Richtig/);steps++;}
   assert.equal(d.activeElement,status);assert.ok(input.disabled);assert.match(status.textContent,/Alle Rechenschritte sind richtig/);assert.equal(host.querySelectorAll('[data-decimal-history] li').length,m.steps.length);reset.click();assert.equal(d.activeElement,input);assert.equal(host.dataset.step,'0');while(!show.disabled)show.click();assert.match(status.textContent,/wurden gezeigt/);assert.doesNotMatch(status.textContent,/Alle Rechenschritte sind richtig/);reset.click();
  }
  for(const raw of ['', ' ', '2e1','-1','0x2','3/4']){input.value=raw;check.click();assert.equal(input.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,input);assert.equal(host.dataset.step,'0');}input.dispatchEvent(new w.Event('input'));assert.equal(status.textContent,'');assert.equal(input.hasAttribute('aria-invalid'),false);
 }
 assert.equal(JSON.stringify(w.localStorage),saved);assert.equal(w.decimalAnswerMatches('0,00360',{decimal:true,expected:'0,0036'}),true);assert.equal(w.decimalAnswerMatches('0,036',{decimal:true,expected:'0,0036'}),false);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,23);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;
 for(const[i,q]of qs.entries())for(let a=0;a<q.answers.length;a++){assert.equal(q.answers[a].correct,a===keys[q.id]);w.restartChapterQuiz();qs.forEach((other,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?a:keys[other.id])+'"]').checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,a===keys[q.id]?100:96);assert.equal(r.contentRevision,4);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));paths++;}dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>de});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-decimal-paper]').length,4);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,5);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,23);paper.window.close();
 console.log('PASS: '+models+' exact decimal models, '+steps+' entered steps, '+paths+' independent chapter answer paths, decimal input/zero cases, keyboard/focus/reveal/reset/storage, four paper alternatives and five solution groups.');
})().catch(e=>{console.error(e);process.exitCode=1;});
