const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb8_kommunikation';
const keys=require('./fixtures/dgb8_communication_keys.json');
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const lab=d.querySelector('.crop-workshop'),view=lab.querySelector('[data-crop-view]'),caption=lab.querySelector('[data-crop-caption]'),pic=lab.querySelector('[data-crop-image]'),status=lab.querySelector('[data-crop-status]'),stored=JSON.stringify(w.localStorage),original=[...pic.querySelectorAll("[data-vote]")].map(e=>e.outerHTML).join("");
 const cards=[...pic.querySelectorAll('[data-vote]')];assert.equal(cards.length,12);assert.equal(cards.filter(c=>c.dataset.vote==='yes').length,4);assert.deepEqual(cards.map(c=>c.dataset.col),['0','1','2','0','1','2','0','1','2','0','1','2']);
 for(const v of ['full','yes'])for(const c of ['careful','all']){view.value=v;caption.value=c;view.dispatchEvent(new w.Event('change'));caption.dispatchEvent(new w.Event('change'));assert.equal(pic.getAttribute('viewBox'),v==='full'?'0 0 420 320':'0 0 140 320');assert.equal([...pic.querySelectorAll("[data-vote]")].map(e=>e.outerHTML).join(""),original);assert.equal(pic.querySelector("[data-crop-clip]").getAttribute("width"),v==="full"?"420":"140");assert.match(status.textContent,v==='full'?/Gesamtbild: 4 von 12 sichtbaren/:/Ausschnitt: 4 von 4 sichtbaren/);assert.match(status.textContent,/Gesamtbild sind es 4 von 12/);assert.equal(status.textContent.includes('Die Überschrift ist falsch'),c==='all');assert.match(pic.getAttribute('aria-label'),v==='full'?/4 Ja-Karten von 12/:/4 Ja-Karten von 4/);}
 lab.querySelector('[data-crop-reset]').click();assert.equal(view.value,'full');assert.equal(caption.value,'careful');assert.equal(d.activeElement,view);assert.equal(JSON.stringify(w.localStorage),stored);assert.equal(d.getElementById(view.getAttribute('aria-describedby')),status);assert.equal(d.getElementById(caption.getAttribute('aria-describedby')),status);
 w.enhanceCoreLearning(data[id],id,'de');assert.equal(d.querySelectorAll('[data-core-navigation]').length,1);assert.equal(d.querySelectorAll('[data-crop-image]').length,1);
 assert.equal(d.querySelectorAll('[data-media-tasks] > li').length,16);assert.equal(d.querySelectorAll('[data-protocol-cards] > li').length,4);assert.equal(d.querySelectorAll('[data-sharing-cases] > div').length,3);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,lastPercent:100}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,11);for(const [i,q]of qs.entries()){assert.equal(q.sectionIndex,i<6?Math.floor(i/2):i<9?3:4);assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,n)=>d.querySelector(`input[name="chapter_q_${n}"][value="${i===n?choice:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[1,0,2]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material'),svgs=[...material.querySelectorAll('[data-crop-paper] svg')];assert.equal(svgs.length,2);assert.deepEqual(svgs.map(s=>s.getAttribute('viewBox')),['0 0 420 320','0 0 140 320']);for(const s of svgs){assert.equal(s.querySelectorAll('[data-vote]').length,12);assert.equal(s.querySelectorAll('[data-vote="yes"]').length,4);}assert.equal(material.querySelectorAll('[data-media-tasks] > li').length,16);assert.equal(material.querySelectorAll('button,input,select,details').length,0);assert.equal(material.querySelectorAll('[data-media-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-media-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);paper.window.close();console.log('PASS: four crop/caption combinations, unchanged 12 source cards, reset/focus/storage/re-init, 33 keyed answer paths, three practice keys, 16 tasks, two static paper views and four separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
