'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_genetik_gentechnik';
const keys={bio_4_genetik_s1:[1,0],bio_4_genetik_d1:[2,0],bio_4_genetik_s2:[0,1],bio_4_genetik_wahrscheinlichkeit:[2,1],bio_4_genetik_dominanz:[1,1],bio_4_genetik_d2:[1,2],bio_4_genetik_mutation:[0,2],bio_4_genetik_gesundheit:[2,2],bio_4_genetik_s3:[1,3],bio_4_genetik_d3:[0,3],bio_4_genetik_daten:[2,3]};
// Independent four-field expectations in row order and counts AA, Aa, aa.
const cases=[['AA','AA',['AA','AA','AA','AA'],[4,0,0]],['AA','Aa',['AA','Aa','AA','Aa'],[2,2,0]],['AA','aa',['Aa','Aa','Aa','Aa'],[0,4,0]],['Aa','AA',['AA','AA','Aa','Aa'],[2,2,0]],['Aa','Aa',['AA','Aa','Aa','aa'],[1,2,1]],['Aa','aa',['Aa','Aa','aa','aa'],[0,2,2]],['aa','AA',['Aa','Aa','Aa','Aa'],[0,4,0]],['aa','Aa',['Aa','aa','Aa','aa'],[0,2,2]],['aa','aa',['aa','aa','aa','aa'],[0,0,4]]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-genetics-lab]'),first=zone.querySelector('[data-genetics-parent1]'),second=zone.querySelector('[data-genetics-parent2]'),rule=zone.querySelector('[data-genetics-rule]'),check=zone.querySelector('[data-genetics-check]'),reset=zone.querySelector('[data-genetics-reset]'),result=zone.querySelector('[data-genetics-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.invalid,undefined);};
 for(const[a,b,fields,counts]of cases)for(const mode of ['unknown','dominant','intermediate']){
  set(first,a);set(second,b);set(rule,mode);check.click();assert.equal(d.activeElement,result);
  assert.deepEqual([...result.querySelectorAll('[data-genetics-combination]')].map(e=>e.dataset.geneticsCombination),fields);assert.deepEqual([...result.querySelectorAll('[data-genetics-count]')].map(e=>Number(e.dataset.geneticsCount)),counts);
  assert.equal(result.querySelectorAll('.genetics-square tbody tr').length,2);assert.equal(result.querySelectorAll('.genetics-distribution tbody tr').length,3);
  const phenotype=result.querySelector('[data-genetics-phenotype]');assert.equal(phenotype.dataset.geneticsPhenotype,mode);
  if(mode==='unknown'){assert.equal(phenotype.dataset.geneticsColors,undefined);assert.match(phenotype.textContent,/keine Farbwahrscheinlichkeiten/);assert.deepEqual([...result.querySelectorAll('.genetics-distribution tbody tr')].map(e=>e.lastChild.textContent),['Unbekannt','Unbekannt','Unbekannt']);}
  else{const expected=mode==='dominant'?[counts[0]+counts[1],0,counts[2]]:counts;assert.equal(phenotype.dataset.geneticsColors,expected.join(','));assert.deepEqual([...result.querySelectorAll('.genetics-distribution tbody tr')].map(e=>e.lastChild.textContent),mode==='dominant'?['Rot','Rot','Weiß']:['Rot','Rosa','Weiß']);}
  assert.match(result.textContent,/keine feste Reihenfolge/);assert.match(result.textContent,/keine Vorhersage menschlicher Eigenschaften/);assert.equal(result.querySelectorAll('h4').length,1);
 }
 for(const[input,name]of [[first,'parent1'],[second,'parent2'],[rule,'rule']]){reset.click();set(input,'');check.click();assert.equal(result.dataset.invalid,name);assert.equal(d.activeElement,input);}reset.click();assert.equal(first.value,'Aa');assert.equal(second.value,'Aa');assert.equal(rule.value,'unknown');assert.equal(result.textContent,'');assert.equal(d.activeElement,first);assert.equal(JSON.stringify(w.localStorage),storage);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('[data-genetics-solution]').length,4);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 const ruleRows=[...d.querySelectorAll('.genetics-rules tbody tr')].map(e=>[...e.children].map(c=>c.textContent));assert.deepEqual(ruleRows,[['Keine Zuordnung','Unbekannt','Unbekannt','Unbekannt'],['A dominant','Rot','Rot','Weiß'],['Zwischenform','Rot','Rosa','Weiß']]);
 const growth=[...d.querySelectorAll('.genetics-growth tbody tr')].map(e=>e.lastChild.textContent.split(' / ').map(Number));assert.deepEqual(growth,[[22,24,26],[12,14,16],[18,20,22],[10,12,14]]);assert.deepEqual(growth.map(r=>r.reduce((a,b)=>a+b,0)/3),[24,14,20,12]);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,11);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].id,'bio_4_genetik_extra_dna');assert.ok(practice[0].answers.every(a=>a.pts===0));const practiceStorage=JSON.stringify(w.localStorage);w.playSuccessSound=()=>{};for(const answer of practice[0].answers){const button=[...d.querySelectorAll('.practice-box .practice-option')].find(e=>e.textContent===answer.text);assert.ok(button);w.handlePracticeAnswer(button,answer.correct,button.dataset.feedback);assert.ok(button.closest('.practice-box').querySelector('.feedback').innerText.includes(answer.feedback));assert.equal(button.classList.contains(answer.correct?'is-correct':'is-wrong'),true);assert.equal(button.disabled,false);}assert.equal(JSON.stringify(w.localStorage),practiceStorage);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-genetics-paper]').length,1);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(pd.querySelectorAll('.genetics-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('#ws-solutions [data-genetics-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-genetics-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);assert.doesNotMatch(pd.body.textContent,/undefined/);for(const s of data[id].sources){assert.ok(s.title&&s.url.startsWith('https://'));assert.ok(pd.body.textContent.includes(s.title));}
 const solution=pd.querySelector('#ws-solutions [data-genetics-solution="1"]').textContent;for(const[a,b,,counts]of cases.filter((_,i)=>[0,1,2,4,5,8].includes(i)))assert.ok(solution.includes(a+' × '+b+': '+counts.map(v=>v*25).join(' / ')+' %'));assert.ok(solution.includes('75 / 25'));assert.ok(solution.includes('25 / 50 / 25'));const growthSolution=pd.querySelector('#ws-solutions [data-genetics-solution="2"]').textContent;for(const text of ['24 cm','14 cm','20 cm','12 cm','10 cm','8 cm','keine A/a-Genotypen'])assert.ok(growthSolution.includes(text));paper.window.close();
 console.log('PASS: 27 inheritance/rule combinations, nine independent genotype distributions, invalid/reset/focus/storage, 33 quiz answers and complete paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
