const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math1_11_figuren_koerper';
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();const zone=d.querySelector('[data-rectangle-lab]'),a=zone.querySelector('[data-rectangle-a]'),b=zone.querySelector('[data-rectangle-b]'),status=zone.querySelector('[data-rectangle-status]');const before=w.localStorage.getItem('physik_score');
for(let x=1;x<=10;x++)for(let y=1;y<=10;y++){a.value=x;b.value=y;a.focus();a.dispatchEvent(new w.Event('input'));assert.equal(d.activeElement,a);const cells=[...zone.querySelectorAll('[data-unit-square]')];assert.equal(cells.length,x*y);const positions=new Set(cells.map(c=>c.getAttribute('x')+','+c.getAttribute('y')));assert.equal(positions.size,x*y);const border=zone.querySelector('[data-rectangle-border]');assert.equal(Number(border.getAttribute('width')),x*28);assert.equal(Number(border.getAttribute('height')),y*28);assert.equal(Number(status.dataset.area),x*y);assert.equal(Number(status.dataset.perimeter),x+x+y+y);assert.equal(a.getAttribute('aria-valuetext'),x+' Zentimeter');}
const reset=zone.querySelector('[data-rectangle-reset]');reset.focus();reset.click();assert.equal(d.activeElement,reset);assert.equal(a.value,'4');assert.equal(b.value,'3');assert.equal(w.localStorage.getItem('physik_score'),before);assert.equal(d.querySelectorAll('[data-rectangle-task] li').length,5);
const cz=d.querySelector('[data-cuboid-lab]'),ci=['a','b','c'].map(k=>cz.querySelector('[data-cuboid-'+k+']')),cs=cz.querySelector('[data-cuboid-status]');
for(let x=1;x<=6;x++)for(let y=1;y<=6;y++)for(let z=1;z<=6;z++){ci.forEach((input,i)=>input.value=[x,y,z][i]);ci[0].dispatchEvent(new w.Event('input'));const faces=[...cz.querySelectorAll('[data-cuboid-face]')].map(el=>['x','y','width','height'].map(k=>Number(el.getAttribute(k))));assert.equal(faces.length,6);assert.equal(faces.reduce((sum,f)=>sum+f[2]*f[3]/256,0),2*(x*y+x*z+y*z));for(let i=0;i<6;i++)for(let j=i+1;j<6;j++){const a=faces[i],b=faces[j];assert.ok(a[0]+a[2]<=b[0]||b[0]+b[2]<=a[0]||a[1]+a[3]<=b[1]||b[1]+b[3]<=a[1],'Net faces do not overlap');}assert.equal(cz.querySelectorAll('[data-unit-cube]').length,x*y*z);assert.equal(Number(cs.dataset.volume),x*y*z);assert.equal(Number(cs.dataset.surface),2*x*y+2*x*z+2*y*z);for(let layer=1;layer<=z;layer++)assert.equal(cz.querySelectorAll('[data-unit-cube="'+layer+'"]').length,x*y);}
const cr=cz.querySelector('[data-cuboid-reset]');cr.focus();cr.click();assert.equal(d.activeElement,cr);assert.deepEqual(ci.map(i=>i.value),['4','3','2']);assert.equal(d.querySelectorAll('[data-cuboid-task] li').length,7);assert.equal(w.localStorage.getItem('physik_score'),before);
const corner=d.getElementById('rect_input'),feedback=d.getElementById('rect_feedback');for(const invalid of ['', '4.5','4e0','0x4','-4']){corner.value=invalid;w.checkRect();assert.match(feedback.textContent,/ganze Anzahl/);}corner.value='4';corner.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter'}));assert.match(feedback.textContent,/Richtig/);corner.dispatchEvent(new w.Event('input'));assert.equal(feedback.textContent,'');d.getElementById('k_select').value='';w.checkK();assert.match(d.getElementById('k_feedback').textContent,/Wähle zuerst/);
let paths=0;for(const [i,q]of w.currentChapterQuiz.questions.entries())if(q.id.startsWith('rectangle_')||q.id.startsWith('cuboid_'))for(let j=0;j<q.answers.length;j++){assert.equal(q.sectionIndex,q.id.startsWith('cuboid_')?3:1);w.currentChapterQuiz.questions.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${k===i?j:item.answers.findIndex(x=>x.correct)}"]`).checked=true);w.submitChapterQuiz();const n=w.currentChapterQuiz.questions.length;assert.equal(JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id].lastPercent,Math.round(100*(n-(q.answers[j].correct?0:1))/n));assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[j].feedback));paths++;}assert.equal(paths,18);assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).passed,false);dom.window.close();console.log('PASS: all 100 rectangle dimensions, unit squares/border geometry, area/perimeter, reset/focus, unchanged score, 216 cuboids with non-overlapping nets, layer counts, eighteen answer paths and revision.');})().catch(e=>{console.error(e);process.exitCode=1;});
