const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{
 const data=JSON.parse(read('lang/de.json')),id='bio_2_wirbellose';
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});
 for(const file of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+file+'.js'));
 await w.renderTopic();assert.equal(d.querySelectorAll('.chapter-question').length,12);
 assert.equal(w.currentChapterResult(id,{passed:true}).outdated,true);
 w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-invertebrate-key]'),legs=zone.querySelector('[data-key-legs]'),shell=zone.querySelector('[data-key-shell]'),foot=zone.querySelector('[data-key-foot]'),status=zone.querySelector('[role=status]'),storage=JSON.stringify(w.localStorage);
 // Hand-authored candidate sets independent of the implementation's example records.
 const sets={legs:{'':['ant','bee','spider','woodlouse','snail','slug','worm'],'0':['snail','slug','worm'],'6':['ant','bee'],'8':['spider'],many:['woodlouse']},shell:{'':['ant','bee','spider','woodlouse','snail','slug','worm'],yes:['snail'],no:['ant','bee','spider','woodlouse','slug','worm']},foot:{'':['ant','bee','spider','woodlouse','snail','slug','worm'],yes:['snail','slug'],no:['ant','bee','spider','woodlouse','worm']}};
 for(const a of Object.keys(sets.legs))for(const b of Object.keys(sets.shell))for(const c of Object.keys(sets.foot)){
  legs.value=a;shell.value=b;foot.value=c;foot.focus();foot.dispatchEvent(new w.Event('change'));
  const expected=sets.legs[a].filter(id=>sets.shell[b].includes(id)&&sets.foot[c].includes(id)),actual=[...zone.querySelectorAll('[data-animal-example]')].map(e=>e.dataset.animalExample);
  assert.deepEqual(actual,expected);assert.equal(d.activeElement,foot);if(!actual.length)assert.match(status.textContent,/nicht, dass ein solches Tier unmöglich/);else if(actual.length===1)assert.match(status.textContent,/keine sichere Artbestimmung/);else assert.match(status.textContent,/Vergleiche weitere Merkmale/);
 }
 zone.querySelector('[data-key-reset]').click();assert.equal(d.activeElement,legs);assert.equal(zone.querySelectorAll('li').length,7);for(const select of [legs,shell,foot])assert.equal(select.value,'');assert.equal(JSON.stringify(w.localStorage),storage);
 const keys={"bio_2_wirbellose_s1":[1,0],"bio_2_wirbellose_s2":[2,1],"bio_2_wirbellose_d1":[0,1],"bio_2_wirbellose_d2":[1,1],"bio_2_wirbellose_d4":[2,1],"bio_2_wirbellose_s3":[0,2],"bio_2_wirbellose_comparison":[1,2],"bio_2_wirbellose_s4":[2,3],"bio_2_wirbellose_d3":[1,3],"bio_2_wirbellose_s5":[0,4],"bio_2_wirbellose_d5":[2,4],"bio_2_wirbellose_ambiguity":[2,4]};
 const questions=w.currentChapterQuiz.questions;for(const [i,q]of questions.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();questions.forEach((item,n)=>d.querySelector(`input[name="chapter_q_${n}"][value="${i===n?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:92);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 assert.equal(w.chapterRevision(id),2);assert.equal(d.querySelectorAll('.bio-training-panel[data-assignment-mode="direct"]').length,5);assert.equal(d.querySelectorAll('.bio-training-card').length,15);assert.equal(d.querySelectorAll('[data-invertebrate-solution]').length,5);assert.equal(d.querySelectorAll('.invertebrate-data tbody tr').length,3);assert.equal(d.querySelectorAll('.invertebrate-profile svg').length,1);assert.equal(d.querySelectorAll('img').length,0);
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.ok(data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).every(q=>q.answers.every(a=>a.pts===0)));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-invertebrate-paper] tbody tr').length,7);assert.equal(pd.querySelectorAll('.invertebrate-data tbody tr').length,3);assert.equal(pd.querySelectorAll('.invertebrate-profile svg').length,1);assert.equal(pd.querySelectorAll('#ws-solutions [data-invertebrate-solution]').length,5);assert.equal(pd.querySelectorAll('#ws-biology-material [data-invertebrate-solution]').length,0);assert.equal(pd.querySelectorAll('[data-invertebrate-paper] select').length,0);paper.window.close();
 console.log('PASS: all 45 filter combinations, uncertainty/ambiguity, reset/focus/storage, 36 independently keyed quiz answers and review sections, 15 direct tasks, diagram, data and seven paper examples with five separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
