'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_kompetenzplan';
const keys={bio_4_plan_s1:[1,0],bio_4_plan_d1:[2,0],bio_4_plan_s2:[0,1],bio_4_plan_d2:[2,1],bio_4_plan_d3:[1,1],bio_4_plan_naechster_schritt:[0,2],bio_4_plan_speicher:[2,2],bio_4_plan_revision:[1,2]},correct=[1,2,0,2,1,0,2,1];
const topics=['bio_4_landwirtschaft_biodiversitaet','bio_4_siedlungsraeume','bio_4_kohlenstoff_klima','bio_4_genetik_gentechnik','bio_4_immunsystem_resistenzen','bio_4_nerven_hormone','bio_4_sexualitaet_verantwortung','bio_4_menschheitsentwicklung'],sections=[2,1,1,1,2,2,3,2];
const reasons=[[/Suchdauer/,/vergleichbarer/,/Standortunterschiede/],[/Bodenoberflächen/,/einzelner Vergleich/,/48 − 30/],[/103/,/Nettoänderung/,/abgezogen/],[/keine feste Reihenfolge/,/entweder/,/ein Halb/],[/Anzahl.*10/,/10\/19/,/Umwandlung/],[/Bei 50/,/hört/,/Gegenregel/],[/erkennbar/,/ersetzt.*nicht/,/Unterstützung/],[/keinen gemeinsamen Fundort/,/weder Begegnung noch direkte Abstammung/,/überschneiden/]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/physik_bay6/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const fixtures={[topics[0]]:{contentRevision:2,lastPercent:60,bestPercent:100,passed:true},[topics[1]]:{contentRevision:1,lastPercent:100},[topics[3]]:{contentRevision:2,lastPercent:100},[topics[4]]:null,[topics[5]]:{contentRevision:2,lastPercent:101},[topics[6]]:{contentRevision:2},[topics[7]]:{lastPercent:100}};
 w.localStorage.setItem('sciverse_chapter_quiz_results',JSON.stringify(fixtures));w.localStorage.setItem('sciverse_study_plan',JSON.stringify(['optik1']));const storage=JSON.stringify(w.localStorage);w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-bio4path-lab]'),select=zone.querySelector('select'),panels=[...zone.querySelectorAll('fieldset')],result=zone.querySelector('[role=status]'),check=zone.querySelector('[data-bio4path-check]'),reset=zone.querySelector('[data-bio4path-reset]'),progress=()=>[...zone.querySelectorAll('[data-bio4path-progress]')],plan=zone.querySelector('[data-bio4path-plan]'),all=zone.querySelector('[data-bio4path-all]');
 const rows=()=>[...zone.querySelectorAll('li[data-bio4path-progress]')];assert.equal(panels.length,8);assert.equal(rows().length,8);
 const readPlan=a=>{const url=new URL(a.href);assert.equal(url.pathname,'/physik_bay6/index.html');assert.doesNotMatch(url.hash,/answer|percent|lastPercent|60/);const p=new URLSearchParams(url.hash.split('?')[1]);assert.equal(p.get('mode'),'review');return p.get('plan').split(',');};assert.deepEqual(readPlan(plan),topics);assert.deepEqual(readPlan(all),topics);
 const labels=rows().map(r=>r.querySelector('.bio4path-saved').textContent);assert.match(labels[0],/60 Prozent/);assert.doesNotMatch(labels[0],/100/);assert.match(labels[1],/früheren Inhaltsfassung/);assert.match(labels[2],/Noch kein/);assert.match(labels[3],/100 Prozent/);for(const i of [4,5,6])assert.match(labels[i],/nicht lesbar/);assert.match(labels[7],/früheren Inhaltsfassung/);
 let decisions=0;for(let i=0;i<8;i++){
  select.value=String(i);select.dispatchEvent(new w.Event('change'));assert.deepEqual(panels.map(p=>p.hidden),[0,1,2,3,4,5,6,7].map(j=>j!==i));check.click();assert.equal(result.dataset.invalid,'answer');assert.equal(d.activeElement,panels[i].querySelector('input'));
  for(const[j,input]of [...panels[i].querySelectorAll('input')].entries()){input.click();assert.equal(result.textContent,'');assert.equal(rows()[i].dataset.state,'unanswered');check.click();assert.equal(result.dataset.supported,String(j===correct[i]));assert.match(result.textContent,reasons[i][j]);assert.equal(rows()[i].dataset.state,j===correct[i]?'correct':'review');assert.equal(d.activeElement,result);assert.equal(input.disabled,false);decisions++;}
  const expectedLink=new URL(result.querySelector('a').href);assert.equal(expectedLink.pathname,'/physik_bay6/index.html');const target=new URL(expectedLink.hash.slice(1),'https://example.test/physik_bay6/');assert.equal(target.searchParams.get('topic'),topics[i]);assert.equal(target.searchParams.get('mode'),'review');assert.equal(target.hash,'#learning-section-'+sections[i]);assert.ok(data[topics[i]].sections[sections[i]]);
 }
 assert.equal(decisions,24);select.value='0';select.dispatchEvent(new w.Event('change'));assert.match(result.textContent,reasons[0][2]);assert.equal(panels[0].querySelector('input[value="2"]').checked,true);
 for(let i=0;i<8;i++){select.value=String(i);select.dispatchEvent(new w.Event('change'));panels[i].querySelector('input[value="'+correct[i]+'"]').click();check.click();}
 assert.equal(plan.hidden,true);assert.equal(plan.hasAttribute('href'),false);assert.match(zone.querySelector('[data-bio4path-count]').textContent,/8 von 8.*8 Auswahlantworten richtig/);select.value='3';select.dispatchEvent(new w.Event('change'));panels[3].querySelector('input[value="0"]').click();assert.equal(plan.hidden,false);assert.deepEqual(readPlan(plan),[topics[3]]);assert.equal(result.textContent,'');
 select.value='';select.dispatchEvent(new w.Event('change'));assert.ok(panels.every(p=>p.hidden));check.click();assert.equal(result.dataset.invalid,'case');assert.equal(d.activeElement,select);reset.click();assert.equal(select.value,'0');assert.equal(d.activeElement,select);assert.equal(result.textContent,'');assert.equal(zone.querySelectorAll('input:checked').length,0);assert.deepEqual(readPlan(plan),topics);assert.equal(JSON.stringify(w.localStorage),storage);
 for(const corrupt of ['{broken','[]','null','"text"']){w.localStorage.setItem('sciverse_chapter_quiz_results',corrupt);w.dispatchEvent(new w.StorageEvent('storage',{key:'sciverse_chapter_quiz_results'}));assert.ok(rows().every(r=>r.textContent.includes('nicht lesbar')));}
 w.localStorage.setItem('sciverse_chapter_quiz_results',JSON.stringify(fixtures));const getItem=w.Storage.prototype.getItem;w.Storage.prototype.getItem=()=>{throw Error('blocked');};reset.click();assert.ok(rows().every(r=>r.textContent.includes('nicht lesbar')));w.Storage.prototype.getItem=getItem;reset.click();assert.match(rows()[0].textContent,/60 Prozent/);assert.equal(JSON.stringify(w.localStorage),storage);
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,9);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,12);assert.equal(d.querySelectorAll('.bio4path-route>li').length,8);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,8);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:88);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].answers.findIndex(a=>a.correct),1);assert.ok(practice[0].answers.every(a=>a.pts===0));const before=JSON.stringify(w.localStorage);w.playSuccessSound=()=>{};for(const answer of practice[0].answers){const button=[...d.querySelectorAll('.practice-box .practice-option')].find(e=>e.textContent===answer.text);w.handlePracticeAnswer(button,answer.correct,button.dataset.feedback);assert.ok(button.closest('.practice-box').querySelector('.feedback').innerText.includes(answer.feedback));assert.equal(button.disabled,false);}assert.equal(JSON.stringify(w.localStorage),before);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/physik_bay6/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.bio4path-paper-case').length,8);assert.equal(pd.querySelectorAll('.bio4path-paper-case li').length,24);assert.equal(pd.querySelectorAll('#ws-solutions [data-bio4path-solution]').length,3);assert.equal(pd.querySelectorAll('#ws-solutions .bio4path-case-solution').length,8);assert.equal(pd.querySelectorAll('#ws-biology-material [data-bio4path-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material input,#ws-biology-material select').length,0);assert.equal(pd.querySelectorAll('.bio4path-vocab .ws-glossary-entry').length,12);assert.doesNotMatch(pd.body.textContent,/undefined/);for(const[i,s]of [...pd.querySelectorAll('.bio4path-case-solution')].entries())for(let j=0;j<3;j++)assert.match(s.querySelectorAll('p')[j].textContent,reasons[i][j]);paper.window.close();
 console.log('PASS: 24 diagnostic decisions and 24 graded paths; 3 point-free answers; real routes, filtered plan links, current/old/missing/corrupt/blocked storage, state restoration/invalidation/reset and complete paper.');
})().catch(e=>{console.error(e);process.exitCode=1;});
