const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),sample=require('./fixtures/wiki_sample.json'),fields=Object.keys(sample),html=read('examples/klassenwiki.html');
const wait=()=>new Promise(resolve=>setTimeout(resolve,10));
(async()=>{
 const blobs=[],pending=[];const dom=new JSDOM(html,{url:'https://example.test/physik_bay6/examples/klassenwiki.html',runScripts:'dangerously',beforeParse(w){Object.defineProperty(w,'localStorage',{get(){throw Error('Storage deliberately unavailable');}});w.URL.createObjectURL=blob=>{blobs.push(blob);return 'blob:test-'+blobs.length;};w.URL.revokeObjectURL=()=>{};w.FileReader=class{readAsText(file){const run=()=>{this.result=file.content;this.onload();};if(file.deferred)pending.push(run);else setTimeout(run,0);}};w.document.addEventListener('click',e=>{if(e.target.closest('a[download]'))e.preventDefault();});}}),w=dom.window,d=w.document;
 const value=()=>Object.fromEntries(fields.map(key=>[key,d.getElementById(key).value]));const original=value();
 const fill=v=>{for(const key of fields){const input=d.getElementById(key);input.value=v[key];input.dispatchEvent(new w.Event('input',{bubbles:true}));}};
 async function load(content,options={}){const input=d.getElementById('load');Object.defineProperty(input,'files',{configurable:true,value:[{content,size:Buffer.byteLength(content),...options}]});input.dispatchEvent(new w.Event('change'));await wait();}
 const serialize=v=>JSON.stringify({application:'sciverse-klassenwiki',version:1,fields:v});
 assert.equal(d.querySelectorAll('#evidence tbody tr').length,6);const source=new JSDOM(JSON.parse(read('lang/de.json')).dgb8_information.sections[1].content);const rows=root=>[...root.querySelectorAll('tbody tr')].map(row=>[...row.cells].map(cell=>cell.textContent));assert.deepEqual(rows(d.getElementById('evidence')),rows(source.window.document.querySelector('[data-trace-events]')));source.window.close();
 assert.equal(d.querySelectorAll('script[src],iframe,img,link[rel=stylesheet]').length,0);for(const key of fields)assert.equal(d.getElementById(key).labels.length,1);
 fill(sample);for(const key of fields)assert.equal(d.getElementById('preview-'+key).textContent,sample[key]);d.getElementById('compare').click();assert.equal(d.activeElement.id,'compare-heading');assert.match(d.getElementById('compare-count').textContent,/5 von 5.*nicht richtige Antworten/);assert.equal(d.querySelectorAll('.compare-cell').length,5);
 for(const key of ['check-count','check-limit','check-reader']){const box=d.getElementById(key);box.checked=true;box.dispatchEvent(new w.Event('change'));}assert.match(d.getElementById('review-state').textContent,/Selbstprüfung dokumentiert.*keine automatische Fachprüfung/);fill({...sample,title:sample.title+'!'});assert.equal(d.querySelectorAll('input[type=checkbox]:checked').length,0);assert.equal(d.getElementById('comparison').hidden,true);
 fill(sample);d.getElementById('reset').click();assert.deepEqual(value(),original);assert.equal(d.activeElement.id,'title');d.getElementById('undo').click();assert.deepEqual(value(),sample);
 const payload='Eine Zeile mit <img src=x onerror="window.attack=1"> & </script>\nÄnderung: Ö, ß, →.';fill({...sample,observations:payload});const exported=w.htmlExport(),exp=new JSDOM(exported);assert.equal(exp.window.document.querySelectorAll('script,img,iframe').length,0);assert.equal(exp.window.document.querySelector('#article-observations + p').textContent,payload);for(const link of exp.window.document.querySelectorAll('a'))assert.ok(exp.window.document.querySelector(link.getAttribute('href')));assert.equal(w.attack,undefined);exp.window.close();
 fill(sample);d.getElementById('save').click();assert.equal(blobs.length,1);assert.equal(blobs[0].type,'application/json');d.getElementById('export').click();assert.equal(blobs[1].type,'text/html');assert.match(d.getElementById('notice').textContent,/nichts veröffentlicht/);
 const invalid=['broken','null','[]',serialize({...sample,title:3}),serialize({...sample,title:'x'.repeat(141)}),serialize({...sample,unknown:'field'}),JSON.stringify({application:'another-app',version:1,fields:sample}),JSON.stringify({application:'sciverse-klassenwiki',version:2,fields:sample})];
 for(const raw of invalid){await load(raw);assert.deepEqual(value(),sample);assert.match(d.getElementById('notice').textContent,/Datei nicht geladen/);}await load(serialize(sample),{size:100001});assert.deepEqual(value(),sample);assert.match(d.getElementById('notice').textContent,/Datei nicht geladen/);
 const loaded={...sample,title:'Eine geladene Arbeitsfassung'};await load(serialize(loaded));assert.deepEqual(value(),loaded);assert.equal(d.activeElement.id,'title');assert.equal(d.querySelectorAll('input[type=checkbox]:checked').length,0);d.getElementById('undo').click();assert.deepEqual(value(),sample);
 await load(serialize(loaded),{deferred:true});fill({...sample,title:'Während des Ladens weitergeschrieben'});pending.shift()();await wait();assert.equal(value().title,'Während des Ladens weitergeschrieben');assert.match(d.getElementById('notice').textContent,/Während des Ladens/);
 await load(serialize(loaded),{deferred:true});await load(serialize({...sample,title:'Neueste Dateiauswahl'}));pending.shift()();await wait();assert.equal(value().title,'Neueste Dateiauswahl');dom.window.close();
 const local=new JSDOM(html,{url:'file:///workshop.html',runScripts:'dangerously'});assert.equal(local.window.document.getElementById('chapter-link').href,'https://thingummyboop.github.io/physik_bay6/index.html#dgb8_information');local.window.close();
 const data=JSON.parse(read('lang/de.json')),paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=dgb8_information',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const file of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+file+'.js'));await wait();const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-wiki-tasks]>li').length,7);assert.equal(material.querySelectorAll('[data-wiki-protocol] tbody tr').length,4);assert.equal(material.querySelectorAll('[data-wiki-original]').length,1);assert.equal(material.querySelectorAll('[data-wiki-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-wiki-solution]').length,1);assert.equal(pd.getElementById('ws-solutions').hidden,true);paper.window.close();
 console.log('PASS: wiki editing/preview/comparison, manual review invalidation, reset/undo, safe standalone export, bounded imports, failed/racing imports preserve current work, offline link, original evidence and complete paper material.');
})().catch(error=>{console.error(error);process.exitCode=1;});
