const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),keys=require('./fixtures/thermal_assessment_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=waermelehre',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 assert.equal(w.chapterRevision('waermelehre'),5);assert.equal(w.currentChapterResult('waermelehre',{contentRevision:4,passed:true,bestPercent:100}).passed,false);assert.deepEqual([...w.currentChapterQuiz.questions].map(q=>q.id).sort(),Object.keys(keys).sort());
 let practice=0,assessed=0;const saved=JSON.stringify(w.localStorage);
 for(const section of data.waermelehre.sections)for(const q of section.quizzes||[]){const box=d.querySelector('.practice-box[data-id="'+q.id+'"]');for(const [a,answer]of q.answers.entries()){const b=[...box.querySelectorAll('button')].find(b=>b.textContent===answer.text);new w.Function(b.getAttribute('onclick')).call(b);assert.equal(b.classList.contains('is-correct'),a===keys[q.id]);assert.ok(box.querySelector('.feedback').innerText.includes(answer.feedback));practice++;}}
 assert.equal(JSON.stringify(w.localStorage),saved);
 for(const [index,q]of w.currentChapterQuiz.questions.entries()){
  assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);
  for(let a=0;a<3;a++){w.restartChapterQuiz();w.currentChapterQuiz.questions.forEach((other,i)=>d.querySelector(`input[name="chapter_q_${i}"][value="${i===index?a:keys[other.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results')).waermelehre;assert.equal(result.lastPercent,a===keys[q.id]?100:97);assert.equal(result.contentRevision,5);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));assessed++;}
 }
 assert.equal(practice,42);assert.equal(assessed,87);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=waermelehre',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,29);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.doesNotMatch(pd.body.textContent,/Pumpen in der Spitze|Wärmeleitung an Meteoriten|Sie werden größer und platzen/);for(const q of [...data.waermelehre.sections.flatMap(s=>s.quizzes||[]),...data.waermelehre.diplom.questions]){assert.ok(pd.getElementById('ws-content').textContent.includes(q.question));assert.ok(pd.getElementById('ws-solutions').textContent.includes(q.answers[keys[q.id]].text));}paper.window.close();
 console.log('PASS: all 29 thermal questions independently keyed; 87 assessed and 42 free answer paths; feedback, revision 5 migration and corresponding paper questions/solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
