'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),id='bio_3_geologie_lebensraeume';
const keys={bio_3_geologie_s1:[1,0],bio_3_geologie_d1:[2,0],bio_3_geologie_path:[0,0],bio_3_geologie_s2:[1,1],bio_3_geologie_d2:[2,1],bio_3_geologie_s3:[0,2],bio_3_geologie_d3:[1,2],bio_3_geologie_mean:[2,2],bio_3_geologie_s4:[0,3],bio_3_geologie_restore:[1,3]};
// Columns: cooling, weathering-to-deposition, compaction, metamorphism, melting.
const actions=['cool','weather','compact','transform','melt'];
const outcomes={magma:['igneous',null,null,null,null],igneous:[null,'sediment',null,'metamorphic','magma'],sediment:[null,null,'sedimentary',null,null],sedimentary:[null,'sediment',null,'metamorphic','magma'],metamorphic:[null,'sediment',null,'metamorphic','magma']};
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-geology-lab]'),start=zone.querySelector('[data-geology-start]'),process=zone.querySelector('[data-geology-process]'),check=zone.querySelector('[data-geology-check]'),reset=zone.querySelector('[data-geology-reset]'),current=zone.querySelector('[data-geology-current]'),feedback=zone.querySelector('[data-geology-feedback]'),history=zone.querySelector('[data-geology-history]'),storage=JSON.stringify(w.localStorage);
 const begin=value=>{start.value=value;start.dispatchEvent(new w.Event('change'));};const act=value=>{process.value=value;process.dispatchEvent(new w.Event('change'));assert.equal(feedback.textContent,'');check.click();};let decisions=0;
 for(const [state,targets]of Object.entries(outcomes))for(const [i,target]of targets.entries()){
  begin(state);assert.equal(zone.dataset.steps,'0');assert.equal(history.children.length,0);act(actions[i]);assert.equal(zone.dataset.state,target||state);assert.equal(zone.dataset.steps,target?'1':'0');assert.equal(feedback.dataset.correct,String(!!target));assert.equal(history.children.length,target?1:0);assert.ok(feedback.textContent.length>45);if(target){assert.equal(d.activeElement,current);assert.equal(process.value,'');}decisions++;
 }
 // Paths required by the teaching tasks, including branching and repeated metamorphism.
 for(const [initial,route,target]of [['igneous',['weather','compact'],'sedimentary'],['igneous',['transform','weather','compact'],'sedimentary'],['sedimentary',['melt','cool'],'igneous'],['metamorphic',['transform','transform'],'metamorphic']]){begin(initial);route.forEach(act);assert.equal(zone.dataset.state,target);assert.equal(zone.dataset.steps,String(route.length));}
 begin('igneous');for(let i=0;i<6;i++){act('melt');act('cool');}assert.equal(zone.dataset.steps,'12');assert.equal(history.children.length,8);assert.equal(history.start,5);assert.match(zone.querySelector('[data-geology-count]').textContent,/12 Schritte/);
 process.value='';check.click();assert.equal(zone.dataset.steps,'12');assert.equal(d.activeElement,process);assert.match(feedback.textContent,/Wähle einen Vorgang/);begin('');assert.equal(zone.dataset.state,'igneous');assert.match(feedback.textContent,/Startmaterialien/);reset.click();assert.equal(start.value,'igneous');assert.equal(zone.dataset.steps,'0');assert.equal(d.activeElement,start);assert.equal(feedback.textContent,'');assert.equal(JSON.stringify(w.localStorage),storage);
 assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));
 for(const [i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('.geology-plates svg[data-worksheet-static]').length,4);assert.equal(d.querySelectorAll('.geology-rock-cases .geology-card').length,3);assert.equal(d.querySelectorAll('.geology-sites .geology-card').length,2);assert.equal(d.querySelectorAll('[data-geology-solution]').length,4);
 const numbers=s=>[...d.querySelectorAll(s+' tbody tr')].map(r=>[...r.querySelectorAll('td')].map(e=>Number(e.textContent)));assert.deepEqual(numbers('.geology-soil'),[[76,74,75],[42,40,41]]);assert.deepEqual(numbers('.geology-soil').map(row=>row.reduce((a,b)=>a+b)/3),[75,41]);assert.equal((40-12)/40*100,70);const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.ok(practice[0].answers.every(a=>a.pts===0));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-geology-paper]').length,1);assert.equal(pd.querySelectorAll('.geology-plates svg').length,4);assert.equal(pd.querySelectorAll('.geology-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('.geology-routes tbody tr').length,5);assert.equal(pd.querySelectorAll('.geology-soil tbody tr').length,2);assert.equal(pd.querySelectorAll('.geology-resources tbody tr').length,2);assert.equal(pd.querySelectorAll('#ws-solutions [data-geology-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-geology-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);paper.window.close();
 console.log(`PASS: ${decisions} state/process decisions, four teaching routes, 12-step history/reset/focus/storage, 30 independently keyed quiz answers, 12 tasks, 16 terms and four paper diagrams.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
