'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_nerven_hormone';
const keys={bio_4_steuerung_s1:[1,0],bio_4_steuerung_d1:[2,0],bio_4_steuerung_synapse:[0,0],bio_4_steuerung_s2:[2,1],bio_4_steuerung_d4:[1,1],bio_4_steuerung_d2:[0,1],bio_4_steuerung_feedback:[1,2],bio_4_steuerung_modell:[2,2],bio_4_steuerung_s3:[0,3],bio_4_steuerung_d3:[2,3],bio_4_steuerung_daten:[1,3]};
// Complete independently specified trajectories, including before and after the one-time influence.
const cases=[['40','-10',[40,30,35,40,45,50],[40,30,30,30,30,30]],['40','0',[40,40,45,50,50,50],[40,40,40,40,40,40]],['40','10',[40,50,50,50,50,50],[40,50,50,50,50,50]],['50','-10',[50,40,45,50,50,50],[50,40,40,40,40,40]],['50','0',[50,50,50,50,50,50],[50,50,50,50,50,50]],['50','10',[50,60,55,50,50,50],[50,60,60,60,60,60]],['60','-10',[60,50,50,50,50,50],[60,50,50,50,50,50]],['60','0',[60,60,55,50,50,50],[60,60,60,60,60,60]],['60','10',[60,70,65,60,55,50],[60,70,70,70,70,70]]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-regulation-lab]'),start=zone.querySelector('[data-regulation-start]'),change=zone.querySelector('[data-regulation-change]'),mode=zone.querySelector('[data-regulation-mode]'),check=zone.querySelector('[data-regulation-check]'),reset=zone.querySelector('[data-regulation-reset]'),result=zone.querySelector('[data-regulation-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.invalid,undefined);};
 for(const[a,c,on,off]of cases)for(const m of ['on','off']){
  set(start,a);set(change,c);set(mode,m);check.click();assert.equal(d.activeElement,result);assert.equal(result.querySelectorAll('h4').length,1);const expected=m==='on'?on:off,rows=[...result.querySelectorAll('tbody tr')];assert.deepEqual(rows.map(e=>Number(e.dataset.regulationValue)),expected);
  assert.deepEqual(rows.map(e=>e.lastChild.textContent),expected.map(v=>String(Math.abs(v-50))));assert.deepEqual(rows.map(e=>e.dataset.regulationDelta),expected.map((v,i)=>i?String(v-expected[i-1]):'initial'));
  const points=result.querySelector('[data-regulation-line]').getAttribute('points').split(' ').map(s=>s.split(',').map(Number));assert.deepEqual(points.map(([x])=>x),[40,90,140,190,240,290]);assert.deepEqual(points.map(([,y])=>(218-y)/2),expected);assert.equal(result.querySelectorAll('.regulation-chart circle').length,6);
  const hit=expected.slice(1).indexOf(50),conclusion=result.querySelector('[data-regulation-conclusion]').textContent;if(hit<0)assert.match(conclusion,/keinem/);else if(hit===0)assert.match(conclusion,/bereits/);else assert.ok(conclusion.includes('Regelschritt '+hit));assert.match(result.textContent,/keine Behandlungsvorhersage/);
 }
 for(const[input,name]of [[start,'start'],[change,'change'],[mode,'mode']]){reset.click();set(input,'');check.click();assert.equal(result.dataset.invalid,name);assert.equal(d.activeElement,input);}reset.click();assert.equal(start.value,'60');assert.equal(change.value,'10');assert.equal(mode.value,'on');assert.equal(result.textContent,'');assert.equal(d.activeElement,start);assert.equal(JSON.stringify(w.localStorage),storage);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('[data-regulation-solution]').length,4);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 assert.deepEqual([...d.querySelectorAll('.regulation-targets tbody tr')].map(e=>[...e.children].map(c=>c.textContent)),[['A','für H'],['B','für G'],['C','für H und G'],['D','weder für H noch für G']]);const times=[...d.querySelectorAll('.regulation-data tbody tr')].map(e=>e.children[1].textContent.split(' / ').map(Number));assert.deepEqual(times,[[300,320,280,310,290],[260,280,300,270,290]]);assert.deepEqual(times.map(r=>r.reduce((a,b)=>a+b)/5),[300,280]);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,11);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].id,'bio_4_nerven_extra_stress');assert.ok(practice[0].answers.every(a=>a.pts===0));const practiceStorage=JSON.stringify(w.localStorage);w.playSuccessSound=()=>{};for(const answer of practice[0].answers){const button=[...d.querySelectorAll('.practice-box .practice-option')].find(e=>e.textContent===answer.text);assert.ok(button);w.handlePracticeAnswer(button,answer.correct,button.dataset.feedback);assert.ok(button.closest('.practice-box').querySelector('.feedback').innerText.includes(answer.feedback));assert.equal(button.classList.contains(answer.correct?'is-correct':'is-wrong'),true);assert.equal(button.disabled,false);}assert.equal(JSON.stringify(w.localStorage),practiceStorage);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.ok(pd.body.textContent.includes('Papierwerkstatt: Gegenregelung.'));assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(pd.querySelectorAll('.regulation-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('#ws-solutions [data-regulation-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-regulation-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);assert.doesNotMatch(pd.body.textContent,/undefined/);for(const s of data[id].sources){assert.ok(s.title&&s.url.startsWith('https://'));assert.ok(pd.body.textContent.includes(s.title));}
 const paperRows=[...pd.querySelectorAll('.regulation-paper tbody tr')];assert.equal(paperRows.length,6);const expectedPaper=[cases[8][2],cases[8][3],cases[0][2],cases[4][2],cases[2][2],cases[6][3]];for(const[row,values]of paperRows.map((r,i)=>[r,expectedPaper[i]])){assert.equal(row.children[1].textContent,values.join(' → '));assert.equal(row.children[3].textContent,values.slice(1).map(n=>Math.abs(n-50)).join(' → '));}const plan=pd.querySelector('[data-regulation-solution="3"]').textContent;for(const s of ['300 ms','280 ms','140 Minuten','75 + 20 + 20 + 5 = 120'])assert.ok(plan.includes(s));paper.window.close();
 console.log('PASS: 18 independently specified trajectories, values/changes/distances/graphs, invalid/reset/focus/storage, 33 quiz and 3 practice paths, complete paper cases and data.');
})().catch(e=>{console.error(e);process.exitCode=1;});
