const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),topic='linsen_spiegel',keys=require('./fixtures/optics_research_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+topic,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const expectedSections=[0,0,0,0,0,1,1,2,2,2,2,2,3,4,4,4,4,5,6,6,6,7,7,7,7,8,8,8,8,9,9,9],qs=w.currentChapterQuiz.questions;
 assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));assert.deepEqual(Array.from(qs,q=>q.sectionIndex),expectedSections);let answers=0;
 for(const [i,q]of qs.entries())for(let a=0;a<3;a++){
  assert.equal(q.answers.length,3);qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${i===j?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[topic];assert.equal(result.lastPercent,a===keys[q.id]?100:97);assert.equal(result.contentRevision,7);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));if(a!==keys[q.id]){const review=d.querySelector('#chapter-quiz-result button[onclick^="reviewChapterSection"]');assert.equal(review.getAttribute('onclick'),`reviewChapterSection(${expectedSections[i]})`);}answers++;
 }
 assert.equal(answers,96);assert.equal(w.currentChapterResult(topic,{passed:true,contentRevision:6,bestPercent:100}).passed,false);
 assert.deepEqual(data[topic].sections.map(s=>s.id),['sec0','sec1','sec4','sec3','optische_geraete_recherche','sec2','sec6','sec7','sec8','sec5']);
 assert.equal(d.querySelectorAll('[data-optics-source]').length,4);assert.equal(d.querySelectorAll('[data-optics-research-task]>li').length,7);assert.ok(d.querySelector('[data-optics-research-solution]'));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+topic,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pd.getElementById('ws-physics-material');assert.equal(material.querySelectorAll(':scope>article').length,10);assert.equal(material.querySelectorAll('[data-optics-source]').length,4);assert.equal(material.querySelectorAll('[data-optics-research-task]>li').length,7);assert.ok(material.querySelector('[data-optics-source-protocol]'));assert.ok(!material.querySelector('[data-optics-research-solution]'));assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.querySelectorAll('#ws-solutions .ws-paper-solution').length,3);assert.match(pd.getElementById('ws-solutions').textContent,/Bildabstände: 5 cm, 10 cm, 15 cm/);assert.match(pd.getElementById('ws-solutions').textContent,/Pfeilhöhen 0,5, 1 und 2 cm/);assert.match(pd.getElementById('ws-solutions').textContent,/Zwei Seiten, die nur denselben Werbetext kopieren/);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,32);paper.window.close();
 console.log('PASS: all 96 independently keyed optics answers, exact section review, revision 7; four source cards, seven research tasks and separated paper solutions in ten ordered sections.');
})().catch(e=>{console.error(e);process.exitCode=1;});
