const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb6_handeln',keys=require('./fixtures/dgb6_action_keys.json');
const cases={system:[{key:1,reason:/Arbeitsspeicher.*Version 1/},{key:2,reason:/Ursache bleibt offen/}],transfer:[{key:0,reason:/lokales Netzwerk.*externer Dienst/},{key:2,reason:/lokaler Pfad.*Datei/}],participation:[{key:1,reason:/Zwei Drittel.*Hälfte/},{key:0,reason:/Fünf Punkte.*drei/}],balance:[{key:2,reason:/Ziel und Bedarf/},{key:1,reason:/begrenzte Fehler.*Bedarf/}]};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();const stored=JSON.stringify(w.localStorage);
 for(const [name,expected]of Object.entries(cases)){
  const zone=d.querySelector('[data-action-lab="'+name+'"]'),control=zone.querySelector('select'),cards=[...zone.querySelectorAll('[data-boundary-case]')],status=zone.querySelector('[role=status]');assert.equal(cards.length,2);assert.equal(d.getElementById(control.getAttribute('aria-describedby')),status);
  for(const [n,e]of expected.entries()){control.value=String(n);control.dispatchEvent(new w.Event('change'));assert.equal(cards.filter(c=>!c.hidden).length,1);assert.equal(cards[n].hidden,false);assert.match(status.textContent,/Lies den Fall/);for(let a=0;a<3;a++){const b=cards[n].querySelectorAll('button')[a];b.click();assert.equal(status.textContent.startsWith('Richtig:'),a===e.key);if(a===e.key)assert.match(status.textContent,e.reason);assert.equal(b.getAttribute('aria-describedby'),status.id);}}
  zone.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.match(status.textContent,/Lies den Fall/);
 }
 assert.equal(JSON.stringify(w.localStorage),stored);const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);
 assert.equal(d.querySelectorAll('[data-action-tasks]>li').length,18);
 assert.equal(read('examples/datenaustausch-probe.txt'),'Version 1\nTreffpunkt: Werkraum 12\nPrüfsatz: Drei blaue Kreise.\n');assert.equal(d.querySelector('[data-action-download]').href,'https://example.test/site/examples/datenaustausch-probe.txt');
 assert.equal(d.querySelector('[data-action-file]').textContent,'Version 1\nTreffpunkt: Werkraum 12\nPrüfsatz: Drei blaue Kreise.');
 assert.match(d.querySelector('[data-action-tasks="transfer"]').textContent,/Verbinden.*Status.*Version 2, Werkraum 14.*Prüfsatz.*noch nicht ausgeführt/s);
 assert.match(d.querySelector('[data-action-solution="transfer"]').textContent,/Version 2.*Werkraum 14.*Drei blaue Kreise.*USB-Erfolg belegt keine WLAN-Verbindung/s);
 assert.match(d.querySelector('[data-action-solution="participation"]').textContent,/12 ÷ 18 = 2\/3.*12 ÷ 24 = 1\/2.*12 zu 12.*5 > 3/s);
 assert.equal(12/18,2/3);assert.equal(12/24,1/2);assert.equal(6+6,12);assert.equal(2+3,5);
 assert.match(d.querySelector('[data-action-solution="balance"]').textContent,/60 Wh.*6 Wh.*54 Wh = 0,054 kWh.*keine vollständige Umweltbilanz/s);assert.equal(30*2-3*2,54);
 assert.equal(w.chapterRevision(id),1);assert.equal(w.currentChapterResult(id,{contentRevision:0,passed:true,lastPercent:100}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));
 for(const [n,q]of qs.entries()){assert.equal(q.sectionIndex,Math.floor(n/2));assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let a=0;a<3;a++){w.restartChapterQuiz();qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===n?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:88);assert.equal(result.contentRevision,1);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[a].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[2,0,1]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-action-paper] .ai-paper-case').length,8);assert.equal(material.querySelectorAll('[data-action-tasks]>li').length,18);assert.equal(material.querySelectorAll('[data-action-solution],button,select,input').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-action-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.match(material.textContent,/noch nicht ausgeführt/);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,8);paper.window.close();
 console.log('PASS: 24 case decisions, 24 assessed answer paths, independent vote/energy arithmetic and transfer file, revision/review IDs, three free practices, reset/focus/storage and eight paper cases with four separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
