'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),id='bio_3_boden_mikroorganismen';
const keys={bio_3_boden_s1:[1,0],bio_3_boden_pores:[2,0],bio_3_boden_s2:[0,1],bio_3_boden_fair:[1,1],bio_3_boden_loss:[2,1],bio_3_boden_s3:[0,2],bio_3_boden_water:[1,2],bio_3_boden_roots:[1,2],bio_3_boden_s4:[2,3],bio_3_boden_plan:[0,3]};
const pairs={moisture:[['same','fair','other','confounded'],['fair','same','confounded','other'],['other','confounded','same','fair'],['confounded','other','fair','same']],temperature:[['same','other','fair','confounded'],['other','same','confounded','fair'],['fair','confounded','same','other'],['confounded','fair','other','same']]};
const rows=['A','B','C','D'],means=['6','8,5','8','9'],losses=['40','15','20','10'];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-soil-lab]'),factor=zone.querySelector('[data-soil-factor]'),left=zone.querySelector('[data-soil-left]'),right=zone.querySelector('[data-soil-right]'),check=zone.querySelector('[data-soil-check]'),reset=zone.querySelector('[data-soil-reset]'),result=zone.querySelector('[data-soil-result]'),storage=JSON.stringify(w.localStorage);
 const select=(el,value)=>{el.value=value;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.verdict,undefined);};let cases=0;
 for(const [influence,matrix]of Object.entries(pairs))for(let i=0;i<4;i++)for(let j=0;j<4;j++){
  select(factor,influence);select(left,rows[i]);select(right,rows[j]);check.click();assert.equal(result.dataset.verdict,matrix[i][j]);assert.equal(result.children.length,5);assert.ok(result.textContent.includes(means[i]+' g mittlere Restmasse'));assert.ok(result.textContent.includes(means[j]+' g mittlere Restmasse'));assert.ok(result.textContent.includes(losses[i]+' % der Anfangsmasse'));assert.ok(result.textContent.includes(losses[j]+' % der Anfangsmasse'));assert.equal(d.activeElement,result);cases++;
 }
 for(const el of [factor,left,right]){reset.click();select(el,'');check.click();assert.equal(result.dataset.verdict,'invalid');assert.equal(d.activeElement,el);assert.equal(result.children.length,1);}
 reset.click();assert.equal(factor.value,'moisture');assert.equal(left.value,'A');assert.equal(right.value,'B');assert.equal(d.activeElement,factor);assert.equal(result.textContent,'');assert.equal(JSON.stringify(w.localStorage),storage);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;
 assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,2);assert.equal(d.querySelectorAll('[data-soil-solution]').length,4);
 const cells=selector=>[...d.querySelectorAll(selector+' tbody tr')].map(r=>[...r.children].map(e=>e.textContent));assert.deepEqual(cells('.soil-trials'),[['A','20 °C','feucht, nicht vernässt','6 / 6,5 / 5,5'],['B','20 °C','trocken','8,5 / 9 / 8'],['C','8 °C','feucht, nicht vernässt','8 / 7,5 / 8,5'],['D','8 °C','trocken','9 / 9,5 / 8,5']]);assert.deepEqual(cells('.soil-plans'),[['A','0 m²','160 m²','80 m²'],['B','40 m²','120 m²','120 m²'],['C','100 m²','60 m²','180 m²']]);
 assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));
 for(const [i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.ok(practice[0].answers.every(a=>a.pts===0));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-soil-paper]').length,1);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,2);assert.equal(pd.querySelectorAll('.soil-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('.soil-trials tbody tr').length,4);assert.equal(pd.querySelectorAll('.soil-plans tbody tr').length,3);assert.equal(pd.querySelectorAll('#ws-solutions [data-soil-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-soil-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);paper.window.close();
 console.log(`PASS: ${cases} independent comparison decisions, four data calculations, stale results/invalid inputs/reset/focus/storage, 30 quiz answers, 12 direct tasks, 16 terms and paper material.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
