const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb7_orientierung',keys=require('./fixtures/dgb7_orientation_keys.json'),expected=require('./fixtures/feed_expectations');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const lab=d.querySelector('.recommendation-model'),inputs=[...lab.querySelectorAll('input')],rule=lab.querySelector('select'),status=lab.querySelector('[role=status]'),before=JSON.stringify(w.localStorage),source=lab.querySelector('[data-feed-material]').innerHTML;
 assert.deepEqual([...lab.querySelectorAll('[data-feed-source]')].map(e=>[Number(e.dataset.feedId),e.dataset.feedCategory]),[[1,'Sport'],[2,'Kunst'],[3,'Wissen'],[4,'Sport'],[5,'Kunst'],[6,'Wissen']]);
 const selected=()=>[...lab.querySelectorAll('[data-feed-selected]')].map(e=>Number(e.dataset.feedSelected));assert.deepEqual(selected(),[1,4,2]);
 let states=0;for(let s=0;s<=3;s++)for(let k=0;k<=3;k++)for(let z=0;z<=3;z++)for(const mode of ['common','profile','mix']){
  const counts=[s,k,z];inputs.forEach((e,i)=>{e.value=String(counts[i]);e.dispatchEvent(new w.Event('input'));});rule.value=mode;rule.dispatchEvent(new w.Event('change'));assert.deepEqual(selected(),expected(counts,mode));
  for(const [i,input]of inputs.entries()){assert.equal(input.getAttribute('aria-valuetext'),counts[i]+' Modellklicks');assert.equal(lab.querySelector('[data-feed-value="'+input.dataset.feedCount+'"]').textContent,String(counts[i]));assert.equal(d.getElementById(input.getAttribute('aria-describedby')),status);}
  assert.match(status.textContent,/keine Qualitätsbewertung/);assert.equal(lab.querySelector('[data-feed-material]').innerHTML,source);states++;
 }
 assert.equal(states,192);lab.querySelector('[data-feed-reset]').click();assert.deepEqual(inputs.map(i=>i.value),['3','1','0']);assert.equal(rule.value,'profile');assert.deepEqual(selected(),[1,4,2]);assert.equal(d.activeElement,inputs[0]);assert.equal(JSON.stringify(w.localStorage),before);
 w.enhanceCoreLearning(data[id],id,'de');assert.equal(lab.querySelectorAll('[data-feed-selected]').length,3);assert.equal(lab.querySelectorAll('[data-feed-reset]').length,1);
 const rows=[...d.querySelectorAll('[data-ai-tests] tbody tr')];assert.equal(rows.length,6);assert.deepEqual(rows.map(r=>r.cells[1].textContent===r.cells[2].textContent),[true,true,true,true,false,false]);assert.equal(d.querySelectorAll('[data-orientation-tasks]>li').length,15);assert.equal(d.querySelectorAll('[data-design-observations]>li').length,4);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));assert.equal(w.chapterRevision(id),1);assert.equal(w.currentChapterResult(id,{contentRevision:0,lastPercent:100}).outdated,true);
 for(const [n,q]of qs.entries()){assert.equal(q.sectionIndex,Math.floor(n/2));assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let a=0;a<3;a++){w.restartChapterQuiz();qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===n?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,a===keys[q.id]?100:88);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[a].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[0,1,0]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const m=pd.getElementById('ws-dgb-material');assert.equal(m.querySelectorAll('[data-feed-paper] [data-feed-source]').length,6);assert.equal(m.querySelectorAll('[data-orientation-tasks]>li').length,15);assert.equal(m.querySelectorAll('[data-orientation-solution],button,input,select').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-orientation-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.match(m.textContent,/Profilregel.*Gleichstand.*Mischregel/s);paper.window.close();
 console.log('PASS: all 192 recommendation states, independent card ordering, stable source material, reset/focus/storage/re-init, six AI test rows, 24 independent quiz paths and four separate worksheet solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
