const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{
 const data=JSON.parse(read('lang/de.json')),id='bio_2_sinne_gehirn';
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});
 for(const file of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+file+'.js'));
 await w.renderTopic();assert.equal(d.querySelectorAll('.chapter-question').length,12);
 assert.equal(w.currentChapterResult(id,{passed:true}).outdated,true);
 w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();

 const zone=d.querySelector('[data-contrast-lab]'),centers=[...zone.querySelectorAll('[data-contrast-center]')],backs=[...zone.querySelectorAll('[data-contrast-background]')],original=centers.map(e=>e.outerHTML),storage=JSON.stringify(w.localStorage);
 const expected={original:['#222222','#eeeeee'],swapped:['#eeeeee','#222222'],equal:['#bbbbbb','#bbbbbb']};
 const verify=mode=>{assert.deepEqual(backs.map(e=>e.getAttribute('fill')),expected[mode]);assert.deepEqual(centers.map(e=>e.outerHTML),original);assert.equal(zone.querySelectorAll('[aria-pressed="true"]').length,1);assert.equal(zone.querySelector('[aria-pressed="true"]').dataset.contrastMode,mode);};
 verify('original');for(const from of Object.keys(expected))for(const to of [...Object.keys(expected),'reset']){zone.querySelector('[data-contrast-mode="'+from+'"]').click();const button=zone.querySelector(to==='reset'?'[data-contrast-reset]':'[data-contrast-mode="'+to+'"]');button.focus();button.click();verify(to==='reset'?'original':to);assert.equal(d.activeElement,to==='reset'?zone.querySelector('[data-contrast-mode="original"]'):button);assert.match(zone.querySelector('[role=status]').textContent,/nicht verändert/);}
 assert.equal(JSON.stringify(w.localStorage),storage);assert.match(zone.textContent,/keine Messung deiner Sehfähigkeit/);
 const keys={"bio_2_sinne_gehirn_s1":[1,0],"bio_2_sinne_gehirn_s2":[2,1],"bio_2_sinne_gehirn_d1":[0,1],"bio_2_sinne_gehirn_d2":[1,1],"bio_2_sinne_gehirn_s3":[2,2],"bio_2_sinne_gehirn_d3":[0,2],"bio_2_sinne_gehirn_d4":[2,2],"bio_2_sinne_gehirn_s4":[1,3],"bio_2_sinne_gehirn_data":[0,3],"bio_2_sinne_gehirn_s5":[2,4],"bio_2_sinne_gehirn_d5":[1,4],"bio_2_sinne_gehirn_control":[1,4]};
 const questions=w.currentChapterQuiz.questions;for(const [i,q]of questions.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();questions.forEach((item,n)=>d.querySelector(`input[name="chapter_q_${n}"][value="${i===n?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:92);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 assert.equal(w.chapterRevision(id),2);assert.equal(d.querySelectorAll('.bio-training-panel[data-assignment-mode="direct"]').length,5);assert.equal(d.querySelectorAll('.bio-training-card').length,15);assert.equal(d.querySelectorAll('[data-senses-solution]').length,5);assert.equal(d.querySelectorAll('.senses-data tbody tr').length,2);assert.equal(d.querySelectorAll('.senses-pathway svg').length,1);assert.equal(d.querySelectorAll('img').length,0);
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.ok(data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).every(q=>q.answers.every(a=>a.pts===0)));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-senses-paper] svg').length,3);assert.equal(pd.querySelectorAll('.senses-data tbody tr').length,2);assert.equal(pd.querySelectorAll('.senses-protocol tbody tr').length,3);assert.equal(pd.querySelectorAll('.senses-pathway svg').length,1);assert.equal(pd.querySelectorAll('#ws-solutions [data-senses-solution]').length,5);assert.equal(pd.querySelectorAll('#ws-biology-material [data-senses-solution]').length,0);assert.equal(pd.querySelectorAll('[data-senses-paper] button').length,0);paper.window.close();
 console.log('PASS: 12 contrast transitions, unchanged target colors/geometry, focus/reset/storage, 36 independently keyed quiz answers and review sections, 15 direct tasks, pathway diagram, data and three paper comparisons with five separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
