const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math2_4_relative_zahlen';
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const start=d.getElementById('integer-start'),steps=d.getElementById('integer-steps'),dir=d.getElementById('integer-direction'),button=d.querySelector('[data-integer-run]'),status=d.querySelector('[data-integer-status]'),path=d.querySelector('[data-integer-path]');
 for(let s=-10;s<=10;s++)for(let n=0;n<=10;n++)for(const op of ['plus','minus']){start.value=String(s);steps.value=String(n);dir.value=op;button.click();const values=path.textContent.split(': ')[1].split(' → ').map(Number);assert.equal(values.length,n+1);assert.equal(values[0],s);assert.equal(values[n],op==='plus'?s+n:s-n);for(let i=1;i<values.length;i++)assert.equal(values[i]-values[i-1],op==='plus'?1:-1);}
 for(const [s,n]of [['','2'],['1',''],['1.5','2'],['1','2.5'],['-11','1'],['11','1'],['0','-1'],['0','11']]){start.value=s;steps.value=n;button.click();assert.match(status.textContent,/Gib eine ganze/);assert.equal(path.textContent,'');}
 start.value='-3';steps.value='5';dir.value='plus';steps.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(status.textContent,/= 2/);steps.dispatchEvent(new w.Event('input'));assert.equal(status.textContent,'');assert.equal(path.textContent,'');
 assert.equal(w.currentChapterQuiz.questions.length,4);for(const [i,q]of w.currentChapterQuiz.questions.entries())for(let a=0;a<q.answers.length;a++){w.currentChapterQuiz.questions.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${i===j?a:item.answers.findIndex(a=>a.correct)}"]`).checked=true);w.submitChapterQuiz();assert.equal(JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id].lastPercent,q.answers[a].correct?100:75);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));}
 assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100}).passed,false);dom.window.close();console.log('PASS: 462 integer paths, eight invalid inputs, Enter/changed input, all twelve answer paths and old-result revision.');})().catch(e=>{console.error(e);process.exitCode=1;});
