const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb7_handeln',keys=require('./fixtures/dgb7_action_keys.json');
const expected={device:[{key:1,reason:/lokal.*ausgefallene Verbindung/},{key:2,reason:/Zweck.*unnötige Übertragung/}],protection:[{key:0,reason:/unabhängige Prüfweg/},{key:2,reason:/Unabhängiger Speicherort.*Wiederherstellung/}],resources:[{key:1,reason:/Reparatur.*Nutzungsdauer/},{key:0,reason:/Schadstoffe.*Materialien/}]};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const before=JSON.stringify(w.localStorage);
 for(const [name,expectations]of Object.entries(expected)){
  const zone=d.querySelector('[data-device-lab="'+name+'"]'),control=zone.querySelector('select'),cases=[...zone.querySelectorAll('[data-boundary-case]')],result=zone.querySelector('[role=status]');assert.equal(cases.length,2);assert.equal(d.getElementById(control.getAttribute('aria-describedby')),result);
  for(const [n,e]of expectations.entries()){control.value=String(n);control.dispatchEvent(new w.Event('change'));assert.equal(cases.filter(c=>!c.hidden).length,1);assert.equal(cases[n].hidden,false);assert.match(result.textContent,/Lies den Fall/);for(let a=0;a<3;a++){const b=cases[n].querySelectorAll('button')[a];b.click();assert.equal(result.textContent.startsWith('Richtig:'),a===e.key);if(a===e.key)assert.match(result.textContent,e.reason);assert.equal(b.getAttribute('aria-describedby'),result.id);}}
  zone.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.match(result.textContent,/Lies den Fall/);
 }
 assert.equal(JSON.stringify(w.localStorage),before);const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);assert.equal(d.querySelectorAll('[data-device-tasks]>li').length,14);assert.equal(d.querySelectorAll('[data-device-system]>li').length,4);
 assert.match(d.querySelector('[data-device-solution="resources"]').textContent,/120 W.*1800 Wh = 1,8 kWh.*600 Wh = 0,6 kWh.*1,2 kWh/s);
 assert.match(d.querySelector('[data-device-lab="device"]').textContent,/Ohne Internet bleibt die lokale Regelung eingeschaltet/);assert.match(d.querySelector('[data-device-lab="resources"]').textContent,/weiterhin Sicherheitsupdates/);assert.match(d.querySelector('[data-device-tasks="protection"]').textContent,/unabhängigen Speicherort.*Original bleibt erhalten.*zurück.*öffne.*vergleiche/s);
 assert.equal(w.chapterRevision(id),1);assert.equal(w.currentChapterResult(id,{contentRevision:0,lastPercent:100}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));
 for(const [n,q]of qs.entries()){assert.equal(q.sectionIndex,Math.floor(n/2));assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let a=0;a<3;a++){w.restartChapterQuiz();qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===n?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:88);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[a].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[0,1,0]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-device-paper] .ai-paper-case').length,6);assert.equal(material.querySelectorAll('[data-device-tasks]>li').length,14);assert.equal(material.querySelectorAll('[data-device-solution],button,select,input').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-device-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.match(material.textContent,/noch nicht ausgeführt/);paper.window.close();
 console.log('PASS: 18 independently keyed device/protection/resource decisions, 24 assessed answer paths, practice keys, revision/review IDs, reset/focus/storage, model arithmetic and all six paper cases with four separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
