'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{JSDOM}=require('jsdom'),keys=require('./fixtures/column_arithmetic_answer_keys.json');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),de=JSON.parse(read('lang/de.json')),id='math1_3_add_sub';
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>de});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();w.topicInit();
 let models=0,steps=0;const value=digits=>Array.from(digits).reduce((n,x,i)=>n+x*10**i,0);
 function verify(a,b,kind){const m=w.columnArithmeticModel(a,b,kind);assert.equal(m.result,kind==='add'?a+b:a-b);assert.equal(value(m.left),a);assert.equal(value(m.right),b);let result=0,carry=0;
  for(const s of m.steps){if(s.kind==='exchange'){assert.equal(value(s.before),a);assert.equal(value(s.after),a);assert.equal(s.source,s.column+1);assert.equal(s.after[s.source],s.before[s.source]-1);assert.equal(s.after[s.column],s.before[s.column]+10);assert.equal(s.expected,s.after[s.column]);assert.ok(s.after.every(x=>x>=0));}else{assert.ok(s.digit>=0&&s.digit<=9);result+=s.digit*10**s.column;if(kind==='add'){assert.equal(s.incoming,carry);assert.equal(s.expected,s.x+s.y+carry);assert.equal(s.digit+10*s.carry,s.expected);carry=s.carry;}else{assert.equal(value(s.after),a);assert.equal(s.expected,s.x-s.y);}}}
  assert.equal(result,m.result);models++;return m;
 }
 for(let a=0;a<=250;a++)for(let b=0;b<=250;b++){verify(a,b,'add');if(a>=b)verify(a,b,'subtract');}
 for(const a of [999,1000,1010,4095,8709,9999,10000,99999])for(const b of [0,1,9,99,578,909,999,9999]){verify(a,b,'add');if(a>=b)verify(a,b,'subtract');}
 assert.deepEqual(Array.from(w.columnArithmeticModel(1000,1,'subtract').steps.filter(s=>s.kind==='exchange'),s=>Array.from(s.after)),[[0,0,10,0],[0,10,9,0],[10,9,9,0]]);
 for(const args of [[-1,1,'add'],[1,-1,'add'],[1.5,1,'add'],['1',1,'add'],[100000,1,'add'],[1,100000,'add'],[1,2,'subtract'],[1,1,'divide']])assert.throws(()=>w.columnArithmeticModel(...args));
 const saved=JSON.stringify(w.localStorage);
 for(const host of d.querySelectorAll('[data-column-lab]')){const input=host.querySelector('input'),select=host.querySelector('select'),status=host.querySelector('[data-column-status]'),check=host.querySelector('[data-column-check]'),show=host.querySelector('[data-column-show]'),reset=host.querySelector('[data-column-reset]');
  for(let i=0;i<select.options.length;i++){select.value=String(i);select.dispatchEvent(new w.Event('change'));const[a,b]=select.options[i].textContent.split(/[+−]/).map(Number),m=verify(a,b,host.dataset.columnLab);
   for(const[j,s]of m.steps.entries()){input.value=String(s.expected+1);check.click();assert.equal(host.dataset.step,String(j));assert.doesNotMatch(status.textContent,/^Richtig/);input.value=String(s.expected);input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(host.dataset.step,String(j+1));assert.match(status.textContent,/^Richtig/);steps++;}
   const rows=[...host.querySelectorAll('tbody tr')],rowValue=r=>Number([...r.querySelectorAll('td')].map(c=>c.textContent).join(''));assert.equal(rowValue(rows[0]),a);assert.equal(rowValue(rows[1]),b);assert.equal(rowValue(rows.at(-1)),m.result);
   if(host.dataset.columnLab==='subtract')assert.equal(value([...rows[2].querySelectorAll('td')].map(c=>Number(c.textContent)).reverse()),a);
   assert.equal(d.activeElement,status);assert.equal(input.disabled,true);assert.match(status.textContent,/Alle Zwischenergebnisse sind richtig/);assert.equal(host.querySelectorAll('[data-column-history] li').length,m.steps.length);
   reset.click();assert.equal(d.activeElement,input);assert.equal(host.dataset.step,'0');assert.equal(host.querySelectorAll('[data-column-history] li').length,0);while(!show.disabled)show.click();assert.match(status.textContent,/wurden gezeigt/);assert.doesNotMatch(status.textContent,/Alle Zwischenergebnisse sind richtig/);assert.equal(d.activeElement,status);reset.click();
  }
  for(const raw of ['', ' ', '2.0','2,0','2e1','0x2','-1','100','9007199254740992']){input.value=raw;check.click();assert.equal(input.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,input);assert.equal(host.dataset.step,'0');}input.dispatchEvent(new w.Event('input'));assert.equal(input.hasAttribute('aria-invalid'),false);assert.equal(status.textContent,'');
 }
 assert.equal(JSON.stringify(w.localStorage),saved);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,9);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;
 for(const[i,q]of qs.entries())for(let a=0;a<q.answers.length;a++){assert.equal(q.answers[a].correct,a===keys[q.id]);w.restartChapterQuiz();qs.forEach((other,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?a:keys[other.id])+'"]').checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,a===keys[q.id]?100:89);assert.equal(r.contentRevision,2);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));paths++;}dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>de});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 assert.equal(pd.querySelectorAll('[data-column-paper],[data-column-quick-paper]').length,4);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,5);assert.equal(pd.querySelectorAll('.column-reference').length,3);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,9);let generated=0;
 for(let seed=1;seed<=12;seed++){let n=seed;pw.Math.random=()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};const box=pd.createElement('div');box.innerHTML=pw.generateWorksheetContent(id,de[id].title);const tasks=box.querySelectorAll('[data-column-generated]'),answers=box.querySelector('template').content.querySelectorAll('[data-column-generated-answer]');assert.equal(tasks.length,20);assert.equal(answers.length,20);for(let i=0;i<20;i++){const a=+tasks[i].dataset.a,b=+tasks[i].dataset.b,result=+answers[i].dataset.columnGeneratedAnswer;assert.equal(result,tasks[i].dataset.kind==='add'?a+b:a-b);assert.ok(result>=0);generated++;}}paper.window.close();
 console.log('PASS: '+models+' arithmetic models with value-preserving exchanges, '+steps+' entered steps, '+paths+' independent quiz paths, focus/reveal/reset/storage, four paper alternatives and '+generated+' generated answers.');
})().catch(e=>{console.error(e);process.exitCode=1;});
