const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb6_orientierung',keys=require('./fixtures/dgb6_choice_keys.json');
const cases={software:[{key:1,reason:/18.*21/},{key:2,reason:/Rechte und Preis/}],shopping:[{key:0,reason:/Gesamtpreis.*Zeitpunkt/},{key:2,reason:/Stückpreis.*Gesamtbetrag/}],media:[{key:1,reason:/10.*15.*Pay-to-win/},{key:0,reason:/Bezahlung und Auswahl.*Belege/}],access:[{key:2,reason:/Textfassung.*Hindernis/},{key:0,reason:/geprüften Ablauf|diesen Ablauf/}]};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();const stored=JSON.stringify(w.localStorage);
 for(const [name,expected]of Object.entries(cases)){
  const zone=d.querySelector('[data-choice-lab="'+name+'"]'),control=zone.querySelector('select'),cards=[...zone.querySelectorAll('[data-boundary-case]')],status=zone.querySelector('[role=status]');assert.equal(cards.length,2);assert.equal(d.getElementById(control.getAttribute('aria-describedby')),status);
  for(const [n,e]of expected.entries()){control.value=String(n);control.dispatchEvent(new w.Event('change'));assert.equal(cards.filter(c=>!c.hidden).length,1);assert.equal(cards[n].hidden,false);assert.match(status.textContent,/Lies den Fall/);for(let a=0;a<3;a++){const b=cards[n].querySelectorAll('button')[a];b.click();assert.equal(status.textContent.startsWith('Richtig:'),a===e.key);if(a===e.key)assert.match(status.textContent,e.reason);assert.equal(b.getAttribute('aria-describedby'),status.id);}}
  zone.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.match(status.textContent,/Lies den Fall/);
 }
 assert.equal(JSON.stringify(w.localStorage),stored);const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);
 assert.equal(d.querySelectorAll('[data-choice-tasks]>li').length,18);assert.equal(d.querySelectorAll('[data-choice-observations] dt').length,4);
 const csv=read('examples/werkzeugwahl-anmeldungen.csv').replace(/^\ufeff/,'').trim().split(/\r?\n/).map(r=>r.split(';'));assert.deepEqual(csv,[['Workshop','Anmeldungen'],['Zeichnen','6'],['Bauen','4'],['Forschen','8']]);assert.equal(d.querySelector('[data-choice-download]').href,'https://example.test/site/examples/werkzeugwahl-anmeldungen.csv');
 assert.match(d.querySelector('[data-choice-tasks="software"]').textContent,/B2 bis B4.*=B2\+B3\+B4.*B3 auf 7.*anmeldungen\.ods.*schließe und öffne.*einladung\.odt/s);
 assert.match(d.querySelector('[data-choice-solution="software"]').textContent,/6 \+ 4 \+ 8 = 18.*6 \+ 7 \+ 8 = 21/s);
 assert.match(d.querySelector('[data-choice-solution="shopping"]').textContent,/5,70.*2,20.*2,25/s);assert.match(d.querySelector('[data-choice-solution="media"]').textContent,/15 zu 10.*4 Euro.*50 übrig.*3 Euro/s);
 assert.equal(w.chapterRevision(id),1);assert.equal(w.currentChapterResult(id,{contentRevision:0,passed:true,lastPercent:100}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));
 for(const [n,q]of qs.entries()){assert.equal(q.sectionIndex,Math.floor(n/2));assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let a=0;a<3;a++){w.restartChapterQuiz();qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===n?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:88);assert.equal(result.contentRevision,1);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[a].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[1,0,2]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-choice-paper] .ai-paper-case').length,8);assert.equal(material.querySelectorAll('[data-choice-tasks]>li').length,18);assert.equal(material.querySelectorAll('[data-choice-solution],button,select,input').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-choice-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.match(material.textContent,/noch nicht ausgeführt/);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,8);paper.window.close();
 console.log('PASS: 24 case decisions, 24 assessed answer paths, independent arithmetic/CSV data, revision/review IDs, three free practices, reset/focus/storage and eight paper cases with four separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
