const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),keys=require('./fixtures/weather_assessment_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=wetter',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 assert.equal(w.chapterRevision('wetter'),4);assert.equal(w.currentChapterResult('wetter',{contentRevision:3,passed:true,bestPercent:100}).passed,false);assert.deepEqual([...w.currentChapterQuiz.questions].map(q=>q.id).sort(),Object.keys(keys).sort());
 let practice=0,assessed=0;const saved=JSON.stringify(w.localStorage);
 for(const section of data.wetter.sections)for(const q of section.quizzes||[]){const box=d.querySelector('.practice-box[data-id="'+q.id+'"]');for(const [a,answer]of q.answers.entries()){const b=[...box.querySelectorAll('button')].find(b=>b.textContent===answer.text);new w.Function(b.getAttribute('onclick')).call(b);assert.equal(b.classList.contains('is-correct'),a===keys[q.id]);assert.ok(box.querySelector('.feedback').innerText.includes(answer.feedback));practice++;}}
 assert.equal(JSON.stringify(w.localStorage),saved);
 const rows=[...d.querySelectorAll('[data-weather-humidity-table] tbody tr')].map(row=>[...row.children].map(c=>c.textContent));
 assert.deepEqual(rows,[['A','20 °C','11,7 hPa','23,4 hPa','… %'],['B','10 °C','11,7 hPa','12,3 hPa','… %']]);
 assert.deepEqual(rows.map(row=>Math.round(100*parseFloat(row[2].replace(',','.'))/parseFloat(row[3].replace(',','.')))),[50,95]);
 assert.equal(d.querySelectorAll('[data-weather-humidity-tasks]>li').length,3);assert.equal(d.querySelector('.weather-humidity-scroll').tabIndex,0);assert.ok(d.querySelector('[data-weather-high-pressure]'));
 for(const [index,q]of w.currentChapterQuiz.questions.entries()){
  assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);
  for(let a=0;a<3;a++){w.restartChapterQuiz();w.currentChapterQuiz.questions.forEach((other,i)=>d.querySelector(`input[name="chapter_q_${i}"][value="${i===index?a:keys[other.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results')).wetter;assert.equal(result.lastPercent,a===keys[q.id]?100:94);assert.equal(result.contentRevision,4);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));assessed++;}
 }
 assert.equal(practice,39);assert.equal(assessed,54);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=wetter',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,18);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.querySelectorAll('[data-weather-humidity-table] tbody tr').length,2);assert.equal(pd.querySelectorAll('#ws-content [data-weather-humidity-solution]').length,0);assert.ok(pd.getElementById('ws-solutions').textContent.includes('Vergleichslösung zur relativen Feuchte'));for(const q of [...data.wetter.sections.flatMap(s=>s.quizzes||[]),...data.wetter.diplom.questions]){assert.ok(pd.getElementById('ws-content').textContent.includes(q.question));assert.ok(pd.getElementById('ws-solutions').textContent.includes(q.answers[keys[q.id]].text));}paper.window.close();
 console.log('PASS: all 18 weather questions independently keyed; 54 assessed and 39 free paths; humidity calculation and tasks, high-pressure explanation, revision 4 and matching paper material/solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
