const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),de=JSON.parse(read('lang/de.json')),en=JSON.parse(read('lang/en.json'));
(async()=>{const id='klimawandel',dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.localStorage.setItem('physik_lang','en');w.fetch=async url=>({ok:true,json:async()=>url.includes('/de.json')?de:en});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
// The stored translation is revision 1; the released German chapter is revision 2.
// Exercise the actual fallback before retaining the older English runtime coverage below.
assert.equal(en[id].sourceRevision,1);assert.equal(w.chapterRevision(id),2);
assert.equal(d.querySelector('[data-content-language-notice]').lang,'en');
assert.equal(d.getElementById('sections-container').lang,'de');
assert.equal(w.currentChapterQuiz.questions.length,17);assert.equal(d.querySelectorAll('.practice-box').length,13);
assert.ok(w.currentChapterQuiz.questions.some(q=>q.id==='kw_targets_compare'));
assert.equal(w.currentChapterQuiz.questions.find(q=>q.id==='kw_d1').sectionIndex,0);
w.eval(read('js/topics/klimawandel.js'));w.topicInit();
assert.match(d.getElementById('greenhouseExplanation').textContent,/Temperatur|Temperaturen/);
// Isolated revision-1 fixture: this does not mark the stored translation current.
w.SCIVERSE_CHAPTER_REVISIONS[id]=en[id].sourceRevision;
w.fetch=async()=>({ok:true,json:async()=>en});
await w.renderTopic();w.topicInit();assert.equal(d.querySelector('[data-content-language-notice]'),null);assert.equal(d.getElementById('sections-container').lang,'en');assert.equal(en[id].sourceRevision,w.chapterRevision(id));assert.equal(w.currentChapterQuiz.questions.length,13);assert.equal(d.querySelectorAll('.practice-box').length,9);for(let i=0;i<6;i++){assert.equal(de[id].sections[i].id,en[id].sections[i].id);for(let j=0;j<(en[id].sections[i].quizzes||[]).length;j++){const b=en[id].sections[i].quizzes[j],a=de[id].sections[i].quizzes.find(q=>q.id===b.id);assert.equal(a.id,b.id);assert.deepEqual(a.answers.map(a=>a.correct),b.answers.map(a=>a.correct));}}
for(const value of [0,1,2]){d.getElementById('climateGasRange').value=value;w.updateGreenhouseLab();assert.match(d.getElementById('greenhouseExplanation').textContent,/same initial temperature/);}for(let year=1880;year<=2025;year++){d.getElementById('climateYearRange').value=year;w.updateClimateTimeline();assert.match(d.getElementById('austriaTempLabel').textContent,/Austria/);assert.equal(d.querySelector('.climate-stripe.active').dataset.year,String(year));}for(let i=10;i<=40;i++){d.getElementById('warmingRange').value=i/10;w.updateTippingRisk();assert.match(d.getElementById('tippingNote').textContent,/no|not/);assert.match(d.getElementById('warmingRange').getAttribute('aria-valuetext'),/degrees of warming/);}for(const type of ['heat','drought','heavyRain','alps'])w.showClimateImpact(type);for(const card of d.querySelectorAll('.climate-action-card')){w.classifyClimateAction(card,card.dataset.type==='schutz'?'anpassung':'schutz');assert.match(card.querySelector('[data-action-feedback]').textContent,/Try this card again/);w.classifyClimateAction(card,card.dataset.type);}assert.equal(d.getElementById('climateActionScore').textContent,'4 of 4 classified');assert.doesNotMatch(d.getElementById('sections-container').textContent,/Treibhaus|Erwärmung|Österreich|Klimaschutz|Anpassung|Bezugszeitraum|Zurücksetzen/);
for(const index of [0,1,2]){w.restartChapterQuiz();w.currentChapterQuiz.questions.forEach((q,i)=>d.querySelector(`input[name="chapter_q_${i}"][value="${index}"]`).checked=true);w.submitChapterQuiz();assert.equal(w.getChapterQuizResult(id).lastPercent,index===0?100:0);const box=d.getElementById('chapter-quiz-result');assert.equal(box.querySelectorAll('li').length,13);w.currentChapterQuiz.questions.forEach(q=>assert.ok(box.textContent.includes(q.answers[index].feedback)));}dom.window.close();console.log('PASS: actual outdated climate translation falls back to all 17 current German questions; isolated older English fixture retains 13 questions/39 feedback paths, all annual/risk states and English explanations. Translation remains unchanged.');})().catch(e=>{console.error(e);process.exitCode=1;});
