const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic=kunst_4_portfolio',runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(resolve=>setImmediate(resolve));w.fetch=async()=>({ok:true,json:async()=>data});for(const name of ['curriculum','chapter-revisions','common','core-learning','language-workshop','art-workshop','renderer'])w.eval(read('js/'+name+'.js'));await w.renderTopic();
 const zone=d.querySelector('[data-art-framing]'),control=zone.querySelector('select'),facts=zone.querySelector('[data-framing-facts]'),original=facts.outerHTML,headline=zone.querySelector('[data-framing-headline]'),feedback=zone.querySelector('[data-framing-feedback]'),status=zone.querySelector('[data-framing-status]'),check=zone.querySelector('[data-framing-check]'),reset=zone.querySelector('[data-framing-reset]');
 assert.ok(control.closest('label'));assert.equal(status.getAttribute('aria-live'),'polite');assert.equal(status.getAttribute('aria-atomic'),'true');assert.equal(feedback.hidden,true);assert.match(facts.textContent,/erfunden/);assert.ok(facts.querySelector('svg[role="img"][aria-label]'));
 for(let repeat=0;repeat<4;repeat++)for(const value of ['trees','parking','everyone']){
  control.focus();control.value=value;control.dispatchEvent(new w.Event('change'));assert.equal(d.activeElement,control);assert.equal(feedback.hidden,true);assert.equal(feedback.textContent,'');assert.equal(headline.textContent,control.selectedOptions[0].textContent);assert.equal(facts.outerHTML,original);
  check.focus();check.click();assert.equal(d.activeElement,check);assert.equal(feedback.hidden,false);assert.equal(feedback.textContent,control.selectedOptions[0].dataset.reason);assert.equal(status.textContent,feedback.textContent);assert.match(feedback.textContent,value==='everyone'?/nicht gedeckt/:/belegt/);assert.equal(facts.outerHTML,original);
 }
 w.initArtWorkshops();reset.focus();reset.click();assert.equal(d.activeElement,reset);assert.equal(control.value,'trees');assert.equal(feedback.hidden,true);assert.equal(feedback.textContent,'');assert.equal(facts.outerHTML,original);assert.equal(zone.querySelectorAll('[data-framing-feedback]').length,1);
 control.value='unknown';control.dispatchEvent(new w.Event('change'));assert.equal(control.value,'trees');assert.equal(feedback.hidden,true);control.value='unknown';check.click();assert.equal(control.value,'trees');assert.equal(feedback.hidden,false);assert.doesNotMatch(feedback.textContent,/undefined/);
 const questions=w.currentChapterQuiz.questions.filter(q=>q.id.includes('_medien'));assert.equal(questions.length,2);questions.forEach(q=>assert.equal(q.sectionIndex,6));assert.equal(w.localStorage.getItem('sciverse_chapter_quiz_results'),null,'Comparing headlines is not a chapter quiz attempt');dom.window.close();
 console.log('PASS: actual media framing chapter, three headlines with stable facts/image, causal feedback, stale feedback clearing, focus, reset, reinitialization, invalid choice recovery and no quiz score side effect.');
})().catch(error=>{console.error(error);process.exitCode=1;});
