'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_immunsystem_resistenzen';
const keys={bio_4_immun_s1:[1,0],bio_4_immun_d1:[2,0],bio_4_immun_s2:[0,1],bio_4_immun_d2:[1,1],bio_4_immun_daten:[2,1],bio_4_immun_s3:[1,2],bio_4_immun_d3:[0,2],bio_4_immun_anteil:[2,2],bio_4_immun_entstehung:[1,2],bio_4_immun_null:[0,2],bio_4_immun_handeln:[2,3]};
// Independent expected survivors and displayed proportions, before any division.
const cases=[['0','N',100,0,'0 %'],['0','S',10,0,'0 %'],['0','V',0,0,'Nicht bestimmbar (keine Bakterien)'],['10','N',90,10,'10 %'],['10','S',9,10,'52,6 %'],['10','V',0,10,'100 %'],['40','N',60,40,'40 %'],['40','S',6,40,'87,0 %'],['40','V',0,40,'100 %']];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-immunity-lab]'),start=zone.querySelector('[data-immunity-start]'),rule=zone.querySelector('[data-immunity-rule]'),rounds=zone.querySelector('[data-immunity-rounds]'),check=zone.querySelector('[data-immunity-check]'),reset=zone.querySelector('[data-immunity-reset]'),result=zone.querySelector('[data-immunity-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.invalid,undefined);};
 for(const[r,mode,eAfter,rAfter,share]of cases)for(const n of [0,1,2]){
  set(start,r);set(rule,mode);set(rounds,String(n));check.click();assert.equal(d.activeElement,result);assert.equal(result.querySelectorAll('h4').length,1);
  const rows=[...result.querySelectorAll('tbody tr')];assert.equal(rows.length,n+2);
  assert.deepEqual([...rows[0].children].map(e=>e.textContent),['Anfang',String(100-Number(r)),r,'100',r+' %']);
  for(let i=1;i<rows.length;i++){const factor=[1,2,4][i-1],row=rows[i];assert.deepEqual([...row.children].map(e=>e.textContent),[i===1?'Direkt nach Auswahl':'Teilungsrunde '+(i-1),String(eAfter*factor),String(rAfter*factor),String((eAfter+rAfter)*factor),share]);assert.equal(row.dataset.share,eAfter+rAfter?String(rAfter/(eAfter+rAfter)*100):'undefined');}
  assert.match(result.textContent,/nur eine Auswahl/);assert.match(result.textContent,/keine Behandlung voraus/);
  if(r==='10'&&mode==='V')assert.match(result.textContent,/bleibt die Anzahl R bei 10/);
  if(r==='0'&&mode==='V')assert.match(result.textContent,/Population leer/);
 }
 for(const[input,name]of [[start,'start'],[rule,'rule'],[rounds,'rounds']]){reset.click();set(input,'');check.click();assert.equal(result.dataset.invalid,name);assert.equal(d.activeElement,input);}reset.click();assert.equal(start.value,'10');assert.equal(rule.value,'V');assert.equal(rounds.value,'1');assert.equal(result.textContent,'');assert.equal(d.activeElement,start);assert.equal(JSON.stringify(w.localStorage),storage);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('[data-immunity-solution]').length,4);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 assert.deepEqual([...d.querySelectorAll('.immunity-evidence tbody tr')].map(e=>[...e.children].map(c=>c.textContent)),[['Mit Impfung','200','4'],['Ohne Impfung','200','12']]);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,11);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].id,'bio_4_immunsystem_extra_resistenz');assert.ok(practice[0].answers.every(a=>a.pts===0));const practiceStorage=JSON.stringify(w.localStorage);w.playSuccessSound=()=>{};for(const answer of practice[0].answers){const button=[...d.querySelectorAll('.practice-box .practice-option')].find(e=>e.textContent===answer.text);assert.ok(button);w.handlePracticeAnswer(button,answer.correct,button.dataset.feedback);assert.ok(button.closest('.practice-box').querySelector('.feedback').innerText.includes(answer.feedback));assert.equal(button.classList.contains(answer.correct?'is-correct':'is-wrong'),true);assert.equal(button.disabled,false);}assert.equal(JSON.stringify(w.localStorage),practiceStorage);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.ok(pd.body.textContent.includes('Papierwerkstatt: Auswahl und Vermehrung'));assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(pd.querySelectorAll('.immunity-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('#ws-solutions [data-immunity-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-immunity-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);assert.doesNotMatch(pd.body.textContent,/undefined/);for(const s of data[id].sources){assert.ok(s.title&&s.url.startsWith('https://'));assert.ok(pd.body.textContent.includes(s.title));}
 const paperRows=[...pd.querySelectorAll('.immunity-paper tbody tr')].map(e=>e.textContent);assert.equal(paperRows.length,6);for(const[i,values]of [[0,['90 / 10 / 100 / 10 %','0 / 10 / 10 / 100 %','0 / 20 / 20 / 100 %']],[1,['9 / 10 / 19 / 52,6 %','18 / 20 / 38 / 52,6 %','36 / 40 / 76 / 52,6 %']],[2,['6 / 40 / 46 / 87,0 %','12 / 80 / 92 / 87,0 %']],[3,['0 / 0 / 0 / nicht bestimmbar']],[4,['120 / 80 / 200 / 40 %','240 / 160 / 400 / 40 %']],[5,['10 / 0 / 10 / 0 %','20 / 0 / 20 / 0 %']]])for(const value of values)assert.ok(paperRows[i].includes(value));paper.window.close();
 console.log('PASS: 27 selection/division states, independent counts and proportions, empty population, invalid/reset/focus/storage, 33 quiz and 3 practice paths, paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
