const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),keys=require('./fixtures/clima_concepts_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=klima',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/klima.js'));w.topicInit();
 assert.equal(w.currentChapterQuiz.questions.length,12);assert.deepEqual(Array.from(w.currentChapterQuiz.questions,q=>q.id).sort(),Object.keys(keys).sort());assert.equal(w.currentChapterResult('klima',{contentRevision:1,passed:true,bestPercent:100}).passed,false);
 const range=d.getElementById('co2Range'),solar=d.querySelector('[data-klima-solar]').outerHTML,saved=JSON.stringify(w.localStorage);assert.equal(range.max,'2');assert.equal(range.step,'1');
 for(const [value,label]of [[0,'weniger'],[1,'mittlere'],[2,'mehr'],[1,'mittlere'],[0,'weniger']]){range.value=value;range.dispatchEvent(new w.Event('input')); // outside-only does not execute inline handlers
  w.updateGreenhouseEffect();assert.match(range.getAttribute('aria-valuetext'),new RegExp(label));assert.doesNotMatch(d.getElementById('co2LevelText').textContent,/\d|%|ppm|°C/);const outward=Number(d.getElementById('heatEscapeGroup').getAttribute('opacity')),back=Number(d.getElementById('heatBackGroup').getAttribute('opacity'));assert.equal(outward,[1,.7,.4][value]);assert.equal(back,[.4,.7,1][value]);assert.ok(outward>0);assert.equal(d.querySelector('[data-klima-solar]').outerHTML,solar);assert.match(d.getElementById('greenhouseStatus').textContent,/zunächst gleichen Temperaturen.*weiterhin Energie.*nicht berechnet/);}
 assert.equal(d.getElementById('tempVal'),null);assert.equal(d.getElementById('heatRetentionText'),null);assert.equal(d.getElementById('greenhouseMeterFill'),null);assert.equal(d.querySelectorAll('[data-klima-flow-legend]>li').length,3);assert.equal(d.querySelectorAll('[data-klima-source-tasks]>li').length,3);assert.equal(d.querySelectorAll('[data-klima-greenhouse-tasks]>li').length,3);
 for(const [type,phrase]of [['ice','nicht gleich alt'],['tree','keine genaue Temperaturanzeige'],['sediment','Nicht jede sichtbare Schicht']]){w.showClimateArchive(type);assert.ok(d.getElementById('archiveText').textContent.includes(phrase));}assert.equal(JSON.stringify(w.localStorage),saved);
 let paths=0;for(const [index,q]of w.currentChapterQuiz.questions.entries()){assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let a=0;a<3;a++){if(paths)w.restartChapterQuiz();w.currentChapterQuiz.questions.forEach((other,i)=>d.querySelector(`input[name="chapter_q_${i}"][value="${i===index?a:keys[other.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results')).klima;assert.equal(r.lastPercent,a===keys[q.id]?100:92);assert.equal(r.contentRevision,2);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[a].feedback));paths++;}}
 assert.equal(w.currentChapterQuiz.questions.find(q=>q.id==='klima_model_limit').sectionIndex,1);assert.equal(w.currentChapterQuiz.questions.find(q=>q.id==='klima_source_compare').sectionIndex,1);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=klima',runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setTimeout(r,50));const pd=pw.document;assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,12);assert.equal(pd.querySelectorAll('[data-klima-greenhouse-paper] svg').length,1);assert.equal(pd.querySelectorAll('[data-klima-source-tasks]>li').length,3);assert.equal(pd.querySelectorAll('#ws-physics-material [data-klima-greenhouse-solution]').length,0);assert.match(pd.getElementById('ws-solutions').textContent,/Vergleichshinweise zu den Strahlungswegen/);assert.equal(pd.getElementById('ws-solutions').hidden,true);const ids=Array.from(pd.querySelectorAll('[id]'),e=>e.id);assert.equal(new Set(ids).size,ids.length);paper.window.close();console.log(`PASS: ${paths} independently keyed climate answers, five model selections, stable solar input and continuing output, archive limits, revision and complete paper alternative.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
