const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math3_11_statistik';
const keys={m311_q1:0,m311_q2:0,m311_q3:0,m311_zero:0,m311_equal:0,m311_dip1:0,m311_dip2:0,m311_axis_change:1,m311_axis_picture:2,m311_compare_groups:0,m311_laplace:1,m311_bag:2,m311_complement:0,m311_empirical:1,m311_prediction:2,m311_estimate:0};
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 assert.equal(w.currentChapterQuiz.questions.length,16);assert.equal(w.chapterRevision(id),3);assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).passed,false);assert.equal(d.querySelectorAll('[data-stat3-tasks] li').length,9);
 const before=JSON.stringify(w.localStorage),axis=d.querySelector('[data-stat3-axis]');for(const start of [0,30]){axis.querySelector('select').value=start;axis.querySelector('select').dispatchEvent(new w.Event('change'));const bars=[...axis.querySelectorAll('[data-stat3-bar]')];assert.ok(Math.abs(Number(bars[1].getAttribute('height'))/Number(bars[0].getAttribute('height'))-(start===0?1.25:2))<1e-10);bars.forEach((bar,i)=>assert.ok(Math.abs((220-Number(bar.getAttribute('y')))*(60-start)/160+start-[40,50][i])<1e-10));assert.match(axis.textContent,/25 % mehr/);}
 const lab=d.querySelector('[data-stat3-chance]'),select=lab.querySelector('select'),run=n=>lab.querySelector('[data-stat3-run="'+n+'"]').click(),reset=()=>lab.querySelector('[data-stat3-reset]').click();let decisions=0;
 assert.equal(lab.querySelector('[data-stat3-chance-plot]').contains(lab.querySelector('[data-stat3-chance-legend]')),false);
 lab.querySelector('[data-stat3-chance-plot]').scrollLeft=80;reset();assert.equal(lab.querySelector('[data-stat3-chance-plot]').scrollLeft,0);
 const cases={six:{size:6,win:[6],p:1/6},even:{size:6,win:[2,4,6],p:.5},coin:{size:2,win:[1],p:.5},bag:{size:4,win:[1,2,3],p:.75}};
 for(const [name,model]of Object.entries(cases)){
  select.value=name;select.dispatchEvent(new w.Event('change'));assert.equal(lab.dataset.total,'0');assert.equal(lab.querySelector('[data-stat3-observed]'),null);let index=0,expected=0;
  w.Math.random=()=>{const outcome=index%model.size+1;index++;if(model.win.includes(outcome))expected++;return(outcome-.5)/model.size;};
  for(let i=0;i<12;i++){run(1);assert.equal(Number(lab.dataset.hits),expected);assert.equal(Number(lab.dataset.total),index);const last=lab.querySelector('[data-stat3-last]');assert.equal(Number(last.getAttribute('cy')),220-expected/index*160);decisions++;}
  assert.equal(Number(lab.querySelector('[data-stat3-theory]').getAttribute('y1')),220-model.p*160);assert.equal(lab.querySelectorAll('tbody tr').length,10);run(10);run(100);assert.equal(Number(lab.dataset.total),122);assert.equal(Number(lab.dataset.hits),expected);assert.equal(lab.querySelector('[data-stat3-observed]').getAttribute('points').split(' ').length,122);
  for(const random of [0,.999999]){reset();w.Math.random=()=>random;run(100);assert.equal(Number(lab.dataset.hits),model.win.includes(random===0?1:model.size)?100:0);assert.ok(!lab.innerHTML.includes('NaN'));}
 }
 reset();assert.equal(d.activeElement,select);w.Math.random=()=>0;for(let i=0;i<10;i++)run(100);assert.equal(lab.dataset.total,'1000');run(100);assert.equal(lab.dataset.total,'1000');assert.equal(d.activeElement,lab.querySelector('[data-stat3-chance-status]'));select.value='six';select.dispatchEvent(new w.Event('change'));assert.equal(lab.dataset.total,'0');assert.equal(JSON.stringify(w.localStorage),before);
 let paths=0;for(const [i,q]of w.currentChapterQuiz.questions.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id],q.id);for(let answer=0;answer<q.answers.length;answer++){w.currentChapterQuiz.questions.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?answer:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,answer===keys[q.id]?100:94);assert.deepEqual(r.reviewQuestionIds,answer===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[answer].feedback));paths++;}}assert.equal(paths,43);
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.stat3-figure svg').length,2);assert.equal(pd.querySelectorAll('.stat3-paper').length,2);assert.equal(pd.querySelectorAll('[data-stat3-tasks] li').length,9);assert.equal(pd.querySelectorAll('#ws-solutions [data-stat3-solution]').length,3);assert.equal(pd.querySelectorAll('#ws-solutions [data-stat3-mean-solution]').length,1);assert.equal(pd.getElementById('ws-solutions').hidden,true);
 const tasks=[...pd.querySelectorAll('[data-stat3-generated]')],solutions=[...pd.querySelectorAll('[data-stat3-generated-answer]')];assert.equal(tasks.length,6);assert.equal(solutions.length,6);tasks.forEach((t,i)=>assert.equal(t.dataset.values.split(',').map(Number).reduce((a,b)=>a+b,0)/4,Number(solutions[i].dataset.stat3GeneratedAnswer)));const toggle=pd.getElementById('ws-include-solutions');toggle.checked=true;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,false);paper.window.close();dom.window.close();console.log('PASS: two axis mappings, 48 controlled single outcomes, four batch models and extremes, 1000-trial limit/reset/storage, 43 graded paths, diagrams and six optional generated solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
