'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),id='bio_3_fossilien_erdgeschichte';
const keys={bio_3_fossilien_s1:[1,0],bio_3_fossilien_d2:[2,0],bio_3_fossilien_abdruck:[0,0],bio_3_fossilien_s2:[2,1],bio_3_fossilien_d1:[1,1],bio_3_fossilien_s3:[0,2],bio_3_fossilien_d3:[2,2],bio_3_fossilien_massstab:[1,2],bio_3_fossilien_s4:[0,3],bio_3_fossilien_d4:[1,3]};
const answers={original:'bounded',reworked:'minimum',loose:'unknown'};
const permutations=values=>values.length?values.flatMap((v,i)=>permutations(values.filter((_,j)=>i!==j)).map(rest=>[v,...rest])):[[]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-fossil-lab]'),orders=[...zone.querySelectorAll('[data-fossil-order]')],context=zone.querySelector('[data-fossil-context]'),age=zone.querySelector('[data-fossil-age]'),check=zone.querySelector('[data-fossil-check]'),reset=zone.querySelector('[data-fossil-reset]'),result=zone.querySelector('[data-fossil-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,value)=>{el.value=value;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.orderCorrect,undefined);assert.equal(result.dataset.ageCorrect,undefined);};const order=values=>values.forEach((v,i)=>set(orders[i],v));
 let combinations=0;
 // Every four-position selection: 24 permutations, 232 with a duplicate/missing layer.
 for(const a of 'ABCD')for(const b of 'ABCD')for(const c of 'ABCD')for(const e of 'ABCD'){
  const row=[a,b,c,e];order(row);set(context,'original');set(age,'bounded');check.click();if(new Set(row).size===4){assert.equal(result.dataset.invalid,undefined);assert.equal(result.dataset.orderCorrect,String(row.join('')==='ABCD'));}else{assert.equal(result.dataset.invalid,'duplicate');assert.equal(result.dataset.orderCorrect,undefined);}combinations++;
 }
 let outcomes=0;
 for(const row of permutations(['A','B','C','D']))for(const [mode,key]of Object.entries(answers))for(const answer of Object.values(answers)){
  order(row);set(context,mode);assert.equal(age.value,'');set(age,answer);check.click();assert.equal(result.dataset.orderCorrect,String(row.join('')==='ABCD'));assert.equal(result.dataset.ageCorrect,String(answer===key));assert.equal(result.children.length,3);assert.equal(d.activeElement,result);if(mode==='reworked')assert.match(result.textContent,/älter als 120/);if(mode==='loose')assert.match(result.textContent,/keiner Schicht sicher/);outcomes++;
 }
 reset.click();check.click();assert.equal(result.dataset.invalid,'order');assert.equal(d.activeElement,orders[0]);order(['A','B','C','D']);check.click();assert.equal(result.dataset.invalid,'age');assert.equal(d.activeElement,age);set(context,'');set(age,'bounded');check.click();assert.equal(result.dataset.invalid,'context');assert.equal(d.activeElement,context);reset.click();assert.equal(context.value,'original');assert.equal(age.value,'');assert.ok(orders.every(e=>e.value===''));assert.equal(d.activeElement,orders[0]);assert.equal(result.textContent,'');assert.equal(JSON.stringify(w.localStorage),storage);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,4);assert.equal(d.querySelectorAll('[data-fossil-solution]').length,4);
 const time=[...d.querySelectorAll('.fossil-time tbody tr')].map(r=>r.children[2].textContent);assert.deepEqual(time,['4.600','3.500','540','66','0,3']);const distances=time.map(s=>Number(s.replace('.','').replace(',','.'))/10);assert.deepEqual(distances,[460,350,54,6.6,0.03]);assert.equal(distances[4]*10,0.3);assert.ok(d.querySelector('[data-fossil-solution="2"]').textContent.includes('0,03 cm = 0,3 mm'));
 assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));
 for(const [i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.ok(practice[0].answers.every(a=>a.pts===0));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-fossil-paper]').length,1);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,4);assert.equal(pd.querySelectorAll('.fossil-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('.fossil-time tbody tr').length,5);assert.equal(pd.querySelectorAll('#ws-solutions [data-fossil-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-fossil-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);paper.window.close();
 console.log(`PASS: ${combinations} layer selections, ${outcomes} independently checked order/context/age combinations, stale results/invalid inputs/reset/focus/storage, time scale, 30 quiz answers and paper material.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
