const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb5_kommunikation',keys=require('./fixtures/dgb5_communication_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/dgb5_kommunikation.js'));w.topicInit();w.topicInit();
 const stored=JSON.stringify(w.localStorage),lab=d.querySelector('[data-sharing-lab]'),mode=lab.querySelector('#sharing-mode'),person=lab.querySelector('#sharing-person'),open=lab.querySelector('[data-sharing-open]'),edit=lab.querySelector('[data-sharing-edit]'),reset=lab.querySelector('[data-sharing-reset]'),preview=lab.querySelector('[data-sharing-preview]'),content=lab.querySelector('[data-sharing-text]'),result=lab.querySelector('[data-sharing-result]');
 const set=(el,value)=>{el.value=value;el.dispatchEvent(new w.Event('change'));};
 // Explicit independently specified permissions, not derived from the production rule.
 const rows=[['team','team',true,true],['team','teacher',true,false],['team','guest',false,false],['read','team',true,true],['read','teacher',true,false],['read','guest',true,false],['edit','team',true,true],['edit','teacher',true,true],['edit','guest',true,true]];
 for(const [m,p,canRead,canEdit]of rows){reset.click();set(mode,m);set(person,p);assert.equal(preview.hidden,true);assert.equal(lab.querySelector('[data-sharing-read-status]').textContent,canRead?'Lesen erlaubt':'Lesen nicht erlaubt');assert.equal(lab.querySelector('[data-sharing-edit-status]').textContent,canEdit?'Bearbeiten erlaubt':'Bearbeiten nicht erlaubt');open.click();assert.equal(preview.hidden,!canRead);const before=content.textContent;edit.click();assert.equal(result.textContent.startsWith('Änderung gelungen:'),canEdit);assert.equal(content.textContent,canEdit?'Übungsplan: Wir sammeln Fragen bis zur nächsten Lernrunde.':before);if(canEdit){edit.click();assert.equal(content.textContent,'Übungsplan: Alle sollen sofort antworten.');}}
 reset.click();set(mode,'edit');edit.click();set(mode,'team');assert.equal(preview.hidden,true);assert.match(result.textContent,/Regel eingestellt/);open.click();assert.match(result.textContent,/Kein Lesezugriff/);edit.click();assert.match(result.textContent,/Änderung abgelehnt/);set(person,'team');open.click();assert.match(content.textContent,/Wir sammeln Fragen/);reset.click();assert.equal(d.activeElement,mode);assert.equal(mode.value,'team');assert.equal(person.value,'guest');assert.equal(preview.hidden,true);set(person,'team');open.click();assert.match(content.textContent,/Alle sollen sofort antworten/);
 const cases=d.querySelector('[data-service-cases]'),control=cases.querySelector('select'),cards=[...cases.querySelectorAll('[data-boundary-case]')],status=cases.querySelector('[role=status]');let decisions=0;
 for(const [i,key]of [1,2,0].entries()){set(control,String(i));assert.deepEqual(cards.map(c=>c.hidden),[0,1,2].map(j=>i!==j));assert.match(status.textContent,/Lies die Datenkarte/);for(let a=0;a<3;a++){cards[i].querySelectorAll('button')[a].click();assert.equal(status.textContent.startsWith('Richtig:'),a===key);decisions++;}}
 cases.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.equal(JSON.stringify(w.localStorage),stored);
 assert.equal(d.querySelectorAll('[data-communication-tasks]>li').length,17);assert.equal(d.querySelectorAll('[data-collaboration-task]>li').length,6);assert.equal(d.querySelectorAll('[data-service-data] tbody tr').length,4);assert.equal(d.querySelectorAll('[data-collaboration-protocol] tbody tr').length,4);const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));assert.deepEqual(Array.from(qs,q=>q.sectionIndex),[0,0,0,1,1,2,2,2,3]);let answers=0;
 for(const [i,q]of qs.entries())for(let a=0;a<3;a++){qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:89);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));answers++;}
 assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).outdated,true);const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[2,1,0]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-sharing-paper] tbody tr').length,3);assert.equal(material.querySelectorAll('[data-service-paper] .ai-paper-case').length,3);assert.equal(material.querySelectorAll('[data-communication-tasks]>li').length,17);assert.equal(material.querySelectorAll('[data-collaboration-task]>li').length,6);assert.equal(material.querySelectorAll('button,input,select,details,[data-feedback]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions .ws-paper-solution').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,9);paper.window.close();
 assert.equal(decisions,9);assert.equal(answers,27);console.log('PASS: nine permission combinations and real model changes, denied changes, narrowed access retains history, reset/focus/re-init, nine data cases, 27 independent quiz paths, 23 tasks and four separate paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
