const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),data=JSON.parse(read('lang/de.json')),id='chemie_reaktionen_energie';
// Expectations specified independently of HTML answer flags and quiz keys.
const cases={water:['physical','physical',0],bottle:['unknown','physical',1],sugar:['physical','physical',2],wax:['chemical','chemical',0],metal:['unknown','chemical',1],foam:['unknown','chemical',2]};
const keys={ch_chemie_reaktionen_energie_q1:1,ch_chemie_reaktionen_energie_q2:2,ch_chemie_reaktionen_energie_q3:0,dip_chemie_reaktionen_energie_1:2,dip_chemie_reaktionen_energie_2:1,dip_chemie_reaktionen_energie_3:0,dip_chemie_reaktionen_energie_4:2,reaction_mass:1,reaction_activation:0,reaction_controls:2,reaction_coefficients:1,reaction_molecules:0};
const groups=[['ch_chemie_reaktionen_energie_q1'],['ch_chemie_reaktionen_energie_q2','dip_chemie_reaktionen_energie_1','dip_chemie_reaktionen_energie_3','reaction_coefficients','reaction_molecules'],['ch_chemie_reaktionen_energie_q3','reaction_controls'],['dip_chemie_reaktionen_energie_2'],['dip_chemie_reaktionen_energie_4','reaction_mass','reaction_activation']];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/physik_bay6/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/chemie_common.js'));w.ChemieLabs.topicInit();
 const lab=d.querySelector('[data-chem-lab="evidence-cases"]'),select=lab.querySelector('select'),toggle=lab.querySelector('[data-evidence-toggle]'),feedback=lab.querySelector('[data-evidence-feedback]'),nextFeedback=lab.querySelector('[data-evidence-next-feedback]'),before=JSON.stringify(w.localStorage);let decisions=0;
 assert.equal(select.labels.length,1);
 for(const[name,expected]of Object.entries(cases)){
  select.value=name;select.dispatchEvent(new w.Event('change'));const card=lab.querySelector('[data-evidence-case="'+name+'"]');assert.equal(lab.querySelectorAll('[data-evidence-case]:not([hidden])').length,1);assert.equal(card.hidden,false);assert.equal(toggle.getAttribute('aria-controls'),card.querySelector('[data-evidence-extra]').id);assert.equal(feedback.textContent,'');
  for(let phase=0;phase<2;phase++){
   if(phase)toggle.click();assert.equal(toggle.getAttribute('aria-expanded'),String(phase===1));assert.equal(card.querySelector('[data-evidence-extra]').hidden,phase===0);
   for(const value of ['physical','chemical','unknown']){const btn=lab.querySelector('[data-evidence-verdict="'+value+'"]');btn.click();assert.equal(feedback.dataset.correct,String(value===expected[phase]));assert.equal(btn.getAttribute('aria-pressed'),'true');assert.ok(feedback.textContent.length>70);decisions++;}
  }
  for(const[index,btn]of [...card.querySelectorAll('[data-evidence-next]')].entries()){btn.click();assert.equal(nextFeedback.dataset.correct,String(index===expected[2]));assert.ok(nextFeedback.textContent.includes(btn.dataset.explain));decisions++;}
  w.ChemieLabs.topicInit();assert.equal(toggle.getAttribute('aria-expanded'),'true');toggle.click();assert.equal(toggle.getAttribute('aria-expanded'),'false');assert.equal(feedback.textContent,'');assert.equal(nextFeedback.textContent,'');
 }
 lab.querySelector('[data-evidence-reset]').click();assert.equal(select.value,'water');assert.equal(d.activeElement,select);assert.equal(feedback.textContent,'');assert.equal(JSON.stringify(w.localStorage),before);assert.equal(decisions,54);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,12);assert.equal(d.querySelectorAll('.practice-box').length,12);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;
 for(const q of qs){assert.equal(q.answers.length,3);assert.equal(q.answers.filter(a=>a.correct).length,1);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);assert.equal(q.sectionIndex,groups.findIndex(g=>g.includes(q.id)));
  for(let choice=0;choice<3;choice++){for(const[i,other]of qs.entries())d.querySelector(`input[name="chapter_q_${i}"][value="${other.id===q.id?choice:keys[other.id]}"]`).checked=true;w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id]?100:92);assert.equal(r.contentRevision,3);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;}
 }
 assert.equal(paths,36);assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/physik_bay6/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-evidence-paper-case]').length,6);assert.equal(pd.querySelectorAll('[data-evidence-tasks]>li').length,4);assert.equal(pd.querySelectorAll('[data-decomposition-steps]>li').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.ok(pd.getElementById('ws-solutions').textContent.includes('Erstes Urteil: Noch nicht entscheidbar'));assert.ok(!pd.querySelector('[data-evidence-paper-case]').textContent.includes('Erstes Urteil:'));assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,12);assert.equal(pd.getElementById('ws-print').disabled,false);paper.window.close();
 console.log('PASS: six evidence cases, 36 classifications and 18 investigation choices, reset/focus/reinit/storage, twelve checks with 36 independent answer paths and five section mappings, revision 3 and six paper cases with separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
