const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math3_3_gleichungen';
// Expected answers and section mapping are independent of the stored correct flags.
const answers={m33_q1:0,m33_q2:0,m33_dip1:0,m33_twosteps:0,m33_expand:1,m33_negative:2,m33_check:0,m33_both:1,m33_route:2,m33_denominator:1,m33_fraction:2,m33_cost_compare:0,m33_formula_height:2,m33_none:0,m33_all:1};
const sections=[['m33_q1','m33_q2','m33_dip1'],['m33_twosteps','m33_expand','m33_negative'],['m33_check','m33_both','m33_route'],['m33_denominator','m33_fraction'],['m33_cost_compare','m33_formula_height'],['m33_none','m33_all']];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 assert.equal(data[id].sections.length,6);assert.equal(d.querySelectorAll('[data-equation3-tasks]>li').length,18);assert.equal(d.querySelectorAll('[data-equation3-x]').length,5);assert.equal(d.querySelectorAll('[data-equation3-x="cancelled"]').length,4);assert.equal(d.querySelectorAll('[data-equation3-unit]').length,13);
 const saved=JSON.stringify(w.localStorage),lab=d.querySelector('[data-equation3-lab]'),task=lab.querySelector('[data-equation3-task]'),op=lab.querySelector('[data-equation3-operation]'),input=lab.querySelector('input'),apply=lab.querySelector('[data-equation3-apply]'),undo=lab.querySelector('[data-equation3-undo]'),feedback=lab.querySelector('[role=status]'),current=lab.querySelector('[data-equation3-current]');
 const choose=t=>{task.value=String(t);task.dispatchEvent(new w.Event('change'));};
 const step=(operation,value)=>{op.value=operation;input.value=String(value);input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));};
 const state=()=>JSON.parse(lab.dataset.linearState).map(([n,d])=>Number(n)/Number(d));
 const starts=[[3,4,2,9],[2,-6,1,4],[-2,5,0,11],[1/3,2/3,0,4],[2,2,2,2],[2,1,2,4]],solutions=[5,10,-3,10];let calculations=0;
 for(let t=0;t<6;t++)for(const operation of ['add','subtract','addx','subtractx','multiply','divide'])for(const value of [-3,-1,-.5,0,.5,1,2,3]){
  choose(t);step(operation,value);const expected=starts[t].slice(),rejected=value===0&&['multiply','divide'].includes(operation);
  if(['add','subtract'].includes(operation))for(const i of [1,3])expected[i]+=value*(operation==='add'?1:-1);
  if(['addx','subtractx'].includes(operation))for(const i of [0,2])expected[i]+=value*(operation==='addx'?1:-1);
  if(!rejected&&['multiply','divide'].includes(operation))for(let i=0;i<4;i++)expected[i]=operation==='multiply'?expected[i]*value:expected[i]/value;
  const actual=state();actual.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-10));assert.equal(lab.querySelectorAll('[data-equation3-history]>li').length,rejected?0:1);
  const[a,b,c,d]=actual;if(t<4){assert.ok(Math.abs(a*solutions[t]+b-c*solutions[t]-d)<1e-10);assert.notEqual(a,c);}else{assert.equal(a,c);assert.equal(b===d,t===4);}calculations++;
 }
 const routes=[{task:0,steps:[['subtractx',2],['subtract',4]],text:'x = 5',probe:19},{task:0,steps:[['subtractx',3],['subtract',9],['divide',-1]],text:'5 = x',probe:19},{task:1,steps:[['subtractx',1],['add',6]],text:'x = 10',probe:14},{task:2,steps:[['subtract',5],['divide',-2]],text:'x = −3',probe:11},{task:3,steps:[['multiply',3],['subtract',2]],text:'x = 10',probe:4}];
 for(const route of routes){choose(route.task);for(const args of route.steps)step(...args);assert.equal(current.textContent,route.text);assert.ok(feedback.textContent.includes('links '+route.probe+', rechts '+route.probe));assert.equal(lab.querySelectorAll('[data-equation3-history]>li').length,route.steps.length);}
 choose(4);step('subtractx',2);assert.equal(current.textContent,'2 = 2');assert.match(feedback.textContent,/Alle rationalen Zahlen/);choose(5);step('subtractx',2);assert.equal(current.textContent,'1 = 4');assert.match(feedback.textContent,/keine Lösung/);
 choose(0);step('add',2);assert.equal(current.textContent,'3x + 6 = 2x + 11');w.topicInit();assert.equal(lab.querySelectorAll('[data-equation3-history]>li').length,1);undo.click();assert.deepEqual(state(),starts[0]);assert.equal(d.activeElement,apply);assert.equal(undo.disabled,true);
 for(const [text,value]of [['1/3',1/3],['2/-4',-.5],['−1 / +2',-.5],['+2',2],['+1,25',1.25],['0.125',.125]]){choose(0);step('add',text);assert.ok(Math.abs(state()[1]-4-value)<1e-10);assert.equal(input.hasAttribute('aria-invalid'),false);}
 choose(0);step('multiply','1/3');step('multiply',3);assert.deepEqual(state(),starts[0]);
 for(const bad of ['',' ','1/0','1/-00','abc','1e2','1+2','NaN','Infinity','1.0001','1000000','1/2/3']){choose(0);step('add',bad);assert.equal(input.getAttribute('aria-invalid'),'true',bad);assert.deepEqual(state(),starts[0]);assert.equal(lab.querySelectorAll('[data-equation3-history]>li').length,0);input.dispatchEvent(new w.Event('input'));assert.equal(input.hasAttribute('aria-invalid'),false);}
 choose(0);step('multiply',999999);const before=lab.dataset.linearState;step('multiply',999999);assert.equal(lab.dataset.linearState,before);assert.match(feedback.textContent,/zu groß/);undo.click();assert.deepEqual(state(),starts[0]);
 choose(2);step('add',2);lab.querySelector('[data-equation3-reset]').click();assert.equal(task.value,'2');assert.deepEqual(state(),starts[2]);assert.equal(d.activeElement,op);assert.equal(JSON.stringify(w.localStorage),saved);
 const questions=w.currentChapterQuiz.questions;assert.equal(questions.length,15);assert.deepEqual(Array.from(questions,q=>q.id).sort(),Object.keys(answers).sort());let paths=0;
 for(const[i,q]of questions.entries()){assert.equal(q.sectionIndex,sections.findIndex(s=>s.includes(q.id)));for(let answer=0;answer<3;answer++){questions.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?answer:answers[item.id])+'"]').checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,answer===answers[q.id]?100:93);assert.deepEqual(r.reviewQuestionIds,answer===answers[q.id]?[]:[q.id]);assert.equal(r.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[answer].feedback));paths++;}}
 assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:1}).passed,false);dom.window.close();
 const legacy=new JSDOM('<input id="gl1"><p id="glFb"></p>',{runScripts:'outside-only'});legacy.window.eval(read('js/topics/'+id+'.js'));legacy.window.document.getElementById('gl1').value='5';legacy.window.checkGl();assert.match(legacy.window.document.getElementById('glFb').textContent,/^Richtig:/);legacy.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pd.getElementById('ws-math-material');assert.equal(material.querySelectorAll('article').length,6);assert.equal(material.querySelectorAll('[data-equation3-tasks]>li').length,18);assert.equal(material.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(material.querySelectorAll('[data-equation3-paper-history] tbody tr').length,5);assert.equal(material.querySelectorAll('[data-equation3-paper-cases]>li').length,6);assert.equal(material.querySelectorAll('button,input,select,[role=status]').length,0);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,15);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,6);assert.equal(pd.getElementById('ws-print').disabled,false);
 function checkGenerated(tasks,solutions){assert.equal(tasks.length,8);assert.equal(solutions.length,8);for(let i=0;i<8;i++){const {a,b,c,d}=Object.fromEntries(Object.entries(tasks[i].dataset).map(([k,v])=>[k,Number(v)])),x=Number(solutions[i].dataset.generatedAnswer);assert.notEqual(a,c);assert.equal((d-b)/(a-c),x);assert.equal(a*x+b,c*x+d);assert.ok(tasks[i].textContent.includes(a+'x + '+b+' = '+c+'x '+(d<0?'- '+Math.abs(d):'+ '+d)));assert.ok(solutions[i].textContent.includes('links '+a+' · ('+x+') + '+b+' = '+(a*x+b)));assert.ok(solutions[i].textContent.includes('rechts '+c+' · ('+x+') + ('+d+') = '+(c*x+d)));assert.equal(solutions[i].querySelector('h3').textContent,'Zusatzübung A'+(i+1));}}
 const generated=pd.querySelectorAll('[data-generated-equation3]');checkGenerated(generated,pd.querySelectorAll('#ws-solutions .ws-generated-equation-solution'));assert.equal(pd.querySelectorAll('template[data-generated-worksheet-solutions]').length,0);assert.equal(pd.getElementById('ws-solutions').hidden,true);
 const draw=Array.from(generated,e=>e.textContent),toggle=pd.getElementById('ws-include-solutions');for(const checked of [true,false,true]){toggle.checked=checked;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,!checked);assert.deepEqual(Array.from(generated,e=>e.textContent),draw);}
 for(const seed of [0,.5,.999999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);checkGenerated(host.querySelectorAll('[data-generated-equation3]'),host.querySelector('template').content.querySelectorAll('.ws-generated-equation-solution'));}paper.window.close();
 console.log(`PASS: year-three equations: ${paths} independently keyed quiz paths/section/revision mappings; ${calculations} operations and solution invariants; alternative routes, exact fractions, zero/invalid/large input, undo/reset/no storage; six-section paper and 32 generated task/solution pairs.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
