'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),topic='bio_2_mikroorganismen';
const keys={bio_2_mikroorganismen_s1:[1,0],bio_2_mikroorganismen_d1:[2,0],bio_2_mikroorganismen_d2:[0,0],bio_2_mikroorganismen_s2:[2,1],bio_2_microbe_samples:[0,1],bio_2_mikroorganismen_s3:[1,2],bio_2_mikroorganismen_d5:[2,2],bio_2_mikroorganismen_s4:[0,3],bio_2_mikroorganismen_d3:[1,3],bio_2_mikroorganismen_d4:[2,3],bio_2_microbe_late:[1,3],bio_2_mikroorganismen_s5:[1,4]};
// Hand-written access paths to all eight states, in hands/tools/salad order.
const paths={'000':[],'100':['touch'],'110':['cut'],'010':['cut','hands'],'111':['cut','salad'],'011':['cut','salad','hands'],'101':['cut','salad','tools'],'001':['cut','salad','hands','tools']};
const expected={touch:['100','101','110','111','100','101','110','111'],cut:['110','111','110','111','110','111','110','111'],hands:['000','001','010','011','000','001','010','011'],tools:['000','001','000','001','100','101','100','101'],salad:['000','111','111','111','111','111','111','111']};
(async()=>{const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+topic,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+topic+'.js'));w.topicInit();w.topicInit();const zone=d.querySelector('[data-kitchen-trace]'),reset=zone.querySelector('[data-microbe-reset]'),status=zone.querySelector('[role=status]'),snapshot=()=>['hands','tools','salad'].map(id=>zone.querySelector(`[data-microbe-station="${id}"]`).dataset.marked==='true'?'1':'0').join(''),act=id=>zone.querySelector(`[data-microbe-action="${id}"]`).click(),store=JSON.stringify(w.localStorage);
 for(const [state,sequence]of Object.entries(paths))for(const action of Object.keys(expected)){reset.click();sequence.forEach(act);assert.equal(snapshot(),state);const button=zone.querySelector(`[data-microbe-action="${action}"]`);button.focus();button.click();const next=expected[action][parseInt(state,2)];assert.equal(snapshot(),next,state+' '+action);assert.equal(d.activeElement,button);assert.ok(status.textContent.startsWith('Schritt '+(sequence.length+1)+':'));assert.ok(status.textContent.includes(`Hände ${next[0]}, Geräte ${next[1]}, Salat ${next[2]}`));assert.equal(zone.querySelector('[data-microbe-station="source"]').dataset.marked,'true');assert.ok(zone.querySelectorAll('[data-microbe-history] li').length<=4);}
 reset.click();assert.equal(snapshot(),'000');assert.equal(zone.querySelectorAll('[data-microbe-history] li').length,0);assert.equal(d.activeElement,zone.querySelector('[data-microbe-action="touch"]'));assert.equal(JSON.stringify(w.localStorage),store);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,12);for(const [i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,n)=>d.querySelector(`input[name="chapter_q_${n}"][value="${i===n?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[topic];assert.equal(result.lastPercent,choice===keys[q.id][0]?100:92);assert.deepEqual(result.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 assert.equal(w.chapterRevision(topic),2);assert.equal(w.currentChapterResult(topic,{passed:true}).outdated,true);assert.equal(d.querySelectorAll('.bio-training-panel[data-assignment-mode="direct"]').length,5);assert.equal(d.querySelectorAll('.bio-training-card').length,15);const authored=new JSDOM(data[topic].sections.map(s=>s.content).join('')).window.document;assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.ok(data[topic].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).every(q=>q.answers.every(a=>a.pts===0)));assert.equal(d.querySelectorAll('[data-microbe-solution]').length,5);assert.equal(d.querySelectorAll('img').length,0);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+topic,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.ok(pd.querySelector('[data-microbe-paper]'));assert.equal(pd.querySelectorAll('[data-microbe-paper] tbody tr').length,6);assert.equal(pd.querySelectorAll('#ws-solutions [data-microbe-solution]').length,5);assert.equal(pd.querySelectorAll('#ws-biology-material [data-microbe-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material button').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material .microbe-data tbody tr').length,18);paper.window.close();console.log('PASS: all 40 transitions across eight trace states, stable focus/reset/history/storage, 36 independently keyed answers and review sections, 15 direct tasks, full paper rules/protocol and five separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
