const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb5_information',keys=require('./fixtures/dgb5_information_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const stored=JSON.stringify(w.localStorage),lab=d.querySelector('[data-source-cases]'),control=lab.querySelector('select'),cards=[...lab.querySelectorAll('[data-boundary-case]')],status=lab.querySelector('[role=status]');let decisions=0;
 for(const [i,key]of [1,0,2].entries()){
  control.value=String(i);control.dispatchEvent(new w.Event('change'));assert.deepEqual(cards.map(c=>c.hidden),[0,1,2].map(j=>i!==j));assert.match(status.textContent,/Vergleiche die Karten/);
  for(let a=0;a<3;a++){cards[i].querySelectorAll('button')[a].click();assert.equal(status.textContent.startsWith('Richtig:'),a===key);assert.ok(status.textContent.length>70);decisions++;}
 }
 lab.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.match(status.textContent,/Vergleiche die Karten/);assert.equal(JSON.stringify(w.localStorage),stored);
 assert.deepEqual([...d.querySelectorAll('[data-information-source]')].map(e=>e.dataset.informationSource),['A','B','C','D']);assert.match(d.querySelector('[data-information-source="B"]').textContent,/ab 12 Uhr geschlossen/);assert.match(d.querySelector('[data-information-source="C"]').textContent,/Quelle nennt der Beitrag den Wochenplan A/);
 assert.equal(d.querySelectorAll('[data-information-tasks]>li').length,15);assert.equal(d.querySelectorAll('[data-search-task]>li').length,5);assert.equal(d.querySelectorAll('[data-file-practice]>li').length,7);assert.equal(d.querySelectorAll('[data-research-protocol]>article').length,2);
 const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));assert.deepEqual(Array.from(qs,q=>q.sectionIndex),[0,0,1,1,1,2,2,3,3,3]);let answers=0;
 for(const [i,q]of qs.entries())for(let a=0;a<3;a++){
  qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:90);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));answers++;
 }
 assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).outdated,true);const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[0,2,1]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-information-source]').length,4);assert.equal(material.querySelectorAll('[data-source-case-paper] .ai-paper-case').length,3);assert.equal(material.querySelectorAll('[data-research-protocol]>article').length,2);assert.equal(material.querySelectorAll('[data-information-tasks]>li').length,15);assert.equal(material.querySelectorAll('[data-file-practice]>li').length,7);assert.equal(material.querySelectorAll('[data-search-task]>li').length,5);assert.equal(material.querySelectorAll('button,input,select,details,[data-feedback]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions .ws-paper-solution').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,10);paper.window.close();
 assert.equal(decisions,9);assert.equal(answers,30);console.log('PASS: nine evidence decisions, reset/focus/stale feedback, 30 independent quiz answer paths, revision 3, 27 tasks, two research protocols and four separate worksheet solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
