'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
const keys={m46_q1:0,m46_q2:0,m46_dip1:0,sphere_q0:0,sphere_q1:0,sphere_q2:0,sphere_q3:0,round_cylinder_height:1,round_cylinder_radius:2,round_surface_possible:0,round_cone_height:2,round_cone_surface:0,round_cone_radius:1,round_mass_units:0,round_density:2,round_hollow:1,round_density_unit:2};
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=math4_6_koerper',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','sphere-lab','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/math4_6_koerper.js'));let injected=0;w.GGBApplet=function(){this.inject=()=>injected++;};w.topicInit();w.topicInit();assert.equal(injected,0);const optional=d.querySelector('.round-optional');optional.open=true;optional.dispatchEvent(new w.Event('toggle'));optional.open=false;optional.dispatchEvent(new w.Event('toggle'));optional.open=true;optional.dispatchEvent(new w.Event('toggle'));assert.equal(injected,1);
 assert.equal(w.chapterRevision('math4_6_koerper'),3);assert.equal(w.currentChapterResult('math4_6_koerper',{revision:2,passed:true}).passed,false);assert.equal(w.currentChapterQuiz.questions.length,17);assert.equal(d.querySelectorAll('[data-round-tasks] li').length,9);assert.equal(d.querySelectorAll('[data-round-solution]').length,3);
 const saved=JSON.stringify(w.localStorage),set=(id,v)=>{const e=d.getElementById(id);e.value=String(v);e.dispatchEvent(new w.Event('change'));};let inverseCases=0,massCases=0,paths=0;
 for(const mode of ['cylinder_h','cylinder_r','cylinder_surface','cone_h','cone_r','cone_surface'])for(let i=0;i<6;i++){
  set('round-mode',mode);set('round-case',i);const [r,h]=[[3,4],[5,12],[8,15],[6,8],[10,24],[16,30]][i],cone=mode.startsWith('cone'),v=Math.PI*r*r*h/(cone?3:1),surface=cone?Math.PI*r*(r+Math.hypot(r,h)):2*Math.PI*r*(r+h),expected=mode.endsWith('_r')?r:h,m=w.roundInverseModel(mode,i);assert.equal(m.answer,expected);assert.ok(Math.abs(m.v*Math.PI-v)<1e-10);assert.ok(Math.abs(m.o*Math.PI-surface)<1e-10);const recovered=mode.endsWith('_surface')?(cone?Math.sqrt((surface/(Math.PI*r)-r)**2-r*r):(surface-2*Math.PI*r*r)/(2*Math.PI*r)):mode.endsWith('_r')?Math.sqrt(v*(cone?3:1)/(Math.PI*h)):v*(cone?3:1)/(Math.PI*r*r);assert.ok(Math.abs(recovered-expected)<1e-10);
  const a=d.getElementById('round-answer'),out=d.getElementById('round-status');assert.equal(a.value,'');assert.equal(out.textContent,'');a.value=String(expected);a.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(out.textContent,/^Richtig/);assert.equal(d.activeElement,out);assert.ok(d.querySelector('[data-round-steps]').textContent.includes('Probe:'));a.value=String(expected+1);d.querySelector('[data-round-check]').click();assert.match(out.textContent,/^Noch nicht/);a.dispatchEvent(new w.Event('input'));assert.equal(out.textContent,'');assert.equal(d.querySelector('[data-round-steps]').textContent,'');inverseCases++;
 }
 for(const shape of ['cylinder','cone'])for(const r of [2,3,5])for(const h of [6,12])for(let material=0;material<3;material++)for(const target of ['mass','density']){
  for(const [k,v]of Object.entries({shape,r,h,material,target}))set('mass-'+k,v);const density=[.5,1.2,2.7][material],volume=Math.PI*r*r*h/(shape==='cone'?3:1),expected=target==='mass'?volume*density:density,m=w.roundMassModel(shape,r,h,material,target);assert.ok(Math.abs(m.volume-volume)<1e-10);assert.ok(Math.abs(m.mass-volume*density)<1e-10);assert.ok(Math.abs(m.answer-expected)<1e-10);const a=d.getElementById('mass-answer'),out=d.getElementById('mass-status');assert.equal(a.value,'');assert.equal(out.textContent,'');a.value=expected.toFixed(2).replace('.',',');a.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(out.textContent,/^Richtig/);assert.equal(d.activeElement,out);a.value=(expected+1).toFixed(2);d.querySelector('[data-mass-check]').click();assert.match(out.textContent,/^Noch nicht/);a.dispatchEvent(new w.Event('input'));assert.equal(out.textContent,'');massCases++;
 }
 for(const prefix of ['round','mass']){const a=d.getElementById(prefix+'-answer');for(const bad of ['','0','-1','10001','NaN','1e2','3cm']){a.value=bad;d.querySelector('[data-'+prefix+'-check]').click();assert.equal(a.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,a);}d.querySelector('[data-'+prefix+'-reset]').click();assert.equal(d.activeElement.id,prefix==='round'?'round-mode':'mass-shape');assert.equal(a.getAttribute('aria-invalid'),null);}
 const quick=d.getElementById('cyl_v');quick.value='200';quick.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(d.getElementById('koerper_feedback').textContent,/^Richtig/);quick.dispatchEvent(new w.Event('input'));assert.equal(d.getElementById('koerper_feedback').textContent,'');assert.equal(JSON.stringify(w.localStorage),saved);
 for(const [i,q]of w.currentChapterQuiz.questions.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let choice=0;choice<q.answers.length;choice++){w.currentChapterQuiz.questions.forEach((q,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?choice:keys[q.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results')).math4_6_koerper;assert.equal(r.lastPercent,choice===keys[q.id]?100:94);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;}}
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=math4_6_koerper',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.round-paper').length,4);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,2);assert.equal(pd.querySelectorAll('#ws-solutions [data-round-solution]').length,3);assert.equal(pd.getElementById('ws-solutions').hidden,true);
 const verify=(tasks,answers)=>{assert.equal(tasks.length,8);assert.equal(answers.length,8);tasks.forEach((task,i)=>{const {kind,cone}=task.dataset,r=Number(task.dataset.r),h=Number(task.dataset.h),rho=Number(task.dataset.rho),volume=Math.PI*r*r*h/(cone==='true'?3:1),expected=kind==='volume'?volume:kind==='height_surface'?h:kind==='radius'?r:kind==='mass'?volume*rho:rho;assert.ok(Math.abs(Number(answers[i].dataset.roundGeneratedAnswer)-expected)<1e-9);assert.ok(answers[i].textContent.includes(expected.toLocaleString('de-AT',{maximumFractionDigits:2})));});};verify([...pd.querySelectorAll('[data-round-generated]')],[...pd.querySelectorAll('[data-round-generated-answer]')]);for(const random of [0,.2,.5,.8,.99999]){pw.Math.random=()=>random;const box=pd.createElement('div');box.innerHTML=pw.generateWorksheetContent('math4_6_koerper','Körper');verify([...box.querySelectorAll('[data-round-generated]')],[...box.querySelector('template[data-generated-worksheet-solutions]').content.querySelectorAll('[data-round-generated-answer]')]);}
 assert.equal(inverseCases,36);assert.equal(massCases,72);assert.equal(paths,48);paper.window.close();dom.window.close();console.log('PASS: 36 inverse cases with forward probes, 72 mass/density cases, 48 quiz answer paths, input/focus/reset/storage/lazy explorer; four paper alternatives, two figures, eight generated solutions and 40 controlled generator cases.');
})().catch(e=>{console.error(e);process.exitCode=1;});
