const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
const normalCurrents={fixed:[1,1,1,1,1,1,1,1],commutator:[1,1,0,-1,-1,-1,0,1]},normalTorque={fixed:[1,1,0,-1,-1,-1,0,1],commutator:[1,1,0,1,1,1,0,1]};
const near=(a,b)=>assert.ok(Math.abs(a-b)<0.002,`${a} != ${b}`);
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=elektromagnetismus',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer','topics/elektromagnetismus'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 const lab=d.querySelector('[data-motor-lab]'),angle=lab.querySelector('[data-motor-angle]'),mode=lab.querySelector('[data-motor-mode]'),polarity=lab.querySelector('[data-motor-polarity]'),power=lab.querySelector('[data-motor-power]'),initialStorage=JSON.stringify(w.localStorage);let states=0,decisions=0;
 for(const m of ['fixed','commutator'])for(const p of ['normal','reverse'])for(const supply of ['on','off'])for(let i=0;i<8;i++){
  for(const[el,v]of [[mode,m],[polarity,p],[power,supply],[angle,String(i*45)]]){el.value=v;el.focus();el.dispatchEvent(new w.Event(el===angle?'input':'change'));assert.equal(d.activeElement,el);}const s=w.sciverseMotorState(i*45,m,p,supply),sign=p==='normal'?1:-1,expectedI=supply==='off'?0:normalCurrents[m][i]*sign,expectedT=supply==='off'?0:normalTorque[m][i]*sign;
  assert.ok(s.currentA===expectedI);assert.ok(s.currentB===-expectedI);assert.ok(s.direction===expectedT);assert.equal(s.contactGap,m==='commutator'&&(i===2||i===6));near(s.torque,Math.cos(i*Math.PI/4)*expectedI);
  const points={A:[180+60*Math.cos(i*Math.PI/4),140-60*Math.sin(i*Math.PI/4)],B:[180-60*Math.cos(i*Math.PI/4),140+60*Math.sin(i*Math.PI/4)]};
  for(const name of ['A','B']){const g=lab.querySelector('[data-motor-side="'+name+'"]'),circle=g.querySelector('circle'),cur=name==='A'?expectedI:-expectedI;near(Number(circle.getAttribute('cx')),points[name][0]);near(Number(circle.getAttribute('cy')),points[name][1]);assert.ok(Number(g.dataset.current)===cur);const force=g.querySelector('[data-motor-force]');assert.equal(!!force,cur!==0);if(force){const coords=force.getAttribute('d').match(/-?\d+(?:\.\d+)?/g).map(Number);assert.equal(Math.sign(coords[2]-coords[1]),-cur);near(Math.abs(coords[2]-coords[1]),35);}}
  assert.equal(lab.querySelector('[data-motor-feedback]').textContent,'');for(const b of lab.querySelectorAll('[data-motor-verdict]')){b.click();assert.equal(lab.querySelector('[data-motor-feedback]').textContent.startsWith('Richtig:'),Number(b.dataset.motorVerdict)===expectedT);decisions++;}states++;
 }
 assert.equal(states,64);assert.equal(decisions,192);for(const el of [angle,mode,polarity,power]){assert.equal(el.labels.length,1);assert.equal(el.getAttribute('aria-describedby'),'motor-status');}
 w.initMotorLab();assert.equal(angle.value,'315');lab.querySelector('[data-motor-step="45"]').click();assert.equal(angle.value,'0');lab.querySelector('[data-motor-step="-45"]').click();assert.equal(angle.value,'315');lab.querySelector('[data-motor-reset]').click();assert.deepEqual([angle.value,mode.value,polarity.value,power.value],['0','commutator','normal','on']);assert.equal(d.activeElement,angle);assert.equal(lab.querySelector('[data-motor-feedback]').textContent,'');assert.equal(JSON.stringify(w.localStorage),initialStorage);
 for(const params of [[-45,'fixed','normal','on'],[360,'fixed','normal','on'],[22,'fixed','normal','on'],['x','fixed','normal','on'],[0,'other','normal','on'],[0,'fixed','other','on'],[0,'fixed','normal','other']])assert.equal(w.sciverseMotorState(...params),null);
 assert.equal(d.querySelectorAll('[data-motor-static] svg[data-worksheet-static]').length,2);assert.equal(d.querySelectorAll('[data-motor-tasks]>li').length,4);assert.ok(lab.textContent.includes('keine berechnete Drehbewegung'));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic=elektromagnetismus',runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-motor-paper] tbody tr').length,8);assert.equal(pd.querySelectorAll('[data-motor-static] svg').length,2);assert.equal(pd.querySelectorAll('[data-motor-tasks]>li').length,4);assert.ok(!pd.getElementById('ws-physics-material').textContent.includes('Tabellenreihenfolge'));assert.ok(pd.getElementById('ws-solutions').textContent.includes('Tabellenreihenfolge'));assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.getElementById('ws-print').disabled,false);paper.window.close();console.log('PASS: motor: 64 independently expected states, 192 classifications, current/force/torque geometry, dead points, control focus/reset/wrap, no storage, two static figures and eight paper cases.');
})().catch(e=>{console.error(e);process.exitCode=1;});
