const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='bio_1_ernaehrung_verdauung';
// Independent expected decisions and section targets, not copied from authored flags.
const correct={bio_ernaehrung_s1:1,bio_ernaehrung_s2:2,bio_ernaehrung_s3:0,bio_ernaehrung_s4:1,bio_ernaehrung_s5:2,bio_ernaehrung_d1:1,bio_ernaehrung_d2:2,bio_ernaehrung_d3:0,bio_ernaehrung_d4:1,bio_ernaehrung_d5:2,bio_ernaehrung_d6:0,bio_ernaehrung_portion:1,bio_ernaehrung_fehlend:2};
const sections={bio_ernaehrung_s1:0,bio_ernaehrung_s2:1,bio_ernaehrung_s3:2,bio_ernaehrung_s4:3,bio_ernaehrung_s5:4,bio_ernaehrung_d1:4,bio_ernaehrung_d2:0,bio_ernaehrung_d3:0,bio_ernaehrung_d4:1,bio_ernaehrung_d5:3,bio_ernaehrung_d6:4,bio_ernaehrung_portion:3,bio_ernaehrung_fehlend:3};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')),texts=doc=>[...doc.querySelectorAll('.bio-training-card')].map(e=>e.textContent);assert.equal(texts(d).length,15);assert.deepEqual(texts(d),texts(authored.window.document));assert.equal(d.querySelectorAll('.bio-training-direct-text').length,0);authored.window.close();
 const model=d.querySelector('[data-core-experiment="digestion-model"]'),control=model.querySelector('select'),stages=[...model.querySelectorAll('[data-digestion-stage]')],saved=JSON.stringify(w.localStorage);assert.equal(stages.length,4);
 for(let i=0;i<4;i++){
  control.value=String(i);control.dispatchEvent(new w.Event('change'));assert.deepEqual(stages.map(e=>e.hidden),[0,1,2,3].map(x=>x!==i));const stage=stages[i];assert.equal(stage.querySelectorAll('[data-glucose-unit]').length,6);assert.equal(stage.querySelectorAll('[data-starch-link]').length,[4,4,0,0][i]);assert.equal(stage.querySelectorAll('[data-food-piece]').length,[1,2,0,0][i]);assert.equal(stage.querySelectorAll('[data-gut-wall]').length,i===3?1:0);assert.ok(model.querySelector('[role=status]').textContent.includes('Bild '+(i+1)+' von 4'));
  if(i===3){const x=[...stage.querySelectorAll('circle')].map(e=>Number(e.getAttribute('cx')));assert.equal(x.filter(v=>v<143).length,3);assert.equal(x.filter(v=>v>157).length,3);assert.match(stage.textContent,/Verwertung/);}
 }
 w.enhanceCoreLearning(data[id],id,'de');assert.equal(control.value,'3');model.querySelector('button').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);
 const z=d.querySelector('[data-core-experiment="drink-portions"]'),fields=['a','b'].map(k=>z.querySelector('[data-drink-amount="'+k+'"]')),out=z.querySelector('[data-drink-result]');let cases=0;
 for(let a=0;a<=500;a+=50)for(let b=0;b<=500;b+=50){
  for(const [i,value]of [a,b].entries()){fields[i].value=String(value);fields[i].dispatchEvent(new w.Event('input'));}
  const amounts=[a*0.06,b*0.04];for(const [i,key]of ['a','b'].entries()){
   assert.equal(z.querySelector('[data-drink-volume="'+key+'"]').textContent,String([a,b][i]));assert.ok(Math.abs(Number(z.querySelector('[data-drink-bar="'+key+'"]').getAttribute('width'))-amounts[i]/30*260)<1e-8);assert.equal(z.querySelector('[data-drink-label="'+key+'"]').textContent,key.toUpperCase()+': '+amounts[i]+' g Zucker');
  }
  const compared=amounts[0]===amounts[1]?'gleich viel':amounts[0]>amounts[1]?'Menge A enthält mehr':'Menge B enthält mehr';assert.ok(out.textContent.includes(compared));assert.ok(out.textContent.includes('je 100 ml bleiben A: 6 g und B: 4 g'));cases++;
 }
 assert.equal(cases,121);z.querySelector('button').click();assert.equal(fields[0].value,'200');assert.equal(fields[1].value,'500');assert.equal(d.activeElement,fields[0]);assert.match(out.textContent,/12 g.*20 g/);assert.equal(JSON.stringify(w.localStorage),saved);
 const questions=w.currentChapterQuiz.questions;assert.equal(questions.length,13);assert.deepEqual(Array.from(questions,q=>q.id).sort(),Object.keys(correct).sort());assert.equal(data[id].diplom.questions.length,0);let paths=0;
 for(const [i,q]of questions.entries()){
  assert.equal(q.sectionIndex,sections[q.id]);for(let choice=0;choice<3;choice++){
   questions.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?choice:correct[item.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,choice===correct[q.id]?100:92);assert.deepEqual(result.reviewQuestionIds,choice===correct[q.id]?[]:[q.id]);assert.equal(result.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;
  }
 }
 assert.equal(paths,39);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).passed,true);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pw.document.getElementById('ws-biology-material'),solutions=pw.document.getElementById('ws-solutions');assert.equal(material.querySelectorAll('article').length,5);assert.equal(material.querySelectorAll('.bio-training-card').length,15);assert.equal(material.querySelectorAll('.ws-glossary-entry').length,27);assert.equal(material.querySelectorAll('[data-digestion-protocol] tbody tr').length,4);assert.equal(material.querySelectorAll('[data-drink-paper-table] tbody tr').length,3);assert.equal(material.querySelectorAll('[data-digestion-paper] svg[data-worksheet-static]').length,4);assert.equal(material.querySelectorAll('[data-drink-paper] svg[data-worksheet-static]').length,1);assert.equal(material.querySelectorAll('select,input,button,[data-digestion-stage],[data-drink-chart]').length,0);assert.equal(solutions.hidden,true);assert.match(solutions.textContent,/200 ml A = 12 g und 300 ml B = 12 g/);assert.match(solutions.textContent,/Bild 2: Lebensmittelstück geteilt/);assert.ok(!material.textContent.includes('Bild 2: Lebensmittelstück geteilt'));paper.window.close();
 assert.ok(material.querySelector('[data-drink-paper]').textContent.includes('200 ml A und 500 ml B'));
 console.log('PASS: nutrition/digestion: 39 independently keyed answers, section/revision checks, 15 preserved tasks, four molecular-model states, 121 portion comparisons and bar scales, reset/focus/re-init/storage, 27 glossary entries, five paper diagrams, protocols and separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
