const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),data=JSON.parse(read('lang/de.json'));
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/physik_bay6/topics/template.html?topic=math4_6_koerper',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(resolve=>setImmediate(resolve));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','core-learning','sphere-lab','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
assert.equal(d.querySelectorAll('.practice-box').length,16);assert.ok(d.getElementById('ggb-koerper'));const zone=d.querySelector('[data-sphere-lab]'),input=zone.querySelector('input');
for(let r=1;r<=10;r++){input.value=r;input.dispatchEvent(new w.Event('input'));const s=w.sphereMeasures(r);assert.ok(Math.abs(s.surface/(Math.PI*r*r)-4)<1e-10);assert.ok(Math.abs(s.volume/(Math.PI*r*r*r)-4/3)<1e-10);assert.equal(Number(zone.querySelector('circle').getAttribute('r')),10*r);assert.equal(Number(zone.querySelector('[data-radius-line]').getAttribute('x2')),130+10*r);assert.match(zone.querySelector('[data-status]').textContent,/cm².*cm³/);}
const small=w.sphereMeasures(2),large=w.sphereMeasures(4);assert.equal(large.surface/small.surface,4);assert.equal(large.volume/small.volume,8);w.initSphereLabs();assert.equal(zone.querySelectorAll('svg').length,1);assert.match(data.math4_6_koerper.sections[1].content,/gleicher Grundfläche.*gleicher senkrechter Höhe/);
w.eval(read('js/topics/math4_6_koerper.js'));w.bindKoerperHintExercise();w.bindKoerperHintExercise();assert.equal(d.querySelectorAll('[data-check-cylinder]').length,1);const answer=d.getElementById('cyl_v'),feedback=()=>d.getElementById('koerper_feedback').textContent;
d.querySelector('[data-check-cylinder]').click();assert.match(feedback(),/zuerst/);answer.value=30;d.querySelector('[data-check-cylinder]').click();assert.match(feedback(),/Noch nicht/);answer.value=200;answer.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(feedback(),/Richtig.*200 cm³/);dom.window.close();
console.log('PASS: expanded solid-geometry chapter, 16 practice questions, retained GeoGebra, ten sphere radii, dimensions/units and quadratic/cubic scaling.');
})().catch(error=>{console.error(error);process.exitCode=1;});
