const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
(async()=>{for(const denied of [false,true]){
 const dom=new JSDOM(read('topics/learning.html'),{url:'https://example.test/site/topics/learning.html?mode=teach&plan=dgb7_information,energie',runScripts:'outside-only'}),w=dom.window,d=w.document;
 w.fetch=async()=>({ok:true,json:async()=>data});if(denied)w.Storage.prototype.setItem=function(){throw new w.DOMException('Denied','SecurityError');};for(const f of ['curriculum','chapter-revisions','learning'])w.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const guide=d.getElementById('dgb-guide'),stored=JSON.stringify(w.localStorage),order=()=>[...d.querySelectorAll('#selected>li [data-focus-key^="plan-open-"]')].map(e=>e.dataset.focusKey.slice(10));assert.equal(guide.hidden,false);assert.equal(guide.open,false);assert.equal(guide.lang,'de');assert.equal(guide.querySelectorAll('.guide-stage').length,4);guide.open=true;
 const prior=order();for(const grade of ['5','6','7','8']){d.getElementById('search').value='keinKapitelXYZ9473';d.getElementById('search').dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.chapter').length,0);d.querySelector('[data-focus-key="dgb-guide-'+grade+'"]').click();assert.equal(d.getElementById('grade').value,grade);assert.equal(d.getElementById('search').value,'');assert.equal(guide.open,true);assert.equal(d.activeElement,d.getElementById('count'));assert.equal(d.querySelectorAll('.guide-stage button[aria-pressed=true]').length,1);assert.equal(d.querySelector('.guide-stage button[aria-pressed=true]').dataset.focusKey,'dgb-guide-'+grade);
 const ids=[...d.querySelectorAll('#chapters [data-focus-key^="catalog-open-"]')].map(e=>e.dataset.focusKey.slice(13));assert.equal(ids.length,grade<'7'?6:5);for(const area of ['orientierung','information','kommunikation','produktion','handeln'])assert.ok(ids.includes('dgb'+grade+'_'+area));assert.equal(ids.includes('dgb_word_werkstatt'),grade<'7');assert.deepEqual(order(),prior);assert.equal(JSON.stringify(w.localStorage),stored);assert.equal(d.querySelector('[data-mode=teach]').getAttribute('aria-pressed'),'true');assert.equal(d.querySelectorAll('.personal-result').length,0);}
 d.getElementById('subject').value='physik';d.getElementById('subject').dispatchEvent(new w.Event('input'));assert.equal(guide.hidden,true);d.getElementById('subject').value='dgb';d.getElementById('subject').dispatchEvent(new w.Event('input'));assert.equal(guide.open,true);assert.equal(guide.hidden,false);
 const summary=guide.querySelector('summary');summary.focus();d.querySelector('[data-mode=review]').click();assert.equal(d.activeElement,guide.querySelector('summary'));assert.equal(guide.open,true);d.getElementById('share').click();assert.match(decodeURIComponent(d.getElementById('share-url').value),/plan=dgb7_information,energie/);assert.equal(JSON.stringify(w.localStorage),stored);dom.window.close();
 }
 // All twenty year chapters and the supplementary workshop have existing, acyclic prerequisite links.
 const ids=Object.keys(data).filter(id=>/^dgb[5-8]_/.test(id)||id==='dgb_word_werkstatt');assert.equal(ids.length,21);const visiting=new Set(),done=new Set();function visit(id){assert.ok(data[id],id);if(done.has(id))return;assert.ok(!visiting.has(id),'prerequisite cycle '+id);visiting.add(id);for(const p of data[id].prerequisites||[])visit(p);visiting.delete(id);done.add(id);}ids.forEach(visit);
 console.log('PASS: four DGB year filters, appropriate supplementary workshop, search reset and result focus, disclosure state, unchanged ordered/shared plan and storage including denied storage; all 21 prerequisite paths valid and acyclic.');
})().catch(e=>{console.error(e);process.exitCode=1;});
