const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),cases=require('./fixtures/physics_year3_keys.json');
(async()=>{let assessed=0,practice=0;
 for(const [id,x]of Object.entries(cases)){
  const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();const qs=w.currentChapterQuiz.questions;
  assert.equal(qs.length,x.count,id);assert.equal(w.chapterRevision(id),x.revision);assert.equal(w.currentChapterResult(id,{contentRevision:x.revision-1,passed:true,bestPercent:100}).passed,false);
  for(const [qid,key]of Object.entries(x.keys)){const q=qs.find(q=>q.id===qid),index=qs.indexOf(q);assert.ok(q);assert.equal(q.sectionIndex,x.sections[qid]);assert.equal(q.answers.length,3);
   for(let a=0;a<3;a++){qs.forEach((item,i)=>d.querySelector(`input[name="chapter_q_${i}"][value="${i===index?a:item.id in x.keys?x.keys[item.id]:item.answers.findIndex(a=>a.correct)}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===key?100:Math.round(100*(x.count-1)/x.count));assert.equal(result.contentRevision,x.revision);assert.deepEqual(result.reviewQuestionIds,a===key?[]:[qid]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));if(a!==key)assert.equal(d.querySelector('#chapter-quiz-result button[onclick^="reviewChapterSection"]').getAttribute('onclick'),'reviewChapterSection('+x.sections[qid]+')');assessed++;}
  }
  const stored=JSON.stringify(w.localStorage);
  for(const [qid,key]of Object.entries(x.extra||{})){assert.ok(!qs.some(q=>q.id===qid));const q=data[id].sections.flatMap(s=>s.quizzes||[]).find(q=>q.id===qid),box=d.querySelector('.practice-box[data-id="'+qid+'"]');assert.ok(box);assert.equal(q.answers.length,3);
   q.answers.forEach((a,i)=>{const button=[...box.querySelectorAll('button')].find(b=>b.textContent.trim()===a.text);new w.Function(button.getAttribute('onclick')).call(button);assert.equal(button.classList.contains('is-correct'),i===key);assert.ok(box.querySelector('.feedback').innerText.includes(a.feedback));practice++;});
  }assert.equal(JSON.stringify(w.localStorage),stored);
  if(id==='kraft_und_bewegung'){assert.equal(d.querySelectorAll('[data-force-station]').length,4);assert.equal(d.querySelectorAll('[data-force-station-tasks]>li').length,5);assert.equal(d.querySelectorAll('[data-force-station-protocol] tbody tr').length,4);assert.equal(d.querySelectorAll('[data-mobility-options] tbody tr').length,2);assert.equal(d.querySelectorAll('[data-mobility-tasks]>li').length,5);assert.match(d.querySelector('[data-force-qualitative]').textContent,/Zuerst ohne Rechnung/);}
  if(id==='elektromagnetismus'){assert.equal(d.querySelectorAll('[data-motor-research-tasks]>li').length,4);assert.equal(d.querySelectorAll('[data-motor-research-sources] a').length,2);assert.match(d.querySelector('[data-motor-research-sources]').textContent,/31.10.2016/);}
  dom.window.close();
  const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,x.count);assert.equal(pd.querySelectorAll('#ws-extension-questions>.question-block').length,Object.keys(x.extra||{}).length);assert.equal(pd.getElementById('ws-solutions').hidden,true);
  if(id==='kraft_und_bewegung'){assert.equal(pd.querySelectorAll('#ws-physics-material [data-force-station]').length,4);assert.ok(!pd.querySelector('#ws-physics-material [data-force-station-solution]'));assert.match(pd.getElementById('ws-solutions').textContent,/mehr als 12 Minuten Wartezeit/);assert.match(pd.getElementById('ws-solutions').textContent,/Gewichtskraft wirkt vor und nach/);}
  if(id==='elektromagnetismus')assert.match(pd.getElementById('ws-solutions').textContent,/Archivdatum 2016/);paper.window.close();
 }
 assert.equal(assessed,21);assert.equal(practice,21);
 const hub=new JSDOM(read('topics/learning.html'),{url:'https://example.test/topics/learning.html?mode=teach&plan=arbeit,kraft_und_bewegung,elektromagnetismus',runScripts:'outside-only'}),w=hub.window,d=w.document;w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','learning'])w.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));d.getElementById('subject').value='physik';d.getElementById('grade').value='7';d.getElementById('grade').dispatchEvent(new w.Event('input'));assert.deepEqual([...d.querySelectorAll('#chapters [data-focus-key^="catalog-open-"]')].map(e=>e.dataset.focusKey.slice(13)),['sieinheiten','kraft_und_bewegung','energie','elektrizitaet','elektromagnetismus','arbeit','drehundstatik']);assert.deepEqual([...d.querySelectorAll('#selected [data-focus-key^="plan-open-"]')].map(e=>e.dataset.focusKey.slice(10)),['arbeit','kraft_und_bewegung','elektromagnetismus']);assert.deepEqual(data.energie.prerequisites,['kraft_und_bewegung']);assert.deepEqual(data.arbeit.prerequisites,['energie']);hub.window.close();
 console.log('PASS: 21 independently keyed new assessed answers, 21 extension answers without storage changes, source/experiment tasks and paper solutions, concept-first year-3 order with preserved teacher plan.');
})().catch(e=>{console.error(e);process.exitCode=1;});
