const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic=math2_3_dezimalzahlen',runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/math2_3_dezimalzahlen.js'));w.topicInit();w.topicInit();
 for(const [id,feedbackId,correct,hint]of [['geld_input','geld_feedback',['2,5','2.50',' 2,50 '],'Noch nicht'],['rund_input','rund_feedback',['12','12,0'],'Tipp:'],['komma_input','komma_feedback',['520','520,0'],'Noch nicht']]){
 const input=d.getElementById(id),feedback=d.getElementById(feedbackId),button=input.parentElement.querySelector('button');assert.equal(input.type,'text');assert.equal(input.inputMode,'decimal');assert.ok(input.getAttribute('aria-label'));assert.equal(d.querySelectorAll('#'+feedbackId).length,1);
 for(const value of correct){input.value=value;input.focus();input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(feedback.textContent,/Genau!|Richtig!|Super!/);assert.equal(d.activeElement,input);input.dispatchEvent(new w.Event('input'));assert.equal(feedback.textContent,'');}
 for(const value of ['',' ','2,5,0','0x208','5e2','Infinity','12abc']){input.value=value;button.click();assert.match(feedback.textContent,/Gib eine Zahl/);}
 input.value=id==='geld_input'?'2,5000000001':'1';button.click();assert.ok(feedback.textContent.startsWith(hint));
 }dom.window.close();console.log('PASS: actual decimal inputs accept comma/dot, reject malformed and empty values, preserve focus, clear stale feedback and bind once.');})().catch(e=>{console.error(e);process.exitCode=1;});
