const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='bio_1_pubertaet_fortpflanzung';
const correct={bio_pubertaet_s1:1,bio_pubertaet_d1:2,bio_pubertaet_s2:0,bio_pubertaet_d3:1,bio_pubertaet_organ:2,bio_pubertaet_s3:2,bio_pubertaet_d4:0,bio_pubertaet_s4:1,bio_pubertaet_d2:2,bio_pubertaet_d5:0,bio_pubertaet_s5:1,bio_pubertaet_d6:2,bio_pubertaet_hilfe:0};
const sections={bio_pubertaet_s1:0,bio_pubertaet_d1:0,bio_pubertaet_s2:1,bio_pubertaet_d3:1,bio_pubertaet_organ:1,bio_pubertaet_s3:2,bio_pubertaet_d4:2,bio_pubertaet_s4:3,bio_pubertaet_d2:3,bio_pubertaet_d5:3,bio_pubertaet_s5:4,bio_pubertaet_d6:4,bio_pubertaet_hilfe:4};
const reasons=[[/erkennbar/,/ohne persönliche Angaben/,/Druck/],[/keine automatische Zustimmung/,/Zuschneiden ersetzt/,/eigene Klärung/],[/Schweigen ist kein Einverständnis/,/Verantwortung/,/nicht weitere Details/],[/beendet.*nicht/,/weitere Unterstützung/,/nicht von einer Abstimmung/]];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')),texts=doc=>[...doc.querySelectorAll('.bio-training-card')].map(e=>e.textContent);assert.equal(texts(d).length,15);assert.deepEqual(texts(d),texts(authored.window.document));assert.equal(d.querySelectorAll('.bio-training-direct-text').length,0);authored.window.close();
 const z=d.querySelector('[data-core-experiment="boundary-cases"]'),control=z.querySelector('select'),cases=[...z.querySelectorAll('[data-boundary-case]')],result=z.querySelector('[role=status]'),saved=JSON.stringify(w.localStorage);assert.equal(cases.length,4);assert.equal(z.querySelectorAll('input,textarea').length,0);let decisions=0;
 for(let i=0;i<4;i++){
  control.value=String(i);control.dispatchEvent(new w.Event('change'));assert.deepEqual(cases.map(e=>e.hidden),[0,1,2,3].map(j=>i!==j));assert.equal(result.textContent,'Wähle eine Handlung.');
  for(const [j,button]of [...cases[i].querySelectorAll('button')].entries()){button.focus();button.click();assert.match(result.textContent,reasons[i][j]);assert.equal(d.activeElement,button);assert.equal(button.disabled,false);decisions++;}
 }
 assert.equal(decisions,12);w.enhanceCoreLearning(data[id],id,'de');assert.equal(control.value,'3');z.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.equal(result.textContent,'Wähle eine Handlung.');assert.equal(JSON.stringify(w.localStorage),saved);
 assert.equal(d.querySelectorAll('[data-cycle-schema] li').length,4);assert.match(d.querySelector('[data-cycle-schema]').textContent,/keine persönlichen Termine/);assert.equal(d.querySelectorAll('[data-puberty-sources]').length,1);
 const questions=w.currentChapterQuiz.questions;assert.equal(questions.length,13);assert.deepEqual(Array.from(questions,q=>q.id).sort(),Object.keys(correct).sort());assert.equal(data[id].diplom.questions.length,0);let paths=0;
 for(const [i,q]of questions.entries()){assert.equal(q.sectionIndex,sections[q.id]);for(let choice=0;choice<3;choice++){
  questions.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?choice:correct[item.id])+'"]').checked=true);w.submitChapterQuiz();const stored=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(stored.lastPercent,choice===correct[q.id]?100:92);assert.deepEqual(stored.reviewQuestionIds,choice===correct[q.id]?[]:[q.id]);assert.equal(stored.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;
 }}
 assert.equal(paths,39);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pw.document.getElementById('ws-biology-material'),solutions=pw.document.getElementById('ws-solutions');assert.equal(material.querySelectorAll('article').length,5);assert.equal(material.querySelectorAll('.bio-training-card').length,15);assert.equal(material.querySelectorAll('.ws-glossary-entry').length,25);assert.equal(material.querySelectorAll('[data-boundary-protocol] tbody tr').length,4);assert.equal(material.querySelectorAll('[data-boundary-paper-case]').length,4);assert.equal(material.querySelectorAll('[data-boundary-paper-case] li').length,12);assert.equal(material.querySelectorAll('select,input,button,[data-boundary-case]').length,0);assert.equal(solutions.hidden,true);assert.equal(solutions.querySelectorAll('.ws-paper-solution').length,2);assert.match(solutions.textContent,/Fall 1, B/);assert.match(solutions.textContent,/Fall 2, C/);assert.match(solutions.textContent,/Fall 3, A/);assert.match(solutions.textContent,/Fall 4, B/);assert.ok(!material.textContent.includes('Fall 1, B:'));assert.match(material.textContent,/keine Verhütungsmethode/);paper.window.close();
 console.log('PASS: puberty: 39 independently keyed assessed paths, section/revision checks, 15 preserved tasks, 12 decision explanations, reset/focus/re-init/no storage, four-stage cycle schema, four paper cases and protocol, 25 glossary entries and two separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
