const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math3_6_zuordnungen';
const answers={m36_q1:0,m36_dip1:0,m36_unit:2,m36_q2:0,m36_zero:0,m36_time:1,m36_graph:0,m36_falling:2,m36_fee_zero:1,m36_point:2,m36_difference:1,m36_domain:0,m36_work_parameter:1,m36_invariant:2,m36_assumptions:0};
const sections=[['m36_q1','m36_dip1','m36_unit'],['m36_q2','m36_zero','m36_time'],['m36_graph','m36_falling','m36_fee_zero'],['m36_point','m36_difference','m36_domain'],['m36_work_parameter','m36_invariant','m36_assumptions']];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 assert.equal(data[id].sections.length,5);assert.equal(d.querySelectorAll('[data-assignment-task]>li').length,15);assert.equal(d.querySelectorAll('[data-assignment-static] svg').length,3);
 const rows=[...d.querySelectorAll('[data-assignment-table] tbody tr')];assert.equal(rows.length,5);for(const row of rows){const[x,a,b,c]=[...row.cells].map(cell=>Number(cell.textContent));assert.equal(a/x,3);assert.equal(x*b,12);assert.equal(c-a,5);}
 const input=d.getElementById('kino_in'),feedback=d.getElementById('kino_feedback'),button=input.closest('.interactive-zone').querySelector('button');
 for(const value of ['50','50,00','50.0',' 50 ']){input.value=value;button.click();assert.match(feedback.textContent,/^Richtig/);assert.equal(input.hasAttribute('aria-invalid'),false);}
 for(const value of ['','1e2','0x32','50,001','-1','50abc']){input.value=value;button.click();assert.match(feedback.textContent,/Gib einen/);assert.equal(input.getAttribute('aria-invalid'),'true');}
 for(const value of ['0','10','20','100']){input.value=value;button.click();assert.match(feedback.textContent,/Noch nicht/);assert.equal(input.hasAttribute('aria-invalid'),false);}
 input.value='50';input.dispatchEvent(new w.Event('input'));assert.equal(feedback.textContent,'');input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(feedback.textContent,/^Richtig/);
 const zone=d.querySelector('[data-assignment-graph]'),model=d.getElementById('assignment-model'),parameter=zone.querySelector('[data-assignment-parameter]'),slider=d.getElementById('assignment-x'),out=d.getElementById('assignment-result'),verdict=zone.querySelector('[data-assignment-verdict-feedback]'),stored=JSON.stringify(w.localStorage);let states=0,decisions=0;
 const value=(key,p,n)=>key==='a'?p*n:key==='b'?(n===0?null:p/n):p+3*n;
 const parse=s=>Number(s.replace('≈','').replace(',','.').trim());
 for(const key of ['a','b','c'])for(const p of {a:[2,3,4],b:[6,12,24],c:[0,5,10]}[key])for(let x=0;x<=6;x++){
  model.value=key;model.dispatchEvent(new w.Event('change'));parameter.value=String(p);parameter.dispatchEvent(new w.Event('change'));slider.value=String(x);slider.focus();slider.dispatchEvent(new w.Event('input'));assert.equal(verdict.textContent,'');
  const points=[...zone.querySelectorAll('[data-assignment-point]')],selected=zone.querySelector('[data-assignment-selected]'),svg=zone.querySelector('svg');assert.equal(points.length,key==='b'?6:7);
  for(const point of points){const n=Number(point.dataset.assignmentPoint),expected=value(key,p,n);assert.equal(Number(point.dataset.value),expected);assert.equal(Number(point.getAttribute('cx')),45+45*n);assert.ok(Math.abs(Number(point.getAttribute('cy'))-(240-expected*200/(key==='b'?24:30)))<1e-8);assert.ok(Number(point.getAttribute('cy'))>=40&&Number(point.getAttribute('cy'))<=240);assert.equal(point.dataset.extension,String(key==='c'&&p>0&&n===0));if(point.dataset.extension==='true')assert.equal(point.getAttribute('fill'),'white');}
  if(key==='b'&&x===0){assert.equal(selected,null);assert.match(out.textContent,/nicht definiert/);assert.match(svg.getAttribute('aria-label'),/Kein Punkt/);}else{assert.equal(selected.dataset.assignmentSelected,String(x));assert.ok(out.textContent.includes('y = '+new Intl.NumberFormat('de-AT',{maximumFractionDigits:2}).format(value(key,p,x))+' '+(key==='b'?'Stunden':'Euro')));}
  if(key==='c'&&p>0&&x===0)assert.match(out.textContent,/Ohne Bestellung/);assert.equal(d.activeElement,slider);
  const liveRows=[...zone.querySelectorAll('[data-assignment-live-table] tbody tr')];assert.equal(liveRows.length,7);
  for(const[n,row]of liveRows.entries()){const y=value(key,p,n),cells=[...row.cells].map(c=>c.textContent);assert.equal(row.hasAttribute('data-selected'),n===x);assert.equal(cells[0].includes('*'),key==='c'&&p>0&&n===0);for(const[j,expected]of [[1,y],[2,n===0?null:y/n],[3,y===null?null:n*y]]){if(expected===null)assert.equal(cells[j],'–');else{assert.ok(Math.abs(parse(cells[j])-expected)<=.005000001);assert.equal(cells[j].startsWith('≈'),Math.abs(Math.round(expected*100)/100-expected)>1e-9);}}}
  const expectedKind=key==='b'?'inverse':key==='a'||p===0?'direct':'neither';for(const b of zone.querySelectorAll('[data-assignment-verdict]')){b.click();assert.equal(verdict.textContent.startsWith('Richtig:'),b.dataset.assignmentVerdict===expectedKind);assert.ok(verdict.textContent.length>70);decisions++;}states++;
 }
 assert.equal(states,63);assert.equal(decisions,189);for(const control of [slider,model,parameter]){assert.equal(control.labels.length,1);assert.equal(d.getElementById(control.getAttribute('aria-describedby')),out);}
 w.topicInit();assert.equal(model.value,'c');assert.equal(parameter.value,'10');assert.equal(slider.value,'6');zone.querySelector('[data-assignment-reset]').click();assert.equal(model.value,'a');assert.equal(parameter.value,'3');assert.equal(slider.value,'2');assert.equal(d.activeElement,model);assert.equal(verdict.textContent,'');assert.equal(JSON.stringify(w.localStorage),stored);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,15);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(answers).sort());let paths=0;
 for(const[i,q]of qs.entries()){assert.equal(q.sectionIndex,sections.findIndex(s=>s.includes(q.id)));for(let a=0;a<3;a++){qs.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?a:answers[item.id])+'"]').checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,a===answers[q.id]?100:93);assert.equal(r.contentRevision,2);assert.deepEqual(r.reviewQuestionIds,a===answers[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));paths++;}}
 assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pd.getElementById('ws-math-material');assert.equal(material.querySelectorAll('article').length,5);assert.equal(material.querySelectorAll('[data-assignment-task]>li').length,15);assert.equal(material.querySelectorAll('svg[data-worksheet-static]').length,3);assert.equal(material.querySelectorAll('[data-assignment-paper] tbody tr').length,8);assert.equal(material.querySelectorAll('input,button,select,[role=status]').length,0);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,15);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,5);assert.ok(material.textContent.includes('Vergleiche A und C bei x = 0, 2 und 5'));assert.equal(pd.getElementById('ws-print').disabled,false);
 function generated(tasks,solutions){assert.equal(tasks.length,8);assert.equal(solutions.length,8);for(let i=0;i<8;i++){const t=tasks[i].dataset,s=solutions[i].dataset,n=Number(t.x),fixed=Number(t.fixed),unit=Number(t.unit),answer=Number(s.assignmentAnswer);assert.equal(s.kind,t.kind);assert.equal(t.kind,['direct','inverse','neither'][i%3]);if(t.kind==='inverse'){assert.ok(Math.abs(n*answer-fixed)<1e-9);assert.ok(solutions[i].textContent.includes('Personenstunden'));}else assert.equal(answer,unit*n+fixed);assert.ok(solutions[i].textContent.includes(new Intl.NumberFormat('de-AT').format(answer)));assert.equal(solutions[i].querySelector('h3').textContent,'Zusatzübung A'+(i+1));}}
 const tasks=pd.querySelectorAll('[data-assignment-generated]');generated(tasks,pd.querySelectorAll('#ws-solutions [data-assignment-answer]'));assert.equal(pd.querySelectorAll('template[data-generated-worksheet-solutions]').length,0);assert.equal(pd.getElementById('ws-solutions').hidden,true);const originalDraw=Array.from(tasks,e=>e.textContent),toggle=pd.getElementById('ws-include-solutions');for(const checked of [true,false,true]){toggle.checked=checked;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,!checked);assert.deepEqual(Array.from(tasks,e=>e.textContent),originalDraw);}
 for(const seed of [0,.5,.999999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);generated(host.querySelectorAll('[data-assignment-generated]'),host.querySelector('template').content.querySelectorAll('[data-assignment-answer]'));}paper.window.close();
 console.log(`PASS: assignment representations: ${paths} independently keyed quiz paths and revision; ${states} parameter/selection states with values, points, table invariants, rounding, zero and domain; ${decisions} classifications; input/reset/focus/no storage; three paper figures/eight cases and 32 generated task/solution pairs.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
