'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),data=JSON.parse(read('lang/de.json')),id='math1_2_nat_zahlen';
const keys={m12_ziffer_zahl:0,natural_place_zero:0,natural_numberline:0,natural_estimate:0,roman_read_pairs:1,roman_year:2,roman_clock:0,roman_place_value:2,roman_compare:1,roman_zero:0,m12_check_place:0,m12_check_build:0};
const expected=[1,4,6,9,12,14,19,24,39,40,44,49,58,90,94,99,400,444,900,944,1492,1848,1988,1999,2026,3999,4];
function independentlyRead(roman){const v={I:1,V:5,X:10,L:50,C:100,D:500,M:1000};return [...roman].reduce((s,c,i)=>s+(v[c]<(v[roman[i+1]]||0)?-v[c]:v[c]),0);}
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();w.topicInit();const q=s=>d.querySelector(s),saved=JSON.stringify(w.localStorage);
 assert.equal(q('#roman-case').options.length,27);assert.equal(q('#roman-case').value,'11');assert.equal(q('[data-roman-steps]').hidden,true);
 for(let i=0;i<expected.length;i++){
  const m=w.romanReadingModel(i);assert.equal(m.value,expected[i]);assert.equal(independentlyRead(m.roman),expected[i]);assert.equal(m.groups.map(g=>g.text).join(''),m.roman);
  for(const g of m.groups){assert.equal(independentlyRead(g.text),g.value);assert.equal(Function('return '+g.calculation.replace('−','-'))(),g.value);}
  q('#roman-case').value=String(i);q('#roman-case').dispatchEvent(new w.Event('change'));assert.equal(q('#roman-answer').value,'');assert.equal(q('[data-roman-steps]').hidden,true);assert.equal(q('[data-roman-steps]').textContent,'');
  q('#roman-answer').value=String(expected[i]);q('#roman-answer').focus();q('#roman-answer').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.match(q('#roman-status').textContent,/^Richtig:/);assert.equal(d.activeElement,q('#roman-answer'));
  q('[data-roman-show]').click();assert.equal(q('[data-roman-steps]').hidden,false);assert.equal(d.querySelectorAll('[data-roman-steps] tbody tr').length,m.groups.length);assert.ok(q('[data-roman-steps]').textContent.includes('= '+expected[i]));
 }
 assert.match(q('[data-roman-question]').textContent,/Zifferblatt/);assert.match(q('[data-roman-steps]').textContent,/Zifferblättern/);
 for(const bad of [-1,27,1.1,NaN,'1'])assert.equal(w.romanReadingModel(bad),null);
 q('[data-roman-reset]').click();assert.equal(q('#roman-case').value,'11');assert.equal(d.activeElement,q('#roman-case'));assert.equal(q('[data-roman-steps]').hidden,true);
 for(const raw of ['', '0','-4','4.0','4,0','4e1','0x31','4000','10000','49a']){q('#roman-answer').value=raw;q('[data-roman-check]').click();assert.match(q('#roman-status').textContent,/^Gib eine ganze Zahl/);}
 q('#roman-answer').value='61';q('[data-roman-check]').click();assert.match(q('#roman-status').textContent,/^Noch nicht/);q('#roman-answer').dispatchEvent(new w.Event('input'));assert.equal(q('#roman-status').textContent,'');q('#roman-answer').value=' 0049 ';q('[data-roman-check]').click();assert.match(q('#roman-status').textContent,/^Richtig/);assert.equal(JSON.stringify(w.localStorage),saved);
 assert.equal(data[id].sections.length,5);assert.equal(d.querySelectorAll('[data-roman-tasks]>li').length,6);assert.equal(d.querySelectorAll('.roman-clock text').length,12);assert.equal(d.querySelectorAll('.roman-clock text')[4].textContent,'IIII');
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,12);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;
 for(const [i,item]of qs.entries())for(let a=0;a<item.answers.length;a++){
  assert.equal(item.answers[a].correct,a===keys[item.id]);const original=[...data[id].sections.flatMap(s=>s.quizzes),...data[id].diplom.questions].find(q=>q.id===item.id);assert.equal(original.answers[a].pts,a===keys[item.id]?10:0);
  if(item.id.startsWith('roman_'))assert.equal(item.sectionIndex,['roman_read_pairs','roman_year','roman_clock'].includes(item.id)?3:4);
  qs.forEach((item,j)=>q('input[name="chapter_q_'+j+'"][value="'+(j===i?a:keys[item.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[item.id]?100:92);assert.deepEqual(result.reviewQuestionIds,a===keys[item.id]?[]:[item.id]);assert.equal(result.contentRevision,3);assert.ok(q('#chapter-quiz-result').textContent.includes(item.answers[a].feedback));paths++;
 }
 assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:2}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 assert.equal(pd.querySelectorAll('#ws-math-material article').length,5);assert.equal(pd.querySelectorAll('#ws-math-material input,#ws-math-material button,#ws-math-material select').length,0);assert.equal(pd.querySelectorAll('[data-natural-paper],[data-roman-paper]').length,2);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,4);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,12);assert.equal(pd.querySelectorAll('.roman-clock').length,1);assert.equal(pd.querySelectorAll('[data-roman-tasks]>li').length,6);assert.equal(pd.querySelectorAll('[data-natural-number-task]>li,[data-estimation-task]>li').length,7);assert.ok(!pd.querySelector('#ws-math-material').textContent.includes('Freiwillige Vertiefung'));
 function verify(host,solution){const tasks=host.querySelectorAll('[data-natural-generated]'),answers=solution.querySelectorAll('[data-natural-answer]');assert.equal(tasks.length,12);assert.equal(answers.length,12);for(let i=0;i<12;i++){const t=tasks[i],kind=t.dataset.naturalGenerated,a=Number(t.dataset.first),b=Number(t.dataset.second);let result;if(kind==='roman'){result=independentlyRead(t.dataset.second);assert.equal(result,a);assert.ok(t.textContent.includes(t.dataset.second));}else if(kind==='round')result=Math.round(a/b)*b;else if(kind==='compare')result=a<b?'<':a>b?'>':'=';else if(kind==='add')result=a+b;else{assert.equal(kind,'subtract');result=a-b;assert.ok(result>=0);}assert.equal(answers[i].dataset.naturalAnswer,String(result));assert.ok(answers[i].textContent.startsWith('A'+(i+1)+'.'));}}
 verify(pd,pd.getElementById('ws-solutions'));for(const seed of [0,.5,.99999]){pw.Math.random=()=>seed;const host=pd.createElement('div');host.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify(host,host.querySelector('template').content);}
 const before=Array.from(pd.querySelectorAll('[data-natural-generated]'),e=>e.textContent),toggle=pd.getElementById('ws-include-solutions');for(const checked of [true,false,true]){toggle.checked=checked;toggle.dispatchEvent(new pw.Event('change'));assert.deepEqual(Array.from(pd.querySelectorAll('[data-natural-generated]'),e=>e.textContent),before);}paper.window.close();
 console.log('PASS: Roman numerals: 27 independent readings and decompositions, all '+paths+' chapter answer paths, validation/Enter/reset/storage/revision; five-section worksheet, two paper alternatives, four solution blocks, 48 matched generated tasks.');
})().catch(e=>{console.error(e);process.exitCode=1;});
