const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='bio_1_haustiere';
// Independent expected decisions, not inferred from the authored correct flags.
const correct={bio_haustiere_s1:1,bio_haustiere_s2:2,bio_haustiere_s3:0,bio_haustiere_s4:2,bio_haustiere_s5:1,bio_haustiere_d1:2,bio_haustiere_d2:1,bio_haustiere_d3:0,bio_haustiere_d4:1,bio_haustiere_d5:2,bio_haustiere_d6:1,bio_haustiere_d7:0};
const sections={bio_haustiere_d1:2,bio_haustiere_d2:1,bio_haustiere_d3:0,bio_haustiere_d4:2,bio_haustiere_d5:3,bio_haustiere_d6:1,bio_haustiere_d7:4};
const kinds={sofa:'observation',visitors:'interpretation',space:'decision',photo:'observation',alone:'interpretation',postpone:'decision'};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')),texts=d=>[...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent);assert.equal(texts(d).length,15);assert.deepEqual(texts(d),texts(authored.window.document));assert.equal(d.querySelectorAll('.bio-training-direct-text').length,0);authored.window.close();
 const zone=d.querySelector('[data-core-experiment="pet-evidence"]'),rows=[...zone.querySelectorAll('[data-pet-statement]')],out=zone.querySelector('[data-pet-result]'),check=zone.querySelector('[data-pet-check]'),reset=zone.querySelector('[data-pet-reset]');assert.equal(rows.length,6);
 const before=JSON.stringify(w.localStorage);check.click();assert.match(out.textContent,/0 von 6.*6 noch offen/);assert.equal(zone.querySelectorAll('[data-pet-state="open"]').length,6);let classificationPaths=0;
 for(const row of rows){
  const select=row.querySelector('select'),feedback=row.querySelector('[data-pet-feedback]');assert.equal(d.getElementById(select.getAttribute('aria-describedby')),feedback);assert.ok(select.getAttribute('aria-label').includes(row.querySelector('p').textContent));
  for(const category of ['observation','interpretation','decision']){
   select.value=category;select.dispatchEvent(new w.Event('change'));assert.equal(feedback.textContent,'');assert.match(out.textContent,/erneut/);check.click();assert.equal(row.dataset.petState,category===kinds[row.dataset.petStatement]?'correct':'review');assert.match(feedback.textContent,category===kinds[row.dataset.petStatement]?/^Passend: .+/:/^Prüfe noch einmal: .+/);classificationPaths++;
  }
 }
 rows.forEach(row=>row.querySelector('select').value=kinds[row.dataset.petStatement]);check.click();assert.match(out.textContent,/6 von 6.*0 noch offen/);assert.equal(JSON.stringify(w.localStorage),before);w.enhanceCoreLearning(data[id],id,'de');assert.match(out.textContent,/6 von 6/);reset.click();assert.ok(rows.every(row=>row.querySelector('select').value===''&&!row.dataset.petState&&!row.querySelector('[data-pet-feedback]').textContent));assert.equal(d.activeElement,rows[0].querySelector('select'));assert.equal(out.textContent,'Noch nicht geprüft.');
 const cases=d.querySelector('[data-pet-cases]');assert.equal(cases.closest('[data-chapter-section]').dataset.chapterSection,'1');assert.equal(cases.querySelectorAll('[data-pet-case]').length,3);assert.ok(cases.textContent.includes('erfundene'));assert.equal(d.querySelectorAll('[data-pet-plan-protocol] tbody tr').length,7);assert.equal(d.querySelectorAll('[data-pet-observation-protocol] tbody tr').length,7);assert.equal(d.querySelectorAll('[data-pet-case-protocol] tbody tr').length,3);
 const questions=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(questions,q=>q.id).sort(),Object.keys(correct).sort());assert.equal(data[id].diplom.questions.length,0);let paths=0;
 for(const [i,q]of questions.entries()){
  assert.equal(q.sectionIndex,q.id in sections?sections[q.id]:Number(q.id.at(-1))-1);
  for(let choice=0;choice<3;choice++){
   questions.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?choice:correct[item.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,choice===correct[q.id]?100:92);assert.deepEqual(result.reviewQuestionIds,choice===correct[q.id]?[]:[q.id]);assert.equal(result.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;
  }
 }
 assert.equal(paths,36);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).passed,true);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pw.document.getElementById('ws-biology-material'),solutions=pw.document.getElementById('ws-solutions');assert.equal(material.querySelectorAll('article').length,5);assert.equal(material.querySelectorAll('.bio-training-card').length,15);assert.equal(material.querySelectorAll('[data-pet-evidence-paper] > li').length,6);assert.equal(material.querySelectorAll('[data-pet-case]').length,3);assert.equal(material.querySelectorAll('[data-pet-plan-protocol] tbody tr').length,7);assert.equal(material.querySelectorAll('[data-pet-observation-protocol] tbody tr').length,7);assert.equal(material.querySelectorAll('[data-pet-case-protocol] tbody tr').length,3);assert.equal(material.querySelectorAll('select,button,[data-pet-feedback]').length,0);assert.equal(solutions.hidden,true);assert.ok(solutions.textContent.includes('Zuordnungen und Begründungen vergleichen'));assert.ok(solutions.textContent.includes('Das ist die beschriebene, zeitlich begrenzte Beobachtung'));assert.ok(!material.textContent.includes('Das ist die beschriebene, zeitlich begrenzte Beobachtung'));paper.window.close();
 console.log('PASS: pet welfare: 36 independently keyed assessed paths, section review/revision 2, 15 preserved tasks, 18 classification paths, empty/change/reset/re-init/storage/focus, three cases and 17 protocol rows, paper tasks and separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
