const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb6_kommunikation',keys=require('./fixtures/dgb6_communication_keys.json');
const cases={channels:[{key:1,reason:/vereinbarte Kanal/},{key:0,reason:/Zeitversetzte schriftliche/}],business:[{key:2,reason:/Geld fließt.*Namensverkauf/},{key:1,reason:/Beobachtung und Schlussfolgerung/}],framing:[{key:0,reason:/12\/24 = 1\/2/},{key:2,reason:/Meinungsbildung und Beteiligung/}]};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();const stored=JSON.stringify(w.localStorage);
 let decisions=0;for(const [name,expected]of Object.entries(cases)){
  const zone=d.querySelector('[data-communication-lab="'+name+'"]'),select=zone.querySelector('select'),cards=[...zone.querySelectorAll('[data-boundary-case]')],status=zone.querySelector('[role=status]');assert.equal(cards.length,2);assert.equal(d.getElementById(select.getAttribute('aria-describedby')),status);
  for(const [n,e]of expected.entries()){select.value=String(n);select.dispatchEvent(new w.Event('change'));assert.equal(cards.filter(c=>!c.hidden).length,1);assert.equal(cards[n].hidden,false);assert.match(status.textContent,/Lies den Fall/);for(let a=0;a<3;a++){const b=cards[n].querySelectorAll('button')[a];b.focus();b.click();assert.equal(d.activeElement,b);assert.equal(status.textContent.startsWith('Richtig:'),a===e.key);if(a===e.key)assert.match(status.textContent,e.reason);assert.equal(b.getAttribute('aria-describedby'),status.id);decisions++;}}
  zone.querySelector('[data-boundary-reset]').click();assert.equal(select.value,'0');assert.equal(d.activeElement,select);assert.match(status.textContent,/Lies den Fall/);
 }
 assert.equal(decisions,18);assert.equal(JSON.stringify(w.localStorage),stored);const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);
 assert.equal(d.querySelectorAll('[data-communication-tasks]>li').length,16);assert.equal(d.querySelectorAll('[data-packet-tasks]>li,[data-phishing-tasks]>li,[data-source-tasks]>li').length,14);
 assert.equal(d.querySelectorAll('[data-channel-comparison] tbody tr').length,4);const paths=[...d.querySelectorAll('[data-communication-route] figure p')].map(p=>p.textContent.split(' → '));assert.equal(paths.length,2);for(const p of paths){assert.equal(p.length,5);assert.equal(p[4],'Zielserver');assert.match(p[1],/Schulrouter/);assert.match(p[3],/Zielrouter/);}assert.notEqual(paths[0][2],paths[1][2]);
 const practices=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practices.map(q=>q.id),['dgb6_kommunikation_p3','dgb6_kommunikation_p2','dgb6_kommunikation_p1']);assert.deepEqual(practices.map(q=>q.answers.findIndex(a=>a.correct)),[0,1,2]);assert.ok(practices.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));
 const questions=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(questions,q=>q.id),Object.keys(keys));assert.deepEqual(Array.from(questions,q=>q.sectionIndex),[0,0,1,1,1,2,3,3,3,3]);
 for(const [n,q]of questions.entries())for(let a=0;a<3;a++){
  questions.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===n?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:90);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));
 }
 assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).outdated,true);assert.equal(w.currentChapterResult(id,{contentRevision:2,passed:true,bestPercent:100}).passed,true);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pw.document.getElementById('ws-dgb-material'),solutions=pw.document.getElementById('ws-solutions');
 assert.equal(material.querySelectorAll('[data-communication-paper] .ai-paper-case').length,6);assert.equal(material.querySelectorAll('[data-communication-tasks]>li').length,16);assert.equal(material.querySelectorAll('[data-communication-route] figure p').length,2);assert.equal(material.querySelectorAll('button,select,input,template,details,[data-communication-solution]').length,0);assert.equal(solutions.querySelectorAll('[data-communication-solution]').length,4);assert.equal(solutions.hidden,true);assert.ok(solutions.textContent.includes('12 + 8 + 4 = 24'));assert.equal(12/(12+8+4),.5);assert.equal(Math.max(12,8,4),12);
 paper.window.close();console.log('PASS: 18 independently keyed communication decisions, 30 assessed answer paths, revised free exercises, routes, 30 tasks, paper cases and separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
