const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='bio_2_pflanzenvermehrung';
const correct=Object.fromEntries(['s1','s2','s3','s4','s5','d1','d2','d3','d4','d5'].map(k=>['bio_2_pflanzenvermehrung_'+k,0]));Object.assign(correct,{bio_vermehrung_einzelbluete:2,bio_vermehrung_tageszahlen:1});
const sections=Object.fromEntries(Object.entries({s1:0,s2:1,s3:2,s4:3,s5:4,d1:0,d2:1,d3:1,d4:2,d5:4}).map(([k,v])=>['bio_2_pflanzenvermehrung_'+k,v]));Object.assign(sections,{bio_vermehrung_einzelbluete:0,bio_vermehrung_tageszahlen:4});
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/bio_2_pflanzenvermehrung'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')),texts=doc=>[...doc.querySelectorAll('.bio-training-card')].map(e=>e.textContent);assert.equal(texts(d).length,15);assert.deepEqual(texts(d),texts(authored.window.document));authored.window.close();
 const saved=JSON.stringify(w.localStorage),flower=d.querySelector('[data-flower-organization]'),control=flower.querySelector('select');
 for(const [kind,expected]of Object.entries({both:[['S + F','S + F']],mono:[['S','F']],dio:[['S','S'],['F','F']]})){
  control.value=kind;control.dispatchEvent(new w.Event('change'));assert.equal(flower.querySelectorAll('[data-flower-view]:not([hidden])').length,1);const view=flower.querySelector('[data-flower-view="'+kind+'"]');assert.equal(view.hidden,false);assert.deepEqual([...view.querySelectorAll('[data-layout-plant]')].map(p=>[...p.querySelectorAll('[data-layout-flower]')].map(e=>e.dataset.layoutFlower)),expected);
 }
 w.topicInit();assert.equal(control.value,'dio');flower.querySelector('button').click();assert.equal(control.value,'both');assert.equal(d.activeElement,control);
 const timeline=d.querySelector('[data-germination-timeline]'),day=timeline.querySelector('select'),result=timeline.querySelector('[role=status]'),counts=[0,2,6,7,8],increments=[null,2,4,1,1];
 assert.deepEqual([...d.querySelectorAll('[data-germination-data] tbody tr')].map(r=>[...r.querySelectorAll('td')].map(t=>Number(t.textContent))),counts.map(n=>[0,n]));
 for(let i=0;i<5;i++){day.value=String(i);day.dispatchEvent(new w.Event('change'));assert.ok(result.textContent.includes('B '+counts[i]+' von 10 = '+counts[i]*10+' %'));if(i)assert.ok(result.textContent.includes('B '+increments[i]+' Samen'));else assert.match(result.textContent,/frühere Zählung liegt nicht vor/);assert.equal(Number(timeline.querySelector('[data-germination-marker]').getAttribute('x1')),42+72*i);}
 for(const key of ['a','b']){const pts=timeline.querySelector('[data-germination-line="'+key+'"]').getAttribute('points').split(' ').map(s=>s.split(',').map(Number));assert.deepEqual(pts,(key==='a'?[0,0,0,0,0]:counts).map((n,i)=>[42+72*i,220-17*n]));}
 timeline.querySelector('button').click();assert.equal(day.value,'0');assert.equal(d.activeElement,day);w.topicInit();assert.equal(timeline.querySelectorAll('[data-germination-marker]').length,1);
 const selects=[...d.querySelectorAll('[data-reproduction-item]')],answers=['pollination','fertilization','development','dispersal','germination'],check=d.querySelector('[data-reproduction-check]');let assignments=0;
 check.click();assert.match(d.querySelector('[data-reproduction-status]').textContent,/5 noch nicht/);
 for(let i=0;i<5;i++)for(const choice of answers){selects.forEach((s,j)=>{s.value=j===i?choice:answers[j];s.dispatchEvent(new w.Event('change'));});check.click();assert.equal(selects[i].getAttribute('aria-invalid'),String(choice!==answers[i]));assert.match(d.querySelector('[data-reproduction-status]').textContent,new RegExp((choice===answers[i]?5:4)+' von 5'));assignments++;}
 d.querySelector('[data-reproduction-reset]').click();assert.equal(d.activeElement,selects[0]);assert.equal(JSON.stringify(w.localStorage),saved);assert.equal(assignments,25);
 const questions=w.currentChapterQuiz.questions;assert.equal(questions.length,12);assert.deepEqual(Array.from(questions,q=>q.id).sort(),Object.keys(correct).sort());let paths=0;
 for(const [i,q]of questions.entries()){assert.equal(q.sectionIndex,sections[q.id]);for(let choice=0;choice<3;choice++){
  questions.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(j===i?choice:correct[item.id])+'"]').checked=true);w.submitChapterQuiz();const stored=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(stored.lastPercent,choice===correct[q.id]?100:92);assert.deepEqual(stored.reviewQuestionIds,choice===correct[q.id]?[]:[q.id]);assert.equal(stored.contentRevision,2);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[choice].feedback));paths++;
 }}
 assert.equal(paths,36);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true,bestPercent:100}).passed,false);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const m=pw.document.getElementById('ws-biology-material'),s=pw.document.getElementById('ws-solutions');assert.equal(m.querySelectorAll('article').length,5);assert.equal(m.querySelectorAll('.bio-training-card').length,15);assert.equal(m.querySelectorAll('[data-germination-protocol] tbody tr').length,6);assert.equal(m.querySelectorAll('[data-germination-data] tbody tr').length,5);assert.equal(m.querySelectorAll('[data-reproduction-paper] li').length,5);assert.equal(m.querySelectorAll('svg[data-worksheet-static]').length,4);assert.equal(m.querySelectorAll('select,button,input,[data-flower-view]').length,0);assert.equal(s.querySelectorAll('.ws-paper-solution').length,3);assert.equal(s.hidden,true);assert.match(s.textContent,/0 von 10 = 0 %/);assert.match(s.textContent,/8 von 10 = 80 %/);assert.ok(!m.textContent.includes('0 + 2 + 6 + 7 + 8 = 23'));paper.window.close();
 console.log('PASS: reproduction learning: 36 independently keyed paths, section/revision, 15 preserved tasks, three flower distributions, five germination counts/deltas/percentages and plot coordinates, 25 term assignments, reset/focus/no storage, four paper diagrams, experiment protocol/data, five paper assignments and three separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
