const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),de=JSON.parse(read('lang/de.json')),en=JSON.parse(read('lang/en.json'));
(async()=>{const id='kunst_4_gebaeude_umnutzen',dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
await new Promise(r=>setImmediate(r));w.localStorage.setItem('physik_lang','en');w.fetch=async url=>({ok:true,json:async()=>url.includes('/de.json')?de:en});w.HTMLElement.prototype.scrollIntoView=()=>{};
for(const f of ['curriculum','chapter-revisions','common','core-learning','language-workshop','art-workshop','renderer'])w.eval(read('js/'+f+'.js'));w.eval('globalPhysikScore=0');await w.renderTopic();
assert.equal(d.querySelector('[data-content-language-notice]'),null);assert.equal(d.getElementById('sections-container').lang,'en');assert.equal(en[id].sourceRevision,w.chapterRevision(id));assert.equal(w.currentChapterQuiz.questions.length,6);
for(let i=0;i<de[id].sections.length;i++){const a=de[id].sections[i],b=en[id].sections[i];assert.equal(a.id,b.id);assert.equal(a.quizzes.length,b.quizzes.length);a.quizzes.forEach((q,j)=>{assert.equal(q.id,b.quizzes[j].id);assert.deepEqual(q.answers.map(a=>a.correct),b.quizzes[j].answers.map(a=>a.correct));});}
assert.equal(en[id].sources[0].url,de[id].sources[0].url);assert.equal(d.querySelectorAll('table tbody tr').length,5);assert.ok(d.querySelector('a[href*="2001/07/05"]'));assert.deepEqual(en[id].prerequisites,de[id].prerequisites);
const workshop=d.querySelector('[data-language-workshop]');[...workshop.querySelectorAll('select')].forEach((select,i)=>select.value=en[id].workshop.items[i].answer);[...workshop.querySelectorAll('button')].find(b=>b.textContent==='Check matches').click();assert.match(workshop.textContent,/3 of 3/);assert.match(workshop.textContent,/Evidence or next step/);
assert.doesNotMatch(d.getElementById('sections-container').textContent,/Werkkarte|Zuordnung|Entwurf|Beschriftung|Beobachtung|Gestalten/);
for(const answer of [0,1,2]){w.startChapterQuiz();w.currentChapterQuiz.questions.forEach((q,i)=>{d.querySelector('input[name="chapter_q_'+i+'"][value="'+answer+'"]').checked=true;});w.submitChapterQuiz();const result=d.getElementById('chapter-quiz-result');assert.equal(result.querySelectorAll('li').length,6);assert.equal(w.getChapterQuizResult(id).lastPercent,answer===0?100:0);w.currentChapterQuiz.questions.forEach(q=>assert.ok(result.textContent.includes(q.answers[answer].feedback)));}
dom.window.close();console.log('PASS: current English building reuse chapter, equivalent six questions and all 18 feedback paths, English workshop and reflection labels, preserved historical source, five user groups and prerequisite links.');})().catch(e=>{console.error(e);process.exitCode=1;});
