const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb5_produktion',keys=require('./fixtures/dgb5_production_keys.json');
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/dgb5_produktion.js'));w.topicInit();w.topicInit();
 const stored=JSON.stringify(w.localStorage),lab=d.querySelector('[data-production-views]'),control=lab.querySelector('select'),views=[...lab.querySelectorAll('[data-production-view]')];
 for(const value of ['text','table','chart','table','text']){control.value=value;control.dispatchEvent(new w.Event('change'));assert.deepEqual(views.filter(e=>!e.hidden).map(e=>e.dataset.productionView),[value]);assert.match(lab.querySelector('[role=status]').textContent,/acht erfundene Antworten, Lesen 3, Radfahren 4, Ballspiel 1/);}
 lab.querySelector('[data-production-view-reset]').click();assert.equal(control.value,'text');assert.equal(d.activeElement,control);assert.equal(JSON.stringify(w.localStorage),stored);
 assert.deepEqual([...lab.querySelectorAll('[data-media-counts] tbody tr')].map(r=>[r.cells[0].textContent,r.cells[1].textContent]),[['Lesen','3'],['Radfahren','4'],['Ballspiel','1']]);assert.match(views[0].textContent,/drei auf Lesen, vier auf Radfahren und eine auf Ballspiel/);
 assert.deepEqual([...lab.querySelectorAll('[data-chart-value]')].map(e=>[e.dataset.chartValue,e.querySelector('.production-bar-fill').style.width]),[['3','75%'],['4','100%'],['1','25%']]);assert.deepEqual([...lab.querySelectorAll('.production-chart-scale span')].map(e=>e.textContent),['0','1','2','3','4']);assert.ok(views.every(e=>e.textContent.includes('Keine Aussage über alle Kinder in Wien')));
 assert.deepEqual(data[id].sections.map(s=>s.id),['sec1','sec_loop','sec3','sec2','sec4']);assert.equal(d.querySelectorAll('[data-production-tasks]>li').length,19);assert.equal(d.querySelectorAll('[data-survey-tasks]>li').length,6);assert.equal(d.querySelectorAll('[data-loop-tasks]>li').length,4);assert.equal(d.querySelectorAll('[data-slide-plan]>article').length,3);assert.equal(d.querySelectorAll('[data-presentation-protocol] tbody tr').length,5);const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);
 const qs=w.currentChapterQuiz.questions;assert.deepEqual(Array.from(qs,q=>q.id),Object.keys(keys));assert.deepEqual(Array.from(qs,q=>q.sectionIndex),[0,0,1,2,2,3,3,4,4]);let answers=0;
 for(const [i,q]of qs.entries())for(let a=0;a<3;a++){qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?a:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:89);assert.equal(result.contentRevision,4);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));answers++;}
 assert.equal(w.currentChapterResult(id,{contentRevision:3,passed:true,bestPercent:100}).outdated,true);const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[2,2,1]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-media-paper] .production-medium').length,3);assert.equal(material.querySelectorAll('[data-media-paper] [data-chart-value]').length,3);assert.equal(material.querySelectorAll('[data-production-tasks]>li').length,19);assert.equal(material.querySelectorAll('[data-survey-tasks]>li').length,6);assert.equal(material.querySelectorAll('[data-loop-tasks]>li').length,4);assert.equal(material.querySelectorAll('[data-slide-plan]>article').length,3);assert.equal(material.querySelectorAll('button,input,select,details').length,0);assert.equal(pd.querySelectorAll('#ws-solutions .ws-paper-solution').length,5);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,9);paper.window.close();
 assert.equal(answers,27);console.log('PASS: three equal-data representations, independent counts and bar scale, reset/focus/no storage changes, 27 quiz paths, reordered review routes, 29 tasks, three-slide plan and five separate paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
