const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('../../qa/node_modules/jsdom'));}
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),de=JSON.parse(read('lang/de.json'));
(async()=>{
 const check=new JSDOM('<body></body>',{url:'https://example.test/',runScripts:'outside-only'}),v=check.window;await new Promise(r=>setImmediate(r));for(const name of ['curriculum','chapter-revisions','renderer','chapter-title-index'])v.eval(read('js/'+name+'.js'));
 const ids=Object.values(v.SCIVERSE_CURRICULUM).flatMap(s=>s.topics.filter(t=>t.available!==false).map(t=>t.id));
 for(const language of ['en','ar','sr','tr','uk']){const data=JSON.parse(read('lang/'+language+'.json'));for(const id of ids){const selected=v.selectCurrentTopic(id,data[id],de[id],language),entry=v.SCIVERSE_TRANSLATED_TITLES[language][id];if(!selected||selected.languageFallback||selected.contentLanguage==='de'){assert.equal(entry,undefined,language+' '+id);continue;}assert.ok(entry,'Rebuild title index: '+language+' '+id);assert.equal(entry.revision,v.chapterRevision(id));const node=v.document.createElement('div');node.innerHTML=selected.title;assert.equal(entry.title,node.textContent.trim());node.innerHTML=selected.subtitle||'';assert.equal(entry.subtitle,node.textContent.trim());const expectedGoals=(selected.learningGoals||[]).map(value=>{node.innerHTML=value;return node.textContent.trim();});assert.equal(JSON.stringify(entry.learningGoals),JSON.stringify(expectedGoals));}}
 check.window.close();
 for(const language of ['en','ar','sr','tr','uk']){
 const dom=new JSDOM(read('topics/learning.html'),{url:'https://example.test/site/topics/learning.html',runScripts:'outside-only'}),w=dom.window,d=w.document;w.localStorage.setItem('physik_lang',language);w.fetch=async()=>({ok:true,json:async()=>de});for(const name of ['curriculum','chapter-revisions','chapter-title-index','learning'])w.eval(read('js/'+name+'.js'));await new Promise(r=>setImmediate(r));
 const subject=d.getElementById('subject'),search=d.getElementById('search');subject.value='kunst';search.value=w.SCIVERSE_TRANSLATED_TITLES[language].kunst_1_museum.title;search.dispatchEvent(new w.Event('input'));
 const card=d.querySelector('[data-focus-key="catalog-open-kunst_1_museum"]').closest('article'),line=card.querySelector('.original-chapter-title');assert.ok(line);assert.equal(line.lang,'de');assert.equal(line.dir,'ltr');assert.ok(line.textContent.includes(de.kunst_1_museum.title));const heading=card.querySelector('h2');assert.equal(heading.lang,language);assert.equal(heading.dir,language==='ar'?'rtl':'ltr');assert.equal(heading.textContent,search.value);assert.equal(d.querySelectorAll('#selected>li').length,0);const metadata=w.SCIVERSE_TRANSLATED_TITLES[language].kunst_1_museum;assert.equal(card.querySelector('[data-chapter-subtitle]').textContent,metadata.subtitle);assert.equal(card.querySelector('[data-chapter-goals]').lang,language);assert.equal(card.querySelector('[data-chapter-goals]').dir,language==='ar'?'rtl':'ltr');assert.deepEqual([...card.querySelectorAll('[data-chapter-goals] li')].map(el=>el.textContent),Array.from(metadata.learningGoals));d.querySelector('[data-focus-key="catalog-toggle-kunst_1_museum"]').click();assert.equal(d.querySelector('#selected>li>strong').textContent,metadata.title);assert.equal(d.querySelector('#selected>li>strong').lang,language);assert.equal(d.querySelector('.plan-chapter-link bdi').lang,language);assert.equal(d.querySelector('[data-plan-goals]').lang,language);assert.ok(d.querySelector('[data-plan-goals]').textContent.includes(metadata.learningGoals[0]));
 w.dispatchEvent(new w.MessageEvent('message',{origin:'https://untrusted.test',data:{type:'languageChange',lang:'de'}}));assert.ok(d.querySelector('.original-chapter-title'));
 w.dispatchEvent(new w.MessageEvent('message',{origin:w.location.origin,data:{type:'languageChange',lang:'de'}}));assert.equal(d.querySelector('.original-chapter-title'),null);assert.equal(d.querySelector('[data-plan-goals]').lang,'de');assert.ok(d.querySelector('[data-plan-goals]').textContent.includes(de.kunst_1_museum.learningGoals[0]));assert.ok(d.querySelector('[data-focus-key="catalog-open-kunst_1_museum"]'),'Translated query still finds chapter with German UI');
 search.value=de.kunst_1_museum.title;search.dispatchEvent(new w.Event('input'));assert.ok(d.querySelector('[data-focus-key="catalog-open-kunst_1_museum"]'),'German title remains searchable');w.SCIVERSE_CHAPTER_REVISIONS.kunst_1_museum++;w.dispatchEvent(new w.MessageEvent('message',{origin:w.location.origin,data:{type:'languageChange',lang:language}}));assert.equal(d.querySelector('.original-chapter-title'),null);assert.equal(d.querySelector('#selected>li>strong').textContent,de.kunst_1_museum.title);assert.equal(d.querySelector('#selected>li>strong').lang,'de');dom.window.close();
 }
 console.log('PASS: generated titles and metadata match actual renderer selection for every chapter/language; all five museum titles searchable with localized goals in cards and plans, localized labels/RTL, safe language changes, unchanged plans and stale-revision exclusion.');
})().catch(e=>{console.error(e);process.exitCode=1;});
