'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_siedlungsraeume';
const keys={bio_4_stadt_s1:[1,0],bio_4_stadt_d1:[2,0],bio_4_stadt_s2:[0,1],bio_4_stadt_messung:[2,1],bio_4_stadt_d2:[1,1],bio_4_stadt_speicher:[1,2],bio_4_stadt_plan:[0,2],bio_4_stadt_s3:[2,3],bio_4_stadt_d3:[1,3],bio_4_stadt_abfall:[0,3]};
// Independent water balances in litres: plan, rainfall, free capacity, retained, runoff.
const cases=[['A','10','20',0,4000],['A','10','5',0,4000],['A','30','20',0,12000],['A','30','5',0,12000],['A','50','20',0,20000],['A','50','5',0,20000],['B','10','20',1500,2500],['B','10','5',750,3250],['B','30','20',3000,9000],['B','30','5',750,11250],['B','50','20',3000,17000],['B','50','5',750,19250],['C','10','20',2500,1500],['C','10','5',1250,2750],['C','30','20',5000,7000],['C','30','5',1250,10750],['C','50','20',5000,15000],['C','50','5',1250,18750]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-city-lab]'),plan=zone.querySelector('[data-city-plan]'),rain=zone.querySelector('[data-city-rain]'),capacity=zone.querySelector('[data-city-capacity]'),check=zone.querySelector('[data-city-check]'),reset=zone.querySelector('[data-city-reset]'),result=zone.querySelector('[data-city-result]'),storage=JSON.stringify(w.localStorage);
 const set=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change'));assert.equal(result.textContent,'');assert.equal(result.dataset.invalid,undefined);};
 const value=key=>Number(result.querySelector(`[data-city-value="${key}"]`).textContent.replace(/[^\d]/g,''));
 for(const[p,r,c,held,runoff]of cases){set(plan,p);set(rain,r);set(capacity,c);check.click();assert.equal(value('retained'),held);assert.equal(value('runoff'),runoff);assert.equal(value('total'),held+runoff);assert.equal(value('total'),Number(r)*400);assert.equal(result.children.length,5);assert.equal(result.querySelector('[data-city-fit]').dataset.cityFit,p==='C'?'no':'yes');assert.equal(d.activeElement,result);assert.match(result.textContent,/keine Vorhersage einer Abflussspitze/);}
 for(const[input,name]of [[plan,'plan'],[rain,'rain'],[capacity,'capacity']]){reset.click();set(input,'');check.click();assert.equal(result.dataset.invalid,name);assert.equal(d.activeElement,input);}reset.click();assert.equal(plan.value,'A');assert.equal(rain.value,'10');assert.equal(capacity.value,'20');assert.equal(result.textContent,'');assert.equal(d.activeElement,plan);assert.equal(JSON.stringify(w.localStorage),storage);
 const maps=[...d.querySelectorAll('.city-plans svg')];assert.equal(maps.length,3);for(const[i,map]of maps.entries()){const labels=[...map.querySelectorAll('text')].map(e=>e.textContent);assert.equal(labels.length,16);assert.equal(labels.filter(x=>x==='W').length,4);assert.equal(labels.filter(x=>x==='B').length,[12,6,2][i]);assert.equal(labels.filter(x=>x==='G').length,[0,6,10][i]);}
 assert.deepEqual([...d.querySelectorAll('.city-temperatures tbody tr')].map(r=>[...r.children].map(e=>e.textContent)),[['1','48 °C','31 °C'],['2','50 °C','32 °C'],['3','49 °C','30 °C']]);assert.match(d.querySelector('[data-city-solution="1"]').textContent,/49 °C/);assert.match(d.querySelector('[data-city-solution="1"]').textContent,/18 °C/);assert.match(d.querySelector('[data-city-solution="3"]').textContent,/20 g je Mahlzeit/);assert.match(d.querySelector('[data-city-solution="3"]').textContent,/30 g je Mahlzeit/);
 const source=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...source.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('[data-city-solution]').length,4);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].id,'bio_4_siedlungsraeume_extra_gruen');assert.ok(practice[0].answers.every(a=>a.pts===0));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-city-paper]').length,1);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,3);assert.equal(pd.querySelectorAll('.city-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('#ws-solutions [data-city-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-city-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material select').length,0);assert.doesNotMatch(pd.body.textContent,/undefined/);for(const s of data[id].sources){assert.ok(s.title&&s.url.startsWith('https://'));assert.ok(pd.body.textContent.includes(s.title));}
 const solution=pd.querySelector('#ws-solutions [data-city-solution="2"]').textContent;for(const value of ['12.000 L','9.000 L','7.000 L','11.250 L','2.500 L','17.000 L'])assert.ok(solution.includes(value),value+' paper answer');paper.window.close();
 console.log('PASS: 18 independently calculated water balances, 3 true-area plans, invalid/reset/focus/storage, 30 quiz answers, 12 direct tasks and all paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
