const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb6_information',wait=()=>new Promise(r=>setImmediate(r));
const samples=[{name:'a',bytes:[65],text:'A',bits:['01000001']},{name:'aa',bytes:[65,65],text:'AA',bits:['01000001','01000001']},{name:'umlaut',bytes:[195,132],text:'Ä',bits:['11000011','10000100']}];
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/site/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await wait();w.TextDecoder=TextDecoder;w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();const stored=JSON.stringify(w.localStorage);
 const zone=d.querySelector('[data-core-experiment="byte-pattern"]'),buttons=[...zone.querySelectorAll('[data-byte-weight]')],pattern=zone.querySelector('[data-byte-pattern]'),out=zone.querySelector('[data-byte-result]');
 assert.deepEqual(buttons.map(b=>Number(b.dataset.byteWeight)),[128,64,32,16,8,4,2,1]);
 for(let value=0;value<256;value++){const expected=value.toString(2).padStart(8,'0');for(let i=0;i<8;i++){const on=expected[i]==='1';if((buttons[i].getAttribute('aria-pressed')==='true')!==on){buttons[i].focus();buttons[i].click();assert.equal(d.activeElement,buttons[i]);}assert.equal(buttons[i].querySelector('[data-byte-digit]').textContent,expected[i]);assert.equal(buttons[i].getAttribute('aria-describedby'),out.id);assert.equal(buttons[i].getAttribute('aria-label'),`Stellenwert ${128>>i}, Bit ${expected[i]}`);}assert.equal(pattern.textContent,expected);assert.ok(out.textContent.startsWith('Als vorzeichenlose Zahl: '+value+'.'));}
 zone.querySelector('[data-byte-reset]').click();assert.equal(pattern.textContent,'00000000');assert.equal(d.activeElement,buttons[0]);w.enhanceCoreLearning(data[id],id,'de');buttons[0].click();assert.equal(pattern.textContent,'10000000');zone.querySelector('[data-byte-reset]').click();
 const lab=d.querySelector('[data-core-experiment="file-bytes"]'),select=lab.querySelector('[data-file-choice]'),fetchButton=lab.querySelector('[data-file-fetch]'),result=lab.querySelector('[data-file-result]'),details=lab.querySelector('[data-file-details]'),reset=lab.querySelector('[data-file-reset]');
 const change=name=>{select.value='../examples/bytes-'+name+'.txt';select.dispatchEvent(new w.Event('change'));assert.equal(details.hidden,true);assert.equal(lab.querySelector('[data-file-text]').textContent,'');assert.equal(lab.querySelector('[data-file-bits]').children.length,0);};
 const response=bytes=>({ok:true,status:200,arrayBuffer:async()=>Uint8Array.from(bytes).buffer});let calls=0;
 for(const sample of samples){assert.deepEqual([...fs.readFileSync(path.join(__dirname,'../examples/bytes-'+sample.name+'.txt'))],sample.bytes);change(sample.name);w.fetch=async(url,options)=>{calls++;assert.equal(String(url),'https://example.test/site/examples/bytes-'+sample.name+'.txt');assert.equal(options.cache,'no-store');assert.equal(options.signal.aborted,false);return response(sample.bytes);};fetchButton.focus();fetchButton.click();assert.equal(fetchButton.disabled,true);await wait();assert.equal(fetchButton.disabled,false);assert.equal(details.hidden,false);assert.equal(lab.querySelector('[data-file-text]').textContent,sample.text);assert.deepEqual([...lab.querySelectorAll('[data-file-bits] code')].map(e=>e.textContent),sample.bits);assert.ok(result.textContent.includes(sample.bytes.length+' Byte = '+sample.bytes.length*8+' Bit'));assert.match(result.textContent,/HTTP 200/);}
 assert.equal(calls,3);w.fetch=async()=>({ok:false,status:404});fetchButton.click();await wait();assert.match(result.textContent,/HTTP 404.*kein Ausfall des gesamten Internets/);assert.equal(details.hidden,true);
 w.fetch=async()=>{throw new Error('offline');};fetchButton.click();await wait();assert.match(result.textContent,/Abruf nicht gelungen.*Ursache.*nicht nachgewiesen/);assert.equal(details.hidden,true);
 w.fetch=async()=>response([255]);fetchButton.click();await wait();assert.match(result.textContent,/nicht als UTF-8/);assert.equal(details.hidden,true);assert.equal(fetchButton.disabled,false);
 // Late request completion must not replace the newer selection or its result.
 let finishOld,oldSignal;change('a');w.fetch=async(url,options)=>{oldSignal=options.signal;return new Promise(r=>finishOld=r);};fetchButton.click();change('aa');assert.equal(oldSignal.aborted,true);w.fetch=async()=>response([65,65]);fetchButton.click();await wait();finishOld(response([65]));await wait();assert.equal(lab.querySelector('[data-file-text]').textContent,'AA');assert.equal(select.value,'../examples/bytes-aa.txt');
 // Also cover a response received before reset whose body arrives only afterwards.
 let finishBody;w.fetch=async()=>({ok:true,status:200,arrayBuffer:()=>new Promise(r=>finishBody=r)});fetchButton.click();await wait();reset.click();assert.equal(d.activeElement,select);finishBody(Uint8Array.from([65,65]).buffer);await wait();assert.equal(details.hidden,true);assert.match(result.textContent,/Noch nicht abgerufen/);assert.equal(select.selectedIndex,0);assert.equal(fetchButton.disabled,false);
 assert.equal(JSON.stringify(w.localStorage),stored);assert.equal(w.chapterRevision(id),4);assert.equal(w.currentChapterResult(id,{contentRevision:3,passed:true,lastPercent:100}).outdated,true);
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[1,0,2]);assert.ok(practice.every(q=>q.answers.length===3&&q.answers.every(a=>a.pts===0)));const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/site/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await wait();const material=pd.getElementById('ws-dgb-material');assert.ok(material.querySelector('[data-info-byte-paper]'));assert.ok(material.querySelector('[data-info-file-paper]'));assert.equal(material.querySelectorAll('button,input,select,[data-file-details],details').length,0);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,12);assert.equal(pd.querySelectorAll('#ws-solutions [data-info-byte-solution],#ws-solutions [data-info-license-solution],#ws-solutions [data-info-file-solution]').length,3);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.match(pd.querySelector('[data-info-byte-solution]').textContent,/50.000.*24.000.*24.576/s);assert.equal(1048576-1024000,24576);paper.window.close();
 console.log('PASS: all 256 byte patterns, native control contracts, three exact UTF-8 files, HTTP/network/decoding failures, stale request and body prevention, abort/reset/focus, storage preservation, revised practices and separate paper solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
