const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='math3_10_prozent_zins';
const answers={m310_q1:0,m310_q2:1,m310_dip1:2,m310_factor:0,m310_chain:1,m310_points:2,m310_q3:0,m310_half:1,m310_interest:2,m310_compound_value:1,m310_dip2:0,m310_limits:2,m310_linear:2,m310_decay:0,m310_constant:1,m310_copy:1,m310_sheet_rate:0,m310_model:2};
const groups=[['m310_q1','m310_q2','m310_dip1'],['m310_factor','m310_chain','m310_points'],['m310_q3','m310_half','m310_interest'],['m310_compound_value','m310_dip2','m310_limits'],['m310_linear','m310_decay','m310_constant'],['m310_copy','m310_sheet_rate','m310_model']];
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`),parsed=s=>Number(s.replace('≈','').replaceAll('.','').replace(/\s/g,'').replace(',','.'));
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();
 assert.equal(data[id].sections.length,6);assert.equal(d.querySelectorAll('[data-growth-task]>li').length,18);assert.equal(d.querySelectorAll('[data-growth-static] svg[data-worksheet-static]').length,1);
 const lab=d.querySelector('[data-growth-lab]'),start=d.getElementById('growth-start'),delta=d.getElementById('growth-delta'),rate=d.getElementById('growth-rate'),step=d.getElementById('growth-step'),stored=JSON.stringify(w.localStorage);let states=0;
 function set(el,v,event='change'){el.value=String(v);el.dispatchEvent(new w.Event(event));}
 for(const s of [100,500,1000])for(const a of [-10,0,10])for(const p of [-10,0,10])for(let n=0;n<=6;n++){
  set(start,s);set(delta,a);set(rate,p);step.focus();set(step,n,'input');assert.equal(d.activeElement,step);const values=w.sciverseGrowthSeries(s,a,p);assert.equal(values.length,7);
  const points=[...lab.querySelectorAll('[data-growth-point]')];assert.equal(points.length,14);const max=Number(lab.querySelector('svg').dataset.maximum),rows=[...lab.querySelectorAll('tbody tr')];assert.equal(rows.length,7);
  for(let i=0;i<=6;i++){
   // Independent closed forms (the implementation uses repeated multiplication).
   const l=s+a*i,pro=s*(100+p)**i/100**i,change=i?s*p*(100+p)**(i-1)/100**i:null;
   near(values[i].linear,l);near(values[i].proportional,pro);if(i)near(values[i].change,change);else assert.equal(values[i].change,null);
   const cells=[...rows[i].cells].map(e=>e.textContent);assert.equal(rows[i].hasAttribute('data-selected'),i===n);
   for(const[j,v]of [[1,l],[2,pro],[3,i?a:null],[4,change]]){if(v===null)assert.equal(cells[j],'–');else{assert.ok(Math.abs(parsed(cells[j])-v)<=.00500001);assert.equal(cells[j].includes('≈'),Math.abs(v-Math.round(v*100)/100)>1e-8);}}
   for(const key of ['linear','proportional']){const pt=points.find(e=>e.dataset.growthPoint===key&&Number(e.dataset.n)===i),expected=key==='linear'?l:pro;near(Number(pt.dataset.value),expected);near(Number(pt.getAttribute(key==='linear'?'cx':'x'))+(key==='linear'?0:5),65+43*i);near(Number(pt.getAttribute(key==='linear'?'cy':'y'))+(key==='linear'?0:5),240-200*expected/max);}
  }
  assert.equal(lab.querySelectorAll('[data-growth-selected]').length,2);for(const e of lab.querySelectorAll('[data-growth-selected]'))near(Number(e.getAttribute('cx')),65+43*n);
  const text=lab.querySelector('[data-growth-formula]').textContent;assert.ok(text.includes(`F2 = ${s}, G2 = ${a}, H2 = ${p}.`));assert.ok(text.includes(n?`C${n+2} = C${n+1}*(1+$H$2/100)`:'=$F$2'));assert.equal(step.getAttribute('aria-valuetext'),'Schritt '+n);states++;
 }
 assert.equal(states,189);for(const el of [start,delta,rate,step]){assert.equal(el.labels.length,1);assert.equal(el.getAttribute('aria-describedby'),'growth-result');}
 for(const args of [[0,10,10],[100,20,10],[100,10,NaN]])assert.equal(w.sciverseGrowthSeries(...args),null);
 assert.equal(w.sciverseGrowthSvg(100,10,10,7),'');w.eval(read('js/topics/'+id+'.js'));w.topicInit();assert.equal(start.value,'1000');lab.querySelector('[data-growth-reset]').click();assert.equal(start.value,'100');assert.equal(delta.value,'10');assert.equal(rate.value,'10');assert.equal(step.value,'2');assert.equal(d.activeElement,start);assert.equal(JSON.stringify(w.localStorage),stored);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,18);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(answers).sort());let paths=0;
 for(const[i,q]of qs.entries()){assert.equal(q.sectionIndex,groups.findIndex(g=>g.includes(q.id)));for(let a=0;a<3;a++){qs.forEach((item,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?a:answers[item.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===answers[q.id]?100:94);assert.equal(result.contentRevision,2);assert.deepEqual(result.reviewQuestionIds,a===answers[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));paths++;}}
 assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:1}).passed,false);
 for(const source of data[id].sources){assert.ok(source.title?.length>10);assert.ok([...d.querySelectorAll('a')].some(a=>a.textContent===source.title&&a.href===source.url));}
 const cells=[...d.querySelectorAll('[data-growth-sheet] tbody tr')];const formulas=Object.fromEntries(cells.map(tr=>[tr.cells[0].textContent,tr.cells[1].textContent]));assert.equal(formulas.C3,'=C2*(1+$H$2/100)');assert.equal(formulas.B3,'=B2+$G$2');assert.equal(formulas['B2 und C2'],'=$F$2');
 // Copy the actual authored formula references, then interpret only the supported arithmetic.
 function copy(f,offset){return f.replace(/(\$?[A-Z]+)(\$?)(\d+)/g,(_,col,absolute,row)=>col+absolute+(absolute?row:Number(row)+offset));}
 for(const[s,a,p]of [[100,10,10],[100,-10,-10],[500,-10,-10],[500,0,0]]){const sheet={F2:s,G2:a,H2:p,A2:0,B2:s,C2:s};for(let row=3;row<=8;row++)for(const col of ['A','B','C']){const f=copy(formulas[col+'3'],row-3),expression=f.slice(1).replace(/\$?([A-Z]+)\$?(\d+)/g,(_,c,r)=>'('+sheet[c+r]+')');assert.match(expression,/^[\d()+*/.\-]+$/);sheet[col+row]=Function('return '+expression)();}near(sheet.B8,s+6*a);near(sheet.C8,s*(1+p/100)**6);assert.equal(copy(formulas.C3,1),'=C3*(1+$H$2/100)');}dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));
 const material=pd.getElementById('ws-math-material');assert.equal(material.querySelectorAll('article').length,6);assert.equal(material.querySelectorAll('[data-growth-task]>li').length,18);assert.equal(material.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(material.querySelectorAll('[data-growth-paper] tbody tr').length,5);assert.equal(material.querySelectorAll('input,select,button,[role=status]').length,0);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,18);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,6);assert.equal(pd.getElementById('ws-print').disabled,false);
 assert.ok(!material.textContent.includes('undefined'));assert.ok(!material.textContent.includes('Die Tabelle lässt sich'));for(const source of data[id].sources)assert.ok(material.textContent.includes(source.title));
 function generated(tasks,solutions){assert.equal(tasks.length,8);assert.equal(solutions.length,8);for(let i=0;i<8;i++){const t=tasks[i].dataset,s=solutions[i].dataset,k=Number(t.start),r=Number(t.rate),n=Number(t.steps),kind=Number(t.kind),v=kind===0?k-k*r/100:kind===1?k*r*n/1200:kind===2?k+n*r:k*(100+r)**n/100**n;assert.equal(kind,i%4);assert.equal(s.kind,t.kind);near(Number(s.growthAnswer),v);assert.equal(solutions[i].textContent.includes('≈'),Math.abs(v-Math.round(v*100)/100)>1e-8);assert.ok(solutions[i].textContent.includes(new Intl.NumberFormat('de-AT',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)));}}
 generated([...pd.querySelectorAll('[data-growth-generated]')],[...pd.querySelectorAll('[data-growth-answer]')]);const before=pd.querySelectorAll('[data-growth-generated]')[0].outerHTML;const toggle=pd.getElementById('ws-include-solutions');assert.equal(pd.getElementById('ws-solutions').hidden,true);toggle.checked=true;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,false);assert.equal(pd.querySelectorAll('[data-growth-generated]')[0].outerHTML,before);
 for(const seed of [.01,.5,.99]){pw.Math.random=()=>seed;const fragment=JSDOM.fragment(pw.generateWorksheetContent(id,data[id].title));generated([...fragment.querySelectorAll('[data-growth-generated]')],[...fragment.querySelector('template').content.querySelectorAll('[data-growth-answer]')]);}
 paper.window.close();console.log(`PASS: growth year three: ${paths} independently keyed quiz paths, ${states} model states/coordinates/table/rounding, actual spreadsheet references and four copied series, reset/reload, paper and 32 generated solutions.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
