'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),id='bio_3_blut_kreislauf';
const keys={bio_3_blut_s1:[1,0],bio_3_blut_d1:[2,0],bio_3_blut_d4:[0,0],bio_3_blut_path:[1,0],bio_3_blut_s2:[1,1],bio_3_blut_d2:[0,1],bio_3_blut_clot:[2,1],bio_3_blut_s3:[0,2],bio_3_blut_d3:[2,2],bio_3_blut_volume:[0,2],bio_3_blut_s4:[1,3]};
const stations=['Rechte Herzkammer','Lungenarterien','Lungenkapillaren','Lungenvenen','Linker Vorhof','Linke Herzkammer','Körperarterien','Körperkapillaren','Körpervenen','Rechter Vorhof'],targets=['Lungenarterien','Lungenkapillaren','Lungenvenen','Linker Vorhof','Linke Herzkammer','Körperarterien','Körperkapillaren','Körpervenen','Rechter Vorhof','Rechte Herzkammer'];
(async()=>{const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
const zone=d.querySelector('[data-circulation-lab]'),buttons=[...zone.querySelectorAll('[data-circulation-choice]')],next=zone.querySelector('[data-circulation-next]'),reset=zone.querySelector('[data-circulation-reset]'),current=zone.querySelector('[data-circulation-current]'),out=zone.querySelector('[data-circulation-feedback]'),storage=JSON.stringify(w.localStorage);let attempts=0;
for(let i=0;i<10;i++){assert.equal(zone.dataset.step,String(i));assert.ok(current.textContent.includes(stations[i]));assert.equal(next.disabled,true);next.click();assert.equal(zone.dataset.step,String(i));const correct=buttons.findIndex(b=>b.textContent===targets[i]);assert.ok(correct>=0);for(const b of buttons.filter((_,n)=>n!==correct)){b.click();assert.equal(out.dataset.correct,'false');assert.ok(out.textContent.length>35);assert.equal(next.disabled,true);assert.equal(zone.dataset.step,String(i));attempts++;}buttons[correct].click();assert.equal(out.dataset.correct,'true');assert.match(out.textContent,/^Richtig:/);assert.equal(next.disabled,false);assert.equal(buttons[correct].getAttribute('aria-pressed'),'true');attempts++;const feedback=out.textContent;buttons[(correct+1)%3].click();assert.equal(out.textContent,feedback);next.click();assert.equal(d.activeElement,current);assert.equal(out.textContent,'');}
assert.equal(zone.dataset.step,'10');assert.equal(next.hidden,true);assert.equal(zone.querySelector('[data-circulation-options]').hidden,true);assert.match(current.textContent,/Runde abgeschlossen/);assert.equal(next.disabled,true);reset.click();assert.equal(zone.dataset.step,'0');assert.equal(next.hidden,false);assert.equal(next.disabled,true);assert.equal(d.activeElement,buttons[0]);assert.equal(out.textContent,'');assert.equal(JSON.stringify(w.localStorage),storage);
// Reset is safe after an error and after a correct answer awaiting advancement.
buttons[0].click();reset.click();buttons[1].click();reset.click();assert.equal(zone.dataset.step,'0');assert.equal(next.disabled,true);assert.equal(JSON.stringify(w.localStorage),storage);
assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,11);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));
for(const [i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('.circulation-map svg[data-worksheet-static]').length,1);assert.equal(d.querySelectorAll('.circulation-components .circulation-card').length,4);assert.equal(d.querySelectorAll('.circulation-cases .circulation-card').length,3);assert.deepEqual([...d.querySelectorAll('.circulation-route li')].map(e=>e.textContent),stations);assert.equal(d.querySelectorAll('[data-circulation-solution]').length,4);assert.equal(d.querySelectorAll('img').length,0);const numbers=s=>[...d.querySelectorAll(s+' tbody tr')].map(r=>[...r.querySelectorAll('td')].map(e=>Number(e.textContent)));assert.deepEqual(numbers('.circulation-pulse'),[[18,15],[27,15],[20,15]]);assert.deepEqual(numbers('.circulation-output'),[[72,70],[108,70],[108,50]]);assert.deepEqual(numbers('.circulation-output').map(([rate,v])=>rate*v/1000),[5.04,7.56,5.4]);assert.ok(data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).every(q=>q.answers.every(a=>a.pts===0)));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-circulation-paper]').length,1);assert.equal(pd.querySelectorAll('.circulation-map svg').length,1);assert.equal(pd.querySelectorAll('.circulation-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('.circulation-pulse tbody tr').length,3);assert.equal(pd.querySelectorAll('.circulation-output tbody tr').length,3);assert.equal(pd.querySelectorAll('.circulation-vessels tbody tr').length,4);assert.equal(pd.querySelectorAll('#ws-solutions [data-circulation-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-circulation-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material [data-circulation-choice]').length,0);paper.window.close();
console.log(`PASS: ${attempts} route decisions, 10 guarded transitions, completion/reset/focus/storage, 33 independently keyed quiz answers, 12 tasks, 16 terms, original schema and complete separate paper solutions.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
