'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_sexualitaet_verantwortung';
const keys={bio_4_sex_s1:[1,0],bio_4_sexualitaet_d1:[2,0],bio_4_sex_hormone:[0,0],bio_4_sex_s2:[2,1],bio_4_sexualitaet_d2:[0,1],bio_4_sex_kalender:[1,1],bio_4_sex_s3:[0,2],bio_4_sex_methoden:[2,2],bio_4_sex_quellen:[1,2],bio_4_sexualitaet_d3:[2,3],bio_4_sex_hilfe:[0,3]};
const correct=[1,2,0,2,1,0],reasons=[[/keine Messung/,/belegt keinen sicheren Tag/,/garantiert keinen/],[/keinen gemeinsamen Schutz/,/keinen Infektionsschutz/,/getrennt zu beurteilen/],[/90 Prozent.*80 Prozent/,/Nenner/,/keine fachliche Richtigkeit/],[/verpflichtet nicht/,/Rechtfertigung/,/aktuelle Grenze/],[/Alex’ Zustimmung nicht/,/Alex entscheidet/,/ebenso verletzen/],[/zeitabhängig/,/Warten/,/Fremde Medikamente/]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-responsibility-lab]'),select=zone.querySelector('select'),panels=[...zone.querySelectorAll('fieldset')],result=zone.querySelector('[role=status]'),check=zone.querySelector('[data-responsibility-check]'),reset=zone.querySelector('[data-responsibility-reset]'),storage=JSON.stringify(w.localStorage);assert.equal(panels.length,6);assert.equal(zone.querySelectorAll('textarea,input:not([type=radio])').length,0);
 let decisions=0;for(let i=0;i<6;i++){
  select.value=String(i);select.dispatchEvent(new w.Event('change'));assert.deepEqual(panels.map(p=>p.hidden),[0,1,2,3,4,5].map(j=>j!==i));assert.equal(result.textContent,'');assert.equal(zone.querySelectorAll('input:checked').length,0);
  check.click();assert.equal(result.dataset.invalid,'answer');assert.equal(d.activeElement,panels[i].querySelector('input'));
  for(const[j,input]of [...panels[i].querySelectorAll('input')].entries()){input.click();assert.equal(result.textContent,'');check.click();assert.equal(result.dataset.supported,String(j===correct[i]));assert.match(result.textContent,reasons[i][j]);assert.equal(d.activeElement,result);assert.equal(input.disabled,false);assert.equal(result.querySelectorAll('h4').length,1);decisions++;}
 }
 assert.equal(decisions,18);select.value='';select.dispatchEvent(new w.Event('change'));assert.ok(panels.every(p=>p.hidden));check.click();assert.equal(result.dataset.invalid,'case');assert.equal(d.activeElement,select);reset.click();assert.equal(select.value,'0');assert.equal(d.activeElement,select);assert.equal(result.textContent,'');assert.equal(zone.querySelectorAll('input:checked').length,0);assert.equal(JSON.stringify(w.localStorage),storage);
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(d.querySelectorAll('.responsibility-cycle li').length,4);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 assert.deepEqual([...d.querySelectorAll('.responsibility-survey tbody tr')].map(e=>[...e.children].map(c=>c.textContent)),[['A','20','18'],['B','40','32']]);assert.match(d.querySelector('[data-responsibility-solution="2"]').textContent,/10 Prozentpunkte/);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,11);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].id,'bio_4_sexualitaet_extra_einverstaendnis');assert.equal(practice[0].answers.findIndex(a=>a.correct),1);assert.ok(practice[0].answers.every(a=>a.pts===0));const before=JSON.stringify(w.localStorage);w.playSuccessSound=()=>{};for(const answer of practice[0].answers){const button=[...d.querySelectorAll('.practice-box .practice-option')].find(e=>e.textContent===answer.text);assert.ok(button);w.handlePracticeAnswer(button,answer.correct,button.dataset.feedback);assert.ok(button.closest('.practice-box').querySelector('.feedback').innerText.includes(answer.feedback));assert.equal(button.disabled,false);}assert.equal(JSON.stringify(w.localStorage),before);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.responsibility-paper-case').length,6);assert.equal(pd.querySelectorAll('.responsibility-paper-case li').length,18);assert.equal(pd.querySelectorAll('#ws-solutions .responsibility-case-solution').length,6);assert.equal(pd.querySelectorAll('#ws-solutions [data-responsibility-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-responsibility-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material input,#ws-biology-material select').length,0);assert.equal(pd.querySelectorAll('.responsibility-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,1);assert.doesNotMatch(pd.body.textContent,/undefined/);
 for(const [i,s]of [...pd.querySelectorAll('.responsibility-case-solution')].entries()){assert.ok(s.querySelector('h4').textContent.endsWith(String.fromCharCode(65+correct[i])));for(let j=0;j<3;j++)assert.match(s.querySelectorAll('p')[j].textContent,reasons[i][j]);}
 for(const s of data[id].sources){assert.ok(s.title&&s.url.startsWith('https://'));assert.ok(pd.body.textContent.includes(s.title));}paper.window.close();
 console.log('PASS: 18 independently checked case decisions, empty/invalid/reset/focus/storage, 33 graded and 3 practice paths, original tasks, six complete paper cases and solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
