'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb8_handeln';
const keys={dgb8_handeln_q3:1,dgb8_system_rights:2,dgb8_handeln_q1:1,dgb8_crypto_integrity:0,dgb8_handeln_q2:2,dgb8_consumer_help:0,dgb8_handeln_q4:2,dgb8_civic_participation:1};
(async()=>{
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 assert.equal(d.querySelectorAll('[data-action-tasks] > li').length,18);assert.equal(d.querySelectorAll('[data-action-case]').length,4);assert.equal(d.querySelectorAll('[data-system-cards] > div').length,3);assert.equal(d.querySelectorAll('[data-action-solution]').length,4);
 assert.equal(d.querySelector('[data-encryption-link]').href,'https://example.test/examples/verschluesselungswerkstatt.html');assert.ok(fs.existsSync(path.join(__dirname,'../examples/verschluesselungswerkstatt.html')));
 assert.match(d.querySelector('[data-action-solution="consumer"]').textContent,/1 \+ 9 \+ 9 = 19.*23.*3 × 8 = 24/s);
 assert.equal(w.chapterRevision(id),1);assert.equal(w.currentChapterResult(id,{contentRevision:0,lastPercent:100}).outdated,true);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,8);
 for(const [i,q]of qs.entries()){assert.equal(q.sectionIndex,Math.floor(i/2));assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,n)=>d.querySelector(`input[name="chapter_q_${n}"][value="${i===n?choice:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id]?100:88);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.deepEqual(practice.map(q=>q.answers.findIndex(a=>a.correct)),[0,1,0]);assert.ok(practice.every(q=>q.answers.every(a=>a.pts===0)));dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('[data-action-tasks] > li').length,18);assert.equal(material.querySelectorAll('[data-action-case]').length,4);assert.equal(material.querySelectorAll('[data-action-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-action-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);assert.match(material.textContent,/Vorbereitung.*wirklichen Versuch/s);paper.window.close();
 console.log('PASS: 24 independently keyed answers and review sections, 3 ungraded practice keys, 18 tasks, system/consumer/participation material, revision and actual paper export with 4 separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
