'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{JSDOM}=require('jsdom'),keys=require('./fixtures/written_arithmetic_answer_keys.json');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),de=JSON.parse(read('lang/de.json')),id='math1_4_mult_div';
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>de});for(const f of ['curriculum','common','chapter-revisions','core-learning','renderer','topics/'+id])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.topicInit();w.topicInit();
let mul=0,div=0;
function multiplication(a,b){const m=w.writtenMultiplication(a,b);assert.equal(m.result,a*b);assert.equal(m.partials.reduce((x,y)=>x+y,0),a*b);for(const step of m.steps.filter(s=>s.kind==='multiply')){assert.equal(step.expected,step.digit*step.factor+step.incoming);if(!step.last){assert.equal(step.write+10*step.carry,step.expected);assert.ok(step.write>=0&&step.write<10);}else assert.equal(step.partial,m.partials[step.row]);}mul++;}
function division(a,b){const m=w.writtenDivision(a,b);assert.equal(m.result,Math.trunc(a/b));assert.equal(m.remainder,a%b);assert.equal(m.result*b+m.remainder,a);for(const step of m.steps){assert.ok(step.expected>=0&&step.expected<=9);assert.ok(step.remainder>=0&&step.remainder<b);assert.equal(step.expected*b+step.remainder,step.partial);assert.equal(step.partial,step.previous*10+step.brought);}div++;}
for(let a=0;a<100;a++)for(let b=0;b<100;b++)multiplication(a,b);for(const a of [108,203,286,407,999,1005,9999])for(const b of [14,26,34,99,205,999])multiplication(a,b);
for(let a=0;a<=1000;a++)for(let b=1;b<=25;b++)division(a,b);for(const a of [1001,1005,7344,7350,999999])for(const b of [4,8,24,25,99])division(a,b);
assert.deepEqual(Array.from(w.writtenDivision(7344,24).steps,s=>s.expected),[3,0,6]);assert.deepEqual(Array.from(w.writtenDivision(1005,8).steps,s=>s.partial),[10,20,45]);assert.deepEqual(Array.from(w.writtenMultiplication(286,34).steps,s=>s.expected),[24,34,11,18,25,8,9724]);
for(const args of [[1,0],[-1,5],[1.2,5],[1000000,2],[1,100]])assert.throws(()=>w.writtenDivision(...args));for(const args of [[-1,2],[10000,2],[1,1000],['1',2]])assert.throws(()=>w.writtenMultiplication(...args));
const saved=JSON.stringify(w.localStorage);let steps=0;
for(const host of d.querySelectorAll('[data-written-lab]')){const input=host.querySelector('input'),select=host.querySelector('select'),status=host.querySelector('[data-written-status]'),check=host.querySelector('[data-written-check]'),reveal=host.querySelector('[data-written-show]');for(let i=0;i<select.options.length;i++){
 select.value=String(i);select.dispatchEvent(new w.Event('change'));const[a,b]=select.options[i].textContent.split(/[·:]/).map(Number),model=host.dataset.writtenLab==='multiply'?w.writtenMultiplication(a,b):w.writtenDivision(a,b);
 for(const [j,step]of model.steps.entries()){input.value=String(step.expected+1);check.click();assert.equal(host.dataset.step,String(j));assert.doesNotMatch(status.textContent,/^Richtig/);if(host.dataset.writtenLab==='divide'&&step.expected>0){input.value='0';check.click();assert.match(status.textContent,/Noch zu klein/);assert.equal(host.dataset.step,String(j));}input.value=String(step.expected);input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(host.dataset.step,String(j+1));assert.match(status.textContent,/^Richtig/);steps++;}
 const boardRows=[...host.querySelectorAll('[data-written-board] tbody tr')];if(host.dataset.writtenLab==='multiply'){assert.deepEqual(boardRows.map(r=>Number([...r.querySelectorAll('td')].map(c=>c.textContent).join('').trim())),[...model.partials,model.result]);}else{assert.equal(Number(boardRows.map(r=>r.cells[2].textContent).join('')),model.result);assert.equal(Number(boardRows.at(-1).cells[3].textContent),model.remainder);}
 assert.equal(d.activeElement,status);assert.ok(status.textContent.includes('Alle Zwischenergebnisse'));assert.equal(input.disabled,true);assert.equal(host.querySelectorAll('[data-written-history] li').length,model.steps.length);
 host.querySelector('[data-written-reset]').click();assert.equal(d.activeElement,input);assert.equal(host.dataset.step,'0');reveal.click();assert.match(status.textContent,/Schritt gezeigt/);assert.ok(host.querySelector('[data-written-history]').textContent.includes('Gezeigter Schritt'));
 while(!reveal.disabled)reveal.click();assert.ok(status.textContent.includes('wurden gezeigt'));assert.ok(!status.textContent.includes('Alle Zwischenergebnisse sind richtig'));
 host.querySelector('[data-written-reset]').click();
 }
 for(const raw of ['',' ','2.0','2,0','2e1','0x2','-1','9007199254740992']){input.value=raw;check.click();assert.equal(input.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,input);}input.dispatchEvent(new w.Event('input'));assert.equal(status.textContent,'');assert.equal(input.hasAttribute('aria-invalid'),false);
}
assert.equal(JSON.stringify(w.localStorage),saved);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,20);assert.deepEqual(Array.from(qs,q=>q.id).sort(),Object.keys(keys).sort());let paths=0;
for(const[i,q]of qs.entries())for(let a=0;a<q.answers.length;a++){assert.equal(q.answers[a].correct,a===keys[q.id]);w.restartChapterQuiz();qs.forEach((other,j)=>d.querySelector('input[name="chapter_q_'+j+'"][value="'+(i===j?a:keys[other.id])+'"]').checked=true);w.submitChapterQuiz();const result=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(result.lastPercent,a===keys[q.id]?100:95);assert.equal(result.contentRevision,3);assert.deepEqual(result.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));paths++;}dom.window.close();
const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.MathJax={typesetPromise:async()=>{}};pw.fetch=async()=>({ok:true,json:async()=>de});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-written-paper]').length,2);assert.equal(pd.querySelectorAll('#ws-math-material svg').length,2);assert.equal(pd.querySelectorAll('.ws-paper-solution').length,5);assert.equal(pd.querySelectorAll('#ws-content>.question-block').length,20);let generated=0;
for(let seed=1;seed<=12;seed++){let n=seed;pw.Math.random=()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};const box=pd.createElement('div');box.innerHTML=pw.generateWorksheetContent(id,de[id].title);const tasks=box.querySelectorAll('[data-written-generated]'),answers=box.querySelector('template').content.querySelectorAll('[data-written-generated-answer]');assert.equal(tasks.length,20);for(let i=0;i<20;i++){const a=+tasks[i].dataset.a,b=+tasks[i].dataset.b,result=+answers[i].dataset.writtenGeneratedAnswer,rest=+answers[i].dataset.rest;if(tasks[i].dataset.kind==='multiply')assert.equal(result,a*b);else{assert.equal(result*b+rest,a);assert.ok(rest>=0&&rest<b);}generated++;}}paper.window.close();console.log('PASS: '+mul+' multiplication models, '+div+' divisions, '+steps+' entered steps, '+paths+' independent quiz paths, focus/reveal/reset/storage and '+generated+' generated answers with paper material.');
})().catch(e=>{console.error(e);process.exitCode=1;});
