const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),data=JSON.parse(read('lang/de.json'));
(async()=>{const ids=Object.keys(data).filter(id=>/^dgb/.test(id));assert.equal(ids.length,21);for(const id of ids){const dom=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/physik_bay6/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])w.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=d.getElementById('ws-dgb-material');assert.ok(material,id);if(data[id].sections.some(s=>s.title.includes('Fachw&ouml;rter')))assert.ok([...material.querySelectorAll('article > .ws-section-header > h3')].some(h=>h.textContent.includes('Fachwörter')),id);assert.ok(![...material.querySelectorAll('article > .ws-section-header > h3')].some(h=>h.textContent.includes('&ouml;')),id);assert.equal(material.querySelectorAll('article').length,data[id].sections.length,id);assert.equal(material.querySelectorAll('button,input,select,script,details').length,0);if(id==='dgb8_information'){assert.equal(material.querySelectorAll('[data-restore-steps] li').length,7);assert.equal(material.querySelectorAll('[data-restore-protocol] tbody tr').length,3);assert.match(material.textContent,/Version 2; 15 Uhr/);}const toggle=d.getElementById('ws-include-material');toggle.checked=false;toggle.dispatchEvent(new w.Event('change'));assert.equal(material.hidden,true);assert.equal(d.getElementById('ws-solutions').hidden,true);dom.window.close();}
// Revised German content must be selected when older translations are no longer current.
for(const language of ['de','en','tr','sr']){
 const translated=JSON.parse(read('lang/'+language+'.json')),id='dgb8_information';
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.localStorage.setItem('physik_lang',language);w.fetch=async url=>({ok:true,json:async()=>url.includes('/de.json')?data:translated});
 for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 assert.equal(w.currentChapterQuiz.questions.length,8);assert.equal(d.getElementById('sections-container').lang,'de');
 assert.equal(d.querySelectorAll('[data-restore-steps] li').length,7);assert.equal(d.querySelectorAll('[data-restore-protocol] tbody tr').length,3);
 assert.deepEqual([...d.querySelectorAll('[data-restore-protocol] tbody tr')].map(r=>r.cells[1].textContent),['Version 2; 15 Uhr','Version 1; 14 Uhr','Version 1; 14 Uhr']);
 assert.ok(d.querySelector('.trace-workshop'));if(language!=='de'){assert.ok(d.querySelector('[data-content-language-notice]'));assert.ok(translated[id].sourceRevision<w.chapterRevision(id));}
 assert.equal(w.currentChapterResult(id,{contentRevision:1,lastPercent:100}).outdated,true);dom.window.close();
}
console.log('PASS: 21 complete DGB worksheets, material/solution separation, unchanged seven-step restore exercise and three file versions; current German eight-question chapter and explicit fallback for three stale translations. Independent quiz keys are checked in test_profile_traces.js.');
})().catch(e=>{console.error(e);process.exitCode=1;});
