'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
const keys={m38_q1:0,pyth_names:1,pyth_puzzle_1:0,m38_q2:0,m38_dip1:0,pyth_same_pieces:2,pyth_middle_square:0,pyth_general:1,pyth_converse:1,pyth_not_right:2,pyth_degenerate:0,m42_q1:0,m42_q2:0,m42_leg:0,m42_diagonal:0,m42_dip1:0,pyth_isosceles:1,pyth_triangle_area:2,pyth_rhombus:0,pyth_space_triangle:2,pyth_space_value:0,pyth_space_inverse:1,pyth_pyramid_height:1,pyth_pyramid_area:2,pyth_pyramid_edge:0};
const area=points=>Math.abs(points.reduce((s,p,i)=>{const next=points[(i+1)%points.length];return s+p[0]*next[1]-p[1]*next[0];},0))/2;
function inside(p,points){const signs=points.map((a,i)=>{const b=points[(i+1)%points.length];return(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);});return signs.every(x=>x>=0)||signs.every(x=>x<=0);}
const permutations=([a,b,c])=>[[a,b,c],[a,c,b],[b,a,c],[b,c,a],[c,a,b],[c,b,a]];
(async()=>{let proofCases=0,converseCases=0,spaceCases=0,paths=0;for(const id of ['math3_8_pythagoras','math4_2_pythagoras']){
 const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();assert.equal(w.chapterRevision(id),3);assert.equal(w.currentChapterResult(id,{revision:2,passed:true,bestPercent:100}).passed,false);const saved=JSON.stringify(w.localStorage),set=(selector,value,event='input')=>{const el=d.querySelector(selector);el.value=String(value);el.dispatchEvent(new w.Event(event));};
 if(id==='math3_8_pythagoras'){
  assert.equal(d.querySelectorAll('[data-core-intro] li').length,5);assert.equal(w.currentChapterQuiz.questions.length,11);assert.equal(d.querySelectorAll('[data-pyth-tasks] li').length,6);
  const input=d.querySelector('#proof-answer'),status=d.querySelector('#proof-status');
  for(let a=1;a<=6;a++)for(let b=1;b<=6;b++){
   set('#proof-a',a);set('#proof-b',b);const L=a+b;for(const layout of ['central','split']){const g=w.pythProofGeometry(a,b,layout),all=[...g.triangles,...g.squares];assert.equal(g.triangles.length,4);assert.equal(g.squares.length,layout==='central'?1:2);assert.ok(Math.abs(all.reduce((n,p)=>n+area(p),0)-L*L)<1e-10);for(const triangle of g.triangles){assert.equal(area(triangle),a*b/2);const lengths=triangle.map((p,i)=>{const next=triangle[(i+1)%3];return(p[0]-next[0])**2+(p[1]-next[1])**2;}).sort((a,b)=>a-b);assert.deepEqual(Array.from(lengths),[a*a,b*b,a*a+b*b].sort((a,b)=>a-b));}assert.equal(g.squares.reduce((n,p)=>n+area(p),0),a*a+b*b);for(let x=0;x<13;x++)for(let y=0;y<13;y++){const point=[(x+.371)*L/13,(y+.613)*L/13];assert.equal(all.filter(poly=>inside(point,poly)).length,1,`${a}/${b}/${layout}: gap or overlap`);}}
   assert.equal(d.querySelectorAll('[data-proof-drawings] [data-pyth-piece]').length,8);input.value=String(a*a+b*b);d.querySelector('[data-proof-check]').click();assert.match(status.textContent,/^Richtig/);assert.equal(d.activeElement,status);assert.ok(d.querySelector('[data-proof-result]').textContent.includes((a*a+b*b)+' cm²'));input.value='199';d.querySelector('[data-proof-check]').click();assert.match(status.textContent,/^Noch nicht/);input.dispatchEvent(new w.Event('input'));assert.equal(status.textContent,'');proofCases++;
  }
  for(const bad of ['','NaN','-1','201','1e2','3cm²']){input.value=bad;d.querySelector('[data-proof-check]').click();assert.equal(input.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,input);}
  d.querySelector('[data-proof-reset]').click();assert.equal(d.activeElement.id,'proof-a');assert.equal(d.querySelector('#proof-a').value,'3');input.value='25';input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(status.textContent,/^Richtig/);
  for(const [sides,expected]of [[[3,4,5],'right'],[[5,12,13],'right'],[[8,15,17],'right'],[[1.5,2,2.5],'right'],[[.03,.04,.05],'right'],[[6,8,11],'other'],[[5,5,6],'other'],[[3,4,5.01],'other'],[[2,3,5],'none'],[[2,3,6],'none']])for(const order of permutations(sides)){order.forEach((value,i)=>set('#converse-'+['x','y','z'][i],String(value).replace('.',',')));d.querySelector('[data-converse-check]').click();const text=d.querySelector('[data-converse-status]').textContent;assert.equal(text.includes('Kein Dreieck:'),expected==='none');assert.equal(text.includes('Rechtwinklig.'),expected==='right');assert.equal(text.includes('Nicht rechtwinklig.'),expected==='other');converseCases++;}
  for(const bad of ['','0','-1','100.01','0.001','3cm','1e1']){set('#converse-x',bad);d.querySelector('[data-converse-check]').click();assert.equal(d.querySelector('#converse-x').getAttribute('aria-invalid'),'true');assert.equal(d.activeElement.id,'converse-x');}d.querySelector('[data-converse-reset]').click();assert.equal(d.activeElement.id,'converse-x');
  const polygons=[...d.querySelectorAll('#pyth-puzzle-svg [role="button"]')];assert.equal(polygons.length,25);for(const poly of polygons){const points=poly.getAttribute('points').split(' ').map(x=>x.split(',').map(Number));assert.equal(area(points),900);poly.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(poly.getAttribute('aria-disabled'),'true');assert.equal(area(poly.getAttribute('points').split(' ').map(x=>x.split(',').map(Number))),900);}assert.match(d.getElementById('pyth-success-msg').textContent,/Beispiel überprüft/);assert.equal(new Set(polygons.map(p=>p.getAttribute('points'))).size,25);w.resetPythPuzzle();assert.equal(d.querySelectorAll('#pyth-puzzle-svg [data-moved]').length,0);assert.match(d.getElementById('pyth-success-msg').textContent,/0 von 25/);
  const nextButton=d.querySelector('[data-pyth-next]');nextButton.focus();for(let i=0;i<25;i++){assert.equal(nextButton.disabled,false);nextButton.click();assert.equal(d.querySelectorAll('#pyth-puzzle-svg [data-moved]').length,i+1);if(i<24)assert.equal(d.activeElement,nextButton);}assert.equal(nextButton.disabled,true);assert.equal(d.activeElement,d.querySelector('[data-pyth-puzzle-reset]'));w.resetPythPuzzle();assert.equal(nextButton.disabled,false);assert.equal(d.querySelectorAll('#pyth-puzzle-svg [data-moved]').length,0);assert.equal(d.activeElement,d.querySelector('#pyth-puzzle-svg [role=button]'));
  set('#pyth_in','5');d.querySelector('#pyth_in').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(d.getElementById('pyth_feedback').textContent,/Richtig/);
 }else{
  assert.equal(d.querySelectorAll('[data-core-intro] li').length,6);assert.equal(w.currentChapterQuiz.questions.length,14);assert.equal(d.querySelectorAll('[data-pyth-tasks] li').length,9);
  const input=d.querySelector('#space-answer'),status=d.querySelector('#space-status');for(const a of [2,3,4,6])for(const b of [2,3,4,6])for(const h of [2,6,12]){set('#space-a',a,'change');set('#space-b',b,'change');set('#space-h',h,'change');const expected=Math.hypot(a,b,h),m=w.pythSpaceModel(a,b,h);assert.ok(Math.abs(m.space-expected)<1e-12);assert.equal(m.floorSquared,a*a+b*b);input.value=expected.toFixed(2).replace('.',',');input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(status.textContent,/^Richtig/);assert.equal(d.activeElement,status);assert.equal(d.querySelectorAll('[data-space-result] li').length,3);input.value='99';d.querySelector('[data-space-check]').click();assert.match(status.textContent,/^Noch nicht/);input.dispatchEvent(new w.Event('input'));assert.equal(status.textContent,'');spaceCases++;}
  for(const bad of ['','-1','101','13cm','1e1']){input.value=bad;d.querySelector('[data-space-check]').click();assert.equal(input.getAttribute('aria-invalid'),'true');assert.equal(d.activeElement,input);}d.querySelector('[data-space-reset]').click();assert.equal(d.activeElement.id,'space-a');assert.equal(d.querySelector('#space-h').value,'12');set('#pyth1','5');d.querySelector('#pyth1').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(d.getElementById('fb_pyth1').textContent,/Richtig/);
 }
 assert.equal(JSON.stringify(w.localStorage),saved);
 for(const[i,q]of w.currentChapterQuiz.questions.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id],q.id);for(let answer=0;answer<q.answers.length;answer++){w.currentChapterQuiz.questions.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?answer:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,answer===keys[q.id]?100:id==='math3_8_pythagoras'?91:93);assert.deepEqual(r.reviewQuestionIds,answer===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[answer].feedback));paths++;}}
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.pyth-paper').length,id==='math3_8_pythagoras'?4:2);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,id==='math3_8_pythagoras'?2:4);assert.equal(pd.querySelectorAll('#ws-solutions [data-pyth-solution]').length,id==='math3_8_pythagoras'?2:3);assert.equal(pd.getElementById('ws-solutions').hidden,true);const toggle=pd.getElementById('ws-include-solutions');toggle.checked=true;toggle.dispatchEvent(new pw.Event('change'));assert.equal(pd.getElementById('ws-solutions').hidden,false);
 const verify=(tasks,answers)=>{assert.equal(tasks.length,6);assert.equal(answers.length,6);tasks.forEach((t,i)=>{const a=Number(t.dataset.a),b=Number(t.dataset.b),c=Number(t.dataset.c),h=Number(t.dataset.h),expected=t.dataset.kind==='triangle'?(t.dataset.target==='c'?Math.hypot(a,b):Math.sqrt(c*c-a*a)):t.dataset.kind==='cuboid'?Math.hypot(a,b,h):a*a+4*(a*Math.hypot(h,a/2)/2);assert.ok(Math.abs(Number(answers[i].dataset.pythGeneratedAnswer)-expected)<1e-10);assert.ok(answers[i].textContent.includes(t.dataset.kind==='triangle'?expected+' cm':expected.toLocaleString('de-AT',{minimumFractionDigits:2,maximumFractionDigits:2})+' cm'));});};verify([...pd.querySelectorAll('[data-pyth-generated]')],[...pd.querySelectorAll('#ws-solutions [data-pyth-generated-answer]')]);for(const random of [0,.2,.5,.8,.99999]){pw.Math.random=()=>random;const block=pd.createElement('div');block.innerHTML=pw.generateWorksheetContent(id,data[id].title);verify([...block.querySelectorAll('[data-pyth-generated]')],[...block.querySelector('template[data-generated-worksheet-solutions]').content.querySelectorAll('[data-pyth-generated-answer]')]);}
 paper.window.close();dom.window.close();
 }assert.equal(paths,69);console.log(`PASS: ${proofCases} geometric dissections (areas, congruent triangles, sampled coverage), ${converseCases} reordered exact side checks, 25 keyboard puzzle pieces, ${spaceCases} cuboids, ${paths} quiz paths, both complete worksheets and matching generated solutions.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
