const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json'));
(async()=>{let answers=0;
 for(const [id,keys,count]of [['optik1',{o1_visibility:1,o1_light_time:2},21],['akustik',{ak_receiver:2},22]]){
  const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,count);
  for(const q of qs.filter(q=>q.id in keys)){assert.equal(q.sectionIndex,0);const i=qs.indexOf(q);for(let a=0;a<3;a++){qs.forEach((item,j)=>d.querySelector(`input[name="chapter_q_${j}"][value="${j===i?a:item.id in keys?keys[item.id]:item.answers.findIndex(x=>x.correct)}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,a===keys[q.id]?100:95);assert.equal(r.contentRevision,5);assert.deepEqual(r.reviewQuestionIds,a===keys[q.id]?[]:[q.id]);assert.ok(d.getElementById('chapter-quiz-result').textContent.includes(q.answers[a].feedback));answers++;}}
  assert.equal(w.currentChapterResult(id,{passed:true,bestPercent:100,contentRevision:4}).passed,false);dom.window.close();
  const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.getElementById('ws-solutions').hidden,true);
  const material=pd.getElementById('ws-physics-material');if(id==='optik1'){assert.equal(material.querySelectorAll('[data-visibility-task]>li').length,4);assert.ok(material.querySelector('[data-light-speed]'));assert.match(material.textContent,/fortlaufend Licht in viele Richtungen/);assert.ok(material.querySelector('[data-shadow-prediction]'));assert.ok(!material.querySelector('[data-visibility-solution]'));assert.match(pd.getElementById('ws-solutions').textContent,/Ein Reflektor ist keine eigene Lichtquelle/);}else{assert.equal(material.querySelectorAll('[data-hearing-task]>li').length,3);assert.ok(!material.querySelector('[data-hearing-solution]'));assert.match(pd.getElementById('ws-solutions').textContent,/zusätzliche sichtbare Mitteilung/);}paper.window.close();
 }
 const dom=new JSDOM(read('topics/learning.html'),{url:'https://example.test/topics/learning.html?subject=physik&grade=6&mode=teach&plan=akustik,optik1',runScripts:'outside-only'}),w=dom.window,d=dom.window.document;w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','learning'])w.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));d.getElementById('subject').value='physik';d.getElementById('grade').value='6';d.getElementById('subject').dispatchEvent(new w.Event('input'));
 assert.deepEqual([...d.querySelectorAll('#chapters [data-focus-key^="catalog-open-"]')].map(e=>e.dataset.focusKey.slice(13)),['sieinheiten','optik1','erde_mond_sonne','linsen_spiegel','farben','akustik']);assert.deepEqual([...d.querySelectorAll('#selected [data-focus-key^="plan-open-"]')].map(e=>e.dataset.focusKey.slice(10)),['akustik','optik1']);dom.window.close();assert.equal(answers,9);
 console.log('PASS: nine independently keyed light/sound transfer answers, revision 5, printed tasks and separated solutions; coherent year-2 catalog order preserves assigned plan order.');
})().catch(e=>{console.error(e);process.exitCode=1;});
