const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),data=JSON.parse(read('lang/de.json')),id='dgb8_orientierung';
const keys=require('./fixtures/dgb8_orientation_keys.json');
(async()=>{const dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();
 const control=d.querySelector('[data-boundary-control]'),cases=[...d.querySelector('[data-core-experiment="boundary-cases"]').querySelectorAll('[data-boundary-case]')],out=d.querySelector('[data-boundary-result]'),stored=JSON.stringify(w.localStorage),prefix=['Belegt:','Widerlegt:','Nicht geklärt:'];
 assert.equal(cases.length,3);for(let c=0;c<3;c++){control.value=String(c);control.dispatchEvent(new w.Event('change'));assert.equal(cases.filter(e=>!e.hidden).length,1);assert.equal(cases[c].hidden,false);for(let choice=0;choice<3;choice++){cases[c].querySelectorAll('button')[choice].click();assert.equal(out.textContent.startsWith(prefix[c]),choice===c);assert.match(out.textContent,[[/Q1.*10 Uhr/,/Q1.*10 Uhr/,/Q1.*10 Uhr/],[/Q2.*2025.*Q1.*3 Euro/,/Q1.*3 Euro.*Q3/,/Q1.*3 Euro/],[/Erdgeschoß.*Eingangsstufe/,/Keine Angabe.*nicht/,/Veranstalter.*Eingang/]][c][choice]);}}
 d.querySelector('[data-boundary-reset]').click();assert.equal(control.value,'0');assert.equal(d.activeElement,control);assert.match(out.textContent,/Wähle ein Urteil/);assert.equal(JSON.stringify(w.localStorage),stored);assert.equal(d.getElementById(control.getAttribute('aria-describedby')),out);
 assert.equal(d.querySelectorAll('[data-ai-sources] > div').length,3);assert.match(d.querySelector('[data-ai-sources]').textContent,/3 Euro/);assert.match(d.querySelector('[data-ai-sources]').textContent,/2025/);
 const rows=[...d.querySelectorAll('[data-ai-feed] tbody tr')].map(r=>[...r.cells].map(c=>c.textContent));assert.deepEqual(rows.map(r=>r[0][0]),['A','B','C','D','E','F']);assert.deepEqual(rows.map(r=>r[1]),['Sport','Sport','Sport','Natur','Mitbestimmung','Natur']);assert.deepEqual(rows.map(r=>Number(r[2])),[9,8,7,6,5,4]);assert.match(d.querySelector('[data-ai-solution="feed"]').textContent,/Regel A: A, B, C;.*Regel B: A, D, E;/s);
 assert.equal(d.querySelectorAll('[data-ai-tasks] > li').length,16);assert.equal(d.querySelectorAll('[data-worksheet-solution]').length,6);assert.equal(d.querySelectorAll('template[data-worksheet-alternative]')[0].content.querySelectorAll('.ai-paper-case').length,3);
 assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,lastPercent:100}).outdated,true);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,14);for(const [i,q]of qs.entries()){assert.equal(q.sectionIndex,i<8?Math.floor(i/2):i<11?4:5);assert.equal(q.answers.length,3);assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,n)=>d.querySelector(`input[name="chapter_q_${n}"][value="${i===n?choice:keys[item.id]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id]?100:93);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));const material=pd.getElementById('ws-dgb-material');assert.equal(material.querySelectorAll('.ai-paper-case').length,9);assert.equal(material.querySelectorAll('[data-ai-tasks] > li').length,16);assert.equal(material.querySelectorAll('[data-ai-sources] > div').length,3);assert.equal(material.querySelectorAll('button,select,input,details').length,0);assert.equal(material.querySelectorAll('[data-ai-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-solutions [data-ai-solution]').length,4);assert.equal(pd.getElementById('ws-solutions').hidden,true);paper.window.close();
 console.log('PASS: nine evidence decisions, reset/focus/storage, 42 independently keyed assessed answers, exact source/feed material, 16 tasks, nine paper cases and separate solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
