const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const keys={bio_3_wassertiere_s1:[1,0],bio_3_wassertiere_d2:[2,0],bio_3_wassertiere_air:[0,0],bio_3_wassertiere_s2:[2,1],bio_3_wassertiere_identity:[1,1],bio_3_wassertiere_d1:[0,1],bio_3_wassertiere_s3:[1,2],bio_3_wassertiere_d3:[2,2],bio_3_wassertiere_s4:[0,3],bio_3_wassertiere_model:[1,3]};
const permutations=a=>a.length?a.flatMap((v,i)=>permutations(a.filter((_,j)=>i!==j)).map(p=>[v,...p])):[[]];
(async()=>{
 const data=JSON.parse(read('lang/de.json')),id='bio_3_wassertiere_entwicklung',dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-aquatic-order]'),slots=[...zone.querySelectorAll('select')],check=zone.querySelector('[data-aquatic-check]'),reset=zone.querySelector('[data-aquatic-reset]'),out=zone.querySelector('[data-aquatic-feedback]'),store=JSON.stringify(w.localStorage);
 check.click();assert.match(out.textContent,/jeden der vier/);
 let choices=0,correct=0;const expected=['eggs','larva','froglet','adult'];
 for(const order of permutations(expected)){
  slots.forEach((s,i)=>{s.value=order[i];s.dispatchEvent(new w.Event('change'));assert.match(out.textContent,/Auswahl geändert/);assert.equal(out.querySelectorAll('li').length,0);});check.focus();check.click();const matched=order.filter((v,i)=>v===expected[i]).length;assert.equal(out.textContent.startsWith('Alle vier'),matched===4);if(matched<4)assert.match(out.textContent,new RegExp(matched+' von 4'));else correct++;assert.equal(out.querySelectorAll('li').length,4);assert.deepEqual([...out.querySelectorAll('li')].map(li=>li.textContent.startsWith('Passt.')),order.map((v,i)=>v===expected[i]));assert.match(out.textContent,/nächste Generation/);assert.equal(d.activeElement,check);choices++;
 }
 assert.equal(correct,1);slots.forEach(s=>s.value='eggs');check.click();assert.match(out.textContent,/doppelt/);assert.equal(out.querySelectorAll('li').length,0);slots[0].value='';check.click();assert.match(out.textContent,/jeden der vier/);reset.click();assert.deepEqual(slots.map(s=>s.value),['','','','']);assert.equal(out.textContent,'');assert.equal(d.activeElement,slots[0]);assert.equal(JSON.stringify(w.localStorage),store);
 assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,10);
 for(const [i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,n)=>d.querySelector(`input[name="chapter_q_${n}"][value="${i===n?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:90);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('[data-aquatic-stage] svg').length,4);assert.equal(d.querySelectorAll('[data-aquatic-solution]').length,4);assert.equal(d.querySelectorAll('.aquatic-observations tbody tr').length,7);assert.equal(d.querySelectorAll('img').length,0);
 const forces=[...d.querySelectorAll('.aquatic-forces tbody tr')].map(r=>[...r.querySelectorAll('td')].map(e=>Number(e.textContent.replace(',','.'))));assert.deepEqual(forces,[[.12,.21],[.13,.19],[.11,.20]]);assert.ok(Math.abs(forces.reduce((s,r)=>s+r[0],0)/3-.12)<1e-12);assert.ok(Math.abs(forces.reduce((s,r)=>s+r[1],0)/3-.20)<1e-12);assert.ok(data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly).every(q=>q.answers.every(a=>a.pts===0)));assert.doesNotMatch(d.body.textContent,/Stell dir eine echte Situation vor/);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('[data-aquatic-paper]').length,1);assert.equal(pd.querySelectorAll('.aquatic-stage svg').length,4);assert.equal(pd.querySelectorAll('.aquatic-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('.aquatic-observations tbody tr').length,7);assert.equal(pd.querySelectorAll('.aquatic-forces tbody tr').length,3);assert.equal(pd.querySelectorAll('#ws-solutions [data-aquatic-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-aquatic-solution]').length,0);paper.window.close();
 console.log(`PASS: ${choices} permutations, missing/duplicate/reset/focus/storage, 30 independently keyed quiz answers, 12 direct tasks, four original diagrams and complete paper data with four separate solutions.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
