'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8'),id='bio_4_menschheitsentwicklung';
const keys={bio_4_mensch_s1:[1,0],bio_4_mensch_d1:[2,0],bio_4_mensch_stammbaum:[0,0],bio_4_mensch_s2:[2,1],bio_4_mensch_d3:[0,1],bio_4_mensch_d2:[1,1],bio_4_mensch_zeit:[1,2],bio_4_mensch_begegnung:[2,2],bio_4_mensch_grenzen:[0,2],bio_4_mensch_s3:[1,3],bio_4_mensch_verhalten:[2,3]};
// Independently specified expected results: times 0, 50, 200, 1000, 3000, 3500 (thousand years ago).
const expected={
 'af-er':{hits:['neither','neither','second','second','first','first'],overlap:['none','none']},
 'af-ne':{hits:['neither','second','second','neither','first','first'],overlap:['none','none']},
 'af-sa':{hits:['second','second','second','neither','first','first'],overlap:['none','none']},
 'er-ne':{hits:['neither','second','both','first','neither','neither'],overlap:['400','110']},
 'er-sa':{hits:['second','second','both','first','neither','neither'],overlap:['300','110']},
 'ne-sa':{hits:['second','both','both','neither','neither','neither'],overlap:['300','40']}
};
(async()=>{
 const data=JSON.parse(read('lang/de.json')),dom=new JSDOM(read('topics/template.html'),{url:'https://example.test/topics/template.html?topic='+id,runScripts:'outside-only'}),w=dom.window,d=w.document;
 await new Promise(r=>setImmediate(r));w.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','common','core-learning','renderer'])w.eval(read('js/'+f+'.js'));await w.renderTopic();w.eval(read('js/topics/'+id+'.js'));w.topicInit();w.topicInit();
 const zone=d.querySelector('[data-origins-lab]'),pair=zone.querySelector('[data-origins-pair]'),time=zone.querySelector('[data-origins-time]'),prediction=zone.querySelector('[data-origins-prediction]'),result=zone.querySelector('[role=status]'),check=zone.querySelector('[data-origins-check]'),reset=zone.querySelector('[data-origins-reset]'),storage=JSON.stringify(w.localStorage),change=input=>input.dispatchEvent(new w.Event('change'));
 let decisions=0;for(const[p,e]of Object.entries(expected))for(const[i,t]of ['0','50','200','1000','3000','3500'].entries()){
  pair.value=p;change(pair);time.value=t;change(time);assert.equal(result.textContent,'');assert.equal(prediction.value,'');
  check.click();assert.equal(result.dataset.invalid,'prediction');assert.equal(d.activeElement,prediction);
  for(const guess of ['both','first','second','neither']){prediction.value=guess;change(prediction);assert.equal(result.textContent,'');check.click();assert.equal(result.dataset.actual,e.hits[i]);assert.equal(result.dataset.correct,String(guess===e.hits[i]));assert.equal(d.activeElement,result);assert.deepEqual([result.dataset.overlapOld,result.dataset.overlapYoung],e.overlap);assert.equal(result.querySelectorAll('h4').length,1);assert.match(result.textContent,/weder eine Begegnung.*noch direkte Abstammung/);decisions++;}
 }
 assert.equal(decisions,144);
 // Geometry against hand calculated values for 0..500 ka; marker at 200 ka.
 pair.value='ne-sa';time.value='200';prediction.value='both';check.click();let bars=[...result.querySelectorAll('[data-origins-bar]')];assert.deepEqual(bars.map(e=>[+e.getAttribute('x'),+e.getAttribute('width')].map(n=>Math.round(n))),[[82,187],[134,156]]);assert.equal(result.querySelector('[data-origins-marker]').getAttribute('d'),'M186 53V65M186 101V127M186 171V197');assert.match(result.querySelector('figcaption').textContent,/500[.\s]000/);
 // Full range 0..4000 ka, including the much older fossil interval.
 pair.value='af-er';time.value='3500';prediction.value='first';check.click();bars=[...result.querySelectorAll('[data-origins-bar]')];assert.deepEqual(bars.map(e=>[+e.getAttribute('x'),+e.getAttribute('width')].map(n=>Math.round(n*100)/100)),[[39.75,58.5],[167.15,115.7]]);
 for(const[input,key]of [[pair,'pair'],[time,'time'],[prediction,'prediction']]){reset.click();input.value='';change(input);check.click();assert.equal(result.dataset.invalid,key);assert.equal(d.activeElement,input);}
 reset.click();assert.equal(pair.value,'ne-sa');assert.equal(time.value,'200');assert.equal(prediction.value,'');assert.equal(result.textContent,'');assert.equal(d.activeElement,pair);assert.equal(JSON.stringify(w.localStorage),storage);
 const authored=new JSDOM(data[id].sections.map(s=>s.content).join('')).window.document;assert.equal(d.querySelectorAll('.bio-training-card').length,12);assert.deepEqual([...d.querySelectorAll('.bio-training-card')].map(e=>e.textContent),[...authored.querySelectorAll('.bio-training-card')].map(e=>e.textContent));assert.equal(d.querySelectorAll('.bio-vocab-item').length,16);assert.equal(d.querySelectorAll('svg[data-worksheet-static]').length,1);assert.equal(w.chapterRevision(id),2);assert.equal(w.currentChapterResult(id,{contentRevision:1,passed:true}).outdated,true);
 assert.deepEqual([...d.querySelectorAll('.origins-times tbody tr')].map(e=>[...e.children].map(c=>c.textContent)),[['Australopithecus afarensis','3.850.000','2.950.000'],['Homo erectus','1.890.000','110.000'],['Homo neanderthalensis','400.000','40.000'],['Homo sapiens','300.000','0 (heute)']]);
 const qs=w.currentChapterQuiz.questions;assert.equal(qs.length,11);assert.deepEqual(new Set(qs.map(q=>q.id)),new Set(Object.keys(keys)));for(const[i,q]of qs.entries()){assert.equal(q.answers.findIndex(a=>a.correct),keys[q.id][0]);assert.equal(q.sectionIndex,keys[q.id][1]);for(let choice=0;choice<3;choice++){w.restartChapterQuiz();qs.forEach((item,k)=>d.querySelector(`input[name="chapter_q_${k}"][value="${i===k?choice:keys[item.id][0]}"]`).checked=true);w.submitChapterQuiz();const r=JSON.parse(w.localStorage.getItem('sciverse_chapter_quiz_results'))[id];assert.equal(r.lastPercent,choice===keys[q.id][0]?100:91);assert.deepEqual(r.reviewQuestionIds,choice===keys[q.id][0]?[]:[q.id]);assert.ok(d.querySelector('#chapter-quiz-result').textContent.includes(q.answers[choice].feedback));}}
 const practice=data[id].sections.flatMap(s=>s.quizzes).filter(q=>q.practiceOnly);assert.equal(practice.length,1);assert.equal(practice[0].answers.findIndex(a=>a.correct),0);assert.ok(practice[0].answers.every(a=>a.pts===0));const before=JSON.stringify(w.localStorage);w.playSuccessSound=()=>{};for(const answer of practice[0].answers){const button=[...d.querySelectorAll('.practice-box .practice-option')].find(e=>e.textContent===answer.text);assert.ok(button);w.handlePracticeAnswer(button,answer.correct,button.dataset.feedback);assert.ok(button.closest('.practice-box').querySelector('.feedback').innerText.includes(answer.feedback));assert.equal(button.disabled,false);}assert.equal(JSON.stringify(w.localStorage),before);dom.window.close();
 const paper=new JSDOM(read('topics/worksheet.html'),{url:'https://example.test/topics/worksheet.html?topic='+id,runScripts:'outside-only'}),pw=paper.window,pd=pw.document;pw.fetch=async()=>({ok:true,json:async()=>data});for(const f of ['curriculum','chapter-revisions','worksheet_generator','worksheet'])pw.eval(read('js/'+f+'.js'));await new Promise(r=>setImmediate(r));assert.equal(pd.querySelectorAll('.origins-paper').length,1);assert.equal(pd.querySelectorAll('#ws-solutions [data-origins-solution]').length,4);assert.equal(pd.querySelectorAll('#ws-biology-material [data-origins-solution]').length,0);assert.equal(pd.querySelectorAll('#ws-biology-material input,#ws-biology-material select').length,0);assert.equal(pd.querySelectorAll('.origins-vocab .ws-glossary-entry').length,16);assert.equal(pd.querySelectorAll('svg[data-worksheet-static]').length,1);assert.doesNotMatch(pd.body.textContent,/undefined/);assert.match(pd.querySelector('[data-origins-solution="2"]').textContent,/290.000.*190.000.*260.000/);
 for(const s of data[id].sources){assert.ok(s.title&&s.url.startsWith('https://'));assert.ok(pd.body.textContent.includes(s.title));}paper.window.close();
 console.log('PASS: 144 independent predictions; interval and chart geometry; invalid/reset/focus/storage; 33 graded and 3 practice paths; authored tasks, terms, paper cases and solutions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
